#!/usr/bin/env python3
"""Cross-checks Grammaticon's declined nouns against Collatinus data.

Same approach as verify_collatinus.py (whose parsers it reuses): Collatinus
(GPL-3.0, Yves Ouvrard / Biblissima) is a development-time oracle only; the
forms it predicts for our noun lexicon are compared with the forms exported by
`dart run tool/export_nouns.dart` and a report is written. Nothing from
Collatinus is embedded in the application. The locative is not produced by
Collatinus and is checked against Allen & Greenough in test/linguistics.

Usage: python3 tool/corpus/verify_collatinus_nouns.py [nouns_export.json]
"""
import json, os, sys
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from verify_collatinus import DATA, OUT, plain, parse_models, parse_lemmes, radical, resolve  # noqa: E402

# Collatinus noun morphos 1–12: nom, voc, acc, gen, dat, abl × sg, pl.
CASES = ['nom', 'voc', 'acc', 'gen', 'dat', 'abl']
MORPHO_TO_SEL = {i + 1: f'{CASES[i]}.sg' for i in range(6)}
MORPHO_TO_SEL.update({i + 7: f'{CASES[i]}.pl' for i in range(6)})

# Our ids -> Collatinus lemma keys when they differ (i/j, u/v are normalised by plain()).
ALIASES = {'iuppiter': 'Iuppiter', 'roma': 'Roma', 'athenae': 'Athenae', 'corinthus': 'Corinthus', 'carthago': 'Carthago', 'meridies': 'meridies'}


def generate_noun(entry, models):
    """-> dict selector -> set(plain surfaces) for a Collatinus noun entry."""
    R, des, abs_ = resolve(models, entry['model'])
    out = defaultdict(set)
    for m, cells in des.items():
        if m in abs_ or m not in MORPHO_TO_SEL:
            continue
        sel = MORPHO_TO_SEL[m]
        for rad, endings in cells:
            for r in radical(entry, R, rad):
                for e in endings:
                    e = e.strip()
                    # '-' is Collatinus' empty ending (nom. sg. = radical).
                    out[sel].add(r if e == '-' else r + plain(e))
    return out


def main():
    export = sys.argv[1] if len(sys.argv) > 1 else os.path.join(OUT, 'nouns_export.json')
    data = json.load(open(export, encoding='utf-8'))
    models, _ = parse_models()
    lemmes = parse_lemmes()
    totals = defaultdict(int)
    rows = []
    for n in data['nouns']:
        key = plain(ALIASES.get(n['id'], n['lemmaPlain']))
        candidates = lemmes.get(key) or lemmes.get(key + '1') or lemmes.get(key + '2')
        if not candidates:
            rows.append((n['id'], 'absent in Collatinus', 0, 0, 0, [], []))
            totals['missing_lemma'] += 1
            continue
        ours = defaultdict(set)
        for f in n['forms']:
            if f['sel'].startswith('loc.'):
                continue
            ours[f['sel']].add(plain(f['plain']))
        best = None
        for e in candidates:
            if e['model'] not in models:
                continue
            g = generate_noun(e, models)
            score = sum(1 for sel, ss in ours.items() for x in ss if x in g.get(sel, set()))
            if best is None or score > best[0]:
                best = (score, e, g)
        if best is None:
            rows.append((n['id'], 'no noun model', 0, 0, 0, [], []))
            totals['missing_lemma'] += 1
            continue
        _, entry, coll = best
        matched, ours_only, coll_only = 0, [], []
        for sel, surfaces in ours.items():
            for s in surfaces:
                if s in coll.get(sel, set()):
                    matched += 1
                else:
                    ours_only.append((sel, s))
        for sel, surfaces in coll.items():
            for s in surfaces:
                if s not in ours.get(sel, set()):
                    coll_only.append((sel, s))
        totals['matched'] += matched
        totals['ours_only'] += len(ours_only)
        totals['coll_only'] += len(coll_only)
        rows.append((n['id'], entry['model'], matched, len(ours_only), len(coll_only), ours_only, coll_only))

    lines = ['# Collatinus cross-check report — nouns', '', f"Export: `{os.path.basename(export)}` ({data['generatedAt']})", '',
             f"Matched forms: **{totals['matched']}**  ·  in Grammaticon only: **{totals['ours_only']}**  ·  in Collatinus only: **{totals['coll_only']}**  ·  lemmas absent from Collatinus: {totals['missing_lemma']}", '',
             'Locatives are not generated by Collatinus and are checked against Allen & Greenough §427 in `test/linguistics/gold_nouns_test.dart`.', '',
             '| noun | Collatinus model | matched | Grammaticon only | Collatinus only |', '|---|---|---:|---:|---:|']
    for nid, model, m, o, c, _, _ in rows:
        lines.append(f'| {nid} | {model} | {m} | {o} | {c} |')
    lines += ['', '## Details', '']
    for nid, model, m, o, c, ours_only, coll_only in rows:
        if not ours_only and not coll_only:
            continue
        lines.append(f'### {nid} ({model})')
        if ours_only:
            lines.append('Grammaticon only:')
            lines += [f'- `{sel}` {s}' for sel, s in sorted(ours_only)]
        if coll_only:
            lines.append('Collatinus only:')
            lines += [f'- `{sel}` {s}' for sel, s in sorted(coll_only)]
        lines.append('')
    os.makedirs(OUT, exist_ok=True)
    rp = os.path.join(OUT, 'collatinus_nouns_report.md')
    open(rp, 'w', encoding='utf-8').write('\n'.join(lines))
    print('\n'.join(lines[:6]))
    print(f'report: {rp}')
    for nid, model, m, o, c, _, _ in rows:
        if o or c or m == 0:
            print(f'{nid:12s} {model:14s} ok={m:3d} ours_only={o:3d} coll_only={c:3d}')


if __name__ == '__main__':
    main()
