# sheet_005 → batch_005
ITEMS = [
    Q('th-modus-subiunctivus', 'LEV 16:19',
      target=('sanctificet', 'v:subj.praes.act.3.sg'),
      paed=True, fr="et, faisant l’aspersion avec son doigt sept fois, qu’il le purifie et qu’il le sanctifie des impuretés des enfants d’Israël.",
      dist=[
        ("et, faisant l’aspersion avec son doigt sept fois, qu’il le purifie et qu’ils le sanctifient des impuretés des enfants d’Israël.", 'sanctificet', 'numerus', 'v:subj.praes.act.3.pl', "plusieurs officiants sanctifient"),
        ("et, faisant l’aspersion avec son doigt sept fois, qu’il le purifie et que tu le sanctifies des impuretés des enfants d’Israël.", 'sanctificet', 'persona', 'v:subj.praes.act.2.sg', "la sanctification est confiée à l’interlocuteur"),
        ("et, faisant l’aspersion avec son doigt sept fois, qu’il le purifie et qu’il le sanctifie des impuretés de l’enfant d’Israël.", 'filiorum', 'numerus', 'n:gen.pl>n:gen.sg', "un seul enfant d’Israël"),
      ],
      note="Segond rend les subjonctifs de prescription par des futurs (« il le purifiera et le sanctifiera ») ; rendu pédagogique."),
    Q('th-tempus-futurum', '2TI 3:2',
      target=('erunt', 'v:ind.fut.act.3.pl'),
      gloss={'elati': 'orgueilleux, enflé d’orgueil'},
      dist=[
        ("Car les hommes sont égoïstes, amis de l’argent, fanfarons, hautains, blasphémateurs, rebelles à leurs parents, ingrats, irréligieux,", 'erunt', 'tempus', 'v:ind.praes.act.3.pl', "la corruption est actuelle et non annoncée"),
        ("Car les hommes ont été égoïstes, amis de l’argent, fanfarons, hautains, blasphémateurs, rebelles à leurs parents, ingrats, irréligieux,", 'erunt', 'tempus', 'v:ind.perf.act.3.pl', "la corruption est un fait passé"),
        ("Car les hommes étaient égoïstes, amis de l’argent, fanfarons, hautains, blasphémateurs, rebelles à leurs parents, ingrats, irréligieux,", 'erunt', 'tempus', 'v:ind.imperf.act.3.pl', "la corruption est un état passé"),
      ],
      note="Segond rend « seipsos amantes » par « égoïstes » et « cupidi » par « amis de l’argent »."),
    Q('th-tempus-futurum', 'LEV 19:9',
      target=('colliges', 'v:ind.fut.act.2.sg'),
      dist=[
        ("Quand vous ferez la moisson dans votre pays, tu laisseras un coin de ton champ sans le moissonner, et tu ne ramasses pas ce qui reste à glaner.", 'colliges', 'tempus', 'v:ind.praes.act.2.sg', "la règle devient un constat présent"),
        ("Quand vous ferez la moisson dans votre pays, tu laisseras un coin de ton champ sans le moissonner, et tu n’as pas ramassé ce qui reste à glaner.", 'colliges', 'tempus', 'v:ind.perf.act.2.sg', "la règle devient un fait passé"),
        ("Quand vous ferez la moisson dans votre pays, tu laisseras un coin de ton champ sans le moissonner, et vous ne ramasserez pas ce qui reste à glaner.", 'colliges', 'numerus', 'v:ind.fut.act.2.pl', "la règle s’adresse à plusieurs personnes"),
      ],
      note="Segond a « vous ferez la moisson » pour « messueris » (2e sg) et paraphrase « non tondebis usque ad solum superficiem terræ »."),
    Q('th-tempus-futurum', 'WIS 5:22',
      target=('Ibunt', 'v:ind.fut.act.3.pl'),
      paed=True, fr="Les traits des éclairs iront droit au but ; comme d’un arc de nuées bien tendu ils seront lancés, et ils bondiront vers un lieu déterminé.",
      dist=[
        ("Les traits des éclairs vont droit au but ; comme d’un arc de nuées bien tendu ils seront lancés, et ils bondiront vers un lieu déterminé.", 'Ibunt', 'tempus', 'v:ind.praes.act.3.pl', "la course des éclairs est actuelle"),
        ("Les traits des éclairs sont allés droit au but ; comme d’un arc de nuées bien tendu ils seront lancés, et ils bondiront vers un lieu déterminé.", 'Ibunt', 'tempus', 'v:ind.perf.act.3.pl', "la course des éclairs est un fait passé"),
        ("Les traits de l’éclair iront droit au but ; comme d’un arc de nuées bien tendu ils seront lancés, et ils bondiront vers un lieu déterminé.", 'fulgurum', 'numerus', 'n:gen.pl>n:gen.sg', "un seul éclair"),
      ],
      note="Livre absent de Segond ; rendu pédagogique."),
    Q('th-numerus', '1SA 13:21',
      target=('erant', 'v:ind.imperf.act.3.pl'),
      paed=True, fr="Ainsi les tranchants des socs, des hoyaux, des tridents et des haches étaient émoussés, jusqu’à l’aiguillon qu’il fallait redresser.",
      dist=[
        ("Ainsi le tranchant des socs, des hoyaux, des tridents et des haches était émoussé, jusqu’à l’aiguillon qu’il fallait redresser.", 'erant', 'numerus', 'v:ind.imperf.act.3.sg', "un seul tranchant"),
        ("Ainsi les tranchants des socs, des hoyaux, des tridents et de la hache étaient émoussés, jusqu’à l’aiguillon qu’il fallait redresser.", 'securium', 'numerus', 'n:gen.pl>n:gen.sg', "une seule hache"),
        ("Ainsi les tranchants du soc, des hoyaux, des tridents et des haches étaient émoussés, jusqu’à l’aiguillon qu’il fallait redresser.", 'vomerum', 'numerus', 'n:gen.pl>n:gen.sg', "un seul soc"),
      ],
      note="Segond (« le tranchant … était émoussé », « les aiguillons ») change les nombres ; rendu pédagogique."),
    Q('th-nonfinita', 'ISA 1:6',
      target=('fota', 'v:part.perf.pass.nom.sg.f'),
      paed=True, fr="De la plante du pied jusqu’au sommet de la tête, il n’y a en lui rien de sain : blessure, meurtrissure et plaie enflée, qui n’a été ni bandée, ni soignée par un remède, ni adoucie par l’huile.",
      dist=[
        ("De la plante du pied jusqu’au sommet de la tête, il n’y a en lui rien de sain : blessure, meurtrissure et plaies enflées, qui n’ont été ni bandées, ni soignées par un remède, ni adoucies par l’huile.", 'fota', 'numerus', 'v:part.perf.pass.nom.pl.f', "plusieurs plaies"),
        ("De la plante du pied jusqu’au sommet de la tête, il n’y a en lui rien de sain : blessure, meurtrissure et plaie enflée, qui n’a été ni bandée, ni soignée par un remède, ni adoucie par les huiles.", 'oleo', 'numerus', 'n:abl.sg>n:abl.pl', "plusieurs huiles"),
        ("De la plante des pieds jusqu’au sommet de la tête, il n’y a en lui rien de sain : blessure, meurtrissure et plaie enflée, qui n’a été ni bandée, ni soignée par un remède, ni adoucie par l’huile.", 'pedis', 'numerus', 'n:gen.sg>n:gen.pl', "les deux pieds"),
      ],
      note="Segond met les plaies au pluriel (« plaies vives, Qui n’ont été ni pansées ») ; rendu pédagogique gardant le singulier latin."),
    Q('th-tempus-praeteritum', 'ISA 57:9',
      target=('Misisti', 'v:ind.perf.act.2.sg'),
      paed=True, fr="Et tu t’es parée pour le roi avec un parfum, et tu as multiplié tes aromates. Tu as envoyé au loin tes messagers, et tu t’es abaissée jusqu’aux enfers.",
      dist=[
        ("Et tu t’es parée pour le roi avec un parfum, et tu as multiplié tes aromates. Tu envoies au loin tes messagers, et tu t’es abaissée jusqu’aux enfers.", 'Misisti', 'tempus', 'v:ind.praes.act.2.sg', "l’envoi des messagers est actuel"),
        ("Et tu t’es parée pour le roi avec un parfum, et tu as multiplié tes aromates. Tu enverras au loin tes messagers, et tu t’es abaissée jusqu’aux enfers.", 'Misisti', 'tempus', 'v:ind.fut.act.2.sg', "l’envoi des messagers est annoncé"),
        ("Et tu t’es parée pour le roi avec un parfum, et tu as multiplié tes aromates. Elle a envoyé au loin ses messagers, et tu t’es abaissée jusqu’aux enfers.", 'Misisti', 'persona', 'v:ind.perf.act.3.sg', "l’envoi est attribué à une tierce personne"),
      ],
      note="Segond a le présent partout (« Tu vas », « Tu envoies ») ; rendu pédagogique des parfaits."),
    Q('th-tempus-praeteritum', 'PRO 28:25',
      target=('concitat', 'v:ind.praes.act.3.sg'),
      dist=[
        ("L’orgueilleux a excité les querelles, Mais celui qui se confie en l’Éternel est rassasié.", 'concitat', 'tempus', 'v:ind.perf.act.3.sg', "une vérité générale devient un fait passé"),
        ("L’orgueilleux excitera les querelles, Mais celui qui se confie en l’Éternel est rassasié.", 'concitat', 'tempus', 'v:ind.fut.act.3.sg', "une vérité générale devient une prédiction"),
        ("L’orgueilleux excite la querelle, Mais celui qui se confie en l’Éternel est rassasié.", 'jurgia', 'numerus', 'n:acc.pl>n:acc.sg', "une seule querelle"),
      ],
      note="Segond a « L’orgueilleux » pour « Qui se jactat et dilatat » et « est rassasié » (hébreu) pour « sanabitur » ; la cible est concitat."),
    Q('th-tempus-praeteritum', 'GEN 48:10',
      target=('poterat', 'v:ind.imperf.act.3.sg'),
      dist=[
        ("Les yeux d’Israël étaient appesantis par la vieillesse; il ne peut plus voir. Joseph les fit approcher de lui; et Israël leur donna un baiser, et les embrassa.", 'poterat', 'tempus', 'v:ind.praes.act.3.sg', "la cécité est actuelle"),
        ("Les yeux d’Israël étaient appesantis par la vieillesse; il ne put plus voir. Joseph les fit approcher de lui; et Israël leur donna un baiser, et les embrassa.", 'poterat', 'tempus', 'v:ind.perf.act.3.sg', "un état qui dure devient un fait ponctuel"),
        ("L’œil d’Israël était appesanti par la vieillesse; il ne pouvait plus voir. Joseph les fit approcher de lui; et Israël leur donna un baiser, et les embrassa.", 'Oculi', 'numerus', 'n:nom.pl>n:nom.sg', "un seul œil"),
      ],
      note="Segond explicite « Joseph » et « Israël » et rend « caligabant præ nimia senectute » par « étaient appesantis par la vieillesse »."),
    Q('th-tempus-praeteritum', 'JER 52:19',
      target=('tulit', 'v:ind.perf.act.3.sg'),
      gloss={'cyathos': 'coupes, gobelets'},
      dist=[
        ("Le chef des gardes prend encore les bassins, les brasiers, les coupes, les cendriers, les chandeliers, les tasses et les calices, ce qui était d’or et ce qui était d’argent.", 'tulit', 'tempus', 'v:ind.praes.act.3.sg', "le pillage est présenté comme actuel"),
        ("Le chef des gardes prendra encore les bassins, les brasiers, les coupes, les cendriers, les chandeliers, les tasses et les calices, ce qui était d’or et ce qui était d’argent.", 'tulit', 'tempus', 'v:ind.fut.act.3.sg', "le pillage est annoncé"),
        ("Le chef des gardes prit encore les bassins, les brasiers, les coupes, les cendriers, le chandelier, les tasses et les calices, ce qui était d’or et ce qui était d’argent.", 'candelabra', 'numerus', 'n:acc.pl>n:acc.sg', "un seul chandelier"),
      ],
      note="Segond rend « magister militiæ » par « Le chef des gardes » et « quotquot aurea, aurea » par « ce qui était d’or »."),
    Q('th-persona', 'NUM 29:17',
      target=('offeretis', 'v:ind.fut.act.2.pl'),
      dist=[
        ("Le second jour, ils offriront douze jeunes taureaux, deux béliers, et quatorze agneaux d’un an sans défaut,", 'offeretis', 'persona', 'v:ind.fut.act.3.pl', "l’offrande incombe à des tiers"),
        ("Le second jour, tu offriras douze jeunes taureaux, deux béliers, et quatorze agneaux d’un an sans défaut,", 'offeretis', 'numerus', 'v:ind.fut.act.2.sg', "un seul offrant"),
        ("Le second jour, nous offrirons douze jeunes taureaux, deux béliers, et quatorze agneaux d’un an sans défaut,", 'offeretis', 'persona', 'v:ind.fut.act.1.pl', "celui qui parle s’inclut parmi les offrants"),
      ],
      note="Segond ne rend pas « de armento »."),
    Q('th-tempus-praeteritum', '1CH 26:14',
      target=('Cecidit', 'v:ind.perf.act.3.sg'),
      gloss={'Selemiæ': 'Schélémia'},
      dist=[
        ("Le sort échoit à Schélémia pour le côté de l’orient. On tira au sort pour Zacharie, son fils, qui était un sage conseiller, et le côté du septentrion lui échut par le sort.", 'Cecidit', 'tempus', 'v:ind.praes.act.3.sg', "le tirage au sort est actuel"),
        ("Le sort échoira à Schélémia pour le côté de l’orient. On tira au sort pour Zacharie, son fils, qui était un sage conseiller, et le côté du septentrion lui échut par le sort.", 'Cecidit', 'tempus', 'v:ind.fut.act.3.sg', "le tirage au sort est annoncé"),
        ("Les sorts échurent à Schélémia pour le côté de l’orient. On tira au sort pour Zacharie, son fils, qui était un sage conseiller, et le côté du septentrion lui échut par le sort.", 'sors', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs sorts"),
      ],
      note="Segond paraphrase la seconde phrase (« On tira au sort pour Zacharie … lui échut par le sort »)."),
    Q('th-numerus', 'COL 2:15',
      target=('traduxit', 'v:ind.perf.act.3.sg'),
      dist=[
        ("ils ont dépouillé les dominations et les autorités, et les ont livrées publiquement en spectacle, en triomphant d’elles par la croix.", 'traduxit', 'numerus', 'v:ind.perf.act.3.pl', "plusieurs vainqueurs au lieu du Christ seul"),
        ("il a dépouillé les dominations et l’autorité, et les a livrées publiquement en spectacle, en triomphant d’elles par la croix.", 'potestates', 'numerus', 'n:acc.pl>n:acc.sg', "une seule autorité"),
        ("il a dépouillé la domination et les autorités, et les a livrées publiquement en spectacle, en triomphant d’elles par la croix.", 'principatus', 'numerus', 'n:acc.pl>n:acc.sg', "une seule domination"),
      ],
      note="Segond a « par la croix » (variante) pour « in semetipso »."),
    Q('th-modus-subiunctivus', 'PHI 2:15',
      target=('sitis', 'v:subj.praes.act.2.pl'),
      dist=[
        ("afin qu’ils soient irréprochables et purs, des enfants de Dieu irrépréhensibles au milieu d’une génération perverse et corrompue, parmi laquelle vous brillez comme des flambeaux dans le monde,", 'sitis', 'persona', 'v:subj.praes.act.3.pl', "l’exhortation vise des tiers"),
        ("afin que vous fussiez irréprochables et purs, des enfants de Dieu irrépréhensibles au milieu d’une génération perverse et corrompue, parmi laquelle vous brillez comme des flambeaux dans le monde,", 'sitis', 'tempus', 'v:subj.imperf.act.2.pl', "la finalité est rejetée dans le passé"),
        ("afin que vous soyez irréprochables et purs, des enfants de Dieu irrépréhensibles au milieu d’une génération perverse et corrompue, parmi laquelle vous brillez comme un flambeau dans le monde,", 'luminaria', 'numerus', 'n:nom.pl>n:nom.sg', "un seul flambeau"),
      ],
      note="Segond rend « sine querela, et simplices » par « irréprochables et purs »."),
    Q('th-tempus-futurum', 'JOB 41:20',
      target=('deridebit', 'v:ind.fut.act.3.sg'),
      paed=True, fr="Il estimera la massue comme un brin de paille, et il se rira de la lance qui vibre.",
      dist=[
        ("Il estimera la massue comme un brin de paille, et il se rit de la lance qui vibre.", 'deridebit', 'tempus', 'v:ind.praes.act.3.sg', "la moquerie est actuelle"),
        ("Il estimera la massue comme un brin de paille, et il s’est ri de la lance qui vibre.", 'deridebit', 'tempus', 'v:ind.perf.act.3.sg', "la moquerie est un fait passé"),
        ("Il estimera la massue comme un brin de paille, et il se rira des lances qui vibrent.", 'hastam', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs lances"),
      ],
      note="Segond a le présent et « des dards » au pluriel ; rendu pédagogique des futurs."),
    Q('th-tempus-praeteritum', 'LAM 4:3',
      target=('lactaverunt', 'v:ind.perf.act.3.pl'),
      paed=True, fr="Même les lamies ont découvert leur mamelle, elles ont allaité leurs petits ; la fille de mon peuple est cruelle comme l’autruche au désert.",
      gloss={'Ghimel': 'guimel (lettre hébraïque)'},
      dist=[
        ("Même les lamies ont découvert leur mamelle, elles allaitent leurs petits ; la fille de mon peuple est cruelle comme l’autruche au désert.", 'lactaverunt', 'tempus', 'v:ind.praes.act.3.pl', "l’allaitement est actuel"),
        ("Même les lamies ont découvert leur mamelle, elles allaiteront leurs petits ; la fille de mon peuple est cruelle comme l’autruche au désert.", 'lactaverunt', 'tempus', 'v:ind.fut.act.3.pl', "l’allaitement est annoncé"),
        ("Même les lamies ont découvert leur mamelle, elles ont allaité leur petit ; la fille de mon peuple est cruelle comme l’autruche au désert.", 'catulos', 'numerus', 'n:acc.pl>n:acc.sg', "un seul petit"),
      ],
      note="Segond a le présent (« présentent », « allaitent ») et « Les chacals » pour « lamiæ » ; rendu pédagogique des parfaits."),
    Q('th-tempus-praeteritum', 'ECC 3:19',
      target=('moriuntur', 'v:ind.praes.act.3.pl'),
      la='Sicut moritur homo, sic et illa moriuntur.',
      paed=True, fr="Comme meurt l’homme, ainsi meurent aussi les bêtes.",
      dist=[
        ("Comme meurt l’homme, ainsi mouraient aussi les bêtes.", 'moriuntur', 'tempus', 'v:ind.imperf.act.3.pl', "une vérité générale devient un état passé"),
        ("Comme meurt l’homme, ainsi mourront aussi les bêtes.", 'moriuntur', 'tempus', 'v:ind.fut.act.3.pl', "une vérité générale devient une prédiction"),
        ("Comme meurt l’homme, ainsi meurt aussi la bête.", 'moriuntur', 'numerus', 'v:ind.praes.act.3.sg', "une seule bête"),
      ],
      note="Segond (« comme meurt l’un, ainsi meurt l’autre ») met les deux verbes au singulier ; rendu pédagogique de la phrase centrale."),
    Q('th-tempus-praeteritum', 'LUK 22:1',
      target=('Appropinquabat', 'v:ind.imperf.act.3.sg'),
      dist=[
        ("La fête des pains sans levain, appelée la Pâque, approche.", 'Appropinquabat', 'tempus', 'v:ind.praes.act.3.sg', "l’approche de la fête est actuelle"),
        ("La fête des pains sans levain, appelée la Pâque, approcha.", 'Appropinquabat', 'tempus', 'v:ind.perf.act.3.sg', "une approche progressive devient un fait ponctuel"),
        ("La fête des pains sans levain, appelée la Pâque, approchera.", 'Appropinquabat', 'tempus', 'v:ind.fut.act.3.sg', "l’approche de la fête est annoncée"),
      ],
      note="Segond rend « qui dicitur » par « appelée » et « dies festus » par « La fête »."),
    Q('th-tempus-praeteritum', 'RUT 4:16',
      target=('posuit', 'v:ind.perf.act.3.sg'),
      dist=[
        ("Naomi prit l’enfant et le met sur son sein, et elle fut sa garde.", 'posuit', 'tempus', 'v:ind.praes.act.3.sg', "le geste est présenté comme actuel"),
        ("Naomi prit l’enfant et le mettra sur son sein, et elle fut sa garde.", 'posuit', 'tempus', 'v:ind.fut.act.3.sg', "le geste est annoncé"),
        ("Naomi prit l’enfant et le mettait sur son sein, et elle fut sa garde.", 'posuit', 'tempus', 'v:ind.imperf.act.3.sg', "un geste ponctuel devient une habitude"),
      ],
      note="Segond rend le participe « Susceptum » par « prit » et « nutricis ac gerulæ fungebatur officio » par « elle fut sa garde »."),
    Q('th-persona', '2CO 6:1',
      target=('exhortamur', 'v:ind.praes.act.1.pl'),
      dist=[
        ("Puisque nous travaillons avec Dieu, ils vous exhortent à ne pas recevoir la grâce de Dieu en vain.", 'exhortamur', 'persona', 'v:ind.praes.act.3.pl', "l’exhortation vient de tiers et non de l’apôtre"),
        ("Puisque nous travaillons avec Dieu, je vous exhorte à ne pas recevoir la grâce de Dieu en vain.", 'exhortamur', 'numerus', 'v:ind.praes.act.1.sg', "l’apôtre parle seul"),
        ("Puisque nous travaillons avec Dieu, nous t’exhortons à ne pas recevoir la grâce de Dieu en vain.", 'recipiatis', 'numerus', 'v:subj.praes.act.2.pl>v:subj.praes.act.2.sg', "un seul destinataire"),
      ],
      note="Segond rend le participe « Adjuvantes » par « Puisque nous travaillons avec Dieu »."),
    Q('th-tempus-futurum', 'PSA 59:10',
      target=('extendam', 'v:ind.fut.act.1.sg'),
      paed=True, fr="Moab est le bassin de mon espérance. Sur l’Idumée j’étendrai ma chaussure : les étrangers me sont soumis.",
      dist=[
        ("Moab est le bassin de mon espérance. Sur l’Idumée j’étends ma chaussure : les étrangers me sont soumis.", 'extendam', 'tempus', 'v:ind.praes.act.1.sg', "la prise de possession est actuelle"),
        ("Moab est le bassin de mon espérance. Sur l’Idumée j’ai étendu ma chaussure : les étrangers me sont soumis.", 'extendam', 'tempus', 'v:ind.perf.act.1.sg', "la prise de possession est un fait passé"),
        ("Moab est le bassin de mon espérance. Sur l’Idumée il étendra sa chaussure : les étrangers me sont soumis.", 'extendam', 'persona', 'v:ind.fut.act.3.sg', "un autre que le locuteur prend possession"),
      ],
      note="Segond (60:10) suit l’hébreu (« le bassin où je me lave », « Édom », « Pays des Philistins ») ; la Vulgate suit la LXX ; rendu pédagogique."),
    Q('th-modus-subiunctivus', 'WIS 13:11',
      target=('fabricet', 'v:subj.praes.act.3.sg'),
      paed=True, fr="Ou bien si quelque artisan charpentier a coupé dans la forêt un bois droit, en racle habilement toute l’écorce et, usant de son art, fabrique avec soin un ustensile utile aux usages de la vie ;",
      dist=[
        ("Ou bien si quelque artisan charpentier a coupé dans la forêt un bois droit, en racle habilement toute l’écorce et, usant de son art, fabriquait avec soin un ustensile utile aux usages de la vie ;", 'fabricet', 'tempus', 'v:subj.imperf.act.3.sg', "l’hypothèse est rejetée dans le passé"),
        ("Ou bien si quelque artisan charpentier a coupé dans la forêt un bois droit, en racle habilement toute l’écorce et, usant de son art, fabrique avec soin des ustensiles utiles aux usages de la vie ;", 'vas', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs ustensiles"),
        ("Ou bien si quelque artisan charpentier a coupé dans la forêt un bois droit, en racle habilement toutes les écorces et, usant de son art, fabrique avec soin un ustensile utile aux usages de la vie ;", 'corticem', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs écorces"),
      ],
      note="Livre absent de Segond ; rendu pédagogique (les subjonctifs de l’hypothèse sont rendus par l’indicatif français)."),
    Q('th-modus-subiunctivus', 'MAT 14:7',
      target=('postulasset', 'v:subj.plusq.act.3.sg'),
      dist=[
        ("de sorte qu’il promit avec serment de lui donner ce qu’elle demandait.", 'postulasset', 'tempus', 'v:subj.imperf.act.3.sg', "la demande n’est plus à venir par rapport à la promesse"),
        ("de sorte qu’il promit avec serment de lui donner ce qu’ils demanderaient.", 'postulasset', 'numerus', 'v:subj.plusq.act.3.pl', "plusieurs demandeurs"),
        ("de sorte qu’il promit avec serment de lui donner ce que tu demanderais.", 'postulasset', 'persona', 'v:subj.plusq.act.2.sg', "la demande est attribuée à l’interlocuteur"),
      ],
      note="Le plus-que-parfait du subjonctif (futur du passé au discours indirect) est rendu par le conditionnel « demanderait »."),
    Q('th-tempus-praeteritum', 'EXO 2:3',
      target=('sumpsit', 'v:ind.perf.act.3.sg'),
      gloss={'linivit': 'enduire'},
      dist=[
        ("Ne pouvant plus le cacher, elle prend une caisse de jonc, qu’elle enduisit de bitume et de poix; elle y mit l’enfant, et le déposa parmi les roseaux, sur le bord du fleuve.", 'sumpsit', 'tempus', 'v:ind.praes.act.3.sg', "le geste est présenté comme actuel"),
        ("Ne pouvant plus le cacher, elle prendra une caisse de jonc, qu’elle enduisit de bitume et de poix; elle y mit l’enfant, et le déposa parmi les roseaux, sur le bord du fleuve.", 'sumpsit', 'tempus', 'v:ind.fut.act.3.sg', "le geste est annoncé"),
        ("Ne pouvant plus le cacher, elle prenait une caisse de jonc, qu’elle enduisit de bitume et de poix; elle y mit l’enfant, et le déposa parmi les roseaux, sur le bord du fleuve.", 'sumpsit', 'tempus', 'v:ind.imperf.act.3.sg', "un geste ponctuel devient une action qui dure"),
      ],
      note="Segond rend « Cumque jam celare non posset » par « Ne pouvant plus le cacher »."),
    Q('th-modus-subiunctivus', '2CO 5:10',
      target=('referat', 'v:subj.praes.act.3.sg'),
      dist=[
        ("Car il nous faut tous comparaître devant le tribunal de Christ, afin que chacun reçût selon le bien ou le mal qu’il aura fait, étant dans son corps.", 'referat', 'tempus', 'v:subj.imperf.act.3.sg', "la finalité est rejetée dans le passé"),
        ("Car il nous faut tous comparaître devant les tribunaux de Christ, afin que chacun reçoive selon le bien ou le mal qu’il aura fait, étant dans son corps.", 'tribunal', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs tribunaux"),
        ("Car il nous faut tous comparaître devant le tribunal de Christ, afin que chacun reçoive selon le bien ou le mal qu’ils auront fait, étant dans son corps.", 'gessit', 'numerus', 'v:ind.perf.act.3.sg>v:ind.perf.act.3.pl', "les actes jugés sont ceux de tous et non de chacun"),
      ],
      note="Segond rend « referat propria corporis » par « reçoive … étant dans son corps »."),
    Q('th-numerus', 'LAM 4:7',
      target=('Nazaræi', 'a:nom.pl.m'),
      paed=True, fr="Ses nazaréens étaient plus blancs que la neige, plus éclatants que le lait, plus vermeils que l’ivoire antique, plus beaux que le saphir.",
      gloss={'Zain': 'zaïn (lettre hébraïque)'},
      dist=[
        ("Son nazaréen était plus blanc que la neige, plus éclatant que le lait, plus vermeil que l’ivoire antique, plus beau que le saphir.", 'Nazaræi', 'numerus', 'a:nom.sg.m', "un seul nazaréen"),
        ("Ses nazaréens étaient plus blancs que les neiges, plus éclatants que le lait, plus vermeils que l’ivoire antique, plus beaux que le saphir.", 'nive', 'numerus', 'n:abl.sg>n:abl.pl', "plusieurs neiges"),
        ("Leurs nazaréens étaient plus blancs que la neige, plus éclatants que le lait, plus vermeils que l’ivoire antique, plus beaux que le saphir.", 'ejus', 'numerus', 'a:gen.sg.f>a:gen.pl.f', "plusieurs possesseurs au lieu de la seule Jérusalem"),
      ],
      note="Segond (« Ses princes », « que le corail », « comme le saphir ») s’écarte de la Vulgate ; rendu pédagogique."),
    Q('th-numerus', 'JER 52:18',
      target=('tulerunt', 'v:ind.perf.act.3.pl'),
      dist=[
        ("Il prit les cendriers, les pelles, les couteaux, les coupes, les tasses, et tous les ustensiles d’airain avec lesquels on faisait le service.", 'tulerunt', 'numerus', 'v:ind.perf.act.3.sg', "un seul pillard"),
        ("Ils prirent les cendriers, les pelles, les couteaux, la coupe, les tasses, et tous les ustensiles d’airain avec lesquels on faisait le service.", 'phialas', 'numerus', 'n:acc.pl>n:acc.sg', "une seule coupe"),
        ("Ils prirent les cendriers, les pelles, les couteaux, les coupes, les tasses, et tout l’ustensile d’airain avec lequel on faisait le service.", 'vasa', 'numerus', 'n:acc.pl>n:acc.sg', "un seul ustensile"),
      ],
      note="Segond rend « quæ in ministerio fuerant » par « avec lesquels on faisait le service »."),
    Q('th-vox', 'HEB 12:15',
      target=('inquinentur', 'v:subj.praes.pass.3.pl'),
      dist=[
        ("Veillez à ce que nul ne se prive de la grâce de Dieu; à ce qu’aucune racine d’amertume, poussant des rejetons, ne produise du trouble, et que plusieurs n’en infectent d’autres;", 'inquinentur', 'vox', 'v:subj.praes.act.3.pl', "les nombreux deviennent ceux qui infectent"),
        ("Veillez à ce que nul ne se prive de la grâce de Dieu; à ce qu’aucune racine d’amertume, poussant des rejetons, ne produise du trouble, et que plusieurs n’en fussent infectés;", 'inquinentur', 'tempus', 'v:subj.imperf.pass.3.pl', "la crainte est rejetée dans le passé"),
        ("Veillez à ce que nul ne se prive de la grâce de Dieu; à ce qu’aucune racine d’amertume, poussant des rejetons, ne produise du trouble, et que quelqu’un n’en soit infecté;", 'inquinentur', 'numerus', 'v:subj.praes.pass.3.sg', "une seule victime"),
      ],
      note="Segond rend le participe « contemplantes » par l’impératif « Veillez »."),
    Q('th-tempus-futurum', 'JOB 7:14',
      target=('terrebis', 'v:ind.fut.act.2.sg'),
      paed=True, fr="tu m’effraieras par des songes, et par des visions tu me secoueras d’horreur.",
      dist=[
        ("tu m’effraies par des songes, et par des visions tu me secoueras d’horreur.", 'terrebis', 'tempus', 'v:ind.praes.act.2.sg', "l’effroi est actuel"),
        ("tu m’as effrayé par des songes, et par des visions tu me secoueras d’horreur.", 'terrebis', 'tempus', 'v:ind.perf.act.2.sg', "l’effroi est un fait passé"),
        ("il m’effraiera par des songes, et par des visions tu me secoueras d’horreur.", 'terrebis', 'persona', 'v:ind.fut.act.3.sg', "l’effroi n’est plus imputé à Dieu, l’interlocuteur"),
      ],
      note="Segond a le présent (« tu m’effraies », « tu m’épouvantes ») ; rendu pédagogique des futurs."),
    Q('th-modus-imperativus', 'JOS 10:18',
      target=('Volvite', 'v:imp.praes.act.2.pl'),
      dist=[
        ("Josué dit: Vous roulez de grosses pierres à l’entrée de la caverne, et mettez-y des hommes pour les garder.", 'Volvite', 'modus', 'v:ind.praes.act.2.pl', "un ordre devient un constat"),
        ("Josué dit: Roulez une grosse pierre à l’entrée de la caverne, et mettez-y des hommes pour les garder.", 'saxa', 'numerus', 'n:acc.pl>n:acc.sg', "une seule pierre"),
        ("Josué dit: Roulez de grosses pierres à l’entrée de la caverne, et mettez-y un homme pour les garder.", 'viros', 'numerus', 'n:acc.pl>n:acc.sg', "un seul gardien"),
      ],
      note="Segond ne rend pas « præcepit sociis » et résume « viros industrios, qui clausos custodiant » en « des hommes pour les garder »."),
    Q('th-tempus-praeteritum', 'JOS 15:19',
      target=('dedisti', 'v:ind.perf.act.2.sg'),
      gloss={'irriguam': 'arrosée, pourvue d’eau', 'irriguum': 'terrain arrosé, sources'},
      dist=[
        ("Elle répondit: Fais-moi un présent, car tu me donnes une terre du midi; donne-moi aussi des sources d’eau. Et il lui donna les sources supérieures et les sources inférieures.", 'dedisti', 'tempus', 'v:ind.praes.act.2.sg', "le don de la terre est en cours"),
        ("Elle répondit: Fais-moi un présent, car tu me donneras une terre du midi; donne-moi aussi des sources d’eau. Et il lui donna les sources supérieures et les sources inférieures.", 'dedisti', 'tempus', 'v:ind.fut.act.2.sg', "le don de la terre est à venir"),
        ("Elle répondit: Fais-moi un présent, car il m’a donné une terre du midi; donne-moi aussi des sources d’eau. Et il lui donna les sources supérieures et les sources inférieures.", 'dedisti', 'persona', 'v:ind.perf.act.3.sg', "le don passé n’est plus attribué à l’interlocuteur"),
      ],
      note="Segond ne rend pas « et arentem » ni le nom « Caleb » (« il lui donna »)."),
    Q('th-tempus-praeteritum', 'EST 14:1',
      target=('imminebat', 'v:ind.imperf.act.3.sg'),
      paed=True, fr="La reine Esther, elle aussi, se réfugia auprès du Seigneur, redoutant le péril qui la menaçait.",
      dist=[
        ("La reine Esther, elle aussi, se réfugia auprès du Seigneur, redoutant le péril qui la menaça.", 'imminebat', 'tempus', 'v:ind.perf.act.3.sg', "une menace qui pèse devient un fait ponctuel"),
        ("La reine Esther, elle aussi, se réfugia auprès du Seigneur, redoutant le péril qui la menace.", 'imminebat', 'tempus', 'v:ind.praes.act.3.sg', "la menace est actuelle"),
        ("La reine Esther, elle aussi, se réfugia auprès du Seigneur, redoutant le péril qui la menacera.", 'imminebat', 'tempus', 'v:ind.fut.act.3.sg', "la menace est à venir"),
      ],
      note="Passage deutérocanonique absent de Segond ; rendu pédagogique."),
    Q('th-nonfinita', 'NAH 2:3',
      target=('consopiti', 'v:part.perf.pass.nom.pl.m'),
      paed=True, fr="Le bouclier de ses vaillants est enflammé, les hommes de l’armée sont vêtus d’écarlate ; les rênes du char sont de feu au jour de sa préparation, et les conducteurs ont été endormis.",
      dist=[
        ("Le bouclier de ses vaillants est enflammé, les hommes de l’armée sont vêtus d’écarlate ; les rênes du char sont de feu au jour de sa préparation, et le conducteur a été endormi.", 'consopiti', 'numerus', 'v:part.perf.pass.nom.sg.m', "un seul conducteur"),
        ("Le bouclier de ses vaillants est enflammé, les hommes de l’armée sont vêtus d’écarlate ; les rênes du char sont de feu au jour de sa préparation, et les conducteurs ont endormi.", 'consopiti', 'nonfinita', 'v:ind.perf.act.3.pl', "les conducteurs deviennent ceux qui endorment"),
        ("Les boucliers de ses vaillants sont enflammés, les hommes de l’armée sont vêtus d’écarlate ; les rênes du char sont de feu au jour de sa préparation, et les conducteurs ont été endormis.", 'Clypeus', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs boucliers"),
      ],
      note="Segond (2:3 dans sa numérotation) correspond à un autre verset de la Vulgate ; rendu pédagogique."),
    Q('th-tempus-praeteritum', '2PE 2:22',
      target=('Contigit', 'v:ind.perf.act.3.sg'),
      dist=[
        ("Il leur arrive ce que dit un proverbe vrai: Le chien est retourné à ce qu’il avait vomi, et la truie lavée s’est vautrée dans le bourbier.", 'Contigit', 'tempus', 'v:ind.praes.act.3.sg', "la rechute est actuelle"),
        ("Il leur arrivera ce que dit un proverbe vrai: Le chien est retourné à ce qu’il avait vomi, et la truie lavée s’est vautrée dans le bourbier.", 'Contigit', 'tempus', 'v:ind.fut.act.3.sg', "la rechute est annoncée"),
        ("Il lui est arrivé ce que dit un proverbe vrai: Le chien est retourné à ce qu’il avait vomi, et la truie lavée s’est vautrée dans le bourbier.", 'eis', 'numerus', 'a:dat.pl.m>a:dat.sg.m', "une seule personne concernée"),
      ],
      note="Segond rend « illud veri proverbii » par « ce que dit un proverbe vrai » et « lota in volutabro luti » par « lavée s’est vautrée dans le bourbier »."),
    Q('th-tempus-praeteritum', 'GEN 41:18',
      target=('conscendere', 'v:ind.perf.act.3.pl'),
      dist=[
        ("Et voici, sept vaches grasses de chair et belles d’apparence montent hors du fleuve, et se mirent à paître dans la prairie.", 'conscendere', 'tempus', 'v:ind.praes.act.3.pl', "la montée des vaches est présentée comme actuelle"),
        ("Et voici, sept vaches grasses de chair et belles d’apparence monteront hors du fleuve, et se mirent à paître dans la prairie.", 'conscendere', 'tempus', 'v:ind.fut.act.3.pl', "la montée des vaches est annoncée"),
        ("Et voici, sept vaches grasses de chair et belles d’apparence montaient hors du fleuve, et se mirent à paître dans la prairie.", 'conscendere', 'tempus', 'v:ind.imperf.act.3.pl', "un fait ponctuel devient une action qui dure"),
      ],
      note="« conscendere » est la forme syncopée de conscenderunt ; Segond rend « quæ in pastu paludis virecta carpebant » par « se mirent à paître dans la prairie »."),
    Q('th-tempus-futurum', 'ISA 33:21',
      target=('transibit', 'v:ind.fut.act.3.sg'),
      paed=True, fr="car c’est là seulement que notre Seigneur est magnifique : lieu de fleuves, de canaux très larges et ouverts ; le navire à rames n’y passera pas, et la grande trière ne le traversera pas.",
      dist=[
        ("car c’est là seulement que notre Seigneur est magnifique : lieu de fleuves, de canaux très larges et ouverts ; le navire à rames n’y passe pas, et la grande trière ne le traversera pas.", 'transibit', 'tempus', 'v:ind.praes.act.3.sg', "l’interdiction de passage est un constat présent"),
        ("car c’est là seulement que notre Seigneur est magnifique : lieu de fleuves, de canaux très larges et ouverts ; le navire à rames n’y est pas passé, et la grande trière ne le traversera pas.", 'transibit', 'tempus', 'v:ind.perf.act.3.sg', "l’absence de passage est un fait passé"),
        ("car c’est là seulement que notre Seigneur est magnifique : lieu de fleuves, de canaux très larges et ouverts ; les navires à rames n’y passeront pas, et la grande trière ne le traversera pas.", 'navis', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs navires"),
      ],
      note="Segond a le présent (« ne pénètrent point », « ne traverse ») ; rendu pédagogique des futurs."),
    Q('th-numerus', '2SA 17:28',
      target=('obtulerunt', 'v:ind.perf.act.3.pl'),
      dist=[
        ("apporta des lits, des bassins, des vases de terre, du froment, de l’orge, de la farine, du grain rôti, des fèves, des lentilles, des pois rôtis,", 'obtulerunt', 'numerus', 'v:ind.perf.act.3.sg', "un seul donateur"),
        ("apportèrent des lits, des bassins, un vase de terre, du froment, de l’orge, de la farine, du grain rôti, des fèves, des lentilles, des pois rôtis,", 'vasa', 'numerus', 'n:acc.pl>n:acc.sg', "un seul vase"),
        ("apportèrent des lits, des bassins, des vases de terre, du froment, de l’orge, des farines, du grain rôti, des fèves, des lentilles, des pois rôtis,", 'farinam', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs farines"),
      ],
      note="Segond ne rend pas « ei » et met « fèves », « lentilles », « pois » au pluriel pour des singuliers collectifs."),
    Q('th-modus-imperativus', 'ISA 29:9',
      target=('Obstupescite', 'v:imp.praes.act.2.pl'),
      la='Obstupescite et admiramini',
      fr='Soyez stupéfaits et étonnés!',
      dist=[
        ("Vous êtes stupéfaits et étonnés!", 'Obstupescite', 'modus', 'v:ind.praes.act.2.pl', "un ordre devient un constat"),
        ("Sois stupéfait et étonné!", 'Obstupescite', 'numerus', 'v:imp.praes.act.2.sg', "l’ordre s’adresse à une seule personne"),
        ("Puissiez-vous être stupéfaits et étonnés!", 'Obstupescite', 'modus', 'v:subj.praes.act.2.pl', "un ordre devient un souhait"),
      ],
      note="Segond s’écarte de la Vulgate dans la suite du verset (« Ils sont ivres ») ; le passage est réduit aux deux premiers impératifs."),
    Q('th-tempus-praeteritum', 'TIT 1:7',
      target=('Oportet', 'v:ind.praes.act.3.sg'),
      dist=[
        ("Car il a fallu que l’évêque soit irréprochable, comme économe de Dieu; qu’il ne soit ni arrogant, ni colère, ni adonné au vin, ni violent, ni porté à un gain déshonnête;", 'Oportet', 'tempus', 'v:ind.perf.act.3.sg', "une exigence permanente devient une nécessité passée"),
        ("Car il faudra que l’évêque soit irréprochable, comme économe de Dieu; qu’il ne soit ni arrogant, ni colère, ni adonné au vin, ni violent, ni porté à un gain déshonnête;", 'Oportet', 'tempus', 'v:ind.fut.act.3.sg', "l’exigence est reportée à l’avenir"),
        ("Car il fallait que l’évêque soit irréprochable, comme économe de Dieu; qu’il ne soit ni arrogant, ni colère, ni adonné au vin, ni violent, ni porté à un gain déshonnête;", 'Oportet', 'tempus', 'v:ind.imperf.act.3.sg', "l’exigence est rejetée dans le passé"),
      ],
      note="Segond rend l’infinitif « esse » par « soit » et les accusatifs par « qu’il ne soit ni … »."),
    Q('th-tempus-futurum', '1CO 6:10',
      target=('possidebunt', 'v:ind.fut.act.3.pl'),
      la='neque fures, neque avari, neque ebriosi, neque maledici, neque rapaces regnum Dei possidebunt.',
      fr='ni les voleurs, ni les cupides, ni les ivrognes, ni les outrageux, ni les ravisseurs, n’hériteront le royaume de Dieu.',
      dist=[
        ("ni les voleurs, ni les cupides, ni les ivrognes, ni les outrageux, ni les ravisseurs, n’héritent le royaume de Dieu.", 'possidebunt', 'tempus', 'v:ind.praes.act.3.pl', "l’exclusion est un constat présent"),
        ("ni les voleurs, ni les cupides, ni les ivrognes, ni les outrageux, ni les ravisseurs, n’ont hérité le royaume de Dieu.", 'possidebunt', 'tempus', 'v:ind.perf.act.3.pl', "l’exclusion est un fait passé"),
        ("ni les voleurs, ni les cupides, ni les ivrognes, ni les outrageux, ni les ravisseurs, n’hériteront les royaumes de Dieu.", 'regnum', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs royaumes"),
      ],
      note="Segond rend « possidebunt » par « hériteront » ; les deux premiers termes du verset latin (« molles », « concubitores ») sont traduits par Segond au verset 9."),
]
