# sheet_008 → batch_008
# skipped: GEN 46:21 (list of names, no verb)
ITEMS = [
    Q('th-tempus-futurum', 'LEV 23:38',
      target=('offeretis', 'v:ind.fut.act.2.pl'),
      paed=True, fr="outre les sabbats du Seigneur, et vos dons, et ce que vous offrirez par vœu, ou ce que vous donnerez spontanément au Seigneur.",
      dist=[
        ("outre les sabbats du Seigneur, et vos dons, et ce que vous offrez par vœu, ou ce que vous donnerez spontanément au Seigneur.", 'offeretis', 'tempus', 'v:ind.praes.act.2.pl', "l’offrande est présentée comme actuelle"),
        ("outre les sabbats du Seigneur, et vos dons, et ce que vous avez offert par vœu, ou ce que vous donnerez spontanément au Seigneur.", 'offeretis', 'tempus', 'v:ind.perf.act.2.pl', "l’offrande est déjà faite"),
        ("outre les sabbats du Seigneur, et vos dons, et ce que tu offriras par vœu, ou ce que vous donnerez spontanément au Seigneur.", 'offeretis', 'numerus', 'v:ind.fut.act.2.sg', "un seul offrant"),
      ],
      note="Segond (« Vous observerez en outre les sabbats… vous continuerez à faire vos dons ») réorganise le verset et ne rend pas offeretis ; rendu pédagogique."),
    Q('th-tempus-praeteritum', '1CH 21:21',
      target=('adoravit', 'v:ind.perf.act.3.sg'),
      dist=[
        ("Lorsque David arriva auprès d’Ornan, Ornan regarda, et il aperçut David; puis il sortit de l’aire, et se prosterne devant David, le visage contre terre.", 'adoravit', 'tempus', 'v:ind.praes.act.3.sg', "la prosternation est présentée comme en cours"),
        ("Lorsque David arriva auprès d’Ornan, Ornan regarda, et il aperçut David; puis il sortit de l’aire, et se prosternera devant David, le visage contre terre.", 'adoravit', 'tempus', 'v:ind.fut.act.3.sg', "la prosternation est annoncée"),
        ("Lorsque David arriva auprès d’Ornan, Ornan regarda, et il aperçut David; puis il sortait de l’aire, et se prosterna devant David, le visage contre terre.", 'processit', 'tempus', 'v:ind.perf.act.3.sg>v:ind.imperf.act.3.sg', "la sortie devient une action qui dure"),
      ],
      note="Segond dédouble conspexit (« regarda, et il aperçut ») et explicite eum par « David » ; la cible est adoravit."),
    Q('th-tempus-praeteritum', 'JOE 3:15',
      target=('retraxerunt', 'v:ind.perf.act.3.pl'),
      paed=True, fr="Le soleil et la lune se sont obscurcis, et les étoiles ont retiré leur éclat.",
      gloss={'obtenebrati': 'obscurci, enténébré'},
      dist=[
        ("Le soleil et la lune se sont obscurcis, et les étoiles retirent leur éclat.", 'retraxerunt', 'tempus', 'v:ind.praes.act.3.pl', "le retrait de l’éclat est actuel"),
        ("Le soleil et la lune se sont obscurcis, et les étoiles retireront leur éclat.", 'retraxerunt', 'tempus', 'v:ind.fut.act.3.pl', "le retrait de l’éclat est annoncé"),
        ("Le soleil et la lune se sont obscurcis, et l’étoile a retiré son éclat.", 'retraxerunt', 'numerus', 'v:ind.perf.act.3.sg', "une seule étoile"),
      ],
      note="Segond (« s’obscurcissent… retirent ») a le présent pour les parfaits latins ; rendu pédagogique."),
    Q('th-tempus-futurum', 'LEV 7:18',
      target=('erit', 'v:ind.fut.act.3.sg'),
      dist=[
        ("Dans le cas où l’on mangerait de la chair de son sacrifice d’actions de grâces le troisième jour, le sacrifice ne sera point agréé; il n’en sera pas tenu compte à celui qui l’a offert; ce sera une chose infecte, et quiconque en mangera reste chargé de sa faute.", 'erit', 'tempus', 'v:ind.praes.act.3.sg', "la faute est constatée au présent"),
        ("Dans le cas où l’on mangerait de la chair de son sacrifice d’actions de grâces le troisième jour, le sacrifice ne sera point agréé; il n’en sera pas tenu compte à celui qui l’a offert; ce sera une chose infecte, et quiconque en mangera resta chargé de sa faute.", 'erit', 'tempus', 'v:ind.perf.act.3.sg', "la faute est rejetée dans le passé"),
        ("Dans le cas où l’on mangerait de la chair de son sacrifice d’actions de grâces le troisième jour, le sacrifice n’est point agréé; il n’en sera pas tenu compte à celui qui l’a offert; ce sera une chose infecte, et quiconque en mangera restera chargé de sa faute.", 'fiet', 'tempus', 'v:ind.fut.act.3.sg>v:ind.praes.act.3.sg', "le rejet du sacrifice est actuel"),
      ],
      note="Segond rend comederit par un conditionnel et irrita fiet oblatio par « le sacrifice ne sera point agréé » ; la cible est erit (rea erit)."),
    Q('th-tempus-praeteritum', 'PRO 30:17',
      target=('subsannat', 'v:ind.praes.act.3.sg'),
      dist=[
        ("L’œil qui s’est moqué d’un père Et qui dédaigne l’obéissance envers une mère, Les corbeaux du torrent le perceront, Et les petits de l’aigle le mangeront.", 'subsannat', 'tempus', 'v:ind.perf.act.3.sg', "la moquerie est un fait passé"),
        ("L’œil qui se moquera d’un père Et qui dédaigne l’obéissance envers une mère, Les corbeaux du torrent le perceront, Et les petits de l’aigle le mangeront.", 'subsannat', 'tempus', 'v:ind.fut.act.3.sg', "la moquerie est à venir"),
        ("L’œil qui se moque d’un père Et qui dédaigne l’obéissance envers une mère, Le corbeau du torrent le percera, Et les petits de l’aigle le mangeront.", 'corvi', 'numerus', 'n:nom.pl>n:nom.sg', "un seul corbeau"),
      ],
      note="Segond a le futur pour les subjonctifs effodiant, comedant et « du torrent » pour de torrentibus ; la cible est subsannat."),
    Q('th-tempus-praeteritum', 'JER 40:8',
      target=('venerunt', 'v:ind.perf.act.3.pl'),
      la='venerunt ad Godoliam in Masphath',
      fr='ils se rendirent auprès de Guedalia à Mitspa',
      gloss={'Masphath': 'Mitspa'},
      dist=[
        ("ils se rendent auprès de Guedalia à Mitspa", 'venerunt', 'tempus', 'v:ind.praes.act.3.pl', "le déplacement est présenté comme en cours"),
        ("ils se rendront auprès de Guedalia à Mitspa", 'venerunt', 'tempus', 'v:ind.fut.act.3.pl', "le déplacement est annoncé"),
        ("il se rendit auprès de Guedalia à Mitspa", 'venerunt', 'numerus', 'v:ind.perf.act.3.sg', "un seul visiteur"),
      ],
      note="Première proposition du verset ; la liste des noms qui suit est laissée de côté."),
    Q('th-tempus-praeteritum', 'EST 9:19',
      target=('morabantur', 'v:ind.imperf.act.3.pl'),
      la='Hi vero Judæi, qui in oppidis non muratis ac villis morabantur, quartumdecimum diem mensis Adar conviviorum et gaudii decreverunt',
      paed=True, fr="Quant aux Juifs qui demeuraient dans les villes non fortifiées et dans les villages, ils décrétèrent que le quatorzième jour du mois d’Adar serait un jour de festins et de joie",
      gloss={'quartumdecimum': 'quatorzième', 'Adar': 'Adar (mois)'},
      dist=[
        ("Quant aux Juifs qui demeurent dans les villes non fortifiées et dans les villages, ils décrétèrent que le quatorzième jour du mois d’Adar serait un jour de festins et de joie", 'morabantur', 'tempus', 'v:ind.praes.act.3.pl', "le séjour est actuel"),
        ("Quant aux Juifs qui demeureront dans les villes non fortifiées et dans les villages, ils décrétèrent que le quatorzième jour du mois d’Adar serait un jour de festins et de joie", 'morabantur', 'tempus', 'v:ind.fut.act.3.pl', "le séjour est à venir"),
        ("Quant aux Juifs qui demeuraient dans la ville non fortifiée et dans les villages, ils décrétèrent que le quatorzième jour du mois d’Adar serait un jour de festins et de joie", 'oppidis', 'numerus', 'n:abl.pl>n:abl.sg', "une seule ville"),
      ],
      note="Segond (« qui habitent… font du quatorzième jour ») a le présent pour l’imparfait et le parfait latins ; rendu pédagogique de la première partie du verset."),
    Q('th-modus-subiunctivus', 'LUK 12:39',
      target=('vigilaret', 'v:subj.imperf.act.3.sg'),
      dist=[
        ("Sachez-le bien, si le maître de la maison savait à quelle heure le voleur doit venir, il veillait et ne laisserait pas percer sa maison.", 'vigilaret', 'modus', 'v:ind.imperf.act.3.sg', "l’hypothèse devient un fait passé"),
        ("Sachez-le bien, si le maître de la maison savait à quelle heure le voleur doit venir, il aurait veillé et ne laisserait pas percer sa maison.", 'vigilaret', 'tempus', 'v:subj.plusq.act.3.sg', "l’irréel est rejeté dans le passé"),
        ("Sachez-le bien, si le maître de la maison savait à quelle heure le voleur doit venir, ils veilleraient et ne laisserait pas percer sa maison.", 'vigilaret', 'numerus', 'v:subj.imperf.act.3.pl', "plusieurs veilleurs"),
      ],
      note="Segond rend veniret par « doit venir » ; la cible est vigilaret (irréel rendu par le conditionnel)."),
    Q('th-tempus-futurum', 'EXO 30:8',
      target=('collocabit', 'v:ind.fut.act.3.sg'),
      dist=[
        ("il en fera brûler aussi entre les deux soirs, lorsqu’il arrange les lampes. C’est ainsi que l’on brûlera à perpétuité du parfum devant l’Éternel parmi vos descendants.", 'collocabit', 'tempus', 'v:ind.praes.act.3.sg', "le geste est présenté comme actuel"),
        ("il en fera brûler aussi entre les deux soirs, lorsqu’il a arrangé les lampes. C’est ainsi que l’on brûlera à perpétuité du parfum devant l’Éternel parmi vos descendants.", 'collocabit', 'tempus', 'v:ind.perf.act.3.sg', "le geste est déjà accompli"),
        ("il en fera brûler aussi entre les deux soirs, lorsqu’ils arrangeront les lampes. C’est ainsi que l’on brûlera à perpétuité du parfum devant l’Éternel parmi vos descendants.", 'collocabit', 'numerus', 'v:ind.fut.act.3.pl', "plusieurs prêtres"),
      ],
      note="Segond réorganise le verset et rend uret par « l’on brûlera » ; la cible est collocabit."),
    Q('th-nonfinita', 'MAR 12:39',
      target=('sedere', 'v:inf.praes.act'),
      paed=True, fr="et à siéger dans les premières chaires dans les synagogues, et aux premières places dans les repas :",
      gloss={'synagogis': 'synagogues', 'cœnis': 'repas, dîners (cena)', 'discubitus': 'places à table (discubitus)'},
      dist=[
        ("et à avoir siégé dans les premières chaires dans les synagogues, et aux premières places dans les repas :", 'sedere', 'tempus', 'v:inf.perf.act', "l’action est déjà accomplie"),
        ("et ils siègent dans les premières chaires dans les synagogues, et aux premières places dans les repas :", 'sedere', 'nonfinita', '!verbum fīnītum (sedent)', "l’infinitif complément devient une affirmation"),
        ("et à siéger dans la première chaire dans les synagogues, et aux premières places dans les repas :", 'cathedris', 'numerus', 'n:abl.pl>n:abl.sg', "une seule chaire"),
      ],
      note="Segond (« qui recherchent les premiers sièges ») ne rend pas l’infinitif sedere ; rendu pédagogique."),
    Q('th-tempus-futurum', '2SA 15:18',
      target=('fuerant', 'v:ind.plusq.act.3.pl'),
      paed=True, fr="et tous ses serviteurs marchaient à ses côtés, et les légions des Kéréthiens et des Péléthiens, et tous les Gathiens, vaillants combattants, six cents hommes qui l’avaient suivi de Gath à pied, précédaient le roi.",
      gloss={'Cerethi': 'Kéréthiens', 'Phelethi': 'Péléthiens', 'servi': 'serviteurs (servus)'},
      dist=[
        ("et tous ses serviteurs marchaient à ses côtés, et les légions des Kéréthiens et des Péléthiens, et tous les Gathiens, vaillants combattants, six cents hommes qui l’ont suivi de Gath à pied, précédaient le roi.", 'fuerant', 'tempus', 'v:ind.praes.act.3.pl', "la suite n’est plus antérieure au récit"),
        ("et tous ses serviteurs marchaient à ses côtés, et les légions des Kéréthiens et des Péléthiens, et tous les Gathiens, vaillants combattants, six cents hommes qui le suivront de Gath à pied, précédaient le roi.", 'fuerant', 'tempus', 'v:ind.fut.act.3.pl', "la suite est annoncée"),
        ("et tous ses serviteurs marchaient à ses côtés, et les légions des Kéréthiens et des Péléthiens, et tous les Gathiens, vaillants combattants, six cents hommes qui le suivaient de Gath à pied, précédaient le roi.", 'fuerant', 'tempus', 'v:ind.imperf.act.3.pl', "la suite est présentée comme en cours"),
      ],
      note="Segond (« passèrent… venus de Gath à sa suite ») a le passé simple pour les imparfaits et un participe pour secuti fuerant ; rendu pédagogique."),
    Q('th-vox', 'ISA 30:14',
      target=('comminuetur', 'v:ind.fut.pass.3.sg'),
      la='Et comminuetur sicut conteritur lagena figuli contritione pervalida',
      paed=True, fr="Et il sera brisé comme est brisée la cruche du potier, d’un brisement très violent",
      dist=[
        ("Et il brisera comme est brisée la cruche du potier, d’un brisement très violent", 'comminuetur', 'vox', 'v:ind.fut.act.3.sg', "il devient celui qui brise"),
        ("Et il est brisé comme est brisée la cruche du potier, d’un brisement très violent", 'comminuetur', 'tempus', 'v:ind.praes.pass.3.sg', "la destruction est actuelle"),
        ("Et ils seront brisés comme est brisée la cruche du potier, d’un brisement très violent", 'comminuetur', 'numerus', 'v:ind.fut.pass.3.pl', "plusieurs objets brisés"),
      ],
      note="Segond (« Il se brise comme se brise un vase de terre, Que l’on casse sans ménagement ») a le présent pour le futur passif ; rendu pédagogique de la première partie."),
    Q('th-nonfinita', 'NAH 2:10',
      target=('Dissipata', 'v:part.perf.pass.nom.sg.f'),
      paed=True, fr_ref='NAH 2:11',
      fr="Elle est dévastée, et déchirée, et mise en pièces ; et le cœur se fond, et les genoux se dérobent, et la défaillance est dans tous les reins, et le visage de tous est comme la noirceur d’une marmite.",
      dist=[
        ("Elles sont dévastées, et déchirées, et mises en pièces ; et le cœur se fond, et les genoux se dérobent, et la défaillance est dans tous les reins, et le visage de tous est comme la noirceur d’une marmite.", 'Dissipata', 'numerus', 'v:part.perf.pass.nom.pl.f', "plusieurs villes dévastées"),
        ("Elle dévaste, et déchire, et met en pièces ; et le cœur se fond, et les genoux se dérobent, et la défaillance est dans tous les reins, et le visage de tous est comme la noirceur d’une marmite.", 'Dissipata', 'nonfinita', '!participium praesēns āctīvum (dissipāns)', "la ville devient celle qui dévaste"),
        ("Elle est dévastée, et déchirée, et mise en pièces ; et le cœur se fond, et les genoux se dérobent, et la défaillance est dans tous les reins, et le visage de tous est comme la noirceur des marmites.", 'ollæ', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs marmites"),
      ],
      note="Segond 2:11 (« On pille, on dévaste, on ravage ! ») tourne les participes passifs en actifs impersonnels ; rendu pédagogique."),
    Q('th-tempus-futurum', 'LEV 19:27',
      target=('attondebitis', 'v:ind.fut.act.2.pl'),
      gloss={'comam': 'chevelure (coma)'},
      dist=[
        ("Vous ne coupez point en rond les coins de votre chevelure, et tu ne raseras point les coins de ta barbe.", 'attondebitis', 'tempus', 'v:ind.praes.act.2.pl', "l’interdiction devient un constat présent"),
        ("Vous n’avez point coupé en rond les coins de votre chevelure, et tu ne raseras point les coins de ta barbe.", 'attondebitis', 'tempus', 'v:ind.perf.act.2.pl', "l’interdiction est rejetée dans le passé"),
        ("Tu ne couperas point en rond les coins de ta chevelure, et tu ne raseras point les coins de ta barbe.", 'attondebitis', 'numerus', 'v:ind.fut.act.2.sg', "un seul destinataire"),
      ],
      note="Segond passe au singulier « tu ne raseras » pour radetis (pluriel) ; la cible est attondebitis."),
    Q('th-tempus-futurum', 'AMO 6:7',
      target=('migrabunt', 'v:ind.fut.act.3.pl'),
      paed=True, fr="C’est pourquoi maintenant ils partiront en exil à la tête des exilés, et la bande des voluptueux sera emportée.",
      gloss={'capite': 'tête (caput)'},
      dist=[
        ("C’est pourquoi maintenant ils partent en exil à la tête des exilés, et la bande des voluptueux sera emportée.", 'migrabunt', 'tempus', 'v:ind.praes.act.3.pl', "l’exil est présenté comme actuel"),
        ("C’est pourquoi maintenant ils sont partis en exil à la tête des exilés, et la bande des voluptueux sera emportée.", 'migrabunt', 'tempus', 'v:ind.perf.act.3.pl', "l’exil est déjà accompli"),
        ("C’est pourquoi maintenant il partira en exil à la tête des exilés, et la bande des voluptueux sera emportée.", 'migrabunt', 'numerus', 'v:ind.fut.act.3.sg', "un seul exilé"),
      ],
      note="Segond (« ils seront emmenés… les cris de joie… cesseront ») change la voix de migrabunt et le sujet d’auferetur ; rendu pédagogique."),
    Q('th-modus-subiunctivus', 'DAN 4:13',
      target=('detur', 'v:subj.praes.pass.3.sg'),
      paed=True, fr_ref='DAN 4:16',
      fr="Que son cœur soit changé de celui d’un homme, et qu’un cœur de bête lui soit donné, et que sept temps passent sur lui.",
      dist=[
        ("Que son cœur soit changé de celui d’un homme, et un cœur de bête lui est donné, et que sept temps passent sur lui.", 'detur', 'modus', 'v:ind.praes.pass.3.sg', "l’ordre devient un constat"),
        ("Que son cœur soit changé de celui d’un homme, et qu’un cœur de bête lui fût donné, et que sept temps passent sur lui.", 'detur', 'tempus', 'v:subj.imperf.pass.3.sg', "le souhait est rejeté dans le passé"),
        ("Que son cœur soit changé de celui d’un homme, et que des cœurs de bête lui soient donnés, et que sept temps passent sur lui.", 'detur', 'numerus', 'v:subj.praes.pass.3.pl', "plusieurs cœurs"),
      ],
      note="Segond 4:16 (« Son cœur d’homme lui sera ôté, et un cœur de bête lui sera donné ») a le futur pour les subjonctifs de sentence ; rendu pédagogique."),
    Q('th-modus-imperativus', 'JOE 2:15',
      target=('Canite', 'v:imp.praes.act.2.pl'),
      dist=[
        ("Sonne de la trompette en Sion! Publiez un jeûne, une convocation solennelle!", 'Canite', 'numerus', 'v:imp.praes.act.2.sg', "l’ordre s’adresse à une seule personne"),
        ("Vous sonnez de la trompette en Sion! Publiez un jeûne, une convocation solennelle!", 'Canite', 'modus', 'v:ind.praes.act.2.pl', "l’ordre devient un constat"),
        ("Sonnez de la trompette en Sion! Publiez des jeûnes, une convocation solennelle!", 'jejunium', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs jeûnes"),
      ],
      note="Segond rend sanctificate et vocate par le seul « Publiez » ; la cible est Canite."),
    Q('th-tempus-futurum', 'EXO 28:11',
      target=('sculpes', 'v:ind.fut.act.2.sg'),
      gloss={'cælatura': 'ciselure (caelatura)'},
      dist=[
        ("Tu graves sur les deux pierres les noms des fils d’Israël, comme on grave les pierres et les cachets; tu les entoureras de montures d’or.", 'sculpes', 'tempus', 'v:ind.praes.act.2.sg', "le travail est présenté comme actuel"),
        ("Tu as gravé sur les deux pierres les noms des fils d’Israël, comme on grave les pierres et les cachets; tu les entoureras de montures d’or.", 'sculpes', 'tempus', 'v:ind.perf.act.2.sg', "le travail est déjà fait"),
        ("Tu graveras sur les deux pierres le nom des fils d’Israël, comme on grave les pierres et les cachets; tu les entoureras de montures d’or.", 'nominibus', 'numerus', 'n:abl.pl>n:abl.sg', "un seul nom"),
      ],
      note="Segond réorganise le verset (« comme on grave les pierres et les cachets » pour opere sculptoris et cælatura gemmarii) ; la cible est sculpes."),
    Q('th-tempus-praeteritum', 'DAN 3:55',
      target=('intueris', 'v:ind.praes.act.2.sg'),
      paed=True, fr="Tu es béni, toi qui regardes les abîmes et qui sièges sur les chérubins ; et tu es louable et souverainement exalté dans les siècles.",
      dist=[
        ("Tu es béni, toi qui regardais les abîmes et qui sièges sur les chérubins ; et tu es louable et souverainement exalté dans les siècles.", 'intueris', 'tempus', 'v:ind.imperf.act.2.sg', "le regard appartient au passé"),
        ("Tu es béni, toi qui regarderas les abîmes et qui sièges sur les chérubins ; et tu es louable et souverainement exalté dans les siècles.", 'intueris', 'tempus', 'v:ind.fut.act.2.sg', "le regard est à venir"),
        ("Tu es béni, toi qui regardes l’abîme et qui sièges sur les chérubins ; et tu es louable et souverainement exalté dans les siècles.", 'abyssos', 'numerus', 'n:acc.pl>n:acc.sg', "un seul abîme"),
      ],
      note="Passage absent de Segond (cantique des trois jeunes gens) ; rendu pédagogique."),
    Q('th-persona', 'GEN 41:9',
      target=('Confiteor', 'v:ind.praes.act.1.sg'),
      paed=True, fr="Alors enfin, se souvenant, le chef des échansons dit : Je confesse ma faute.",
      dist=[
        ("Alors enfin, se souvenant, le chef des échansons dit : Il confesse sa faute.", 'Confiteor', 'persona', 'v:ind.praes.act.3.sg', "l’aveu porte sur un tiers"),
        ("Alors enfin, se souvenant, le chef des échansons dit : Tu confesses ta faute.", 'Confiteor', 'persona', 'v:ind.praes.act.2.sg', "l’aveu est attribué à l’interlocuteur"),
        ("Alors enfin, se souvenant, le chef des échansons dit : Nous confessons notre faute.", 'Confiteor', 'numerus', 'v:ind.praes.act.1.pl', "plusieurs coupables"),
      ],
      note="Segond (« prit la parole, et dit à Pharaon: Je vais rappeler aujourd’hui le souvenir de ma faute ») paraphrase ; rendu pédagogique."),
    Q('th-tempus-praeteritum', '1CH 15:11',
      target=('Vocavitque', 'v:ind.perf.act.3.sg'),
      gloss={'Sadoc': 'Tsadok', 'Uriel': 'Uriel', 'Asaiam': 'Asaja', 'Eliel': 'Éliel'},
      dist=[
        ("David appelle les sacrificateurs Tsadok et Abiathar, et les Lévites Uriel, Asaja, Joël, Schemaeja, Éliel et Amminadab.", 'Vocavitque', 'tempus', 'v:ind.praes.act.3.sg', "la convocation est présentée comme actuelle"),
        ("David appellera les sacrificateurs Tsadok et Abiathar, et les Lévites Uriel, Asaja, Joël, Schemaeja, Éliel et Amminadab.", 'Vocavitque', 'tempus', 'v:ind.fut.act.3.sg', "la convocation est annoncée"),
        ("David appelait les sacrificateurs Tsadok et Abiathar, et les Lévites Uriel, Asaja, Joël, Schemaeja, Éliel et Amminadab.", 'Vocavitque', 'tempus', 'v:ind.imperf.act.3.sg', "un fait ponctuel devient une action qui dure"),
      ]),
    Q('th-vox', 'ISA 18:5',
      target=('præcidentur', 'v:ind.fut.pass.3.pl'),
      paed=True, fr="Car avant la moisson tout a fleuri, et la maturité imparfaite germera ; et ses sarments seront coupés avec des serpes, et ce qui aura été laissé sera arraché et secoué.",
      dist=[
        ("Car avant la moisson tout a fleuri, et la maturité imparfaite germera ; et ses sarments couperont avec des serpes, et ce qui aura été laissé sera arraché et secoué.", 'præcidentur', 'vox', 'v:ind.fut.act.3.pl', "les sarments deviennent ceux qui coupent"),
        ("Car avant la moisson tout a fleuri, et la maturité imparfaite germera ; et ses sarments sont coupés avec des serpes, et ce qui aura été laissé sera arraché et secoué.", 'præcidentur', 'tempus', 'v:ind.praes.pass.3.pl', "la taille est actuelle"),
        ("Car avant la moisson tout a fleuri, et la maturité imparfaite germera ; et son sarment sera coupé avec des serpes, et ce qui aura été laissé sera arraché et secoué.", 'præcidentur', 'numerus', 'v:ind.fut.pass.3.sg', "un seul sarment"),
      ],
      note="Segond (« Il coupe les sarments avec des serpes, Il enlève, il tranche les ceps ») met les passifs à l’actif et au présent ; rendu pédagogique."),
    Q('th-modus-subiunctivus', '2CO 12:7',
      target=('extollat', 'v:subj.praes.act.3.sg'),
      paed=True, fr="Et pour que la grandeur des révélations ne m’enorgueillisse pas, il m’a été donné une écharde dans ma chair, un ange de Satan, pour me souffleter.",
      dist=[
        ("Et la grandeur des révélations ne m’enorgueillit pas ; il m’a été donné une écharde dans ma chair, un ange de Satan, pour me souffleter.", 'extollat', 'modus', 'v:ind.praes.act.3.sg', "le but devient un constat"),
        ("Et pour que la grandeur des révélations ne m’enorgueillît pas, il m’a été donné une écharde dans ma chair, un ange de Satan, pour me souffleter.", 'extollat', 'tempus', 'v:subj.imperf.act.3.sg', "la finalité est rejetée dans le passé"),
        ("Et pour que la grandeur de la révélation ne m’enorgueillisse pas, il m’a été donné une écharde dans ma chair, un ange de Satan, pour me souffleter.", 'revelationum', 'numerus', 'n:gen.pl>n:gen.sg', "une seule révélation"),
      ],
      note="Segond (« pour que je ne sois pas enflé d’orgueil… et m’empêcher de m’enorgueillir ») change le sujet d’extollat et ajoute une finale ; rendu pédagogique."),
    Q('th-persona', 'ACT 28:13',
      target=('devenimus', 'v:ind.perf.act.1.pl'),
      dist=[
        ("De là, en suivant la côte, ils atteignirent Reggio; et, le vent du midi s’étant levé le lendemain, nous fîmes en deux jours le trajet jusqu’à Pouzzoles,", 'devenimus', 'persona', 'v:ind.perf.act.3.pl', "le narrateur ne fait plus partie du voyage"),
        ("De là, en suivant la côte, vous atteignîtes Reggio; et, le vent du midi s’étant levé le lendemain, nous fîmes en deux jours le trajet jusqu’à Pouzzoles,", 'devenimus', 'persona', 'v:ind.perf.act.2.pl', "on s’adresse aux voyageurs"),
        ("De là, en suivant la côte, j’atteignis Reggio; et, le vent du midi s’étant levé le lendemain, nous fîmes en deux jours le trajet jusqu’à Pouzzoles,", 'devenimus', 'numerus', 'v:ind.perf.act.1.sg', "le narrateur voyage seul"),
      ],
      note="Segond rend secunda die venimus Puteolos par « nous fîmes en deux jours le trajet jusqu’à Pouzzoles » ; la cible est devenimus."),
    Q('th-tempus-praeteritum', '2KI 15:30',
      target=('percussit', 'v:ind.perf.act.3.sg'),
      gloss={'Ela': 'Éla', 'Phacee': 'Pékach', 'Romeliæ': 'Remalia'},
      dist=[
        ("Osée, fils d’Éla, forma une conspiration contre Pékach, fils de Remalia, le frappe et le fit mourir; et il régna à sa place, la vingtième année de Jotham, fils d’Ozias.", 'percussit', 'tempus', 'v:ind.praes.act.3.sg', "le coup est présenté comme actuel"),
        ("Osée, fils d’Éla, forma une conspiration contre Pékach, fils de Remalia, le frappera et le fit mourir; et il régna à sa place, la vingtième année de Jotham, fils d’Ozias.", 'percussit', 'tempus', 'v:ind.fut.act.3.sg', "le coup est annoncé"),
        ("Osée, fils d’Éla, forma une conspiration contre Pékach, fils de Remalia, le frappa et le fit mourir; et il régnait à sa place, la vingtième année de Jotham, fils d’Ozias.", 'regnavitque', 'tempus', 'v:ind.perf.act.3.sg>v:ind.imperf.act.3.sg', "l’avènement devient un état qui dure"),
      ],
      note="Segond fond Conjuravit… et tetendit insidias en « forma une conspiration » ; la cible est percussit."),
    Q('th-nonfinita', 'LEV 21:20',
      target=('habens', 'v:part.praes.act.nom.sg.m'),
      gloss={'jugem': 'continuelle (iugis)'},
      dist=[
        ("un homme bossu ou grêle, devant avoir une tache à l’œil, la gale, une dartre, ou les testicules écrasés.", 'habens', 'tempus', 'v:part.fut.act.nom.sg.m', "le défaut n’existe pas encore"),
        ("un homme bossu ou grêle, ayant une tache aux yeux, la gale, une dartre, ou les testicules écrasés.", 'oculo', 'numerus', 'n:abl.sg>n:abl.pl', "les deux yeux atteints"),
        ("un homme bossu ou grêle, ayant des taches à l’œil, la gale, une dartre, ou les testicules écrasés.", 'albuginem', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs taches"),
      ],
      note="Segond résume la liste (« la gale, une dartre » pour jugem scabiem, impetiginem in corpore) ; la cible est le participe habens."),
    Q('th-tempus-praeteritum', 'JOH 5:2',
      target=('Est', 'v:ind.praes.act.3.sg'),
      gloss={'Jerosolymis': 'Jérusalem'},
      dist=[
        ("Or, à Jérusalem, près de la porte des brebis, il y avait une piscine qui s’appelle en hébreu Béthesda, et qui a cinq portiques.", 'Est', 'tempus', 'v:ind.imperf.act.3.sg', "la piscine appartient au passé"),
        ("Or, à Jérusalem, près de la porte des brebis, il y aura une piscine qui s’appelle en hébreu Béthesda, et qui a cinq portiques.", 'Est', 'tempus', 'v:ind.fut.act.3.sg', "la piscine est annoncée"),
        ("Or, à Jérusalem, près de la porte des brebis, il y a une piscine qui s’appellera en hébreu Béthesda, et qui a cinq portiques.", 'cognominatur', 'tempus', 'v:ind.praes.pass.3.sg>v:ind.fut.pass.3.sg', "le nom n’est pas encore donné"),
      ],
      note="Segond a « Béthesda » (variante textuelle) pour Bethsaida et « près de la porte des brebis » pour probatica ; la cible est Est."),
    Q('th-modus-imperativus', 'PSA 31:9',
      target=('Nolite', 'v:imp.praes.act.2.pl'),
      la='Nolite fieri sicut equus et mulus, quibus non est intellectus',
      fr='Ne soyez pas comme un cheval ou un mulet sans intelligence',
      dist=[
        ("Ne sois pas comme un cheval ou un mulet sans intelligence", 'Nolite', 'numerus', 'v:imp.praes.act.2.sg', "l’avertissement s’adresse à une seule personne"),
        ("Ne soyez pas comme des chevaux ou un mulet sans intelligence", 'equus', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs chevaux"),
        ("Ne soyez pas comme un cheval ou des mulets sans intelligence", 'mulus', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs mulets"),
      ],
      note="Segond 32:9 rend quibus non est intellectus par « sans intelligence » ; première partie du verset."),
    Q('th-tempus-futurum', 'JER 32:29',
      target=('comburent', 'v:ind.fut.act.3.pl'),
      dist=[
        ("Les Chaldéens qui attaquent cette ville vont entrer, Ils y mettront le feu, et ils la brûlent, Avec les maisons sur les toits desquelles on a offert de l’encens à Baal Et fait des libations à d’autres dieux, Afin de m’irriter.", 'comburent', 'tempus', 'v:ind.praes.act.3.pl', "l’incendie est présenté comme en cours"),
        ("Les Chaldéens qui attaquent cette ville vont entrer, Ils y mettront le feu, et ils l’ont brûlée, Avec les maisons sur les toits desquelles on a offert de l’encens à Baal Et fait des libations à d’autres dieux, Afin de m’irriter.", 'comburent', 'tempus', 'v:ind.perf.act.3.pl', "l’incendie est déjà accompli"),
        ("Les Chaldéens qui attaquent cette ville vont entrer, Ils y mettront le feu, et il la brûlera, Avec les maisons sur les toits desquelles on a offert de l’encens à Baal Et fait des libations à d’autres dieux, Afin de m’irriter.", 'comburent', 'numerus', 'v:ind.fut.act.3.sg', "un seul incendiaire"),
      ],
      note="Segond rend venient par « vont entrer » et sacrificabant par « on a offert » ; la cible est comburent."),
    Q('th-vox', 'LUK 6:15',
      target=('vocatur', 'v:ind.praes.pass.3.sg'),
      paed=True, fr="Matthieu et Thomas, Jacques fils d’Alphée, et Simon, qui est appelé le Zélote,",
      dist=[
        ("Matthieu et Thomas, Jacques fils d’Alphée, et Simon, qui appelle le Zélote,", 'vocatur', 'vox', 'v:ind.praes.act.3.sg', "Simon devient celui qui appelle"),
        ("Matthieu et Thomas, Jacques fils d’Alphée, et Simon, qui sera appelé le Zélote,", 'vocatur', 'tempus', 'v:ind.fut.pass.3.sg', "le surnom n’est pas encore donné"),
        ("Matthieu et Thomas, Jacques fils d’Alphée, et Simon, qui était appelé le Zélote,", 'vocatur', 'tempus', 'v:ind.imperf.pass.3.sg', "le surnom appartient au passé"),
      ],
      note="Segond (« Simon, appelé le zélote ») rend le verbe vocatur par un participe ; rendu pédagogique."),
    Q('th-modus-imperativus', 'LAM 3:19',
      target=('Recordare', 'v:imp.praes.act.2.sg'),
      paed=True, fr="Souviens-toi de ma pauvreté et de ma transgression, de l’absinthe et du fiel.",
      gloss={'Zain': 'zaïn (lettre hébraïque)'},
      dist=[
        ("Souvenez-vous de ma pauvreté et de ma transgression, de l’absinthe et du fiel.", 'Recordare', 'numerus', 'v:imp.praes.act.2.pl', "la prière s’adresse à plusieurs"),
        ("Tu te souviens de ma pauvreté et de ma transgression, de l’absinthe et du fiel.", 'Recordare', 'modus', 'v:ind.praes.act.2.sg', "la prière devient un constat"),
        ("Souviens-toi de ma pauvreté et de mes transgressions, de l’absinthe et du fiel.", 'transgressionis', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs transgressions"),
      ],
      note="Segond (« Quand je pense à ma détresse et à ma misère ») met l’impératif à la première personne ; rendu pédagogique."),
    Q('th-persona', 'JAM 5:5',
      target=('enutristis', 'v:ind.perf.act.2.pl'),
      dist=[
        ("Vous avez vécu sur la terre dans les voluptés et dans les délices, ils ont rassasié leurs cœurs au jour du carnage.", 'enutristis', 'persona', 'v:ind.perf.act.3.pl', "le reproche vise des tiers"),
        ("Vous avez vécu sur la terre dans les voluptés et dans les délices, nous avons rassasié nos cœurs au jour du carnage.", 'enutristis', 'persona', 'v:ind.perf.act.1.pl', "l’auteur s’inclut dans le reproche"),
        ("Vous avez vécu sur la terre dans les voluptés et dans les délices, vous avez rassasié vos cœurs aux jours du carnage.", 'die', 'numerus', 'n:abl.sg>n:abl.pl', "plusieurs jours de carnage"),
      ],
      note="Segond rend Epulati estis par « Vous avez vécu… dans les voluptés » ; la cible est enutristis."),
    Q('th-vox', 'PRO 14:29',
      target=('gubernatur', 'v:ind.praes.pass.3.sg'),
      paed=True, fr="Celui qui est patient est gouverné par une grande prudence ; mais celui qui est impatient exalte sa folie.",
      dist=[
        ("Celui qui est patient gouverne par une grande prudence ; mais celui qui est impatient exalte sa folie.", 'gubernatur', 'vox', 'v:ind.praes.act.3.sg', "le patient devient celui qui gouverne"),
        ("Celui qui est patient sera gouverné par une grande prudence ; mais celui qui est impatient exalte sa folie.", 'gubernatur', 'tempus', 'v:ind.fut.pass.3.sg', "la sagesse est promise au lieu d’être constatée"),
        ("Ceux qui sont patients sont gouvernés par une grande prudence ; mais celui qui est impatient exalte sa folie.", 'gubernatur', 'numerus', 'v:ind.praes.pass.3.pl', "plusieurs patients"),
      ],
      note="Segond (« a une grande intelligence… proclame sa folie ») paraphrase le passif gubernatur ; rendu pédagogique."),
    Q('th-persona', 'ACT 25:16',
      target=('respondi', 'v:ind.perf.act.1.sg'),
      dist=[
        ("Il leur a répondu que ce n’est pas la coutume des Romains de livrer un homme avant que l’inculpé ait été mis en présence de ses accusateurs, et qu’il ait eu la faculté de se défendre sur les choses dont on l’accuse.", 'respondi', 'persona', 'v:ind.perf.act.3.sg', "la réponse est attribuée à un tiers"),
        ("Tu leur as répondu que ce n’est pas la coutume des Romains de livrer un homme avant que l’inculpé ait été mis en présence de ses accusateurs, et qu’il ait eu la faculté de se défendre sur les choses dont on l’accuse.", 'respondi', 'persona', 'v:ind.perf.act.2.sg', "on s’adresse à celui qui a répondu"),
        ("Nous leur avons répondu que ce n’est pas la coutume des Romains de livrer un homme avant que l’inculpé ait été mis en présence de ses accusateurs, et qu’il ait eu la faculté de se défendre sur les choses dont on l’accuse.", 'respondi', 'numerus', 'v:ind.perf.act.1.pl', "plusieurs répondants"),
      ],
      note="Segond rend is qui accusatur par « l’inculpé » et ad abluenda crimina par « sur les choses dont on l’accuse » ; la cible est respondi."),
    Q('th-tempus-praeteritum', 'ACT 27:40',
      target=('tendebant', 'v:ind.imperf.act.3.pl'),
      paed=True, fr="Et ayant levé les ancres, ils s’abandonnaient à la mer, relâchant en même temps les attaches des gouvernails ; et, la voile d’artimon hissée selon le souffle du vent, ils se dirigeaient vers le rivage.",
      gloss={'juncturas': 'attaches, jointures (iunctura)', 'secundum': 'selon (secundum)'},
      dist=[
        ("Et ayant levé les ancres, ils s’abandonnaient à la mer, relâchant en même temps les attaches des gouvernails ; et, la voile d’artimon hissée selon le souffle du vent, ils se dirigèrent vers le rivage.", 'tendebant', 'tempus', 'v:ind.perf.act.3.pl', "une manœuvre qui dure devient un fait ponctuel"),
        ("Et ayant levé les ancres, ils s’abandonnaient à la mer, relâchant en même temps les attaches des gouvernails ; et, la voile d’artimon hissée selon le souffle du vent, ils se dirigent vers le rivage.", 'tendebant', 'tempus', 'v:ind.praes.act.3.pl', "la manœuvre est présentée comme actuelle"),
        ("Et ayant levé les ancres, ils s’abandonnaient à la mer, relâchant en même temps les attaches des gouvernails ; et, la voile d’artimon hissée selon le souffle du vent, ils se dirigeaient vers les rivages.", 'littus', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs rivages"),
      ],
      note="Segond (« Ils délièrent les ancres… et se dirigèrent ») a le passé simple pour les imparfaits latins ; rendu pédagogique."),
    Q('th-nonfinita', 'EST 15:7',
      target=('sustentans', 'v:part.praes.act.nom.sg.f'),
      paed=True, fr="et l’autre des servantes suivait sa maîtresse, soutenant les vêtements qui traînaient jusqu’à terre.",
      dist=[
        ("et l’autre des servantes suivait sa maîtresse, sur le point de soutenir les vêtements qui traînaient jusqu’à terre.", 'sustentans', 'tempus', 'v:part.fut.act.nom.sg.f', "le geste n’a pas encore commencé"),
        ("et l’autre des servantes suivait sa maîtresse qui soutenait les vêtements qui traînaient jusqu’à terre.", 'sustentans', 'congruentia', '!cum dominam (acc. sg. f.) congruēns', "c’est la maîtresse qui soutient les vêtements"),
        ("et l’autre des servantes suivait sa maîtresse, soutenant le vêtement qui traînait jusqu’à terre.", 'indumenta', 'numerus', 'n:acc.pl>n:acc.sg', "un seul vêtement"),
      ],
      note="Verset absent de Segond (additions grecques d’Esther) ; rendu pédagogique."),
    Q('th-modus-imperativus', 'PSA 73:18',
      target=('esto', 'v:imp.fut.act.2.sg'),
      dist=[
        ("Souvenez-vous que l’ennemi outrage l’Éternel, Et qu’un peuple insensé méprise ton nom!", 'esto', 'numerus', 'v:imp.fut.act.2.pl', "la prière s’adresse à plusieurs"),
        ("Tu te souviendras que l’ennemi outrage l’Éternel, Et qu’un peuple insensé méprise ton nom!", 'esto', 'modus', 'v:ind.fut.act.2.sg', "la prière devient une prédiction"),
        ("Souviens-toi que les ennemis outragent l’Éternel, Et qu’un peuple insensé méprise ton nom!", 'inimicus', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs ennemis"),
      ],
      note="Segond 74:18 a le présent (« outrage… méprise ») pour les parfaits improperavit, incitavit ; la cible est esto (memor esto)."),
    Q('th-modus-imperativus', 'HOS 5:8',
      target=('Clangite', 'v:imp.praes.act.2.pl'),
      gloss={'Rama': 'Rama'},
      dist=[
        ("Vous sonnez de la trompette à Guibea, Sonnez de la trompette à Rama! Poussez des cris à Beth-Aven! Derrière toi, Benjamin!", 'Clangite', 'modus', 'v:ind.praes.act.2.pl', "l’ordre devient un constat"),
        ("Sonne de la trompette à Guibea, Sonne de la trompette à Rama! Poussez des cris à Beth-Aven! Derrière toi, Benjamin!", 'Clangite', 'numerus', 'v:imp.praes.act.2.sg', "un seul sonneur"),
        ("Sonnez de la trompette à Guibea, Sonnez de la trompette à Rama! Pousse des cris à Beth-Aven! Derrière toi, Benjamin!", 'ululate', 'numerus', 'v:imp.praes.act.2.pl>v:imp.praes.act.2.sg', "une seule personne doit crier"),
      ],
      note="Segond répète « Sonnez de la trompette » pour buccina… tuba (verbe sous-entendu) ; la cible est Clangite."),
    Q('th-tempus-praeteritum', 'LUK 7:38',
      target=('tergebat', 'v:ind.imperf.act.3.sg'),
      paed=True, fr="et se tenant derrière, à ses pieds, elle commença à arroser ses pieds de larmes, et elle les essuyait avec les cheveux de sa tête, et elle baisait ses pieds et les oignait de parfum.",
      gloss={'capitis': 'tête (caput)'},
      dist=[
        ("et se tenant derrière, à ses pieds, elle commença à arroser ses pieds de larmes, et elle les essuya avec les cheveux de sa tête, et elle baisait ses pieds et les oignait de parfum.", 'tergebat', 'tempus', 'v:ind.perf.act.3.sg', "un geste qui dure devient un fait ponctuel"),
        ("et se tenant derrière, à ses pieds, elle commença à arroser ses pieds de larmes, et elle les essuie avec les cheveux de sa tête, et elle baisait ses pieds et les oignait de parfum.", 'tergebat', 'tempus', 'v:ind.praes.act.3.sg', "le geste est présenté comme actuel"),
        ("et se tenant derrière, à ses pieds, elle commença à arroser ses pieds de larmes, et elles les essuyaient avec les cheveux de leur tête, et elle baisait ses pieds et les oignait de parfum.", 'tergebat', 'numerus', 'v:ind.imperf.act.3.pl', "plusieurs femmes"),
      ],
      note="Segond (« Elle pleurait; et bientôt elle lui mouilla les pieds… puis les essuya ») a le passé simple pour les imparfaits latins ; rendu pédagogique."),
]
