# sheet_011 → batch_011
# skipped: 1CH 1:17 (list of names, no verb)
# skipped: JOS 19:35 (list of place names; only «civitates munitissimæ» declined, not enough for three misreadings)
# skipped: NEH 12:6 (list of names, no verb)
ITEMS = [
    Q('th-tempus-futurum', 'DEU 17:18',
      target=('describet', 'v:ind.fut.act.3.sg'),
      dist=[
        ("Quand il s’assiéra sur le trône de son royaume, il écrit pour lui, dans un livre, une copie de cette loi, qu’il prendra auprès des sacrificateurs, les Lévites.", 'describet', 'tempus', 'v:ind.praes.act.3.sg', "la copie est présentée comme en cours d’écriture"),
        ("Quand il s’assiéra sur le trône de son royaume, ils écriront pour eux, dans un livre, une copie de cette loi, qu’il prendra auprès des sacrificateurs, les Lévites.", 'describet', 'numerus', 'v:ind.fut.act.3.pl', "plusieurs scribes au lieu du roi seul"),
        ("Quand il s’assiéra sur le trône de son royaume, il écrira pour lui, dans un livre, une copie de cette loi, qu’il prendra auprès du sacrificateur, le Lévite.", 'sacerdotibus', 'numerus', 'n:abl.pl>n:abl.sg', "un seul prêtre au lieu du corps sacerdotal"),
      ],
      note="Segond rend « Deuteronomium legis hujus » par « une copie de cette loi » ; la cible est le verbe principal."),
    Q('th-tempus-futurum', 'ISA 55:13',
      target=('ascendet', 'v:ind.fut.act.3.sg'),
      dist=[
        ("Au lieu de l’épine s’élève le cyprès, Au lieu de la ronce croîtra le myrte; Et ce sera pour l’Éternel une gloire, Un monument perpétuel, impérissable.", 'ascendet', 'tempus', 'v:ind.praes.act.3.sg', "la croissance est actuelle au lieu d’être promise"),
        ("Au lieu de l’épine s’éleva le cyprès, Au lieu de la ronce croîtra le myrte; Et ce sera pour l’Éternel une gloire, Un monument perpétuel, impérissable.", 'ascendet', 'tempus', 'v:ind.perf.act.3.sg', "la promesse devient un fait passé"),
        ("Au lieu de l’épine s’élèveront les cyprès, Au lieu de la ronce croîtra le myrte; Et ce sera pour l’Éternel une gloire, Un monument perpétuel, impérissable.", 'ascendet', 'numerus', 'v:ind.fut.act.3.pl', "plusieurs arbres au lieu d’un seul"),
      ],
      note="Segond a « cyprès » pour abies (sapin) et « épine » pour saliunca ; la cible est le verbe."),
    Q('th-numerus', '2TI 3:3',
      target=('criminatores', 'n:nom.pl'),
      dist=[
        ("insensibles, déloyaux, calomniateur, intempérants, cruels, ennemis des gens de bien,", 'criminatores', 'numerus', 'n:nom.sg', "un seul calomniateur dans la liste"),
        ("insensibles, déloyaux, calomniateurs, intempérant, cruels, ennemis des gens de bien,", 'incontinentes', 'numerus', 'a:nom.pl.m>a:nom.sg.m', "un seul intempérant"),
        ("insensibles, déloyaux, calomniateurs, intempérants, cruel, ennemis des gens de bien,", 'immites', 'numerus', 'a:nom.pl.m>a:nom.sg.m', "un seul cruel"),
      ],
      note="Attributs des « homines » du verset précédent (nominatif pluriel) ; Segond rend « sine benignitate » par « ennemis des gens de bien »."),
    Q('th-nonfinita', 'NUM 33:49',
      target=('castrametati', 'v:part.perf.act.nom.pl.m'),
      gloss={'Bethsimoth': 'Beth-Jeschimoth', 'Abelsatim': 'Abel-Sittim'},
      dist=[
        ("Il campa près du Jourdain, depuis Beth-Jeschimoth jusqu’à Abel-Sittim, dans les plaines de Moab.", 'castrametati', 'numerus', 'v:part.perf.act.nom.sg.m', "un seul homme campe au lieu du peuple"),
        ("Ils campent près du Jourdain, depuis Beth-Jeschimoth jusqu’à Abel-Sittim, dans les plaines de Moab.", 'castrametati', 'tempus', 'v:part.praes.act.nom.pl.m', "le campement est en cours au lieu d’être achevé"),
        ("Ils campèrent près du Jourdain, depuis Beth-Jeschimoth jusqu’à Abel-Sittim, dans la plaine de Moab.", 'planioribus', 'numerus', 'a:abl.pl.f.comp>a:abl.sg.f.comp', "une seule plaine"),
      ],
      note="Segond ajoute « près du Jourdain » ; parfait périphrastique déponent castrametati sunt."),
    Q('th-tempus-praeteritum', '1TH 4:6',
      target=('prædiximus', 'v:ind.perf.act.1.pl'),
      dist=[
        ("c’est que personne n’use envers son frère de fraude et de cupidité dans les affaires, parce que le Seigneur tire vengeance de toutes ces choses, comme nous vous l’avions déjà dit et attesté.", 'prædiximus', 'tempus', 'v:ind.plusq.act.1.pl', "l’avertissement est rejeté dans un passé antérieur"),
        ("c’est que personne n’use envers son frère de fraude et de cupidité dans les affaires, parce que le Seigneur tire vengeance de toutes ces choses, comme ils vous l’ont déjà dit et attesté.", 'prædiximus', 'persona', 'v:ind.perf.act.3.pl', "d’autres que Paul ont averti"),
        ("c’est que personne n’use envers ses frères de fraude et de cupidité dans les affaires, parce que le Seigneur tire vengeance de toutes ces choses, comme nous vous l’avons déjà dit et attesté.", 'fratrem', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs frères"),
      ],
      note="Segond fond « supergrediatur » et « circumveniat » en « n’use de fraude et de cupidité » ; la cible est prædiximus."),
    Q('th-persona', 'NUM 11:5',
      target=('recordamur', 'v:ind.praes.act.1.pl'),
      dist=[
        ("Vous vous souvenez des poissons que nous mangions en Égypte, et qui ne nous coûtaient rien, des concombres, des melons, des poireaux, des oignons et des aulx.", 'recordamur', 'persona', 'v:ind.praes.act.2.pl', "le souvenir est attribué aux interlocuteurs"),
        ("Ils se souviennent des poissons que nous mangions en Égypte, et qui ne nous coûtaient rien, des concombres, des melons, des poireaux, des oignons et des aulx.", 'recordamur', 'persona', 'v:ind.praes.act.3.pl', "le souvenir est attribué à des tiers"),
        ("Je me souviens des poissons que nous mangions en Égypte, et qui ne nous coûtaient rien, des concombres, des melons, des poireaux, des oignons et des aulx.", 'recordamur', 'numerus', 'v:ind.praes.act.1.sg', "un seul se souvient au lieu du peuple"),
      ]),
    Q('th-tempus-futurum', 'PRO 27:7',
      target=('calcabit', 'v:ind.fut.act.3.sg'),
      paed=True, fr="L’âme rassasiée foulera aux pieds le rayon de miel, et l’âme affamée prendra même l’amer pour du doux.",
      dist=[
        ("L’âme rassasiée foule aux pieds le rayon de miel, et l’âme affamée prendra même l’amer pour du doux.", 'calcabit', 'tempus', 'v:ind.praes.act.3.sg', "le dédain est présenté comme actuel"),
        ("L’âme rassasiée foula aux pieds le rayon de miel, et l’âme affamée prendra même l’amer pour du doux.", 'calcabit', 'tempus', 'v:ind.perf.act.3.sg', "le dédain devient un fait passé"),
        ("L’âme rassasiée foulera aux pieds le rayon de miel, et l’âme affamée prend même l’amer pour du doux.", 'sumet', 'tempus', 'v:ind.fut.act.3.sg>v:ind.praes.act.3.sg', "la faim est actuelle au lieu d’être envisagée"),
      ],
      note="Segond a le présent (« foule », « trouve ») pour les futurs latins ; rendu pédagogique."),
    Q('th-numerus', 'ISA 3:22',
      target=('palliola', 'n:acc.pl'),
      paed=True, fr="et les vêtements de rechange, et les petits manteaux, et les linges, et les aiguilles,",
      dist=[
        ("et les vêtements de rechange, et le petit manteau, et les linges, et les aiguilles,", 'palliola', 'numerus', 'n:acc.sg', "un seul manteau"),
        ("et le vêtement de rechange, et les petits manteaux, et les linges, et les aiguilles,", 'mutatoria', 'numerus', 'n:acc.pl>n:acc.sg', "un seul vêtement"),
        ("et les vêtements de rechange, et les petits manteaux, et les linges, et l’aiguille,", 'acus', 'numerus', 'n:acc.pl>n:acc.sg', "une seule aiguille"),
      ],
      note="Segond suit l’hébreu (« vêtements précieux… gibecières ») et ne rend pas les mots latins ; rendu pédagogique de la liste (accusatifs, objets de auferet, v. 18)."),
    Q('th-tempus-futurum', 'EXO 22:16',
      target=('dotabit', 'v:ind.fut.act.3.sg'),
      dist=[
        ("Si un homme séduit une vierge qui n’est point fiancée, et qu’il couche avec elle, il paie sa dot et la prendra pour femme.", 'dotabit', 'tempus', 'v:ind.praes.act.3.sg', "le paiement est constaté au lieu d’être prescrit"),
        ("Si un homme séduit une vierge qui n’est point fiancée, et qu’il couche avec elle, il paya sa dot et la prendra pour femme.", 'dotabit', 'tempus', 'v:ind.perf.act.3.sg', "le paiement devient un fait passé"),
        ("Si un homme séduit des vierges qui ne sont point fiancées, et qu’il couche avec elles, il paiera sa dot et la prendra pour femme.", 'virginem', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs jeunes filles"),
      ]),
    Q('th-numerus', 'EZE 38:5',
      target=('Æthiopes', 'n:nom.pl', 'aethiops'),
      paed=True, fr="Les Perses, les Éthiopiens et les Libyens avec eux, tous munis du bouclier et du casque.",
      gloss={'Libyes': 'Libyens (Segond : Puth)'},
      dist=[
        ("Les Perses, l’Éthiopien et les Libyens avec eux, tous munis du bouclier et du casque.", 'Æthiopes', 'numerus', 'n:nom.sg', "un seul Éthiopien"),
        ("Le Perse, les Éthiopiens et les Libyens avec eux, tous munis du bouclier et du casque.", 'Persæ', 'numerus', 'n:nom.pl>n:nom.sg', "un seul Perse"),
        ("Les Perses, les Éthiopiens et les Libyens avec lui, tous munis du bouclier et du casque.", 'eis', 'numerus', 'a:abl.pl.m>a:abl.sg.m', "un seul allié au lieu des peuples précédents"),
      ],
      note="Segond a « ceux de Perse, d’Éthiopie et de Puth » (noms de pays) ; rendu pédagogique des nominatifs pluriels."),
    Q('th-persona', '2PE 1:19',
      target=('habemus', 'v:ind.praes.act.1.pl'),
      gloss={'attendentes': 'prêtant attention, attentifs'},
      dist=[
        ("Et vous tenez pour d’autant plus certaine la parole prophétique, à laquelle vous faites bien de prêter attention, comme à une lampe qui brille dans un lieu obscur, jusqu’à ce que le jour vienne à paraître et que l’étoile du matin se lève dans vos cœurs;", 'habemus', 'persona', 'v:ind.praes.act.2.pl', "la certitude est attribuée aux destinataires seuls"),
        ("Et ils tiennent pour d’autant plus certaine la parole prophétique, à laquelle vous faites bien de prêter attention, comme à une lampe qui brille dans un lieu obscur, jusqu’à ce que le jour vienne à paraître et que l’étoile du matin se lève dans vos cœurs;", 'habemus', 'persona', 'v:ind.praes.act.3.pl', "la certitude est attribuée à des tiers"),
        ("Et je tiens pour d’autant plus certaine la parole prophétique, à laquelle vous faites bien de prêter attention, comme à une lampe qui brille dans un lieu obscur, jusqu’à ce que le jour vienne à paraître et que l’étoile du matin se lève dans vos cœurs;", 'habemus', 'numerus', 'v:ind.praes.act.1.sg', "l’apôtre parle seul au lieu de parler pour tous"),
      ],
      note="Segond rend « firmiorem » par « d’autant plus certaine » ; la cible est habemus."),
    Q('th-tempus-praeteritum', 'GEN 43:32',
      target=('vescebantur', 'v:ind.imperf.act.3.pl'),
      gloss={'illicitum': 'illicite, interdit'},
      dist=[
        ("On servit Joseph à part, et ses frères à part; les Égyptiens qui mangent avec lui furent aussi servis à part, car les Égyptiens ne pouvaient pas manger avec les Hébreux, parce que c’est à leurs yeux une abomination.", 'vescebantur', 'tempus', 'v:ind.praes.act.3.pl', "le repas est actuel"),
        ("On servit Joseph à part, et ses frères à part; l’Égyptien qui mangeait avec lui fut aussi servi à part, car les Égyptiens ne pouvaient pas manger avec les Hébreux, parce que c’est à leurs yeux une abomination.", 'vescebantur', 'numerus', 'v:ind.imperf.act.3.sg', "un seul convive égyptien"),
        ("On servit Joseph à part, et ses frères à part; les Égyptiens qui mangeaient avec lui furent aussi servis à part, car les Égyptiens ne pouvaient pas manger avec l’Hébreu, parce que c’est à leurs yeux une abomination.", 'Hebræis', 'numerus', 'a:abl.pl.m>a:abl.sg.m', "un seul Hébreu au lieu du peuple"),
      ],
      note="Segond paraphrase la construction absolue « Quibus appositis » et « illicitum est » ; la cible est vescebantur, rendu fidèlement par « mangeaient »."),
    Q('th-numerus', 'PRO 7:21',
      target=('Irretivit', 'v:ind.perf.act.3.sg'),
      dist=[
        ("Elles le séduisirent à force de paroles, Elle l’entraîna par ses lèvres doucereuses.", 'Irretivit', 'numerus', 'v:ind.perf.act.3.pl', "plusieurs séductrices"),
        ("Elle les séduisit à force de paroles, Elle l’entraîna par ses lèvres doucereuses.", 'eum', 'numerus', 'a:acc.sg.m>a:acc.pl.m', "plusieurs victimes"),
        ("Elle le séduisit à force de paroles, Elle les entraîna par ses lèvres doucereuses.", 'illum', 'numerus', 'a:acc.sg.m>a:acc.pl.m', "plusieurs hommes entraînés"),
      ],
      note="Segond rend « blanditiis labiorum » par « ses lèvres doucereuses »."),
    Q('th-tempus-praeteritum', 'ISA 44:13',
      target=('extendit', 'v:ind.praes.act.3.sg'),
      dist=[
        ("Le charpentier étendra le cordeau, Fait un tracé au crayon, Façonne le bois avec un couteau, Et marque ses dimensions avec le compas; Et il produit une figure d’homme, Une belle forme humaine, Pour qu’elle habite dans une maison.", 'extendit', 'tempus', 'v:ind.fut.act.3.sg', "le geste est annoncé au lieu d’être décrit"),
        ("Le charpentier étendait le cordeau, Fait un tracé au crayon, Façonne le bois avec un couteau, Et marque ses dimensions avec le compas; Et il produit une figure d’homme, Une belle forme humaine, Pour qu’elle habite dans une maison.", 'extendit', 'tempus', 'v:ind.imperf.act.3.sg', "le geste est rejeté dans le passé"),
        ("Les charpentiers étendent le cordeau, Fait un tracé au crayon, Façonne le bois avec un couteau, Et marque ses dimensions avec le compas; Et il produit une figure d’homme, Une belle forme humaine, Pour qu’elle habite dans une maison.", 'Artifex', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs artisans"),
      ],
      note="extendit est ambigu (présent/parfait) ; on retient le présent, que Segond rend « étend » ; Segond garde le présent pour les parfaits suivants (formavit, fecit, tornavit)."),
    Q('th-tempus-futurum', 'EXO 12:49',
      target=('erit', 'v:ind.fut.act.3.sg'),
      dist=[
        ("La même loi existe pour l’indigène comme pour l’étranger en séjour au milieu de vous.", 'erit', 'tempus', 'v:ind.praes.act.3.sg', "la règle est constatée au lieu d’être instituée"),
        ("La même loi exista pour l’indigène comme pour l’étranger en séjour au milieu de vous.", 'erit', 'tempus', 'v:ind.perf.act.3.sg', "la règle devient un fait passé"),
        ("Les mêmes lois existeront pour l’indigène comme pour l’étranger en séjour au milieu de vous.", 'lex', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs lois au lieu d’une loi unique"),
      ]),
    Q('th-tempus-praeteritum', 'JON 4:7',
      target=('paravit', 'v:ind.perf.act.3.sg'),
      gloss={'vermen': 'ver'},
      dist=[
        ("Mais le lendemain, à l’aurore, Dieu fait venir un ver qui piqua le ricin, et le ricin sécha.", 'paravit', 'tempus', 'v:ind.praes.act.3.sg', "l’envoi du ver est présenté comme actuel"),
        ("Mais le lendemain, à l’aurore, Dieu fera venir un ver qui piqua le ricin, et le ricin sécha.", 'paravit', 'tempus', 'v:ind.fut.act.3.sg', "l’envoi du ver est annoncé"),
        ("Mais le lendemain, à l’aurore, Dieu fit venir un ver qui pique le ricin, et le ricin sécha.", 'percussit', 'tempus', 'v:ind.perf.act.3.sg>v:ind.praes.act.3.sg', "la piqûre est actuelle"),
      ],
      note="Segond rend « paravit » (prépara) par « fit venir » et « hederam » (lierre) par « ricin » d’après l’hébreu."),
    Q('th-numerus', 'EXO 36:14',
      target=('Fecit', 'v:ind.perf.act.3.sg'),
      dist=[
        ("Ils firent des tapis de poil de chèvre, pour servir de tente sur le tabernacle; on fit onze de ces tapis.", 'Fecit', 'numerus', 'v:ind.perf.act.3.pl', "plusieurs artisans au lieu d’un seul"),
        ("On fit un tapis de poil de chèvre, pour servir de tente sur le tabernacle; on fit onze de ces tapis.", 'saga', 'numerus', 'n:acc.pl>n:acc.sg', "un seul tapis"),
        ("On fit des tapis de poil de chèvre, pour servir de tente sur les tabernacles; on fit onze de ces tapis.", 'tabernaculi', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs tabernacles"),
      ],
      note="Segond a l’impersonnel « on fit » pour le singulier « Fecit » (Béséléel) et reporte « undecim » en fin de verset."),
    Q('th-tempus-futurum', 'ISA 42:13',
      target=('suscitabit', 'v:ind.fut.act.3.sg'),
      paed=True, fr="Le Seigneur sortira comme un héros, comme un homme de guerre il excitera son ardeur; il poussera des cris et il clamera; il sera fortifié contre ses ennemis.",
      dist=[
        ("Le Seigneur sortira comme un héros, comme un homme de guerre il excite son ardeur; il poussera des cris et il clamera; il sera fortifié contre ses ennemis.", 'suscitabit', 'tempus', 'v:ind.praes.act.3.sg', "l’ardeur est actuelle au lieu d’être annoncée"),
        ("Le Seigneur sortira comme un héros, comme un homme de guerre il excita son ardeur; il poussera des cris et il clamera; il sera fortifié contre ses ennemis.", 'suscitabit', 'tempus', 'v:ind.perf.act.3.sg', "l’ardeur devient un fait passé"),
        ("Le Seigneur sortira comme un héros, comme un homme de guerre il excitera son ardeur; il poussera des cris et il clamera; il sera fortifié contre son ennemi.", 'inimicos', 'numerus', 'n:acc.pl>n:acc.sg', "un seul ennemi"),
      ],
      note="Segond a le présent pour toute la série de futurs latins ; rendu pédagogique."),
    Q('th-tempus-futurum', 'ISA 29:5',
      target=('erit', 'v:ind.fut.act.3.sg'),
      la='Et erit sicut pulvis tenuis multitudo ventilantium te',
      fr='La multitude de tes ennemis sera comme une fine poussière',
      dist=[
        ("La multitude de tes ennemis est comme une fine poussière", 'erit', 'tempus', 'v:ind.praes.act.3.sg', "la dispersion est actuelle au lieu d’être promise"),
        ("La multitude de tes ennemis fut comme une fine poussière", 'erit', 'tempus', 'v:ind.perf.act.3.sg', "la dispersion devient un fait passé"),
        ("Les multitudes de tes ennemis seront comme une fine poussière", 'multitudo', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs foules"),
      ],
      note="Segond rend « ventilantium te » (ceux qui te vannent) par « tes ennemis » ; la seconde moitié du verset diverge, d’où la clause."),
    Q('th-tempus-futurum', 'NUM 9:11',
      target=('comedent', 'v:ind.fut.act.3.pl'),
      gloss={'quartadecima': 'quatorzième'},
      dist=[
        ("C’est au second mois qu’ils la célébreront, le quatorzième jour, entre les deux soirs; ils la mangent avec des pains sans levain et des herbes amères.", 'comedent', 'tempus', 'v:ind.praes.act.3.pl', "le repas est actuel au lieu d’être prescrit"),
        ("C’est au second mois qu’ils la célébreront, le quatorzième jour, entre les deux soirs; ils la mangèrent avec des pains sans levain et des herbes amères.", 'comedent', 'tempus', 'v:ind.perf.act.3.pl', "le repas devient un fait passé"),
        ("C’est au second mois qu’ils la célébreront, le quatorzième jour, entre les deux soirs; il la mangera avec des pains sans levain et des herbes amères.", 'comedent', 'numerus', 'v:ind.fut.act.3.sg', "un seul convive au lieu de la communauté"),
      ],
      note="Segond ajoute « qu’ils la célébreront » et rend « lactucis agrestibus » par « herbes amères »."),
    Q('th-tempus-praeteritum', 'EXO 12:38',
      target=('ascendit', 'v:ind.perf.act.3.sg'),
      paed=True, fr="Et aussi une foule mêlée innombrable monta avec eux, des brebis, des troupeaux et des animaux d’espèces diverses en très grand nombre.",
      dist=[
        ("Et aussi une foule mêlée innombrable montait avec eux, des brebis, des troupeaux et des animaux d’espèces diverses en très grand nombre.", 'ascendit', 'tempus', 'v:ind.imperf.act.3.sg', "un fait accompli devient une action qui dure"),
        ("Et aussi une foule mêlée innombrable montera avec eux, des brebis, des troupeaux et des animaux d’espèces diverses en très grand nombre.", 'ascendit', 'tempus', 'v:ind.fut.act.3.sg', "la montée est annoncée au lieu d’être racontée"),
        ("Et aussi une foule mêlée innombrable monta avec lui, des brebis, des troupeaux et des animaux d’espèces diverses en très grand nombre.", 'eis', 'numerus', 'a:abl.pl.m>a:abl.sg.m', "un seul compagnon au lieu des Israélites"),
      ],
      note="Segond a le pluriel « montèrent » pour le collectif singulier vulgus ascendit ; rendu pédagogique (parfait retenu pour la forme ambiguë ascendit)."),
    Q('th-tempus-praeteritum', 'GEN 5:30',
      target=('Vixitque', 'v:ind.perf.act.3.sg'),
      gloss={'Lamech': 'Lémec'},
      dist=[
        ("Lémec vivait, après la naissance de Noé, cinq cent quatre-vingt-quinze ans; et il engendra des fils et des filles.", 'Vixitque', 'tempus', 'v:ind.imperf.act.3.sg', "une durée close devient un état qui se prolonge"),
        ("Lémec vivra, après la naissance de Noé, cinq cent quatre-vingt-quinze ans; et il engendra des fils et des filles.", 'Vixitque', 'tempus', 'v:ind.fut.act.3.sg', "la vie de Lémec est annoncée"),
        ("Lémec vécut, après la naissance de Noé, cinq cent quatre-vingt-quinze ans; et il engendra un fils et des filles.", 'filios', 'numerus', 'n:acc.pl>n:acc.sg', "un seul fils"),
      ],
      note="Segond rend « postquam genuit Noë » par « après la naissance de Noé »."),
    Q('th-tempus-praeteritum', 'EZE 13:19',
      target=('violabant', 'v:ind.imperf.act.3.pl'),
      paed=True, fr="Et elles me profanaient auprès de mon peuple pour une poignée d’orge et un morceau de pain, pour tuer des âmes qui ne meurent pas et faire vivre des âmes qui ne vivent pas, en mentant à mon peuple qui croit aux mensonges.",
      dist=[
        ("Et elles me profanent auprès de mon peuple pour une poignée d’orge et un morceau de pain, pour tuer des âmes qui ne meurent pas et faire vivre des âmes qui ne vivent pas, en mentant à mon peuple qui croit aux mensonges.", 'violabant', 'tempus', 'v:ind.praes.act.3.pl', "la profanation est actuelle"),
        ("Et elles me profanèrent auprès de mon peuple pour une poignée d’orge et un morceau de pain, pour tuer des âmes qui ne meurent pas et faire vivre des âmes qui ne vivent pas, en mentant à mon peuple qui croit aux mensonges.", 'violabant', 'tempus', 'v:ind.perf.act.3.pl', "une pratique habituelle devient un fait ponctuel"),
        ("Et elles me profanaient auprès de mon peuple pour des poignées d’orge et un morceau de pain, pour tuer des âmes qui ne meurent pas et faire vivre des âmes qui ne vivent pas, en mentant à mon peuple qui croit aux mensonges.", 'pugillum', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs poignées"),
      ],
      note="Segond a la 2e personne du présent (« Vous me déshonorez ») pour la 3e de l’imparfait ; rendu pédagogique (sujet : les prophétesses du v. 17)."),
    Q('th-modus-imperativus', 'ISA 16:4',
      target=('esto', 'v:imp.fut.act.2.sg'),
      la='Moab, esto latibulum eorum a facie vastatoris',
      fr='Sois pour eux un refuge contre le dévastateur',
      dist=[
        ("Tu seras pour eux un refuge contre le dévastateur", 'esto', 'modus', 'v:ind.fut.act.2.sg', "un ordre devient une prédiction"),
        ("Soyez pour eux un refuge contre le dévastateur", 'esto', 'numerus', 'v:imp.fut.act.2.pl', "l’ordre s’adresse à plusieurs"),
        ("Sois pour lui un refuge contre le dévastateur", 'eorum', 'numerus', 'a:gen.pl.m>a:gen.sg.m', "un seul réfugié"),
      ],
      note="Segond lit un impératif pour « Habitabunt » ; on retient la clause où l’impératif futur esto est rendu par « Sois »."),
    Q('th-tempus-praeteritum', 'JDG 9:46',
      target=('habitabant', 'v:ind.imperf.act.3.pl'),
      la='Quod cum audissent qui habitabant in turre Sichimorum, ingressi sunt fanum dei sui Berith',
      paed=True, fr="Lorsque ceux qui habitaient dans la tour de Sichem l’apprirent, ils entrèrent dans le temple de leur dieu Berith",
      gloss={'Sichimorum': 'Sichem (les Sichémites)', 'Berith': 'Berith'},
      dist=[
        ("Lorsque ceux qui habitent dans la tour de Sichem l’apprirent, ils entrèrent dans le temple de leur dieu Berith", 'habitabant', 'tempus', 'v:ind.praes.act.3.pl', "les habitants sont actuels"),
        ("Lorsque ceux qui habitèrent dans la tour de Sichem l’apprirent, ils entrèrent dans le temple de leur dieu Berith", 'habitabant', 'tempus', 'v:ind.perf.act.3.pl', "un séjour durable devient un fait ponctuel"),
        ("Lorsque ceux qui habitaient dans les tours de Sichem l’apprirent, ils entrèrent dans le temple de leur dieu Berith", 'turre', 'numerus', 'n:abl.sg>n:abl.pl', "plusieurs tours"),
      ],
      note="Segond rend la relative par le nom « les habitants » et « fanum » par « forteresse de la maison » ; rendu pédagogique de la première clause."),
    Q('th-persona', 'JOB 12:19',
      target=('Ducit', 'v:ind.praes.act.3.sg'),
      dist=[
        ("Tu emmènes captifs les sacrificateurs; Il fait tomber les puissants.", 'Ducit', 'persona', 'v:ind.praes.act.2.sg', "l’action est attribuée à l’interlocuteur"),
        ("J’emmène captifs les sacrificateurs; Il fait tomber les puissants.", 'Ducit', 'persona', 'v:ind.praes.act.1.sg', "le locuteur s’attribue l’action de Dieu"),
        ("Ils emmènent captifs les sacrificateurs; Il fait tomber les puissants.", 'Ducit', 'numerus', 'v:ind.praes.act.3.pl', "plusieurs acteurs au lieu de Dieu seul"),
      ],
      note="Segond rend « inglorios » par « captifs » d’après l’hébreu."),
    Q('th-tempus-praeteritum', 'JAM 3:8',
      target=('potest', 'v:ind.praes.act.3.sg'),
      dist=[
        ("mais la langue, aucun homme ne pouvait la dompter; c’est un mal qu’on ne peut réprimer; elle est pleine d’un venin mortel.", 'potest', 'tempus', 'v:ind.imperf.act.3.sg', "l’impuissance est rejetée dans le passé"),
        ("mais la langue, aucun homme ne pourra la dompter; c’est un mal qu’on ne peut réprimer; elle est pleine d’un venin mortel.", 'potest', 'tempus', 'v:ind.fut.act.3.sg', "l’impuissance est annoncée au lieu d’être constatée"),
        ("mais la langue, aucun homme ne peut la dompter; c’est un mal qu’on ne peut réprimer; elle est pleine de venins mortels.", 'veneno', 'numerus', 'n:abl.sg>n:abl.pl', "plusieurs venins"),
      ],
      note="Segond rend « inquietum malum » par « un mal qu’on ne peut réprimer »."),
    Q('th-numerus', 'ISA 40:15',
      target=('gentes', 'n:nom.pl'),
      dist=[
        ("Voici, la nation est comme une goutte d’un seau, Elle est comme de la poussière sur une balance; Voici, les îles sont comme une fine poussière qui s’envole.", 'gentes', 'numerus', 'n:nom.sg', "une seule nation"),
        ("Voici, les nations sont comme une goutte de seaux, Elles sont comme de la poussière sur une balance; Voici, les îles sont comme une fine poussière qui s’envole.", 'situlæ', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs seaux"),
        ("Voici, les nations sont comme une goutte d’un seau, Elles sont comme de la poussière sur une balance; Voici, l’île est comme une fine poussière qui s’envole.", 'insulæ', 'numerus', 'n:nom.pl>n:nom.sg', "une seule île"),
      ],
      note="Segond ne rend pas « reputatæ sunt » (sont comptées) ; la cible est le nom sujet."),
    Q('th-tempus-futurum', '1MA 1:11',
      target=('fuerat', 'v:ind.plusq.act.3.sg'),
      paed=True, fr="Et il sortit d’eux une racine de péché, Antiochus l’Illustre, fils du roi Antiochus, qui avait été otage à Rome; et il régna en la cent trente-septième année du royaume des Grecs.",
      dist=[
        ("Et il sortit d’eux une racine de péché, Antiochus l’Illustre, fils du roi Antiochus, qui était otage à Rome; et il régna en la cent trente-septième année du royaume des Grecs.", 'fuerat', 'tempus', 'v:ind.imperf.act.3.sg', "l’otage l’est encore au moment du récit"),
        ("Et il sortit d’eux une racine de péché, Antiochus l’Illustre, fils du roi Antiochus, qui fut otage à Rome; et il régna en la cent trente-septième année du royaume des Grecs.", 'fuerat', 'tempus', 'v:ind.perf.act.3.sg', "l’antériorité de la captivité disparaît"),
        ("Et il sortit d’eux une racine de péché, Antiochus l’Illustre, fils du roi Antiochus, qui avait été otage à Rome; et il règne en la cent trente-septième année du royaume des Grecs.", 'regnavit', 'tempus', 'v:ind.perf.act.3.sg>v:ind.praes.act.3.sg', "le règne est actuel"),
      ],
      note="Livre absent de Segond ; rendu pédagogique."),
    Q('th-numerus', '1CH 27:28',
      target=('oliveta', 'n:acc.pl'),
      gloss={'Gederites': 'de Guéder (le Guédérite)', 'Balanam': 'Baal-Hanan'},
      dist=[
        ("Baal-Hanan, de Guéder, sur l’olivier et les sycomores dans la plaine; Joasch, sur les provisions d’huile;", 'oliveta', 'numerus', 'n:acc.sg', "un seul plant d’oliviers"),
        ("Baal-Hanan, de Guéder, sur les oliviers et le sycomore dans la plaine; Joasch, sur les provisions d’huile;", 'ficeta', 'numerus', 'n:acc.pl>n:acc.sg', "un seul plant de figuiers"),
        ("Baal-Hanan, de Guéder, sur les oliviers et les sycomores dans la plaine; Joasch, sur la provision d’huile;", 'apothecas', 'numerus', 'n:acc.pl>n:acc.sg', "une seule réserve"),
      ],
      note="Segond a « sycomores » pour ficeta (plantations de figuiers) ; « Balanam » est le nom propre Baal-Hanan, non le verbe balo."),
    Q('th-persona', '2CO 4:2',
      target=('abdicamus', 'v:ind.praes.act.1.pl'),
      dist=[
        ("Vous rejetez les choses honteuses qui se font en secret, nous n’avons point une conduite astucieuse, et nous n’altérons point la parole de Dieu. Mais, en publiant la vérité, nous nous recommandons à toute conscience d’homme devant Dieu.", 'abdicamus', 'persona', 'v:ind.praes.act.2.pl', "le rejet est attribué aux destinataires"),
        ("Ils rejettent les choses honteuses qui se font en secret, nous n’avons point une conduite astucieuse, et nous n’altérons point la parole de Dieu. Mais, en publiant la vérité, nous nous recommandons à toute conscience d’homme devant Dieu.", 'abdicamus', 'persona', 'v:ind.praes.act.3.pl', "le rejet est attribué à des tiers"),
        ("Je rejette les choses honteuses qui se font en secret, nous n’avons point une conduite astucieuse, et nous n’altérons point la parole de Dieu. Mais, en publiant la vérité, nous nous recommandons à toute conscience d’homme devant Dieu.", 'abdicamus', 'numerus', 'v:ind.praes.act.1.sg', "Paul parle seul au lieu de parler pour ses compagnons"),
      ],
      note="Segond rend les participes « ambulantes », « adulterantes » par des verbes conjugués ; la cible est abdicamus."),
    Q('th-tempus-praeteritum', '1KI 18:28',
      target=('Clamabant', 'v:ind.imperf.act.3.pl'),
      paed=True, fr="Ils criaient donc à haute voix, et ils se faisaient des incisions, selon leur rite, avec des couteaux et des lancettes, jusqu’à ce qu’ils fussent couverts de sang.",
      dist=[
        ("Ils crièrent donc à haute voix, et ils se faisaient des incisions, selon leur rite, avec des couteaux et des lancettes, jusqu’à ce qu’ils fussent couverts de sang.", 'Clamabant', 'tempus', 'v:ind.perf.act.3.pl', "une action qui dure devient un cri ponctuel"),
        ("Ils crient donc à haute voix, et ils se faisaient des incisions, selon leur rite, avec des couteaux et des lancettes, jusqu’à ce qu’ils fussent couverts de sang.", 'Clamabant', 'tempus', 'v:ind.praes.act.3.pl', "les cris sont actuels"),
        ("Ils criaient donc à haute voix, et ils se faisaient des incisions, selon leur rite, avec un couteau et des lancettes, jusqu’à ce qu’ils fussent couverts de sang.", 'cultris', 'numerus', 'n:abl.pl>n:abl.sg', "un seul couteau"),
      ],
      note="Segond a le passé simple (« ils crièrent », « ils se firent ») pour les imparfaits latins ; rendu pédagogique."),
    Q('th-modus-imperativus', 'WIS 1:12',
      target=('Nolite', 'v:imp.praes.act.2.pl'),
      paed=True, fr="Ne recherchez pas avec zèle la mort dans l’erreur de votre vie, et n’acquérez pas la perdition par les œuvres de vos mains.",
      dist=[
        ("Ne recherche pas avec zèle la mort dans l’erreur de ta vie, et n’acquérez pas la perdition par les œuvres de vos mains.", 'Nolite', 'numerus', 'v:imp.praes.act.2.sg', "la défense s’adresse à une seule personne"),
        ("Ne recherchez pas avec zèle la mort dans l’erreur de votre vie, et vous n’acquérez pas la perdition par les œuvres de vos mains.", 'acquiratis', 'modus', 'v:subj.praes.act.2.pl>v:ind.praes.act.2.pl', "une défense devient un constat"),
        ("Ne recherchez pas avec zèle la mort dans l’erreur de votre vie, et n’acquérez pas la perdition par les œuvres de votre main.", 'manuum', 'numerus', 'n:gen.pl>n:gen.sg', "une seule main"),
      ],
      note="Livre absent de Segond ; rendu pédagogique (nolite + infinitif = défense)."),
    Q('th-tempus-praeteritum', 'MAR 9:14',
      target=('salutabant', 'v:ind.imperf.act.3.pl'),
      paed=True, fr="Et aussitôt tout le peuple, voyant Jésus, fut stupéfait; et ils furent effrayés, et, accourant, ils le saluaient.",
      dist=[
        ("Et aussitôt tout le peuple, voyant Jésus, fut stupéfait; et ils furent effrayés, et, accourant, ils le saluèrent.", 'salutabant', 'tempus', 'v:ind.perf.act.3.pl', "une salutation prolongée devient un fait ponctuel"),
        ("Et aussitôt tout le peuple, voyant Jésus, fut stupéfait; et ils furent effrayés, et, accourant, ils le saluent.", 'salutabant', 'tempus', 'v:ind.praes.act.3.pl', "la salutation est actuelle"),
        ("Et aussitôt tout le peuple, voyant Jésus, fut stupéfait; et ils furent effrayés, et, accourant, ils les saluaient.", 'eum', 'numerus', 'a:acc.sg.m>a:acc.pl.m', "plusieurs personnes saluées au lieu de Jésus seul"),
      ],
      note="Le verset de Segond suit le texte grec (les scribes discutant avec les disciples) et ne rend pas la Vulgate ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'PSA 76:19',
      target=('Illuxerunt', 'v:ind.perf.act.3.pl'),
      dist=[
        ("Ton tonnerre éclata dans le tourbillon, Les éclairs illuminent le monde; La terre s’émut et trembla.", 'Illuxerunt', 'tempus', 'v:ind.praes.act.3.pl', "les éclairs sont actuels"),
        ("Ton tonnerre éclata dans le tourbillon, Les éclairs illumineront le monde; La terre s’émut et trembla.", 'Illuxerunt', 'tempus', 'v:ind.fut.act.3.pl', "les éclairs sont annoncés"),
        ("Ton tonnerre éclata dans le tourbillon, L’éclair illumina le monde; La terre s’émut et trembla.", 'coruscationes', 'numerus', 'n:nom.pl>n:nom.sg', "un seul éclair"),
      ],
      note="Segond (77:19) rend « vox tonitrui tui in rota » par « Ton tonnerre éclata dans le tourbillon »."),
    Q('th-modus-imperativus', 'JOB 37:2',
      target=('Audite', 'v:imp.praes.act.2.pl'),
      la='Audite auditionem in terrore vocis ejus',
      fr='Écoutez, écoutez le frémissement de sa voix',
      dist=[
        ("Écoute, écoute le frémissement de sa voix", 'Audite', 'numerus', 'v:imp.praes.act.2.sg', "l’ordre s’adresse à une seule personne"),
        ("Vous écoutez, vous écoutez le frémissement de sa voix", 'Audite', 'modus', 'v:ind.praes.act.2.pl', "un ordre devient un constat"),
        ("Écoutez, écoutez le frémissement de ses voix", 'vocis', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs voix"),
      ],
      note="Segond redouble « Écoutez » pour « Audite auditionem » (écoutez l’écoute) ; la clause est retenue."),
    Q('th-vox', 'ISA 22:17',
      target=('asportatur', 'v:ind.praes.pass.3.sg'),
      paed=True, fr="Voici, le Seigneur te fera emporter, comme un coq de basse-cour est emporté; et il te soulèvera comme un manteau.",
      dist=[
        ("Voici, le Seigneur te fera emporter, comme un coq de basse-cour emporte; et il te soulèvera comme un manteau.", 'asportatur', 'vox', 'v:ind.praes.act.3.sg', "le coq devient celui qui emporte au lieu d’être emporté"),
        ("Voici, le Seigneur te fera emporter, comme un coq de basse-cour sera emporté; et il te soulèvera comme un manteau.", 'asportatur', 'tempus', 'v:ind.fut.pass.3.sg', "la comparaison est reportée dans l’avenir"),
        ("Voici, le Seigneur te fera emporter, comme un coq de basse-cour est emporté; et il te soulève comme un manteau.", 'sublevabit', 'tempus', 'v:ind.fut.act.3.sg>v:ind.praes.act.3.sg', "le geste est actuel au lieu d’être annoncé"),
      ],
      note="Segond suit l’hébreu (« te lancera d’un jet vigoureux ») et n’a pas la comparaison du coq ; rendu pédagogique."),
]
