# sheet_013 → batch_013
# skipped: SOL 4:14 (list of nominative singular nouns, no verb; number changes give no natural French)
# skipped: 1CH 3:8 (list of names, no verb)
# skipped: NEH 12:8 (list of names; Segond renders «hymnos» by a singular and «eorum» by «ses», no faithful misreading left)
# skipped: JOS 15:55 (list of place names)
# skipped: 1CH 3:2 (list of names with ordinals, no verb)
ITEMS = [
    Q('th-nonfinita', '2PE 2:14',
      target=('habentes', 'v:part.praes.act.nom.pl.m'),
      dist=[
        ("Il a les yeux pleins d’adultère et insatiables de péché; ils amorcent les âmes mal affermies; ils ont le cœur exercé à la cupidité; ce sont des enfants de malédiction.", 'habentes', 'numerus', 'v:part.praes.act.nom.sg.m', "un seul séducteur au lieu de tous"),
        ("Ils auront les yeux pleins d’adultère et insatiables de péché; ils amorcent les âmes mal affermies; ils ont le cœur exercé à la cupidité; ce sont des enfants de malédiction.", 'habentes', 'tempus', 'v:part.fut.act.nom.pl.m', "la débauche est à venir au lieu d’être actuelle"),
        ("Ils ont les yeux pleins d’adultère et insatiables de péché; ils amorcent l’âme mal affermie; ils ont le cœur exercé à la cupidité; ce sont des enfants de malédiction.", 'animas', 'numerus', 'n:acc.pl>n:acc.sg', "une seule victime"),
      ],
      note="Segond rend les participes nominatifs (habentes, Pellicientes) par des verbes conjugués « ils ont », « ils amorcent »."),
    Q('th-tempus-praeteritum', 'DEU 25:16',
      target=('facit', 'v:ind.praes.act.3.sg'),
      dist=[
        ("Car quiconque fit ces choses, quiconque commet une iniquité, est en abomination à l’Éternel, ton Dieu.", 'facit', 'tempus', 'v:ind.perf.act.3.sg', "la faute est rejetée dans le passé"),
        ("Car quiconque fera ces choses, quiconque commet une iniquité, est en abomination à l’Éternel, ton Dieu.", 'facit', 'tempus', 'v:ind.fut.act.3.sg', "la faute est envisagée pour l’avenir"),
        ("Car quiconque fait cette chose, quiconque commet une iniquité, est en abomination à l’Éternel, ton Dieu.", 'hæc', 'numerus', 'a:acc.pl.n>a:acc.sg.n', "une seule faute"),
      ],
      note="Segond inverse la phrase (« est en abomination à l’Éternel ») pour les déponents Abominatur et aversatur ; la cible est facit."),
    Q('th-tempus-praeteritum', 'SIR 11:5',
      target=('sederunt', 'v:ind.perf.act.3.pl'),
      paed=True, fr="Beaucoup de tyrans se sont assis sur le trône, et celui qu’on ne soupçonnait pas a porté le diadème.",
      gloss={'tyranni': 'tyrans'},
      dist=[
        ("Beaucoup de tyrans s’assoient sur le trône, et celui qu’on ne soupçonnait pas a porté le diadème.", 'sederunt', 'tempus', 'v:ind.praes.act.3.pl', "l’accession au trône est actuelle"),
        ("Beaucoup de tyrans s’assiéront sur le trône, et celui qu’on ne soupçonnait pas a porté le diadème.", 'sederunt', 'tempus', 'v:ind.fut.act.3.pl', "l’accession au trône est annoncée"),
        ("Beaucoup de tyrans se sont assis sur les trônes, et celui qu’on ne soupçonnait pas a porté le diadème.", 'throno', 'numerus', 'n:abl.sg>n:abl.pl', "plusieurs trônes"),
      ],
      note="Livre absent de Segond ; rendu pédagogique."),
    Q('th-numerus', 'LEV 13:59',
      target=('lex', 'n:nom.sg'),
      dist=[
        ("Telles sont les lois sur la plaie de la lèpre, lorsqu’elle attaque les vêtements de laine ou de lin, la chaîne ou la trame, ou un objet quelconque de peau, et d’après laquelle ils seront déclarés purs ou impurs.", 'lex', 'numerus', 'n:nom.pl', "plusieurs lois"),
        ("Telle est la loi sur la plaie de la lèpre, lorsqu’elle attaque les vêtements de laine ou de lin, les chaînes ou la trame, ou un objet quelconque de peau, et d’après laquelle ils seront déclarés purs ou impurs.", 'staminis', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs chaînes"),
        ("Telle est la loi sur la plaie de la lèpre, lorsqu’elle attaque les vêtements de laine ou de lin, la chaîne ou les trames, ou un objet quelconque de peau, et d’après laquelle ils seront déclarés purs ou impurs.", 'subtegminis', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs trames"),
      ],
      note="Segond a le pluriel « les vêtements » pour vestimenti (singulier) et tourne « quomodo mundari debeat » en « d’après laquelle ils seront déclarés » ; la cible est lex."),
    Q('th-vox', '2MA 5:10',
      target=('abjicitur', 'v:ind.praes.pass.3.sg'),
      paed=True, fr="et lui qui avait jeté beaucoup d’hommes sans sépulture, il est lui-même jeté sans être pleuré et sans sépulture, n’ayant eu ni sépulture étrangère ni part au tombeau de ses pères.",
      dist=[
        ("et lui qui avait jeté beaucoup d’hommes sans sépulture, il jette lui-même sans être pleuré et sans sépulture, n’ayant eu ni sépulture étrangère ni part au tombeau de ses pères.", 'abjicitur', 'vox', 'v:ind.praes.act.3.sg', "il reste celui qui jette au lieu de subir le même sort"),
        ("et lui qui avait jeté beaucoup d’hommes sans sépulture, il sera lui-même jeté sans être pleuré et sans sépulture, n’ayant eu ni sépulture étrangère ni part au tombeau de ses pères.", 'abjicitur', 'tempus', 'v:ind.fut.pass.3.sg', "le châtiment est annoncé au lieu d’être raconté"),
        ("et lui qui jetait beaucoup d’hommes sans sépulture, il est lui-même jeté sans être pleuré et sans sépulture, n’ayant eu ni sépulture étrangère ni part au tombeau de ses pères.", 'abjecerat', 'tempus', 'v:ind.plusq.act.3.sg>v:ind.imperf.act.3.sg', "les crimes ne sont plus antérieurs au châtiment"),
      ],
      note="Livre absent de Segond ; rendu pédagogique (présent de narration abjicitur)."),
    Q('th-tempus-praeteritum', 'DEU 8:4',
      target=('defecit', 'v:ind.perf.act.3.sg'),
      dist=[
        ("Ton vêtement ne s’use point sur toi, et ton pied ne s’est point enflé, pendant ces quarante années.", 'defecit', 'tempus', 'v:ind.praes.act.3.sg', "la préservation est présentée comme actuelle"),
        ("Ton vêtement ne s’usera point sur toi, et ton pied ne s’est point enflé, pendant ces quarante années.", 'defecit', 'tempus', 'v:ind.fut.act.3.sg', "la préservation est promise au lieu d’être constatée"),
        ("Ton vêtement ne s’est point usé sur toi, et tes pieds ne se sont point enflés, pendant ces quarante années.", 'pes', 'numerus', 'n:nom.sg>n:nom.pl', "les deux pieds au lieu du singulier collectif"),
      ],
      note="Segond rend « quo operiebaris » par « sur toi » et « en quadragesimus annus est » par « pendant ces quarante années »."),
    Q('th-tempus-praeteritum', 'JOS 10:3',
      target=('Misit', 'v:ind.perf.act.3.sg'),
      gloss={'Jerusalem': 'Jérusalem', 'Oham': 'Hoham', 'Pharam': 'Piream', 'Jerimoth': 'Jarmuth', 'Japhia': 'Japhia', 'Lachis': 'Lakis', 'Dabir': 'Debir', 'Eglon': 'Églon'},
      dist=[
        ("Adoni-Tsédek, roi de Jérusalem, fait dire à Hoham, roi d’Hébron, à Piream, roi de Jarmuth, à Japhia, roi de Lakis, et à Debir, roi d’Églon:", 'Misit', 'tempus', 'v:ind.praes.act.3.sg', "l’envoi des messagers est actuel"),
        ("Adoni-Tsédek, roi de Jérusalem, fera dire à Hoham, roi d’Hébron, à Piream, roi de Jarmuth, à Japhia, roi de Lakis, et à Debir, roi d’Églon:", 'Misit', 'tempus', 'v:ind.fut.act.3.sg', "l’envoi des messagers est annoncé"),
        ("Adoni-Tsédek, roi de Jérusalem, avait fait dire à Hoham, roi d’Hébron, à Piream, roi de Jarmuth, à Japhia, roi de Lakis, et à Debir, roi d’Églon:", 'Misit', 'tempus', 'v:ind.plusq.act.3.sg', "l’envoi devient antérieur au récit"),
      ],
      note="Segond rend « Misit… dicens » par « fit dire »."),
    Q('th-tempus-futurum', 'ISA 3:24',
      target=('erit', 'v:ind.fut.act.3.sg'),
      dist=[
        ("Au lieu de parfum, il y a de l’infection; Au lieu de ceinture, une corde; Au lieu de cheveux bouclés, une tête chauve; Au lieu d’un large manteau, un sac étroit; Une marque flétrissante, au lieu de beauté.", 'erit', 'tempus', 'v:ind.praes.act.3.sg', "le châtiment est constaté au lieu d’être annoncé"),
        ("Au lieu de parfum, il y eut de l’infection; Au lieu de ceinture, une corde; Au lieu de cheveux bouclés, une tête chauve; Au lieu d’un large manteau, un sac étroit; Une marque flétrissante, au lieu de beauté.", 'erit', 'tempus', 'v:ind.perf.act.3.sg', "le châtiment devient un fait passé"),
        ("Au lieu de parfum, il y aura de l’infection; Au lieu de ceinture, des cordes; Au lieu de cheveux bouclés, une tête chauve; Au lieu d’un large manteau, un sac étroit; Une marque flétrissante, au lieu de beauté.", 'funiculus', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs cordes"),
      ],
      note="Segond ajoute d’après l’hébreu « Une marque flétrissante, au lieu de beauté » ; la cible est erit."),
    Q('th-persona', 'EZR 2:69',
      target=('dederunt', 'v:ind.perf.act.3.pl'),
      dist=[
        ("Nous donnâmes au trésor de l’œuvre, selon nos moyens, soixante et un mille dariques d’or, cinq mille mines d’argent, et cent tuniques sacerdotales.", 'dederunt', 'persona', 'v:ind.perf.act.1.pl', "le narrateur s’inclut parmi les donateurs"),
        ("Vous donnâtes au trésor de l’œuvre, selon vos moyens, soixante et un mille dariques d’or, cinq mille mines d’argent, et cent tuniques sacerdotales.", 'dederunt', 'persona', 'v:ind.perf.act.2.pl', "le don est attribué aux interlocuteurs"),
        ("Il donna au trésor de l’œuvre, selon ses moyens, soixante et un mille dariques d’or, cinq mille mines d’argent, et cent tuniques sacerdotales.", 'dederunt', 'numerus', 'v:ind.perf.act.3.sg', "un seul donateur au lieu de la communauté"),
      ],
      note="Segond a « dariques » pour solidos et « au trésor de l’œuvre » pour impensas operis."),
    Q('th-tempus-praeteritum', '1CH 24:1',
      target=('erant', 'v:ind.imperf.act.3.pl'),
      paed=True, fr="Or, voici quelles étaient les classes des fils d’Aaron. Fils d’Aaron: Nadab, Abihu, Éléazar et Ithamar.",
      gloss={'Nadab': 'Nadab', 'Abiu': 'Abihu'},
      dist=[
        ("Or, voici quelles sont les classes des fils d’Aaron. Fils d’Aaron: Nadab, Abihu, Éléazar et Ithamar.", 'erant', 'tempus', 'v:ind.praes.act.3.pl', "la répartition est actuelle"),
        ("Or, voici quelles furent les classes des fils d’Aaron. Fils d’Aaron: Nadab, Abihu, Éléazar et Ithamar.", 'erant', 'tempus', 'v:ind.perf.act.3.pl', "un état durable devient un fait ponctuel"),
        ("Or, voici quelles étaient les classes du fils d’Aaron. Fils d’Aaron: Nadab, Abihu, Éléazar et Ithamar.", 'filiis', 'numerus', 'n:dat.pl>n:dat.sg', "un seul fils"),
      ],
      note="Segond (« Voici les classes des fils d’Aaron ») ne rend pas erant ; rendu pédagogique."),
    Q('th-modus-imperativus', 'JER 3:4',
      target=('voca', 'v:imp.praes.act.2.sg'),
      paed=True, fr="Désormais du moins, appelle-moi: Mon père, tu es le guide de ma jeunesse.",
      dist=[
        ("Désormais du moins, appelez-moi: Mon père, tu es le guide de ma jeunesse.", 'voca', 'numerus', 'v:imp.praes.act.2.pl', "l’appel est demandé à plusieurs"),
        ("Désormais du moins, tu m’appelles: Mon père, tu es le guide de ma jeunesse.", 'voca', 'modus', 'v:ind.praes.act.2.sg', "une demande devient un constat"),
        ("Désormais du moins, appelle-moi: Mon père, il est le guide de ma jeunesse.", 'es', 'persona', 'v:ind.praes.act.2.sg>v:ind.praes.act.3.sg', "le guide n’est plus celui à qui l’on parle"),
      ],
      note="Segond a l’indicatif (« Tu cries vers moi ») et le passé (« Tu as été l’ami de ma jeunesse ») ; rendu pédagogique de l’impératif et du présent latins."),
    Q('th-vox', 'EST 1:6',
      target=('fulciebantur', 'v:ind.imperf.pass.3.pl'),
      la='qui eburneis circulis inserti erant, et columnis marmoreis fulciebantur',
      paed=True, fr="qui étaient passés dans des anneaux d’ivoire et soutenus par des colonnes de marbre",
      dist=[
        ("qui étaient passés dans des anneaux d’ivoire et soutenaient des colonnes de marbre", 'fulciebantur', 'vox', 'v:ind.imperf.act.3.pl', "les cordons deviennent ce qui soutient au lieu d’être soutenus"),
        ("qui étaient passés dans des anneaux d’ivoire et sont soutenus par des colonnes de marbre", 'fulciebantur', 'tempus', 'v:ind.praes.pass.3.pl', "le soutien est actuel au lieu d’appartenir au décor passé"),
        ("qui étaient passés dans des anneaux d’ivoire et soutenus par une colonne de marbre", 'columnis', 'numerus', 'n:abl.pl>n:abl.sg', "une seule colonne"),
      ],
      note="Verset de 338 caractères ; Segond (« à des anneaux d’argent et à des colonnes de marbre ») ne rend pas le verbe ; rendu pédagogique de la relative."),
    Q('th-tempus-futurum', 'ISA 4:6',
      target=('erit', 'v:ind.fut.act.3.sg'),
      dist=[
        ("Il y a un abri pour donner de l’ombre contre la chaleur du jour, Pour servir de refuge et d’asile contre l’orage et la pluie.", 'erit', 'tempus', 'v:ind.praes.act.3.sg', "l’abri existe déjà au lieu d’être promis"),
        ("Il y eut un abri pour donner de l’ombre contre la chaleur du jour, Pour servir de refuge et d’asile contre l’orage et la pluie.", 'erit', 'tempus', 'v:ind.perf.act.3.sg', "la promesse devient un fait passé"),
        ("Il y aura des abris pour donner de l’ombre contre la chaleur du jour, Pour servir de refuge et d’asile contre l’orage et la pluie.", 'tabernaculum', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs abris"),
      ],
      note="Segond rend « tabernaculum… in umbraculum » par « un abri pour donner de l’ombre »."),
    Q('th-numerus', 'EXO 37:17',
      target=('Fecit', 'v:ind.perf.act.3.sg'),
      gloss={'scyphi': 'coupes, calices'},
      dist=[
        ("Ils firent le chandelier d’or pur; il fit le chandelier d’or battu; son pied, sa tige, ses calices, ses pommes et ses fleurs, étaient d’une même pièce.", 'Fecit', 'numerus', 'v:ind.perf.act.3.pl', "plusieurs artisans au lieu de Béséléel seul"),
        ("Il fit le chandelier d’or pur; il fit le chandelier d’or battu; son pied, sa tige, ses calices, sa pomme et ses fleurs, étaient d’une même pièce.", 'sphærulæque', 'numerus', 'n:nom.pl>n:nom.sg', "une seule pomme"),
        ("Il fit le chandelier d’or pur; il fit le chandelier d’or battu; son pied, sa tige, ses calices, ses pommes et sa fleur, étaient d’une même pièce.", 'lilia', 'numerus', 'n:nom.pl>n:nom.sg', "une seule fleur"),
      ],
      note="Segond suit l’hébreu et dédouble « il fit » ; « procedebant » est rendu par « étaient d’une même pièce »."),
    Q('th-modus-imperativus', 'PSA 12:4',
      target=('Respice', 'v:imp.praes.act.2.sg'),
      dist=[
        ("Regardez, réponds-moi, Éternel, mon Dieu! Donne à mes yeux la clarté, Afin que je ne m’endorme pas du sommeil de la mort,", 'Respice', 'numerus', 'v:imp.praes.act.2.pl', "la prière s’adresse à plusieurs"),
        ("Tu regardes, réponds-moi, Éternel, mon Dieu! Donne à mes yeux la clarté, Afin que je ne m’endorme pas du sommeil de la mort,", 'Respice', 'modus', 'v:ind.praes.act.2.sg', "une prière devient un constat"),
        ("Regarde, réponds-moi, Éternel, mon Dieu! Donne à mon œil la clarté, Afin que je ne m’endorme pas du sommeil de la mort,", 'oculos', 'numerus', 'n:acc.pl>n:acc.sg', "un seul œil"),
      ],
      note="Segond (13:4) rend « exaudi » par « réponds-moi » et « Illumina oculos meos » par « Donne à mes yeux la clarté » ; la cible est Respice."),
    Q('th-modus-imperativus', 'EZE 6:11',
      target=('Percute', 'v:imp.praes.act.2.sg'),
      dist=[
        ("Ainsi parle le Seigneur, l’Éternel: Frappez de la main, frappe du pied, et dis: Hélas! Sur toutes les méchantes abominations de la maison d’Israël, Qui tombera par l’épée, par la famine et par la peste.", 'Percute', 'numerus', 'v:imp.praes.act.2.pl', "l’ordre s’adresse à plusieurs"),
        ("Ainsi parle le Seigneur, l’Éternel: Tu frappes de la main, frappe du pied, et dis: Hélas! Sur toutes les méchantes abominations de la maison d’Israël, Qui tombera par l’épée, par la famine et par la peste.", 'Percute', 'modus', 'v:ind.praes.act.2.sg', "un ordre devient un constat"),
        ("Ainsi parle le Seigneur, l’Éternel: Frappe des mains, frappe du pied, et dis: Hélas! Sur toutes les méchantes abominations de la maison d’Israël, Qui tombera par l’épée, par la famine et par la peste.", 'manum', 'numerus', 'n:acc.sg>n:acc.pl', "les deux mains"),
      ],
      note="Segond rend « Percute manum tuam et allide pedem tuum » par « Frappe de la main, frappe du pied »."),
    Q('th-numerus', 'DEU 25:3',
      target=('excedant', 'v:subj.praes.act.3.pl'),
      paed=True, fr="de sorte seulement qu’ils ne dépassent pas le nombre de quarante: de peur que ton frère, honteusement déchiré, ne s’en aille sous tes yeux.",
      dist=[
        ("de sorte seulement qu’il ne dépasse pas le nombre de quarante: de peur que ton frère, honteusement déchiré, ne s’en aille sous tes yeux.", 'excedant', 'numerus', 'v:subj.praes.act.3.sg', "un seul exécuteur au lieu de plusieurs"),
        ("de sorte seulement qu’ils ne dépassent pas le nombre de quarante: de peur que tes frères, honteusement déchirés, ne s’en aillent sous tes yeux.", 'frater', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs frères"),
        ("de sorte seulement qu’ils ne dépassent pas le nombre de quarante: de peur que ton frère, honteusement déchiré, ne s’en aille sous ton œil.", 'oculos', 'numerus', 'n:acc.pl>n:acc.sg', "un seul œil"),
      ],
      note="Segond paraphrase (« Il ne lui fera pas donner plus de quarante coups ») ; rendu pédagogique."),
    Q('th-persona', '1PE 2:8',
      target=('offendunt', 'v:ind.praes.act.3.pl'),
      dist=[
        ("nous nous y heurtons pour n’avoir pas cru à la parole, et c’est à cela que nous sommes destinés.", 'offendunt', 'persona', 'v:ind.praes.act.1.pl', "l’apôtre s’inclut parmi ceux qui se heurtent"),
        ("vous vous y heurtez pour n’avoir pas cru à la parole, et c’est à cela que vous êtes destinés.", 'offendunt', 'persona', 'v:ind.praes.act.2.pl', "les lecteurs deviennent ceux qui se heurtent"),
        ("il s’y heurte pour n’avoir pas cru à la parole, et c’est à cela qu’il est destiné.", 'offendunt', 'numerus', 'v:ind.praes.act.3.sg', "un seul incrédule"),
      ],
      note="Segond place « lapis offensionis, et petra scandali » au verset 7 ; son verset 8 rend la relative, avec « pour n’avoir pas cru à la parole » pour offendunt verbo, nec credunt."),
    Q('th-tempus-praeteritum', '2SA 21:8',
      target=('Tulit', 'v:ind.perf.act.3.sg'),
      gloss={'Respha': 'Ritspa', 'Aja': 'Ajja', 'Armoni': 'Armoni', 'Michol': 'Mérab (Vulgate : Michol)', 'Hadrieli': 'Adriel', 'Molathi': 'Mehola'},
      dist=[
        ("Mais le roi prend les deux fils que Ritspa, fille d’Ajja, avait enfantés à Saül, Armoni et Mephiboscheth, et les cinq fils que Mérab, fille de Saül, avait enfantés à Adriel de Mehola, fils de Barzillaï;", 'Tulit', 'tempus', 'v:ind.praes.act.3.sg', "l’arrestation est actuelle"),
        ("Mais le roi prendra les deux fils que Ritspa, fille d’Ajja, avait enfantés à Saül, Armoni et Mephiboscheth, et les cinq fils que Mérab, fille de Saül, avait enfantés à Adriel de Mehola, fils de Barzillaï;", 'Tulit', 'tempus', 'v:ind.fut.act.3.sg', "l’arrestation est annoncée"),
        ("Mais les rois prirent les deux fils que Ritspa, fille d’Ajja, avait enfantés à Saül, Armoni et Mephiboscheth, et les cinq fils que Mérab, fille de Saül, avait enfantés à Adriel de Mehola, fils de Barzillaï;", 'rex', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs rois"),
      ],
      note="Segond a le plus-que-parfait (« avait enfantés ») pour peperit et « Mérab » pour Michol ; la cible est Tulit."),
    Q('th-tempus-futurum', 'HEB 13:4',
      target=('judicabit', 'v:ind.fut.act.3.sg'),
      dist=[
        ("Que le mariage soit honoré de tous, et le lit conjugal exempt de souillure, car Dieu juge les impudiques et les adultères.", 'judicabit', 'tempus', 'v:ind.praes.act.3.sg', "le jugement est actuel au lieu d’être annoncé"),
        ("Que le mariage soit honoré de tous, et le lit conjugal exempt de souillure, car Dieu jugea les impudiques et les adultères.", 'judicabit', 'tempus', 'v:ind.perf.act.3.sg', "le jugement devient un fait passé"),
        ("Que le mariage soit honoré de tous, et le lit conjugal exempt de souillure, car Dieu jugera les impudiques et l’adultère.", 'adulteros', 'numerus', 'n:acc.pl>n:acc.sg', "un seul adultère"),
      ],
      note="Segond tourne la phrase nominale « Honorabile connubium » en souhait (« Que le mariage soit honoré ») ; la cible est judicabit."),
    Q('th-numerus', 'ISA 24:8',
      target=('gaudium', 'n:nom.sg'),
      dist=[
        ("Les joies des tambourins ont cessé, La gaîté bruyante a pris fin, La joie de la harpe a cessé.", 'gaudium', 'numerus', 'n:nom.pl', "plusieurs joies"),
        ("La joie du tambourin a cessé, La gaîté bruyante a pris fin, La joie de la harpe a cessé.", 'tympanorum', 'numerus', 'n:gen.pl>n:gen.sg', "un seul tambourin"),
        ("La joie des tambourins a cessé, La gaîté bruyante a pris fin, La joie des harpes a cessé.", 'citharæ', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs harpes"),
      ],
      note="Segond rend « sonitus lætantium » par « La gaîté bruyante » et « dulcedo » par « La joie »."),
    Q('th-vox', 'ISA 33:4',
      target=('colligitur', 'v:ind.praes.pass.3.sg'),
      paed=True, fr="Et vos dépouilles seront rassemblées comme est ramassée la sauterelle, comme lorsque les fossés en seront remplis.",
      dist=[
        ("Et vos dépouilles seront rassemblées comme ramasse la sauterelle, comme lorsque les fossés en seront remplis.", 'colligitur', 'vox', 'v:ind.praes.act.3.sg', "la sauterelle devient celle qui ramasse au lieu d’être ramassée"),
        ("Et vos dépouilles seront rassemblées comme sera ramassée la sauterelle, comme lorsque les fossés en seront remplis.", 'colligitur', 'tempus', 'v:ind.fut.pass.3.sg', "la comparaison est reportée dans l’avenir"),
        ("Et votre dépouille sera rassemblée comme est ramassée la sauterelle, comme lorsque les fossés en seront remplis.", 'spolia', 'numerus', 'n:nom.pl>n:nom.sg', "une seule dépouille"),
      ],
      note="Segond suit l’hébreu (« Comme moissonne la sauterelle », actif) ; la Vulgate a le passif colligitur ; rendu pédagogique."),
    Q('th-modus-imperativus', 'JER 47:6',
      target=('ingredere', 'v:imp.praes.act.2.sg'),
      dist=[
        ("Ah! Épée de l’Éternel, quand te reposeras-tu? Rentrez dans votre fourreau, Arrête, et sois tranquille!", 'ingredere', 'numerus', 'v:imp.praes.act.2.pl', "l’ordre s’adresse à plusieurs épées"),
        ("Ah! Épée de l’Éternel, quand te reposeras-tu? Rentre dans ton fourreau, Arrête, et tu es tranquille!", 'sile', 'modus', 'v:imp.praes.act.2.sg>v:ind.praes.act.2.sg', "un ordre devient un constat"),
        ("Ah! Épée de l’Éternel, quand se reposera-t-elle? Rentre dans ton fourreau, Arrête, et sois tranquille!", 'quiesces', 'persona', 'v:ind.fut.act.2.sg>v:ind.fut.act.3.sg', "on parle de l’épée au lieu de s’adresser à elle"),
      ],
      note="Segond rend « refrigerare » par « Arrête » ; la cible est l’impératif déponent ingredere."),
    Q('th-tempus-futurum', 'EXO 28:37',
      target=('Ligabisque', 'v:ind.fut.act.2.sg'),
      gloss={'hyacinthina': 'de couleur hyacinthe (bleu violet)'},
      dist=[
        ("Tu l’attaches avec un cordon bleu sur la tiare, sur le devant de la tiare.", 'Ligabisque', 'tempus', 'v:ind.praes.act.2.sg', "le geste est décrit au lieu d’être prescrit"),
        ("Tu l’attachas avec un cordon bleu sur la tiare, sur le devant de la tiare.", 'Ligabisque', 'tempus', 'v:ind.perf.act.2.sg', "le geste devient un fait passé"),
        ("Il l’attachera avec un cordon bleu sur la tiare, sur le devant de la tiare.", 'Ligabisque', 'persona', 'v:ind.fut.act.3.sg', "un tiers exécute l’ordre au lieu de Moïse"),
      ],
      note="Segond ajoute « sur le devant de la tiare » d’après l’hébreu."),
    Q('th-persona', 'MAT 23:33',
      target=('fugietis', 'v:ind.fut.act.2.pl'),
      dist=[
        ("Serpents, race de vipères! Comment échapperons-nous au châtiment de la géhenne?", 'fugietis', 'persona', 'v:ind.fut.act.1.pl', "Jésus s’inclut parmi les menacés"),
        ("Serpents, race de vipères! Comment échapperont-ils au châtiment de la géhenne?", 'fugietis', 'persona', 'v:ind.fut.act.3.pl', "la menace vise des tiers au lieu des interlocuteurs"),
        ("Serpents, race de vipères! Comment échapperas-tu au châtiment de la géhenne?", 'fugietis', 'numerus', 'v:ind.fut.act.2.sg', "un seul interlocuteur"),
      ]),
    Q('th-tempus-futurum', 'JER 7:33',
      target=('erit', 'v:ind.fut.act.3.sg'),
      paed=True, fr="Et le cadavre de ce peuple sera en pâture aux oiseaux du ciel et aux bêtes de la terre, et il n’y aura personne pour les chasser.",
      dist=[
        ("Et le cadavre de ce peuple est en pâture aux oiseaux du ciel et aux bêtes de la terre, et il n’y aura personne pour les chasser.", 'erit', 'tempus', 'v:ind.praes.act.3.sg', "le châtiment est actuel au lieu d’être annoncé"),
        ("Et le cadavre de ce peuple fut en pâture aux oiseaux du ciel et aux bêtes de la terre, et il n’y aura personne pour les chasser.", 'erit', 'tempus', 'v:ind.perf.act.3.sg', "le châtiment devient un fait passé"),
        ("Et le cadavre de ce peuple sera en pâture à l’oiseau du ciel et aux bêtes de la terre, et il n’y aura personne pour les chasser.", 'volucribus', 'numerus', 'n:dat.pl>n:dat.sg', "un seul oiseau"),
      ],
      note="Segond a le pluriel « Les cadavres… seront » pour le singulier collectif morticinum… erit ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'JOS 11:3',
      target=('habitabat', 'v:ind.imperf.act.3.sg'),
      paed=True, fr="le Cananéen aussi, à l’orient et à l’occident, l’Amoréen, le Héthien, le Phérézien et le Jébusien dans les montagnes, le Hévien aussi qui habitait au pied de l’Hermon, au pays de Mitspa.",
      gloss={'Hermon': 'Hermon', 'Maspha': 'Mitspa'},
      dist=[
        ("le Cananéen aussi, à l’orient et à l’occident, l’Amoréen, le Héthien, le Phérézien et le Jébusien dans les montagnes, le Hévien aussi qui habite au pied de l’Hermon, au pays de Mitspa.", 'habitabat', 'tempus', 'v:ind.praes.act.3.sg', "le séjour est actuel"),
        ("le Cananéen aussi, à l’orient et à l’occident, l’Amoréen, le Héthien, le Phérézien et le Jébusien dans les montagnes, le Hévien aussi qui habita au pied de l’Hermon, au pays de Mitspa.", 'habitabat', 'tempus', 'v:ind.perf.act.3.sg', "un séjour durable devient un fait ponctuel"),
        ("le Cananéen aussi, à l’orient et à l’occident, l’Amoréen, le Héthien, le Phérézien et le Jébusien dans la montagne, le Hévien aussi qui habitait au pied de l’Hermon, au pays de Mitspa.", 'montanis', 'numerus', 'a:abl.pl.m>a:abl.sg.m', "une seule montagne"),
      ],
      note="Segond a les pluriels (« aux Cananéens… ») pour les singuliers collectifs latins et ne rend pas habitabat ; rendu pédagogique."),
    Q('th-tempus-futurum', 'DEU 7:26',
      target=('inferes', 'v:ind.fut.act.2.sg'),
      dist=[
        ("Tu n’introduis point une chose abominable dans ta maison, afin que tu ne sois pas, comme cette chose, dévoué par interdit; tu l’auras en horreur, tu l’auras en abomination, car c’est une chose dévouée par interdit.", 'inferes', 'tempus', 'v:ind.praes.act.2.sg', "la défense devient un constat"),
        ("Tu n’introduisis point une chose abominable dans ta maison, afin que tu ne sois pas, comme cette chose, dévoué par interdit; tu l’auras en horreur, tu l’auras en abomination, car c’est une chose dévouée par interdit.", 'inferes', 'tempus', 'v:ind.perf.act.2.sg', "la défense devient un fait passé"),
        ("Tu n’introduiras point une chose abominable dans tes maisons, afin que tu ne sois pas, comme cette chose, dévoué par interdit; tu l’auras en horreur, tu l’auras en abomination, car c’est une chose dévouée par interdit.", 'domum', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs maisons"),
      ],
      note="Segond rend « quippiam ex idolo » par « une chose abominable » et « anathema » par « dévoué par interdit »."),
    Q('th-persona', '1CH 5:19',
      target=('Dimicaverunt', 'v:ind.perf.act.3.pl'),
      gloss={'Agareos': 'Hagaréniens', 'Naphis': 'Naphisch', 'Nodab': 'Nodab'},
      dist=[
        ("Nous fîmes la guerre aux Hagaréniens, à Jethur, à Naphisch et à Nodab.", 'Dimicaverunt', 'persona', 'v:ind.perf.act.1.pl', "le narrateur s’inclut parmi les combattants"),
        ("Vous fîtes la guerre aux Hagaréniens, à Jethur, à Naphisch et à Nodab.", 'Dimicaverunt', 'persona', 'v:ind.perf.act.2.pl', "la guerre est attribuée aux interlocuteurs"),
        ("Il fit la guerre aux Hagaréniens, à Jethur, à Naphisch et à Nodab.", 'Dimicaverunt', 'numerus', 'v:ind.perf.act.3.sg', "un seul combattant au lieu des tribus"),
      ],
      note="Segond rend « Ituræi » par « Jethur »."),
    Q('th-tempus-futurum', 'LEV 18:20',
      target=('coibis', 'v:ind.fut.act.2.sg'),
      gloss={'commistione': 'mélange, union'},
      dist=[
        ("Tu n’as point commerce avec la femme de ton prochain, pour te souiller avec elle.", 'coibis', 'tempus', 'v:ind.praes.act.2.sg', "la défense devient un constat"),
        ("Tu n’eus point commerce avec la femme de ton prochain, pour te souiller avec elle.", 'coibis', 'tempus', 'v:ind.perf.act.2.sg', "la défense devient un fait passé"),
        ("Vous n’aurez point commerce avec la femme de votre prochain, pour vous souiller avec elle.", 'coibis', 'numerus', 'v:ind.fut.act.2.pl', "la défense s’adresse à plusieurs"),
      ],
      note="Segond rend « seminis commistione maculaberis » par « pour te souiller avec elle » ; la cible est coibis."),
    Q('th-tempus-futurum', 'LEV 21:7',
      target=('ducent', 'v:ind.fut.act.3.pl'),
      dist=[
        ("Ils ne prennent point une femme prostituée ou déshonorée, ils ne prendront point une femme répudiée par son mari, car ils sont saints pour leur Dieu.", 'ducent', 'tempus', 'v:ind.praes.act.3.pl', "la règle est constatée au lieu d’être prescrite"),
        ("Ils ne prirent point une femme prostituée ou déshonorée, ils ne prendront point une femme répudiée par son mari, car ils sont saints pour leur Dieu.", 'ducent', 'tempus', 'v:ind.perf.act.3.pl', "la règle devient un fait passé"),
        ("Il ne prendra point une femme prostituée ou déshonorée, ils ne prendront point une femme répudiée par son mari, car ils sont saints pour leur Dieu.", 'ducent', 'numerus', 'v:ind.fut.act.3.sg', "un seul prêtre au lieu de tous"),
      ],
      note="Segond rend « Scortum et vile prostibulum non ducent uxorem » par « Ils ne prendront point une femme prostituée ou déshonorée »."),
    Q('th-numerus', 'PSA 101:21',
      target=('gemitus', 'n:acc.pl'),
      dist=[
        ("Pour écouter le gémissement des captifs, Pour délivrer ceux qui vont périr,", 'gemitus', 'numerus', 'n:acc.sg', "un seul gémissement"),
        ("Pour écouter les gémissements du captif, Pour délivrer ceux qui vont périr,", 'compeditorum', 'numerus', 'v:part.perf.pass.gen.pl.m>v:part.perf.pass.gen.sg.m', "un seul captif"),
        ("Pour écouter les gémissements des captifs, Pour délivrer celui qui va périr,", 'filios', 'numerus', 'n:acc.pl>n:acc.sg', "un seul délivré"),
      ],
      note="Segond (102:21) rend les subjonctifs « ut audiret… ut solveret » par des infinitifs et « filios interemptorum » par « ceux qui vont périr » ; la cible est le nom gemitus."),
    Q('th-tempus-praeteritum', 'GAL 2:3',
      target=('erat', 'v:ind.imperf.act.3.sg'),
      dist=[
        ("Mais Tite, qui est avec moi, et qui était Grec, ne fut pas même contraint de se faire circoncire.", 'erat', 'tempus', 'v:ind.praes.act.3.sg', "la présence de Tite est actuelle"),
        ("Mais Tite, qui fut avec moi, et qui était Grec, ne fut pas même contraint de se faire circoncire.", 'erat', 'tempus', 'v:ind.perf.act.3.sg', "un compagnonnage durable devient ponctuel"),
        ("Mais Tite, qui était avec moi, et qui est Grec, ne fut pas même contraint de se faire circoncire.", 'esset', 'tempus', 'v:subj.imperf.act.3.sg>v:subj.praes.act.3.sg', "l’origine de Tite est rapportée au présent"),
      ],
      note="Segond rend « gentilis » par « Grec » et « cum esset » par « et qui était »."),
    Q('th-tempus-praeteritum', '1KI 11:5',
      target=('colebat', 'v:ind.imperf.act.3.sg'),
      paed=True, fr="Mais Salomon honorait Astarté, déesse des Sidoniens, et Moloch, idole des Ammonites.",
      dist=[
        ("Mais Salomon honore Astarté, déesse des Sidoniens, et Moloch, idole des Ammonites.", 'colebat', 'tempus', 'v:ind.praes.act.3.sg', "le culte est actuel"),
        ("Mais Salomon honora Astarté, déesse des Sidoniens, et Moloch, idole des Ammonites.", 'colebat', 'tempus', 'v:ind.perf.act.3.sg', "un culte habituel devient un acte ponctuel"),
        ("Mais Salomon honorait Astarté, déesse du Sidonien, et Moloch, idole des Ammonites.", 'Sidoniorum', 'numerus', 'a:gen.pl.m>a:gen.sg.m', "un seul Sidonien"),
      ],
      note="Segond suit l’hébreu (« alla après Astarté… Milcom, l’abomination ») ; la Vulgate a colebat et Moloch ; rendu pédagogique."),
    Q('th-numerus', 'SIR 29:29',
      target=('asserum', 'n:gen.pl'),
      paed=True, fr="Mieux vaut la vie du pauvre sous un toit de planches que des festins splendides à l’étranger sans domicile.",
      dist=[
        ("Mieux vaut la vie du pauvre sous un toit de planche que des festins splendides à l’étranger sans domicile.", 'asserum', 'numerus', 'n:gen.sg', "une seule planche"),
        ("Mieux vaut la vie des pauvres sous un toit de planches que des festins splendides à l’étranger sans domicile.", 'pauperis', 'numerus', 'a:gen.sg.m>a:gen.pl.m', "plusieurs pauvres"),
        ("Mieux vaut la vie du pauvre sous un toit de planches qu’un festin splendide à l’étranger sans domicile.", 'splendidæ', 'numerus', 'a:nom.pl.f>a:nom.sg.f', "un seul festin"),
      ],
      note="Livre absent de Segond ; rendu pédagogique (victus : nourriture, subsistance, rendu « la vie »)."),
]
