# sheet_006 → batch_006
# skipped: 1CH 15:18 (list of names, no verb)
# skipped: 1CH 1:38 (list of names, no verb)
# skipped: EZE 27:23 (list of place names, no verb)
ITEMS = [
    Q('th-tempus-praeteritum', 'NUM 30:13',
      target=('contradixit', 'v:ind.perf.act.3.sg'),
      paed=True, fr="Mais si son mari s’y oppose aussitôt, elle ne sera pas tenue pour coupable de sa promesse, parce que son mari s’y est opposé, et le Seigneur lui sera propice.",
      dist=[
        ("Mais si son mari s’y oppose aussitôt, elle ne sera pas tenue pour coupable de sa promesse, parce que son mari s’y oppose, et le Seigneur lui sera propice.", 'contradixit', 'tempus', 'v:ind.praes.act.3.sg', "l’opposition du mari est actuelle et non accomplie"),
        ("Mais si son mari s’y oppose aussitôt, elle ne sera pas tenue pour coupable de sa promesse, parce que son mari s’y opposera, et le Seigneur lui sera propice.", 'contradixit', 'tempus', 'v:ind.fut.act.3.sg', "l’opposition du mari est à venir"),
        ("Mais si son mari s’y oppose aussitôt, elle ne sera pas tenue pour coupable de ses promesses, parce que son mari s’y est opposé, et le Seigneur lui sera propice.", 'promissionis', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs promesses"),
      ],
      note="Segond (« si son mari les annule le jour où il en a connaissance ») suit l’hébreu et découpe le verset autrement ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'JER 11:16',
      target=('exarsit', 'v:ind.perf.act.3.sg'),
      paed=True, fr="Olivier fertile, beau, fécond, magnifique : tel est le nom que le Seigneur t’a donné ; au bruit d’une parole, un grand feu s’est allumé en lui, et ses rameaux ont été brûlés.",
      dist=[
        ("Olivier fertile, beau, fécond, magnifique : tel est le nom que le Seigneur t’a donné ; au bruit d’une parole, un grand feu s’allume en lui, et ses rameaux ont été brûlés.", 'exarsit', 'tempus', 'v:ind.praes.act.3.sg', "l’embrasement est en cours"),
        ("Olivier fertile, beau, fécond, magnifique : tel est le nom que le Seigneur t’a donné ; au bruit d’une parole, un grand feu s’allumera en lui, et ses rameaux ont été brûlés.", 'exarsit', 'tempus', 'v:ind.fut.act.3.sg', "l’embrasement est annoncé"),
        ("Olivier fertile, beau, fécond, magnifique : tel est le nom que le Seigneur t’a donné ; au bruit d’une parole, un grand feu s’est allumé en lui, et son rameau a été brûlé.", 'fruteta', 'numerus', 'n:nom.pl>n:nom.sg', "un seul rameau"),
      ],
      note="Segond (« t’avait donné », « il l’embrase », « sont brisés ») s’écarte des temps et du texte de la Vulgate ; rendu pédagogique."),
    Q('th-modus-imperativus', 'PSA 146:1',
      target=('Laudate', 'v:imp.praes.act.2.pl'),
      dist=[
        ("Loue l’Éternel! Car il est beau de célébrer notre Dieu, Car il est doux, il est bienséant de le louer.", 'Laudate', 'numerus', 'v:imp.praes.act.2.sg', "l’appel s’adresse à une seule personne"),
        ("Vous louez l’Éternel! Car il est beau de célébrer notre Dieu, Car il est doux, il est bienséant de le louer.", 'Laudate', 'modus', 'v:ind.praes.act.2.pl', "un appel devient un constat"),
        ("Puissiez-vous louer l’Éternel! Car il est beau de célébrer notre Dieu, Car il est doux, il est bienséant de le louer.", 'Laudate', 'modus', 'v:subj.praes.act.2.pl', "un ordre devient un souhait"),
      ],
      note="Segond (147:1) ne rend pas « Alleluja » et paraphrase « bonus est psalmus … jucunda decoraque laudatio »."),
    Q('th-modus-imperativus', 'JER 49:3',
      target=('plangite', 'v:imp.praes.act.2.pl'),
      gloss={'Hai': 'Aï', 'Rabbath': 'Rabba', 'Melchom': 'Malcom'},
      dist=[
        ("Pousse des gémissements, Hesbon, car Aï est ravagée! Poussez des cris, filles de Rabba, revêtez-vous de sacs, Lamente-toi, et courez çà et là le long des murailles! Car Malcom s’en va en captivité, Avec ses prêtres et avec ses chefs.", 'plangite', 'numerus', 'v:imp.praes.act.2.sg', "l’ordre de se lamenter vise une seule personne"),
        ("Pousse des gémissements, Hesbon, car Aï est ravagée! Poussez des cris, filles de Rabba, revêtez-vous de sacs, vous vous lamentez, et courez çà et là le long des murailles! Car Malcom s’en va en captivité, Avec ses prêtres et avec ses chefs.", 'plangite', 'modus', 'v:ind.praes.act.2.pl', "un ordre devient un constat"),
        ("Pousse des gémissements, Hesbon, car Aï est ravagée! Poussez des cris, filles de Rabba, revêtez-vous de sacs, Lamentez-vous, et courez çà et là le long des murailles! Car Malcom s’en va en captivité, Avec son prêtre et avec ses chefs.", 'sacerdotes', 'numerus', 'n:acc.pl>n:acc.sg', "un seul prêtre"),
      ],
      note="Segond rend le futur passif « ducetur » par « s’en va »."),
    Q('th-tempus-praeteritum', '2CH 10:15',
      target=('acquievit', 'v:ind.perf.act.3.sg'),
      gloss={'Silonitis': 'de Silo (Silonite)', 'Nabat': 'Nebath'},
      dist=[
        ("Ainsi le roi n’écoute point le peuple; car cela fut dirigé par Dieu, en vue de l’accomplissement de la parole que l’Éternel avait dite par Achija de Silo à Jéroboam, fils de Nebath.", 'acquievit', 'tempus', 'v:ind.praes.act.3.sg', "le refus du roi est actuel"),
        ("Ainsi le roi n’écoutera point le peuple; car cela fut dirigé par Dieu, en vue de l’accomplissement de la parole que l’Éternel avait dite par Achija de Silo à Jéroboam, fils de Nebath.", 'acquievit', 'tempus', 'v:ind.fut.act.3.sg', "le refus du roi est annoncé"),
        ("Ainsi le roi n’écouta point les peuples; car cela fut dirigé par Dieu, en vue de l’accomplissement de la parole que l’Éternel avait dite par Achija de Silo à Jéroboam, fils de Nebath.", 'populi', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs peuples"),
      ],
      note="Segond explicite « le roi », rend « populi precibus » par « le peuple » et « erat voluntatis Dei » par « cela fut dirigé par Dieu »."),
    Q('th-tempus-praeteritum', 'LUK 7:29',
      target=('justificaverunt', 'v:ind.perf.act.3.pl'),
      lemma={'Joannis': 'ioannes'},
      dist=[
        ("Et tout le peuple qui l’a entendu et même les publicains justifient Dieu, en se faisant baptiser du baptême de Jean;", 'justificaverunt', 'tempus', 'v:ind.praes.act.3.pl', "la reconnaissance de Dieu est actuelle"),
        ("Et tout le peuple qui l’a entendu et même les publicains justifieront Dieu, en se faisant baptiser du baptême de Jean;", 'justificaverunt', 'tempus', 'v:ind.fut.act.3.pl', "la reconnaissance de Dieu est annoncée"),
        ("Et tout le peuple qui l’a entendu et même le publicain ont justifié Dieu, en se faisant baptiser du baptême de Jean;", 'publicani', 'numerus', 'n:nom.pl>n:nom.sg', "un seul publicain"),
      ],
      note="Segond rend le participe « audiens » par « qui l’a entendu » et « baptizati » par « en se faisant baptiser »."),
    Q('th-tempus-futurum', 'AMO 1:5',
      target=('conteram', 'v:ind.fut.act.1.sg'),
      paed=True, fr="Et je briserai le verrou de Damas, et j’exterminerai l’habitant du champ de l’idole et celui qui tient le sceptre de la maison de plaisir ; et le peuple de Syrie sera transféré à Cyrène, dit le Seigneur.",
      dist=[
        ("Et je brise le verrou de Damas, et j’exterminerai l’habitant du champ de l’idole et celui qui tient le sceptre de la maison de plaisir ; et le peuple de Syrie sera transféré à Cyrène, dit le Seigneur.", 'conteram', 'tempus', 'v:ind.praes.act.1.sg', "le châtiment est en cours"),
        ("Et j’ai brisé le verrou de Damas, et j’exterminerai l’habitant du champ de l’idole et celui qui tient le sceptre de la maison de plaisir ; et le peuple de Syrie sera transféré à Cyrène, dit le Seigneur.", 'conteram', 'tempus', 'v:ind.perf.act.1.sg', "le châtiment est déjà accompli"),
        ("Et il brisera le verrou de Damas, et j’exterminerai l’habitant du champ de l’idole et celui qui tient le sceptre de la maison de plaisir ; et le peuple de Syrie sera transféré à Cyrène, dit le Seigneur.", 'conteram', 'persona', 'v:ind.fut.act.3.sg', "le châtiment n’est plus l’œuvre de Dieu qui parle"),
      ],
      note="Segond garde les noms hébreux (« Bikath-Aven », « Beth-Éden », « Kir ») là où la Vulgate traduit ; rendu pédagogique."),
    Q('th-tempus-futurum', 'LEV 13:43',
      target=('condemnabit', 'v:ind.fut.act.3.sg'),
      paed=True, fr="et que le prêtre l’a constaté, il le déclarera atteint d’une lèpre indubitable, qui a paru sur la partie chauve.",
      dist=[
        ("et que le prêtre l’a constaté, il le déclare atteint d’une lèpre indubitable, qui a paru sur la partie chauve.", 'condemnabit', 'tempus', 'v:ind.praes.act.3.sg', "le verdict est actuel"),
        ("et que le prêtre l’a constaté, il l’a déclaré atteint d’une lèpre indubitable, qui a paru sur la partie chauve.", 'condemnabit', 'tempus', 'v:ind.perf.act.3.sg', "le verdict est déjà rendu"),
        ("et que le prêtre l’a constaté, il le déclarait atteint d’une lèpre indubitable, qui a paru sur la partie chauve.", 'condemnabit', 'tempus', 'v:ind.imperf.act.3.sg', "le verdict devient une pratique passée"),
      ],
      note="Segond (« Le sacrificateur l’examinera. S’il y a une tumeur… ») découpe et paraphrase autrement ; rendu pédagogique."),
    Q('th-persona', 'GAL 1:14',
      target=('proficiebam', 'v:ind.imperf.act.1.sg'),
      dist=[
        ("et comment il était plus avancé dans le judaïsme que beaucoup de ceux de son âge et de sa nation, étant animé d’un zèle excessif pour les traditions de ses pères.", 'proficiebam', 'persona', 'v:ind.imperf.act.3.sg', "Paul ne parle plus de lui-même"),
        ("et comment nous étions plus avancés dans le judaïsme que beaucoup de ceux de notre âge et de notre nation, étant animés d’un zèle excessif pour les traditions de nos pères.", 'proficiebam', 'numerus', 'v:ind.imperf.act.1.pl', "Paul s’associe d’autres personnes"),
        ("et comment j’étais plus avancé dans le judaïsme que beaucoup de ceux de mon âge et de ma nation, étant animé d’un zèle excessif pour la tradition de mes pères.", 'traditionum', 'numerus', 'n:gen.pl>n:gen.sg', "une seule tradition"),
      ],
      note="Segond rend « abundantius æmulator existens » par « étant animé d’un zèle excessif »."),
    Q('th-tempus-praeteritum', 'JDG 3:21',
      target=('tulit', 'v:ind.perf.act.3.sg'),
      gloss={'Aod': 'Éhud'},
      dist=[
        ("Alors Éhud avança la main gauche, tire l’épée de son côté droit, et la lui enfonça dans le ventre.", 'tulit', 'tempus', 'v:ind.praes.act.3.sg', "le geste est présenté comme actuel"),
        ("Alors Éhud avança la main gauche, tirera l’épée de son côté droit, et la lui enfonça dans le ventre.", 'tulit', 'tempus', 'v:ind.fut.act.3.sg', "le geste est annoncé"),
        ("Alors Éhud avança la main gauche, tirait l’épée de son côté droit, et la lui enfonça dans le ventre.", 'tulit', 'tempus', 'v:ind.imperf.act.3.sg', "un geste ponctuel devient une action qui dure"),
      ],
      note="Segond rend « de dextro femore suo » par « de son côté droit »."),
    Q('th-tempus-praeteritum', 'WIS 7:22',
      target=('vetat', 'v:ind.praes.act.3.sg'),
      paed=True, fr="Car il y a en elle un esprit d’intelligence, saint, unique, multiple, subtil, éloquent, mobile, sans souillure, sûr, doux, aimant le bien, pénétrant, que rien n’empêche, bienfaisant,",
      dist=[
        ("Car il y a en elle un esprit d’intelligence, saint, unique, multiple, subtil, éloquent, mobile, sans souillure, sûr, doux, aimant le bien, pénétrant, que rien n’a empêché, bienfaisant,", 'vetat', 'tempus', 'v:ind.perf.act.3.sg', "une liberté permanente devient un fait passé"),
        ("Car il y a en elle un esprit d’intelligence, saint, unique, multiple, subtil, éloquent, mobile, sans souillure, sûr, doux, aimant le bien, pénétrant, que rien n’empêchera, bienfaisant,", 'vetat', 'tempus', 'v:ind.fut.act.3.sg', "une liberté permanente devient une promesse"),
        ("Car il y a en elle un esprit d’intelligence, saint, unique, multiple, subtil, éloquent, mobile, sans souillure, sûr, doux, aimant le bien, pénétrant, que rien n’empêchait, bienfaisant,", 'vetat', 'tempus', 'v:ind.imperf.act.3.sg', "une liberté permanente devient un état passé"),
      ],
      note="Livre absent de Segond ; rendu pédagogique."),
    Q('th-modus-subiunctivus', 'JUD 1:9',
      target=('Imperet', 'v:subj.praes.act.3.sg'),
      dist=[
        ("Or, l’archange Michel, lorsqu’il contestait avec le diable et lui disputait le corps de Moïse, n’osa pas porter contre lui un jugement injurieux, mais il dit: Le Seigneur te réprime!", 'Imperet', 'modus', 'v:ind.praes.act.3.sg', "un souhait devient un constat"),
        ("Or, l’archange Michel, lorsqu’il contestait avec le diable et lui disputait le corps de Moïse, n’osa pas porter contre lui un jugement injurieux, mais il dit: Le Seigneur te réprimera!", 'Imperet', 'modus', 'v:ind.fut.act.3.sg', "un souhait devient une prédiction"),
        ("Or, l’archange Michel, lorsqu’il contestait avec le diable et lui disputait le corps de Moïse, n’osa pas porter contre lui un jugement injurieux, mais il dira: Que le Seigneur te réprime!", 'dixit', 'tempus', 'v:ind.perf.act.3.sg>v:ind.fut.act.3.sg', "la parole de Michel est à venir"),
      ],
      note="Segond rend « disputans altercaretur » par « contestait … et lui disputait »."),
    Q('th-tempus-praeteritum', 'PRO 25:20',
      target=('nocet', 'v:ind.praes.act.3.sg'),
      la='Sicut tinea vestimento, et vermis ligno, ita tristitia viri nocet cordi.',
      paed=True, fr="Comme la teigne au vêtement et le ver au bois, ainsi la tristesse de l’homme nuit au cœur.",
      dist=[
        ("Comme la teigne au vêtement et le ver au bois, ainsi la tristesse de l’homme a nui au cœur.", 'nocet', 'tempus', 'v:ind.perf.act.3.sg', "une vérité générale devient un fait passé"),
        ("Comme la teigne au vêtement et le ver au bois, ainsi la tristesse de l’homme nuira au cœur.", 'nocet', 'tempus', 'v:ind.fut.act.3.sg', "une vérité générale devient une prédiction"),
        ("Comme la teigne au vêtement et le ver au bois, ainsi la tristesse des hommes nuit au cœur.", 'viri', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs hommes"),
      ],
      note="Segond ne traduit que les deux premières phrases (hébreu) ; la troisième vient de la LXX ; rendu pédagogique."),
    Q('th-tempus-futurum', 'JOB 22:26',
      target=('elevabis', 'v:ind.fut.act.2.sg'),
      gloss={'deliciis': 'délices'},
      dist=[
        ("Alors tu feras du Tout-Puissant tes délices, Tu élèves vers Dieu ta face;", 'elevabis', 'tempus', 'v:ind.praes.act.2.sg', "le geste de confiance est actuel"),
        ("Alors tu feras du Tout-Puissant tes délices, Tu as élevé vers Dieu ta face;", 'elevabis', 'tempus', 'v:ind.perf.act.2.sg', "le geste de confiance est un fait passé"),
        ("Alors tu feras du Tout-Puissant tes délices, Il élèvera vers Dieu sa face;", 'elevabis', 'persona', 'v:ind.fut.act.3.sg', "le geste n’est plus celui de l’interlocuteur"),
      ],
      note="Segond rend « super Omnipotentem deliciis afflues » par « tu feras du Tout-Puissant tes délices »."),
    Q('th-tempus-praeteritum', '1PE 3:21',
      target=('fecit', 'v:ind.perf.act.3.sg'),
      paed=True, fr="C’est ce qui, sous une forme semblable, vous a sauvés vous aussi maintenant : le baptême, non la purification des souillures de la chair, mais l’engagement d’une bonne conscience envers Dieu, par la résurrection de Jésus-Christ.",
      dist=[
        ("C’est ce qui, sous une forme semblable, vous sauve vous aussi maintenant : le baptême, non la purification des souillures de la chair, mais l’engagement d’une bonne conscience envers Dieu, par la résurrection de Jésus-Christ.", 'fecit', 'tempus', 'v:ind.praes.act.3.sg', "le salut est présenté comme en cours"),
        ("C’est ce qui, sous une forme semblable, vous sauvera vous aussi maintenant : le baptême, non la purification des souillures de la chair, mais l’engagement d’une bonne conscience envers Dieu, par la résurrection de Jésus-Christ.", 'fecit', 'tempus', 'v:ind.fut.act.3.sg', "le salut est annoncé"),
        ("C’est ce qui, sous une forme semblable, vous a sauvés vous aussi maintenant : le baptême, non la purification de la souillure de la chair, mais l’engagement d’une bonne conscience envers Dieu, par la résurrection de Jésus-Christ.", 'sordium', 'numerus', 'n:gen.pl>n:gen.sg', "une seule souillure"),
      ],
      note="Segond a le présent « vous sauve » pour le parfait « salvos fecit » et « du corps » pour « carnis » ; rendu pédagogique."),
    Q('th-modus-imperativus', 'EXO 30:34',
      target=('Sume', 'v:imp.praes.act.2.sg'),
      gloss={'onycha': 'onyx, ongle odorant (parfum)'},
      dist=[
        ("L’Éternel dit à Moïse: Prenez des aromates, du stacté, de l’ongle odorant, du galbanum, et de l’encens pur, en parties égales.", 'Sume', 'numerus', 'v:imp.praes.act.2.pl', "l’ordre s’adresse à plusieurs personnes"),
        ("L’Éternel dit à Moïse: Tu prends des aromates, du stacté, de l’ongle odorant, du galbanum, et de l’encens pur, en parties égales.", 'Sume', 'modus', 'v:ind.praes.act.2.sg', "un ordre devient un constat"),
        ("L’Éternel dit à Moïse: Puisses-tu prendre des aromates, du stacté, de l’ongle odorant, du galbanum, et de l’encens pur, en parties égales.", 'Sume', 'modus', 'v:subj.praes.act.2.sg', "un ordre devient un souhait"),
      ],
      note="Segond ne rend pas « tibi », « boni odoris », « lucidissimum » et résume « æqualis ponderis erunt omnia » en « en parties égales »."),
    Q('th-tempus-futurum', 'LEV 13:21',
      target=('recludet', 'v:ind.fut.act.3.sg'),
      dist=[
        ("Si le sacrificateur voit qu’il n’y a point de poil blanc dans la tache, qu’elle n’est pas plus enfoncée que la peau, et qu’elle est devenue pâle, il enferme cet homme pendant sept jours.", 'recludet', 'tempus', 'v:ind.praes.act.3.sg', "la mise à l’écart est actuelle"),
        ("Si le sacrificateur voit qu’il n’y a point de poil blanc dans la tache, qu’elle n’est pas plus enfoncée que la peau, et qu’elle est devenue pâle, il a enfermé cet homme pendant sept jours.", 'recludet', 'tempus', 'v:ind.perf.act.3.sg', "la mise à l’écart est un fait passé"),
        ("Si le sacrificateur voit qu’il n’y a point de poil blanc dans la tache, qu’elle n’est pas plus enfoncée que la peau, et qu’elle est devenue pâle, tu enfermeras cet homme pendant sept jours.", 'recludet', 'persona', 'v:ind.fut.act.2.sg', "la mise à l’écart est confiée à l’interlocuteur"),
      ],
      note="Segond suit l’hébreu (« point de poil blanc », « devenue pâle ») et explicite « le sacrificateur voit » et « cet homme »."),
    Q('th-tempus-futurum', '2MA 4:38',
      target=('commiserat', 'v:ind.plusq.act.3.sg'),
      paed=True, fr="et, l’esprit enflammé, il ordonne qu’Andronicus, dépouillé de la pourpre, soit conduit à travers toute la ville, et qu’au lieu même où il avait commis son impiété contre Onias, le sacrilège soit privé de la vie, le Seigneur lui rendant le châtiment qu’il méritait.",
      dist=[
        ("et, l’esprit enflammé, il ordonne qu’Andronicus, dépouillé de la pourpre, soit conduit à travers toute la ville, et qu’au lieu même où il a commis son impiété contre Onias, le sacrilège soit privé de la vie, le Seigneur lui rendant le châtiment qu’il méritait.", 'commiserat', 'tempus', 'v:ind.perf.act.3.sg', "le crime n’est plus situé avant le récit"),
        ("et, l’esprit enflammé, il ordonne qu’Andronicus, dépouillé de la pourpre, soit conduit à travers toute la ville, et qu’au lieu même où il commettait son impiété contre Onias, le sacrilège soit privé de la vie, le Seigneur lui rendant le châtiment qu’il méritait.", 'commiserat', 'tempus', 'v:ind.imperf.act.3.sg', "un crime accompli devient une action qui dure"),
        ("et, l’esprit enflammé, il ordonne qu’Andronicus, dépouillé de la pourpre, soit conduit à travers toute la ville, et qu’au lieu même où ils avaient commis leur impiété contre Onias, le sacrilège soit privé de la vie, le Seigneur lui rendant le châtiment qu’il méritait.", 'commiserat', 'numerus', 'v:ind.plusq.act.3.pl', "plusieurs coupables"),
      ],
      note="Livre absent de Segond ; rendu pédagogique."),
    Q('th-modus-subiunctivus', 'DAN 3:2',
      target=('convenirent', 'v:subj.imperf.act.3.pl'),
      gloss={'tyrannos': 'princes, gouverneurs'},
      dist=[
        ("Le roi Nebucadnetsar fit convoquer les satrapes, les intendants et les gouverneurs, les grands juges, les trésoriers, les jurisconsultes, les juges, et tous les magistrats des provinces, pour qu’ils se rendent à la dédicace de la statue qu’avait élevée le roi Nebucadnetsar.", 'convenirent', 'tempus', 'v:subj.praes.act.3.pl', "la convocation est présentée comme actuelle"),
        ("Le roi Nebucadnetsar fit convoquer les satrapes, les intendants et les gouverneurs, les grands juges, les trésoriers, les jurisconsultes, les juges, et tous les magistrats des provinces, pour qu’il se rendît à la dédicace de la statue qu’avait élevée le roi Nebucadnetsar.", 'convenirent', 'numerus', 'v:subj.imperf.act.3.sg', "un seul convoqué"),
        ("Le roi Nebucadnetsar fit convoquer les satrapes, les intendants et les gouverneurs, les grands juges, les trésoriers, les jurisconsultes, les juges, et tous les magistrats des provinces, pour qu’ils se rendissent à la dédicace de la statue qu’a élevée le roi Nebucadnetsar.", 'erexerat', 'tempus', 'v:ind.plusq.act.3.sg>v:ind.perf.act.3.sg', "l’érection de la statue n’est plus antérieure au récit"),
      ],
      note="La liste des dignitaires de Segond suit l’araméen et diffère de celle de la Vulgate ; la cible est convenirent."),
    Q('th-tempus-futurum', 'PSA 44:5',
      target=('deducet', 'v:ind.fut.act.3.sg'),
      paed=True, fr="Dans ta beauté et ta grâce, tends ton arc, avance heureusement et règne, pour la vérité, la douceur et la justice ; et ta droite te conduira merveilleusement.",
      dist=[
        ("Dans ta beauté et ta grâce, tends ton arc, avance heureusement et règne, pour la vérité, la douceur et la justice ; et ta droite te conduit merveilleusement.", 'deducet', 'tempus', 'v:ind.praes.act.3.sg', "la conduite victorieuse est actuelle"),
        ("Dans ta beauté et ta grâce, tends ton arc, avance heureusement et règne, pour la vérité, la douceur et la justice ; et ta droite t’a conduit merveilleusement.", 'deducet', 'tempus', 'v:ind.perf.act.3.sg', "la conduite victorieuse est un fait passé"),
        ("Dans ta beauté et ta grâce, tends ton arc, avance heureusement et règne, pour la vérité, la douceur et la justice ; et ta droite te conduisait merveilleusement.", 'deducet', 'tempus', 'v:ind.imperf.act.3.sg', "la conduite victorieuse devient un état passé"),
      ],
      note="Segond (45:5) suit l’hébreu (« Sois vainqueur, monte sur ton char ») ; la Vulgate suit la LXX ; rendu pédagogique."),
    Q('th-modus-subiunctivus', 'JDT 15:1',
      target=('audisset', 'v:subj.plusq.act.3.sg'),
      paed=True, fr="Et quand toute l’armée eut appris qu’Holopherne était décapité, la raison et le jugement les abandonnèrent ; agités seulement par le tremblement et la peur, ils cherchent leur salut dans la fuite,",
      dist=[
        ("Et quand toute l’armée apprenait qu’Holopherne était décapité, la raison et le jugement les abandonnèrent ; agités seulement par le tremblement et la peur, ils cherchent leur salut dans la fuite,", 'audisset', 'tempus', 'v:subj.imperf.act.3.sg', "la nouvelle n’est plus antérieure à la panique"),
        ("Et quand toutes les armées eurent appris qu’Holopherne était décapité, la raison et le jugement les abandonnèrent ; agités seulement par le tremblement et la peur, ils cherchent leur salut dans la fuite,", 'audisset', 'numerus', 'v:subj.plusq.act.3.pl', "plusieurs armées"),
        ("Et quand toute l’armée eut appris qu’Holopherne était décapité, la raison et le jugement les abandonnèrent ; agités seulement par le tremblement et la peur, ils ont cherché leur salut dans la fuite,", 'sumunt', 'tempus', 'v:ind.praes.act.3.pl>v:ind.perf.act.3.pl', "le présent de narration devient un passé"),
      ],
      note="Livre absent de Segond ; rendu pédagogique."),
    Q('th-tempus-futurum', 'EXO 23:28',
      target=('fugabunt', 'v:ind.fut.act.3.pl'),
      dist=[
        ("J’enverrai les frelons devant toi, et ils chassent loin de ta face les Héviens, les Cananéens et les Héthiens.", 'fugabunt', 'tempus', 'v:ind.praes.act.3.pl', "l’expulsion est actuelle"),
        ("J’enverrai les frelons devant toi, et ils ont chassé loin de ta face les Héviens, les Cananéens et les Héthiens.", 'fugabunt', 'tempus', 'v:ind.perf.act.3.pl', "l’expulsion est un fait passé"),
        ("J’enverrai les frelons devant toi, et ils chassaient loin de ta face les Héviens, les Cananéens et les Héthiens.", 'fugabunt', 'tempus', 'v:ind.imperf.act.3.pl', "l’expulsion devient un état passé"),
      ],
      note="Segond rend le participe « emittens » par « J’enverrai », met les peuples au pluriel et omet « antequam introëas »."),
    Q('th-modus-subiunctivus', 'ISA 46:6',
      target=('faciat', 'v:subj.praes.act.3.sg'),
      dist=[
        ("Ils versent l’or de leur bourse, Et pèsent l’argent à la balance; Ils paient un orfèvre, pour qu’ils en fassent un dieu, Et ils adorent et se prosternent.", 'faciat', 'numerus', 'v:subj.praes.act.3.pl', "plusieurs fabricants du dieu"),
        ("Ils versent l’or de leur bourse, Et pèsent l’argent à la balance; Ils paient un orfèvre, pour qu’il en fît un dieu, Et ils adorent et se prosternent.", 'faciat', 'tempus', 'v:subj.imperf.act.3.sg', "la fabrication est rejetée dans le passé"),
        ("Ils versent l’or de leur bourse, Et pèsent l’argent à la balance; Ils paient un orfèvre, pour que tu en fasses un dieu, Et ils adorent et se prosternent.", 'faciat', 'persona', 'v:subj.praes.act.2.sg', "la fabrication est confiée à l’interlocuteur"),
      ],
      note="Segond a la 3e personne (« Ils versent », « pèsent ») pour les 2e personnes latines « confertis », « ponderatis » ; la cible est faciat."),
    Q('th-nonfinita', 'NAH 3:2',
      target=('frementis', 'v:part.praes.act.gen.sg.m'),
      paed=True, fr="Bruit du fouet, et bruit de la roue qui s’élance, du cheval qui frémit, du char qui bondit, et du cavalier qui monte,",
      dist=[
        ("Bruit du fouet, et bruit de la roue qui s’élance, des chevaux qui frémissent, du char qui bondit, et du cavalier qui monte,", 'frementis', 'numerus', 'v:part.praes.act.gen.pl.m', "plusieurs chevaux"),
        ("Bruit du fouet, et bruit de la roue qui s’élance, du cheval qui va frémir, du char qui bondit, et du cavalier qui monte,", 'frementis', 'tempus', 'v:part.fut.act.gen.sg.m', "le frémissement n’a pas encore commencé"),
        ("Bruit du fouet, et bruit des roues qui s’élancent, du cheval qui frémit, du char qui bondit, et du cavalier qui monte,", 'rotæ', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs roues"),
      ],
      note="Segond (« Le bruit des roues, Le galop des chevaux ») met au pluriel et ne rend pas les participes ; rendu pédagogique."),
    Q('th-nonfinita', '2MA 5:8',
      target=('fugiens', 'v:part.praes.act.nom.sg.m'),
      paed=True, fr="Enfin, enfermé pour sa perte par Arétas, tyran des Arabes, fuyant de ville en ville, odieux à tous comme déserteur des lois et exécrable comme ennemi de sa patrie et de ses concitoyens, il fut chassé en Égypte.",
      gloss={'tyranno': 'tyran, souverain'},
      dist=[
        ("Enfin, enfermé pour sa perte par Arétas, tyran des Arabes, sur le point de fuir de ville en ville, odieux à tous comme déserteur des lois et exécrable comme ennemi de sa patrie et de ses concitoyens, il fut chassé en Égypte.", 'fugiens', 'tempus', 'v:part.fut.act.nom.sg.m', "la fuite n’a pas encore commencé"),
        ("Enfin, enfermé pour sa perte par Arétas, tyran des Arabes, il fuit de ville en ville, odieux à tous comme déserteur des lois et exécrable comme ennemi de sa patrie et de ses concitoyens, il fut chassé en Égypte.", 'fugiens', 'nonfinita', 'v:ind.praes.act.3.sg', "le participe devient l’action principale"),
        ("Enfin, enfermé pour sa perte par Arétas, tyran des Arabes, fuyant de ville en ville, odieux à tous comme déserteur de la loi et exécrable comme ennemi de sa patrie et de ses concitoyens, il fut chassé en Égypte.", 'legum', 'numerus', 'n:gen.pl>n:gen.sg', "une seule loi"),
      ],
      note="Livre absent de Segond ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'LUK 9:39',
      target=('clamat', 'v:ind.praes.act.3.sg'),
      dist=[
        ("Un esprit le saisit, et aussitôt il a poussé des cris; et l’esprit l’agite avec violence, le fait écumer, et a de la peine à se retirer de lui, après l’avoir tout brisé.", 'clamat', 'tempus', 'v:ind.perf.act.3.sg', "le cri devient un fait passé"),
        ("Un esprit le saisit, et aussitôt il poussera des cris; et l’esprit l’agite avec violence, le fait écumer, et a de la peine à se retirer de lui, après l’avoir tout brisé.", 'clamat', 'tempus', 'v:ind.fut.act.3.sg', "le cri est annoncé"),
        ("Un esprit le saisit, et aussitôt il poussait des cris; et l’esprit l’agite avec violence, le fait écumer, et a de la peine à se retirer de lui, après l’avoir tout brisé.", 'clamat', 'tempus', 'v:ind.imperf.act.3.sg', "le cri devient un état passé"),
      ],
      note="Segond explicite « l’esprit » et rend « dilanians » par « après l’avoir tout brisé »."),
    Q('th-modus-subiunctivus', 'PRO 30:9',
      target=('dicam', 'v:subj.praes.act.1.sg'),
      dist=[
        ("De peur que, dans l’abondance, je ne te renie Et qu’il ne dise: Qui est l’Éternel? Ou que, dans la pauvreté, je ne dérobe, Et ne m’attaque au nom de mon Dieu.", 'dicam', 'persona', 'v:subj.praes.act.3.sg', "le blasphème est attribué à un tiers"),
        ("De peur que, dans l’abondance, je ne te renie Et ne disions: Qui est l’Éternel? Ou que, dans la pauvreté, je ne dérobe, Et ne m’attaque au nom de mon Dieu.", 'dicam', 'numerus', 'v:subj.praes.act.1.pl', "plusieurs blasphémateurs"),
        ("De peur que, dans l’abondance, je ne te renie Et ne dise: Qui est l’Éternel? Ou que, dans la pauvreté, je ne dérobe, Et ne m’attaque au nom de mes dieux.", 'Dei', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs dieux"),
      ],
      note="Segond rend « satiatus illiciar ad negandum » par « dans l’abondance, je ne te renie » et « furer » par « je ne dérobe »."),
    Q('th-tempus-praeteritum', 'GEN 29:30',
      target=('prætulit', 'v:ind.perf.act.3.sg'),
      paed=True, fr="Ayant enfin obtenu les noces désirées, il préféra l’amour de la seconde à la première, servant chez lui sept autres années.",
      dist=[
        ("Ayant enfin obtenu les noces désirées, il préfère l’amour de la seconde à la première, servant chez lui sept autres années.", 'prætulit', 'tempus', 'v:ind.praes.act.3.sg', "la préférence est actuelle"),
        ("Ayant enfin obtenu les noces désirées, il préférera l’amour de la seconde à la première, servant chez lui sept autres années.", 'prætulit', 'tempus', 'v:ind.fut.act.3.sg', "la préférence est annoncée"),
        ("Ayant enfin obtenu les noces désirées, il préférait l’amour de la seconde à la première, servant chez lui sept autres années.", 'prætulit', 'tempus', 'v:ind.imperf.act.3.sg', "un choix accompli devient un état qui dure"),
      ],
      note="Segond (« Jacob alla aussi vers Rachel, qu’il aimait plus que Léa ») suit l’hébreu ; rendu pédagogique de la Vulgate."),
    Q('th-tempus-futurum', 'MAT 17:19',
      target=('dicetis', 'v:ind.fut.act.2.pl'),
      paed=True, fr="Jésus leur dit : À cause de votre incrédulité. Car en vérité je vous le dis, si vous avez de la foi comme un grain de sénevé, vous direz à cette montagne : Passe d’ici là, et elle passera, et rien ne vous sera impossible.",
      dist=[
        ("Jésus leur dit : À cause de votre incrédulité. Car en vérité je vous le dis, si vous avez de la foi comme un grain de sénevé, vous dites à cette montagne : Passe d’ici là, et elle passera, et rien ne vous sera impossible.", 'dicetis', 'tempus', 'v:ind.praes.act.2.pl', "la parole de foi est actuelle"),
        ("Jésus leur dit : À cause de votre incrédulité. Car en vérité je vous le dis, si vous avez de la foi comme un grain de sénevé, vous avez dit à cette montagne : Passe d’ici là, et elle passera, et rien ne vous sera impossible.", 'dicetis', 'tempus', 'v:ind.perf.act.2.pl', "la parole de foi est un fait passé"),
        ("Jésus leur dit : À cause de votre incrédulité. Car en vérité je vous le dis, si vous avez de la foi comme un grain de sénevé, ils diront à cette montagne : Passe d’ici là, et elle passera, et rien ne vous sera impossible.", 'dicetis', 'persona', 'v:ind.fut.act.3.pl', "la parole de foi est attribuée à des tiers"),
      ],
      note="Segond numérote ce verset 17:20 et le rend au conditionnel (« si vous aviez … vous diriez ») ; rendu pédagogique des futurs latins."),
    Q('th-tempus-praeteritum', 'SIR 10:11',
      target=('gravat', 'v:ind.praes.act.3.sg'),
      paed=True, fr="Toute puissance est de courte vie ; une maladie qui se prolonge pèse au médecin.",
      dist=[
        ("Toute puissance est de courte vie ; une maladie qui se prolonge a pesé au médecin.", 'gravat', 'tempus', 'v:ind.perf.act.3.sg', "une vérité générale devient un fait passé"),
        ("Toute puissance est de courte vie ; une maladie qui se prolonge pèsera au médecin.", 'gravat', 'tempus', 'v:ind.fut.act.3.sg', "une vérité générale devient une prédiction"),
        ("Toute puissance est de courte vie ; une maladie qui se prolonge pèse aux médecins.", 'medicum', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs médecins"),
      ],
      note="Livre absent de Segond ; rendu pédagogique."),
    Q('th-nonfinita', 'HEB 4:12',
      target=('pertingens', 'v:part.praes.act.nom.sg.m'),
      dist=[
        ("Car la parole de Dieu est vivante et efficace, plus tranchante qu’une épée quelconque à deux tranchants, sur le point de pénétrer jusqu’à partager âme et esprit, jointures et mœlles; elle juge les sentiments et les pensées du cœur.", 'pertingens', 'tempus', 'v:part.fut.act.nom.sg.m', "la pénétration n’a pas encore lieu"),
        ("Car la parole de Dieu est vivante et efficace, plus tranchante qu’une épée quelconque à deux tranchants, elle pénètre jusqu’à partager âme et esprit, jointures et mœlles; elle juge les sentiments et les pensées du cœur.", 'pertingens', 'nonfinita', 'v:ind.praes.act.3.sg', "le participe devient une proposition indépendante"),
        ("Car la parole de Dieu est vivante et efficace, plus tranchante qu’une épée quelconque à deux tranchants, pénétrante jusqu’à partager âme et esprit, jointures et mœlles; elle juge les sentiments et la pensée du cœur.", 'cogitationum', 'numerus', 'n:gen.pl>n:gen.sg', "une seule pensée"),
      ],
      note="Segond rend le nom « discretor » par « elle juge » et « pertingens » par l’adjectif « pénétrante »."),
    Q('th-modus-subiunctivus', '2SA 15:12',
      target=('immolaret', 'v:subj.imperf.act.3.sg'),
      gloss={'Gilonitem': 'Guilonite', 'Gilo': 'Guilo'},
      dist=[
        ("Pendant qu’Absalom offre les sacrifices, il envoya chercher à la ville de Guilo Achitophel, le Guilonite, conseiller de David. La conjuration devint puissante, et le peuple était de plus en plus nombreux auprès d’Absalom.", 'immolaret', 'tempus', 'v:subj.praes.act.3.sg', "les sacrifices sont présentés comme actuels"),
        ("Pendant qu’ils offraient les sacrifices, il envoya chercher à la ville de Guilo Achitophel, le Guilonite, conseiller de David. La conjuration devint puissante, et le peuple était de plus en plus nombreux auprès d’Absalom.", 'immolaret', 'numerus', 'v:subj.imperf.act.3.pl', "plusieurs sacrificateurs au lieu d’Absalom seul"),
        ("Pendant qu’Absalom offrait le sacrifice, il envoya chercher à la ville de Guilo Achitophel, le Guilonite, conseiller de David. La conjuration devint puissante, et le peuple était de plus en plus nombreux auprès d’Absalom.", 'victimas', 'numerus', 'n:acc.pl>n:acc.sg', "un seul sacrifice"),
      ],
      note="Segond déplace la proposition « Cumque immolaret victimas » en tête et rend « concurrens augebatur » par « était de plus en plus nombreux »."),
    Q('th-tempus-praeteritum', 'NUM 36:11',
      target=('nupserunt', 'v:ind.perf.act.3.pl'),
      gloss={'Maala': 'Machla', 'Thersa': 'Thirtsa', 'Hegla': 'Hogla', 'Melcha': 'Milca', 'Noa': 'Noa'},
      dist=[
        ("Machla, Thirtsa, Hogla, Milca et Noa, filles de Tselophchad, se marient aux fils de leurs oncles;", 'nupserunt', 'tempus', 'v:ind.praes.act.3.pl', "les mariages sont actuels"),
        ("Machla, Thirtsa, Hogla, Milca et Noa, filles de Tselophchad, se marieront aux fils de leurs oncles;", 'nupserunt', 'tempus', 'v:ind.fut.act.3.pl', "les mariages sont annoncés"),
        ("Machla, Thirtsa, Hogla, Milca et Noa, filles de Tselophchad, se marièrent au fils de leurs oncles;", 'filiis', 'numerus', 'n:dat.pl>n:dat.sg', "un seul époux"),
      ],
      note="Segond ajoute « filles de Tselophchad » et a « leurs oncles » pour « patrui sui » (singulier)."),
    Q('th-tempus-futurum', 'ZEC 6:14',
      target=('erunt', 'v:ind.fut.act.3.pl'),
      gloss={'Helem': 'Hélem', 'Idaiæ': 'Jedaeja'},
      dist=[
        ("Les couronnes sont pour Hélem, Tobija et Jedaeja, et pour Hen, fils de Sophonie, un souvenir dans le temple de l’Éternel.", 'erunt', 'tempus', 'v:ind.praes.act.3.pl', "la destination des couronnes est actuelle"),
        ("Les couronnes ont été pour Hélem, Tobija et Jedaeja, et pour Hen, fils de Sophonie, un souvenir dans le temple de l’Éternel.", 'erunt', 'tempus', 'v:ind.perf.act.3.pl', "la destination des couronnes est un fait passé"),
        ("La couronne sera pour Hélem, Tobija et Jedaeja, et pour Hen, fils de Sophonie, un souvenir dans le temple de l’Éternel.", 'erunt', 'numerus', 'v:ind.fut.act.3.sg', "une seule couronne"),
      ]),
    Q('th-tempus-praeteritum', 'EZE 23:5',
      target=('insanivit', 'v:ind.perf.act.3.sg'),
      gloss={'Oolla': 'Ohola', 'Assyrios': 'Assyriens'},
      dist=[
        ("Ohola me fut infidèle; Elle s’enflamme pour ses amants, Les Assyriens ses voisins,", 'insanivit', 'tempus', 'v:ind.praes.act.3.sg', "la passion est actuelle"),
        ("Ohola me fut infidèle; Elle s’enflammera pour ses amants, Les Assyriens ses voisins,", 'insanivit', 'tempus', 'v:ind.fut.act.3.sg', "la passion est annoncée"),
        ("Ohola me fut infidèle; Elle s’enflamma pour son amant, Les Assyriens ses voisins,", 'amatores', 'numerus', 'n:acc.pl>n:acc.sg', "un seul amant"),
      ],
      note="Segond rend le participe « propinquantes » par « ses voisins »."),
    Q('th-tempus-praeteritum', 'EST 2:5',
      target=('Erat', 'v:ind.imperf.act.3.sg'),
      gloss={'Susan': 'Suse', 'Jair': 'Jaïr'},
      dist=[
        ("Il y a dans Suse, la capitale, un Juif nommé Mardochée, fils de Jaïr, fils de Schimeï, fils de Kis, homme de Benjamin,", 'Erat', 'tempus', 'v:ind.praes.act.3.sg', "la présence de Mardochée est actuelle"),
        ("Il y eut dans Suse, la capitale, un Juif nommé Mardochée, fils de Jaïr, fils de Schimeï, fils de Kis, homme de Benjamin,", 'Erat', 'tempus', 'v:ind.perf.act.3.sg', "un état durable devient un fait ponctuel"),
        ("Il y aura dans Suse, la capitale, un Juif nommé Mardochée, fils de Jaïr, fils de Schimeï, fils de Kis, homme de Benjamin,", 'Erat', 'tempus', 'v:ind.fut.act.3.sg', "la présence de Mardochée est annoncée"),
      ],
      note="Segond rend « civitate » par « la capitale » et « de stirpe Jemini » par « homme de Benjamin »."),
    Q('th-vox', 'JOS 7:15',
      target=('comburetur', 'v:ind.fut.pass.3.sg'),
      paed=True, fr="Et quiconque sera pris dans ce crime sera brûlé au feu avec tout son bien, parce qu’il a transgressé l’alliance du Seigneur et commis une infamie en Israël.",
      dist=[
        ("Et quiconque sera pris dans ce crime brûlera au feu tout son bien, parce qu’il a transgressé l’alliance du Seigneur et commis une infamie en Israël.", 'comburetur', 'vox', 'v:ind.fut.act.3.sg', "le coupable devient celui qui brûle"),
        ("Et quiconque sera pris dans ce crime est brûlé au feu avec tout son bien, parce qu’il a transgressé l’alliance du Seigneur et commis une infamie en Israël.", 'comburetur', 'tempus', 'v:ind.praes.pass.3.sg', "le châtiment est présenté comme actuel"),
        ("Et tous ceux qui seront pris dans ce crime seront brûlés au feu avec tout leur bien, parce qu’ils ont transgressé l’alliance du Seigneur et commis une infamie en Israël.", 'comburetur', 'numerus', 'v:ind.fut.pass.3.pl', "plusieurs coupables"),
      ],
      note="Segond (« Celui qui sera désigné comme ayant pris de ce qui était dévoué par interdit ») paraphrase ; rendu pédagogique."),
]
