# sheet_002 → batch_002
# skipped: REV 21:20 (list of stones with ordinals, no verb; case and number invisible in French)
ITEMS = [
    Q('th-tempus-praeteritum', 'HEB 9:26',
      target=('apparuit', 'v:ind.perf.act.3.sg'),
      lemma={'peccati': 'peccatum'},
      gloss={'peccati': 'péché'},
      dist=[
        ("autrement, il aurait fallu qu’il eût souffert plusieurs fois depuis la création du monde, tandis que maintenant, à la fin des siècles, il paraît une seule fois pour abolir le péché par son sacrifice.", 'apparuit', 'tempus', 'v:ind.praes.act.3.sg', "la venue du Christ est présentée comme actuelle"),
        ("autrement, il aurait fallu qu’il eût souffert plusieurs fois depuis la création du monde, tandis que maintenant, à la fin des siècles, il paraîtra une seule fois pour abolir le péché par son sacrifice.", 'apparuit', 'tempus', 'v:ind.fut.act.3.sg', "la venue du Christ est annoncée au lieu d’être accomplie"),
        ("autrement, il aurait fallu qu’il eût souffert plusieurs fois depuis la création du monde, tandis que maintenant, à la fin des siècles, ils ont paru une seule fois pour abolir le péché par son sacrifice.", 'apparuit', 'numerus', 'v:ind.perf.act.3.pl', "plusieurs personnes paraissent au lieu du Christ seul"),
      ],
      note="Segond rend « oportebat eum pati » par « il aurait fallu qu’il eût souffert » ; la cible est apparuit."),
    Q('th-modus-imperativus', 'PSA 16:1',
      target=('Exaudi', 'v:imp.praes.act.2.sg'),
      dist=[
        ("Prière de David. Éternel! Écoutez la droiture, sois attentif à mes cris, Prête l’oreille à ma prière faite avec des lèvres sans tromperie!", 'Exaudi', 'numerus', 'v:imp.praes.act.2.pl', "la prière s’adresse à plusieurs personnes"),
        ("Prière de David. Éternel! Tu écoutes la droiture, sois attentif à mes cris, Prête l’oreille à ma prière faite avec des lèvres sans tromperie!", 'Exaudi', 'modus', 'v:ind.praes.act.2.sg', "une prière devient un constat"),
        ("Prière de David. Éternel! Écoute la droiture, sois attentif à mes cris, Prêtez l’oreille à ma prière faite avec des lèvres sans tromperie!", 'percipe', 'numerus', 'v:imp.praes.act.2.sg>v:imp.praes.act.2.pl', "plusieurs auditeurs de la prière"),
      ],
      note="Segond (Ps 17:1) a « Écoute la droiture » pour « exaudi justitiam meam » et « sois attentif à mes cris » pour « intende deprecationem meam »."),
    Q('th-tempus-praeteritum', '2CH 34:4',
      target=('dispersit', 'v:ind.perf.act.3.sg'),
      lemma={'aras': 'ara'},
      dist=[
        ("On renversa devant lui les autels des Baals, et il abattit les statues consacrées au soleil qui étaient dessus; il brisa les idoles, les images taillées et les images en fonte, et les réduisit en poussière, et il répand la poussière sur les sépulcres de ceux qui leur avaient sacrifié;", 'dispersit', 'tempus', 'v:ind.praes.act.3.sg', "la dispersion de la poussière est présentée comme actuelle"),
        ("On renversa devant lui les autels des Baals, et il abattit les statues consacrées au soleil qui étaient dessus; il brisa les idoles, les images taillées et les images en fonte, et les réduisit en poussière, et ils répandirent la poussière sur les sépulcres de ceux qui leur avaient sacrifié;", 'dispersit', 'numerus', 'v:ind.perf.act.3.pl', "plusieurs acteurs au lieu du roi seul"),
        ("On renversa devant lui les autels des Baals, et il abattit les statues consacrées au soleil qui étaient dessus; il brisa les idoles, les images taillées et les images en fonte, et les réduisit en poussière, et il répandit la poussière sur les sépulcres de ceux qui leur sacrifièrent;", 'consueverant', 'tempus', 'v:ind.plusq.act.3.pl>v:ind.perf.act.3.pl', "les sacrifices ne sont plus antérieurs au récit"),
      ],
      note="Segond suit l’hébreu et développe (« statues consacrées au soleil… images en fonte ») ; la cible dispersit est rendue fidèlement."),
    Q('th-tempus-futurum', 'NUM 3:28',
      target=('habebunt', 'v:ind.fut.act.3.pl'),
      paed=True, fr="Tous les mâles depuis l’âge d’un mois et au-dessus, huit mille six cents, auront la garde du sanctuaire,",
      dist=[
        ("Tous les mâles depuis l’âge d’un mois et au-dessus, huit mille six cents, ont la garde du sanctuaire,", 'habebunt', 'tempus', 'v:ind.praes.act.3.pl', "la charge est actuelle au lieu d’être prescrite"),
        ("Tous les mâles depuis l’âge d’un mois et au-dessus, huit mille six cents, eurent la garde du sanctuaire,", 'habebunt', 'tempus', 'v:ind.perf.act.3.pl', "la charge est rejetée dans le passé"),
        ("Tous les mâles depuis l’âge d’un mois et au-dessus, huit mille six cents, auront la garde des sanctuaires,", 'sanctuarii', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs sanctuaires"),
      ],
      note="Segond a le passé (« il y en eut… qui furent chargés ») pour le futur habebunt ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'ACT 16:22',
      target=('jusserunt', 'v:ind.perf.act.3.pl'),
      lemma={'cædi': 'caedo'},
      dist=[
        ("La foule se souleva aussi contre eux, et les préteurs, ayant fait arracher leurs vêtements, ordonnent qu’on les batte de verges.", 'jusserunt', 'tempus', 'v:ind.praes.act.3.pl', "l’ordre est donné maintenant"),
        ("La foule se souleva aussi contre eux, et le préteur, ayant fait arracher leurs vêtements, ordonna qu’on les battît de verges.", 'jusserunt', 'numerus', 'v:ind.perf.act.3.sg', "un seul magistrat"),
        ("Les foules se soulevèrent aussi contre eux, et les préteurs, ayant fait arracher leurs vêtements, ordonnèrent qu’on les battît de verges.", 'cucurrit', 'numerus', 'v:ind.perf.act.3.sg>v:ind.perf.act.3.pl', "plusieurs foules"),
      ],
      note="Segond rend « scissis tunicis eorum » par « ayant fait arracher leurs vêtements » ; la cible est jusserunt."),
    Q('th-persona', 'JOB 30:15',
      target=('abstulisti', 'v:ind.perf.act.2.sg'),
      paed=True, fr="J’ai été réduit à rien : tu as emporté mon désir comme le vent, et mon salut a passé comme un nuage.",
      lemma={'ventus': 'uentus'},
      gloss={'ventus': 'vent'},
      dist=[
        ("J’ai été réduit à rien : il a emporté mon désir comme le vent, et mon salut a passé comme un nuage.", 'abstulisti', 'persona', 'v:ind.perf.act.3.sg', "Job ne s’adresse plus à Dieu"),
        ("J’ai été réduit à rien : vous avez emporté mon désir comme le vent, et mon salut a passé comme un nuage.", 'abstulisti', 'numerus', 'v:ind.perf.act.2.pl', "plusieurs interlocuteurs"),
        ("J’ai été réduit à rien : tu as emporté mon désir comme le vent, et mon salut a passé comme des nuages.", 'nubes', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs nuages"),
      ],
      note="Segond suit l’hébreu (« Les terreurs m’assiègent ; Ma gloire est emportée… ») ; rendu pédagogique."),
    Q('th-numerus', 'JOB 3:17',
      target=('cessaverunt', 'v:ind.perf.act.3.pl'),
      paed=True, fr="Là les méchants ont cessé leur tumulte, et là se sont reposés ceux dont la force était épuisée.",
      dist=[
        ("Là le méchant a cessé son tumulte, et là se sont reposés ceux dont la force était épuisée.", 'cessaverunt', 'numerus', 'v:ind.perf.act.3.sg', "un seul méchant"),
        ("Là les méchants ont cessé leur tumulte, et là s’est reposé celui dont la force était épuisée.", 'requieverunt', 'numerus', 'v:ind.perf.act.3.pl>v:ind.perf.act.3.sg', "un seul homme se repose"),
        ("Là les méchants ont cessé leurs tumultes, et là se sont reposés ceux dont la force était épuisée.", 'tumultu', 'numerus', 'n:abl.sg>n:abl.pl', "plusieurs tumultes"),
      ],
      note="Segond met le verset au présent (« ne s’agitent plus… se reposent ») ; rendu pédagogique."),
    Q('th-persona', 'JER 13:27',
      target=('vidi', 'v:ind.perf.act.1.sg'),
      gloss={'Jerusalem': 'Jérusalem'},
      dist=[
        ("Il a vu tes adultères et tes hennissements, Tes criminelles prostitutions sur les collines et dans les champs, Il a vu tes abominations. Malheur à toi, Jérusalem! Jusques à quand tarderas-tu à te purifier?", 'vidi', 'persona', 'v:ind.perf.act.3.sg', "un autre que Dieu a vu"),
        ("Nous avons vu tes adultères et tes hennissements, Tes criminelles prostitutions sur les collines et dans les champs, Nous avons vu tes abominations. Malheur à toi, Jérusalem! Jusques à quand tarderas-tu à te purifier?", 'vidi', 'numerus', 'v:ind.perf.act.1.pl', "plusieurs témoins"),
        ("J’ai vu tes adultères et tes hennissements, Tes criminelles prostitutions sur la colline et dans les champs, J’ai vu tes abominations. Malheur à toi, Jérusalem! Jusques à quand tarderas-tu à te purifier?", 'colles', 'numerus', 'n:acc.pl>n:acc.sg', "une seule colline"),
      ],
      note="Segond répète « J’ai vu » et rend « non mundaberis post me: usquequo adhuc? » par « Jusques à quand tarderas-tu à te purifier ? » ; la cible est vidi."),
    Q('th-vox', 'PRO 21:6',
      target=('impingetur', 'v:ind.fut.pass.3.sg'),
      paed=True, fr="Celui qui amasse des trésors par une langue menteuse est vain et insensé, et il sera poussé vers les filets de la mort.",
      dist=[
        ("Celui qui amasse des trésors par une langue menteuse est vain et insensé, et il poussera vers les filets de la mort.", 'impingetur', 'vox', 'v:ind.fut.act.3.sg', "la victime devient l’agent qui pousse"),
        ("Celui qui amasse des trésors par une langue menteuse est vain et insensé, et il est poussé vers les filets de la mort.", 'impingetur', 'tempus', 'v:ind.praes.pass.3.sg', "le châtiment est actuel au lieu d’être annoncé"),
        ("Celui qui amasse des trésors par une langue menteuse est vain et insensé, et il sera poussé vers le filet de la mort.", 'laqueos', 'numerus', 'n:acc.pl>n:acc.sg', "un seul filet"),
      ],
      note="Segond suit l’hébreu (« Des trésors acquis… sont une vanité fugitive ») ; rendu pédagogique."),
    Q('th-tempus-praeteritum', '2PE 2:10',
      target=('metuunt', 'v:ind.praes.act.3.pl'),
      lemma={'concupiscentia': 'concupiscentia', 'sectas': 'secta'},
      gloss={'sectas': 'secte, doctrine'},
      dist=[
        ("ceux surtout qui vont après la chair dans un désir d’impureté et qui méprisent l’autorité. Audacieux et arrogants, ils n’ont pas craint d’injurier les gloires,", 'metuunt', 'tempus', 'v:ind.perf.act.3.pl', "l’audace est rejetée dans le passé"),
        ("ceux surtout qui vont après la chair dans un désir d’impureté et qui méprisent l’autorité. Audacieux et arrogants, ils ne craindront pas d’injurier les gloires,", 'metuunt', 'tempus', 'v:ind.fut.act.3.pl', "l’audace est annoncée au lieu d’être constatée"),
        ("celui surtout qui va après la chair dans un désir d’impureté et qui méprise l’autorité. Audacieux et arrogants, ils ne craignent pas d’injurier les gloires,", 'ambulant', 'numerus', 'v:ind.praes.act.3.pl>v:ind.praes.act.3.sg', "un seul impie au lieu de plusieurs"),
      ],
      note="Segond rend « sibi placentes » par « arrogants » et « sectas… blasphemantes » par « injurier les gloires » ; la cible est metuunt."),
    Q('th-persona', 'DEU 32:24',
      target=('immittam', 'v:ind.fut.act.1.sg'),
      dist=[
        ("Ils seront desséchés par la faim, consumés par la fièvre Et par des maladies violentes; Il enverra parmi eux la dent des bêtes féroces Et le venin des serpents.", 'immittam', 'persona', 'v:ind.fut.act.3.sg', "un autre que Dieu envoie le châtiment"),
        ("Ils seront desséchés par la faim, consumés par la fièvre Et par des maladies violentes; Nous enverrons parmi eux la dent des bêtes féroces Et le venin des serpents.", 'immittam', 'numerus', 'v:ind.fut.act.1.pl', "plusieurs envoient le châtiment"),
        ("Il sera desséché par la faim, consumé par la fièvre Et par des maladies violentes; J’enverrai parmi eux la dent des bêtes féroces Et le venin des serpents.", 'Consumentur', 'numerus', 'v:ind.fut.pass.3.pl>v:ind.fut.pass.3.sg', "une seule victime"),
      ],
      note="Segond suit l’hébreu pour « devorabunt eos aves morsu amarissimo » (« consumés par la fièvre… ») ; la cible est immittam."),
    Q('th-tempus-futurum', 'PSA 36:2',
      target=('arescent', 'v:ind.fut.act.3.pl'),
      paed=True, fr="car ils se dessécheront vite comme l’herbe, et comme la verdure des champs ils tomberont bientôt.",
      lemma={'cito': 'cito2'},
      gloss={'cito': 'vite, promptement'},
      dist=[
        ("car ils se dessèchent vite comme l’herbe, et comme la verdure des champs ils tomberont bientôt.", 'arescent', 'tempus', 'v:ind.praes.act.3.pl', "le dessèchement est actuel"),
        ("car il se desséchera vite comme l’herbe, et comme la verdure des champs ils tomberont bientôt.", 'arescent', 'numerus', 'v:ind.fut.act.3.sg', "un seul méchant se dessèche"),
        ("car ils se dessécheront vite comme l’herbe, et comme la verdure des champs ils tombent bientôt.", 'decident', 'tempus', 'v:ind.fut.act.3.pl>v:ind.praes.act.3.pl', "la chute est actuelle"),
      ],
      note="Segond (Ps 37:2) met le verset au présent (« ils sont fauchés… ils se flétrissent ») ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'JAM 3:17',
      target=('est', 'v:ind.praes.act.3.sg'),
      dist=[
        ("La sagesse d’en haut était premièrement pure, ensuite pacifique, modérée, conciliante, pleine de miséricorde et de bons fruits, exempte de duplicité, d’hypocrisie.", 'est', 'tempus', 'v:ind.imperf.act.3.sg', "la description de la sagesse vaut pour le passé"),
        ("La sagesse d’en haut sera premièrement pure, ensuite pacifique, modérée, conciliante, pleine de miséricorde et de bons fruits, exempte de duplicité, d’hypocrisie.", 'est', 'tempus', 'v:ind.fut.act.3.sg', "la description devient une promesse"),
        ("La sagesse d’en haut est premièrement pure, ensuite pacifique, modérée, conciliante, pleine de miséricorde et de bon fruit, exempte de duplicité, d’hypocrisie.", 'fructibus', 'numerus', 'n:abl.pl>n:abl.sg', "un seul fruit"),
      ],
      note="Segond fond les deux « est » en un seul et rend « non judicans » par « exempte de duplicité »."),
    Q('th-tempus-praeteritum', 'LEV 9:17',
      target=('offeruntur', 'v:ind.praes.pass.3.pl'),
      paed=True, fr="ajoutant au sacrifice les libations, qui sont offertes en même temps, et les brûlant sur l’autel, sans compter les cérémonies de l’holocauste du matin.",
      gloss={'altare': 'autel'},
      dist=[
        ("ajoutant au sacrifice les libations, qui seront offertes en même temps, et les brûlant sur l’autel, sans compter les cérémonies de l’holocauste du matin.", 'offeruntur', 'tempus', 'v:ind.fut.pass.3.pl', "l’offrande des libations est reportée dans l’avenir"),
        ("ajoutant au sacrifice les libations, qui étaient offertes en même temps, et les brûlant sur l’autel, sans compter les cérémonies de l’holocauste du matin.", 'offeruntur', 'tempus', 'v:ind.imperf.pass.3.pl', "l’usage est rejeté dans le passé"),
        ("ajoutant au sacrifice la libation, qui est offerte en même temps, et la brûlant sur l’autel, sans compter les cérémonies de l’holocauste du matin.", 'offeruntur', 'numerus', 'v:ind.praes.pass.3.sg', "une seule libation"),
      ],
      note="Segond suit l’hébreu (« Il présenta l’offrande, en prit une poignée ») ; rendu pédagogique."),
    Q('th-tempus-futurum', 'LEV 4:12',
      target=('efferet', 'v:ind.fut.act.3.sg'),
      dist=[
        ("le taureau entier, il l’emporte hors du camp, dans un lieu pur, où l’on jette les cendres, et il le brûlera au feu sur du bois: c’est sur le tas de cendres qu’il sera brûlé.", 'efferet', 'tempus', 'v:ind.praes.act.3.sg', "le transport du taureau est actuel"),
        ("le taureau entier, ils l’emporteront hors du camp, dans un lieu pur, où l’on jette les cendres, et il le brûlera au feu sur du bois: c’est sur le tas de cendres qu’il sera brûlé.", 'efferet', 'numerus', 'v:ind.fut.act.3.pl', "plusieurs porteurs"),
        ("le taureau entier, il l’emportera hors du camp, dans un lieu pur, où l’on jetait les cendres, et il le brûlera au feu sur du bois: c’est sur le tas de cendres qu’il sera brûlé.", 'solent', 'tempus', 'v:ind.praes.act.3.pl>v:ind.imperf.act.3.pl', "l’usage du lieu appartient au passé"),
      ],
      note="Segond a « le taureau entier » pour « et reliquo corpore » et « où l’on jette les cendres » pour « ubi cineres effundi solent » ; la cible est efferet."),
    Q('th-tempus-futurum', 'GEN 49:11',
      target=('lavabit', 'v:ind.fut.act.3.sg'),
      paed=True, fr="Il attache à la vigne son ânon, et au cep, ô mon fils, son ânesse ; il lavera dans le vin sa robe, et dans le sang de la grappe son manteau.",
      lemma={'vitem': 'uitis'},
      dist=[
        ("Il attache à la vigne son ânon, et au cep, ô mon fils, son ânesse ; il lave dans le vin sa robe, et dans le sang de la grappe son manteau.", 'lavabit', 'tempus', 'v:ind.praes.act.3.sg', "le lavage est présenté comme actuel"),
        ("Il attache à la vigne son ânon, et au cep, ô mon fils, son ânesse ; tu laveras dans le vin ta robe, et dans le sang de la grappe ton manteau.", 'lavabit', 'persona', 'v:ind.fut.act.2.sg', "c’est le fils interpellé qui lave"),
        ("Il attache à la vigne son ânon, et au cep, ô mon fils, son ânesse ; ils laveront dans le vin leur robe, et dans le sang de la grappe leur manteau.", 'lavabit', 'numerus', 'v:ind.fut.act.3.pl', "plusieurs personnes lavent"),
      ],
      note="Segond a le présent « Il lave » pour le futur lavabit et ne rend pas « o fili mi » ; rendu pédagogique."),
    Q('th-tempus-futurum', 'PRO 24:33',
      target=('dormies', 'v:ind.fut.act.2.sg'),
      paed=True, fr="Tu dormiras un peu, dis-je, tu sommeilleras un peu ; tu croiseras un peu les mains pour te reposer :",
      dist=[
        ("Tu dors un peu, dis-je, tu sommeilleras un peu ; tu croiseras un peu les mains pour te reposer :", 'dormies', 'tempus', 'v:ind.praes.act.2.sg', "le sommeil est actuel au lieu d’être prédit"),
        ("Il dormira un peu, dis-je, tu sommeilleras un peu ; tu croiseras un peu les mains pour te reposer :", 'dormies', 'persona', 'v:ind.fut.act.3.sg', "le paresseux n’est plus interpellé"),
        ("Tu dormiras un peu, dis-je, tu sommeilleras un peu ; vous croiserez un peu les mains pour te reposer :", 'conseres', 'numerus', 'v:ind.fut.act.2.sg>v:ind.fut.act.2.pl', "plusieurs paresseux croisent les mains"),
      ],
      note="Segond a des tournures nominales (« Un peu de sommeil, un peu d’assoupissement… ») ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'EST 15:8',
      target=('celabat', 'v:ind.imperf.act.3.sg'),
      paed=True, fr="Elle-même, le visage coloré d’un teint rose, les yeux gracieux et brillants, cachait un cœur triste et resserré par une crainte excessive.",
      dist=[
        ("Elle-même, le visage coloré d’un teint rose, les yeux gracieux et brillants, cacha un cœur triste et resserré par une crainte excessive.", 'celabat', 'tempus', 'v:ind.perf.act.3.sg', "un état qui dure devient un fait ponctuel"),
        ("Elle-même, le visage coloré d’un teint rose, les yeux gracieux et brillants, cache un cœur triste et resserré par une crainte excessive.", 'celabat', 'tempus', 'v:ind.praes.act.3.sg', "la dissimulation est présentée comme actuelle"),
        ("Elle-même, le visage coloré d’un teint rose, l’œil gracieux et brillant, cachait un cœur triste et resserré par une crainte excessive.", 'oculis', 'numerus', 'n:abl.pl>n:abl.sg', "un seul œil"),
      ],
      note="Segond n’a pas ce verset (addition grecque d’Esther) ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'DAN 1:8',
      target=('Proposuit', 'v:ind.perf.act.3.sg'),
      lemma={'potus': 'potus', 'præpositum': 'praepositus'},
      gloss={'præpositum': 'chef, préposé'},
      dist=[
        ("Daniel résout de ne pas se souiller par les mets du roi et par le vin dont le roi buvait, et il pria le chef des eunuques de ne pas l’obliger à se souiller.", 'Proposuit', 'tempus', 'v:ind.praes.act.3.sg', "la résolution est présentée comme actuelle"),
        ("Daniel résoudra de ne pas se souiller par les mets du roi et par le vin dont le roi buvait, et il pria le chef des eunuques de ne pas l’obliger à se souiller.", 'Proposuit', 'tempus', 'v:ind.fut.act.3.sg', "la résolution est annoncée au lieu d’être racontée"),
        ("Daniel résolut de ne pas se souiller par les mets du roi et par le vin dont le roi buvait, et il prie le chef des eunuques de ne pas l’obliger à se souiller.", 'rogavit', 'tempus', 'v:ind.perf.act.3.sg>v:ind.praes.act.3.sg', "la demande au chef des eunuques est actuelle"),
      ],
      note="Segond rend « ne pollueretur… ne contaminaretur » par des infinitifs ; la cible est Proposuit."),
    Q('th-tempus-futurum', '2SA 2:26',
      target=('desæviet', 'v:ind.fut.act.3.sg'),
      gloss={'Joab': 'Joab'},
      dist=[
        ("Abner appela Joab, et dit: L’épée dévore-t-elle toujours? Ne sais-tu pas qu’il y aura de l’amertume à la fin? Jusques à quand tarderas-tu à dire au peuple de ne plus poursuivre ses frères?", 'desæviet', 'tempus', 'v:ind.praes.act.3.sg', "la question porte sur le présent"),
        ("Abner appela Joab, et dit: Les épées dévoreront-elles toujours? Ne sais-tu pas qu’il y aura de l’amertume à la fin? Jusques à quand tarderas-tu à dire au peuple de ne plus poursuivre ses frères?", 'desæviet', 'numerus', 'v:ind.fut.act.3.pl', "plusieurs épées"),
        ("Abner appela Joab, et dit: L’épée dévorera-t-elle toujours? Ne sais-tu pas qu’il y aura de l’amertume à la fin? Jusques à quand tardera-t-il à dire au peuple de ne plus poursuivre ses frères?", 'dicis', 'persona', 'v:ind.praes.act.2.sg>v:ind.praes.act.3.sg', "un autre que Joab doit parler au peuple"),
      ],
      note="Segond a « L’épée » pour « tuus mucro » et « il y aura de l’amertume à la fin » pour « periculosa sit desperatio » ; la cible est desæviet."),
    Q('th-tempus-praeteritum', '1KI 7:17',
      target=('erat', 'v:ind.imperf.act.3.sg'),
      la='Utrumque capitellum columnarum fusile erat: septena versuum retiacula in capitello uno, et septena retiacula in capitello altero',
      paed=True, fr="Chacun des deux chapiteaux des colonnes était en métal fondu : sept rangs de réseaux sur un chapiteau, et sept réseaux sur l’autre chapiteau",
      gloss={'septena': 'sept chacun, sept par sept'},
      dist=[
        ("Chacun des deux chapiteaux des colonnes est en métal fondu : sept rangs de réseaux sur un chapiteau, et sept réseaux sur l’autre chapiteau", 'erat', 'tempus', 'v:ind.praes.act.3.sg', "la description est présentée comme actuelle"),
        ("Chacun des deux chapiteaux des colonnes fut en métal fondu : sept rangs de réseaux sur un chapiteau, et sept réseaux sur l’autre chapiteau", 'erat', 'tempus', 'v:ind.perf.act.3.sg', "un état durable devient un fait ponctuel"),
        ("Chacun des deux chapiteaux de la colonne était en métal fondu : sept rangs de réseaux sur un chapiteau, et sept réseaux sur l’autre chapiteau", 'columnarum', 'numerus', 'n:gen.pl>n:gen.sg', "une seule colonne"),
      ],
      note="Segond suit l’hébreu (« Il fit des treillis en forme de réseaux… ») ; rendu pédagogique de la seconde partie du verset."),
    Q('th-nonfinita', 'ROM 1:29',
      target=('repletos', 'v:part.perf.pass.acc.pl.m'),
      la='repletos omni iniquitate, malitia, fornicatione, avaritia, nequitia, plenos invidia, homicidio, contentione, dolo, malignitate',
      paed=True, fr="remplis de toute injustice, de méchanceté, de fornication, de cupidité, de malice ; pleins d’envie, de meurtre, de querelle, de ruse, de malignité",
      dist=[
        ("rempli de toute injustice, de méchanceté, de fornication, de cupidité, de malice ; plein d’envie, de meurtre, de querelle, de ruse, de malignité", 'repletos', 'numerus', 'v:part.perf.pass.acc.sg.m', "un seul homme au lieu des impies"),
        ("ils ont été remplis de toute injustice, de méchanceté, de fornication, de cupidité, de malice ; pleins d’envie, de meurtre, de querelle, de ruse, de malignité", 'repletos', 'nonfinita', '!verbum finitum (repleti sunt)', "le participe devient une proposition indépendante au lieu de qualifier « eux »"),
        ("remplis de toute injustice, de méchanceté, de fornication, de cupidité, de malice ; pleins d’envie, de meurtres, de querelle, de ruse, de malignité", 'homicidio', 'numerus', 'n:abl.sg>n:abl.pl', "plusieurs meurtres"),
      ],
      note="Segond omet « fornicatione » (variante textuelle) et rattache « susurrones » au verset suivant ; rendu pédagogique de la liste."),
    Q('th-tempus-futurum', 'DEU 24:21',
      target=('colliges', 'v:ind.fut.act.2.sg'),
      dist=[
        ("Quand tu vendangeras ta vigne, tu ne cueilles point ensuite les grappes qui y seront restées: elles seront pour l’étranger, pour l’orphelin et pour la veuve.", 'colliges', 'tempus', 'v:ind.praes.act.2.sg', "une défense devient un constat"),
        ("Quand tu vendangeras ta vigne, il ne cueillera point ensuite les grappes qui y seront restées: elles seront pour l’étranger, pour l’orphelin et pour la veuve.", 'colliges', 'persona', 'v:ind.fut.act.3.sg', "la défense vise un tiers"),
        ("Quand tu vendangeras ta vigne, tu ne cueilleras point ensuite les grappes qui y seront restées: elles sont pour l’étranger, pour l’orphelin et pour la veuve.", 'cedent', 'tempus', 'v:ind.fut.act.3.pl>v:ind.praes.act.3.pl', "l’attribution des grappes est actuelle"),
      ]),
    Q('th-tempus-praeteritum', 'ACT 20:9',
      target=('cecidit', 'v:ind.perf.act.3.sg'),
      gloss={'Eutychus': 'Eutychus', 'adolescens': 'jeune homme'},
      lemma={'adolescens': 'adolescens', 'Paulo': 'paulus'},
      dist=[
        ("Or, un jeune homme nommé Eutychus, qui était assis sur la fenêtre, s’endormit profondément pendant le long discours de Paul; entraîné par le sommeil, il tombe du troisième étage en bas, et il fut relevé mort.", 'cecidit', 'tempus', 'v:ind.praes.act.3.sg', "la chute est présentée comme actuelle"),
        ("Or, un jeune homme nommé Eutychus, qui était assis sur la fenêtre, s’endormit profondément pendant le long discours de Paul; entraîné par le sommeil, il tombera du troisième étage en bas, et il fut relevé mort.", 'cecidit', 'tempus', 'v:ind.fut.act.3.sg', "la chute est annoncée au lieu d’être racontée"),
        ("Or, un jeune homme nommé Eutychus, qui était assis sur la fenêtre, s’endort profondément pendant le long discours de Paul; entraîné par le sommeil, il tomba du troisième étage en bas, et il fut relevé mort.", 'mergeretur', 'tempus', 'v:subj.imperf.pass.3.sg>v:subj.praes.pass.3.sg', "l’endormissement est actuel"),
      ],
      note="Segond rend « cum mergeretur somno gravi » par « s’endormit profondément » ; la cible est cecidit."),
    Q('th-nonfinita', 'EZE 18:12',
      target=('contristantem', 'v:part.praes.act.acc.sg.m'),
      paed=True, fr="opprimant le malheureux et le pauvre, commettant des rapines, ne rendant pas le gage, levant les yeux vers les idoles, commettant l’abomination :",
      dist=[
        ("il opprime le malheureux et le pauvre, commettant des rapines, ne rendant pas le gage, levant les yeux vers les idoles, commettant l’abomination :", 'contristantem', 'nonfinita', '!verbum finitum (contristat)', "le participe devient la proposition principale au lieu de qualifier le fils"),
        ("opprimant le malheureux et les pauvres, commettant des rapines, ne rendant pas le gage, levant les yeux vers les idoles, commettant l’abomination :", 'pauperem', 'numerus', 'a:acc.sg.m>a:acc.pl.m', "plusieurs pauvres"),
        ("opprimant le malheureux et le pauvre, commettant des rapines, ne rendant pas le gage, levant les yeux vers l’idole, commettant l’abomination :", 'idola', 'numerus', 'n:acc.pl>n:acc.sg', "une seule idole"),
      ],
      note="Segond rend les participes par des conditionnelles (« s’il opprime… ») ; rendu pédagogique."),
    Q('th-persona', 'EXO 9:18',
      target=('pluam', 'v:ind.fut.act.1.sg'),
      dist=[
        ("voici, il fera pleuvoir demain, à cette heure, une grêle tellement forte, qu’il n’y en a point eu de semblable en Égypte depuis le jour où elle a été fondée jusqu’à présent.", 'pluam', 'persona', 'v:ind.fut.act.3.sg', "un autre que Dieu envoie la grêle"),
        ("voici, nous ferons pleuvoir demain, à cette heure, une grêle tellement forte, qu’il n’y en a point eu de semblable en Égypte depuis le jour où elle a été fondée jusqu’à présent.", 'pluam', 'numerus', 'v:ind.fut.act.1.pl', "plusieurs envoient la grêle"),
        ("voici, je ferai pleuvoir demain, à cette heure, une grêle tellement forte, qu’il n’y en a point eu de semblables en Égypte depuis le jour où elle a été fondée jusqu’à présent.", 'fuit', 'numerus', 'v:ind.perf.act.3.sg>v:ind.perf.act.3.pl', "plusieurs grêles semblables"),
      ]),
    Q('th-tempus-futurum', 'ISA 20:4',
      target=('minabit', 'v:ind.fut.act.3.sg'),
      gloss={'Assyriorum': 'Assyriens (d’Assyrie)'},
      lemma={'natibus': 'natis'},
      dist=[
        ("de même le roi d’Assyrie emmène de l’Égypte et de l’Éthiopie captifs et exilés les jeunes hommes et les vieillards, nus et déchaussés, et le dos découvert, à la honte de l’Égypte.", 'minabit', 'tempus', 'v:ind.praes.act.3.sg', "la déportation est présentée comme actuelle"),
        ("de même les rois d’Assyrie emmèneront de l’Égypte et de l’Éthiopie captifs et exilés les jeunes hommes et les vieillards, nus et déchaussés, et le dos découvert, à la honte de l’Égypte.", 'minabit', 'numerus', 'v:ind.fut.act.3.pl', "plusieurs rois"),
        ("de même le roi d’Assyrie emmènera de l’Égypte et de l’Éthiopie captifs et exilés le jeune homme et les vieillards, nus et déchaussés, et le dos découvert, à la honte de l’Égypte.", 'juvenum', 'numerus', 'n:gen.pl>n:gen.sg', "un seul jeune homme"),
      ],
      note="Segond a « le dos découvert » pour « discoopertis natibus » ; la cible est minabit."),
    Q('th-tempus-praeteritum', 'PRO 30:33',
      target=('producit', 'v:ind.praes.act.3.sg'),
      dist=[
        ("Car la pression du lait produit de la crème, La pression du nez produit du sang, Et la pression de la colère a produit des querelles.", 'producit', 'tempus', 'v:ind.perf.act.3.sg', "la conséquence est rejetée dans le passé"),
        ("Car la pression du lait produit de la crème, La pression du nez produit du sang, Et la pression de la colère produira des querelles.", 'producit', 'tempus', 'v:ind.fut.act.3.sg', "la sentence devient une prédiction"),
        ("Car la pression du lait produit de la crème, La pression du nez produit du sang, Et la pression de la colère produit une querelle.", 'discordias', 'numerus', 'n:acc.pl>n:acc.sg', "une seule querelle"),
      ],
      note="Segond suit l’hébreu et nominalise (« la pression du lait ») les relatives « qui premit… qui emungit… qui provocat » ; la cible est producit."),
    Q('th-modus-imperativus', 'GEN 30:32',
      target=('separa', 'v:imp.praes.act.2.sg'),
      dist=[
        ("Je parcourrai aujourd’hui tout ton troupeau; mettez à part parmi les brebis tout agneau tacheté et marqueté et tout agneau noir, et parmi les chèvres tout ce qui est marqueté et tacheté. Ce sera mon salaire.", 'separa', 'numerus', 'v:imp.praes.act.2.pl', "l’ordre s’adresse à plusieurs personnes"),
        ("Je parcourrai aujourd’hui tout ton troupeau; tu mets à part parmi les brebis tout agneau tacheté et marqueté et tout agneau noir, et parmi les chèvres tout ce qui est marqueté et tacheté. Ce sera mon salaire.", 'separa', 'modus', 'v:ind.praes.act.2.sg', "un ordre devient un constat"),
        ("Je parcourrai aujourd’hui tout ton troupeau; mets à part parmi les brebis tout agneau tacheté et marqueté et tout agneau noir, et parmi les chèvres tout ce qui est marqueté et tacheté. Ce seront mes salaires.", 'merces', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs salaires"),
      ],
      note="Segond suit l’hébreu pour « Gyra omnes greges tuos » (« Je parcourrai… ton troupeau ») ; la cible est separa."),
    Q('th-tempus-praeteritum', 'JDG 16:12',
      target=('rupit', 'v:ind.perf.act.3.sg'),
      dist=[
        ("Delila prit des cordes neuves, avec lesquelles elle le lia. Puis elle lui dit: Les Philistins sont sur toi, Samson! Or des gens se tenaient en embuscade dans une chambre. Et il rompt comme un fil les cordes qu’il avait aux bras.", 'rupit', 'tempus', 'v:ind.praes.act.3.sg', "la rupture des cordes est présentée comme actuelle"),
        ("Delila prit des cordes neuves, avec lesquelles elle le lia. Puis elle lui dit: Les Philistins sont sur toi, Samson! Or des gens se tenaient en embuscade dans une chambre. Et il rompra comme un fil les cordes qu’il avait aux bras.", 'rupit', 'tempus', 'v:ind.fut.act.3.sg', "la rupture des cordes est annoncée"),
        ("Delila prit des cordes neuves, avec lesquelles elle le lia. Puis elles lui dirent: Les Philistins sont sur toi, Samson! Or des gens se tenaient en embuscade dans une chambre. Et il rompit comme un fil les cordes qu’il avait aux bras.", 'clamavit', 'numerus', 'v:ind.perf.act.3.sg>v:ind.perf.act.3.pl', "plusieurs femmes crient"),
      ],
      note="Segond suit l’hébreu et explicite « des cordes neuves » et « qu’il avait aux bras » ; la cible est rupit."),
    Q('th-tempus-futurum', 'ISA 35:7',
      target=('orietur', 'v:ind.fut.act.3.sg'),
      paed=True, fr="et ce qui était aride deviendra un étang, et la terre altérée des sources d’eaux. Dans les repaires où habitaient auparavant les dragons naîtra la verdure du roseau et du jonc.",
      dist=[
        ("et ce qui était aride deviendra un étang, et la terre altérée des sources d’eaux. Dans les repaires où habitaient auparavant les dragons naît la verdure du roseau et du jonc.", 'orietur', 'tempus', 'v:ind.praes.act.3.sg', "la verdure pousse dès maintenant"),
        ("et ce qui était aride deviendra un étang, et la terre altérée des sources d’eaux. Dans les repaires où habitait auparavant le dragon naîtra la verdure du roseau et du jonc.", 'habitabant', 'numerus', 'v:ind.imperf.act.3.pl>v:ind.imperf.act.3.sg', "un seul dragon"),
        ("et ce qui était aride devient un étang, et la terre altérée des sources d’eaux. Dans les repaires où habitaient auparavant les dragons naîtra la verdure du roseau et du jonc.", 'erit', 'tempus', 'v:ind.fut.act.3.sg>v:ind.praes.act.3.sg', "la transformation est actuelle"),
      ],
      note="Segond suit l’hébreu (« Le mirage se changera en étang… Croîtront des roseaux ») ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'ACT 15:12',
      target=('Tacuit', 'v:ind.perf.act.3.sg'),
      lemma={'Paulum': 'paulus'},
      dist=[
        ("Toute l’assemblée garde le silence, et l’on écouta Barnabas et Paul, qui racontèrent tous les miracles et les prodiges que Dieu avait faits par eux au milieu des païens.", 'Tacuit', 'tempus', 'v:ind.praes.act.3.sg', "le silence est présenté comme actuel"),
        ("Toute l’assemblée gardera le silence, et l’on écouta Barnabas et Paul, qui racontèrent tous les miracles et les prodiges que Dieu avait faits par eux au milieu des païens.", 'Tacuit', 'tempus', 'v:ind.fut.act.3.sg', "le silence est annoncé au lieu d’être raconté"),
        ("Toute l’assemblée garda le silence, et l’on écouta Barnabas et Paul, qui racontèrent tous les miracles et les prodiges que Dieu a faits par eux au milieu des païens.", 'fecisset', 'tempus', 'v:subj.plusq.act.3.sg>v:subj.perf.act.3.sg', "les miracles ne sont plus antérieurs au récit"),
      ],
      note="Segond a « l’on écouta » pour l’imparfait audiebant et une relative pour le participe narrantes ; la cible est Tacuit."),
    Q('th-numerus', 'MAT 18:6',
      target=('credunt', 'v:ind.praes.act.3.pl'),
      dist=[
        ("Mais, si quelqu’un scandalisait un de ces petits qui croit en moi, il vaudrait mieux pour lui qu’on suspendît à son cou une meule de moulin, et qu’on le jetât au fond de la mer.", 'credunt', 'numerus', 'v:ind.praes.act.3.sg', "la foi n’est attribuée qu’au petit scandalisé, non à tous les petits"),
        ("Mais, si quelqu’un scandalisait un de ces petits qui croient en moi, il vaudrait mieux pour lui qu’on suspendît à son cou des meules de moulin, et qu’on le jetât au fond de la mer.", 'mola', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs meules"),
        ("Mais, si quelqu’un scandalisait un de ces petits qui croient en moi, il vaudrait mieux pour lui qu’on suspendît à son cou une meule de moulin, et qu’on le jetât au fond des mers.", 'maris', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs mers"),
      ],
      note="Segond rend les passifs « suspendatur… demergatur » par « qu’on suspendît… qu’on le jetât » ; la cible est credunt."),
    Q('th-modus-subiunctivus', 'HEB 3:14',
      target=('retineamus', 'v:subj.praes.act.1.pl'),
      dist=[
        ("Car nous sommes devenus participants de Christ, si toutefois nous retenons fermement jusqu’à la fin l’assurance que nous avions au commencement,", 'retineamus', 'modus', 'v:ind.praes.act.1.pl', "la condition devient un constat"),
        ("Car nous sommes devenus participants de Christ, pourvu que nous retinssions fermement jusqu’à la fin l’assurance que nous avions au commencement,", 'retineamus', 'tempus', 'v:subj.imperf.act.1.pl', "la condition est rejetée dans le passé"),
        ("Car nous sommes devenus participants de Christ, pourvu que je retienne fermement jusqu’à la fin l’assurance que nous avions au commencement,", 'retineamus', 'numerus', 'v:subj.praes.act.1.sg', "un seul fidèle est concerné par la condition"),
      ],
      note="Segond rend « initium substantiæ ejus » par « l’assurance que nous avions au commencement »."),
    Q('th-tempus-praeteritum', '2CH 3:5',
      target=('texit', 'v:ind.perf.act.3.sg'),
      dist=[
        ("Il revêt de bois de cyprès la grande maison, la couvrit d’or pur, et y fit sculpter des palmes et des chaînettes.", 'texit', 'tempus', 'v:ind.praes.act.3.sg', "le revêtement est présenté comme en cours"),
        ("Ils revêtirent de bois de cyprès la grande maison, la couvrit d’or pur, et y fit sculpter des palmes et des chaînettes.", 'texit', 'numerus', 'v:ind.perf.act.3.pl', "plusieurs ouvriers au lieu de Salomon"),
        ("Il revêtit de bois de cyprès la grande maison, la couvrit d’or pur, et y fera sculpter des palmes et des chaînettes.", 'sculpsitque', 'tempus', 'v:ind.perf.act.3.sg>v:ind.fut.act.3.sg', "la sculpture est à venir"),
      ],
      note="Segond a « cyprès » pour « abiegnis » (sapin) et résume « laminas auri obrizi affixit per totum » ; la cible est texit."),
    Q('th-tempus-praeteritum', 'JOB 39:25',
      target=('dicit', 'v:ind.praes.act.3.sg'),
      fr_ref='JOB 39:28',
      dist=[
        ("Quand la trompette sonne, il a dit: En avant! Et de loin il flaire la bataille, La voix tonnante des chefs et les cris de guerre.", 'dicit', 'tempus', 'v:ind.perf.act.3.sg', "le cri du cheval est rejeté dans le passé"),
        ("Quand la trompette sonne, il dira: En avant! Et de loin il flaire la bataille, La voix tonnante des chefs et les cris de guerre.", 'dicit', 'tempus', 'v:ind.fut.act.3.sg', "le cri du cheval est annoncé"),
        ("Quand la trompette sonne, il dit: En avant! Et de loin il flaire la bataille, La voix tonnante du chef et les cris de guerre.", 'ducum', 'numerus', 'n:gen.pl>n:gen.sg', "un seul chef"),
      ],
      note="Décalage de numérotation : la Vulgate 39:25 correspond à Segond 39:28 ; Segond a « En avant ! » pour « Vah ! »."),
    Q('th-modus-imperativus', 'JER 51:11',
      target=('Acuite', 'v:imp.praes.act.2.pl'),
      gloss={'Babylonem': 'Babylone'},
      dist=[
        ("Aiguise les flèches, saisissez les boucliers! L’Éternel a excité l’esprit des rois de Médie, Parce qu’il veut détruire Babylone; Car c’est la vengeance de l’Éternel, La vengeance de son temple.", 'Acuite', 'numerus', 'v:imp.praes.act.2.sg', "l’ordre s’adresse à un seul guerrier"),
        ("Vous aiguisez les flèches, saisissez les boucliers! L’Éternel a excité l’esprit des rois de Médie, Parce qu’il veut détruire Babylone; Car c’est la vengeance de l’Éternel, La vengeance de son temple.", 'Acuite', 'modus', 'v:ind.praes.act.2.pl', "un ordre devient un constat"),
        ("Aiguisez les flèches, saisissez les boucliers! L’Éternel a excité l’esprit du roi de Médie, Parce qu’il veut détruire Babylone; Car c’est la vengeance de l’Éternel, La vengeance de son temple.", 'regum', 'numerus', 'n:gen.pl>n:gen.sg', "un seul roi"),
      ],
      note="Segond suit l’hébreu pour « implete pharetras » (« saisissez les boucliers ») et « mens ejus est ut perdat » (« il veut détruire ») ; la cible est Acuite."),
    Q('th-modus-imperativus', 'NAH 3:14',
      target=('hauri', 'v:imp.praes.act.2.sg'),
      lemma={'laterem': 'later'},
      gloss={'laterem': 'brique'},
      dist=[
        ("Puisez de l’eau pour le siège! Répare tes forteresses! Entre dans la boue, foule l’argile! Rétablis le four à briques!", 'hauri', 'numerus', 'v:imp.praes.act.2.pl', "l’ordre s’adresse à plusieurs personnes"),
        ("Tu puises de l’eau pour le siège! Répare tes forteresses! Entre dans la boue, foule l’argile! Rétablis le four à briques!", 'hauri', 'modus', 'v:ind.praes.act.2.sg', "un ordre devient un constat"),
        ("Puise de l’eau pour le siège! Répare ta forteresse! Entre dans la boue, foule l’argile! Rétablis le four à briques!", 'munitiones', 'numerus', 'n:acc.pl>n:acc.sg', "une seule forteresse"),
      ],
      note="Segond a « Rétablis le four à briques » pour « subigens tene laterem » ; la cible est hauri."),
    Q('th-tempus-praeteritum', 'DEU 29:23',
      target=('subvertit', 'v:ind.perf.act.3.sg'),
      dist=[
        ("de l’embrasement de toute la contrée, où il n’y aura ni semence, ni produit, ni aucune herbe qui croisse, comme au bouleversement de Sodome, de Gomorrhe, d’Adma et de Tseboïm, que l’Éternel détruit dans sa colère et dans sa fureur,", 'subvertit', 'tempus', 'v:ind.praes.act.3.sg', "la destruction des villes est présentée comme actuelle"),
        ("de l’embrasement de toute la contrée, où il n’y aura ni semence, ni produit, ni aucune herbe qui croisse, comme au bouleversement de Sodome, de Gomorrhe, d’Adma et de Tseboïm, que l’Éternel détruira dans sa colère et dans sa fureur,", 'subvertit', 'tempus', 'v:ind.fut.act.3.sg', "la destruction des villes est annoncée"),
        ("de l’embrasement de toute la contrée, où il n’y aura ni semence, ni produit, ni aucune herbe qui croisse, comme au bouleversement de Sodome, de Gomorrhe, d’Adma et de Tseboïm, que l’Éternel détruisit dans ses colères et dans sa fureur,", 'ira', 'numerus', 'n:abl.sg>n:abl.pl', "plusieurs accès de colère"),
      ],
      note="Segond a « de l’embrasement de toute la contrée » pour « sulphure, et salis ardore comburens » ; la cible est subvertit."),
]
