# sheet_010 → batch_010
# skipped: 1CH 9:12 (list of names, no verb)
# skipped: NUM 32:3 (list of place names, no verb or declined word)
ITEMS = [
    Q('th-tempus-praeteritum', 'ACT 13:1',
      target=('Erant', 'v:ind.imperf.act.3.pl'),
      dist=[
        ("Il y a dans l’Église d’Antioche des prophètes et des docteurs: Barnabas, Siméon appelé Niger, Lucius de Cyrène, Manahen, qui avait été élevé avec Hérode le tétrarque, et Saul.", 'Erant', 'tempus', 'v:ind.praes.act.3.pl', "la présence des prophètes est actuelle"),
        ("Il y aura dans l’Église d’Antioche des prophètes et des docteurs: Barnabas, Siméon appelé Niger, Lucius de Cyrène, Manahen, qui avait été élevé avec Hérode le tétrarque, et Saul.", 'Erant', 'tempus', 'v:ind.fut.act.3.pl', "la présence des prophètes est annoncée"),
        ("Il y eut dans l’Église d’Antioche des prophètes et des docteurs: Barnabas, Siméon appelé Niger, Lucius de Cyrène, Manahen, qui avait été élevé avec Hérode le tétrarque, et Saul.", 'Erant', 'tempus', 'v:ind.perf.act.3.pl', "un état durable devient un fait ponctuel"),
      ],
      note="Segond rend la relative « qui vocabatur Niger » par un participe ; la cible est le verbe principal."),
    Q('th-nonfinita', 'LEV 13:42',
      target=('exortus', 'v:part.perf.act.nom.sg.m'),
      paed=True, fr="Mais si, sur la partie chauve de devant ou sur celle de derrière, une couleur blanche ou rousse est apparue,",
      dist=[
        ("Mais si, sur la partie chauve de devant ou sur celle de derrière, des couleurs blanches ou rousses sont apparues,", 'exortus', 'numerus', 'v:part.perf.act.nom.pl.m', "plusieurs couleurs"),
        ("Mais si, sur la partie chauve de devant ou sur celle de derrière, une couleur blanche ou rousse est sur le point d’apparaître,", 'exortus', 'tempus', 'v:part.fut.act.nom.sg.m', "l’apparition n’a pas encore eu lieu"),
        ("Mais si, sur les parties chauves de devant ou sur celle de derrière, une couleur blanche ou rousse est apparue,", 'calvitio', 'numerus', 'n:abl.sg>n:abl.pl', "plusieurs parties chauves"),
      ],
      note="Segond paraphrase (« une plaie d’un blanc rougeâtre… c’est la lèpre ») ; rendu pédagogique du futur antérieur périphrastique fuerit exortus."),
    Q('th-modus-imperativus', 'TIT 3:9',
      target=('devita', 'v:imp.praes.act.2.sg'),
      dist=[
        ("Mais évitez les discussions folles, les généalogies, les querelles, les disputes relatives à la loi; car elles sont inutiles et vaines.", 'devita', 'numerus', 'v:imp.praes.act.2.pl', "l’ordre s’adresse à plusieurs personnes"),
        ("Mais tu évites les discussions folles, les généalogies, les querelles, les disputes relatives à la loi; car elles sont inutiles et vaines.", 'devita', 'modus', 'v:ind.praes.act.2.sg', "un ordre devient un constat"),
        ("Mais évite les discussions folles, les généalogies, les querelles, les disputes relatives aux lois; car elles sont inutiles et vaines.", 'legis', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs lois au lieu de la Loi"),
      ]),
    Q('th-tempus-praeteritum', 'GEN 31:2',
      target=('animadvertit', 'v:ind.perf.act.3.sg'),
      gloss={'animadvertit': 'remarquer, observer', 'nudiustertius': 'avant-hier'},
      dist=[
        ("Jacob remarque aussi le visage de Laban; et voici, il n’était plus envers lui comme auparavant.", 'animadvertit', 'tempus', 'v:ind.praes.act.3.sg', "l’observation se fait maintenant"),
        ("Jacob remarquera aussi le visage de Laban; et voici, il n’était plus envers lui comme auparavant.", 'animadvertit', 'tempus', 'v:ind.fut.act.3.sg', "l’observation est à venir"),
        ("Jacob remarqua aussi le visage de Laban; et voici, il n’est plus envers lui comme auparavant.", 'esset', 'tempus', 'v:subj.imperf.act.3.sg>v:subj.praes.act.3.sg', "le changement d’attitude est actuel"),
      ],
      note="Segond explicite le sujet « Jacob » et rend « heri et nudiustertius » par « auparavant »."),
    Q('th-nonfinita', '2MA 2:32',
      target=('brevianti', 'v:part.praes.act.dat.sg.m'),
      paed=True, fr="Mais rechercher la brièveté du discours et éviter les développements des faits, c’est ce qu’il faut accorder à celui qui abrège.",
      dist=[
        ("Mais rechercher la brièveté du discours et éviter les développements des faits, c’est ce qu’il faut accorder à ceux qui abrègent.", 'brevianti', 'numerus', 'v:part.praes.act.dat.pl.m', "plusieurs abréviateurs"),
        ("Mais rechercher la brièveté du discours et éviter les développements des faits, c’est ce qu’il faut accorder à celui qui va abréger.", 'brevianti', 'tempus', 'v:part.fut.act.dat.sg.m', "l’abrégé n’est pas encore commencé"),
        ("Mais rechercher la brièveté du discours et éviter le développement des faits, c’est ce qu’il faut accorder à celui qui abrège.", 'executiones', 'numerus', 'n:acc.pl>n:acc.sg', "un seul développement"),
      ],
      note="Livre absent de Segond ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'JOH 11:1',
      target=('Erat', 'v:ind.imperf.act.3.sg'),
      dist=[
        ("Il y a un homme malade, Lazare, de Béthanie, village de Marie et de Marthe, sa sœur.", 'Erat', 'tempus', 'v:ind.praes.act.3.sg', "la maladie est actuelle"),
        ("Il y aura un homme malade, Lazare, de Béthanie, village de Marie et de Marthe, sa sœur.", 'Erat', 'tempus', 'v:ind.fut.act.3.sg', "la maladie est annoncée"),
        ("Il y eut un homme malade, Lazare, de Béthanie, village de Marie et de Marthe, sa sœur.", 'Erat', 'tempus', 'v:ind.perf.act.3.sg', "un état qui dure devient un fait ponctuel"),
      ]),
    Q('th-nonfinita', '2CH 24:26',
      target=('Insidiati', 'v:part.perf.act.nom.pl.m'),
      gloss={'Zabad': 'Zabad', 'Semaath': 'Schimeath', 'Ammanitidis': 'Ammonite (femme)', 'Jozabad': 'Jozabad', 'Semmarith': 'Schimrith'},
      dist=[
        ("Voici ceux qui conspirent contre lui: Zabad, fils de Schimeath, femme Ammonite, et Jozabad, fils de Schimrith, femme Moabite.", 'Insidiati', 'tempus', 'v:part.praes.act.nom.pl.m', "le complot est en cours"),
        ("Voici celui qui conspira contre lui: Zabad, fils de Schimeath, femme Ammonite, et Jozabad, fils de Schimrith, femme Moabite.", 'Insidiati', 'numerus', 'v:part.perf.act.nom.sg.m', "un seul conspirateur"),
        ("Voici ceux qui conspirèrent contre eux: Zabad, fils de Schimeath, femme Ammonite, et Jozabad, fils de Schimrith, femme Moabite.", 'ei', 'numerus', 'a:dat.sg.m>a:dat.pl.m', "plusieurs victimes du complot"),
      ]),
    Q('th-numerus', 'JDG 16:27',
      target=('erat', 'v:ind.imperf.act.3.sg'),
      gloss={'Philisthinorum': 'Philistins'},
      dist=[
        ("Les maisons étaient remplies d’hommes et de femmes; tous les princes des Philistins étaient là, et il y avait sur le toit environ trois mille personnes, hommes et femmes, qui regardaient Samson jouer.", 'erat', 'numerus', 'v:ind.imperf.act.3.pl', "plusieurs maisons"),
        ("La maison était remplie d’un homme et de femmes; tous les princes des Philistins étaient là, et il y avait sur le toit environ trois mille personnes, hommes et femmes, qui regardaient Samson jouer.", 'virorum', 'numerus', 'n:gen.pl>n:gen.sg', "un seul homme"),
        ("La maison était remplie d’hommes et de femmes; tous les princes des Philistins étaient là, et il y avait sur les toits environ trois mille personnes, hommes et femmes, qui regardaient Samson jouer.", 'tecto', 'numerus', 'n:abl.sg>n:abl.pl', "plusieurs toits"),
      ]),
    Q('th-numerus', '2CO 6:6',
      target=('Spiritu', 'n:abl.sg'),
      dist=[
        ("par la pureté, par la connaissance, par la longanimité, par la bonté, par des esprits saints, par une charité sincère,", 'Spiritu', 'numerus', 'n:abl.pl', "plusieurs esprits"),
        ("par la pureté, par la connaissance, par la longanimité, par la bonté, par un esprit saint, par des charités sincères,", 'caritate', 'numerus', 'n:abl.sg>n:abl.pl', "plusieurs charités"),
        ("par la pureté, par la connaissance, par la longanimité, par des bontés, par un esprit saint, par une charité sincère,", 'suavitate', 'numerus', 'n:abl.sg>n:abl.pl', "des actes de bonté au lieu de la qualité"),
      ]),
    Q('th-nonfinita', 'NAH 2:7',
      target=('gementes', 'v:part.praes.act.nom.pl.f'),
      paed=True, fr_ref='NAH 2:8',
      fr="Et le soldat captif a été emmené, et ses servantes étaient poussées en avant, gémissant comme des colombes, murmurant dans leur cœur.",
      dist=[
        ("Et le soldat captif a été emmené, et ses servantes étaient poussées en avant, prêtes à gémir comme des colombes, murmurant dans leur cœur.", 'gementes', 'tempus', 'v:part.fut.act.nom.pl.f', "le gémissement n’a pas encore commencé"),
        ("Et le soldat captif a été emmené, et ses servantes étaient poussées en avant comme des colombes gémissantes, murmurant dans leur cœur.", 'gementes', 'congruentia', '!cum columbæ (nōm. pl. f.) congruēns', "ce sont les colombes qui gémissent"),
        ("Et le soldat captif a été emmené, et sa servante était poussée en avant, gémissant comme une colombe, murmurant dans son cœur.", 'ancillæ', 'numerus', 'n:nom.pl>n:nom.sg', "une seule servante"),
      ],
      note="Segond 2:8 (« elle est mise à nu… ses servantes gémissent ») paraphrase ; rendu pédagogique de l’imparfait minabantur."),
    Q('th-tempus-futurum', '1SA 1:14',
      target=('eris', 'v:ind.fut.act.2.sg'),
      la='dixitque ei: Usquequo ebria eris? digere paulisper vinum',
      fr='et il lui dit: Jusques à quand seras-tu dans l’ivresse? Fais passer ton vin.',
      dist=[
        ("et il lui dit: Jusques à quand es-tu dans l’ivresse? Fais passer ton vin.", 'eris', 'tempus', 'v:ind.praes.act.2.sg', "l’ivresse est constatée au présent"),
        ("et il lui dit: Jusques à quand sera-t-elle dans l’ivresse? Fais passer ton vin.", 'eris', 'persona', 'v:ind.fut.act.3.sg', "on parle d’une tierce personne"),
        ("et il lui dit: Jusques à quand serez-vous dans l’ivresse? Fais passer ton vin.", 'eris', 'numerus', 'v:ind.fut.act.2.pl', "plusieurs personnes ivres"),
      ],
      note="Segond ne rend ni « paulisper » ni « quo mades »."),
    Q('th-tempus-praeteritum', '2MA 11:5',
      target=('expugnabat', 'v:ind.imperf.act.3.sg'),
      paed=True, fr="Entré en Judée et s’approchant de Bethsur, qui était dans un lieu resserré, à une distance de cinq stades de Jérusalem, il attaquait cette place forte.",
      gloss={'Jerosolyma': 'Jérusalem'},
      dist=[
        ("Entré en Judée et s’approchant de Bethsur, qui était dans un lieu resserré, à une distance de cinq stades de Jérusalem, il attaqua cette place forte.", 'expugnabat', 'tempus', 'v:ind.perf.act.3.sg', "un siège qui dure devient un assaut ponctuel"),
        ("Entré en Judée et s’approchant de Bethsur, qui était dans un lieu resserré, à une distance de cinq stades de Jérusalem, il attaquera cette place forte.", 'expugnabat', 'tempus', 'v:ind.fut.act.3.sg', "l’attaque est à venir"),
        ("Entré en Judée et s’approchant de Bethsur, qui était dans un lieu resserré, à une distance de cinq stades de Jérusalem, j’attaquais cette place forte.", 'expugnabat', 'persona', 'v:ind.imperf.act.1.sg', "le narrateur devient l’assaillant"),
      ],
      note="Livre absent de Segond ; rendu pédagogique."),
    Q('th-persona', 'PSA 17:37',
      target=('Dilatasti', 'v:ind.perf.act.2.sg'),
      paed=True, fr="Tu as élargi mes pas sous moi, et mes pieds n’ont pas été affaiblis.",
      dist=[
        ("Il a élargi mes pas sous moi, et mes pieds n’ont pas été affaiblis.", 'Dilatasti', 'persona', 'v:ind.perf.act.3.sg', "on parle de Dieu au lieu de s’adresser à lui"),
        ("J’ai élargi mes pas sous moi, et mes pieds n’ont pas été affaiblis.", 'Dilatasti', 'persona', 'v:ind.perf.act.1.sg', "le psalmiste se l’attribue"),
        ("Vous avez élargi mes pas sous moi, et mes pieds n’ont pas été affaiblis.", 'Dilatasti', 'numerus', 'v:ind.perf.act.2.pl', "plusieurs destinataires"),
      ],
      note="Segond 18:37 a le présent (« Tu élargis… ne chancellent point ») pour les parfaits latins ; rendu pédagogique."),
    Q('th-tempus-praeteritum', '1CH 4:18',
      target=('peperit', 'v:ind.perf.act.3.sg'),
      gloss={'Judaia': 'la Juive', 'Jared': 'Jéred', 'Gedor': 'Guedor', 'Heber': 'Héber', 'Socho': 'Soco', 'Icuthiel': 'Jekuthiel', 'Zanoë': 'Zanoach', 'Bethiæ': 'Bithja', 'Mered': 'Méred'},
      dist=[
        ("Sa femme, la Juive, enfante Jéred, père de Guedor, Héber, père de Soco, et Jekuthiel, père de Zanoach. Ceux-là sont les fils de Bithja, fille de Pharaon, que Méred prit pour femme.", 'peperit', 'tempus', 'v:ind.praes.act.3.sg', "la naissance est présentée comme actuelle"),
        ("Sa femme, la Juive, enfantera Jéred, père de Guedor, Héber, père de Soco, et Jekuthiel, père de Zanoach. Ceux-là sont les fils de Bithja, fille de Pharaon, que Méred prit pour femme.", 'peperit', 'tempus', 'v:ind.fut.act.3.sg', "la naissance est annoncée"),
        ("Sa femme, la Juive, enfanta Jéred, père de Guedor, Héber, père de Soco, et Jekuthiel, père de Zanoach. Ceux-là sont les fils de Bithja, fille de Pharaon, que Méred prend pour femme.", 'accepit', 'tempus', 'v:ind.perf.act.3.sg>v:ind.praes.act.3.sg', "le mariage est actuel"),
      ]),
    Q('th-tempus-praeteritum', '2MA 10:30',
      target=('jaciebant', 'v:ind.imperf.act.3.pl'),
      paed=True, fr="Deux d’entre eux, tenant Maccabée au milieu d’eux, le gardaient sain et sauf, entouré de leurs armes ; contre les adversaires, ils lançaient des traits et des foudres, si bien que, frappés de cécité et remplis de trouble, ceux-ci tombaient.",
      dist=[
        ("Deux d’entre eux, tenant Maccabée au milieu d’eux, le gardaient sain et sauf, entouré de leurs armes ; contre les adversaires, ils lancèrent des traits et des foudres, si bien que, frappés de cécité et remplis de trouble, ceux-ci tombaient.", 'jaciebant', 'tempus', 'v:ind.perf.act.3.pl', "une action continue devient un fait ponctuel"),
        ("Deux d’entre eux, tenant Maccabée au milieu d’eux, le gardaient sain et sauf, entouré de leurs armes ; contre les adversaires, ils lanceront des traits et des foudres, si bien que, frappés de cécité et remplis de trouble, ceux-ci tombaient.", 'jaciebant', 'tempus', 'v:ind.fut.act.3.pl', "le combat est annoncé"),
        ("Deux d’entre eux, tenant Maccabée au milieu d’eux, le gardaient sain et sauf, entouré de leurs armes ; contre les adversaires, il lançait des traits et des foudres, si bien que, frappés de cécité et remplis de trouble, ceux-ci tombaient.", 'jaciebant', 'numerus', 'v:ind.imperf.act.3.sg', "un seul lanceur"),
      ],
      note="Livre absent de Segond ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'NEH 3:11',
      target=('ædificavit', 'v:ind.perf.act.3.sg'),
      paed=True, fr="Malkija, fils de Harim, construisit la moitié du quartier, avec Haschub, fils de Pachath-Moab, ainsi que la tour des fours.",
      gloss={'Melchias': 'Malkija', 'Herem': 'Harim', 'Hasub': 'Haschub', 'Phahath': 'Pachath (Pachath-Moab)', 'vici': 'quartier, rue (vicus)'},
      dist=[
        ("Malkija, fils de Harim, construit la moitié du quartier, avec Haschub, fils de Pachath-Moab, ainsi que la tour des fours.", 'ædificavit', 'tempus', 'v:ind.praes.act.3.sg', "la construction est en cours"),
        ("Malkija, fils de Harim, construira la moitié du quartier, avec Haschub, fils de Pachath-Moab, ainsi que la tour des fours.", 'ædificavit', 'tempus', 'v:ind.fut.act.3.sg', "la construction est à venir"),
        ("Malkija, fils de Harim, construisait la moitié du quartier, avec Haschub, fils de Pachath-Moab, ainsi que la tour des fours.", 'ædificavit', 'tempus', 'v:ind.imperf.act.3.sg', "un fait accompli devient un travail qui dure"),
      ],
      note="Segond tourne au passif (« furent réparées par Malkija… ») ; rendu pédagogique de l’actif ædificavit."),
    Q('th-tempus-praeteritum', 'JDG 1:35',
      target=('habitavitque', 'v:ind.perf.act.3.sg'),
      paed=True, fr="Et il habita sur la montagne de Harès, ce qui se traduit « d’argile », à Ajalon et à Schaalbim. Et la main de la maison de Joseph s’appesantit, et il lui devint tributaire.",
      gloss={'Hares': 'Harès (Har-Hérès)', 'Salebim': 'Schaalbim', 'aggravata': 's’appesantir, peser (aggravare)'},
      dist=[
        ("Et il habite sur la montagne de Harès, ce qui se traduit « d’argile », à Ajalon et à Schaalbim. Et la main de la maison de Joseph s’appesantit, et il lui devint tributaire.", 'habitavitque', 'tempus', 'v:ind.praes.act.3.sg', "l’installation est actuelle"),
        ("Et il habitera sur la montagne de Harès, ce qui se traduit « d’argile », à Ajalon et à Schaalbim. Et la main de la maison de Joseph s’appesantit, et il lui devint tributaire.", 'habitavitque', 'tempus', 'v:ind.fut.act.3.sg', "l’installation est à venir"),
        ("Et il habitait sur la montagne de Harès, ce qui se traduit « d’argile », à Ajalon et à Schaalbim. Et la main de la maison de Joseph s’appesantit, et il lui devint tributaire.", 'habitavitque', 'tempus', 'v:ind.imperf.act.3.sg', "un fait accompli devient un séjour qui dure"),
      ],
      note="Segond (« Les Amoréens voulurent rester… ils furent assujettis ») ne suit pas la syntaxe latine ; rendu pédagogique."),
    Q('th-tempus-futurum', 'PHI 3:21',
      target=('reformabit', 'v:ind.fut.act.3.sg'),
      dist=[
        ("qui transforme le corps de notre humiliation, en le rendant semblable au corps de sa gloire, par le pouvoir qu’il a de s’assujettir toutes choses.", 'reformabit', 'tempus', 'v:ind.praes.act.3.sg', "la transformation est actuelle"),
        ("qui a transformé le corps de notre humiliation, en le rendant semblable au corps de sa gloire, par le pouvoir qu’il a de s’assujettir toutes choses.", 'reformabit', 'tempus', 'v:ind.perf.act.3.sg', "la transformation est déjà accomplie"),
        ("qui transformeront le corps de notre humiliation, en le rendant semblable au corps de sa gloire, par le pouvoir qu’il a de s’assujettir toutes choses.", 'reformabit', 'numerus', 'v:ind.fut.act.3.pl', "plusieurs acteurs au lieu du Christ seul"),
      ]),
    Q('th-tempus-praeteritum', 'PSA 67:26',
      target=('Prævenerunt', 'v:ind.perf.act.3.pl'),
      paed=True, fr="Les princes ont pris les devants, joints à ceux qui jouent du psaltérion, au milieu des jeunes filles jouant du tambourin.",
      dist=[
        ("Les princes prennent les devants, joints à ceux qui jouent du psaltérion, au milieu des jeunes filles jouant du tambourin.", 'Prævenerunt', 'tempus', 'v:ind.praes.act.3.pl', "le cortège est décrit au présent"),
        ("Les princes prendront les devants, joints à ceux qui jouent du psaltérion, au milieu des jeunes filles jouant du tambourin.", 'Prævenerunt', 'tempus', 'v:ind.fut.act.3.pl', "le cortège est annoncé"),
        ("Les princes ont pris les devants, joints à ceux qui jouent du psaltérion, au milieu de la jeune fille jouant du tambourin.", 'juvencularum', 'numerus', 'n:gen.pl>n:gen.sg', "une seule jeune fille"),
      ],
      note="Segond 68:26 (« En tête vont les chanteurs ») a le présent et suit l’hébreu ; rendu pédagogique."),
    Q('th-numerus', 'PHI 2:1',
      target=('societas', 'n:nom.sg'),
      dist=[
        ("Si donc il y a quelque consolation en Christ, s’il y a quelque soulagement dans la charité, s’il y a quelques unions d’esprit, s’il y a quelque compassion et quelque miséricorde,", 'societas', 'numerus', 'n:nom.pl', "plusieurs unions"),
        ("Si donc il y a quelques consolations en Christ, s’il y a quelque soulagement dans la charité, s’il y a quelque union d’esprit, s’il y a quelque compassion et quelque miséricorde,", 'consolatio', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs consolations"),
        ("Si donc il y a quelque consolation en Christ, s’il y a quelque soulagement dans la charité, s’il y a quelque union d’esprits, s’il y a quelque compassion et quelque miséricorde,", 'spiritus', 'numerus', 'n:gen.sg>n:gen.pl', "une union entre plusieurs esprits"),
      ]),
    Q('th-tempus-praeteritum', 'EZE 27:24',
      target=('habebant', 'v:ind.imperf.act.3.pl'),
      la='quæ obvolutæ et astrictæ erant funibus: cedros quoque habebant in negotiationibus tuis',
      paed=True, fr="qui étaient enveloppées et liées avec des cordes ; ils avaient aussi des cèdres sur tes marchés",
      dist=[
        ("qui étaient enveloppées et liées avec des cordes ; ils eurent aussi des cèdres sur tes marchés", 'habebant', 'tempus', 'v:ind.perf.act.3.pl', "une possession durable devient un fait ponctuel"),
        ("qui étaient enveloppées et liées avec des cordes ; ils auront aussi des cèdres sur tes marchés", 'habebant', 'tempus', 'v:ind.fut.act.3.pl', "le commerce est annoncé"),
        ("qui étaient enveloppées et liées avec des cordes ; il avait aussi des cèdres sur tes marchés", 'habebant', 'numerus', 'v:ind.imperf.act.3.sg', "un seul marchand"),
      ],
      note="Segond (« En riches étoffes contenues dans des coffres… faits en bois de cèdre ») s’écarte du latin ; rendu pédagogique de la fin du verset."),
    Q('th-numerus', 'ISA 3:20',
      target=('murenulas', 'n:acc.pl'),
      paed=True, fr="et les bandeaux, et les chaînettes des pieds, et les petits colliers, et les flacons de parfum, et les boucles d’oreilles,",
      gloss={'periscelidas': 'chaînettes de pieds, périscélides', 'inaures': 'boucles d’oreilles (inauris)'},
      dist=[
        ("et les bandeaux, et les chaînettes des pieds, et le petit collier, et les flacons de parfum, et les boucles d’oreilles,", 'murenulas', 'numerus', 'n:acc.sg', "un seul collier"),
        ("et les bandeaux, et les chaînettes des pieds, et les petits colliers, et le flacon de parfum, et les boucles d’oreilles,", 'olfactoriola', 'numerus', 'n:acc.pl>n:acc.sg', "un seul flacon"),
        ("et le bandeau, et les chaînettes des pieds, et les petits colliers, et les flacons de parfum, et les boucles d’oreilles,", 'discriminalia', 'numerus', 'n:acc.pl>n:acc.sg', "un seul bandeau"),
      ],
      note="La liste de Segond (diadèmes, ceintures, amulettes) suit l’hébreu et ne correspond pas aux objets latins ; rendu pédagogique."),
    Q('th-numerus', 'LEV 11:30',
      target=('chamæleon', 'n:nom.sg'),
      paed=True, fr="la musaraigne, et le caméléon, et le stellion, et le lézard, et la taupe.",
      gloss={'mygale': 'musaraigne'},
      dist=[
        ("la musaraigne, et les caméléons, et le stellion, et le lézard, et la taupe.", 'chamæleon', 'numerus', 'n:nom.pl', "plusieurs caméléons"),
        ("la musaraigne, et le caméléon, et le stellion, et les lézards, et la taupe.", 'lacerta', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs lézards"),
        ("la musaraigne, et le caméléon, et le stellion, et le lézard, et les taupes.", 'talpa', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs taupes"),
      ],
      note="La liste de Segond (hérisson, grenouille, tortue, limaçon) suit l’hébreu ; rendu pédagogique des animaux latins."),
    Q('th-persona', '2MA 6:19',
      target=('præibat', 'v:ind.imperf.act.3.sg'),
      paed=True, fr="Mais lui, embrassant une mort très glorieuse plutôt qu’une vie odieuse, s’avançait volontairement au supplice.",
      gloss={'voluntarie': 'volontairement'},
      dist=[
        ("Mais moi, embrassant une mort très glorieuse plutôt qu’une vie odieuse, je m’avançais volontairement au supplice.", 'præibat', 'persona', 'v:ind.imperf.act.1.sg', "le narrateur devient le martyr"),
        ("Mais toi, embrassant une mort très glorieuse plutôt qu’une vie odieuse, tu t’avançais volontairement au supplice.", 'præibat', 'persona', 'v:ind.imperf.act.2.sg', "on s’adresse au martyr"),
        ("Mais eux, embrassant une mort très glorieuse plutôt qu’une vie odieuse, s’avançaient volontairement au supplice.", 'præibat', 'numerus', 'v:ind.imperf.act.3.pl', "plusieurs martyrs"),
      ],
      note="Livre absent de Segond ; rendu pédagogique."),
    Q('th-nonfinita', 'HEB 6:6',
      target=('prolapsi', 'v:part.perf.act.nom.pl.m'),
      gloss={'sibimetipsis': 'pour eux-mêmes'},
      dist=[
        ("et qui tombent, soient encore renouvelés et amenés à la repentance, puisqu’ils crucifient pour leur part le Fils de Dieu et l’exposent à l’ignominie.", 'prolapsi', 'tempus', 'v:part.praes.act.nom.pl.m', "la chute est en cours au lieu d’être accomplie"),
        ("et qui est tombé, soit encore renouvelé et amené à la repentance, puisqu’il crucifie pour sa part le Fils de Dieu et l’expose à l’ignominie.", 'prolapsi', 'numerus', 'v:part.perf.act.nom.sg.m', "un seul apostat"),
        ("et qui sont tombés, soient encore renouvelés et amenés à la repentance, puisqu’ils crucifient pour leur part les Fils de Dieu et l’exposent à l’ignominie.", 'Filium', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs Fils de Dieu"),
      ],
      note="Segond rend l’infinitif « renovari » par un subjonctif dépendant du verset 4 ; la cible est le participe."),
    Q('th-tempus-praeteritum', 'EZR 2:2',
      target=('venerunt', 'v:ind.perf.act.3.pl'),
      gloss={'Saraia': 'Seraja', 'Rahelaia': 'Reélaja', 'Mardochai': 'Mardochée', 'Belsan': 'Bilschan', 'Mesphar': 'Mispar', 'Beguai': 'Bigvaï', 'Rehum': 'Rehum', 'Baana': 'Baana'},
      dist=[
        ("Ils partent avec Zorobabel, Josué, Néhémie, Seraja, Reélaja, Mardochée, Bilschan, Mispar, Bigvaï, Rehum, Baana. Nombre des hommes du peuple d’Israël:", 'venerunt', 'tempus', 'v:ind.praes.act.3.pl', "le voyage est en cours"),
        ("Ils partiront avec Zorobabel, Josué, Néhémie, Seraja, Reélaja, Mardochée, Bilschan, Mispar, Bigvaï, Rehum, Baana. Nombre des hommes du peuple d’Israël:", 'venerunt', 'tempus', 'v:ind.fut.act.3.pl', "le voyage est annoncé"),
        ("Il partit avec Zorobabel, Josué, Néhémie, Seraja, Reélaja, Mardochée, Bilschan, Mispar, Bigvaï, Rehum, Baana. Nombre des hommes du peuple d’Israël:", 'venerunt', 'numerus', 'v:ind.perf.act.3.sg', "un seul voyageur"),
      ],
      note="Segond a « partirent » pour venerunt (« vinrent ») ; la morphologie (parfait, 3e pl.) est respectée."),
    Q('th-tempus-praeteritum', 'EZE 21:21',
      target=('interrogavit', 'v:ind.perf.act.3.sg'),
      paed=True, fr_ref='EZE 21:26',
      fr="Car le roi de Babylone s’est arrêté au carrefour, à la tête des deux chemins, cherchant la divination, mêlant les flèches ; il a interrogé les idoles, il a consulté les entrailles.",
      gloss={'Babylonis': 'Babylone'},
      dist=[
        ("Car le roi de Babylone s’est arrêté au carrefour, à la tête des deux chemins, cherchant la divination, mêlant les flèches ; il interrogera les idoles, il a consulté les entrailles.", 'interrogavit', 'tempus', 'v:ind.fut.act.3.sg', "la consultation est annoncée"),
        ("Car le roi de Babylone s’est arrêté au carrefour, à la tête des deux chemins, cherchant la divination, mêlant les flèches ; il interroge les idoles, il a consulté les entrailles.", 'interrogavit', 'tempus', 'v:ind.praes.act.3.sg', "la consultation est en cours"),
        ("Car le roi de Babylone s’est arrêté au carrefour, à la tête des deux chemins, cherchant la divination, mêlant les flèches ; ils ont interrogé les idoles, il a consulté les entrailles.", 'interrogavit', 'numerus', 'v:ind.perf.act.3.pl', "plusieurs consultants"),
      ],
      note="Segond 21:26 a le présent (« se tient… interroge… examine ») pour les parfaits latins ; rendu pédagogique."),
    Q('th-tempus-futurum', 'JER 46:20',
      target=('veniet', 'v:ind.fut.act.3.sg'),
      paed=True, fr="L’Égypte est une génisse élégante et belle ; celui qui aiguillonne viendra du nord vers elle.",
      gloss={'stimulator': 'celui qui aiguillonne, le taon'},
      dist=[
        ("L’Égypte est une génisse élégante et belle ; celui qui aiguillonne vient du nord vers elle.", 'veniet', 'tempus', 'v:ind.praes.act.3.sg', "la venue est actuelle"),
        ("L’Égypte est une génisse élégante et belle ; celui qui aiguillonne est venu du nord vers elle.", 'veniet', 'tempus', 'v:ind.perf.act.3.sg', "la venue est déjà accomplie"),
        ("L’Égypte est une génisse élégante et belle ; celui qui aiguillonne venait du nord vers elle.", 'veniet', 'tempus', 'v:ind.imperf.act.3.sg', "la venue est racontée au passé"),
      ],
      note="Segond a le présent (« vient… il arrive ») pour le futur veniet ; rendu pédagogique."),
    Q('th-numerus', '2CO 6:8',
      target=('seductores', 'n:nom.pl'),
      la='per gloriam, et ignobilitatem, per infamiam, et bonam famam: ut seductores, et veraces',
      fr='au milieu de la gloire et de l’ignominie, au milieu de la mauvaise et de la bonne réputation; étant regardés comme imposteurs, quoique véridiques',
      dist=[
        ("au milieu de la gloire et de l’ignominie, au milieu de la mauvaise et de la bonne réputation; étant regardé comme imposteur, quoique véridique", 'seductores', 'numerus', 'n:nom.sg', "un seul apôtre"),
        ("au milieu des gloires et de l’ignominie, au milieu de la mauvaise et de la bonne réputation; étant regardés comme imposteurs, quoique véridiques", 'gloriam', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs gloires"),
        ("au milieu de la gloire et des ignominies, au milieu de la mauvaise et de la bonne réputation; étant regardés comme imposteurs, quoique véridiques", 'ignobilitatem', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs ignominies"),
      ],
      note="Segond reporte « sicut qui ignoti, et cogniti » au verset 9."),
    Q('th-tempus-praeteritum', 'JOS 15:46',
      target=('vergunt', 'v:ind.praes.act.3.pl'),
      paed=True, fr="Depuis Ékron jusqu’à la mer : tout ce qui regarde vers Asdod et ses villages.",
      dist=[
        ("Depuis Ékron jusqu’à la mer : tout ce qui a regardé vers Asdod et ses villages.", 'vergunt', 'tempus', 'v:ind.perf.act.3.pl', "l’orientation est présentée comme passée"),
        ("Depuis Ékron jusqu’à la mer : tout ce qui regardera vers Asdod et ses villages.", 'vergunt', 'tempus', 'v:ind.fut.act.3.pl', "l’orientation est à venir"),
        ("Depuis Ékron jusqu’à la mer : tout ce qui regarde vers Asdod et son village.", 'viculos', 'numerus', 'n:acc.pl>n:acc.sg', "un seul village"),
      ],
      note="Segond (« et à l’occident, toutes les villes près d’Asdod ») ne rend pas le verbe vergunt ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'JDG 7:23',
      target=('persequebantur', 'v:ind.imperf.act.3.pl'),
      la='Conclamantes autem viri Israël de Nephthali, et Aser, et omni Manasse, persequebantur Madian.',
      paed=True, fr="Les hommes d’Israël, ceux de Nephthali, d’Aser et de tout Manassé, s’appelant à grands cris, poursuivaient Madian.",
      gloss={'Aser': 'Aser', 'Manasse': 'Manassé'},
      dist=[
        ("Les hommes d’Israël, ceux de Nephthali, d’Aser et de tout Manassé, s’appelant à grands cris, poursuivent Madian.", 'persequebantur', 'tempus', 'v:ind.praes.act.3.pl', "la poursuite est actuelle"),
        ("L’homme d’Israël, celui de Nephthali, d’Aser et de tout Manassé, s’appelant à grands cris, poursuivait Madian.", 'persequebantur', 'numerus', 'v:ind.imperf.act.3.sg', "un seul poursuivant"),
        ("Les hommes d’Israël, ceux de Nephthali, d’Aser et de tout Manassé, s’appelant à grands cris, poursuivront Madian.", 'persequebantur', 'tempus', 'v:ind.fut.act.3.pl', "la poursuite est annoncée"),
      ],
      note="Segond a le passé simple « poursuivirent » pour l’imparfait persequebantur et ne rend pas « conclamantes » ; rendu pédagogique."),
    Q('th-tempus-futurum', 'JOB 40:19',
      target=('capiet', 'v:ind.fut.act.3.sg'),
      paed=True, fr="Sous ses yeux, comme avec un hameçon, il le prendra, et avec des pieux il lui percera les narines.",
      dist=[
        ("Sous ses yeux, comme avec un hameçon, il le prend, et avec des pieux il lui percera les narines.", 'capiet', 'tempus', 'v:ind.praes.act.3.sg', "la capture est actuelle"),
        ("Sous ses yeux, comme avec un hameçon, il l’a pris, et avec des pieux il lui percera les narines.", 'capiet', 'tempus', 'v:ind.perf.act.3.sg', "la capture est déjà faite"),
        ("Sous ses yeux, comme avec un hameçon, ils le prendront, et avec des pieux il lui percera les narines.", 'capiet', 'numerus', 'v:ind.fut.act.3.pl', "plusieurs chasseurs"),
      ],
      note="Segond (« Est-ce à force ouverte qu’on pourra le saisir ? ») tourne en question impersonnelle ; rendu pédagogique."),
    Q('th-modus-subiunctivus', '1CO 14:24',
      target=('intret', 'v:subj.praes.act.3.sg'),
      dist=[
        ("Mais si tous prophétisent, et il survient quelque non-croyant ou un homme du peuple, il est convaincu par tous, il est jugé par tous,", 'intret', 'modus', 'v:ind.praes.act.3.sg', "l’hypothèse devient un fait"),
        ("Mais si tous prophétisent, et qu’il survienne des non-croyants ou des hommes du peuple, il est convaincu par tous, il est jugé par tous,", 'intret', 'numerus', 'v:subj.praes.act.3.pl', "plusieurs visiteurs"),
        ("Mais si tous prophétisent, et qu’il survînt quelque non-croyant ou un homme du peuple, il est convaincu par tous, il est jugé par tous,", 'intret', 'tempus', 'v:subj.imperf.act.3.sg', "l’hypothèse est rejetée dans le passé"),
      ]),
    Q('th-tempus-praeteritum', '2SA 21:19',
      target=('percussit', 'v:ind.perf.act.3.sg'),
      gloss={'Gob': 'Gob', 'Adeodatus': 'Elchanan', 'Saltus': 'Jaaré (« forêt »)', 'polymitarius': 'brodeur (Oreguim)', 'Gethæum': 'de Gath'},
      dist=[
        ("Il y eut encore une bataille à Gob avec les Philistins. Et Elchanan, fils de Jaaré-Oreguim, de Bethléhem, tue Goliath de Gath, qui avait une lance dont le bois était comme une ensouple de tisserand.", 'percussit', 'tempus', 'v:ind.praes.act.3.sg', "le combat est raconté au présent"),
        ("Il y eut encore une bataille à Gob avec les Philistins. Et Elchanan, fils de Jaaré-Oreguim, de Bethléhem, tuera Goliath de Gath, qui avait une lance dont le bois était comme une ensouple de tisserand.", 'percussit', 'tempus', 'v:ind.fut.act.3.sg', "le combat est annoncé"),
        ("Il y avait encore une bataille à Gob avec les Philistins. Et Elchanan, fils de Jaaré-Oreguim, de Bethléhem, tua Goliath de Gath, qui avait une lance dont le bois était comme une ensouple de tisserand.", 'fuit', 'tempus', 'v:ind.perf.act.3.sg>v:ind.imperf.act.3.sg', "un fait ponctuel devient une situation qui dure"),
      ],
      note="Segond a « tua » pour percussit (« frappa ») et « encore » pour tertium."),
    Q('th-numerus', 'REV 19:8',
      target=('justificationes', 'n:nom.pl'),
      dist=[
        ("et il lui a été donné de se revêtir d’un fin lin, éclatant, pur. Car le fin lin, c’est l’œuvre juste des saints.", 'justificationes', 'numerus', 'n:nom.sg', "une seule œuvre juste"),
        ("et il leur a été donné de se revêtir d’un fin lin, éclatant, pur. Car le fin lin, ce sont les œuvres justes des saints.", 'illi', 'numerus', 'a:dat.sg.f>a:dat.pl.f', "plusieurs bénéficiaires"),
        ("et il lui a été donné de se revêtir d’un fin lin, éclatant, pur. Car le fin lin, ce sont les œuvres justes du saint.", 'sanctorum', 'numerus', 'a:gen.pl.m>a:gen.sg.m', "un seul saint"),
      ]),
    Q('th-persona', 'JDG 9:31',
      target=('misit', 'v:ind.perf.act.3.sg'),
      gloss={'Gaal': 'Gaal'},
      dist=[
        ("J’envoyai secrètement des messagers à Abimélec, pour lui dire: Voici, Gaal, fils d’Ébed, et ses frères, sont venus à Sichem, et ils soulèvent la ville contre toi.", 'misit', 'persona', 'v:ind.perf.act.1.sg', "le narrateur devient l’envoyeur"),
        ("Tu envoyas secrètement des messagers à Abimélec, pour lui dire: Voici, Gaal, fils d’Ébed, et ses frères, sont venus à Sichem, et ils soulèvent la ville contre toi.", 'misit', 'persona', 'v:ind.perf.act.2.sg', "on s’adresse à l’envoyeur"),
        ("Ils envoyèrent secrètement des messagers à Abimélec, pour lui dire: Voici, Gaal, fils d’Ébed, et ses frères, sont venus à Sichem, et ils soulèvent la ville contre toi.", 'misit', 'numerus', 'v:ind.perf.act.3.pl', "plusieurs envoyeurs"),
      ],
      note="Segond a « sont venus… ils soulèvent » (pluriel) pour venit… oppugnat ; la cible est misit."),
    Q('th-modus-subiunctivus', 'DEU 18:10',
      target=('lustret', 'v:subj.praes.act.3.sg'),
      gloss={'ariolos': 'devins'},
      dist=[
        ("Qu’on ne trouve chez toi personne qui fait passer son fils ou sa fille par le feu, personne qui exerce le métier de devin, d’astrologue, d’augure, de magicien,", 'lustret', 'modus', 'v:ind.praes.act.3.sg', "une pratique redoutée devient un fait constaté"),
        ("Qu’on ne trouve chez toi personne qui fît passer son fils ou sa fille par le feu, personne qui exerce le métier de devin, d’astrologue, d’augure, de magicien,", 'lustret', 'tempus', 'v:subj.imperf.act.3.sg', "l’interdiction est rejetée dans le passé"),
        ("Qu’on ne trouve chez toi personne qui fasse passer ses fils ou sa fille par le feu, personne qui exerce le métier de devin, d’astrologue, d’augure, de magicien,", 'filium', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs fils"),
      ],
      note="Segond rend le passif « inveniatur » par « qu’on ne trouve » ; la cible est lustret."),
    Q('th-vox', 'PRO 3:15',
      target=('desiderantur', 'v:ind.praes.pass.3.pl'),
      paed=True, fr="Elle est plus précieuse que toutes les richesses, et tout ce qui est désiré ne peut lui être comparé.",
      dist=[
        ("Elle est plus précieuse que toutes les richesses, et tout ce qui désire ne peut lui être comparé.", 'desiderantur', 'vox', 'v:ind.praes.act.3.pl', "les choses désirent au lieu d’être désirées"),
        ("Elle est plus précieuse que toutes les richesses, et tout ce qui sera désiré ne peut lui être comparé.", 'desiderantur', 'tempus', 'v:ind.fut.pass.3.pl', "le désir est à venir"),
        ("Elles sont plus précieuses que toutes les richesses, et tout ce qui est désiré ne peut leur être comparé.", 'Pretiosior', 'numerus', 'a:nom.sg.f.comp>a:nom.pl.f.comp', "plusieurs sagesses"),
      ],
      note="Segond (« plus précieuse que les perles… tous les objets de prix ») suit l’hébreu et ne rend pas desiderantur ; rendu pédagogique."),
]
