# sheet_001 → batch_001
# skipped: (none)
ITEMS = [
    Q('th-tempus-praeteritum', 'EST 15:9',
      target=('stetit', 'v:ind.perf.act.3.sg'),
      paed=True, fr="Ayant donc franchi toutes les portes l’une après l’autre, elle se tint devant le roi, là où il siégeait sur le trône de son royaume, revêtu des vêtements royaux, étincelant d’or et de pierres précieuses ; et il était terrible à voir.",
      lemma={'aspectu': 'aspectus'},
      dist=[
        ("Ayant donc franchi toutes les portes l’une après l’autre, elle se tient devant le roi, là où il siégeait sur le trône de son royaume, revêtu des vêtements royaux, étincelant d’or et de pierres précieuses ; et il était terrible à voir.", 'stetit', 'tempus', 'v:ind.praes.act.3.sg', "la scène est présentée comme actuelle"),
        ("Ayant donc franchi toutes les portes l’une après l’autre, elles se tinrent devant le roi, là où il siégeait sur le trône de son royaume, revêtu des vêtements royaux, étincelant d’or et de pierres précieuses ; et il était terrible à voir.", 'stetit', 'numerus', 'v:ind.perf.act.3.pl', "plusieurs femmes se présentent au lieu d’Esther seule"),
        ("Ayant donc franchi toutes les portes l’une après l’autre, elle se tint devant le roi, là où il siégeait sur le trône de son royaume, revêtu des vêtements royaux, étincelant d’or et de pierres précieuses ; et il est terrible à voir.", 'eratque', 'tempus', 'v:ind.imperf.act.3.sg>v:ind.praes.act.3.sg', "l’aspect terrible du roi est présenté comme actuel"),
      ],
      note="Segond n’a pas ce verset (addition grecque d’Esther) ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'LAM 2:3',
      target=('Confregit', 'v:ind.perf.act.3.sg'),
      gloss={'Ghimel': 'guimel (lettre hébraïque)'},
      dist=[
        ("Il abat, dans son ardente colère, toute la force d’Israël; Il a retiré sa droite en présence de l’ennemi; Il a allumé dans Jacob des flammes de feu, Qui dévorent de tous côtés.", 'Confregit', 'tempus', 'v:ind.praes.act.3.sg', "la destruction est en cours"),
        ("Il abattra, dans son ardente colère, toute la force d’Israël; Il a retiré sa droite en présence de l’ennemi; Il a allumé dans Jacob des flammes de feu, Qui dévorent de tous côtés.", 'Confregit', 'tempus', 'v:ind.fut.act.3.sg', "la destruction est annoncée au lieu d’être racontée"),
        ("Il a, dans son ardente colère, abattu toute la force d’Israël; Il a retiré sa droite en présence des ennemis; Il a allumé dans Jacob des flammes de feu, Qui dévorent de tous côtés.", 'inimici', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs ennemis"),
      ],
      note="Segond ne rend pas la lettre hébraïque Ghimel ; « cornu » est rendu par « la force »."),
    Q('th-tempus-futurum', 'JDG 3:22',
      target=('percusserat', 'v:ind.plusq.act.3.sg'),
      la='Nec eduxit gladium, sed ita ut percusserat, reliquit in corpore',
      paed=True, fr="Et il ne retira pas l’épée, mais il la laissa dans le corps telle qu’il l’avait enfoncée",
      dist=[
        ("Et il ne retira pas l’épée, mais il la laissa dans le corps telle qu’il l’enfonça", 'percusserat', 'tempus', 'v:ind.perf.act.3.sg', "le coup n’est plus antérieur à l’abandon de l’arme"),
        ("Et il ne retire pas l’épée, mais il la laissa dans le corps telle qu’il l’avait enfoncée", 'eduxit', 'tempus', 'v:ind.perf.act.3.sg>v:ind.praes.act.3.sg', "le geste est présenté comme actuel"),
        ("Et il ne retira pas l’épée, mais ils la laissèrent dans le corps telle qu’il l’avait enfoncée", 'reliquit', 'numerus', 'v:ind.perf.act.3.sg>v:ind.perf.act.3.pl', "plusieurs meurtriers au lieu d’Éhud seul"),
      ],
      note="Segond résume (« il ne retira pas du ventre l’épée, qui sortit par derrière ») ; rendu pédagogique de la proposition."),
    Q('th-tempus-futurum', 'LEV 23:13',
      target=('offerentur', 'v:ind.fut.pass.3.pl'),
      paed=True, fr="Et des libations seront offertes avec lui : deux dixièmes de fleur de farine pétrie à l’huile, en offrande consumée par le feu pour l’Éternel, d’une odeur très agréable ; et aussi des libations de vin, un quart de hin.",
      dist=[
        ("Et des libations sont offertes avec lui : deux dixièmes de fleur de farine pétrie à l’huile, en offrande consumée par le feu pour l’Éternel, d’une odeur très agréable ; et aussi des libations de vin, un quart de hin.", 'offerentur', 'tempus', 'v:ind.praes.pass.3.pl', "la prescription est présentée comme un usage actuel"),
        ("Et des libations étaient offertes avec lui : deux dixièmes de fleur de farine pétrie à l’huile, en offrande consumée par le feu pour l’Éternel, d’une odeur très agréable ; et aussi des libations de vin, un quart de hin.", 'offerentur', 'tempus', 'v:ind.imperf.pass.3.pl', "une prescription devient un récit du passé"),
        ("Et une libation sera offerte avec lui : deux dixièmes de fleur de farine pétrie à l’huile, en offrande consumée par le feu pour l’Éternel, d’une odeur très agréable ; et aussi des libations de vin, un quart de hin.", 'offerentur', 'numerus', 'v:ind.fut.pass.3.sg', "une seule libation"),
      ],
      note="Segond a l’actif « vous y joindrez une offrande » pour le passif offerentur ; rendu pédagogique."),
    Q('th-tempus-praeteritum', '2CH 3:4',
      target=('deauravit', 'v:ind.perf.act.3.sg'),
      lemma={'mensuram': 'mensura', 'cubitorum': 'cubitum'},
      gloss={'mensuram': 'mesure', 'cubitorum': 'coudée'},
      dist=[
        ("Le portique sur le devant avait vingt coudées de longueur, répondant à la largeur de la maison, et cent vingt de hauteur; Salomon le couvre intérieurement d’or pur.", 'deauravit', 'tempus', 'v:ind.praes.act.3.sg', "le revêtement d’or est présenté comme en cours"),
        ("Le portique sur le devant avait vingt coudées de longueur, répondant à la largeur de la maison, et cent vingt de hauteur; Salomon le couvrira intérieurement d’or pur.", 'deauravit', 'tempus', 'v:ind.fut.act.3.sg', "le revêtement d’or est annoncé"),
        ("Le portique sur le devant avait vingt coudées de longueur, répondant à la largeur de la maison, et cent vingt de hauteur; Salomon le couvrait intérieurement d’or pur.", 'deauravit', 'tempus', 'v:ind.imperf.act.3.sg', "un fait accompli devient une action qui dure"),
      ],
      note="Segond explicite le sujet « Salomon » ; la cible est deauravit."),
    Q('th-tempus-praeteritum', 'JDG 19:8',
      target=('Comederunt', 'v:ind.perf.act.3.pl'),
      paed=True, fr="Le matin venu, le Lévite se préparait à partir. Son beau-père lui dit de nouveau : Je t’en prie, prends un peu de nourriture, et, ayant repris des forces, attends que le jour grandisse ; ensuite tu partiras. Ils mangèrent donc ensemble.",
      dist=[
        ("Le matin venu, le Lévite se préparait à partir. Son beau-père lui dit de nouveau : Je t’en prie, prends un peu de nourriture, et, ayant repris des forces, attends que le jour grandisse ; ensuite tu partiras. Ils mangent donc ensemble.", 'Comederunt', 'tempus', 'v:ind.perf.act.3.pl>v:ind.praes.act.3.pl', "le repas est présenté comme actuel"),
        ("Le matin venu, le Lévite se préparait à partir. Son beau-père lui dit de nouveau : Je t’en prie, prends un peu de nourriture, et, ayant repris des forces, attends que le jour grandisse ; ensuite tu partiras. Ils mangeront donc ensemble.", 'Comederunt', 'tempus', 'v:ind.fut.act.3.pl', "le repas est annoncé au lieu d’être raconté"),
        ("Le matin venu, le Lévite se prépara à partir. Son beau-père lui dit de nouveau : Je t’en prie, prends un peu de nourriture, et, ayant repris des forces, attends que le jour grandisse ; ensuite tu partiras. Ils mangèrent donc ensemble.", 'parabat', 'tempus', 'v:ind.imperf.act.3.sg>v:ind.perf.act.3.sg', "un départ en préparation devient un départ décidé"),
      ],
      note="Segond suit l’hébreu (« Le cinquième jour… restez jusqu’au déclin du jour ») et ne rend pas le latin ; rendu pédagogique."),
    Q('th-modus-imperativus', 'JDG 21:21',
      target=('rapite', 'v:imp.praes.act.2.pl'),
      paed=True, fr="Et lorsque vous verrez les filles de Silo sortir, selon la coutume, pour mener les danses, sortez soudain des vignes, enlevez chacun une femme parmi elles, et allez au pays de Benjamin.",
      dist=[
        ("Et lorsque vous verrez les filles de Silo sortir, selon la coutume, pour mener les danses, sortez soudain des vignes, vous enlevez chacun une femme parmi elles, et allez au pays de Benjamin.", 'rapite', 'modus', 'v:ind.praes.act.2.pl', "un ordre devient un constat"),
        ("Et lorsque vous verrez les filles de Silo sortir, selon la coutume, pour mener les danses, sors soudain des vignes, enlevez chacun une femme parmi elles, et allez au pays de Benjamin.", 'exite', 'numerus', 'v:imp.praes.act.2.pl>v:imp.praes.act.2.sg', "l’ordre de sortir s’adresse à un seul homme"),
        ("Et lorsque vous verrez les filles de Silo sortir, selon la coutume, pour mener les danses, sortez soudain des vignes, enlevez chacun une femme parmi elles, et vous irez au pays de Benjamin.", 'pergite', 'modus', 'v:imp.praes.act.2.pl>v:ind.fut.act.2.pl', "l’ordre de partir devient une simple prédiction"),
      ],
      note="Segond rend les impératifs par des futurs (« vous sortirez… vous enlèverez… ») ; rendu pédagogique."),
    Q('th-tempus-futurum', 'JER 18:14',
      target=('deficiet', 'v:ind.fut.act.3.sg'),
      paed=True, fr="La neige du Liban manquera-t-elle au rocher des champs ? Ou les eaux jaillissantes, fraîches et courantes, peuvent-elles être arrachées ?",
      dist=[
        ("La neige du Liban manque-t-elle au rocher des champs ? Ou les eaux jaillissantes, fraîches et courantes, peuvent-elles être arrachées ?", 'deficiet', 'tempus', 'v:ind.praes.act.3.sg', "la question porte sur le présent"),
        ("La neige du Liban a-t-elle manqué au rocher des champs ? Ou les eaux jaillissantes, fraîches et courantes, peuvent-elles être arrachées ?", 'deficiet', 'tempus', 'v:ind.perf.act.3.sg', "la question porte sur le passé"),
        ("La neige du Liban manquera-t-elle au rocher des champs ? Ou l’eau jaillissante, fraîche et courante, peut-elle être arrachée ?", 'possunt', 'numerus', 'v:ind.praes.act.3.pl>v:ind.praes.act.3.sg', "une seule eau au lieu des eaux"),
      ],
      note="Segond a le présent « abandonne-t-elle » pour le futur deficiet ; rendu pédagogique."),
    Q('th-tempus-futurum', '2CH 25:13',
      target=('remiserat', 'v:ind.plusq.act.3.sg'),
      paed=True, fr="Mais cette troupe qu’Amatsia avait renvoyée pour qu’elle n’allât pas avec lui au combat se répandit dans les villes de Juda, depuis Samarie jusqu’à Beth-Horon, et, après avoir tué trois mille hommes, enleva un grand butin.",
      dist=[
        ("Mais cette troupe qu’Amatsia renvoya pour qu’elle n’allât pas avec lui au combat se répandit dans les villes de Juda, depuis Samarie jusqu’à Beth-Horon, et, après avoir tué trois mille hommes, enleva un grand butin.", 'remiserat', 'tempus', 'v:ind.perf.act.3.sg', "le renvoi n’est plus antérieur au récit"),
        ("Mais cette troupe qu’Amatsia avait renvoyée pour qu’elle n’aille pas avec lui au combat se répandit dans les villes de Juda, depuis Samarie jusqu’à Beth-Horon, et, après avoir tué trois mille hommes, enleva un grand butin.", 'iret', 'tempus', 'v:subj.imperf.act.3.sg>v:subj.praes.act.3.sg', "la défense d’aller au combat est actuelle"),
        ("Mais cette troupe qu’Amatsia avait renvoyée pour qu’elle n’allât pas avec lui au combat se répandit dans la ville de Juda, depuis Samarie jusqu’à Beth-Horon, et, après avoir tué trois mille hommes, enleva un grand butin.", 'civitatibus', 'numerus', 'n:abl.pl>n:abl.sg', "une seule ville"),
      ],
      note="Segond met la troupe au pluriel (« les gens de la troupe… firent… ») ; rendu pédagogique."),
    Q('th-tempus-futurum', 'EXO 21:2',
      target=('serviet', 'v:ind.fut.act.3.sg'),
      gloss={'servum': 'esclave, serviteur'},
      dist=[
        ("Si tu achètes un esclave hébreu, il sert six années; mais la septième, il sortira libre, sans rien payer.", 'serviet', 'tempus', 'v:ind.praes.act.3.sg', "le service est présenté comme actuel"),
        ("Si tu achètes un esclave hébreu, tu serviras six années; mais la septième, il sortira libre, sans rien payer.", 'serviet', 'persona', 'v:ind.fut.act.2.sg', "c’est l’acheteur qui sert"),
        ("Si tu achètes un esclave hébreu, il servira six années; mais la septième, ils sortiront libres, sans rien payer.", 'egredietur', 'numerus', 'v:ind.fut.act.3.sg>v:ind.fut.act.3.pl', "plusieurs esclaves sortent"),
      ]),
    Q('th-numerus', 'JOS 9:4',
      target=('tulerunt', 'v:ind.perf.act.3.pl'),
      paed=True, fr="et, usant de ruse, ils prirent pour eux des vivres, mettant de vieux sacs sur leurs ânes, et des outres à vin déchirées et recousues,",
      dist=[
        ("et, usant de ruse, il prit pour lui des vivres, mettant de vieux sacs sur ses ânes, et des outres à vin déchirées et recousues,", 'tulerunt', 'numerus', 'v:ind.perf.act.3.sg', "un seul homme au lieu des Gabaonites"),
        ("et, usant de ruse, ils prirent pour eux des vivres, mettant de vieux sacs sur leur âne, et des outres à vin déchirées et recousues,", 'asinis', 'numerus', 'n:abl.pl>n:abl.sg', "un seul âne"),
        ("et, usant de ruse, ils prirent pour eux des vivres, mettant un vieux sac sur leurs ânes, et des outres à vin déchirées et recousues,", 'saccos', 'numerus', 'n:acc.pl>n:acc.sg', "un seul sac"),
      ],
      note="Segond (« se mirent en route avec des provisions de voyage ») ne rend pas « tulerunt sibi cibaria » ; rendu pédagogique."),
    Q('th-tempus-futurum', 'LEV 3:2',
      target=('Ponetque', 'v:ind.fut.act.3.sg'),
      gloss={'altaris': 'autel'},
      lemma={'introitu': 'introitus', 'circuitum': 'circuitus'},
      dist=[
        ("Il pose sa main sur la tête de la victime, qu’il égorgera à l’entrée de la tente d’assignation; et les sacrificateurs, fils d’Aaron, répandront le sang sur l’autel tout autour.", 'Ponetque', 'tempus', 'v:ind.praes.act.3.sg', "le geste est présenté comme actuel"),
        ("Ils poseront leur main sur la tête de la victime, qu’il égorgera à l’entrée de la tente d’assignation; et les sacrificateurs, fils d’Aaron, répandront le sang sur l’autel tout autour.", 'Ponetque', 'numerus', 'v:ind.fut.act.3.pl', "plusieurs offrants au lieu d’un seul"),
        ("Il posera sa main sur la tête de la victime, qu’il égorgera à l’entrée de la tente d’assignation; et le sacrificateur, fils d’Aaron, répandra le sang sur l’autel tout autour.", 'fundentque', 'numerus', 'v:ind.fut.act.3.pl>v:ind.fut.act.3.sg', "un seul prêtre répand le sang"),
      ],
      note="Segond rend le passif « immolabitur » par « qu’il égorgera » ; la cible est Ponetque."),
    Q('th-persona', 'EST 16:15',
      target=('reperimus', 'v:ind.perf.act.1.pl'),
      paed=True, fr="Mais nous, nous avons trouvé que les Juifs, voués à la mort par le pire des mortels, n’étaient coupables d’aucune faute, mais qu’au contraire ils se servent de lois justes,",
      dist=[
        ("Mais eux, ils ont trouvé que les Juifs, voués à la mort par le pire des mortels, n’étaient coupables d’aucune faute, mais qu’au contraire ils se servent de lois justes,", 'reperimus', 'persona', 'v:ind.perf.act.3.pl', "ce n’est plus le roi qui parle"),
        ("Mais moi, j’ai trouvé que les Juifs, voués à la mort par le pire des mortels, n’étaient coupables d’aucune faute, mais qu’au contraire ils se servent de lois justes,", 'reperimus', 'numerus', 'v:ind.perf.act.1.sg', "le roi parle seul, sans le pluriel de majesté"),
        ("Mais nous, nous avons trouvé que les Juifs, voués à la mort par le pire des mortels, n’étaient coupables d’aucune faute, mais qu’au contraire ils se servent d’une loi juste,", 'legibus', 'numerus', 'n:abl.pl>n:abl.sg', "une seule loi"),
      ],
      note="Segond n’a pas ce verset (addition grecque d’Esther) ; rendu pédagogique."),
    Q('th-tempus-praeteritum', '2KI 20:11',
      target=('Invocavit', 'v:ind.perf.act.3.sg'),
      dist=[
        ("Alors Ésaïe, le prophète, invoque l’Éternel, qui fit reculer l’ombre de dix degrés sur les degrés d’Achaz, où elle était descendue.", 'Invocavit', 'tempus', 'v:ind.praes.act.3.sg', "la prière est présentée comme actuelle"),
        ("Alors Ésaïe, le prophète, invoquera l’Éternel, qui fit reculer l’ombre de dix degrés sur les degrés d’Achaz, où elle était descendue.", 'Invocavit', 'tempus', 'v:ind.fut.act.3.sg', "la prière est annoncée au lieu d’être racontée"),
        ("Alors Ésaïe, le prophète, invoqua l’Éternel, qui fit reculer l’ombre de dix degrés sur les degrés d’Achaz, où elle descendit.", 'descenderat', 'tempus', 'v:ind.plusq.act.3.sg>v:ind.perf.act.3.sg', "la descente de l’ombre n’est plus antérieure au recul"),
      ],
      note="Segond rend « reduxit » par la relative « qui fit reculer » ; la cible est Invocavit."),
    Q('th-tempus-praeteritum', '2CH 17:11',
      target=('deferebant', 'v:ind.imperf.act.3.pl'),
      paed=True, fr="Les Philistins aussi apportaient des présents à Josaphat, et un tribut d’argent ; les Arabes aussi lui amenaient du bétail : sept mille sept cents béliers et autant de boucs.",
      dist=[
        ("Les Philistins aussi apportèrent des présents à Josaphat, et un tribut d’argent ; les Arabes aussi lui amenaient du bétail : sept mille sept cents béliers et autant de boucs.", 'deferebant', 'tempus', 'v:ind.perf.act.3.pl', "une pratique habituelle devient un fait ponctuel"),
        ("Les Philistins aussi apportent des présents à Josaphat, et un tribut d’argent ; les Arabes aussi lui amenaient du bétail : sept mille sept cents béliers et autant de boucs.", 'deferebant', 'tempus', 'v:ind.praes.act.3.pl', "les présents sont apportés maintenant"),
        ("Les Philistins aussi apportaient des présents à Josaphat, et un tribut d’argent ; l’Arabe aussi lui amenait du bétail : sept mille sept cents béliers et autant de boucs.", 'adducebant', 'numerus', 'v:ind.imperf.act.3.pl>v:ind.imperf.act.3.sg', "un seul Arabe"),
      ],
      note="Segond a le passé simple « apportèrent… amenèrent » pour les imparfaits latins ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'JOS 20:8',
      target=('statuerunt', 'v:ind.perf.act.3.pl'),
      gloss={'Bosor': 'Betser', 'Ramoth': 'Ramoth', 'Gad': 'Gad', 'Basan': 'Basan', 'Manasse': 'Manassé'},
      dist=[
        ("Et de l’autre côté du Jourdain, à l’orient de Jéricho, ils choisissent Betser, dans le désert, dans la plaine, dans la tribu de Ruben; Ramoth, en Galaad, dans la tribu de Gad; et Golan, en Basan, dans la tribu de Manassé.", 'statuerunt', 'tempus', 'v:ind.praes.act.3.pl', "le choix des villes est présenté comme actuel"),
        ("Et de l’autre côté du Jourdain, à l’orient de Jéricho, ils choisiront Betser, dans le désert, dans la plaine, dans la tribu de Ruben; Ramoth, en Galaad, dans la tribu de Gad; et Golan, en Basan, dans la tribu de Manassé.", 'statuerunt', 'tempus', 'v:ind.fut.act.3.pl', "le choix des villes est annoncé"),
        ("Et de l’autre côté du Jourdain, à l’orient de Jéricho, il choisit Betser, dans le désert, dans la plaine, dans la tribu de Ruben; Ramoth, en Galaad, dans la tribu de Gad; et Golan, en Basan, dans la tribu de Manassé.", 'statuerunt', 'numerus', 'v:ind.perf.act.3.sg', "un seul homme choisit au lieu du peuple"),
      ],
      note="Segond a « choisirent » pour statuerunt (« établirent »)."),
    Q('th-tempus-futurum', 'EZE 26:10',
      target=('operiet', 'v:ind.fut.act.3.sg'),
      lemma={'sonitu': 'sonitus', 'introitum': 'introitus'},
      dist=[
        ("La multitude de ses chevaux te couvre de poussière; tes murs trembleront au bruit des cavaliers, des roues et des chars, lorsqu’il entrera dans tes portes comme on entre dans une ville conquise.", 'operiet', 'tempus', 'v:ind.praes.act.3.sg', "la poussière couvre la ville dès maintenant"),
        ("La multitude de ses chevaux te couvrira de poussière; ton mur tremblera au bruit des cavaliers, des roues et des chars, lorsqu’il entrera dans tes portes comme on entre dans une ville conquise.", 'movebuntur', 'numerus', 'v:ind.fut.pass.3.pl>v:ind.fut.pass.3.sg', "un seul mur"),
        ("La multitude de ses chevaux te couvrira de poussière; tes murs tremblent au bruit des cavaliers, des roues et des chars, lorsqu’il entrera dans tes portes comme on entre dans une ville conquise.", 'movebuntur', 'tempus', 'v:ind.fut.pass.3.pl>v:ind.praes.pass.3.pl', "le tremblement des murs est actuel"),
      ],
      note="Segond fait de « la multitude de ses chevaux » le sujet (latin : « pulvis eorum ») ; le verbe garde le futur."),
    Q('th-modus-subiunctivus', 'MAT 21:19',
      target=('nascatur', 'v:subj.praes.act.3.sg'),
      dist=[
        ("Voyant un figuier sur le chemin, il s’en approcha; mais il n’y trouva que des feuilles, et il lui dit: Jamais fruit ne naît de toi! Et à l’instant le figuier sécha.", 'nascatur', 'modus', 'v:ind.praes.act.3.sg', "la malédiction devient un constat"),
        ("Voyant un figuier sur le chemin, il s’en approcha; mais il n’y trouva que des feuilles, et il lui dit: Que jamais fruits ne naissent de toi! Et à l’instant le figuier sécha.", 'nascatur', 'numerus', 'v:subj.praes.act.3.pl', "plusieurs fruits"),
        ("Voyant un figuier sur le chemin, il s’en approcha; mais il n’y trouve que des feuilles, et il lui dit: Que jamais fruit ne naisse de toi! Et à l’instant le figuier sécha.", 'invenit', 'tempus', 'v:ind.perf.act.3.sg>v:ind.praes.act.3.sg', "la découverte des feuilles est actuelle"),
      ]),
    Q('th-persona', 'JOB 1:19',
      target=('effugi', 'v:ind.perf.act.1.sg'),
      lemma={'ventus': 'uentus', 'deserti': 'desertum'},
      gloss={'ventus': 'vent', 'deserti': 'désert'},
      dist=[
        ("et voici, un grand vent est venu de l’autre côté du désert, et a frappé contre les quatre coins de la maison; elle s’est écroulée sur les jeunes gens, et ils sont morts. Et il s’est échappé lui seul, pour t’en apporter la nouvelle.", 'effugi', 'persona', 'v:ind.perf.act.3.sg', "ce n’est plus le messager qui a survécu"),
        ("et voici, un grand vent est venu de l’autre côté du désert, et a frappé contre les quatre coins de la maison; elle s’est écroulée sur les jeunes gens, et ils sont morts. Et nous nous sommes échappés nous seuls, pour t’en apporter la nouvelle.", 'effugi', 'numerus', 'v:ind.perf.act.1.pl', "plusieurs survivants"),
        ("et voici, un grand vent est venu de l’autre côté du désert, et a frappé contre les quatre coins des maisons; elle s’est écroulée sur les jeunes gens, et ils sont morts. Et je me suis échappé moi seul, pour t’en apporter la nouvelle.", 'domus', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs maisons"),
      ],
      note="Segond rend « ut nuntiarem tibi » par un infinitif ; la cible est effugi."),
    Q('th-modus-subiunctivus', 'DAN 5:15',
      target=('legerent', 'v:subj.imperf.act.3.pl'),
      lemma={'scripturam': 'scriptura', 'sensum': 'sensus'},
      gloss={'scripturam': 'écriture, écrit'},
      dist=[
        ("On vient d’amener devant moi les sages et les astrologues, afin qu’ils lisent cette écriture et m’en donnassent l’explication; mais ils n’ont pas pu donner l’explication des mots.", 'legerent', 'tempus', 'v:subj.praes.act.3.pl', "le but de la convocation est actuel"),
        ("On vient d’amener devant moi les sages et les astrologues, afin qu’il lût cette écriture et m’en donnassent l’explication; mais ils n’ont pas pu donner l’explication des mots.", 'legerent', 'numerus', 'v:subj.imperf.act.3.sg', "un seul lecteur"),
        ("On vient d’amener devant moi les sages et les astrologues, afin qu’ils lussent cette écriture et m’en donnassent l’explication; mais ils ne peuvent pas donner l’explication des mots.", 'nequiverunt', 'tempus', 'v:ind.perf.act.3.pl>v:ind.praes.act.3.pl', "l’échec des sages est actuel"),
      ],
      note="Segond rend « introgressi sunt » par « on vient d’amener » ; la cible est legerent."),
    Q('th-tempus-praeteritum', 'EXO 15:15',
      target=('obriguerunt', 'v:ind.perf.act.3.pl'),
      paed=True, fr="Alors les princes d’Édom furent troublés ; un tremblement saisit les vaillants de Moab ; tous les habitants de Canaan se figèrent.",
      lemma={'tremor': 'tremor'},
      dist=[
        ("Alors les princes d’Édom furent troublés ; un tremblement saisit les vaillants de Moab ; tous les habitants de Canaan se figent.", 'obriguerunt', 'tempus', 'v:ind.praes.act.3.pl', "la frayeur est présentée comme actuelle"),
        ("Alors les princes d’Édom furent troublés ; un tremblement saisit les vaillants de Moab ; tous les habitants de Canaan se figeront.", 'obriguerunt', 'tempus', 'v:ind.fut.act.3.pl', "la frayeur est annoncée"),
        ("Alors le prince d’Édom fut troublé ; un tremblement saisit les vaillants de Moab ; tous les habitants de Canaan se figèrent.", 'principes', 'numerus', 'n:nom.pl>n:nom.sg', "un seul prince"),
      ],
      note="Segond met le verset au présent (« s’épouvantent… tombent en défaillance ») ; rendu pédagogique."),
    Q('th-tempus-futurum', 'ISA 11:6',
      target=('Habitabit', 'v:ind.fut.act.3.sg'),
      dist=[
        ("Le loup habite avec l’agneau, Et la panthère se couchera avec le chevreau; Le veau, le lionceau, et le bétail qu’on engraisse, seront ensemble, Et un petit enfant les conduira.", 'Habitabit', 'tempus', 'v:ind.praes.act.3.sg', "la paix des animaux est présentée comme actuelle"),
        ("Les loups habiteront avec l’agneau, Et la panthère se couchera avec le chevreau; Le veau, le lionceau, et le bétail qu’on engraisse, seront ensemble, Et un petit enfant les conduira.", 'Habitabit', 'numerus', 'v:ind.fut.act.3.pl', "plusieurs loups"),
        ("Le loup habitera avec l’agneau, Et la panthère se couchera avec le chevreau; Le veau, le lionceau, et le bétail qu’on engraisse, seront ensemble, Et un petit enfant les conduit.", 'minabit', 'tempus', 'v:ind.fut.act.3.sg>v:ind.praes.act.3.sg', "la conduite du troupeau est actuelle"),
      ]),
    Q('th-tempus-praeteritum', 'MAR 1:6',
      target=('edebat', 'v:ind.imperf.act.3.sg'),
      dist=[
        ("Jean avait un vêtement de poils de chameau, et une ceinture de cuir autour des reins. Il se nourrira de sauterelles et de miel sauvage.", 'edebat', 'tempus', 'v:ind.fut.act.3.sg', "le régime de Jean est annoncé"),
        ("Jean avait un vêtement de poils de chameau, et une ceinture de cuir autour des reins. Il s’est nourri de sauterelles et de miel sauvage.", 'edebat', 'tempus', 'v:ind.perf.act.3.sg', "une habitude devient un fait accompli"),
        ("Jean a un vêtement de poils de chameau, et une ceinture de cuir autour des reins. Il se nourrissait de sauterelles et de miel sauvage.", 'erat', 'tempus', 'v:ind.imperf.act.3.sg>v:ind.praes.act.3.sg', "la description de Jean est actuelle"),
      ],
      note="Segond rend « erat vestitus » par « avait un vêtement » ; la cible est edebat."),
    Q('th-modus-imperativus', 'ISA 16:3',
      target=('absconde', 'v:imp.praes.act.2.sg'),
      dist=[
        ("Donne conseil, fais justice, Couvre-nous en plein midi de ton ombre comme de la nuit, Cachez ceux que l’on poursuit, Ne trahis pas le fugitif!", 'absconde', 'numerus', 'v:imp.praes.act.2.pl', "l’ordre s’adresse à plusieurs personnes"),
        ("Donne conseil, fais justice, Couvre-nous en plein midi de ton ombre comme de la nuit, Tu caches ceux que l’on poursuit, Ne trahis pas le fugitif!", 'absconde', 'modus', 'v:ind.praes.act.2.sg', "un ordre devient un constat"),
        ("Donne conseil, fais justice, Couvre-nous en plein midi de ton ombre comme de la nuit, Cache ceux que l’on poursuit, Ne trahissez pas le fugitif!", 'prodas', 'numerus', 'v:subj.praes.act.2.sg>v:subj.praes.act.2.pl', "la défense s’adresse à plusieurs personnes"),
      ],
      note="Segond a « fais justice » pour « coge concilium » et « le fugitif » pour le pluriel vagos ; la cible est absconde."),
    Q('th-tempus-futurum', 'EXO 39:28',
      target=('præceperat', 'v:ind.plusq.act.3.sg'),
      fr_ref='EXO 39:29',
      gloss={'hyacintho': 'hyacinthe (étoffe de couleur bleue)'},
      dist=[
        ("la ceinture de fin lin retors, brodée, et de couleur bleue, pourpre et cramoisi, comme l’Éternel l’ordonna à Moïse.", 'præceperat', 'tempus', 'v:ind.perf.act.3.sg', "l’ordre n’est plus antérieur à l’exécution"),
        ("la ceinture de fin lin retors, brodée, et de couleur bleue, pourpre et cramoisi, comme l’Éternel l’ordonne à Moïse.", 'præceperat', 'tempus', 'v:ind.praes.act.3.sg', "l’ordre est donné maintenant"),
        ("la ceinture de fin lin retors, brodée, et de couleur bleue, pourpre et cramoisi, comme l’Éternel l’ordonnera à Moïse.", 'præceperat', 'tempus', 'v:ind.fut.act.3.sg', "l’ordre est reporté dans l’avenir"),
      ],
      note="Décalage de numérotation : la Vulgate 39:28 correspond à Segond 39:29."),
    Q('th-tempus-praeteritum', 'PSA 92:1',
      target=('regnavit', 'v:ind.perf.act.3.sg'),
      la='Dominus regnavit, decorem indutus est: indutus est Dominus fortitudinem, et præcinxit se. Etenim firmavit orbem terræ, qui non commovebitur',
      paed=True, fr="Le Seigneur a régné, il s’est revêtu de beauté ; le Seigneur s’est revêtu de force et s’est ceint. Car il a affermi le globe de la terre, qui ne sera pas ébranlé",
      dist=[
        ("Le Seigneur règne, il s’est revêtu de beauté ; le Seigneur s’est revêtu de force et s’est ceint. Car il a affermi le globe de la terre, qui ne sera pas ébranlé", 'regnavit', 'tempus', 'v:ind.praes.act.3.sg', "le règne est présenté comme actuel au lieu d’être proclamé accompli"),
        ("Le Seigneur a régné, il s’est revêtu de beauté ; le Seigneur s’est revêtu de force et s’est ceint. Car il affermira le globe de la terre, qui ne sera pas ébranlé", 'firmavit', 'tempus', 'v:ind.perf.act.3.sg>v:ind.fut.act.3.sg', "l’affermissement du monde est à venir"),
        ("Le Seigneur a régné, il s’est revêtu de beauté ; le Seigneur s’est revêtu de force et s’est ceint. Car il a affermi le globe de la terre, qui n’est pas ébranlé", 'commovebitur', 'tempus', 'v:ind.fut.pass.3.sg>v:ind.praes.pass.3.sg', "la stabilité est constatée au lieu d’être promise"),
      ],
      note="Segond (Ps 93:1) met le verset au présent (« règne… est ferme… ne chancelle pas ») et omet le titre ; rendu pédagogique."),
    Q('th-tempus-futurum', 'ISA 17:10',
      target=('plantabis', 'v:ind.fut.act.2.sg'),
      paed=True, fr="Parce que tu as oublié le Dieu ton sauveur, et que tu ne t’es pas souvenue du Fort, ton secours, tu planteras une plantation fidèle et tu sèmeras une semence étrangère ;",
      dist=[
        ("Parce que tu as oublié le Dieu ton sauveur, et que tu ne t’es pas souvenue du Fort, ton secours, tu as planté une plantation fidèle et tu sèmeras une semence étrangère ;", 'plantabis', 'tempus', 'v:ind.perf.act.2.sg', "la plantation est déjà faite"),
        ("Parce que tu as oublié le Dieu ton sauveur, et que tu ne t’es pas souvenue du Fort, ton secours, elle plantera une plantation fidèle et tu sèmeras une semence étrangère ;", 'plantabis', 'persona', 'v:ind.fut.act.3.sg', "une autre que la ville coupable plante"),
        ("Parce que tu as oublié le Dieu ton sauveur, et que tu ne t’es pas souvenue du Fort, ton secours, tu planteras une plantation fidèle et tu sèmes une semence étrangère ;", 'seminabis', 'tempus', 'v:ind.fut.act.2.sg>v:ind.praes.act.2.sg', "la semaille est actuelle"),
      ],
      note="Segond suit l’hébreu et met les verbes au passé (« tu as fait des plantations… tu as planté ») ; rendu pédagogique."),
    Q('th-vox', 'ISA 13:8',
      target=('conteretur', 'v:ind.fut.pass.3.sg'),
      paed=True, fr="et il sera brisé. Les spasmes et les douleurs les saisiront ; ils souffriront comme une femme en travail ; chacun regardera son voisin avec stupeur : leurs visages seront des visages brûlés.",
      lemma={'facies': 'facies'},
      dist=[
        ("et il brisera. Les spasmes et les douleurs les saisiront ; ils souffriront comme une femme en travail ; chacun regardera son voisin avec stupeur : leurs visages seront des visages brûlés.", 'conteretur', 'vox', 'v:ind.fut.act.3.sg', "celui qui devait être brisé devient celui qui brise"),
        ("et il est brisé. Les spasmes et les douleurs les saisiront ; ils souffriront comme une femme en travail ; chacun regardera son voisin avec stupeur : leurs visages seront des visages brûlés.", 'conteretur', 'tempus', 'v:ind.praes.pass.3.sg', "la ruine est constatée au lieu d’être annoncée"),
        ("et il sera brisé. Les spasmes et les douleurs les saisiront ; il souffrira comme une femme en travail ; chacun regardera son voisin avec stupeur : leurs visages seront des visages brûlés.", 'dolebunt', 'numerus', 'v:ind.fut.act.3.pl>v:ind.fut.act.3.sg', "un seul homme souffre"),
      ],
      note="Segond met le verset au présent (« Ils sont frappés d’épouvante… ») ; rendu pédagogique."),
    Q('th-tempus-praeteritum', '2KI 12:13',
      target=('fiebant', 'v:ind.imperf.act.3.pl'),
      paed=True, fr="Toutefois on ne faisait pas avec cet argent les bassins du temple de l’Éternel, ni les fourchettes, ni les encensoirs, ni les trompettes, ni aucun ustensile d’or et d’argent, avec l’argent qu’on apportait dans le temple de l’Éternel.",
      dist=[
        ("Toutefois on ne fait pas avec cet argent les bassins du temple de l’Éternel, ni les fourchettes, ni les encensoirs, ni les trompettes, ni aucun ustensile d’or et d’argent, avec l’argent qu’on apportait dans le temple de l’Éternel.", 'fiebant', 'tempus', 'v:ind.praes.act.3.pl', "la pratique est présentée comme actuelle"),
        ("Toutefois on ne fera pas avec cet argent les bassins du temple de l’Éternel, ni les fourchettes, ni les encensoirs, ni les trompettes, ni aucun ustensile d’or et d’argent, avec l’argent qu’on apportait dans le temple de l’Éternel.", 'fiebant', 'tempus', 'v:ind.fut.act.3.pl', "un usage passé devient une règle pour l’avenir"),
        ("Toutefois on ne faisait pas avec cet argent les bassins du temple de l’Éternel, ni les fourchettes, ni les encensoirs, ni les trompettes, ni aucun ustensile d’or et d’argent, avec l’argent qu’on apporte dans le temple de l’Éternel.", 'inferebatur', 'tempus', 'v:ind.imperf.pass.3.sg>v:ind.praes.pass.3.sg', "les apports d’argent sont actuels"),
      ],
      note="Segond a le passé simple « on ne fit » pour l’imparfait fiebant ; rendu pédagogique."),
    Q('th-numerus', 'PRO 26:7',
      target=('habet', 'v:ind.praes.act.3.sg'),
      paed=True, fr="Comme le boiteux a en vain de belles jambes, ainsi une parabole est déplacée dans la bouche des insensés.",
      dist=[
        ("Comme les boiteux ont en vain de belles jambes, ainsi une parabole est déplacée dans la bouche des insensés.", 'habet', 'numerus', 'v:ind.praes.act.3.pl', "plusieurs boiteux"),
        ("Comme le boiteux a en vain de belles jambes, ainsi une parabole est déplacée dans la bouche de l’insensé.", 'stultorum', 'numerus', 'a:gen.pl.m>a:gen.sg.m', "un seul insensé"),
        ("Comme le boiteux a en vain une belle jambe, ainsi une parabole est déplacée dans la bouche des insensés.", 'tibias', 'numerus', 'n:acc.pl>n:acc.sg', "une seule jambe"),
      ],
      note="Segond (« les jambes du boiteux sont faibles ») suit l’hébreu et ne rend pas « pulchras frustra habet » ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'GAL 5:6',
      target=('valet', 'v:ind.praes.act.3.sg'),
      dist=[
        ("Car, en Jésus-Christ, ni la circoncision ni l’incirconcision n’a eu de valeur, mais la foi qui est agissante par la charité.", 'valet', 'tempus', 'v:ind.perf.act.3.sg', "le constat est rejeté dans le passé"),
        ("Car, en Jésus-Christ, ni la circoncision ni l’incirconcision n’aura de valeur, mais la foi qui est agissante par la charité.", 'valet', 'tempus', 'v:ind.fut.act.3.sg', "le constat devient une annonce"),
        ("Car, en Jésus-Christ, ni la circoncision ni l’incirconcision n’avait de valeur, mais la foi qui est agissante par la charité.", 'valet', 'tempus', 'v:ind.imperf.act.3.sg', "la valeur n’est niée que pour le passé"),
      ],
      note="Segond rend « operatur » par « est agissante » ; la cible est valet."),
    Q('th-tempus-futurum', 'LEV 18:9',
      target=('revelabis', 'v:ind.fut.act.2.sg'),
      dist=[
        ("Vous ne découvrirez point la nudité de votre sœur, fille de votre père ou fille de votre mère, née dans la maison ou née hors de la maison.", 'revelabis', 'numerus', 'v:ind.fut.act.2.pl', "la défense s’adresse à plusieurs personnes"),
        ("Il ne découvrira point la nudité de sa sœur, fille de son père ou fille de sa mère, née dans la maison ou née hors de la maison.", 'revelabis', 'persona', 'v:ind.fut.act.3.sg', "la défense vise un tiers"),
        ("Tu ne découvres point la nudité de ta sœur, fille de ton père ou fille de ta mère, née dans la maison ou née hors de la maison.", 'revelabis', 'tempus', 'v:ind.praes.act.2.sg', "une défense devient un constat"),
      ]),
    Q('th-tempus-praeteritum', 'JOS 4:18',
      target=('fluebant', 'v:ind.imperf.act.3.pl'),
      paed=True, fr="Et lorsque ceux qui portaient l’arche de l’alliance de l’Éternel furent montés et eurent commencé à fouler la terre sèche, les eaux retournèrent dans leur lit et coulaient comme elles en avaient l’habitude auparavant.",
      dist=[
        ("Et lorsque ceux qui portaient l’arche de l’alliance de l’Éternel furent montés et eurent commencé à fouler la terre sèche, les eaux retournèrent dans leur lit et coulèrent comme elles en avaient l’habitude auparavant.", 'fluebant', 'tempus', 'v:ind.perf.act.3.pl', "un écoulement qui dure devient un fait ponctuel"),
        ("Et lorsque ceux qui portaient l’arche de l’alliance de l’Éternel furent montés et eurent commencé à fouler la terre sèche, les eaux retournèrent dans leur lit et coulent comme elles en avaient l’habitude auparavant.", 'fluebant', 'tempus', 'v:ind.praes.act.3.pl', "le récit passe au présent"),
        ("Et lorsque ceux qui portaient les arches de l’alliance de l’Éternel furent montés et eurent commencé à fouler la terre sèche, les eaux retournèrent dans leur lit et coulaient comme elles en avaient l’habitude auparavant.", 'arcam', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs arches"),
      ],
      note="Segond explicite « les sacrificateurs » et « du milieu du Jourdain » et a « se répandirent » pour l’imparfait fluebant ; rendu pédagogique."),
    Q('th-persona', 'JER 31:19',
      target=('convertisti', 'v:ind.perf.act.2.sg'),
      paed=True, fr="Car après que tu m’as converti, j’ai fait pénitence ; et après que tu m’as instruit, j’ai frappé ma cuisse. J’ai été confondu et j’ai rougi, car j’ai porté l’opprobre de ma jeunesse.",
      lemma={'femur': 'femur'},
      dist=[
        ("Car après qu’il m’a converti, j’ai fait pénitence ; et après que tu m’as instruit, j’ai frappé ma cuisse. J’ai été confondu et j’ai rougi, car j’ai porté l’opprobre de ma jeunesse.", 'convertisti', 'persona', 'v:ind.perf.act.3.sg', "un autre que Dieu, à qui l’on parle, convertit"),
        ("Car après que vous m’avez converti, j’ai fait pénitence ; et après que tu m’as instruit, j’ai frappé ma cuisse. J’ai été confondu et j’ai rougi, car j’ai porté l’opprobre de ma jeunesse.", 'convertisti', 'numerus', 'v:ind.perf.act.2.pl', "plusieurs interlocuteurs convertissent"),
        ("Car après que tu m’as converti, j’ai fait pénitence ; et après que tu m’as instruit, j’ai frappé ma cuisse. J’ai été confondu et j’ai rougi, car il a porté l’opprobre de ma jeunesse.", 'sustinui', 'persona', 'v:ind.perf.act.1.sg>v:ind.perf.act.3.sg', "un autre porte l’opprobre"),
      ],
      note="Segond met le verset au présent (« j’éprouve du repentir… je frappe… je porte ») ; rendu pédagogique."),
    Q('th-modus-subiunctivus', 'LEV 27:16',
      target=('venundetur', 'v:subj.praes.pass.3.sg'),
      paed=True, fr="Si quelqu’un voue et consacre à l’Éternel un champ de sa propriété, le prix sera estimé d’après la quantité de semence : si la terre se sème avec trente boisseaux d’orge, qu’elle soit vendue cinquante sicles d’argent.",
      lemma={'mensuram': 'mensura'},
      gloss={'mensuram': 'mesure'},
      dist=[
        ("Si quelqu’un voue et consacre à l’Éternel un champ de sa propriété, le prix sera estimé d’après la quantité de semence : si la terre se sème avec trente boisseaux d’orge, elle est vendue cinquante sicles d’argent.", 'venundetur', 'modus', 'v:ind.praes.pass.3.sg', "une prescription devient un constat"),
        ("Si quelqu’un voue et consacre à l’Éternel un champ de sa propriété, le prix sera estimé d’après la quantité de semence : si la terre se sème avec trente boisseaux d’orge, qu’elle fût vendue cinquante sicles d’argent.", 'venundetur', 'tempus', 'v:subj.imperf.pass.3.sg', "la prescription est rejetée dans le passé"),
        ("Si quelqu’un voue et consacre à l’Éternel un champ de sa propriété, le prix est estimé d’après la quantité de semence : si la terre se sème avec trente boisseaux d’orge, qu’elle soit vendue cinquante sicles d’argent.", 'æstimabitur', 'tempus', 'v:ind.fut.pass.3.sg>v:ind.praes.pass.3.sg', "l’estimation est actuelle"),
      ],
      note="Segond suit l’hébreu (« un homer de semence d’orge… ton estimation sera ») ; rendu pédagogique."),
    Q('th-numerus', 'MAR 7:5',
      target=('manducant', 'v:ind.praes.act.3.pl'),
      dist=[
        ("Et les pharisiens et les scribes lui demandèrent: Pourquoi ton disciple ne suit-il pas la tradition des anciens, mais prend-il ses repas avec des mains impures?", 'discipuli', 'numerus', 'n:nom.pl>n:nom.sg', "un seul disciple"),
        ("Et les pharisiens et les scribes lui demandèrent: Pourquoi tes disciples ne suivent-ils pas la tradition des anciens, mais prennent-ils leurs repas avec une main impure?", 'manibus', 'numerus', 'n:abl.pl>n:abl.sg', "une seule main"),
        ("Et les pharisiens et les scribes lui demandèrent: Pourquoi tes disciples ne suivent-ils pas la tradition de l’ancien, mais prennent-ils leurs repas avec des mains impures?", 'seniorum', 'numerus', 'a:gen.pl.m.comp>a:gen.sg.m.comp', "un seul ancien"),
      ],
      note="Segond a le passé simple « demandèrent » pour l’imparfait interrogabant ; la cible est manducant."),
    Q('th-tempus-futurum', 'EXO 26:3',
      target=('jungentur', 'v:ind.fut.pass.3.pl'),
      lemma={'nexu': 'nexus'},
      gloss={'nexu': 'lien, attache'},
      dist=[
        ("Cinq de ces tapis sont joints ensemble; les cinq autres seront aussi joints ensemble.", 'jungentur', 'tempus', 'v:ind.praes.pass.3.pl', "l’assemblage est présenté comme un fait actuel"),
        ("Cinq de ces tapis étaient joints ensemble; les cinq autres seront aussi joints ensemble.", 'jungentur', 'tempus', 'v:ind.imperf.pass.3.pl', "la prescription devient un récit du passé"),
        ("Cinq de ces tapis seront joints ensemble; les cinq autres sont aussi joints ensemble.", 'cohærebunt', 'tempus', 'v:ind.fut.act.3.pl>v:ind.praes.act.3.pl', "le second assemblage est présenté comme actuel"),
      ],
      note="Segond rend « nexu simili cohærebunt » par « seront aussi joints ensemble »."),
    Q('th-tempus-futurum', 'NUM 4:6',
      target=('extendentque', 'v:ind.fut.act.3.pl'),
      gloss={'hyacinthinum': 'de couleur hyacinthe (bleu violet)'},
      dist=[
        ("ils mettront dessus une couverture de peaux de dauphins, et ils étendent par-dessus un drap entièrement d’étoffe bleue; puis ils placeront les barres de l’arche.", 'extendentque', 'tempus', 'v:ind.praes.act.3.pl', "le geste est présenté comme actuel"),
        ("ils mettront dessus une couverture de peaux de dauphins, et vous étendrez par-dessus un drap entièrement d’étoffe bleue; puis ils placeront les barres de l’arche.", 'extendentque', 'persona', 'v:ind.fut.act.2.pl', "l’ordre s’adresse aux auditeurs au lieu des fils de Kehath"),
        ("ils mettront dessus une couverture de peaux de dauphins, et ils étendront par-dessus un drap entièrement d’étoffe bleue; puis il placera les barres de l’arche.", 'inducent', 'numerus', 'v:ind.fut.act.3.pl>v:ind.fut.act.3.sg', "un seul homme place les barres"),
      ],
      note="Segond a « peaux de dauphins » pour « janthinarum pellium » et explicite « de l’arche » ; la cible est extendentque."),
    Q('th-tempus-futurum', 'ISA 14:11',
      target=('erunt', 'v:ind.fut.act.3.pl'),
      paed=True, fr="Ton orgueil a été précipité aux enfers, ton cadavre est tombé ; sous toi s’étendra la vermine, et les vers seront ta couverture.",
      dist=[
        ("Ton orgueil a été précipité aux enfers, ton cadavre est tombé ; sous toi s’étendra la vermine, et les vers sont ta couverture.", 'erunt', 'tempus', 'v:ind.praes.act.3.pl', "l’état est présenté comme actuel"),
        ("Ton orgueil a été précipité aux enfers, ton cadavre est tombé ; sous toi s’étendra la vermine, et le ver sera ta couverture.", 'erunt', 'numerus', 'v:ind.fut.act.3.sg', "un seul ver"),
        ("Ton orgueil a été précipité aux enfers, ton cadavre tombe ; sous toi s’étendra la vermine, et les vers seront ta couverture.", 'concidit', 'tempus', 'v:ind.perf.act.3.sg>v:ind.praes.act.3.sg', "la chute du cadavre est en cours"),
      ],
      note="Segond suit l’hébreu (« Avec le son de tes luths… les vers sont ta couverture ») ; rendu pédagogique."),
    Q('th-modus-imperativus', 'ISA 23:16',
      target=('Sume', 'v:imp.praes.act.2.sg'),
      dist=[
        ("Prenez la harpe, parcours la ville, Prostituée qu’on oublie! Joue bien, répète tes chants, Pour qu’on se souvienne de toi!", 'Sume', 'numerus', 'v:imp.praes.act.2.pl', "l’ordre s’adresse à plusieurs personnes"),
        ("Tu prends la harpe, parcours la ville, Prostituée qu’on oublie! Joue bien, répète tes chants, Pour qu’on se souvienne de toi!", 'Sume', 'modus', 'v:ind.praes.act.2.sg', "un ordre devient un constat"),
        ("Prends la harpe, parcourez la ville, Prostituée qu’on oublie! Joue bien, répète tes chants, Pour qu’on se souvienne de toi!", 'circui', 'numerus', 'v:imp.praes.act.2.sg>v:imp.praes.act.2.pl', "plusieurs personnes parcourent la ville"),
      ],
      note="Segond a « Prostituée qu’on oublie » pour « meretrix oblivioni tradita »."),
]
