# sheet_004 → batch_004
ITEMS = [
    Q('th-tempus-praeteritum', 'PSA 73:6',
      target=('exciderunt', 'v:ind.perf.act.3.pl'),
      paed=True, fr="Ils en ont abattu les portes toutes à la fois ; à la hache et au pic, ils l’ont démolie.",
      dist=[
        ("Ils en abattent les portes toutes à la fois ; à la hache et au pic, ils l’ont démolie.", 'exciderunt', 'tempus', 'v:ind.praes.act.3.pl', "la destruction des portes est en cours"),
        ("Ils en abattront les portes toutes à la fois ; à la hache et au pic, ils l’ont démolie.", 'exciderunt', 'tempus', 'v:ind.fut.act.3.pl', "la destruction des portes est annoncée"),
        ("Ils en ont abattu les portes toutes à la fois ; à la hache et au pic, il l’a démolie.", 'dejecerunt', 'numerus', 'v:ind.perf.act.3.sg', "un seul destructeur achève l’ouvrage"),
      ],
      note="Segond (74:6) suit l’hébreu (« toutes les sculptures ») là où la Vulgate a « ses portes » ; rendu pédagogique."),
    Q('th-tempus-futurum', 'NUM 6:19',
      target=('tradet', 'v:ind.fut.act.3.sg'),
      dist=[
        ("Le sacrificateur prendra l’épaule cuite du bélier, un gâteau sans levain de la corbeille, et une galette sans levain; et il les pose sur les mains du naziréen, après qu’il aura rasé sa tête consacrée.", 'tradet', 'tempus', 'v:ind.praes.act.3.sg', "la remise se fait maintenant"),
        ("Le sacrificateur prendra l’épaule cuite du bélier, un gâteau sans levain de la corbeille, et une galette sans levain; et il les a posées sur les mains du naziréen, après qu’il aura rasé sa tête consacrée.", 'tradet', 'tempus', 'v:ind.perf.act.3.sg', "la remise est déjà faite"),
        ("Le sacrificateur prendra l’épaule cuite du bélier, un gâteau sans levain de la corbeille, et une galette sans levain; et il les posera sur la main du naziréen, après qu’il aura rasé sa tête consacrée.", 'manus', 'numerus', 'n:acc.pl>n:acc.sg', "une seule main"),
      ],
      note="Segond explicite le sujet « Le sacrificateur prendra » et rend le passif « rasum fuerit caput » à l’actif ; la cible est tradet."),
    Q('th-tempus-praeteritum', 'PRO 18:8',
      target=('perveniunt', 'v:ind.praes.act.3.pl'),
      la='Verba bilinguis quasi simplicia, et ipsa perveniunt usque ad interiora ventris.',
      fr='Les paroles du rapporteur sont comme des friandises, Elles descendent jusqu’au fond des entrailles.',
      gloss={'simplicia': 'simple, inoffensif'},
      dist=[
        ("Les paroles du rapporteur sont comme des friandises, Elles sont descendues jusqu’au fond des entrailles.", 'perveniunt', 'tempus', 'v:ind.perf.act.3.pl', "la pénétration des paroles est un fait passé"),
        ("Les paroles du rapporteur sont comme des friandises, Elles descendront jusqu’au fond des entrailles.", 'perveniunt', 'tempus', 'v:ind.fut.act.3.pl', "la pénétration des paroles est annoncée"),
        ("Les paroles des rapporteurs sont comme des friandises, Elles descendent jusqu’au fond des entrailles.", 'bilinguis', 'numerus', 'a:gen.sg.m>a:gen.pl.m', "plusieurs rapporteurs"),
      ],
      note="Segond ne traduit que la première moitié du verset (la seconde vient de la LXX) ; « quasi simplicia » est rendu librement par « comme des friandises »."),
    Q('th-persona', 'EST 3:3',
      target=('observas', 'v:ind.praes.act.2.sg'),
      dist=[
        ("Et les serviteurs du roi, qui se tenaient à la porte du roi, dirent à Mardochée: Pourquoi transgresse-t-il l’ordre du roi?", 'observas', 'persona', 'v:ind.praes.act.3.sg', "la question vise un tiers et non Mardochée"),
        ("Et les serviteurs du roi, qui se tenaient à la porte du roi, dirent à Mardochée: Pourquoi transgressez-vous l’ordre du roi?", 'observas', 'numerus', 'v:ind.praes.act.2.pl', "la question s’adresse à plusieurs personnes"),
        ("Et les serviteurs du roi, qui se tenaient à la porte du roi, dirent à Mardochée: Pourquoi transgresses-tu l’ordre des rois?", 'regis', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs rois"),
      ],
      note="Segond explicite « à Mardochée » pour « Cui » et rend « non observas » par « transgresses-tu »."),
    Q('th-persona', 'EST 16:9',
      target=('debetis', 'v:ind.praes.act.2.pl'),
      paed=True, fr="Et vous ne devez pas penser, si nous ordonnons des choses contraires, que cela vient de la légèreté de notre esprit ; mais nous rendons notre sentence selon la qualité et la nécessité des temps, comme l’exige l’intérêt de l’État.",
      dist=[
        ("Et ils ne doivent pas penser, si nous ordonnons des choses contraires, que cela vient de la légèreté de notre esprit ; mais nous rendons notre sentence selon la qualité et la nécessité des temps, comme l’exige l’intérêt de l’État.", 'debetis', 'persona', 'v:ind.praes.act.3.pl', "l’avertissement vise des tiers et non les destinataires"),
        ("Et tu ne dois pas penser, si nous ordonnons des choses contraires, que cela vient de la légèreté de notre esprit ; mais nous rendons notre sentence selon la qualité et la nécessité des temps, comme l’exige l’intérêt de l’État.", 'debetis', 'numerus', 'v:ind.praes.act.2.sg', "un seul destinataire"),
        ("Et vous ne devez pas penser, si j’ordonne des choses contraires, que cela vient de la légèreté de notre esprit ; mais nous rendons notre sentence selon la qualité et la nécessité des temps, comme l’exige l’intérêt de l’État.", 'jubeamus', 'numerus', 'v:subj.praes.act.1.sg', "le roi ordonne seul au lieu du pluriel de majesté"),
      ],
      note="Passage deutérocanonique absent de Segond ; rendu pédagogique."),
    Q('th-nonfinita', '2PE 2:9',
      target=('eripere', 'v:inf.praes.act'),
      dist=[
        ("le Seigneur sait avoir délivré de l’épreuve les hommes pieux, et réserver les injustes pour être punis au jour du jugement,", 'eripere', 'tempus', 'v:inf.perf.act', "la délivrance est présentée comme déjà accomplie"),
        ("le Seigneur sait délivrer de l’épreuve l’homme pieux, et réserver les injustes pour être punis au jour du jugement,", 'pios', 'numerus', 'a:acc.pl.m>a:acc.sg.m', "un seul homme pieux"),
        ("le Seigneur sait délivrer de l’épreuve les hommes pieux, et réserver l’injuste pour être puni au jour du jugement,", 'iniquos', 'numerus', 'a:acc.pl.m>a:acc.sg.m', "un seul injuste"),
      ],
      note="« cruciandos » (gérondif) est rendu par « pour être punis »."),
    Q('th-vox', '1TI 2:15',
      target=('Salvabitur', 'v:ind.fut.pass.3.sg'),
      dist=[
        ("Elle sauvera néanmoins en devenant mère, si elle persévère avec modestie dans la foi, dans la charité, et dans la sainteté.", 'Salvabitur', 'vox', 'v:ind.fut.act.3.sg', "la femme devient celle qui sauve"),
        ("Elle est néanmoins sauvée en devenant mère, si elle persévère avec modestie dans la foi, dans la charité, et dans la sainteté.", 'Salvabitur', 'tempus', 'v:ind.praes.pass.3.sg', "le salut est actuel et non promis"),
        ("Elles seront néanmoins sauvées en devenant mères, si elles persévèrent avec modestie dans la foi, dans la charité, et dans la sainteté.", 'Salvabitur', 'numerus', 'v:ind.fut.pass.3.pl', "plusieurs femmes"),
      ],
      note="Segond rend « per filiorum generationem » par « en devenant mère »."),
    Q('th-modus-imperativus', 'ISA 23:12',
      target=('transfreta', 'v:imp.praes.act.2.sg'),
      gloss={'Cethim': 'Kittim'},
      dist=[
        ("Il a dit: Tu ne te livreras plus à la joie, Vierge déshonorée, fille de Sidon! Levez-vous, passez au pays de Kittim! Même là, il n’y aura pas de repos pour toi.", 'transfreta', 'numerus', 'v:imp.praes.act.2.pl', "l’ordre s’adresse à plusieurs personnes"),
        ("Il a dit: Tu ne te livreras plus à la joie, Vierge déshonorée, fille de Sidon! Lève-toi, tu passes au pays de Kittim! Même là, il n’y aura pas de repos pour toi.", 'transfreta', 'modus', 'v:ind.praes.act.2.sg', "un ordre devient un constat"),
        ("Il a dit: Elle ne se livrera plus à la joie, Vierge déshonorée, fille de Sidon! Lève-toi, passe au pays de Kittim! Même là, il n’y aura pas de repos pour toi.", 'adjicies', 'persona', 'v:ind.fut.act.2.sg>v:ind.fut.act.3.sg', "la parole n’est plus adressée à la vierge mais dite d’elle"),
      ],
      note="Segond rend le participe « consurgens » par l’impératif « Lève-toi » et « calumniam sustinens » par « déshonorée »."),
    Q('th-modus-imperativus', 'ISA 35:3',
      target=('roborate', 'v:imp.praes.act.2.pl'),
      dist=[
        ("Fortifiez les mains languissantes, Et vous affermissez les genoux qui chancellent;", 'roborate', 'modus', 'v:ind.praes.act.2.pl', "un ordre devient un constat"),
        ("Fortifiez la main languissante, Et affermissez les genoux qui chancellent;", 'manus', 'numerus', 'n:acc.pl>n:acc.sg', "une seule main"),
        ("Fortifiez les mains languissantes, Et affermissez le genou qui chancelle;", 'genua', 'numerus', 'n:acc.pl>n:acc.sg', "un seul genou"),
      ]),
    Q('th-tempus-futurum', 'ISA 9:18',
      target=('vorabit', 'v:ind.fut.act.3.sg'),
      paed=True, fr="Car l’impiété s’est embrasée comme un feu : elle dévorera la ronce et l’épine, elle s’allumera dans l’épaisseur de la forêt, et elle tourbillonnera en une fumée orgueilleuse.",
      dist=[
        ("Car l’impiété s’est embrasée comme un feu : elle dévore la ronce et l’épine, elle s’allumera dans l’épaisseur de la forêt, et elle tourbillonnera en une fumée orgueilleuse.", 'vorabit', 'tempus', 'v:ind.praes.act.3.sg', "la dévoration est en cours"),
        ("Car l’impiété s’est embrasée comme un feu : elle a dévoré la ronce et l’épine, elle s’allumera dans l’épaisseur de la forêt, et elle tourbillonnera en une fumée orgueilleuse.", 'vorabit', 'tempus', 'v:ind.perf.act.3.sg', "la dévoration est déjà accomplie"),
        ("Car l’impiété s’est embrasée comme un feu : elle dévorera les ronces et l’épine, elle s’allumera dans l’épaisseur de la forêt, et elle tourbillonnera en une fumée orgueilleuse.", 'veprem', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs ronces"),
      ],
      note="Segond (9:17 dans sa numérotation) a le présent (« consume », « dévore ») ; rendu pédagogique des futurs latins."),
    Q('th-nonfinita', '1CH 15:19',
      target=('concrepantes', 'v:part.praes.act.nom.pl.m'),
      paed=True, fr="Quant aux chantres Héman, Asaph et Éthan, faisant retentir des cymbales d’airain,",
      gloss={'Heman': 'Héman', 'Asaph': 'Asaph', 'Ethan': 'Éthan'},
      dist=[
        ("Quant aux chantres Héman, Asaph et Éthan, sur le point de faire retentir des cymbales d’airain,", 'concrepantes', 'tempus', 'v:part.fut.act.nom.pl.m', "la musique n’a pas encore commencé"),
        ("Quant aux chantres Héman, Asaph et Éthan, faisant retentir une cymbale d’airain,", 'cymbalis', 'numerus', 'n:abl.pl>n:abl.sg', "une seule cymbale"),
        ("Quant aux chantres Héman, Asaph et Éthan, ils font retentir des cymbales d’airain.", 'concrepantes', 'nonfinita', 'v:ind.praes.act.3.pl', "le participe devient une proposition complète"),
      ],
      note="Segond ajoute « avaient … pour les faire retentir » ; rendu pédagogique du participe."),
    Q('th-vox', 'EST 8:10',
      target=('mittebantur', 'v:ind.imperf.pass.3.pl'),
      la='Ipsæque epistolæ, quæ regis nomine mittebantur, annulo ipsius obsignatæ sunt',
      paed=True, fr="Et ces lettres, qui étaient envoyées au nom du roi, furent scellées de son anneau",
      dist=[
        ("Et ces lettres, qui envoyaient au nom du roi, furent scellées de son anneau", 'mittebantur', 'vox', 'v:ind.imperf.act.3.pl', "les lettres deviennent celles qui envoient"),
        ("Et ces lettres, qui sont envoyées au nom du roi, furent scellées de son anneau", 'mittebantur', 'tempus', 'v:ind.praes.pass.3.pl', "l’envoi est actuel"),
        ("Et ces lettres, qui étaient envoyées au nom des rois, furent scellées de son anneau", 'regis', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs rois"),
      ],
      note="Segond (« On écrivit au nom du roi Assuérus, et l’on scella ») tourne le passif à l’actif ; rendu pédagogique."),
    Q('th-tempus-futurum', 'MAT 12:20',
      target=('confringet', 'v:ind.fut.act.3.sg'),
      dist=[
        ("Il ne brise point le roseau cassé, Et il n’éteindra point le lumignon qui fume, Jusqu’à ce qu’il ait fait triompher la justice.", 'confringet', 'tempus', 'v:ind.praes.act.3.sg', "le ménagement est actuel et non promis"),
        ("Il n’a point brisé le roseau cassé, Et il n’éteindra point le lumignon qui fume, Jusqu’à ce qu’il ait fait triompher la justice.", 'confringet', 'tempus', 'v:ind.perf.act.3.sg', "le ménagement est un fait passé"),
        ("Il ne brisera point les roseaux cassés, Et il n’éteindra point le lumignon qui fume, Jusqu’à ce qu’il ait fait triompher la justice.", 'arundinem', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs roseaux"),
      ]),
    Q('th-tempus-praeteritum', 'GEN 31:42',
      target=('respexit', 'v:ind.perf.act.3.sg'),
      dist=[
        ("Si je n’eusse pas eu pour moi le Dieu de mon père, le Dieu d’Abraham, celui que craint Isaac, tu m’aurais maintenant renvoyé à vide. Dieu voit ma souffrance et le travail de mes mains, et hier il a prononcé son jugement.", 'respexit', 'tempus', 'v:ind.praes.act.3.sg', "le regard de Dieu est actuel"),
        ("Si je n’eusse pas eu pour moi le Dieu de mon père, le Dieu d’Abraham, celui que craint Isaac, tu m’aurais maintenant renvoyé à vide. Dieu verra ma souffrance et le travail de mes mains, et hier il a prononcé son jugement.", 'respexit', 'tempus', 'v:ind.fut.act.3.sg', "le regard de Dieu est à venir"),
        ("Si je n’eusse pas eu pour moi le Dieu de mon père, le Dieu d’Abraham, celui que craint Isaac, tu m’aurais maintenant renvoyé à vide. Dieu a vu ma souffrance et le travail de ma main, et hier il a prononcé son jugement.", 'manuum', 'numerus', 'n:gen.pl>n:gen.sg', "une seule main"),
      ],
      note="Segond rend « timor Isaac » par « celui que craint Isaac » et « arguit te » par « il a prononcé son jugement »."),
    Q('th-casus-obliqui', 'ZEP 1:15',
      target=('iræ', 'n:gen.sg'),
      dist=[
        ("Ce jour est un jour pour la fureur, Un jour de détresse et d’angoisse, Un jour de ravage et de destruction, Un jour de ténèbres et d’obscurité, Un jour de nuées et de brouillards,", 'iræ', 'casus', 'n:dat.sg', "la fureur n’est plus la nature du jour mais sa destination"),
        ("Ce jour est un jour de fureurs, Un jour de détresse et d’angoisse, Un jour de ravage et de destruction, Un jour de ténèbres et d’obscurité, Un jour de nuées et de brouillards,", 'iræ', 'numerus', 'n:gen.pl', "plusieurs accès de fureur"),
        ("Ce jour est un jour de fureur, Un jour de détresse et d’angoisse, Un jour de ravages et de destruction, Un jour de ténèbres et d’obscurité, Un jour de nuées et de brouillards,", 'calamitatis', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs ravages"),
      ]),
    Q('th-tempus-futurum', 'ISA 59:11',
      target=('Rugiemus', 'v:ind.fut.act.1.pl'),
      paed=True, fr="Nous rugirons tous comme des ours, et comme des colombes qui méditent nous gémirons ; nous avons attendu le jugement, et il n’est pas là ; le salut, et il s’est éloigné de nous.",
      dist=[
        ("Nous rugissons tous comme des ours, et comme des colombes qui méditent nous gémirons ; nous avons attendu le jugement, et il n’est pas là ; le salut, et il s’est éloigné de nous.", 'Rugiemus', 'tempus', 'v:ind.praes.act.1.pl', "la plainte est actuelle"),
        ("Nous avons tous rugi comme des ours, et comme des colombes qui méditent nous gémirons ; nous avons attendu le jugement, et il n’est pas là ; le salut, et il s’est éloigné de nous.", 'Rugiemus', 'tempus', 'v:ind.perf.act.1.pl', "la plainte est passée"),
        ("Ils rugiront tous comme des ours, et comme des colombes qui méditent nous gémirons ; nous avons attendu le jugement, et il n’est pas là ; le salut, et il s’est éloigné de nous.", 'Rugiemus', 'persona', 'v:ind.fut.act.3.pl', "ce sont d’autres qui rugissent, non le peuple qui parle"),
      ],
      note="Segond a le présent partout ; rendu pédagogique des futurs et du parfait latins."),
    Q('th-nonfinita', '1KI 8:37',
      target=('obsidens', 'v:part.praes.act.nom.sg.m'),
      la='et afflixerit eum inimicus ejus portas obsidens',
      paed=True, fr="et si son ennemi l’accable en assiégeant ses portes",
      dist=[
        ("et si son ennemi l’accable en assiégeant sa porte", 'portas', 'numerus', 'n:acc.pl>n:acc.sg', "une seule porte"),
        ("et si ses ennemis l’accablent en assiégeant ses portes", 'obsidens', 'numerus', 'v:part.praes.act.nom.pl.m', "plusieurs ennemis"),
        ("et si son ennemi l’accable et assiège ses portes", 'obsidens', 'nonfinita', 'v:ind.praes.act.3.sg', "le participe devient une action distincte et coordonnée"),
      ],
      note="Segond (« quand l’ennemi assiégera ton peuple dans son pays, dans ses portes ») paraphrase ; rendu pédagogique de la proposition."),
    Q('th-nonfinita', 'PSA 90:6',
      target=('perambulante', 'v:part.praes.act.abl.sg.n'),
      paed=True, fr="de la flèche qui vole pendant le jour, de la chose qui rôde dans les ténèbres, de l’attaque et du démon de midi.",
      dist=[
        ("de la flèche qui vole pendant le jour, des choses qui rôdent dans les ténèbres, de l’attaque et du démon de midi.", 'perambulante', 'numerus', 'v:part.praes.act.abl.pl.n', "plusieurs choses qui rôdent"),
        ("de la flèche qui vole pendant le jour, de la chose qui va rôder dans les ténèbres, de l’attaque et du démon de midi.", 'perambulante', 'tempus', 'v:part.fut.act.abl.sg.n', "la menace n’a pas encore commencé"),
        ("des flèches qui volent pendant le jour, de la chose qui rôde dans les ténèbres, de l’attaque et du démon de midi.", 'sagitta', 'numerus', 'n:abl.sg>n:abl.pl', "plusieurs flèches"),
      ],
      note="Segond (91:6) suit l’hébreu (« la peste qui marche ») ; la Vulgate suit la LXX ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'ISA 9:4',
      target=('superasti', 'v:ind.perf.act.2.sg'),
      paed=True, fr="Car le joug de son fardeau, la verge de son épaule et le sceptre de son oppresseur, tu les as brisés, comme au jour de Madian.",
      dist=[
        ("Car le joug de son fardeau, la verge de son épaule et le sceptre de son oppresseur, tu les brises, comme au jour de Madian.", 'superasti', 'tempus', 'v:ind.praes.act.2.sg', "la victoire est en cours"),
        ("Car le joug de son fardeau, la verge de son épaule et le sceptre de son oppresseur, tu les briseras, comme au jour de Madian.", 'superasti', 'tempus', 'v:ind.fut.act.2.sg', "la victoire est annoncée"),
        ("Car le joug de son fardeau, la verge de son épaule et le sceptre de son oppresseur, il les a brisés, comme au jour de Madian.", 'superasti', 'persona', 'v:ind.perf.act.3.sg', "la victoire n’est plus attribuée à l’interlocuteur"),
      ],
      note="Segond (9:3 dans sa numérotation) a le présent « tu les brises » ; rendu pédagogique du parfait."),
    Q('th-modus-imperativus', 'SOL 8:14',
      target=('Fuge', 'v:imp.praes.act.2.sg'),
      dist=[
        ("Tu fuis, mon bien-aimé! Sois semblable à la gazelle ou au faon des biches, Sur les montagnes des aromates!", 'Fuge', 'modus', 'v:ind.praes.act.2.sg', "un ordre devient un constat"),
        ("Fuis, mon bien-aimé! Sois semblable à la gazelle ou au faon de la biche, Sur les montagnes des aromates!", 'cervorum', 'numerus', 'n:gen.pl>n:gen.sg', "une seule biche"),
        ("Fuis, mon bien-aimé! Sois semblable à la gazelle ou au faon des biches, Sur la montagne des aromates!", 'montes', 'numerus', 'n:acc.pl>n:acc.sg', "une seule montagne"),
      ],
      note="« Sponsa » indique la locutrice (l’épouse) et n’est pas traduit par Segond."),
    Q('th-modus-imperativus', 'ISA 54:2',
      target=('fac', 'v:imp.praes.act.2.sg'),
      dist=[
        ("Élargis l’espace de ta tente; Qu’on déploie les couvertures de ta demeure: Ne retiens pas! Allongez vos cordages, Et affermis tes pieux!", 'fac', 'numerus', 'v:imp.praes.act.2.pl', "l’ordre s’adresse à plusieurs personnes"),
        ("Élargis l’espace de ta tente; Qu’on déploie les couvertures de ta demeure: Ne retiens pas! Tu allonges tes cordages, Et affermis tes pieux!", 'fac', 'modus', 'v:ind.praes.act.2.sg', "un ordre devient un constat"),
        ("Élargis l’espace de ta tente; Qu’on déploie les couvertures de ta demeure: Ne retiens pas! Allonge ton cordage, Et affermis tes pieux!", 'funiculos', 'numerus', 'n:acc.pl>n:acc.sg', "un seul cordage"),
      ],
      note="Segond rend « extende » par « Qu’on déploie » ; la cible est « fac » (longos fac = allonge)."),
    Q('th-numerus', 'JER 38:13',
      target=('extraxerunt', 'v:ind.perf.act.3.pl'),
      dist=[
        ("Il tira Jérémie avec les cordes, et le fit monter hors de la citerne. Jérémie resta dans la cour de la prison.", 'extraxerunt', 'numerus', 'v:ind.perf.act.3.sg', "un seul sauveteur"),
        ("Ils tirèrent Jérémie avec la corde, et le firent monter hors de la citerne. Jérémie resta dans la cour de la prison.", 'funibus', 'numerus', 'n:abl.pl>n:abl.sg', "une seule corde"),
        ("Ils tirèrent Jérémie avec les cordes, et le firent monter hors de la citerne. Jérémie resta dans la cour des prisons.", 'carceris', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs prisons"),
      ]),
    Q('th-tempus-praeteritum', 'GEN 41:21',
      target=('torpebant', 'v:ind.imperf.act.3.pl'),
      paed=True, fr="elles ne donnèrent aucun signe de satiété, mais elles restaient engourdies dans la même maigreur et la même laideur. M’étant éveillé, de nouveau accablé de sommeil,",
      dist=[
        ("elles ne donnèrent aucun signe de satiété, mais elles restèrent engourdies dans la même maigreur et la même laideur. M’étant éveillé, de nouveau accablé de sommeil,", 'torpebant', 'tempus', 'v:ind.perf.act.3.pl', "un état qui dure devient un fait ponctuel"),
        ("elles ne donnèrent aucun signe de satiété, mais elles restent engourdies dans la même maigreur et la même laideur. M’étant éveillé, de nouveau accablé de sommeil,", 'torpebant', 'tempus', 'v:ind.praes.act.3.pl', "l’engourdissement est actuel"),
        ("elles ne donnèrent aucun signe de satiété, mais elle restait engourdie dans la même maigreur et la même laideur. M’étant éveillé, de nouveau accablé de sommeil,", 'torpebant', 'numerus', 'v:ind.imperf.act.3.sg', "une seule vache reste engourdie"),
      ],
      note="Segond suit l’hébreu (« leur apparence était laide comme auparavant. Et je m’éveillai ») ; rendu pédagogique de la Vulgate."),
    Q('th-tempus-praeteritum', 'LAM 4:5',
      target=('vescebantur', 'v:ind.imperf.act.3.pl'),
      gloss={'He': 'hé (lettre hébraïque)'},
      dist=[
        ("Ceux qui se nourrissent de mets délicats Périssent dans les rues; Ceux qui étaient élevés dans la pourpre Embrassent les fumiers.", 'vescebantur', 'tempus', 'v:ind.praes.act.3.pl', "les festins sont actuels"),
        ("Celui qui se nourrissait de mets délicats Périt dans les rues; Ceux qui étaient élevés dans la pourpre Embrassent les fumiers.", 'vescebantur', 'numerus', 'v:ind.imperf.act.3.sg', "un seul homme au lieu d’une classe entière"),
        ("Ceux qui se nourrissaient de mets délicats Périssent dans la rue; Ceux qui étaient élevés dans la pourpre Embrassent les fumiers.", 'viis', 'numerus', 'n:abl.pl>n:abl.sg', "une seule rue"),
      ],
      note="Segond a le présent pour les parfaits « interierunt » et « amplexati sunt » ; la cible est l’imparfait « vescebantur »."),
    Q('th-modus-subiunctivus', 'JOB 32:2',
      target=('diceret', 'v:subj.imperf.act.3.sg'),
      gloss={'Barachel': 'Barakeel', 'Buzites': 'de Buz (Buzite)', 'Ram': 'Ram'},
      dist=[
        ("Alors s’enflamma de colère Élihu, fils de Barakeel de Buz, de la famille de Ram. Sa colère s’enflamma contre Job, parce qu’il se dit juste devant Dieu.", 'diceret', 'tempus', 'v:subj.praes.act.3.sg', "la prétention de Job est actuelle"),
        ("Alors s’enflamma de colère Élihu, fils de Barakeel de Buz, de la famille de Ram. Sa colère s’enflamma contre Job, parce qu’il s’était dit juste devant Dieu.", 'diceret', 'tempus', 'v:subj.plusq.act.3.sg', "la prétention de Job est antérieure et close"),
        ("Alors s’enflamma de colère Élihu, fils de Barakeel de Buz, de la famille de Ram. Sa colère s’enflamma contre Job, parce qu’ils se disaient justes devant Dieu.", 'diceret', 'numerus', 'v:subj.imperf.act.3.pl', "plusieurs personnes se prétendent justes"),
      ],
      note="Segond rend « iratus indignatusque est » par « s’enflamma de colère »."),
    Q('th-tempus-praeteritum', '2PE 2:16',
      target=('prohibuit', 'v:ind.perf.act.3.sg'),
      dist=[
        ("mais qui fut repris pour sa transgression: une ânesse muette, faisant entendre une voix d’homme, arrête la démence du prophète.", 'prohibuit', 'tempus', 'v:ind.praes.act.3.sg', "l’intervention de l’ânesse est actuelle"),
        ("mais qui fut repris pour sa transgression: une ânesse muette, faisant entendre une voix d’homme, arrêtera la démence du prophète.", 'prohibuit', 'tempus', 'v:ind.fut.act.3.sg', "l’intervention de l’ânesse est annoncée"),
        ("mais qui fut repris pour sa transgression: une ânesse muette, faisant entendre une voix d’homme, arrêta la démence des prophètes.", 'prophetæ', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs prophètes"),
      ],
      note="Segond rend « correptionem habuit » par « fut repris » et « subjugale mutum animal » par « une ânesse muette »."),
    Q('th-tempus-praeteritum', 'GEN 18:11',
      target=('Erant', 'v:ind.imperf.act.3.pl'),
      dist=[
        ("Abraham et Sara sont vieux, avancés en âge: et Sara ne pouvait plus espérer avoir des enfants.", 'Erant', 'tempus', 'v:ind.praes.act.3.pl', "la vieillesse est actuelle"),
        ("Abraham et Sara seront vieux, avancés en âge: et Sara ne pouvait plus espérer avoir des enfants.", 'Erant', 'tempus', 'v:ind.fut.act.3.pl', "la vieillesse est annoncée"),
        ("Abraham et Sara ont été vieux, avancés en âge: et Sara ne pouvait plus espérer avoir des enfants.", 'Erant', 'tempus', 'v:ind.perf.act.3.pl', "un état durable devient un fait clos"),
      ],
      note="Segond explicite « Abraham et Sara » pour « ambo » et paraphrase « desierant Saræ fieri muliebria »."),
    Q('th-tempus-praeteritum', '2KI 13:21',
      target=('revixit', 'v:ind.perf.act.3.sg'),
      dist=[
        ("Et comme on enterrait un homme, voici, on aperçut une de ces troupes, et l’on jeta l’homme dans le sépulcre d’Élisée. L’homme alla toucher les os d’Élisée, et il reprend vie et se leva sur ses pieds.", 'revixit', 'tempus', 'v:ind.praes.act.3.sg', "le retour à la vie est présenté comme actuel"),
        ("Et comme on enterrait un homme, voici, on aperçut une de ces troupes, et l’on jeta l’homme dans le sépulcre d’Élisée. L’homme alla toucher les os d’Élisée, et il reprendra vie et se leva sur ses pieds.", 'revixit', 'tempus', 'v:ind.fut.act.3.sg', "le retour à la vie est annoncé"),
        ("Et comme on enterrait un homme, voici, on aperçut une de ces troupes, et l’on jeta l’homme dans le sépulcre d’Élisée. L’homme alla toucher les os d’Élisée, et il reprit vie et se leva sur son pied.", 'pedes', 'numerus', 'n:acc.pl>n:acc.sg', "un seul pied"),
      ],
      note="Segond rend « viderunt … projecerunt » par « on aperçut … l’on jeta »."),
    Q('th-tempus-futurum', 'PRO 26:2',
      target=('superveniet', 'v:ind.fut.act.3.sg'),
      paed=True, fr="Comme l’oiseau qui vole ailleurs et le passereau qui va où il veut, ainsi la malédiction proférée en vain retombera sur quelqu’un.",
      lemma={'avis': 'auis'},
      dist=[
        ("Comme l’oiseau qui vole ailleurs et le passereau qui va où il veut, ainsi la malédiction proférée en vain retombe sur quelqu’un.", 'superveniet', 'tempus', 'v:ind.praes.act.3.sg', "la retombée est actuelle"),
        ("Comme l’oiseau qui vole ailleurs et le passereau qui va où il veut, ainsi la malédiction proférée en vain est retombée sur quelqu’un.", 'superveniet', 'tempus', 'v:ind.perf.act.3.sg', "la retombée est un fait passé"),
        ("Comme l’oiseau qui vole ailleurs et le passereau qui va où il veut, ainsi la malédiction proférée en vain retombait sur quelqu’un.", 'superveniet', 'tempus', 'v:ind.imperf.act.3.sg', "la retombée devient une habitude passée"),
      ],
      note="Segond suit l’hébreu (« n’a point d’effet ») ; rendu pédagogique de la Vulgate."),
    Q('th-nonfinita', 'JUD 1:13',
      target=('despumantes', 'v:part.praes.act.nom.pl.m'),
      dist=[
        ("des vagues furieuses de la mer, sur le point de rejeter l’écume de leurs impuretés; des astres errants, auxquels l’obscurité des ténèbres est réservée pour l’éternité.", 'despumantes', 'tempus', 'v:part.fut.act.nom.pl.m', "l’écume n’est pas encore rejetée"),
        ("des vagues furieuses de la mer, rejetant l’écume de leur impureté; des astres errants, auxquels l’obscurité des ténèbres est réservée pour l’éternité.", 'confusiones', 'numerus', 'n:acc.pl>n:acc.sg', "une seule impureté"),
        ("des vagues furieuses de la mer, rejetant l’écume de leurs impuretés; un astre errant, auquel l’obscurité des ténèbres est réservée pour l’éternité.", 'sidera', 'numerus', 'n:nom.pl>n:nom.sg', "un seul astre"),
      ]),
    Q('th-tempus-futurum', 'DEU 3:11',
      target=('restiterat', 'v:ind.plusq.act.3.sg'),
      la='Solus quippe Og rex Basan restiterat de stirpe gigantum.',
      paed=True, fr="Car seul Og, roi de Basan, était resté de la race des géants.",
      gloss={'Og': 'Og', 'Basan': 'Basan'},
      dist=[
        ("Car seul Og, roi de Basan, resta de la race des géants.", 'restiterat', 'tempus', 'v:ind.perf.act.3.sg', "le fait n’est plus antérieur au récit"),
        ("Car seul Og, roi de Basan, restait de la race des géants.", 'restiterat', 'tempus', 'v:ind.imperf.act.3.sg', "un fait accompli devient un état qui dure"),
        ("Car seul Og, roi de Basan, était resté de la race du géant.", 'gigantum', 'numerus', 'n:gen.pl>n:gen.sg', "un seul géant"),
      ],
      note="Segond garde l’hébreu « Rephaïm » pour « gigantum » ; rendu pédagogique de la première phrase."),
    Q('th-tempus-praeteritum', '1SA 19:10',
      target=('declinavit', 'v:ind.perf.act.3.sg'),
      dist=[
        ("David jouait, et Saül voulut le frapper avec sa lance contre la paroi. Mais David se détourne de lui, et Saül frappa de sa lance la paroi. David prit la fuite et s’échappa pendant la nuit.", 'declinavit', 'tempus', 'v:ind.praes.act.3.sg', "l’esquive est présentée comme actuelle"),
        ("David jouait, et Saül voulut le frapper avec sa lance contre la paroi. Mais David se détournera de lui, et Saül frappa de sa lance la paroi. David prit la fuite et s’échappa pendant la nuit.", 'declinavit', 'tempus', 'v:ind.fut.act.3.sg', "l’esquive est annoncée"),
        ("David jouait, et Saül voulut le frapper avec sa lance contre la paroi. Mais David se détournait de lui, et Saül frappa de sa lance la paroi. David prit la fuite et s’échappa pendant la nuit.", 'declinavit', 'tempus', 'v:ind.imperf.act.3.sg', "un geste ponctuel devient une action qui dure"),
      ],
      note="Segond ajoute « David jouait » et rend « casso vulnere perlata est in parietem » par « frappa de sa lance la paroi »."),
    Q('th-tempus-praeteritum', 'NEH 8:7',
      target=('stabat', 'v:ind.imperf.act.3.sg'),
      la='populus autem stabat in gradu suo.',
      paed=True, fr="et le peuple se tenait debout à sa place.",
      dist=[
        ("et le peuple se tint debout à sa place.", 'stabat', 'tempus', 'v:ind.perf.act.3.sg', "un état qui dure devient un fait ponctuel"),
        ("et le peuple se tient debout à sa place.", 'stabat', 'tempus', 'v:ind.praes.act.3.sg', "la station debout est actuelle"),
        ("et le peuple se tiendra debout à sa place.", 'stabat', 'tempus', 'v:ind.fut.act.3.sg', "la station debout est annoncée"),
      ],
      note="Segond rend « populus … stabat » par « chacun restait » ; la liste des noms est laissée hors du passage."),
    Q('th-tempus-futurum', 'LEV 25:30',
      target=('possidebit', 'v:ind.fut.act.3.sg'),
      paed=True, fr="S’il ne l’a pas rachetée et que le cycle d’une année se soit écoulé, l’acquéreur la possédera, lui et ses descendants, à perpétuité, et elle ne pourra pas être rachetée, même au jubilé.",
      dist=[
        ("S’il ne l’a pas rachetée et que le cycle d’une année se soit écoulé, l’acquéreur la possède, lui et ses descendants, à perpétuité, et elle ne pourra pas être rachetée, même au jubilé.", 'possidebit', 'tempus', 'v:ind.praes.act.3.sg', "la possession est actuelle"),
        ("S’il ne l’a pas rachetée et que le cycle d’une année se soit écoulé, l’acquéreur l’a possédée, lui et ses descendants, à perpétuité, et elle ne pourra pas être rachetée, même au jubilé.", 'possidebit', 'tempus', 'v:ind.perf.act.3.sg', "la possession est un fait passé"),
        ("S’il ne l’a pas rachetée et que le cycle d’une année se soit écoulé, l’acquéreur la possédera, lui et son descendant, à perpétuité, et elle ne pourra pas être rachetée, même au jubilé.", 'posteri', 'numerus', 'a:nom.pl.m>a:nom.sg.m', "un seul descendant"),
      ],
      note="Segond (« elle restera à perpétuité à l’acquéreur ») inverse sujet et objet ; rendu pédagogique."),
    Q('th-persona', 'DEU 9:25',
      target=('jacui', 'v:ind.perf.act.1.sg'),
      dist=[
        ("Il se prosterna devant l’Éternel, il se prosterna quarante jours et quarante nuits, parce que l’Éternel avait dit qu’il voulait vous détruire.", 'jacui', 'persona', 'v:ind.perf.act.3.sg', "Moïse ne parle plus de lui-même"),
        ("Tu te prosternas devant l’Éternel, tu te prosternas quarante jours et quarante nuits, parce que l’Éternel avait dit qu’il voulait vous détruire.", 'jacui', 'persona', 'v:ind.perf.act.2.sg', "l’acte est attribué à l’interlocuteur"),
        ("Nous nous prosternâmes devant l’Éternel, nous nous prosternâmes quarante jours et quarante nuits, parce que l’Éternel avait dit qu’il voulait vous détruire.", 'jacui', 'numerus', 'v:ind.perf.act.1.pl', "plusieurs intercesseurs au lieu de Moïse seul"),
      ],
      note="Segond répète « je me prosternai » (hébreu) et paraphrase « quibus eum suppliciter deprecabar, ne deleret vos ut fuerat comminatus »."),
    Q('th-modus-subiunctivus', 'HEB 9:15',
      target=('accipiant', 'v:subj.praes.act.3.pl'),
      dist=[
        ("Et c’est pour cela qu’il est le médiateur d’une nouvelle alliance, afin que, la mort étant intervenue pour le rachat des transgressions commises sous la première alliance, celui qui a été appelé reçoive l’héritage éternel qui lui a été promis.", 'accipiant', 'numerus', 'v:subj.praes.act.3.sg', "un seul appelé"),
        ("Et c’est pour cela qu’il est le médiateur d’une nouvelle alliance, afin que, la mort étant intervenue pour le rachat des transgressions commises sous la première alliance, ceux qui ont été appelés reçussent l’héritage éternel qui leur a été promis.", 'accipiant', 'tempus', 'v:subj.imperf.act.3.pl', "la finalité est rejetée dans le passé"),
        ("Et c’est pour cela qu’il est le médiateur de nouvelles alliances, afin que, la mort étant intervenue pour le rachat des transgressions commises sous la première alliance, ceux qui ont été appelés reçoivent l’héritage éternel qui leur a été promis.", 'testamenti', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs alliances"),
      ],
      note="Segond rend « repromissionem accipiant … æternæ hæreditatis » par « reçoivent l’héritage éternel qui leur a été promis »."),
    Q('th-tempus-praeteritum', 'MAR 6:21',
      target=('fecit', 'v:ind.perf.act.3.sg'),
      dist=[
        ("Cependant, un jour propice arriva, lorsque Hérode, à l’anniversaire de sa naissance, donne un festin à ses grands, aux chefs militaires et aux principaux de la Galilée.", 'fecit', 'tempus', 'v:ind.praes.act.3.sg', "le festin est présenté comme actuel"),
        ("Cependant, un jour propice arriva, lorsque Hérode, à l’anniversaire de sa naissance, donnera un festin à ses grands, aux chefs militaires et aux principaux de la Galilée.", 'fecit', 'tempus', 'v:ind.fut.act.3.sg', "le festin est annoncé"),
        ("Cependant, un jour propice arriva, lorsque Hérode, à l’anniversaire de sa naissance, donna un festin à ses grands, au chef militaire et aux principaux de la Galilée.", 'tribunis', 'numerus', 'n:dat.pl>n:dat.sg', "un seul chef militaire"),
      ],
      note="Segond rend « cum dies opportunus accidisset » par « un jour propice arriva, lorsque »."),
    Q('th-casus-obliqui', 'LAM 4:2',
      target=('figuli', 'n:gen.sg'),
      gloss={'Beth': 'beth (lettre hébraïque)'},
      dist=[
        ("Les nobles fils de Sion, Estimés à l’égal de l’or pur, Sont regardés, hélas! Comme des vases de terre, Ouvrage des mains pour le potier!", 'figuli', 'casus', 'n:dat.sg', "le potier devient le destinataire de l’ouvrage au lieu de son auteur"),
        ("Les nobles fils de Sion, Estimés à l’égal de l’or pur, Sont regardés, hélas! Comme des vases de terre, Ouvrage de la main du potier!", 'manuum', 'numerus', 'n:gen.pl>n:gen.sg', "une seule main"),
        ("Les nobles fils de Sion, Estimés à l’égal de l’or pur, Sont regardés, hélas! Comme un vase de terre, Ouvrage des mains du potier!", 'vasa', 'numerus', 'n:acc.pl>n:acc.sg', "un seul vase"),
      ],
      note="Segond rend « amicti auro primo » par « Estimés à l’égal de l’or pur » et « reputati sunt » par un présent."),
    Q('th-tempus-futurum', 'ISA 11:8',
      target=('mittet', 'v:ind.fut.act.3.sg'),
      dist=[
        ("Le nourrisson s’ébattra sur l’antre de la vipère, Et l’enfant sevré met sa main dans la caverne du basilic.", 'mittet', 'tempus', 'v:ind.praes.act.3.sg', "le geste de l’enfant est actuel"),
        ("Le nourrisson s’ébattra sur l’antre de la vipère, Et l’enfant sevré a mis sa main dans la caverne du basilic.", 'mittet', 'tempus', 'v:ind.perf.act.3.sg', "le geste de l’enfant est un fait passé"),
        ("Le nourrisson s’ébattra sur l’antre de la vipère, Et l’enfant sevré mettra ses mains dans la caverne du basilic.", 'manum', 'numerus', 'n:acc.sg>n:acc.pl', "les deux mains"),
      ],
      note="Segond ne rend pas « ab ubere » ; « delectabitur » (déponent au futur) est traduit « s’ébattra »."),
    Q('th-persona', 'EZE 34:18',
      target=('conculcastis', 'v:ind.perf.act.2.pl'),
      paed=True, fr="N’était-ce pas assez pour vous de paître de bons pâturages ? Vous avez encore foulé de vos pieds le reste de vos pâturages, et, quand vous buviez l’eau la plus pure, vous troubliez de vos pieds ce qui restait.",
      dist=[
        ("N’était-ce pas assez pour vous de paître de bons pâturages ? Ils ont encore foulé de leurs pieds le reste de vos pâturages, et, quand vous buviez l’eau la plus pure, vous troubliez de vos pieds ce qui restait.", 'conculcastis', 'persona', 'v:ind.perf.act.3.pl', "le piétinement est attribué à des tiers"),
        ("N’était-ce pas assez pour vous de paître de bons pâturages ? Tu as encore foulé de tes pieds le reste de tes pâturages, et, quand vous buviez l’eau la plus pure, vous troubliez de vos pieds ce qui restait.", 'conculcastis', 'numerus', 'v:ind.perf.act.2.sg', "un seul coupable"),
        ("N’était-ce pas assez pour vous de paître de bons pâturages ? Vous avez encore foulé de votre pied le reste de vos pâturages, et, quand vous buviez l’eau la plus pure, vous troubliez de vos pieds ce qui restait.", 'pedibus', 'numerus', 'n:abl.pl>n:abl.sg', "un seul pied"),
      ],
      note="Segond rend le parfait et l’imparfait latins par des subjonctifs (« pour que vous fouliez … troubliez ») ; rendu pédagogique."),
]
