# sheet_012 → batch_012
# skipped: 1CH 1:37 (list of names, no verb)
# skipped: 1CH 11:32 (list of names, no verb or declined common word)
# skipped: 2SA 23:36 (list of names, no verb)
# skipped: EXO 6:15 (list of names; Segond renders «hæ cognationes Ruben» in the previous verse, not enough declined words for three misreadings)
# skipped: NEH 12:17 (list of names, no verb)
ITEMS = [
    Q('th-tempus-praeteritum', 'JER 8:7',
      target=('custodierunt', 'v:ind.perf.act.3.pl'),
      paed=True, fr="Le milan dans le ciel a connu son temps; la tourterelle, l’hirondelle et la cigogne ont gardé le temps de leur venue; mais mon peuple n’a pas connu le jugement du Seigneur.",
      dist=[
        ("Le milan dans le ciel a connu son temps; la tourterelle, l’hirondelle et la cigogne gardent le temps de leur venue; mais mon peuple n’a pas connu le jugement du Seigneur.", 'custodierunt', 'tempus', 'v:ind.praes.act.3.pl', "l’observation des oiseaux est présentée comme actuelle"),
        ("Le milan dans le ciel a connu son temps; la tourterelle, l’hirondelle et la cigogne garderont le temps de leur venue; mais mon peuple n’a pas connu le jugement du Seigneur.", 'custodierunt', 'tempus', 'v:ind.fut.act.3.pl', "l’observation des oiseaux est annoncée"),
        ("Le milan dans le ciel a connu son temps; la tourterelle, l’hirondelle et la cigogne ont gardé le temps de leur venue; mais mon peuple ne connaît pas le jugement du Seigneur.", 'non cognovit', 'tempus', 'v:ind.perf.act.3.sg>v:ind.praes.act.3.sg', "l’ignorance du peuple est actuelle au lieu d’être constatée"),
      ],
      note="Segond a le présent (« connaît », « observent ») pour les parfaits latins et « cigogne… grue » pour milvus… ciconia ; rendu pédagogique."),
    Q('th-tempus-futurum', 'SIR 38:29',
      target=('uret', 'v:ind.fut.act.3.sg'),
      paed=True, fr="Ainsi le forgeron assis près de l’enclume et considérant l’ouvrage du fer: la vapeur du feu brûlera ses chairs, et il lutte contre la chaleur de la fournaise.",
      dist=[
        ("Ainsi le forgeron assis près de l’enclume et considérant l’ouvrage du fer: la vapeur du feu brûle ses chairs, et il lutte contre la chaleur de la fournaise.", 'uret', 'tempus', 'v:ind.praes.act.3.sg', "la brûlure est actuelle au lieu d’être envisagée"),
        ("Ainsi le forgeron assis près de l’enclume et considérant l’ouvrage du fer: la vapeur du feu brûla ses chairs, et il lutte contre la chaleur de la fournaise.", 'uret', 'tempus', 'v:ind.perf.act.3.sg', "la brûlure devient un fait passé"),
        ("Ainsi le forgeron assis près de l’enclume et considérant l’ouvrage du fer: la vapeur du feu brûlera sa chair, et il lutte contre la chaleur de la fournaise.", 'carnes', 'numerus', 'n:acc.pl>n:acc.sg', "une seule chair"),
      ],
      note="Livre absent de Segond ; rendu pédagogique (concertatur, déponent, rendu par « il lutte »)."),
    Q('th-tempus-futurum', 'SIR 43:32',
      target=('supervalebit', 'v:ind.fut.act.3.sg'),
      paed=True, fr="Vous qui glorifiez le Seigneur autant que vous pourrez, il sera encore au-dessus; et sa magnificence est admirable.",
      dist=[
        ("Vous qui glorifiez le Seigneur autant que vous pourrez, il est encore au-dessus; et sa magnificence est admirable.", 'supervalebit', 'tempus', 'v:ind.praes.act.3.sg', "la supériorité est constatée au lieu d’être promise"),
        ("Vous qui glorifiez le Seigneur autant que vous pourrez, il fut encore au-dessus; et sa magnificence est admirable.", 'supervalebit', 'tempus', 'v:ind.perf.act.3.sg', "la supériorité devient un fait passé"),
        ("Vous qui glorifiez le Seigneur autant que vous pourrez, il sera encore au-dessus; et ses magnificences sont admirables.", 'magnificentia', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs magnificences"),
      ],
      note="Livre absent de Segond ; rendu pédagogique (Glorificantes, nominatif pluriel, rendu par « Vous qui glorifiez »)."),
    Q('th-tempus-praeteritum', '1SA 14:3',
      target=('portabat', 'v:ind.imperf.act.3.sg'),
      gloss={'Achias': 'Achija', 'Ichabod': 'I-Kabod', 'isset': 's’en fût allé (plus-que-parfait du subjonctif de eo, aller)'},
      dist=[
        ("Achija, fils d’Achithub, frère d’I-Kabod, fils de Phinées, fils d’Éli, sacrificateur de l’Éternel à Silo, porta l’éphod. Le peuple ne savait pas que Jonathan s’en fût allé.", 'portabat', 'tempus', 'v:ind.perf.act.3.sg', "un port habituel devient un fait ponctuel"),
        ("Achija, fils d’Achithub, frère d’I-Kabod, fils de Phinées, fils d’Éli, sacrificateur de l’Éternel à Silo, porte l’éphod. Le peuple ne savait pas que Jonathan s’en fût allé.", 'portabat', 'tempus', 'v:ind.praes.act.3.sg', "le port de l’éphod est actuel"),
        ("Achija, fils d’Achithub, frère d’I-Kabod, fils de Phinées, fils d’Éli, sacrificateur de l’Éternel à Silo, portait l’éphod. Les peuples ne savaient pas que Jonathan s’en fût allé.", 'populus', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs peuples"),
      ],
      note="Segond rend « qui ortus fuerat ex Heli » par « fils d’Éli » ; la cible est portabat."),
    Q('th-vox', 'WIS 17:14',
      target=('exagitabantur', 'v:ind.imperf.pass.3.pl'),
      paed=True, fr="tantôt ils étaient tourmentés par la peur des monstres, tantôt leurs âmes défaillaient devant le passage des apparitions; car une frayeur subite et inattendue leur était survenue.",
      dist=[
        ("tantôt ils tourmentaient par la peur des monstres, tantôt leurs âmes défaillaient devant le passage des apparitions; car une frayeur subite et inattendue leur était survenue.", 'exagitabantur', 'vox', 'v:ind.imperf.act.3.pl', "les Égyptiens deviennent ceux qui tourmentent au lieu d’être tourmentés"),
        ("tantôt ils sont tourmentés par la peur des monstres, tantôt leurs âmes défaillaient devant le passage des apparitions; car une frayeur subite et inattendue leur était survenue.", 'exagitabantur', 'tempus', 'v:ind.praes.pass.3.pl', "le tourment est actuel"),
        ("tantôt ils étaient tourmentés par la peur des monstres, tantôt leurs âmes défaillaient devant le passage des apparitions; car une frayeur subite et inattendue leur survint.", 'supervenerat', 'tempus', 'v:ind.plusq.act.3.sg>v:ind.perf.act.3.sg', "la frayeur n’est plus antérieure au tourment"),
      ],
      note="Livre absent de Segond ; rendu pédagogique (traductione : passage, défilé des apparitions)."),
    Q('th-numerus', 'DEU 14:5',
      target=('cervum', 'n:acc.sg'),
      gloss={'orygem': 'oryx (antilope du désert)'},
      dist=[
        ("les cerfs, la gazelle et le daim; le bouquetin, le chevreuil, la chèvre sauvage et la girafe.", 'cervum', 'numerus', 'n:acc.pl', "plusieurs cerfs"),
        ("le cerf, les gazelles et le daim; le bouquetin, le chevreuil, la chèvre sauvage et la girafe.", 'capream', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs gazelles"),
        ("le cerf, la gazelle et le daim; le bouquetin, le chevreuil, la chèvre sauvage et les girafes.", 'camelopardalum', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs girafes"),
      ],
      note="Liste d’accusatifs singuliers (objets de « comedetis », v. 4) ; Segond suit l’hébreu pour les espèces intermédiaires."),
    Q('th-vox', 'PRO 24:10',
      target=('imminuetur', 'v:ind.fut.pass.3.sg'),
      paed=True, fr="Si, épuisé, tu désespères au jour de l’angoisse, ta force sera affaiblie.",
      dist=[
        ("Si, épuisé, tu désespères au jour de l’angoisse, ta force affaiblira.", 'imminuetur', 'vox', 'v:ind.fut.act.3.sg', "la force devient ce qui affaiblit au lieu d’être affaiblie"),
        ("Si, épuisé, tu désespères au jour de l’angoisse, ta force est affaiblie.", 'imminuetur', 'tempus', 'v:ind.praes.pass.3.sg', "l’affaiblissement est actuel au lieu d’être la conséquence annoncée"),
        ("Si, épuisé, tu désespères au jour de l’angoisse, tes forces seront affaiblies.", 'fortitudo', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs forces"),
      ],
      note="Segond (« Ta force n’est que détresse ») ne rend pas le futur passif imminuetur ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'WIS 18:22',
      target=('Vicit', 'v:ind.perf.act.3.sg'),
      paed=True, fr="Or il vainquit les foules non par la force du corps ni par la puissance des armes, mais par la parole il soumit celui qui le tourmentait, en rappelant les serments des pères et l’alliance.",
      gloss={'armaturæ': 'armure, armes', 'parentum': 'parents, pères'},
      dist=[
        ("Or il vainc les foules non par la force du corps ni par la puissance des armes, mais par la parole il soumit celui qui le tourmentait, en rappelant les serments des pères et l’alliance.", 'Vicit', 'tempus', 'v:ind.praes.act.3.sg', "la victoire est présentée comme actuelle"),
        ("Or il vaincra les foules non par la force du corps ni par la puissance des armes, mais par la parole il soumit celui qui le tourmentait, en rappelant les serments des pères et l’alliance.", 'Vicit', 'tempus', 'v:ind.fut.act.3.sg', "la victoire est annoncée au lieu d’être racontée"),
        ("Or il vainquit la foule non par la force du corps ni par la puissance des armes, mais par la parole il soumit celui qui le tourmentait, en rappelant les serments des pères et l’alliance.", 'turbas', 'numerus', 'n:acc.pl>n:acc.sg', "une seule foule"),
      ],
      note="Livre absent de Segond ; rendu pédagogique. « armaturæ » et « parentum » sont les noms armatura et parens, non les verbes armo et pareo."),
    Q('th-numerus', 'NUM 10:12',
      target=('recubuit', 'v:ind.perf.act.3.sg'),
      dist=[
        ("Et les enfants d’Israël partirent du désert de Sinaï, selon l’ordre fixé pour leur marche. Les nuées s’arrêtèrent dans le désert de Paran.", 'recubuit', 'numerus', 'v:ind.perf.act.3.pl', "plusieurs nuées au lieu de la nuée unique"),
        ("Et l’enfant d’Israël partit du désert de Sinaï, selon l’ordre fixé pour leur marche. La nuée s’arrêta dans le désert de Paran.", 'filii', 'numerus', 'n:nom.pl>n:nom.sg', "un seul Israélite au lieu du peuple"),
        ("Et les enfants d’Israël partirent du désert de Sinaï, selon l’ordre fixé pour leur marche. La nuée s’arrêta dans les déserts de Paran.", 'solitudine', 'numerus', 'n:abl.sg>n:abl.pl', "plusieurs déserts"),
      ],
      note="Segond rend « per turmas suas » par « selon l’ordre fixé pour leur marche »."),
    Q('th-tempus-praeteritum', 'EXO 9:32',
      target=('erant', 'v:ind.imperf.act.3.pl'),
      paed=True, fr="mais le froment et l’épeautre ne furent pas frappés, parce qu’ils étaient tardifs.",
      dist=[
        ("mais le froment et l’épeautre ne furent pas frappés, parce qu’ils sont tardifs.", 'erant', 'tempus', 'v:ind.praes.act.3.pl', "la maturité tardive est présentée comme une vérité actuelle"),
        ("mais le froment et l’épeautre ne furent pas frappés, parce qu’ils furent tardifs.", 'erant', 'tempus', 'v:ind.perf.act.3.pl', "un état durable devient un fait ponctuel"),
        ("mais le froment et l’épeautre ne furent pas frappés, parce qu’il était tardif.", 'erant', 'numerus', 'v:ind.imperf.act.3.sg', "une seule des deux céréales est tardive"),
      ],
      note="Segond a le plus-que-parfait (« n’avaient point été frappés ») et le présent (« ils sont tardifs ») ; rendu pédagogique."),
    Q('th-numerus', 'HEB 6:17',
      target=('hæredibus', 'n:dat.pl'),
      gloss={'jusjurandum': 'serment'},
      dist=[
        ("C’est pourquoi Dieu, voulant montrer avec plus d’évidence à l’héritier de la promesse l’immuabilité de sa résolution, intervint par un serment,", 'hæredibus', 'numerus', 'n:dat.sg', "un seul héritier"),
        ("C’est pourquoi Dieu, voulant montrer avec plus d’évidence aux héritiers de la promesse l’immuabilité de ses résolutions, intervint par un serment,", 'consilii', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs résolutions"),
        ("C’est pourquoi Dieu, voulant montrer avec plus d’évidence aux héritiers de la promesse l’immuabilité de sa résolution, intervint par des serments,", 'jusjurandum', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs serments"),
      ],
      note="Segond rend « interposuit jusjurandum » par « intervint par un serment »."),
    Q('th-tempus-praeteritum', 'DEU 23:1',
      target=('intravit', 'v:ind.perf.act.3.sg'),
      paed=True, fr="L’eunuque, aux testicules écrasés ou coupés et à la verge tranchée, n’est pas entré dans l’assemblée du Seigneur.",
      dist=[
        ("L’eunuque, aux testicules écrasés ou coupés et à la verge tranchée, n’entrera pas dans l’assemblée du Seigneur.", 'intravit', 'tempus', 'v:ind.fut.act.3.sg', "un fait constaté devient une interdiction à venir"),
        ("L’eunuque, aux testicules écrasés ou coupés et à la verge tranchée, n’entre pas dans l’assemblée du Seigneur.", 'intravit', 'tempus', 'v:ind.praes.act.3.sg', "l’exclusion est présentée comme une règle actuelle"),
        ("Les eunuques, aux testicules écrasés ou coupés et à la verge tranchée, ne sont pas entrés dans l’assemblée du Seigneur.", 'eunuchus', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs eunuques"),
      ],
      note="Segond a le futur (« n’entrera point ») pour le parfait gnomique latin ; rendu pédagogique."),
    Q('th-numerus', 'LEV 3:15',
      target=('renunculis', 'n:abl.pl', 'renunculus'),
      dist=[
        ("les deux rognons, et la graisse qui les entoure, qui couvre les flancs, et le grand lobe du foie, qu’il détachera près du rognon.", 'renunculis', 'numerus', 'n:abl.sg', "un seul rognon"),
        ("les deux rognons, et la graisse qui l’entoure, qui couvre les flancs, et le grand lobe du foie, qu’il détachera près des rognons.", 'eos', 'numerus', 'a:acc.pl.m>a:acc.sg.m', "la graisse n’entoure qu’un rognon"),
        ("les deux rognons, et la graisse qui les entoure, qui couvre les flancs, et le grand lobe des foies, qu’il détachera près des rognons.", 'jecoris', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs foies"),
      ],
      note="Segond ajoute « qu’il détachera » et rend « reticulo » par « la graisse »."),
    Q('th-modus-subiunctivus', 'GEN 36:38',
      target=('obiisset', 'v:subj.plusq.act.3.sg'),
      paed=True, fr="Et lorsque celui-ci aussi fut mort, Baal-Hanan, fils d’Acbor, lui succéda dans la royauté.",
      dist=[
        ("Et lorsque celui-ci aussi était mort, Baal-Hanan, fils d’Acbor, lui succéda dans la royauté.", 'obiisset', 'modus', 'v:ind.plusq.act.3.sg', "la circonstance narrative devient un simple repère temporel"),
        ("Et lorsque celui-ci aussi mourait, Baal-Hanan, fils d’Acbor, lui succéda dans la royauté.", 'obiisset', 'tempus', 'v:subj.imperf.act.3.sg', "la mort est en cours au lieu d’être achevée"),
        ("Et lorsque ceux-ci aussi furent morts, Baal-Hanan, fils d’Acbor, lui succéda dans la royauté.", 'obiisset', 'numerus', 'v:subj.plusq.act.3.pl', "plusieurs morts"),
      ],
      note="Segond explicite le sujet (« Saül mourut ») et coordonne ; rendu pédagogique du cum historicum."),
    Q('th-tempus-praeteritum', 'DAN 3:23',
      target=('ceciderunt', 'v:ind.perf.act.3.pl'),
      gloss={'Sidrach': 'Schadrac'},
      dist=[
        ("Et ces trois hommes, Schadrac, Méschac et Abed-Nego, tombent liés au milieu de la fournaise ardente.", 'ceciderunt', 'tempus', 'v:ind.praes.act.3.pl', "la chute est actuelle"),
        ("Et ces trois hommes, Schadrac, Méschac et Abed-Nego, tomberont liés au milieu de la fournaise ardente.", 'ceciderunt', 'tempus', 'v:ind.fut.act.3.pl', "la chute est annoncée"),
        ("Et ces trois hommes, Schadrac, Méschac et Abed-Nego, tombèrent liés au milieu des fournaises ardentes.", 'camino', 'numerus', 'n:abl.sg>n:abl.pl', "plusieurs fournaises"),
      ],
      note="Segond rend « id est » par une simple apposition."),
    Q('th-tempus-praeteritum', 'JDG 5:15',
      target=('fuere', 'v:ind.perf.act.3.pl'),
      la='Duces Issachar fuere cum Debbora',
      fr='Les princes d’Issacar furent avec Débora',
      dist=[
        ("Les princes d’Issacar sont avec Débora", 'fuere', 'tempus', 'v:ind.praes.act.3.pl', "la présence des princes est actuelle"),
        ("Les princes d’Issacar seront avec Débora", 'fuere', 'tempus', 'v:ind.fut.act.3.pl', "la présence des princes est annoncée"),
        ("Le prince d’Issacar fut avec Débora", 'Duces', 'numerus', 'n:nom.pl>n:nom.sg', "un seul prince"),
      ],
      note="La suite du verset diverge fortement entre Vulgate et Segond ; la première clause est retenue (fuere = fuerunt)."),
    Q('th-tempus-praeteritum', 'EXO 8:14',
      target=('computruit', 'v:ind.perf.act.3.sg'),
      fr_ref='EXO 8:10',
      dist=[
        ("On les entassa par monceaux, et le pays est infecté.", 'computruit', 'tempus', 'v:ind.praes.act.3.sg', "l’infection est actuelle"),
        ("On les entassa par monceaux, et le pays sera infecté.", 'computruit', 'tempus', 'v:ind.fut.act.3.sg', "l’infection est annoncée"),
        ("On les entassa par monceaux, et les pays furent infectés.", 'terra', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs pays"),
      ],
      note="Décalage de numérotation : Vulgate EXO 8:14 = Segond 8:10. Segond a l’impersonnel « on » pour Congregaveruntque ; la cible est computruit."),
    Q('th-tempus-praeteritum', '2MA 14:43',
      target=('præcipitavit', 'v:ind.perf.act.3.sg'),
      paed=True, fr="Mais comme, dans sa hâte, il ne s’était pas donné le coup d’une main sûre, et que les foules se ruaient à l’intérieur des portes, courant hardiment au mur, il se précipita lui-même virilement sur les foules.",
      dist=[
        ("Mais comme, dans sa hâte, il ne s’était pas donné le coup d’une main sûre, et que les foules se ruaient à l’intérieur des portes, courant hardiment au mur, il se précipite lui-même virilement sur les foules.", 'præcipitavit', 'tempus', 'v:ind.praes.act.3.sg', "le saut est présenté comme actuel"),
        ("Mais comme, dans sa hâte, il ne s’était pas donné le coup d’une main sûre, et que les foules se ruaient à l’intérieur des portes, courant hardiment au mur, il se précipitera lui-même virilement sur les foules.", 'præcipitavit', 'tempus', 'v:ind.fut.act.3.sg', "le saut est annoncé"),
        ("Mais comme, dans sa hâte, il ne s’était pas donné le coup d’une main sûre, et que les foules se ruaient à l’intérieur des portes, courant hardiment au mur, il se précipita lui-même virilement sur la foule.", 'turbas', 'numerus', 'n:acc.pl>n:acc.sg', "une seule foule"),
      ],
      note="Livre absent de Segond ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'JER 46:21',
      target=('fugerunt', 'v:ind.perf.act.3.pl'),
      paed=True, fr="Ses mercenaires aussi, qui se trouvaient au milieu d’elle comme des veaux engraissés, ont tourné le dos et ont fui ensemble, et ils n’ont pu tenir; car le jour de leur massacre est venu sur eux, le temps de leur visite.",
      dist=[
        ("Ses mercenaires aussi, qui se trouvaient au milieu d’elle comme des veaux engraissés, ont tourné le dos et fuient ensemble, et ils n’ont pu tenir; car le jour de leur massacre est venu sur eux, le temps de leur visite.", 'fugerunt', 'tempus', 'v:ind.praes.act.3.pl', "la fuite est actuelle"),
        ("Ses mercenaires aussi, qui se trouvaient au milieu d’elle comme des veaux engraissés, ont tourné le dos et fuiront ensemble, et ils n’ont pu tenir; car le jour de leur massacre est venu sur eux, le temps de leur visite.", 'fugerunt', 'tempus', 'v:ind.fut.act.3.pl', "la fuite est annoncée"),
        ("Ses mercenaires aussi, qui se trouvaient au milieu d’elle comme un veau engraissé, ont tourné le dos et ont fui ensemble, et ils n’ont pu tenir; car le jour de leur massacre est venu sur eux, le temps de leur visite.", 'vituli', 'numerus', 'n:nom.pl>n:nom.sg', "un seul veau"),
      ],
      note="Segond a le présent (« sont », « tournent le dos », « fuient ») pour les parfaits latins ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'JOB 39:3',
      target=('pariunt', 'v:ind.praes.act.3.pl'),
      fr_ref='JOB 39:6',
      dist=[
        ("Elles se courbent, laissèrent échapper leur progéniture, Et sont délivrées de leurs douleurs.", 'pariunt', 'tempus', 'v:ind.perf.act.3.pl', "la mise bas devient un fait passé"),
        ("Elles se courbent, laisseront échapper leur progéniture, Et sont délivrées de leurs douleurs.", 'pariunt', 'tempus', 'v:ind.fut.act.3.pl', "la mise bas est annoncée"),
        ("Elles se courbaient, laissent échapper leur progéniture, Et sont délivrées de leurs douleurs.", 'Incurvantur', 'tempus', 'v:ind.praes.pass.3.pl>v:ind.imperf.pass.3.pl', "l’accroupissement est rejeté dans le passé"),
      ],
      note="Décalage de numérotation : Vulgate JOB 39:3 = Segond 39:6. Segond rend « rugitus emittunt » par « sont délivrées de leurs douleurs » d’après l’hébreu ; la cible est pariunt."),
    Q('th-tempus-futurum', 'LUK 11:12',
      target=('porriget', 'v:ind.fut.act.3.sg'),
      dist=[
        ("Ou, s’il demande un œuf, lui donne-t-il un scorpion?", 'porriget', 'tempus', 'v:ind.praes.act.3.sg', "le don est présenté comme actuel"),
        ("Ou, s’il demande un œuf, lui donna-t-il un scorpion?", 'porriget', 'tempus', 'v:ind.perf.act.3.sg', "le don devient un fait passé"),
        ("Ou, s’il demande un œuf, leur donnera-t-il un scorpion?", 'illi', 'numerus', 'a:dat.sg.m>a:dat.pl.m', "plusieurs destinataires"),
      ]),
    Q('th-tempus-futurum', '2MA 12:6',
      target=('refugerant', 'v:ind.plusq.act.3.pl'),
      paed=True, fr="il vint contre les meurtriers de ses frères, et il incendia le port pendant la nuit, brûla les barques, et ceux qui avaient échappé au feu, il les fit périr par l’épée.",
      dist=[
        ("il vint contre les meurtriers de ses frères, et il incendia le port pendant la nuit, brûla les barques, et ceux qui échappaient au feu, il les fit périr par l’épée.", 'refugerant', 'tempus', 'v:ind.imperf.act.3.pl', "la fuite est en cours au lieu d’être antérieure"),
        ("il vint contre les meurtriers de ses frères, et il incendia le port pendant la nuit, brûla les barques, et ceux qui échappèrent au feu, il les fit périr par l’épée.", 'refugerant', 'tempus', 'v:ind.perf.act.3.pl', "l’antériorité de la fuite disparaît"),
        ("il vint contre les meurtriers de ses frères, et il incendia le port pendant la nuit, brûla la barque, et ceux qui avaient échappé au feu, il les fit périr par l’épée.", 'scaphas', 'numerus', 'n:acc.pl>n:acc.sg', "une seule barque"),
      ],
      note="Livre absent de Segond ; rendu pédagogique."),
    Q('th-tempus-praeteritum', '1CH 9:16',
      target=('habitavit', 'v:ind.perf.act.3.sg'),
      la='qui habitavit in atriis Netophati',
      paed=True, fr="qui habita dans les villages des Nethophathiens",
      gloss={'Netophati': 'Nethopha (les Nethophathiens)'},
      dist=[
        ("qui habite dans les villages des Nethophathiens", 'habitavit', 'tempus', 'v:ind.praes.act.3.sg', "le séjour est actuel"),
        ("qui habitait dans les villages des Nethophathiens", 'habitavit', 'tempus', 'v:ind.imperf.act.3.sg', "un séjour achevé devient un état qui dure"),
        ("qui habita dans le village des Nethophathiens", 'atriis', 'numerus', 'n:abl.pl>n:abl.sg', "un seul village"),
      ],
      note="Segond a l’imparfait (« habitait ») pour le parfait latin ; rendu pédagogique de la relative, le reste du verset étant une liste de noms."),
    Q('th-tempus-praeteritum', 'HEB 11:4',
      target=('obtulit', 'v:ind.perf.act.3.sg'),
      dist=[
        ("C’est par la foi qu’Abel offre à Dieu un sacrifice plus excellent que celui de Caïn; c’est par elle qu’il fut déclaré juste, Dieu approuvant ses offrandes; et c’est par elle qu’il parle encore, quoique mort.", 'obtulit', 'tempus', 'v:ind.praes.act.3.sg', "l’offrande est actuelle"),
        ("C’est par la foi qu’Abel offrira à Dieu un sacrifice plus excellent que celui de Caïn; c’est par elle qu’il fut déclaré juste, Dieu approuvant ses offrandes; et c’est par elle qu’il parle encore, quoique mort.", 'obtulit', 'tempus', 'v:ind.fut.act.3.sg', "l’offrande est annoncée"),
        ("C’est par la foi qu’Abel offrit à Dieu un sacrifice plus excellent que celui de Caïn; c’est par elle qu’il fut déclaré juste, Dieu approuvant ses offrandes; et c’est par elle qu’il parlait encore, quoique mort.", 'loquitur', 'tempus', 'v:ind.praes.act.3.sg>v:ind.imperf.act.3.sg', "la parole d’Abel cesse d’être actuelle"),
      ],
      note="Segond rend « testimonium consecutus est esse justus » par « il fut déclaré juste »."),
    Q('th-numerus', 'MAR 14:65',
      target=('cœperunt', 'v:ind.perf.act.3.pl'),
      dist=[
        ("Et quelqu’un se mit à cracher sur lui, à lui voiler le visage et à le frapper à coups de poing, en lui disant: Devine! Et les serviteurs le reçurent en lui donnant des soufflets.", 'cœperunt', 'numerus', 'v:ind.perf.act.3.sg', "un seul agresseur"),
        ("Et quelques-uns se mirent à cracher sur lui, à lui voiler le visage et à le frapper à coups de poing, en lui disant: Devine! Et le serviteur le reçut en lui donnant des soufflets.", 'ministri', 'numerus', 'n:nom.pl>n:nom.sg', "un seul serviteur"),
        ("Et quelques-uns se mirent à cracher sur lui, à lui voiler le visage et à le frapper à coups de poing, en lui disant: Devine! Et les serviteurs le reçurent en lui donnant un soufflet.", 'alapis', 'numerus', 'n:abl.pl>n:abl.sg', "un seul soufflet"),
      ],
      note="Segond rend « Prophetiza » par « Devine ! » et « alapis eum cædebant » par « le reçurent en lui donnant des soufflets »."),
    Q('th-tempus-praeteritum', 'ACT 25:13',
      target=('descenderunt', 'v:ind.perf.act.3.pl'),
      dist=[
        ("Quelques jours après, le roi Agrippa et Bérénice arrivent à Césarée, pour saluer Festus.", 'descenderunt', 'tempus', 'v:ind.praes.act.3.pl', "l’arrivée est actuelle"),
        ("Quelques jours après, le roi Agrippa et Bérénice arriveront à Césarée, pour saluer Festus.", 'descenderunt', 'tempus', 'v:ind.fut.act.3.pl', "l’arrivée est annoncée"),
        ("Quelques jours après, le roi Agrippa et Bérénice étaient arrivés à Césarée, pour saluer Festus.", 'descenderunt', 'tempus', 'v:ind.plusq.act.3.pl', "l’arrivée est antérieure au récit"),
      ],
      note="Segond rend la proposition « cum dies aliquot transacti essent » par « Quelques jours après » et « descenderunt » par « arrivèrent »."),
    Q('th-persona', 'ISA 41:12',
      target=('Quæres', 'v:ind.fut.act.2.sg'),
      dist=[
        ("Il les cherchera, et ne les trouvera plus, Ceux qui te suscitaient querelle; Ils seront réduits à rien, réduits au néant, Ceux qui te faisaient la guerre.", 'Quæres', 'persona', 'v:ind.fut.act.3.sg', "un tiers cherche au lieu d’Israël"),
        ("Je les chercherai, et ne les trouverai plus, Ceux qui te suscitaient querelle; Ils seront réduits à rien, réduits au néant, Ceux qui te faisaient la guerre.", 'Quæres', 'persona', 'v:ind.fut.act.1.sg', "Dieu s’attribue la recherche"),
        ("Vous les chercherez, et ne les trouverez plus, Ceux qui te suscitaient querelle; Ils seront réduits à rien, réduits au néant, Ceux qui te faisaient la guerre.", 'Quæres', 'numerus', 'v:ind.fut.act.2.pl', "plusieurs chercheurs au lieu d’Israël seul"),
      ],
      note="Segond rend « viros rebelles tuos » par « Ceux qui te suscitaient querelle » ; la cible est Quæres."),
    Q('th-numerus', '1PE 1:11',
      target=('glorias', 'n:acc.pl'),
      paed=True, fr="scrutant quel temps ou quelles circonstances leur indiquait l’Esprit de Christ, qui annonçait d’avance les souffrances qui sont en Christ et les gloires qui les suivent:",
      dist=[
        ("scrutant quel temps ou quelles circonstances leur indiquait l’Esprit de Christ, qui annonçait d’avance les souffrances qui sont en Christ et la gloire qui les suit:", 'glorias', 'numerus', 'n:acc.sg', "une seule gloire"),
        ("scrutant quel temps ou quelles circonstances leur indiquait l’Esprit de Christ, qui annonçait d’avance la souffrance qui est en Christ et les gloires qui la suivent:", 'passiones', 'numerus', 'n:acc.pl>n:acc.sg', "une seule souffrance"),
        ("scrutant quel temps ou quelles circonstances lui indiquait l’Esprit de Christ, qui annonçait d’avance les souffrances qui sont en Christ et les gloires qui les suivent:", 'eis', 'numerus', 'a:abl.pl.m>a:abl.sg.m', "un seul prophète au lieu de tous"),
      ],
      note="Segond restructure le verset (« la gloire dont elles seraient suivies ») ; rendu pédagogique gardant le pluriel glorias."),
    Q('th-modus-subiunctivus', 'JOB 3:6',
      target=('numeretur', 'v:subj.praes.pass.3.sg'),
      dist=[
        ("Cette nuit! Que les ténèbres en fassent leur proie, Qu’elle disparaisse de l’année, Elle n’est plus comptée parmi les mois!", 'numeretur', 'modus', 'v:ind.praes.pass.3.sg', "un souhait devient un constat"),
        ("Cette nuit! Que les ténèbres en fassent leur proie, Qu’elle disparaisse de l’année, Qu’elles ne soient plus comptées parmi les mois!", 'numeretur', 'numerus', 'v:subj.praes.pass.3.pl', "plusieurs nuits maudites"),
        ("Cette nuit! Que les ténèbres en fassent leur proie, Qu’elle disparaisse de l’année, Qu’elle ne soit plus comptée parmi le mois!", 'mensibus', 'numerus', 'n:abl.pl>n:abl.sg', "un seul mois"),
      ],
      note="Segond a le pluriel « les ténèbres » pour « tenebrosus turbo » (possideat) ; la cible est numeretur, rendu « ne soit plus comptée »."),
    Q('th-tempus-futurum', 'PRO 3:34',
      target=('dabit', 'v:ind.fut.act.3.sg'),
      paed=True, fr="Lui, il se moquera des moqueurs, et il donnera sa grâce aux doux.",
      dist=[
        ("Lui, il se moquera des moqueurs, et il donne sa grâce aux doux.", 'dabit', 'tempus', 'v:ind.praes.act.3.sg', "la grâce est accordée maintenant au lieu d’être promise"),
        ("Lui, il se moquera des moqueurs, et il donna sa grâce aux doux.", 'dabit', 'tempus', 'v:ind.perf.act.3.sg', "la grâce devient un fait passé"),
        ("Lui, il se moquera du moqueur, et il donnera sa grâce aux doux.", 'illusores', 'numerus', 'n:acc.pl>n:acc.sg', "un seul moqueur"),
      ],
      note="Segond a le présent (« se moque », « fait grâce ») pour les futurs latins ; rendu pédagogique."),
    Q('th-vox', 'ISA 33:1',
      target=('deprædaberis', 'v:ind.fut.pass.2.sg'),
      la='Cum consummaveris deprædationem, deprædaberis',
      fr='Quand tu auras fini de ravager, tu seras ravagé',
      dist=[
        ("Quand tu auras fini de ravager, tu ravageras", 'deprædaberis', 'vox', 'v:ind.fut.act.2.sg', "le ravageur reste ravageur au lieu d’être ravagé à son tour"),
        ("Quand tu auras fini de ravager, tu es ravagé", 'deprædaberis', 'tempus', 'v:ind.praes.pass.2.sg', "le châtiment est actuel au lieu d’être annoncé"),
        ("Quand tu auras fini de ravager, il sera ravagé", 'deprædaberis', 'persona', 'v:ind.fut.pass.3.sg', "un tiers subit le châtiment"),
      ],
      note="Verset long ; la clause centrale, où Segond rend exactement le futur passif, est retenue."),
    Q('th-numerus', 'EXO 20:18',
      target=('populus', 'n:nom.sg'),
      dist=[
        ("Tous les peuples entendaient les tonnerres et le son de la trompette; il voyait les flammes de la montagne fumante. A ce spectacle, le peuple tremblait, et se tenait dans l’éloignement.", 'populus', 'numerus', 'n:nom.pl', "plusieurs peuples"),
        ("Tout le peuple entendait le tonnerre et le son de la trompette; il voyait les flammes de la montagne fumante. A ce spectacle, le peuple tremblait, et se tenait dans l’éloignement.", 'voces', 'numerus', 'n:acc.pl>n:acc.sg', "un seul coup de tonnerre"),
        ("Tout le peuple entendait les tonnerres et le son de la trompette; il voyait la flamme de la montagne fumante. A ce spectacle, le peuple tremblait, et se tenait dans l’éloignement.", 'lampades', 'numerus', 'n:acc.pl>n:acc.sg', "une seule flamme"),
      ],
      note="Segond dédouble « videbat voces et lampades » en « entendait les tonnerres… voyait les flammes » ; la cible est le nom sujet."),
    Q('th-numerus', '2CH 34:8',
      target=('domum', 'n:acc.sg'),
      gloss={'octavodecimo': 'dix-huitième', 'Saphan': 'Schaphan', 'Eseliæ': 'Atsalia', 'Maasiam': 'Maaséja', 'Joha': 'Joach'},
      dist=[
        ("La dix-huitième année de son règne, après qu’il eut purifié le pays et la maison, il envoya Schaphan, fils d’Atsalia, Maaséja, chef de la ville, et Joach, fils de Joachaz, l’archiviste, pour réparer les maisons de l’Éternel, son Dieu.", 'domum', 'numerus', 'n:acc.pl', "plusieurs maisons"),
        ("La dix-huitième année de son règne, après qu’il eut purifié le pays et la maison, il envoya Schaphan, fils d’Atsalia, Maaséja, chef des villes, et Joach, fils de Joachaz, l’archiviste, pour réparer la maison de l’Éternel, son Dieu.", 'civitatis', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs villes"),
        ("La dix-huitième année de son règne, après qu’il eut purifié les pays et la maison, il envoya Schaphan, fils d’Atsalia, Maaséja, chef de la ville, et Joach, fils de Joachaz, l’archiviste, pour réparer la maison de l’Éternel, son Dieu.", 'terra', 'numerus', 'n:abl.sg>n:abl.pl', "plusieurs pays"),
      ],
      note="Segond rend l’ablatif absolu « mundata jam terra et templo » par « après qu’il eut purifié le pays et la maison »."),
    Q('th-modus-imperativus', 'ACT 23:24',
      target=('præparate', 'v:imp.praes.act.2.pl'),
      paed=True, fr="et préparez des montures afin que, y plaçant Paul, ils le conduisent sain et sauf au gouverneur Félix.",
      dist=[
        ("et prépare des montures afin que, y plaçant Paul, ils le conduisent sain et sauf au gouverneur Félix.", 'præparate', 'numerus', 'v:imp.praes.act.2.sg', "l’ordre s’adresse à un seul homme"),
        ("et vous préparez des montures afin que, y plaçant Paul, ils le conduisent sain et sauf au gouverneur Félix.", 'præparate', 'modus', 'v:ind.praes.act.2.pl', "un ordre devient un constat"),
        ("et préparez une monture afin que, y plaçant Paul, ils le conduisent sain et sauf au gouverneur Félix.", 'jumenta', 'numerus', 'n:acc.pl>n:acc.sg', "une seule monture"),
      ],
      note="Segond tourne l’impératif en souhait à la 3e personne (« Qu’il y ait aussi des montures ») ; rendu pédagogique."),
    Q('th-tempus-praeteritum', '1CO 15:14',
      target=('resurrexit', 'v:ind.perf.act.3.sg'),
      dist=[
        ("Et si Christ ne ressuscite pas, notre prédication est donc vaine, et votre foi aussi est vaine.", 'resurrexit', 'tempus', 'v:ind.praes.act.3.sg', "la résurrection est présentée comme actuelle"),
        ("Et si Christ ne ressuscitera pas, notre prédication est donc vaine, et votre foi aussi est vaine.", 'resurrexit', 'tempus', 'v:ind.fut.act.3.sg', "la résurrection devient un événement futur"),
        ("Et si Christ n’est pas ressuscité, nos prédications sont donc vaines, et votre foi aussi est vaine.", 'prædicatio', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs prédications"),
      ]),
]
