# sheet_003 → batch_003
# skipped: (none)
ITEMS = [
    Q('th-tempus-praeteritum', 'NUM 24:6',
      target=('fixit', 'v:ind.perf.act.3.sg'),
      paed=True, fr="comme des vallées boisées, comme des jardins arrosés le long des fleuves, comme des tentes que l’Éternel a dressées, comme des cèdres près des eaux.",
      gloss={'irrigui': 'arrosé, irrigué'},
      dist=[
        ("comme des vallées boisées, comme des jardins arrosés le long des fleuves, comme des tentes que l’Éternel dresse, comme des cèdres près des eaux.", 'fixit', 'tempus', 'v:ind.praes.act.3.sg', "le dressage des tentes est présenté comme en cours"),
        ("comme des vallées boisées, comme des jardins arrosés le long des fleuves, comme des tentes que l’Éternel dressera, comme des cèdres près des eaux.", 'fixit', 'tempus', 'v:ind.fut.act.3.sg', "le dressage des tentes est annoncé"),
        ("comme des vallées boisées, comme des jardins arrosés le long des fleuves, comme des tentes que l’Éternel a dressées, comme un cèdre près des eaux.", 'cedri', 'numerus', 'n:nom.pl>n:nom.sg', "un seul cèdre"),
      ],
      note="Segond suit l’hébreu (« des aloès que l’Éternel a plantés ») pour « tabernacula quæ fixit Dominus » ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'PRO 17:8',
      target=('intelligit', 'v:ind.praes.act.3.sg'),
      paed=True, fr="L’attente de celui qui espère est une pierre très précieuse ; de quelque côté qu’il se tourne, il agit avec intelligence.",
      dist=[
        ("L’attente de celui qui espère est une pierre très précieuse ; de quelque côté qu’il se tourne, il a agi avec intelligence.", 'intelligit', 'tempus', 'v:ind.perf.act.3.sg', "la sagesse est rejetée dans le passé"),
        ("L’attente de celui qui espère est une pierre très précieuse ; de quelque côté qu’il se tourne, il agira avec intelligence.", 'intelligit', 'tempus', 'v:ind.fut.act.3.sg', "la sagesse est annoncée au lieu d’être constatée"),
        ("L’attente de celui qui espère est une pierre très précieuse ; de quelque côté qu’ils se tournent, ils agissent avec intelligence.", 'intelligit', 'numerus', 'v:ind.praes.act.3.pl', "plusieurs personnes au lieu d’une seule"),
      ],
      note="Segond suit l’hébreu (« Les présents sont une pierre précieuse… ils ont du succès ») ; rendu pédagogique."),
    Q('th-tempus-futurum', 'LEV 13:35',
      target=('creverit', 'v:ind.futex.act.3.sg', 'cresco'),
      fr='Mais si la teigne s’est étendue sur la peau, après qu’il a été déclaré pur',
      lemma={'creverit': 'cresco'},
      dist=[
        ("Mais si la teigne s’étend sur la peau, après qu’il a été déclaré pur", 'creverit', 'tempus', 'v:ind.fut.act.3.sg', "l’extension n’est plus achevée au moment de l’examen"),
        ("Mais si la teigne s’était étendue sur la peau, après qu’il a été déclaré pur", 'creverit', 'tempus', 'v:ind.plusq.act.3.sg', "l’extension est rejetée dans un passé antérieur"),
        ("Mais si les teignes se sont étendues sur la peau, après qu’il a été déclaré pur", 'creverit', 'numerus', 'v:ind.futex.act.3.pl', "plusieurs teignes"),
      ],
      note="Le futur antérieur latin après « si » se rend en français par le passé composé ; Segond ajoute « le sacrificateur l’examinera » (verset suivant de la Vulgate)."),
    Q('th-tempus-praeteritum', '2CH 8:18',
      target=('Misit', 'v:ind.perf.act.3.sg'),
      gloss={'quadringenta': 'quatre cents'},
      dist=[
        ("Et Huram lui envoie par ses serviteurs des navires et des serviteurs connaissant la mer. Ils allèrent avec les serviteurs de Salomon à Ophir, et ils y prirent quatre cent cinquante talents d’or, qu’ils apportèrent au roi Salomon.", 'Misit', 'tempus', 'v:ind.praes.act.3.sg', "l’envoi des navires est présenté comme actuel"),
        ("Et Huram lui enverra par ses serviteurs des navires et des serviteurs connaissant la mer. Ils allèrent avec les serviteurs de Salomon à Ophir, et ils y prirent quatre cent cinquante talents d’or, qu’ils apportèrent au roi Salomon.", 'Misit', 'tempus', 'v:ind.fut.act.3.sg', "l’envoi des navires est annoncé"),
        ("Et Huram lui envoya par ses serviteurs des navires et des serviteurs connaissant la mer. Il alla avec les serviteurs de Salomon à Ophir, et ils y prirent quatre cent cinquante talents d’or, qu’ils apportèrent au roi Salomon.", 'abierunt', 'numerus', 'v:ind.perf.act.3.pl>v:ind.perf.act.3.sg', "un seul voyageur"),
      ],
      note="Segond a « serviteurs connaissant la mer » pour « nautas gnaros maris » ; la cible est Misit."),
    Q('th-tempus-praeteritum', 'PSA 143:14',
      target=('est', 'v:ind.praes.act.3.sg'),
      paed=True, fr="leurs bœufs sont gras. Il n’y a pas de brèche dans le mur, ni de passage, ni de cri dans leurs places.",
      dist=[
        ("leurs bœufs sont gras. Il n’y avait pas de brèche dans le mur, ni de passage, ni de cri dans leurs places.", 'est', 'tempus', 'v:ind.imperf.act.3.sg', "la sécurité est rejetée dans le passé"),
        ("leurs bœufs sont gras. Il n’y aura pas de brèche dans le mur, ni de passage, ni de cri dans leurs places.", 'est', 'tempus', 'v:ind.fut.act.3.sg', "la sécurité est promise au lieu d’être constatée"),
        ("leurs bœufs sont gras. Il n’y a pas de brèche dans le mur, ni de passage, ni de cri dans leur place.", 'plateis', 'numerus', 'n:abl.pl>n:abl.sg', "une seule place"),
      ],
      note="Segond (Ps 144:14) suit l’hébreu à la première personne (« Nos génisses… nos rues ») ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'JDG 6:31',
      target=('respondit', 'v:ind.perf.act.3.sg'),
      dist=[
        ("Joas répond à tous ceux qui se présentèrent à lui: Est-ce à vous de prendre parti pour Baal? Est-ce à vous de venir à son secours? Quiconque prendra parti pour Baal mourra avant que le matin vienne. Si Baal est un dieu, qu’il plaide lui-même sa cause, puisqu’on a renversé son autel.", 'respondit', 'tempus', 'v:ind.praes.act.3.sg', "la réponse de Joas est présentée comme actuelle"),
        ("Joas répondra à tous ceux qui se présentèrent à lui: Est-ce à vous de prendre parti pour Baal? Est-ce à vous de venir à son secours? Quiconque prendra parti pour Baal mourra avant que le matin vienne. Si Baal est un dieu, qu’il plaide lui-même sa cause, puisqu’on a renversé son autel.", 'respondit', 'tempus', 'v:ind.fut.act.3.sg', "la réponse de Joas est annoncée"),
        ("Joas répondit à tous ceux qui se présentèrent à lui: Est-ce à vous de prendre parti pour Baal? Est-ce à vous de venir à son secours? Quiconque prendra parti pour Baal mourra avant que le matin vînt. Si Baal est un dieu, qu’il plaide lui-même sa cause, puisqu’on a renversé son autel.", 'veniat', 'tempus', 'v:subj.praes.act.3.sg>v:subj.imperf.act.3.sg', "l’échéance du matin est rejetée dans le passé"),
      ],
      note="Segond explicite « Joas » et « tous ceux qui se présentèrent » et rend « moriatur » par « mourra » ; la cible est respondit."),
    Q('th-modus-imperativus', 'TIT 1:13',
      target=('increpa', 'v:imp.praes.act.2.sg'),
      dist=[
        ("Ce témoignage est vrai. C’est pourquoi reprenez-les sévèrement, afin qu’ils aient une foi saine,", 'increpa', 'numerus', 'v:imp.praes.act.2.pl', "l’ordre s’adresse à plusieurs personnes"),
        ("Ce témoignage est vrai. C’est pourquoi tu les reprends sévèrement, afin qu’ils aient une foi saine,", 'increpa', 'modus', 'v:ind.praes.act.2.sg', "un ordre devient un constat"),
        ("Ce témoignage est vrai. C’est pourquoi reprends-les sévèrement, afin qu’il ait une foi saine,", 'sint', 'numerus', 'v:subj.praes.act.3.pl>v:subj.praes.act.3.sg', "un seul homme est visé par la correction"),
      ]),
    Q('th-tempus-praeteritum', 'HEB 7:26',
      target=('decebat', 'v:ind.imperf.act.3.sg'),
      dist=[
        ("Il nous convient, en effet, d’avoir un souverain sacrificateur comme lui, saint, innocent, sans tache, séparé des pécheurs, et plus élevé que les cieux,", 'decebat', 'tempus', 'v:ind.praes.act.3.sg', "la convenance est présentée comme actuelle"),
        ("Il nous convint, en effet, d’avoir un souverain sacrificateur comme lui, saint, innocent, sans tache, séparé des pécheurs, et plus élevé que les cieux,", 'decebat', 'tempus', 'v:ind.perf.act.3.sg', "un état durable devient un fait ponctuel"),
        ("Il nous convenait, en effet, d’avoir un souverain sacrificateur comme lui, saint, innocent, sans tache, séparé du pécheur, et plus élevé que les cieux,", 'peccatoribus', 'numerus', 'n:abl.pl>n:abl.sg', "un seul pécheur"),
      ],
      note="Segond rend « Talis… ut nobis esset pontifex » par « d’avoir un souverain sacrificateur comme lui » ; la cible est decebat."),
    Q('th-nonfinita', 'SOL 7:2',
      target=('indigens', 'v:part.praes.act.nom.sg.m'),
      paed=True, fr="Ton nombril est une coupe arrondie, ne manquant jamais de breuvages. Ton ventre est comme un tas de froment entouré de lis.",
      dist=[
        ("Ton nombril est une coupe arrondie ; il ne manque jamais de breuvages. Ton ventre est comme un tas de froment entouré de lis.", 'indigens', 'nonfinita', '!verbum finitum (indiget)', "le participe devient une proposition indépendante au lieu de qualifier la coupe"),
        ("Ton nombril est une coupe arrondie, ne manquant jamais de breuvage. Ton ventre est comme un tas de froment entouré de lis.", 'poculis', 'numerus', 'n:abl.pl>n:abl.sg', "un seul breuvage"),
        ("Ton nombril est une coupe arrondie, ne manquant jamais de breuvages. Ton ventre est comme un tas de froment entouré d’un lis.", 'liliis', 'numerus', 'n:abl.pl>n:abl.sg', "un seul lis"),
      ],
      note="Segond (Ct 7:3) suit l’hébreu (« Où le vin parfumé ne manque pas ») et ne rend pas le participe ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'PRO 19:6',
      target=('colunt', 'v:ind.praes.act.3.pl'),
      lemma={'dona': 'donum'},
      dist=[
        ("Beaucoup de gens ont flatté l’homme généreux, Et tous sont les amis de celui qui fait des présents.", 'colunt', 'tempus', 'v:ind.perf.act.3.pl', "la flatterie est rejetée dans le passé"),
        ("Beaucoup de gens flatteront l’homme généreux, Et tous sont les amis de celui qui fait des présents.", 'colunt', 'tempus', 'v:ind.fut.act.3.pl', "la flatterie est annoncée au lieu d’être constatée"),
        ("Beaucoup de gens flattent l’homme généreux, Et chacun est l’ami de celui qui fait des présents.", 'sunt', 'numerus', 'v:ind.praes.act.3.pl>v:ind.praes.act.3.sg', "un seul ami à la fois"),
      ],
      note="Segond a « flattent l’homme généreux » pour « colunt personam potentis » ; la cible est colunt."),
    Q('th-persona', '2CH 19:2',
      target=('præbes', 'v:ind.praes.act.2.sg'),
      paed=True, fr="Jéhu, fils de Hanani, le voyant, alla à sa rencontre et lui dit : Tu prêtes secours à un impie, et tu te lies d’amitié avec ceux qui haïssent l’Éternel ; c’est pourquoi tu méritais la colère de l’Éternel.",
      gloss={'Jehu': 'Jéhu', 'Henani': 'Hanani'},
      dist=[
        ("Jéhu, fils de Hanani, le voyant, alla à sa rencontre et lui dit : Il prête secours à un impie, et tu te lies d’amitié avec ceux qui haïssent l’Éternel ; c’est pourquoi tu méritais la colère de l’Éternel.", 'præbes', 'persona', 'v:ind.praes.act.3.sg', "le reproche ne vise plus Josaphat"),
        ("Jéhu, fils de Hanani, le voyant, alla à sa rencontre et lui dit : Vous prêtez secours à un impie, et tu te lies d’amitié avec ceux qui haïssent l’Éternel ; c’est pourquoi tu méritais la colère de l’Éternel.", 'præbes', 'numerus', 'v:ind.praes.act.2.pl', "plusieurs coupables"),
        ("Jéhu, fils de Hanani, le voyant, alla à sa rencontre et lui dit : Tu prêtes secours à un impie, et tu te lies d’amitié avec ceux qui haïssent l’Éternel ; c’est pourquoi il méritait la colère de l’Éternel.", 'merebaris', 'persona', 'v:ind.imperf.pass.2.sg>v:ind.imperf.pass.3.sg', "un autre que Josaphat encourt la colère"),
      ],
      note="Segond suit l’hébreu (« Doit-on secourir le méchant… l’Éternel est irrité contre toi ») ; rendu pédagogique."),
    Q('th-modus-imperativus', 'PSA 34:2',
      target=('Apprehende', 'v:imp.praes.act.2.sg'),
      dist=[
        ("Saisissez le petit et le grand bouclier, Et lève-toi pour me secourir!", 'Apprehende', 'numerus', 'v:imp.praes.act.2.pl', "la prière s’adresse à plusieurs"),
        ("Tu saisis le petit et le grand bouclier, Et lève-toi pour me secourir!", 'Apprehende', 'modus', 'v:ind.praes.act.2.sg', "une prière devient un constat"),
        ("Saisis le petit et le grand bouclier, Et levez-vous pour me secourir!", 'exsurge', 'numerus', 'v:imp.praes.act.2.sg>v:imp.praes.act.2.pl', "plusieurs secoureurs"),
      ],
      note="Segond (Ps 35:2) a « le petit et le grand bouclier » pour « arma et scutum »."),
    Q('th-tempus-praeteritum', 'JDG 6:11',
      target=('sedit', 'v:ind.perf.act.3.sg'),
      gloss={'Ephra': 'Ophra', 'Ezri': 'Abiézer'},
      dist=[
        ("Puis vint l’ange de l’Éternel, et il s’assied sous le térébinthe d’Ophra, qui appartenait à Joas, de la famille d’Abiézer. Gédéon, son fils, battait du froment au pressoir, pour le mettre à l’abri de Madian.", 'sedit', 'tempus', 'v:ind.praes.act.3.sg', "la scène est présentée comme actuelle"),
        ("Puis vint l’ange de l’Éternel, et il s’assiéra sous le térébinthe d’Ophra, qui appartenait à Joas, de la famille d’Abiézer. Gédéon, son fils, battait du froment au pressoir, pour le mettre à l’abri de Madian.", 'sedit', 'tempus', 'v:ind.fut.act.3.sg', "l’action de s’asseoir est annoncée"),
        ("Puis vint l’ange de l’Éternel, et il s’assit sous le térébinthe d’Ophra, qui appartient à Joas, de la famille d’Abiézer. Gédéon, son fils, battait du froment au pressoir, pour le mettre à l’abri de Madian.", 'pertinebat', 'tempus', 'v:ind.imperf.act.3.sg>v:ind.praes.act.3.sg', "la possession du térébinthe est actuelle"),
      ],
      note="Segond a « térébinthe » pour « quercu » et rend « cum… excuteret » par « battait » ; la cible est sedit."),
    Q('th-modus-imperativus', 'ISA 57:3',
      target=('accedite', 'v:imp.praes.act.2.pl'),
      dist=[
        ("Mais toi, approche ici, fils de l’enchanteresse, Race de l’adultère et de la prostituée!", 'accedite', 'numerus', 'v:imp.praes.act.2.sg', "l’ordre s’adresse à un seul"),
        ("Mais vous, vous approchez ici, fils de l’enchanteresse, Race de l’adultère et de la prostituée!", 'accedite', 'modus', 'v:ind.praes.act.2.pl', "un ordre devient un constat"),
        ("Mais vous, approchez ici, fils de l’enchanteresse, Race des adultères et de la prostituée!", 'adulteri', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs adultères"),
      ]),
    Q('th-modus-subiunctivus', 'DEU 32:2',
      target=('fluat', 'v:subj.praes.act.3.sg'),
      dist=[
        ("Que mes instructions se répandent comme la pluie, Ma parole tombe comme la rosée, Comme des ondées sur la verdure, Comme des gouttes d’eau sur l’herbe!", 'fluat', 'modus', 'v:ind.praes.act.3.sg', "le souhait devient un constat"),
        ("Que mes instructions se répandent comme la pluie, Que mes paroles tombent comme la rosée, Comme des ondées sur la verdure, Comme des gouttes d’eau sur l’herbe!", 'fluat', 'numerus', 'v:subj.praes.act.3.pl', "plusieurs paroles"),
        ("Que mes instructions se répandent comme la pluie, Que ma parole tombât comme la rosée, Comme des ondées sur la verdure, Comme des gouttes d’eau sur l’herbe!", 'fluat', 'tempus', 'v:subj.imperf.act.3.sg', "le souhait est rejeté dans le passé"),
      ],
      note="Segond met « doctrina mea » au pluriel (« mes instructions ») ; la cible est fluat."),
    Q('th-tempus-praeteritum', 'SOL 6:7',
      target=('sunt', 'v:ind.praes.act.3.pl'),
      fr_ref='SOL 6:8',
      dist=[
        ("Il y avait soixante reines, quatre-vingts concubines, Et des jeunes filles sans nombre.", 'sunt', 'tempus', 'v:ind.imperf.act.3.pl', "le dénombrement appartient au passé"),
        ("Il y aura soixante reines, quatre-vingts concubines, Et des jeunes filles sans nombre.", 'sunt', 'tempus', 'v:ind.fut.act.3.pl', "le dénombrement est annoncé"),
        ("Nous sommes soixante reines, quatre-vingts concubines, Et des jeunes filles sans nombre.", 'sunt', 'persona', 'v:ind.praes.act.1.pl', "les reines parlent d’elles-mêmes"),
      ],
      note="Décalage de numérotation : la Vulgate 6:7 correspond à Segond 6:8."),
    Q('th-tempus-praeteritum', 'MAR 15:16',
      target=('duxerunt', 'v:ind.perf.act.3.pl'),
      dist=[
        ("Les soldats conduisent Jésus dans l’intérieur de la cour, c’est-à-dire, dans le prétoire, et ils assemblèrent toute la cohorte.", 'duxerunt', 'tempus', 'v:ind.praes.act.3.pl', "le récit passe au présent"),
        ("Le soldat conduisit Jésus dans l’intérieur de la cour, c’est-à-dire, dans le prétoire, et ils assemblèrent toute la cohorte.", 'duxerunt', 'numerus', 'v:ind.perf.act.3.sg', "un seul soldat"),
        ("Les soldats conduisirent Jésus dans l’intérieur de la cour, c’est-à-dire, dans le prétoire, et ils assemblèrent toutes les cohortes.", 'cohortem', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs cohortes"),
      ],
      note="Segond explicite « Jésus » et a le passé simple « assemblèrent » pour le présent de narration convocant ; la cible est duxerunt."),
    Q('th-tempus-praeteritum', 'EST 3:15',
      target=('Festinabant', 'v:ind.imperf.act.3.pl'),
      paed=True, fr="Les courriers qui avaient été envoyés se hâtaient d’exécuter l’ordre du roi. Aussitôt l’édit fut affiché dans Suse, tandis que le roi et Haman célébraient un festin et que tous les Juifs qui étaient dans la ville pleuraient.",
      gloss={'Susan': 'Suse'},
      dist=[
        ("Les courriers qui avaient été envoyés se hâtèrent d’exécuter l’ordre du roi. Aussitôt l’édit fut affiché dans Suse, tandis que le roi et Haman célébraient un festin et que tous les Juifs qui étaient dans la ville pleuraient.", 'Festinabant', 'tempus', 'v:ind.perf.act.3.pl', "une action en cours devient un fait ponctuel"),
        ("Les courriers qui avaient été envoyés se hâtent d’exécuter l’ordre du roi. Aussitôt l’édit fut affiché dans Suse, tandis que le roi et Haman célébraient un festin et que tous les Juifs qui étaient dans la ville pleuraient.", 'Festinabant', 'tempus', 'v:ind.praes.act.3.pl', "la hâte des courriers est présentée comme actuelle"),
        ("Le courrier qui avait été envoyé se hâtait d’exécuter l’ordre du roi. Aussitôt l’édit fut affiché dans Suse, tandis que le roi et Haman célébraient un festin et que tous les Juifs qui étaient dans la ville pleuraient.", 'cursores', 'numerus', 'n:nom.pl>n:nom.sg', "un seul courrier"),
      ],
      note="Segond suit l’hébreu (« partirent en toute hâte… la ville de Suse était dans la consternation ») ; rendu pédagogique."),
    Q('th-modus-imperativus', 'JDG 13:4',
      target=('Cave', 'v:imp.praes.act.2.sg'),
      dist=[
        ("Maintenant prenez bien garde, ne bois ni vin ni liqueur forte, et ne mange rien d’impur.", 'Cave', 'numerus', 'v:imp.praes.act.2.pl', "l’avertissement s’adresse à plusieurs"),
        ("Maintenant tu prends bien garde, ne bois ni vin ni liqueur forte, et ne mange rien d’impur.", 'Cave', 'modus', 'v:ind.praes.act.2.sg', "un ordre devient un constat"),
        ("Maintenant prends bien garde, ne buvez ni vin ni liqueur forte, et ne mange rien d’impur.", 'bibas', 'numerus', 'v:subj.praes.act.2.sg>v:subj.praes.act.2.pl', "la défense de boire s’adresse à plusieurs"),
      ],
      note="Segond a « Maintenant » pour « ergo »."),
    Q('th-modus-imperativus', 'GAL 6:1',
      target=('instruite', 'v:imp.praes.act.2.pl'),
      dist=[
        ("Frères, si un homme vient à être surpris en quelque faute, vous qui êtes spirituels, redresse-le avec un esprit de douceur. Prends garde à toi-même, de peur que tu ne sois aussi tenté.", 'instruite', 'numerus', 'v:imp.praes.act.2.sg', "l’ordre s’adresse à un seul"),
        ("Frères, si un homme vient à être surpris en quelque faute, vous qui êtes spirituels, vous le redressez avec un esprit de douceur. Prends garde à toi-même, de peur que tu ne sois aussi tenté.", 'instruite', 'modus', 'v:ind.praes.act.2.pl', "un ordre devient un constat"),
        ("Frères, si un homme vient à être surpris en quelque faute, vous qui êtes spirituels, redressez-le avec un esprit de douceur. Prends garde à toi-même, de peur que vous ne soyez aussi tentés.", 'tenteris', 'numerus', 'v:subj.praes.pass.2.sg>v:subj.praes.pass.2.pl', "la mise en garde vise plusieurs personnes"),
      ],
      note="Segond rend le participe « considerans teipsum » par l’impératif « Prends garde à toi-même » ; la cible est instruite."),
    Q('th-modus-imperativus', '1TI 6:20',
      target=('custodi', 'v:imp.praes.act.2.sg'),
      la='O Timothee, depositum custodi, devitans profanas vocum novitates',
      paed=True, fr="O Timothée, garde le dépôt, en évitant les nouveautés profanes de langage",
      lemma={'custodi': 'custodio', 'depositum': 'depositum'},
      dist=[
        ("O Timothée, gardez le dépôt, en évitant les nouveautés profanes de langage", 'custodi', 'numerus', 'v:imp.praes.act.2.pl', "l’ordre s’adresse à plusieurs personnes"),
        ("O Timothée, tu gardes le dépôt, en évitant les nouveautés profanes de langage", 'custodi', 'modus', 'v:ind.praes.act.2.sg', "un ordre devient un constat"),
        ("O Timothée, garde le dépôt, en évitant la nouveauté profane de langage", 'novitates', 'numerus', 'n:acc.pl>n:acc.sg', "une seule nouveauté"),
      ],
      note="Segond (« les discours vains et profanes ») ne rend pas « vocum novitates » ni « oppositiones falsi nominis scientiæ » ; rendu pédagogique de la première partie."),
    Q('th-persona', 'JER 32:10',
      target=('scripsi', 'v:ind.perf.act.1.sg'),
      lemma={'testes': 'testis'},
      gloss={'testes': 'témoin'},
      dist=[
        ("Il écrivit un contrat, que je cachetai, je pris des témoins, et je pesai l’argent dans une balance.", 'scripsi', 'persona', 'v:ind.perf.act.3.sg', "un autre que Jérémie rédige le contrat"),
        ("Nous écrivîmes un contrat, que je cachetai, je pris des témoins, et je pesai l’argent dans une balance.", 'scripsi', 'numerus', 'v:ind.perf.act.1.pl', "plusieurs rédacteurs"),
        ("J’écrivis un contrat, que je cachetai, je pris un témoin, et je pesai l’argent dans une balance.", 'testes', 'numerus', 'n:acc.pl>n:acc.sg', "un seul témoin"),
      ],
      note="Segond explicite « un contrat » pour « in libro » ; la cible est scripsi."),
    Q('th-modus-imperativus', '2TI 2:15',
      target=('cura', 'v:imp.praes.act.2.sg'),
      lemma={'cura': 'curo'},
      dist=[
        ("Efforcez-vous de vous présenter devant Dieu comme un homme éprouvé, un ouvrier qui n’a point à rougir, qui dispense droitement la parole de la vérité.", 'cura', 'numerus', 'v:imp.praes.act.2.pl', "l’ordre s’adresse à plusieurs personnes"),
        ("Tu t’efforces de te présenter devant Dieu comme un homme éprouvé, un ouvrier qui n’a point à rougir, qui dispense droitement la parole de la vérité.", 'cura', 'modus', 'v:ind.praes.act.2.sg', "un ordre devient un constat"),
        ("Efforce-toi de te présenter devant Dieu comme un homme éprouvé, des ouvriers qui n’ont point à rougir, qui dispensent droitement la parole de la vérité.", 'operarium', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs ouvriers"),
      ],
      note="Segond rend « Sollicite cura » par « Efforce-toi »."),
    Q('th-tempus-futurum', 'EXO 34:22',
      target=('facies', 'v:ind.fut.act.2.sg'),
      gloss={'frugum': 'fruits de la terre, récoltes'},
      dist=[
        ("Tu célèbres la fête des semaines, des prémices de la moisson du froment, et la fête de la récolte, à la fin de l’année.", 'facies', 'tempus', 'v:ind.praes.act.2.sg', "une prescription devient un constat"),
        ("Vous célébrerez la fête des semaines, des prémices de la moisson du froment, et la fête de la récolte, à la fin de l’année.", 'facies', 'numerus', 'v:ind.fut.act.2.pl', "la prescription s’adresse à plusieurs"),
        ("Il célébrera la fête des semaines, des prémices de la moisson du froment, et la fête de la récolte, à la fin de l’année.", 'facies', 'persona', 'v:ind.fut.act.3.sg', "la prescription vise un tiers"),
      ],
      note="Segond a « la fête de la récolte, à la fin de l’année » pour « quando redeunte anni tempore cuncta conduntur » ; la cible est facies."),
    Q('th-tempus-praeteritum', '2MA 4:7',
      target=('ambiebat', 'v:ind.imperf.act.3.sg'),
      paed=True, fr="Mais après la mort de Séleucus, quand Antiochus, surnommé le Noble, eut pris le pouvoir, Jason, frère d’Onias, briguait le souverain pontificat :",
      lemma={'excessum': 'excessus'},
      gloss={'excessum': 'sortie, mort'},
      dist=[
        ("Mais après la mort de Séleucus, quand Antiochus, surnommé le Noble, eut pris le pouvoir, Jason, frère d’Onias, brigua le souverain pontificat :", 'ambiebat', 'tempus', 'v:ind.perf.act.3.sg', "une intrigue en cours devient un fait ponctuel"),
        ("Mais après la mort de Séleucus, quand Antiochus, surnommé le Noble, eut pris le pouvoir, Jason, frère d’Onias, brigue le souverain pontificat :", 'ambiebat', 'tempus', 'v:ind.praes.act.3.sg', "l’intrigue est présentée comme actuelle"),
        ("Mais après la mort de Séleucus, quand Antiochus, surnommé le Noble, a pris le pouvoir, Jason, frère d’Onias, briguait le souverain pontificat :", 'suscepisset', 'tempus', 'v:subj.plusq.act.3.sg>v:subj.perf.act.3.sg', "la prise du pouvoir n’est plus antérieure à l’intrigue"),
      ],
      note="Segond n’a pas les livres des Maccabées ; rendu pédagogique."),
    Q('th-tempus-futurum', 'ISA 59:18',
      target=('reddet', 'v:ind.fut.act.3.sg'),
      dist=[
        ("Il rend à chacun selon ses œuvres, La fureur à ses adversaires, La pareille à ses ennemis; Il rend la pareille aux îles.", 'reddet', 'tempus', 'v:ind.praes.act.3.sg', "la rétribution est présentée comme actuelle"),
        ("Ils rendront à chacun selon ses œuvres, La fureur à ses adversaires, La pareille à ses ennemis; Ils rendront la pareille aux îles.", 'reddet', 'numerus', 'v:ind.fut.act.3.pl', "plusieurs vengeurs au lieu de Dieu seul"),
        ("Il rendra à chacun selon ses œuvres, La fureur à ses adversaires, La pareille à ses ennemis; Il rendra la pareille à l’île.", 'insulis', 'numerus', 'n:abl.pl>n:abl.sg', "une seule île"),
      ],
      note="Segond répète « Il rendra » pour l’unique reddet et suit l’hébreu (« selon ses œuvres »)."),
    Q('th-tempus-praeteritum', 'ACT 22:25',
      target=('dicit', 'v:ind.praes.act.3.sg'),
      dist=[
        ("Lorsqu’on l’eut exposé au fouet, Paul a dit au centenier qui était présent: Vous est-il permis de battre de verges un citoyen romain, qui n’est pas même condamné?", 'dicit', 'tempus', 'v:ind.perf.act.3.sg', "le présent de narration devient un passé accompli"),
        ("Lorsqu’on l’eut exposé au fouet, Paul dira au centenier qui était présent: Vous est-il permis de battre de verges un citoyen romain, qui n’est pas même condamné?", 'dicit', 'tempus', 'v:ind.fut.act.3.sg', "la parole de Paul est annoncée"),
        ("Lorsqu’il l’eut exposé au fouet, Paul dit au centenier qui était présent: Vous est-il permis de battre de verges un citoyen romain, qui n’est pas même condamné?", 'astrinxissent', 'numerus', 'v:subj.plusq.act.3.pl>v:subj.plusq.act.3.sg', "un seul bourreau"),
      ],
      note="Segond a « exposé au fouet » pour « astrinxissent eum loris » (« lié de courroies ») ; la cible est dicit."),
    Q('th-nonfinita', '2SA 22:35',
      target=('docens', 'v:part.praes.act.nom.sg.m'),
      paed=True, fr="exerçant mes mains au combat, et tendant comme un arc d’airain mes bras.",
      lemma={'arcum': 'arcus'},
      gloss={'arcum': 'arc'},
      dist=[
        ("il exerce mes mains au combat, et tend comme un arc d’airain mes bras.", 'docens', 'nonfinita', '!verbum finitum (docet)', "les participes deviennent une proposition indépendante au lieu de qualifier Dieu"),
        ("exerçant ma main au combat, et tendant comme un arc d’airain mes bras.", 'manus', 'numerus', 'n:acc.pl>n:acc.sg', "une seule main"),
        ("exerçant mes mains au combat, et tendant comme un arc d’airain mon bras.", 'brachia', 'numerus', 'n:acc.pl>n:acc.sg', "un seul bras"),
      ],
      note="Segond a des verbes finis (« Il exerce… mes bras tendent ») ; rendu pédagogique des participes."),
    Q('th-persona', 'ROM 11:17',
      target=('insertus es', 'v:ind.praes.act.2.sg'),
      dist=[
        ("Mais si quelques-unes des branches ont été retranchées, et si toi, qui étais un olivier sauvage, il a été enté à leur place, et rendu participant de la racine et de la graisse de l’olivier,", 'insertus es', 'persona', 'v:ind.praes.act.3.sg', "un autre que le lecteur est greffé"),
        ("Mais si quelques-unes des branches ont été retranchées, et si toi, qui étais un olivier sauvage, vous avez été entés à leur place, et rendus participants de la racine et de la graisse de l’olivier,", 'insertus es', 'numerus', 'v:ind.praes.act.2.pl', "plusieurs greffés"),
        ("Mais si une des branches a été retranchée, et si toi, qui étais un olivier sauvage, tu as été enté à leur place, et rendu participant de la racine et de la graisse de l’olivier,", 'sunt', 'numerus', 'v:ind.praes.act.3.pl>v:ind.praes.act.3.sg', "une seule branche retranchée"),
      ],
      note="Segond rend « cum oleaster esses » par « qui étais un olivier sauvage » ; la cible est le parfait passif « insertus es »."),
    Q('th-tempus-futurum', 'PRO 15:5',
      target=('fiet', 'v:ind.fut.act.3.sg'),
      paed=True, fr="L’insensé se moque de l’instruction de son père ; mais celui qui garde les réprimandes deviendra plus avisé. Dans une abondante justice est la plus grande force ; mais les pensées des impies seront déracinées.",
      dist=[
        ("L’insensé se moque de l’instruction de son père ; mais celui qui garde les réprimandes devient plus avisé. Dans une abondante justice est la plus grande force ; mais les pensées des impies seront déracinées.", 'fiet', 'tempus', 'v:ind.praes.act.3.sg', "le progrès est constaté au lieu d’être promis"),
        ("L’insensé se moque de l’instruction de son père ; mais celui qui garde les réprimandes deviendra plus avisé. Dans une abondante justice est la plus grande force ; mais les pensées des impies sont déracinées.", 'eradicabuntur', 'tempus', 'v:ind.fut.pass.3.pl>v:ind.praes.pass.3.pl', "le châtiment est actuel"),
        ("Les insensés se moquent de l’instruction de leur père ; mais celui qui garde les réprimandes deviendra plus avisé. Dans une abondante justice est la plus grande force ; mais les pensées des impies seront déracinées.", 'irridet', 'numerus', 'v:ind.praes.act.3.sg>v:ind.praes.act.3.pl', "plusieurs insensés"),
      ],
      note="Segond ne rend que la première moitié du verset et a « agit avec prudence » pour « astutior fiet » ; rendu pédagogique."),
    Q('th-modus-subiunctivus', 'GEN 49:17',
      target=('cadat', 'v:subj.praes.act.3.sg'),
      dist=[
        ("Dan sera un serpent sur le chemin, Une vipère sur le sentier, Mordant les talons du cheval, Pour que le cavalier tombât à la renverse.", 'cadat', 'tempus', 'v:subj.imperf.act.3.sg', "la chute est rejetée dans le passé"),
        ("Dan sera un serpent sur le chemin, Une vipère sur le sentier, Mordant les talons du cheval, Pour que les cavaliers tombent à la renverse.", 'cadat', 'numerus', 'v:subj.praes.act.3.pl', "plusieurs cavaliers"),
        ("Dan sera un serpent sur le chemin, Une vipère sur le sentier, Mordant le talon du cheval, Pour que le cavalier tombe à la renverse.", 'ungulas', 'numerus', 'n:acc.pl>n:acc.sg', "un seul talon"),
      ],
      note="Segond a le futur « sera » pour le subjonctif « Fiat » ; la cible est cadat."),
    Q('th-tempus-praeteritum', 'PRO 14:31',
      target=('exprobrat', 'v:ind.praes.act.3.sg'),
      paed=True, fr="Celui qui opprime l’indigent outrage celui qui l’a fait ; mais celui qui a pitié du pauvre l’honore.",
      dist=[
        ("Celui qui opprime l’indigent a outragé celui qui l’a fait ; mais celui qui a pitié du pauvre l’honore.", 'exprobrat', 'tempus', 'v:ind.perf.act.3.sg', "l’outrage est rejeté dans le passé"),
        ("Celui qui opprime l’indigent outragera celui qui l’a fait ; mais celui qui a pitié du pauvre l’honore.", 'exprobrat', 'tempus', 'v:ind.fut.act.3.sg', "la sentence devient une prédiction"),
        ("Celui qui opprime l’indigent outrage celui qui l’a fait ; mais ceux qui ont pitié du pauvre l’honorent.", 'honorat', 'numerus', 'v:ind.praes.act.3.sg>v:ind.praes.act.3.pl', "plusieurs personnes honorent"),
      ],
      note="Segond a des infinitifs (« Opprimer le pauvre, c’est outrager… ») ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'JOS 12:2',
      target=('habitavit', 'v:ind.perf.act.3.sg'),
      paed=True, fr="Sihon, roi des Amoréens, qui habita à Hesbon, domina depuis Aroër, qui est située sur le bord du torrent de l’Arnon, et depuis le milieu de la vallée, et sur la moitié de Galaad, jusqu’au torrent de Jabbok, qui est la frontière des enfants d’Ammon.",
      gloss={'Sehon': 'Sihon', 'Jaboc': 'Jabbok', 'torrentis': 'torrent', 'torrentem': 'torrent'},
      lemma={'torrentis': 'torrens', 'torrentem': 'torrens'},
      dist=[
        ("Sihon, roi des Amoréens, qui habitait à Hesbon, domina depuis Aroër, qui est située sur le bord du torrent de l’Arnon, et depuis le milieu de la vallée, et sur la moitié de Galaad, jusqu’au torrent de Jabbok, qui est la frontière des enfants d’Ammon.", 'habitavit', 'tempus', 'v:ind.imperf.act.3.sg', "un fait ponctuel devient une résidence qui dure"),
        ("Sihon, roi des Amoréens, qui habite à Hesbon, domina depuis Aroër, qui est située sur le bord du torrent de l’Arnon, et depuis le milieu de la vallée, et sur la moitié de Galaad, jusqu’au torrent de Jabbok, qui est la frontière des enfants d’Ammon.", 'habitavit', 'tempus', 'v:ind.praes.act.3.sg', "la résidence de Sihon est actuelle"),
        ("Sihon, roi des Amoréens, qui habita à Hesbon, domina depuis Aroër, qui est située sur le bord du torrent de l’Arnon, et depuis le milieu de la vallée, et sur la moitié de Galaad, jusqu’au torrent de Jabbok, qui est la frontière du fils d’Ammon.", 'filiorum', 'numerus', 'n:gen.pl>n:gen.sg', "un seul fils"),
      ],
      note="Segond a l’imparfait « habitait » pour le parfait habitavit et « Sa domination s’étendait » pour « dominatus est » ; rendu pédagogique."),
    Q('th-modus-imperativus', 'GEN 25:33',
      target=('Jura', 'v:imp.praes.act.2.sg'),
      lemma={'Jura': 'iuro'},
      dist=[
        ("Et Jacob dit: Jurez-le moi d’abord. Il le lui jura, et il vendit son droit d’aînesse à Jacob.", 'Jura', 'numerus', 'v:imp.praes.act.2.pl', "l’ordre s’adresse à plusieurs personnes"),
        ("Et Jacob dit: Tu me le jures d’abord. Il le lui jura, et il vendit son droit d’aînesse à Jacob.", 'Jura', 'modus', 'v:ind.praes.act.2.sg', "un ordre devient un constat"),
        ("Et Jacob dit: Jure-le moi d’abord. Ils le lui jurèrent, et il vendit son droit d’aînesse à Jacob.", 'Juravit', 'numerus', 'v:ind.perf.act.3.sg>v:ind.perf.act.3.pl', "plusieurs jureurs au lieu d’Ésaü seul"),
      ],
      note="Segond a « d’abord » pour « ergo » et explicite « à Jacob » ; la cible est Jura."),
    Q('th-tempus-futurum', 'PRO 14:13',
      target=('miscebitur', 'v:ind.fut.pass.3.sg'),
      paed=True, fr="Le rire sera mêlé de douleur, et le deuil occupe la fin de la joie.",
      lemma={'Risus': 'risus'},
      gloss={'Risus': 'rire'},
      dist=[
        ("Le rire est mêlé de douleur, et le deuil occupe la fin de la joie.", 'miscebitur', 'tempus', 'v:ind.praes.pass.3.sg', "le mélange est constaté au lieu d’être annoncé"),
        ("Le rire était mêlé de douleur, et le deuil occupe la fin de la joie.", 'miscebitur', 'tempus', 'v:ind.imperf.pass.3.sg', "le mélange est rejeté dans le passé"),
        ("Le rire sera mêlé de douleur, et le deuil occupera la fin de la joie.", 'occupat', 'tempus', 'v:ind.praes.act.3.sg>v:ind.fut.act.3.sg', "la fin de la joie est annoncée au lieu d’être constatée"),
      ],
      note="Segond suit l’hébreu (« le cœur peut être affligé… la joie peut finir par la détresse ») ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'JOS 15:8',
      target=('Ascenditque', 'v:ind.praes.act.3.sg'),
      paed=True, fr="Et elle monte par la vallée du fils d’Hinnom, au côté méridional du Jébusien, c’est-à-dire Jérusalem ; et de là, s’élevant vers le sommet de la montagne qui est en face de Géhinnom à l’occident, à l’extrémité de la vallée des Rephaïm au nord :",
      gloss={'convallem': 'vallée encaissée', 'Ennom': 'Hinnom', 'Geennom': 'Hinnom (Géhinnom)', 'vallis': 'vallée', 'occidentem': 'occident, ouest'},
      lemma={'vallis': 'uallis', 'occidentem': 'occidens'},
      dist=[
        ("Et elle monta par la vallée du fils d’Hinnom, au côté méridional du Jébusien, c’est-à-dire Jérusalem ; et de là, s’élevant vers le sommet de la montagne qui est en face de Géhinnom à l’occident, à l’extrémité de la vallée des Rephaïm au nord :", 'Ascenditque', 'tempus', 'v:ind.perf.act.3.sg', "la description de la frontière devient un récit"),
        ("Et elle montait par la vallée du fils d’Hinnom, au côté méridional du Jébusien, c’est-à-dire Jérusalem ; et de là, s’élevant vers le sommet de la montagne qui est en face de Géhinnom à l’occident, à l’extrémité de la vallée des Rephaïm au nord :", 'Ascenditque', 'tempus', 'v:ind.imperf.act.3.sg', "la frontière est décrite comme un état passé"),
        ("Et elle monte par la vallée du fils d’Hinnom, au côté méridional du Jébusien, c’est-à-dire Jérusalem ; et de là, s’élevant vers le sommet des montagnes qui est en face de Géhinnom à l’occident, à l’extrémité de la vallée des Rephaïm au nord :", 'montis', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs montagnes"),
      ],
      note="Segond a l’imparfait (« Elle montait… s’élevait ») pour le présent de description ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'LEV 1:8',
      target=('adhærent', 'v:ind.praes.act.3.pl'),
      paed=True, fr="et disposant par-dessus les morceaux qui ont été découpés, à savoir la tête et tout ce qui adhère au foie,",
      dist=[
        ("et disposant par-dessus les morceaux qui ont été découpés, à savoir la tête et tout ce qui a adhéré au foie,", 'adhærent', 'tempus', 'v:ind.perf.act.3.pl', "l’adhérence est rejetée dans le passé"),
        ("et disposant par-dessus les morceaux qui ont été découpés, à savoir la tête et tout ce qui adhérera au foie,", 'adhærent', 'tempus', 'v:ind.fut.act.3.pl', "l’adhérence est annoncée"),
        ("et disposant par-dessus le morceau qui a été découpé, à savoir la tête et tout ce qui adhère au foie,", 'membra', 'numerus', 'n:acc.pl>n:acc.sg', "un seul morceau"),
      ],
      note="Segond suit l’hébreu (« les morceaux, la tête et la graisse ») ; rendu pédagogique."),
    Q('th-tempus-futurum', 'MAT 26:75',
      target=('negabis', 'v:ind.fut.act.2.sg'),
      lemma={'egressus': 'egredior'},
      dist=[
        ("Et Pierre se souvint de la parole que Jésus avait dite: Avant que le coq chante, tu me renies trois fois. Et étant sorti, il pleura amèrement.", 'negabis', 'tempus', 'v:ind.praes.act.2.sg', "le reniement est présenté comme actuel"),
        ("Et Pierre se souvint de la parole que Jésus avait dite: Avant que le coq chante, vous me renierez trois fois. Et étant sorti, il pleura amèrement.", 'negabis', 'numerus', 'v:ind.fut.act.2.pl', "plusieurs disciples visés par la prédiction"),
        ("Et Pierre se souvint de la parole que Jésus avait dite: Avant que le coq chante, tu me renieras trois fois. Et étant sorti, il pleure amèrement.", 'flevit', 'tempus', 'v:ind.perf.act.3.sg>v:ind.praes.act.3.sg', "les larmes de Pierre sont actuelles"),
      ]),
    Q('th-modus-imperativus', '1TI 6:17',
      target=('præcipe', 'v:imp.praes.act.2.sg'),
      lemma={'vivo': 'uiuus'},
      dist=[
        ("Recommandez aux riches du présent siècle de ne pas être orgueilleux, et de ne pas mettre leur espérance dans des richesses incertaines, mais de la mettre en Dieu, qui nous donne avec abondance toutes choses pour que nous en jouissions.", 'præcipe', 'numerus', 'v:imp.praes.act.2.pl', "l’ordre s’adresse à plusieurs personnes"),
        ("Tu recommandes aux riches du présent siècle de ne pas être orgueilleux, et de ne pas mettre leur espérance dans des richesses incertaines, mais de la mettre en Dieu, qui nous donne avec abondance toutes choses pour que nous en jouissions.", 'præcipe', 'modus', 'v:ind.praes.act.2.sg', "un ordre devient un constat"),
        ("Recommande au riche du présent siècle de ne pas être orgueilleux, et de ne pas mettre son espérance dans des richesses incertaines, mais de la mettre en Dieu, qui nous donne avec abondance toutes choses pour que nous en jouissions.", 'Divitibus', 'numerus', 'a:dat.pl.m>a:dat.sg.m', "un seul riche"),
      ],
      note="Segond rend « non sublime sapere » par « de ne pas être orgueilleux » ; la cible est præcipe."),
    Q('th-persona', 'ACT 27:2',
      target=('sustulimus', 'v:ind.perf.act.1.pl'),
      lemma={'loca': 'locus'},
      dist=[
        ("Ils montèrent sur un navire d’Adramytte, qui devait côtoyer l’Asie, et ils partirent, ayant avec eux Aristarque, Macédonien de Thessalonique.", 'sustulimus', 'persona', 'v:ind.perf.act.3.pl', "le narrateur ne fait plus partie du voyage"),
        ("Je montai sur un navire d’Adramytte, qui devait côtoyer l’Asie, et je partis, ayant avec moi Aristarque, Macédonien de Thessalonique.", 'sustulimus', 'numerus', 'v:ind.perf.act.1.sg', "le narrateur voyage seul"),
        ("Nous montâmes sur des navires d’Adramytte, qui devaient côtoyer l’Asie, et nous partîmes, ayant avec nous Aristarque, Macédonien de Thessalonique.", 'navem', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs navires"),
      ],
      note="Segond rend les participes « ascendentes… incipientes… perseverante » par des verbes finis ; la cible est sustulimus."),
]
