# sheet_007 → batch_007
# skipped: 1CH 1:36 (list of names, no verb)
# skipped: EZR 4:9 (list of names, no verb)
# skipped: TIT 1:8 (bare list of accusative adjectives without verb; no morphological misreading changes the French)
# skipped: 1CH 25:4 (list of names, no verb)
ITEMS = [
    Q('th-tempus-praeteritum', 'PHI 2:25',
      target=('existimavi', 'v:ind.perf.act.1.sg'),
      dist=[
        ("J’estime nécessaire de vous envoyer mon frère Épaphrodite, mon compagnon d’œuvre et de combat, par qui vous m’avez fait parvenir de quoi pourvoir à mes besoins.", 'existimavi', 'tempus', 'v:ind.praes.act.1.sg', "la décision est présentée comme actuelle"),
        ("J’estimerai nécessaire de vous envoyer mon frère Épaphrodite, mon compagnon d’œuvre et de combat, par qui vous m’avez fait parvenir de quoi pourvoir à mes besoins.", 'existimavi', 'tempus', 'v:ind.fut.act.1.sg', "la décision est encore à venir"),
        ("Nous avons estimé nécessaire de vous envoyer notre frère Épaphrodite, notre compagnon d’œuvre et de combat, par qui vous nous avez fait parvenir de quoi pourvoir à nos besoins.", 'existimavi', 'numerus', 'v:ind.perf.act.1.pl', "plusieurs auteurs de la décision"),
      ],
      note="Segond condense « vestrum autem apostolum et ministrum necessitatis meæ » en « par qui vous m’avez fait parvenir de quoi pourvoir à mes besoins » ; la cible est existimavi."),
    Q('th-nonfinita', 'LUK 3:1',
      target=('procurante', 'v:part.praes.act.abl.sg.m'),
      la='Anno autem quintodecimo imperii Tiberii Cæsaris, procurante Pontio Pilato Judæam',
      fr='La quinzième année du règne de Tibère César, lorsque Ponce Pilate était gouverneur de la Judée',
      gloss={'quintodecimo': 'quinzième'},
      dist=[
        ("La quinzième année du règne de Tibère César, lorsque Ponce Pilate allait être gouverneur de la Judée", 'procurante', 'tempus', 'v:part.fut.act.abl.sg.m', "le gouvernement de Pilate n’a pas encore commencé"),
        ("La quinzième année du règne de Tibère César, Ponce Pilate était gouverneur de la Judée", 'procurante', 'nonfinita', '!verbum fīnītum (procūrābat)', "la circonstance devient l’énoncé principal"),
        ("La quinzième année des règnes de Tibère César, lorsque Ponce Pilate était gouverneur de la Judée", 'imperii', 'numerus', 'n:gen.sg>n:gen.pl', "plusieurs règnes"),
      ],
      note="Segond rend l’ablatif absolu procurante Pontio Pilato par une subordonnée temporelle ; première partie du verset."),
    Q('th-modus-imperativus', 'MAT 13:30',
      target=('Sinite', 'v:imp.praes.act.2.pl'),
      dist=[
        ("Laisse croître ensemble l’un et l’autre jusqu’à la moisson, et, à l’époque de la moisson, je dirai aux moissonneurs: Arrachez d’abord l’ivraie, et liez-la en gerbes pour la brûler, mais amassez le blé dans mon grenier.", 'Sinite', 'numerus', 'v:imp.praes.act.2.sg', "l’ordre s’adresse à un seul serviteur"),
        ("Vous laissez croître ensemble l’un et l’autre jusqu’à la moisson, et, à l’époque de la moisson, je dirai aux moissonneurs: Arrachez d’abord l’ivraie, et liez-la en gerbes pour la brûler, mais amassez le blé dans mon grenier.", 'Sinite', 'modus', 'v:ind.praes.act.2.pl', "l’ordre devient un constat"),
        ("Laissez croître ensemble l’un et l’autre jusqu’à la moisson, et, à l’époque de la moisson, je dirai aux moissonneurs: Arrache d’abord l’ivraie, et liez-la en gerbes pour la brûler, mais amassez le blé dans mon grenier.", 'Colligite', 'numerus', 'v:imp.praes.act.2.pl>v:imp.praes.act.2.sg', "un seul moissonneur reçoit l’ordre"),
      ]),
    Q('th-tempus-praeteritum', 'LUK 23:53',
      target=('posuit', 'v:ind.perf.act.3.sg'),
      dist=[
        ("Il le descendit de la croix, l’enveloppa d’un linceul, et le dépose dans un sépulcre taillé dans le roc, où personne n’avait encore été mis.", 'posuit', 'tempus', 'v:ind.praes.act.3.sg', "la mise au tombeau est présentée comme en cours"),
        ("Il le descendit de la croix, l’enveloppa d’un linceul, et le déposera dans un sépulcre taillé dans le roc, où personne n’avait encore été mis.", 'posuit', 'tempus', 'v:ind.fut.act.3.sg', "la mise au tombeau est annoncée"),
        ("Il le descendit de la croix, l’enveloppa d’un linceul, et le déposa dans un sépulcre taillé dans le roc, où personne n’a encore été mis.", 'fuerat', 'tempus', 'v:ind.plusq.act.3.sg>v:ind.perf.act.3.sg', "l’antériorité par rapport au récit disparaît"),
      ],
      note="Segond rend le participe depositum par « Il le descendit de la croix » ; la cible est posuit."),
    Q('th-tempus-praeteritum', 'EZE 42:5',
      target=('erant', 'v:ind.imperf.act.3.pl'),
      gloss={'gazophylacia': 'chambres (du trésor), cellules'},
      dist=[
        ("Les chambres supérieures sont plus étroites que les inférieures et que celles du milieu du bâtiment, parce que les galeries leur ôtaient de la place.", 'erant', 'tempus', 'v:ind.praes.act.3.pl', "la disposition est décrite au présent"),
        ("Les chambres supérieures seront plus étroites que les inférieures et que celles du milieu du bâtiment, parce que les galeries leur ôtaient de la place.", 'erant', 'tempus', 'v:ind.fut.act.3.pl', "la disposition est annoncée"),
        ("La chambre supérieure était plus étroite que les inférieures et que celles du milieu du bâtiment, parce que les galeries leur ôtaient de la place.", 'erant', 'numerus', 'v:ind.imperf.act.3.sg', "une seule chambre"),
      ],
      note="Segond réorganise le verset (« parce que les galeries leur ôtaient de la place » pour quia supportabant porticus…) ; la cible est erant."),
    Q('th-numerus', 'JOB 34:3',
      target=('probat', 'v:ind.praes.act.3.sg'),
      dist=[
        ("Car les oreilles discernent les paroles, Comme le palais savoure les aliments.", 'probat', 'numerus', 'v:ind.praes.act.3.pl', "plusieurs oreilles"),
        ("Car l’oreille discerne la parole, Comme le palais savoure les aliments.", 'verba', 'numerus', 'n:acc.pl>n:acc.sg', "une seule parole"),
        ("Car l’oreille discerne les paroles, Comme le palais savoure l’aliment.", 'escas', 'numerus', 'n:acc.pl>n:acc.sg', "un seul aliment"),
      ]),
    Q('th-modus-imperativus', 'PSA 30:3',
      target=('Inclina', 'v:imp.praes.act.2.sg'),
      gloss={'accelera': 'hâte-toi (accelero)'},
      dist=[
        ("Tu inclines vers moi ton oreille, hâte-toi de me secourir! Sois pour moi un rocher protecteur, une forteresse, Où je trouve mon salut!", 'Inclina', 'modus', 'v:ind.praes.act.2.sg', "la prière devient un constat"),
        ("Incline vers moi tes oreilles, hâte-toi de me secourir! Sois pour moi un rocher protecteur, une forteresse, Où je trouve mon salut!", 'aurem', 'numerus', 'n:acc.sg>n:acc.pl', "les deux oreilles"),
        ("Incline vers moi ton oreille, hâte-toi de me secourir! Tu seras pour moi un rocher protecteur, une forteresse, Où je trouve mon salut!", 'Esto', 'modus', 'v:imp.fut.act.2.sg>v:ind.fut.act.2.sg', "la prière devient une prédiction"),
      ],
      note="Segond 31:3 a « un rocher protecteur » pour in Deum protectorem (d’après l’hébreu) ; la cible est Inclina."),
    Q('th-tempus-futurum', 'DEU 8:9',
      target=('comedes', 'v:ind.fut.act.2.sg'),
      dist=[
        ("pays où tu manges du pain avec abondance, où tu ne manqueras de rien; pays dont les pierres sont du fer, et des montagnes duquel tu tailleras l’airain.", 'comedes', 'tempus', 'v:ind.praes.act.2.sg', "la promesse devient un constat présent"),
        ("pays où tu as mangé du pain avec abondance, où tu ne manqueras de rien; pays dont les pierres sont du fer, et des montagnes duquel tu tailleras l’airain.", 'comedes', 'tempus', 'v:ind.perf.act.2.sg', "la promesse est déjà accomplie"),
        ("pays où tu mangeras du pain avec abondance, où tu ne manqueras de rien; pays dont la pierre est du fer, et des montagnes duquel tu tailleras l’airain.", 'lapides', 'numerus', 'n:nom.pl>n:nom.sg', "une seule pierre"),
      ],
      note="Segond rend le passif fodiuntur par « tu tailleras » et déplace absque ulla penuria ; la cible est comedes."),
    Q('th-tempus-praeteritum', 'ACT 5:18',
      target=('injecerunt', 'v:ind.perf.act.3.pl'),
      dist=[
        ("mettent les mains sur les apôtres, et les jetèrent dans la prison publique.", 'injecerunt', 'tempus', 'v:ind.praes.act.3.pl', "l’arrestation est présentée comme en cours"),
        ("mettaient les mains sur les apôtres, et les jetèrent dans la prison publique.", 'injecerunt', 'tempus', 'v:ind.imperf.act.3.pl', "un fait ponctuel devient une action qui dure"),
        ("mirent la main sur les apôtres, et les jetèrent dans la prison publique.", 'manus', 'numerus', 'n:acc.pl>n:acc.sg', "une seule main"),
      ]),
    Q('th-tempus-praeteritum', 'EXO 38:26',
      target=('Fuerunt', 'v:ind.perf.act.3.pl'),
      paed=True, fr="Il y eut en outre cent talents d’argent, dont furent fondues les bases du sanctuaire et de l’entrée, où pend le voile.",
      dist=[
        ("Il y a en outre cent talents d’argent, dont furent fondues les bases du sanctuaire et de l’entrée, où pend le voile.", 'Fuerunt', 'tempus', 'v:ind.praes.act.3.pl', "le compte est présenté au présent"),
        ("Il y aura en outre cent talents d’argent, dont furent fondues les bases du sanctuaire et de l’entrée, où pend le voile.", 'Fuerunt', 'tempus', 'v:ind.fut.act.3.pl', "le compte est annoncé"),
        ("Il y eut en outre cent talents d’argent, dont furent fondues les bases du sanctuaire et de l’entrée, où pendent les voiles.", 'velum', 'numerus', 'n:nom.sg>n:nom.pl', "plusieurs voiles"),
      ],
      note="Segond 38:26-27 suit la numérotation hébraïque (« Les cent talents d’argent servirent à fondre… ») et ne rend pas Fuerunt ; rendu pédagogique."),
    Q('th-modus-subiunctivus', 'JOB 12:24',
      target=('incedant', 'v:subj.praes.act.3.pl'),
      paed=True, fr="Il change le cœur des chefs du peuple de la terre, et il les trompe pour qu’ils errent en vain par un lieu sans chemin.",
      dist=[
        ("Il change le cœur des chefs du peuple de la terre, et il les trompe : ainsi ils errent en vain par un lieu sans chemin.", 'incedant', 'modus', 'v:ind.praes.act.3.pl', "le but devient un simple constat"),
        ("Il change le cœur des chefs du peuple de la terre, et il les trompe pour qu’ils errassent en vain par un lieu sans chemin.", 'incedant', 'tempus', 'v:subj.imperf.act.3.pl', "l’errance est rejetée dans le passé"),
        ("Il change le cœur des chefs du peuple de la terre, et il les trompe pour qu’il erre en vain par un lieu sans chemin.", 'incedant', 'numerus', 'v:subj.praes.act.3.sg', "un seul égaré"),
      ],
      note="Segond (« Il enlève l’intelligence aux chefs des peuples, Il les fait errer ») paraphrase ; rendu pédagogique de la finale ut… incedant."),
    Q('th-persona', '1PE 2:11',
      target=('obsecro', 'v:ind.praes.act.1.sg'),
      dist=[
        ("Bien-aimés, il vous exhorte, comme étrangers et voyageurs sur la terre, à vous abstenir des convoitises charnelles qui font la guerre à l’âme.", 'obsecro', 'persona', 'v:ind.praes.act.3.sg', "un tiers exhorte à la place de l’apôtre"),
        ("Bien-aimés, nous vous exhortons, comme étrangers et voyageurs sur la terre, à vous abstenir des convoitises charnelles qui font la guerre à l’âme.", 'obsecro', 'numerus', 'v:ind.praes.act.1.pl', "plusieurs auteurs de l’exhortation"),
        ("Bien-aimés, je vous exhorte, comme étrangers et voyageurs sur la terre, à vous abstenir des convoitises charnelles qui font la guerre aux âmes.", 'animam', 'numerus', 'n:acc.sg>n:acc.pl', "plusieurs âmes"),
      ],
      note="Segond ajoute « sur la terre » ; la cible est obsecro."),
    Q('th-nonfinita', 'LAM 5:10',
      target=('exusta', 'v:part.perf.pass.nom.sg.f'),
      paed=True, fr="Notre peau a été brûlée comme un four, devant les tempêtes de la faim.",
      lemma={'famis': 'fames'},
      dist=[
        ("Nos peaux ont été brûlées comme un four, devant les tempêtes de la faim.", 'exusta', 'numerus', 'v:part.perf.pass.nom.pl.f', "plusieurs peaux"),
        ("Notre peau est comme un four brûlé, devant les tempêtes de la faim.", 'exusta', 'congruentia', '!cum clibanus (nōm. sg. m.) congruēns', "c’est le four qui est brûlé, non la peau"),
        ("Notre peau a été brûlée comme un four, devant la tempête de la faim.", 'tempestatum', 'numerus', 'n:gen.pl>n:gen.sg', "une seule tempête"),
      ],
      note="Segond (« Notre peau est brûlante comme un four, Par l’ardeur de la faim ») lit un état présent ; rendu pédagogique du parfait passif exusta est."),
    Q('th-tempus-praeteritum', 'PSA 8:6',
      target=('coronasti', 'v:ind.perf.act.2.sg'),
      gloss={'paulominus': 'un peu moins, de peu'},
      dist=[
        ("Tu l’as fait de peu inférieur à Dieu, Et tu le couronnes de gloire et de magnificence.", 'coronasti', 'tempus', 'v:ind.praes.act.2.sg', "le couronnement est actuel"),
        ("Tu l’as fait de peu inférieur à Dieu, Et il l’a couronné de gloire et de magnificence.", 'coronasti', 'persona', 'v:ind.perf.act.3.sg', "on parle de Dieu au lieu de s’adresser à lui"),
        ("Tu l’as fait de peu inférieur à Dieu, Et vous l’avez couronné de gloire et de magnificence.", 'coronasti', 'numerus', 'v:ind.perf.act.2.pl', "plusieurs destinataires"),
      ],
      note="Segond a « inférieur à Dieu » pour ab angelis (d’après l’hébreu) ; la cible est coronasti."),
    Q('th-tempus-praeteritum', 'GEN 11:26',
      target=('genuit', 'v:ind.perf.act.3.sg'),
      gloss={'Thare': 'Térach', 'Nachor': 'Nachor', 'Aran': 'Haran'},
      dist=[
        ("Térach, âgé de soixante-dix ans, engendre Abram, Nachor et Haran.", 'genuit', 'tempus', 'v:ind.praes.act.3.sg', "la naissance est présentée comme actuelle"),
        ("Térach, âgé de soixante-dix ans, engendrera Abram, Nachor et Haran.", 'genuit', 'tempus', 'v:ind.fut.act.3.sg', "la naissance est annoncée"),
        ("Térach, âgé de soixante-dix ans, engendrait Abram, Nachor et Haran.", 'genuit', 'tempus', 'v:ind.imperf.act.3.sg', "un fait accompli devient une action qui dure"),
      ],
      note="Segond rend Vixitque… annis par « âgé de soixante-dix ans » ; la cible est genuit."),
    Q('th-tempus-futurum', '1SA 30:5',
      target=('fuerant', 'v:ind.plusq.act.3.pl'),
      gloss={'Jezrahelites': 'de Jizreel (Jizreélite)', 'Nabal': 'Nabal'},
      dist=[
        ("Les deux femmes de David ont été emmenées, Achinoam de Jizreel, et Abigaïl de Carmel, femme de Nabal.", 'fuerant', 'tempus', 'v:ind.praes.act.3.pl', "l’enlèvement n’est plus antérieur au récit"),
        ("Les deux femmes de David seront emmenées, Achinoam de Jizreel, et Abigaïl de Carmel, femme de Nabal.", 'fuerant', 'tempus', 'v:ind.fut.act.3.pl', "l’enlèvement est annoncé"),
        ("Les deux femmes de David étaient emmenées, Achinoam de Jizreel, et Abigaïl de Carmel, femme de Nabal.", 'fuerant', 'tempus', 'v:ind.imperf.act.3.pl', "l’enlèvement est présenté comme en cours"),
      ],
      note="Segond ne rend ni Siquidem et ni captivæ ; la cible est l’auxiliaire fuerant (ductæ fuerant)."),
    Q('th-modus-imperativus', 'ISA 10:30',
      target=('Hinni', 'v:imp.praes.act.2.sg'),
      gloss={'Gallim': 'Gallim', 'attende': 'prends garde (attendo)'},
      dist=[
        ("Tu fais éclater ta voix, fille de Gallim! Prends garde, Laïs! Malheur à toi, Anathoth!", 'Hinni', 'modus', 'v:ind.praes.act.2.sg', "l’ordre devient un constat"),
        ("Tu feras éclater ta voix, fille de Gallim! Prends garde, Laïs! Malheur à toi, Anathoth!", 'Hinni', 'modus', 'v:ind.fut.act.2.sg', "l’ordre devient une prédiction"),
        ("Faites éclater votre voix, filles de Gallim! Prends garde, Laïs! Malheur à toi, Anathoth!", 'Hinni', 'numerus', 'v:imp.praes.act.2.pl', "plusieurs destinataires"),
      ],
      note="Segond rend hinni (« hennis ») par « Fais éclater ta voix » et paupercula par « Malheur à toi » ; la cible est l’impératif Hinni."),
    Q('th-tempus-futurum', 'PSA 60:5',
      target=('Inhabitabo', 'v:ind.fut.act.1.sg'),
      paed=True, fr="J’habiterai dans ta tente pour les siècles ; je serai protégé sous le voile de tes ailes.",
      dist=[
        ("J’habite dans ta tente pour les siècles ; je serai protégé sous le voile de tes ailes.", 'Inhabitabo', 'tempus', 'v:ind.praes.act.1.sg', "le séjour est actuel"),
        ("J’ai habité dans ta tente pour les siècles ; je serai protégé sous le voile de tes ailes.", 'Inhabitabo', 'tempus', 'v:ind.perf.act.1.sg', "le séjour est déjà accompli"),
        ("Nous habiterons dans ta tente pour les siècles ; je serai protégé sous le voile de tes ailes.", 'Inhabitabo', 'numerus', 'v:ind.fut.act.1.pl', "plusieurs habitants"),
      ],
      note="Segond 61:5 a le conditionnel (« Je voudrais séjourner… Me réfugier ») pour les futurs latins ; rendu pédagogique."),
    Q('th-persona', 'COL 2:7',
      target=('didicistis', 'v:ind.perf.act.2.pl'),
      paed=True, fr="enracinés et édifiés en lui, et affermis dans la foi, comme vous l’avez appris, abondant en lui en action de grâces.",
      dist=[
        ("enracinés et édifiés en lui, et affermis dans la foi, comme nous l’avons appris, abondant en lui en action de grâces.", 'didicistis', 'persona', 'v:ind.perf.act.1.pl', "l’auteur s’inclut parmi ceux qui ont appris"),
        ("enracinés et édifiés en lui, et affermis dans la foi, comme ils l’ont appris, abondant en lui en action de grâces.", 'didicistis', 'persona', 'v:ind.perf.act.3.pl', "on parle de tiers"),
        ("enracinés et édifiés en lui, et affermis dans la foi, comme tu l’as appris, abondant en lui en action de grâces.", 'didicistis', 'numerus', 'v:ind.perf.act.2.sg', "un seul destinataire"),
      ],
      note="Segond (« d’après les instructions qui vous ont été données ») ne rend pas le verbe didicistis ; rendu pédagogique."),
    Q('th-tempus-praeteritum', 'JER 48:32',
      target=('irruit', 'v:ind.perf.act.3.sg'),
      la='super messem tuam et vindemiam tuam prædo irruit',
      fr='Le dévastateur s’est jeté sur ta récolte et sur ta vendange',
      dist=[
        ("Le dévastateur se jettera sur ta récolte et sur ta vendange", 'irruit', 'tempus', 'v:ind.fut.act.3.sg', "le ravage est annoncé"),
        ("Le dévastateur se jetait sur ta récolte et sur ta vendange", 'irruit', 'tempus', 'v:ind.imperf.act.3.sg', "un fait accompli devient une action qui dure"),
        ("Les dévastateurs se sont jetés sur ta récolte et sur ta vendange", 'irruit', 'numerus', 'v:ind.perf.act.3.pl', "plusieurs dévastateurs"),
      ],
      note="Segond a le présent et l’imparfait pour plorabo, transierunt, pervenerunt ; seule la dernière proposition est retenue."),
    Q('th-vox', 'NUM 35:17',
      target=('punietur', 'v:ind.fut.pass.3.sg'),
      paed=True, fr="S’il jette une pierre et que celui qui est frappé meure, il sera puni de la même manière.",
      dist=[
        ("S’il jette une pierre et que celui qui est frappé meure, il punira de la même manière.", 'punietur', 'vox', 'v:ind.fut.act.3.sg', "le coupable devient celui qui punit"),
        ("S’il jette une pierre et que celui qui est frappé meure, il est puni de la même manière.", 'punietur', 'tempus', 'v:ind.praes.pass.3.sg', "la sanction est présentée comme actuelle"),
        ("S’il jette une pierre et que celui qui est frappé meure, ils seront punis de la même manière.", 'punietur', 'numerus', 'v:ind.fut.pass.3.pl', "plusieurs coupables"),
      ],
      note="Segond (« c’est un meurtrier: le meurtrier sera puni de mort ») explicite d’après l’hébreu ; rendu pédagogique."),
    Q('th-nonfinita', 'SOL 5:13',
      target=('distillantia', 'v:part.praes.act.nom.pl.n'),
      paed=True, fr="Ses joues sont comme des parterres d’aromates, plantés par les parfumeurs. Ses lèvres sont des lis, distillant la myrrhe première.",
      dist=[
        ("Ses joues sont comme des parterres d’aromates, plantés par les parfumeurs. Ses lèvres sont des lis, qui vont distiller la myrrhe première.", 'distillantia', 'tempus', 'v:part.fut.act.nom.pl.n', "la myrrhe ne coule pas encore"),
        ("Ses joues sont comme des parterres d’aromates, plantés par les parfumeurs. Ses lèvres sont un lis, distillant la myrrhe première.", 'lilia', 'numerus', 'n:nom.pl>n:nom.sg', "un seul lis"),
        ("Ses joues sont comme un parterre d’aromates, planté par les parfumeurs. Ses lèvres sont des lis, distillant la myrrhe première.", 'areolæ', 'numerus', 'n:nom.pl>n:nom.sg', "un seul parterre"),
      ],
      note="Segond (« Une couche de plantes odorantes… D’où découle la myrrhe ») suit l’hébreu et ne rend pas le participe distillantia ; rendu pédagogique."),
    Q('th-numerus', 'PRO 17:4',
      target=('obedit', 'v:ind.praes.act.3.sg'),
      paed=True, fr="Le méchant obéit à la langue inique, et le trompeur se soumet aux lèvres menteuses.",
      dist=[
        ("Les méchants obéissent à la langue inique, et le trompeur se soumet aux lèvres menteuses.", 'obedit', 'numerus', 'v:ind.praes.act.3.pl', "plusieurs méchants"),
        ("Le méchant obéit aux langues iniques, et le trompeur se soumet aux lèvres menteuses.", 'linguæ', 'numerus', 'n:dat.sg>n:dat.pl', "plusieurs langues"),
        ("Le méchant obéit à la langue inique, et le trompeur se soumet à la lèvre menteuse.", 'labiis', 'numerus', 'n:dat.pl>n:dat.sg', "une seule lèvre"),
      ],
      note="Segond (« est attentif à la lèvre inique… prête l’oreille à la langue pernicieuse ») intervertit lèvre et langue ; rendu pédagogique."),
    Q('th-persona', 'LAM 1:13',
      target=('misit', 'v:ind.perf.act.3.sg'),
      gloss={'Mem': 'mem (lettre hébraïque)'},
      dist=[
        ("D’en haut tu as lancé dans mes os un feu qui les dévore; Il a tendu un filet sous mes pieds, Il m’a fait tomber en arrière; Il m’a jetée dans la désolation, dans une langueur de tous les jours.", 'misit', 'persona', 'v:ind.perf.act.2.sg', "on s’adresse à Dieu au lieu de parler de lui"),
        ("D’en haut j’ai lancé dans mes os un feu qui les dévore; Il a tendu un filet sous mes pieds, Il m’a fait tomber en arrière; Il m’a jetée dans la désolation, dans une langueur de tous les jours.", 'misit', 'persona', 'v:ind.perf.act.1.sg', "la victime devient l’auteur du feu"),
        ("D’en haut ils ont lancé dans mes os un feu qui les dévore; Il a tendu un filet sous mes pieds, Il m’a fait tomber en arrière; Il m’a jetée dans la désolation, dans une langueur de tous les jours.", 'misit', 'numerus', 'v:ind.perf.act.3.pl', "plusieurs auteurs du châtiment"),
      ],
      note="Segond a « un feu qui les dévore » pour et erudivit me (d’après l’hébreu) ; la cible est misit."),
    Q('th-modus-subiunctivus', 'PHI 2:10',
      target=('flectatur', 'v:subj.praes.pass.3.sg'),
      dist=[
        ("au nom de Jésus tout genou fléchit dans les cieux, sur la terre et sous la terre,", 'flectatur', 'modus', 'v:ind.praes.pass.3.sg', "le but devient un constat"),
        ("afin qu’au nom de Jésus tous les genoux fléchissent dans les cieux, sur la terre et sous la terre,", 'flectatur', 'numerus', 'v:subj.praes.pass.3.pl', "plusieurs genoux"),
        ("afin qu’au nom de Jésus tout genou fléchît dans les cieux, sur la terre et sous la terre,", 'flectatur', 'tempus', 'v:subj.imperf.pass.3.sg', "la finalité est rejetée dans le passé"),
      ],
      note="Segond rend cælestium, terrestrium et infernorum par des compléments de lieu ; la cible est flectatur."),
    Q('th-tempus-futurum', 'LEV 11:42',
      target=('comedetis', 'v:ind.fut.act.2.pl'),
      dist=[
        ("Vous ne mangez point, parmi tous les reptiles qui rampent sur la terre, de tous ceux qui se traînent sur le ventre, ni de tous ceux qui marchent sur quatre pieds ou sur un grand nombre de pieds; car vous les aurez en abomination.", 'comedetis', 'tempus', 'v:ind.praes.act.2.pl', "l’interdiction devient un constat présent"),
        ("Vous n’avez point mangé, parmi tous les reptiles qui rampent sur la terre, de tous ceux qui se traînent sur le ventre, ni de tous ceux qui marchent sur quatre pieds ou sur un grand nombre de pieds; car vous les aurez en abomination.", 'comedetis', 'tempus', 'v:ind.perf.act.2.pl', "l’interdiction est rejetée dans le passé"),
        ("Vous ne mangiez point, parmi tous les reptiles qui rampent sur la terre, de tous ceux qui se traînent sur le ventre, ni de tous ceux qui marchent sur quatre pieds ou sur un grand nombre de pieds; car vous les aurez en abomination.", 'comedetis', 'tempus', 'v:ind.imperf.act.2.pl', "une habitude passée au lieu d’un ordre"),
      ],
      note="Segond réorganise le verset d’après l’hébreu ; la cible est comedetis."),
    Q('th-modus-imperativus', '1TI 4:7',
      target=('devita', 'v:imp.praes.act.2.sg'),
      la='Ineptas autem, et aniles fabulas devita',
      fr='Repousse les contes profanes et absurdes',
      dist=[
        ("Repoussez les contes profanes et absurdes", 'devita', 'numerus', 'v:imp.praes.act.2.pl', "l’ordre s’adresse à plusieurs personnes"),
        ("Tu repousses les contes profanes et absurdes", 'devita', 'modus', 'v:ind.praes.act.2.sg', "l’ordre devient un constat"),
        ("Repousse le conte profane et absurde", 'fabulas', 'numerus', 'n:acc.pl>n:acc.sg', "un seul conte"),
      ],
      note="Segond rend ineptas et aniles par « profanes et absurdes » ; la seconde moitié du verset est en 4:8 chez Segond."),
    Q('th-tempus-praeteritum', 'JOB 39:28',
      target=('manet', 'v:ind.praes.act.3.sg'),
      fr_ref='JOB 39:31',
      dist=[
        ("C’est dans les rochers qu’il a habité, qu’il a sa demeure, Sur la cime des rochers, sur le sommet des monts.", 'manet', 'tempus', 'v:ind.perf.act.3.sg', "le séjour est révolu"),
        ("C’est dans les rochers qu’il habitera, qu’il a sa demeure, Sur la cime des rochers, sur le sommet des monts.", 'manet', 'tempus', 'v:ind.fut.act.3.sg', "le séjour est annoncé"),
        ("C’est dans le rocher qu’il habite, qu’il a sa demeure, Sur la cime des rochers, sur le sommet des monts.", 'petris', 'numerus', 'n:abl.pl>n:abl.sg', "un seul rocher"),
      ],
      note="Segond 39:31 (numérotation décalée) ; Segond rend commoratur par « il a sa demeure » ; la cible est manet."),
    Q('th-tempus-praeteritum', 'SIR 36:28',
      target=('credit', 'v:ind.praes.act.3.sg'),
      paed=True, fr="Qui fait confiance à celui qui n’a pas de nid, qui se détourne partout où la nuit le surprend, comme un brigand ceint bondissant de ville en ville ?",
      dist=[
        ("Qui a fait confiance à celui qui n’a pas de nid, qui se détourne partout où la nuit le surprend, comme un brigand ceint bondissant de ville en ville ?", 'credit', 'tempus', 'v:ind.perf.act.3.sg', "la confiance est rejetée dans le passé"),
        ("Qui fera confiance à celui qui n’a pas de nid, qui se détourne partout où la nuit le surprend, comme un brigand ceint bondissant de ville en ville ?", 'credit', 'tempus', 'v:ind.fut.act.3.sg', "la confiance est envisagée pour l’avenir"),
        ("Qui fait confiance à ceux qui n’ont pas de nid, qui se détournent partout où la nuit les surprend, comme des brigands ceints bondissant de ville en ville ?", 'habet', 'numerus', 'v:ind.praes.act.3.sg>v:ind.praes.act.3.pl', "plusieurs vagabonds"),
      ],
      note="Livre absent de Segond ; rendu pédagogique (obscuraverit : « là où la nuit le surprend »)."),
    Q('th-tempus-praeteritum', 'NUM 26:58',
      target=('genuit', 'v:ind.perf.act.3.sg'),
      la='At vero Caath genuit Amram',
      fr='Kehath engendra Amram',
      gloss={'Amram': 'Amram'},
      dist=[
        ("Kehath engendre Amram", 'genuit', 'tempus', 'v:ind.perf.act.3.sg>v:ind.praes.act.3.sg', "la naissance est présentée comme actuelle"),
        ("Kehath engendrera Amram", 'genuit', 'tempus', 'v:ind.fut.act.3.sg', "la naissance est annoncée"),
        ("Kehath engendrait Amram", 'genuit', 'tempus', 'v:ind.imperf.act.3.sg', "un fait accompli devient une action qui dure"),
      ],
      note="Segond ne rend pas At vero ; dernière proposition du verset."),
    Q('th-casus-obliqui', '1CH 6:77',
      target=('Filiis', 'n:dat.pl'),
      paed=True, fr="Et aux autres fils de Merari : de la tribu de Zabulon, Rimmono et ses faubourgs, et Thabor et ses faubourgs.",
      gloss={'Remmono': 'Rimmono', 'sus': 'ses (coquille pour suis)'},
      dist=[
        ("Et les autres fils de Merari : de la tribu de Zabulon, Rimmono et ses faubourgs, et Thabor et ses faubourgs.", 'Filiis', 'casus', 'n:nom.pl', "les fils ne sont plus les bénéficiaires mais le sujet"),
        ("Et à l’autre fils de Merari : de la tribu de Zabulon, Rimmono et ses faubourgs, et Thabor et ses faubourgs.", 'Filiis', 'numerus', 'n:dat.sg', "un seul fils"),
        ("Et aux autres fils de Merari : de la tribu de Zabulon, Rimmono et son faubourg, et Thabor et ses faubourgs.", 'suburbana', 'numerus', 'a:acc.pl.n>a:acc.sg.n', "un seul faubourg"),
      ],
      note="Segond (« On donna au reste des Lévites, aux fils de Merari ») explicite un verbe ; rendu pédagogique ; « sus » est une coquille du texte pour suis."),
    Q('th-vox', 'ISA 25:10',
      target=('triturabitur', 'v:ind.fut.pass.3.sg'),
      paed=True, fr="Car la main du Seigneur reposera sur cette montagne ; et Moab sera foulé sous lui, comme les pailles sont foulées dans le chariot.",
      dist=[
        ("Car la main du Seigneur reposera sur cette montagne ; et Moab foulera sous lui, comme les pailles sont foulées dans le chariot.", 'triturabitur', 'vox', 'v:ind.fut.act.3.sg', "Moab devient celui qui foule"),
        ("Car la main du Seigneur reposera sur cette montagne ; et Moab est foulé sous lui, comme les pailles sont foulées dans le chariot.", 'triturabitur', 'tempus', 'v:ind.praes.pass.3.sg', "le châtiment est actuel"),
        ("Car la main du Seigneur reposera sur cette montagne ; et Moab sera foulé sous lui, comme la paille est foulée dans le chariot.", 'paleæ', 'numerus', 'n:nom.pl>n:nom.sg', "une seule paille"),
      ],
      note="Segond (« repose… est foulé… dans une mare à fumier ») a le présent et suit l’hébreu ; rendu pédagogique des futurs latins."),
    Q('th-modus-imperativus', 'MIC 6:5',
      target=('memento', 'v:imp.fut.act.2.sg'),
      gloss={'Balach': 'Balak', 'Beor': 'Beor'},
      dist=[
        ("Mon peuple, tu te rappelles ce que projetait Balak, roi de Moab, Et ce que lui répondit Balaam, fils de Beor, De Sittim à Guilgal, Afin que tu reconnaisses les bienfaits de l’Éternel.", 'memento', 'modus', 'v:ind.perf.act.2.sg', "l’ordre devient un constat"),
        ("Mon peuple, rappelle-toi ce que projetait Balak, roi de Moab, Et ce que lui répondit Balaam, fils de Beor, De Sittim à Guilgal, Afin que vous reconnaissiez les bienfaits de l’Éternel.", 'cognosceres', 'numerus', 'v:subj.imperf.act.2.sg>v:subj.imperf.act.2.pl', "plusieurs destinataires de la leçon"),
        ("Mon peuple, rappelle-toi ce que projetait Balak, roi de Moab, Et ce que lui répondit Balaam, fils de Beor, De Sittim à Guilgal, Afin qu’il reconnaisse les bienfaits de l’Éternel.", 'cognosceres', 'persona', 'v:subj.imperf.act.2.sg>v:subj.imperf.act.3.sg', "un tiers doit reconnaître"),
      ],
      note="Segond rend cogitaverit et responderit par des passés et justitias par « bienfaits » ; la cible est memento."),
    Q('th-tempus-futurum', 'EXO 28:25',
      target=('copulabis', 'v:ind.fut.act.2.sg'),
      dist=[
        ("et tu arrêtes par devant les bouts des deux cordons aux deux montures placées sur les épaulettes de l’éphod.", 'copulabis', 'tempus', 'v:ind.praes.act.2.sg', "l’instruction devient une description présente"),
        ("et tu as arrêté par devant les bouts des deux cordons aux deux montures placées sur les épaulettes de l’éphod.", 'copulabis', 'tempus', 'v:ind.perf.act.2.sg', "le travail est déjà fait"),
        ("et vous arrêterez par devant les bouts des deux cordons aux deux montures placées sur les épaulettes de l’éphod.", 'copulabis', 'numerus', 'v:ind.fut.act.2.pl', "plusieurs artisans"),
      ],
      note="Segond paraphrase la fin (« placées sur les épaulettes de l’éphod » pour in utroque latere superhumeralis quod rationale respicit) ; la cible est copulabis."),
    Q('th-persona', 'ECC 11:5',
      target=('nescis', 'v:ind.praes.act.2.sg'),
      gloss={'fabricator': 'artisan, auteur (fabricator)'},
      dist=[
        ("Comme tu ne sais pas quel est le chemin du vent, ni comment se forment les os dans le ventre de la femme enceinte, il ne connaît pas non plus l’œuvre de Dieu qui fait tout.", 'nescis', 'persona', 'v:ind.praes.act.3.sg', "on parle d’un tiers"),
        ("Comme tu ne sais pas quel est le chemin du vent, ni comment se forment les os dans le ventre de la femme enceinte, je ne connais pas non plus l’œuvre de Dieu qui fait tout.", 'nescis', 'persona', 'v:ind.praes.act.1.sg', "le sage s’applique l’ignorance"),
        ("Comme tu ne sais pas quel est le chemin du vent, ni comment se forment les os dans le ventre de la femme enceinte, vous ne connaissez pas non plus l’œuvre de Dieu qui fait tout.", 'nescis', 'numerus', 'v:ind.praes.act.2.pl', "plusieurs destinataires"),
      ],
      note="Segond a « l’œuvre » (singulier) pour opera et « qui fait tout » pour fabricator est omnium ; la cible est nescis."),
    Q('th-numerus', 'GAL 5:20',
      target=('contentiones', 'n:nom.pl'),
      gloss={'servitus': 'servitude, culte (servitus)', 'sectæ': 'sectes, partis (secta)'},
      dist=[
        ("l’idolâtrie, la magie, les inimitiés, la querelle, les jalousies, les animosités, les disputes, les divisions, les sectes,", 'contentiones', 'numerus', 'n:nom.sg', "une seule querelle"),
        ("l’idolâtrie, la magie, les inimitiés, les querelles, la jalousie, les animosités, les disputes, les divisions, les sectes,", 'æmulationes', 'numerus', 'n:nom.pl>n:nom.sg', "une seule jalousie"),
        ("l’idolâtrie, la magie, les inimitiés, les querelles, les jalousies, l’animosité, les disputes, les divisions, les sectes,", 'iræ', 'numerus', 'n:nom.pl>n:nom.sg', "une seule animosité"),
      ],
      note="Segond a « la magie » (singulier) pour veneficia ; la cible est contentiones."),
]
