/// Contextual items — section "casus". Authored by hand; see syntagma.dart for
/// the markers (`{target}`, `[head]`, `<candidate>`).
library;

import '../../../linguistics/model/grammar.dart';
import '../../../linguistics/model/nominal.dart';
import '../syntagma.dart';

// ignore_for_file: unused_import

const List<Syntagma> kCasusSyntagmata = [
  // ------------------------------------------------------------ cas-verba-dat
  // Datives governed by the verb.
  Syntagma(id: 'cas-verba-dat-001', text: 'mīlitēs {ducī} pārent', lemmaId: 'dux', casus: Casus.dativus, number: Numerus.singularis, functio: Functio.obiectumDativum, tags: {'cas-verba-dat'}, note: 'Pāreō datīvum regit: oboediēns sum ducī.'),
  Syntagma(id: 'cas-verba-dat-002', text: 'servus {dominō} servit', lemmaId: 'dominus', casus: Casus.dativus, number: Numerus.singularis, functio: Functio.obiectumDativum, tags: {'cas-verba-dat'}, note: 'Serviō datīvum regit: servus est dominō.'),
  Syntagma(id: 'cas-verba-dat-003', text: 'fābula {puerīs} placet', lemmaId: 'puer', casus: Casus.dativus, number: Numerus.pluralis, functio: Functio.obiectumDativum, tags: {'cas-verba-dat'}, note: 'Placeō datīvum regit: fābula grāta est puerīs.'),
  Syntagma(id: 'cas-verba-dat-004', text: 'fūmus {oculīs} nocet', lemmaId: 'oculus', casus: Casus.dativus, number: Numerus.pluralis, functio: Functio.obiectumDativum, tags: {'cas-verba-dat'}, note: 'Noceō datīvum regit: fūmus malus est oculīs.'),
  Syntagma(id: 'cas-verba-dat-005', text: 'populus {cōnsulī} favet', lemmaId: 'consul', casus: Casus.dativus, number: Numerus.singularis, functio: Functio.obiectumDativum, tags: {'cas-verba-dat'}, note: 'Faveō datīvum regit: populus amīcus est cōnsulī.'),
  Syntagma(id: 'cas-verba-dat-006', text: 'Mārcus {magistrō} nōn crēdit', lemmaId: 'magister', casus: Casus.dativus, number: Numerus.singularis, functio: Functio.obiectumDativum, tags: {'cas-verba-dat'}, note: 'Crēdō datīvum regit: fidem habeō magistrō.'),
  Syntagma(id: 'cas-verba-dat-007', text: 'dominus {servīs} parcit', lemmaId: 'servus', casus: Casus.dativus, number: Numerus.pluralis, functio: Functio.obiectumDativum, tags: {'cas-verba-dat'}, note: 'Parcō datīvum regit: dominus clēmēns est servīs.'),
  Syntagma(id: 'cas-verba-dat-008', text: 'discipulus {litterīs} studet', lemmaId: 'littera', casus: Casus.dativus, number: Numerus.pluralis, functio: Functio.obiectumDativum, tags: {'cas-verba-dat'}, note: 'Studeō datīvum regit: animum intendō litterīs.'),
  Syntagma(id: 'cas-verba-dat-009', text: 'pater {fīliō} persuādet', lemmaId: 'filius', casus: Casus.dativus, number: Numerus.singularis, functio: Functio.obiectumDativum, tags: {'cas-verba-dat'}, note: 'Persuādeō datīvum regit, nōn accūsātīvum: fīliō persuādet.'),
  Syntagma(id: 'cas-verba-dat-010', text: 'imperātor {mīlitibus} imperat', lemmaId: 'miles', casus: Casus.dativus, number: Numerus.pluralis, functio: Functio.obiectumDativum, tags: {'cas-verba-dat'}, note: 'Imperō datīvum regit: imperium dō mīlitibus.'),
  Syntagma(id: 'cas-verba-dat-011', text: 'puer {patrī} respondet', lemmaId: 'pater', casus: Casus.dativus, number: Numerus.singularis, functio: Functio.obiectumDativum, tags: {'cas-verba-dat'}, note: 'Respondeō datīvum regit: respōnsum dō patrī.'),
  Syntagma(id: 'cas-verba-dat-012', text: 'nāvis {portuī} appropinquat', lemmaId: 'portus', casus: Casus.dativus, number: Numerus.singularis, functio: Functio.obiectumDativum, tags: {'cas-verba-dat'}, note: 'Appropinquō datīvum regit: prope veniō portuī.'),
  Syntagma(id: 'cas-verba-dat-013', text: 'rēx {lēgibus} pāret', lemmaId: 'lex', casus: Casus.dativus, number: Numerus.pluralis, functio: Functio.obiectumDativum, tags: {'cas-verba-dat'}, note: 'Pāreō datīvum regit: rēx quoque oboedit lēgibus.'),
  // Contrast: direct objects.
  Syntagma(id: 'cas-verba-dat-014', text: 'mīlitēs {ducem} laudant', lemmaId: 'dux', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'cas-verba-dat'}, note: 'Laudō trānsitīvum est: accūsātīvum regit, nōn datīvum.'),
  Syntagma(id: 'cas-verba-dat-015', text: 'servus {dominum} timet', lemmaId: 'dominus', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'cas-verba-dat'}, note: 'Timeō trānsitīvum est: dominum accūsātīvus obiectum.'),
  Syntagma(id: 'cas-verba-dat-016', text: 'pater {fīlium} vocat', lemmaId: 'filius', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'cas-verba-dat'}, note: 'Vocō trānsitīvum est: fīlium accūsātīvus obiectum.'),
  Syntagma(id: 'cas-verba-dat-017', text: 'medicus {oculōs} spectat', lemmaId: 'oculus', casus: Casus.accusativus, number: Numerus.pluralis, functio: Functio.obiectum, tags: {'cas-verba-dat'}, note: 'Spectō trānsitīvum est: oculōs accūsātīvus plūrālis obiectum.'),
  Syntagma(id: 'cas-verba-dat-018', text: 'discipulī {magistrum} audiunt', lemmaId: 'magister', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'cas-verba-dat'}, note: 'Audiō trānsitīvum est: magistrum accūsātīvus obiectum.'),
  Syntagma(id: 'cas-verba-dat-019', text: 'imperātor {mīlitēs} dūcit', lemmaId: 'miles', casus: Casus.accusativus, number: Numerus.pluralis, functio: Functio.obiectum, tags: {'cas-verba-dat'}, note: 'Dūcō trānsitīvum est: mīlitēs accūsātīvus obiectum, nōn datīvus ut post imperō.'),
  Syntagma(id: 'cas-verba-dat-020', text: 'puer {patrem} amat', lemmaId: 'pater', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'cas-verba-dat'}, note: 'Amō trānsitīvum est: patrem accūsātīvus obiectum.'),
  // Contrast: dative of the person given to.
  Syntagma(id: 'cas-verba-dat-021', text: 'dominus {servō} pecūniam dat', lemmaId: 'servus', casus: Casus.dativus, number: Numerus.singularis, functio: Functio.datum, tags: {'cas-verba-dat'}, note: 'Datīvus persōnae cui datur: servō pecūnia datur.'),
  Syntagma(id: 'cas-verba-dat-022', text: 'Iūlius {Aemiliae} ōsculum dat', lemmaId: 'aemilia', casus: Casus.dativus, number: Numerus.singularis, functio: Functio.datum, tags: {'cas-verba-dat'}, note: 'Datīvus persōnae cui datur: Aemiliae ōsculum datur.'),
  Syntagma(id: 'cas-verba-dat-023', text: 'māter {īnfantī} lac dat', lemmaId: 'infans', casus: Casus.dativus, number: Numerus.singularis, functio: Functio.datum, tags: {'cas-verba-dat'}, note: 'Datīvus persōnae cui datur: īnfantī lac datur.'),

  // ------------------------------------------------------------ cas-verba-abl
  // Ablatives governed by the verb.
  Syntagma(id: 'cas-verba-abl-001', text: 'mīles {gladiō} ūtitur', lemmaId: 'gladius', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.obiectumAblativum, tags: {'cas-verba-abl'}, note: 'Ūtor ablātīvum regit: gladiō ūtitur, nōn gladium.'),
  Syntagma(id: 'cas-verba-abl-002', text: 'agricola {agrīs} fruitur', lemmaId: 'ager', casus: Casus.ablativus, number: Numerus.pluralis, functio: Functio.obiectumAblativum, tags: {'cas-verba-abl'}, note: 'Fruor ablātīvum regit: frūctum capit ex agrīs.'),
  Syntagma(id: 'cas-verba-abl-003', text: 'cōnsul {mūnere} fungitur', lemmaId: 'munus', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.obiectumAblativum, tags: {'cas-verba-abl'}, note: 'Fungor ablātīvum regit: mūnere fungitur.'),
  Syntagma(id: 'cas-verba-abl-004', text: 'hostēs {urbe} potiuntur', lemmaId: 'urbs', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.obiectumAblativum, tags: {'cas-verba-abl'}, note: 'Potior ablātīvum regit: urbe potiuntur, id est urbem capiunt.'),
  Syntagma(id: 'cas-verba-abl-005', text: 'pāstor {pāne} vescitur', lemmaId: 'panis', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.obiectumAblativum, tags: {'cas-verba-abl'}, note: 'Vescor ablātīvum regit: pāne vescitur, id est pānem ēst.'),
  Syntagma(id: 'cas-verba-abl-006', text: 'bōs {herbā} vescitur', lemmaId: 'herba', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.obiectumAblativum, tags: {'cas-verba-abl'}, note: 'Vescor ablātīvum regit: herbā vescitur.'),
  Syntagma(id: 'cas-verba-abl-007', text: 'servus {pecūniā} caret', lemmaId: 'pecunia', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.obiectumAblativum, tags: {'cas-verba-abl'}, note: 'Careō ablātīvum regit: pecūniā caret, id est pecūniam nōn habet.'),
  Syntagma(id: 'cas-verba-abl-008', text: 'pauper {cibō} eget', lemmaId: 'cibus', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.obiectumAblativum, tags: {'cas-verba-abl'}, note: 'Egeō ablātīvum regit: cibō eget.'),
  Syntagma(id: 'cas-verba-abl-009', text: 'nōbīs {aquā} opus est', lemmaId: 'aqua', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.obiectumAblativum, tags: {'cas-verba-abl'}, note: 'Opus est ablātīvum regit: aquā opus est nōbīs.'),
  Syntagma(id: 'cas-verba-abl-010', text: 'mīlitī {armīs} opus est', lemmaId: 'arma', casus: Casus.ablativus, number: Numerus.pluralis, functio: Functio.obiectumAblativum, tags: {'cas-verba-abl'}, note: 'Opus est ablātīvum regit: armīs opus est mīlitī.'),
  Syntagma(id: 'cas-verba-abl-011', text: 'nauta {ventō} ūtitur', lemmaId: 'ventus', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.obiectumAblativum, tags: {'cas-verba-abl'}, note: 'Ūtor ablātīvum regit: ventō ūtitur nauta.'),
  Syntagma(id: 'cas-verba-abl-012', text: 'Mēdus {lībertāte} fruitur', lemmaId: 'libertas', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.obiectumAblativum, tags: {'cas-verba-abl'}, note: 'Fruor ablātīvum regit: lībertāte fruitur.'),
  // Contrast: direct objects.
  Syntagma(id: 'cas-verba-abl-013', text: 'mīles {gladium} tenet', lemmaId: 'gladius', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'cas-verba-abl'}, note: 'Teneō trānsitīvum est: gladium accūsātīvus obiectum.'),
  Syntagma(id: 'cas-verba-abl-014', text: 'agricola {agrōs} colit', lemmaId: 'ager', casus: Casus.accusativus, number: Numerus.pluralis, functio: Functio.obiectum, tags: {'cas-verba-abl'}, note: 'Colō trānsitīvum est: agrōs accūsātīvus obiectum.'),
  Syntagma(id: 'cas-verba-abl-015', text: 'servus {pecūniam} amat', lemmaId: 'pecunia', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'cas-verba-abl'}, note: 'Amō trānsitīvum est: pecūniam accūsātīvus obiectum.'),
  Syntagma(id: 'cas-verba-abl-016', text: 'puer {aquam} bibit', lemmaId: 'aqua', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'cas-verba-abl'}, note: 'Bibō trānsitīvum est: aquam accūsātīvus obiectum.'),
  Syntagma(id: 'cas-verba-abl-017', text: 'hostēs {urbem} oppugnant', lemmaId: 'urbs', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'cas-verba-abl'}, note: 'Oppugnō trānsitīvum est: urbem accūsātīvus obiectum.'),
  // Contrast: instrument.
  Syntagma(id: 'cas-verba-abl-018', text: 'mīles {gladiō} pugnat', lemmaId: 'gladius', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.instrumentum, tags: {'cas-verba-abl'}, note: 'Ablātīvus īnstrūmentī: pugnō nōn regit ablātīvum, sed gladiō dīcit quō īnstrūmentō.'),
  Syntagma(id: 'cas-verba-abl-019', text: 'servus {baculō} verberātur', lemmaId: 'baculum', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.instrumentum, tags: {'cas-verba-abl'}, note: 'Ablātīvus īnstrūmentī: baculō verberātur, quō īnstrūmentō.'),
  Syntagma(id: 'cas-verba-abl-020', text: 'puer {oculīs} videt', lemmaId: 'oculus', casus: Casus.ablativus, number: Numerus.pluralis, functio: Functio.instrumentum, tags: {'cas-verba-abl'}, note: 'Ablātīvus īnstrūmentī: oculīs videt, quibus īnstrūmentīs.'),

  // ------------------------------------------------------------ cas-verba-gen
  // Genitives after meminī / oblīvīscor.
  Syntagma(id: 'cas-verba-gen-001', text: 'Mārcus {patris} meminit', lemmaId: 'pater', casus: Casus.genetivus, number: Numerus.singularis, functio: Functio.obiectumGenetivum, tags: {'cas-verba-gen'}, note: 'Meminī genetīvum regit: patris meminit.'),
  Syntagma(id: 'cas-verba-gen-002', text: 'fīlius {mātris} nōn oblīvīscitur', lemmaId: 'mater', casus: Casus.genetivus, number: Numerus.singularis, functio: Functio.obiectumGenetivum, tags: {'cas-verba-gen'}, note: 'Oblīvīscor genetīvum regit: mātris oblīvīscitur.'),
  Syntagma(id: 'cas-verba-gen-003', text: 'mīlitēs {ducis} meminērunt', lemmaId: 'dux', casus: Casus.genetivus, number: Numerus.singularis, functio: Functio.obiectumGenetivum, tags: {'cas-verba-gen'}, note: 'Meminī genetīvum regit: ducis meminērunt.'),
  Syntagma(id: 'cas-verba-gen-004', text: 'senex {amīcōrum} oblīvīscitur', lemmaId: 'amicus', casus: Casus.genetivus, number: Numerus.pluralis, functio: Functio.obiectumGenetivum, tags: {'cas-verba-gen'}, note: 'Oblīvīscor genetīvum regit: amīcōrum genetīvus plūrālis.'),
  // Genitives after adjectives.
  Syntagma(id: 'cas-verba-gen-005', text: 'saccus plēnus {nummōrum} est', lemmaId: 'nummus', casus: Casus.genetivus, number: Numerus.pluralis, functio: Functio.obiectumGenetivum, tags: {'cas-verba-gen'}, note: 'Plēnus genetīvum regit: plēnus nummōrum.'),
  Syntagma(id: 'cas-verba-gen-006', text: 'iuvenis cupidus {glōriae} est', lemmaId: 'gloria', casus: Casus.genetivus, number: Numerus.singularis, functio: Functio.obiectumGenetivum, tags: {'cas-verba-gen'}, note: 'Cupidus genetīvum regit: cupidus glōriae.'),
  Syntagma(id: 'cas-verba-gen-007', text: 'mīles memor {patriae} est', lemmaId: 'patria', casus: Casus.genetivus, number: Numerus.singularis, functio: Functio.obiectumGenetivum, tags: {'cas-verba-gen'}, note: 'Memor genetīvum regit: memor patriae.'),
  Syntagma(id: 'cas-verba-gen-008', text: 'nauta perītus {maris} est', lemmaId: 'mare', casus: Casus.genetivus, number: Numerus.singularis, functio: Functio.obiectumGenetivum, tags: {'cas-verba-gen'}, note: 'Perītus genetīvum regit: perītus maris.'),
  Syntagma(id: 'cas-verba-gen-009', text: 'pōculum plēnum {vīnī} est', lemmaId: 'vinum', casus: Casus.genetivus, number: Numerus.singularis, functio: Functio.obiectumGenetivum, tags: {'cas-verba-gen'}, note: 'Plēnus genetīvum regit: plēnum vīnī.'),
  // Partitive genitive.
  Syntagma(id: 'cas-verba-gen-010', text: 'Iūlius satis {pecūniae} habet', lemmaId: 'pecunia', casus: Casus.genetivus, number: Numerus.singularis, constructio: Constructio.genetivusPartitivus, functio: Functio.partitivum, tags: {'cas-verba-gen'}, note: 'Genetīvus partītīvus post satis: satis pecūniae.'),
  Syntagma(id: 'cas-verba-gen-011', text: 'nihil {aquae} in pōculō est', lemmaId: 'aqua', casus: Casus.genetivus, number: Numerus.singularis, constructio: Constructio.genetivusPartitivus, functio: Functio.partitivum, tags: {'cas-verba-gen'}, note: 'Genetīvus partītīvus post nihil: nihil aquae.'),
  Syntagma(id: 'cas-verba-gen-012', text: 'puer multum {temporis} perdit', lemmaId: 'tempus', casus: Casus.genetivus, number: Numerus.singularis, constructio: Constructio.genetivusPartitivus, functio: Functio.partitivum, tags: {'cas-verba-gen'}, note: 'Genetīvus partītīvus post multum: multum temporis.'),
  Syntagma(id: 'cas-verba-gen-013', text: 'servī parum {cibī} habent', lemmaId: 'cibus', casus: Casus.genetivus, number: Numerus.singularis, constructio: Constructio.genetivusPartitivus, functio: Functio.partitivum, tags: {'cas-verba-gen'}, note: 'Genetīvus partītīvus post parum: parum cibī.'),
  // Possessive genitive.
  Syntagma(id: 'cas-verba-gen-014', text: 'liber {puerī} in mēnsā est', lemmaId: 'puer', casus: Casus.genetivus, number: Numerus.singularis, functio: Functio.possessor, tags: {'cas-verba-gen'}, note: 'Genetīvus possessōris: liber puerī, cuius liber.'),
  Syntagma(id: 'cas-verba-gen-015', text: 'vīlla {dominī} magna est', lemmaId: 'dominus', casus: Casus.genetivus, number: Numerus.singularis, functio: Functio.possessor, tags: {'cas-verba-gen'}, note: 'Genetīvus possessōris: vīlla dominī, cuius vīlla.'),
  Syntagma(id: 'cas-verba-gen-016', text: 'fīlia {rēgis} pulchra est', lemmaId: 'rex', casus: Casus.genetivus, number: Numerus.singularis, functio: Functio.possessor, tags: {'cas-verba-gen'}, note: 'Genetīvus possessōris: fīlia rēgis, cuius fīlia.'),
  Syntagma(id: 'cas-verba-gen-017', text: 'dux {mīlitum} fortis est', lemmaId: 'miles', casus: Casus.genetivus, number: Numerus.pluralis, functio: Functio.possessor, tags: {'cas-verba-gen'}, note: 'Genetīvus complēmentī nōminis: dux mīlitum, quōrum dux.'),
  // Contrast: direct objects.
  Syntagma(id: 'cas-verba-gen-018', text: 'Mārcus {patrem} videt', lemmaId: 'pater', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'cas-verba-gen'}, note: 'Videō trānsitīvum est: patrem accūsātīvus obiectum, nōn genetīvus ut post meminī.'),
  Syntagma(id: 'cas-verba-gen-019', text: 'fīlius {mātrem} amat', lemmaId: 'mater', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'cas-verba-gen'}, note: 'Amō trānsitīvum est: mātrem accūsātīvus obiectum.'),
  Syntagma(id: 'cas-verba-gen-020', text: 'mīlitēs {ducem} sequuntur', lemmaId: 'dux', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'cas-verba-gen'}, note: 'Sequor accūsātīvum regit: ducem obiectum.'),
  Syntagma(id: 'cas-verba-gen-021', text: 'puer {librum} legit', lemmaId: 'liber', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'cas-verba-gen'}, note: 'Legō trānsitīvum est: librum accūsātīvus obiectum.'),

  // ---------------------------------------------------------- cas-prep-duplex
  // in + ablative (place where).
  Syntagma(id: 'cas-prep-duplex-001', text: 'puer in {hortō} ambulat', lemmaId: 'hortus', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.inAblativus, functio: Functio.locusUbi, tags: {'cas-prep-duplex'}, note: 'Ambulō verbum statūs est: in cum ablātīvō dīcit ubi.'),
  Syntagma(id: 'cas-prep-duplex-002', text: 'Aemilia in {vīllā} habitat', lemmaId: 'villa', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.inAblativus, functio: Functio.locusUbi, tags: {'cas-prep-duplex'}, note: 'Habitō verbum statūs est: in vīllā ablātīvus, ubi.'),
  Syntagma(id: 'cas-prep-duplex-003', text: 'mercātor in {urbe} habitat', lemmaId: 'urbs', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.inAblativus, functio: Functio.locusUbi, tags: {'cas-prep-duplex'}, note: 'Habitō verbum statūs est: in urbe ablātīvus, ubi.'),
  Syntagma(id: 'cas-prep-duplex-004', text: 'Iūlius in {Italiā} vīvit', lemmaId: 'italia', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.inAblativus, functio: Functio.locusUbi, tags: {'cas-prep-duplex'}, note: 'Vīvō verbum statūs est: in Italiā ablātīvus, ubi.'),
  Syntagma(id: 'cas-prep-duplex-005', text: 'piscēs in {marī} natant', lemmaId: 'mare', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.inAblativus, functio: Functio.locusUbi, tags: {'cas-prep-duplex'}, note: 'Natō verbum statūs est: in marī ablātīvus (-ī tertiae neutrīus), ubi.'),
  Syntagma(id: 'cas-prep-duplex-006', text: 'servī in {agrīs} labōrant', lemmaId: 'ager', casus: Casus.ablativus, number: Numerus.pluralis, constructio: Constructio.inAblativus, functio: Functio.locusUbi, tags: {'cas-prep-duplex'}, note: 'Labōrō verbum statūs est: in agrīs ablātīvus plūrālis, ubi.'),
  Syntagma(id: 'cas-prep-duplex-007', text: 'liber in {mēnsā} iacet', lemmaId: 'mensa', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.inAblativus, functio: Functio.locusUbi, tags: {'cas-prep-duplex'}, note: 'Iaceō verbum statūs est: in mēnsā ablātīvus, ubi.'),
  // in + accusative (motion into).
  Syntagma(id: 'cas-prep-duplex-008', text: 'puer in {hortum} currit', lemmaId: 'hortus', casus: Casus.accusativus, number: Numerus.singularis, constructio: Constructio.inAccusativus, functio: Functio.locusQuo, tags: {'cas-prep-duplex'}, note: 'Currō verbum mōtūs est: in cum accūsātīvō dīcit quō.'),
  Syntagma(id: 'cas-prep-duplex-009', text: 'Iūlius in {vīllam} intrat', lemmaId: 'villa', casus: Casus.accusativus, number: Numerus.singularis, constructio: Constructio.inAccusativus, functio: Functio.locusQuo, tags: {'cas-prep-duplex'}, note: 'Intrō verbum mōtūs est: in vīllam accūsātīvus, quō.'),
  Syntagma(id: 'cas-prep-duplex-010', text: 'mercātor in {urbem} it', lemmaId: 'urbs', casus: Casus.accusativus, number: Numerus.singularis, constructio: Constructio.inAccusativus, functio: Functio.locusQuo, tags: {'cas-prep-duplex'}, note: 'Eō verbum mōtūs est: in urbem accūsātīvus, quō.'),
  Syntagma(id: 'cas-prep-duplex-011', text: 'Mēdus in {Italiam} venit', lemmaId: 'italia', casus: Casus.accusativus, number: Numerus.singularis, constructio: Constructio.inAccusativus, functio: Functio.locusQuo, tags: {'cas-prep-duplex'}, note: 'Veniō verbum mōtūs est: in Italiam accūsātīvus, quō.'),
  Syntagma(id: 'cas-prep-duplex-012', text: 'puer in {mare} cadit', lemmaId: 'mare', casus: Casus.accusativus, number: Numerus.singularis, constructio: Constructio.inAccusativus, functio: Functio.locusQuo, tags: {'cas-prep-duplex'}, note: 'Cadō verbum mōtūs est: in mare accūsātīvus neutrīus, quō.'),
  Syntagma(id: 'cas-prep-duplex-013', text: 'servī in {agrōs} eunt', lemmaId: 'ager', casus: Casus.accusativus, number: Numerus.pluralis, constructio: Constructio.inAccusativus, functio: Functio.locusQuo, tags: {'cas-prep-duplex'}, note: 'Eō verbum mōtūs est: in agrōs accūsātīvus plūrālis, quō.'),
  Syntagma(id: 'cas-prep-duplex-014', text: 'Mārcus in {cubiculum} intrat', lemmaId: 'cubiculum', casus: Casus.accusativus, number: Numerus.singularis, constructio: Constructio.inAccusativus, functio: Functio.locusQuo, tags: {'cas-prep-duplex'}, note: 'Intrō verbum mōtūs est: in cubiculum accūsātīvus, quō.'),
  // sub + ablative / accusative.
  Syntagma(id: 'cas-prep-duplex-015', text: 'canis sub {arbore} dormit', lemmaId: 'arbor', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.subAblativus, functio: Functio.locusUbi, tags: {'cas-prep-duplex'}, note: 'Dormiō verbum statūs est: sub arbore ablātīvus, ubi.'),
  Syntagma(id: 'cas-prep-duplex-016', text: 'puerī sub {arboribus} sedent', lemmaId: 'arbor', casus: Casus.ablativus, number: Numerus.pluralis, constructio: Constructio.subAblativus, functio: Functio.locusUbi, tags: {'cas-prep-duplex'}, note: 'Sedeō verbum statūs est: sub arboribus ablātīvus plūrālis, ubi.'),
  Syntagma(id: 'cas-prep-duplex-017', text: 'servus sub {lectō} iacet', lemmaId: 'lectus', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.subAblativus, functio: Functio.locusUbi, tags: {'cas-prep-duplex'}, note: 'Iaceō verbum statūs est: sub lectō ablātīvus, ubi.'),
  Syntagma(id: 'cas-prep-duplex-018', text: 'canis sub {arborem} currit', lemmaId: 'arbor', casus: Casus.accusativus, number: Numerus.singularis, constructio: Constructio.subAccusativus, functio: Functio.locusQuo, tags: {'cas-prep-duplex'}, note: 'Currō verbum mōtūs est: sub arborem accūsātīvus, quō.'),
  Syntagma(id: 'cas-prep-duplex-019', text: 'puer sub {lectum} sē abdit', lemmaId: 'lectus', casus: Casus.accusativus, number: Numerus.singularis, constructio: Constructio.subAccusativus, functio: Functio.locusQuo, tags: {'cas-prep-duplex'}, note: 'Sē abdere verbum mōtūs est: sub lectum accūsātīvus, quō.'),
  Syntagma(id: 'cas-prep-duplex-020', text: 'pāstor ovēs sub {arborēs} agit', lemmaId: 'arbor', casus: Casus.accusativus, number: Numerus.pluralis, constructio: Constructio.subAccusativus, functio: Functio.locusQuo, tags: {'cas-prep-duplex'}, note: 'Agō verbum mōtūs est: sub arborēs accūsātīvus plūrālis, quō.'),

  // ------------------------------------------------------------- cas-prep-abl
  Syntagma(id: 'cas-prep-abl-001', text: 'puer ā {magistrō} laudātur', lemmaId: 'magister', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'cas-prep-abl'}, note: 'Ā/ab ablātīvum semper regit: ā magistrō.'),
  Syntagma(id: 'cas-prep-abl-002', text: 'Mēdus ab {urbe} discēdit', lemmaId: 'urbs', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'cas-prep-abl'}, note: 'Ā/ab ablātīvum semper regit: ab urbe.'),
  Syntagma(id: 'cas-prep-abl-003', text: 'Iūlius cum {amīcīs} ambulat', lemmaId: 'amicus', casus: Casus.ablativus, number: Numerus.pluralis, functio: Functio.praepositio, tags: {'cas-prep-abl'}, note: 'Cum ablātīvum semper regit: cum amīcīs.'),
  Syntagma(id: 'cas-prep-abl-004', text: 'pāstor dē {monte} dēscendit', lemmaId: 'mons', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'cas-prep-abl'}, note: 'Dē ablātīvum semper regit: dē monte.'),
  Syntagma(id: 'cas-prep-abl-005', text: 'mīlitēs ex {castrīs} exeunt', lemmaId: 'castra', casus: Casus.ablativus, number: Numerus.pluralis, functio: Functio.praepositio, tags: {'cas-prep-abl'}, note: 'Ē/ex ablātīvum semper regit: ex castrīs.'),
  Syntagma(id: 'cas-prep-abl-006', text: 'nauta ē {nāve} exit', lemmaId: 'navis', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'cas-prep-abl'}, note: 'Ē/ex ablātīvum semper regit: ē nāve.'),
  Syntagma(id: 'cas-prep-abl-007', text: 'mīles prō {patriā} pugnat', lemmaId: 'patria', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'cas-prep-abl'}, note: 'Prō ablātīvum semper regit: prō patriā.'),
  Syntagma(id: 'cas-prep-abl-008', text: 'servus sine {pecūniā} venit', lemmaId: 'pecunia', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'cas-prep-abl'}, note: 'Sine ablātīvum semper regit: sine pecūniā.'),
  Syntagma(id: 'cas-prep-abl-009', text: 'cōnsul cōram {populō} loquitur', lemmaId: 'populus', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'cas-prep-abl'}, note: 'Cōram ablātīvum semper regit: cōram populō.'),
  Syntagma(id: 'cas-prep-abl-010', text: 'Mēdus prae {metū} tacet', lemmaId: 'metus', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'cas-prep-abl'}, note: 'Prae ablātīvum semper regit: prae metū (quārtae dēclīnātiōnis).'),
  Syntagma(id: 'cas-prep-abl-011', text: 'māter cum {fīliā} sedet', lemmaId: 'filia', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'cas-prep-abl'}, note: 'Cum ablātīvum semper regit: cum fīliā.'),
  // Contrast: direct objects without preposition.
  Syntagma(id: 'cas-prep-abl-012', text: 'puer {magistrum} salūtat', lemmaId: 'magister', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'cas-prep-abl'}, note: 'Sine praepositiōne: magistrum accūsātīvus obiectum verbī salūtō.'),
  Syntagma(id: 'cas-prep-abl-013', text: 'Mēdus {urbem} relinquit', lemmaId: 'urbs', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'cas-prep-abl'}, note: 'Sine praepositiōne: urbem accūsātīvus obiectum verbī relinquō.'),
  Syntagma(id: 'cas-prep-abl-014', text: 'Iūlius {amīcōs} vocat', lemmaId: 'amicus', casus: Casus.accusativus, number: Numerus.pluralis, functio: Functio.obiectum, tags: {'cas-prep-abl'}, note: 'Sine praepositiōne: amīcōs accūsātīvus plūrālis obiectum.'),
  Syntagma(id: 'cas-prep-abl-015', text: 'mīles {patriam} dēfendit', lemmaId: 'patria', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'cas-prep-abl'}, note: 'Sine praepositiōne: patriam accūsātīvus obiectum verbī dēfendō.'),
  // Contrast: instrument without preposition.
  Syntagma(id: 'cas-prep-abl-016', text: 'pāstor {baculō} lupum pellit', lemmaId: 'baculum', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.instrumentum, tags: {'cas-prep-abl'}, note: 'Ablātīvus īnstrūmentī sine praepositiōne: baculō, quō īnstrūmentō.'),
  Syntagma(id: 'cas-prep-abl-017', text: 'mīles {hastā} pugnat', lemmaId: 'hasta', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.instrumentum, tags: {'cas-prep-abl'}, note: 'Ablātīvus īnstrūmentī sine praepositiōne: hastā pugnat.'),
  Syntagma(id: 'cas-prep-abl-018', text: 'puer {digitō} litterās scrībit', lemmaId: 'digitus', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.instrumentum, tags: {'cas-prep-abl'}, note: 'Ablātīvus īnstrūmentī sine praepositiōne: digitō scrībit.'),

  // ------------------------------------------------------------- cas-prep-acc
  Syntagma(id: 'cas-prep-acc-001', text: 'Mārcus ad {urbem} it', lemmaId: 'urbs', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'cas-prep-acc'}, note: 'Ad accūsātīvum semper regit: ad urbem.'),
  Syntagma(id: 'cas-prep-acc-002', text: 'servus ante {iānuam} stat', lemmaId: 'ianua', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'cas-prep-acc'}, note: 'Ante accūsātīvum semper regit: ante iānuam.'),
  Syntagma(id: 'cas-prep-acc-003', text: 'Iūlius apud {amīcum} cēnat', lemmaId: 'amicus', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'cas-prep-acc'}, note: 'Apud accūsātīvum semper regit: apud amīcum.'),
  Syntagma(id: 'cas-prep-acc-004', text: 'puerī circum {mēnsam} sedent', lemmaId: 'mensa', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'cas-prep-acc'}, note: 'Circum accūsātīvum semper regit: circum mēnsam.'),
  Syntagma(id: 'cas-prep-acc-005', text: 'mīlitēs contrā {hostēs} pugnant', lemmaId: 'hostis', casus: Casus.accusativus, number: Numerus.pluralis, functio: Functio.praepositio, tags: {'cas-prep-acc'}, note: 'Contrā accūsātīvum semper regit: contrā hostēs.'),
  Syntagma(id: 'cas-prep-acc-006', text: 'via inter {montēs} dūcit', lemmaId: 'mons', casus: Casus.accusativus, number: Numerus.pluralis, functio: Functio.praepositio, tags: {'cas-prep-acc'}, note: 'Inter accūsātīvum semper regit: inter montēs.'),
  Syntagma(id: 'cas-prep-acc-007', text: 'Mēdus intrā {mūrōs} manet', lemmaId: 'murus', casus: Casus.accusativus, number: Numerus.pluralis, functio: Functio.praepositio, tags: {'cas-prep-acc'}, note: 'Intrā accūsātīvum semper regit: intrā mūrōs.'),
  Syntagma(id: 'cas-prep-acc-008', text: 'puer ob {morbum} domī manet', lemmaId: 'morbus', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'cas-prep-acc'}, note: 'Ob accūsātīvum semper regit: ob morbum, id est propter morbum.'),
  Syntagma(id: 'cas-prep-acc-009', text: 'mīlitēs per {silvam} eunt', lemmaId: 'silva', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'cas-prep-acc'}, note: 'Per accūsātīvum semper regit: per silvam.'),
  Syntagma(id: 'cas-prep-acc-010', text: 'servus post {tergum} manūs tenet', lemmaId: 'tergum', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'cas-prep-acc'}, note: 'Post accūsātīvum semper regit: post tergum.'),
  Syntagma(id: 'cas-prep-acc-011', text: 'vīlla prope {mare} est', lemmaId: 'mare', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'cas-prep-acc'}, note: 'Prope accūsātīvum semper regit: prope mare.'),
  Syntagma(id: 'cas-prep-acc-012', text: 'propter {tempestātem} nāvis manet', lemmaId: 'tempestas', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'cas-prep-acc'}, note: 'Propter accūsātīvum semper regit: propter tempestātem.'),
  Syntagma(id: 'cas-prep-acc-013', text: 'Mēdus trāns {flūmen} nat', lemmaId: 'flumen', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'cas-prep-acc'}, note: 'Trāns accūsātīvum semper regit: trāns flūmen.'),
  // Contrast: preposition with ablative.
  Syntagma(id: 'cas-prep-acc-014', text: 'Iūlius cum {amīcō} cēnat', lemmaId: 'amicus', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'cas-prep-acc'}, note: 'Cum ablātīvum regit, nōn accūsātīvum: cum amīcō.'),
  Syntagma(id: 'cas-prep-acc-015', text: 'Mēdus ex {urbe} fugit', lemmaId: 'urbs', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'cas-prep-acc'}, note: 'Ex ablātīvum regit, nōn accūsātīvum: ex urbe.'),
  Syntagma(id: 'cas-prep-acc-016', text: 'mīlitēs ā {hostibus} fugiunt', lemmaId: 'hostis', casus: Casus.ablativus, number: Numerus.pluralis, functio: Functio.praepositio, tags: {'cas-prep-acc'}, note: 'Ā/ab ablātīvum regit, nōn accūsātīvum: ā hostibus.'),
  // Contrast: instrument and direct object.
  Syntagma(id: 'cas-prep-acc-017', text: 'mīles {pīlō} pugnat', lemmaId: 'pilum', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.instrumentum, tags: {'cas-prep-acc'}, note: 'Ablātīvus īnstrūmentī sine praepositiōne: pīlō pugnat.'),
  Syntagma(id: 'cas-prep-acc-018', text: 'Mārcus {urbem} videt', lemmaId: 'urbs', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'cas-prep-acc'}, note: 'Sine praepositiōne: urbem accūsātīvus obiectum verbī videō.'),
  Syntagma(id: 'cas-prep-acc-019', text: 'puerī {mēnsam} portant', lemmaId: 'mensa', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'cas-prep-acc'}, note: 'Sine praepositiōne: mēnsam accūsātīvus obiectum verbī portō.'),
  Syntagma(id: 'cas-prep-acc-020', text: 'nauta {flūmen} spectat', lemmaId: 'flumen', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'cas-prep-acc'}, note: 'Sine praepositiōne: flūmen accūsātīvus obiectum verbī spectō.'),

  // ----------------------------------------------------------------- cas-loci
  Syntagma(id: 'cas-loci-001', text: 'Iūlius {Rōmam} it', lemmaId: 'roma', casus: Casus.accusativus, number: Numerus.singularis, constructio: Constructio.accusativusMotus, functio: Functio.locusQuo, tags: {'cas-loci'}, note: 'Nōmen urbis sine praepositiōne: accūsātīvus quō (Rōmam it).'),
  Syntagma(id: 'cas-loci-002', text: 'Mēdus {Rōmā} venit', lemmaId: 'roma', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.ablativusSeparationis, functio: Functio.locusUnde, tags: {'cas-loci'}, note: 'Nōmen urbis sine praepositiōne: ablātīvus unde (Rōmā venit).'),
  Syntagma(id: 'cas-loci-003', text: 'Cornēlius {Rōmae} habitat', lemmaId: 'roma', casus: Casus.locativus, number: Numerus.singularis, constructio: Constructio.locativus, functio: Functio.locusUbi, tags: {'cas-loci'}, note: 'Nōmen urbis prīmae dēclīnātiōnis: locātīvus -ae dīcit ubi (Rōmae habitat).'),
  Syntagma(id: 'cas-loci-004', text: 'Iūlius {Tūsculum} it', lemmaId: 'tusculum', casus: Casus.accusativus, number: Numerus.singularis, constructio: Constructio.accusativusMotus, functio: Functio.locusQuo, tags: {'cas-loci'}, note: 'Nōmen oppidī sine praepositiōne: accūsātīvus quō (Tūsculum it).'),
  Syntagma(id: 'cas-loci-005', text: 'servus {Tūsculō} venit', lemmaId: 'tusculum', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.ablativusSeparationis, functio: Functio.locusUnde, tags: {'cas-loci'}, note: 'Nōmen oppidī sine praepositiōne: ablātīvus unde (Tūsculō venit).'),
  Syntagma(id: 'cas-loci-006', text: 'Aemilia {Tūsculī} habitat', lemmaId: 'tusculum', casus: Casus.locativus, number: Numerus.singularis, constructio: Constructio.locativus, functio: Functio.locusUbi, tags: {'cas-loci'}, note: 'Nōmen oppidī secundae dēclīnātiōnis: locātīvus -ī dīcit ubi (Tūsculī habitat).'),
  Syntagma(id: 'cas-loci-007', text: 'nāvis {Brundisium} nāvigat', lemmaId: 'brundisium', casus: Casus.accusativus, number: Numerus.singularis, constructio: Constructio.accusativusMotus, functio: Functio.locusQuo, tags: {'cas-loci'}, note: 'Nōmen oppidī sine praepositiōne: accūsātīvus quō (Brundisium nāvigat).'),
  Syntagma(id: 'cas-loci-008', text: 'mercātor {Brundisiō} venit', lemmaId: 'brundisium', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.ablativusSeparationis, functio: Functio.locusUnde, tags: {'cas-loci'}, note: 'Nōmen oppidī sine praepositiōne: ablātīvus unde (Brundisiō venit).'),
  Syntagma(id: 'cas-loci-009', text: 'nautae {Ōstiam} eunt', lemmaId: 'ostia', casus: Casus.accusativus, number: Numerus.singularis, constructio: Constructio.accusativusMotus, functio: Functio.locusQuo, tags: {'cas-loci'}, note: 'Nōmen oppidī sine praepositiōne: accūsātīvus quō (Ōstiam eunt).'),
  Syntagma(id: 'cas-loci-010', text: 'nauta {Ōstiae} manet', lemmaId: 'ostia', casus: Casus.locativus, number: Numerus.singularis, constructio: Constructio.locativus, functio: Functio.locusUbi, tags: {'cas-loci'}, note: 'Nōmen oppidī prīmae dēclīnātiōnis: locātīvus -ae dīcit ubi (Ōstiae manet).'),
  Syntagma(id: 'cas-loci-011', text: 'Mēdus {Capuā} venit', lemmaId: 'capua', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.ablativusSeparationis, functio: Functio.locusUnde, tags: {'cas-loci'}, note: 'Nōmen oppidī sine praepositiōne: ablātīvus unde (Capuā venit).'),
  Syntagma(id: 'cas-loci-012', text: 'mercātor {Capuae} habitat', lemmaId: 'capua', casus: Casus.locativus, number: Numerus.singularis, constructio: Constructio.locativus, functio: Functio.locusUbi, tags: {'cas-loci'}, note: 'Nōmen oppidī prīmae dēclīnātiōnis: locātīvus -ae dīcit ubi (Capuae habitat).'),
  Syntagma(id: 'cas-loci-013', text: 'Mēdus {Athēnās} nāvigat', lemmaId: 'athenae', casus: Casus.accusativus, number: Numerus.pluralis, constructio: Constructio.accusativusMotus, functio: Functio.locusQuo, tags: {'cas-loci'}, note: 'Nōmen urbis plūrāle sine praepositiōne: accūsātīvus quō (Athēnās nāvigat).'),
  Syntagma(id: 'cas-loci-014', text: 'Diodōrus {Athēnīs} venit', lemmaId: 'athenae', casus: Casus.ablativus, number: Numerus.pluralis, constructio: Constructio.ablativusSeparationis, functio: Functio.locusUnde, tags: {'cas-loci'}, note: 'Nōmen urbis plūrāle: venit dīcit unde, ergō Athēnīs ablātīvus.'),
  Syntagma(id: 'cas-loci-015', text: 'Diodōrus {Athēnīs} habitat', lemmaId: 'athenae', casus: Casus.locativus, number: Numerus.pluralis, constructio: Constructio.locativus, functio: Functio.locusUbi, tags: {'cas-loci'}, note: 'Nōmen urbis plūrāle: locātīvus fōrmā ablātīvō pār est, habitat dīcit ubi (Athēnīs).'),
  Syntagma(id: 'cas-loci-016', text: 'mercātor {Corinthum} nāvigat', lemmaId: 'corinthus', casus: Casus.accusativus, number: Numerus.singularis, constructio: Constructio.accusativusMotus, functio: Functio.locusQuo, tags: {'cas-loci'}, note: 'Nōmen urbis sine praepositiōne: accūsātīvus quō (Corinthum nāvigat).'),
  Syntagma(id: 'cas-loci-017', text: 'Lȳdia {Corinthī} habitat', lemmaId: 'corinthus', casus: Casus.locativus, number: Numerus.singularis, constructio: Constructio.locativus, functio: Functio.locusUbi, tags: {'cas-loci'}, note: 'Nōmen urbis secundae dēclīnātiōnis: locātīvus -ī dīcit ubi (Corinthī habitat).'),
  Syntagma(id: 'cas-loci-018', text: 'nāvis {Carthāginem} nāvigat', lemmaId: 'carthago', casus: Casus.accusativus, number: Numerus.singularis, constructio: Constructio.accusativusMotus, functio: Functio.locusQuo, tags: {'cas-loci'}, note: 'Nōmen urbis sine praepositiōne: accūsātīvus quō (Carthāginem nāvigat).'),
  Syntagma(id: 'cas-loci-019', text: 'mercātor {Carthāgine} venit', lemmaId: 'carthago', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.ablativusSeparationis, functio: Functio.locusUnde, tags: {'cas-loci'}, note: 'Nōmen urbis tertiae dēclīnātiōnis: venit dīcit unde, ergō Carthāgine ablātīvus.'),
  Syntagma(id: 'cas-loci-020', text: 'mercātor {Carthāginī} habitat', lemmaId: 'carthago', casus: Casus.locativus, number: Numerus.singularis, constructio: Constructio.locativus, functio: Functio.locusUbi, tags: {'cas-loci'}, note: 'Nōmen urbis tertiae dēclīnātiōnis: locātīvus -ī dīcit ubi (Carthāginī habitat).'),
  Syntagma(id: 'cas-loci-021', text: 'Iūlius {domum} redit', lemmaId: 'domus', casus: Casus.accusativus, number: Numerus.singularis, constructio: Constructio.accusativusMotus, functio: Functio.locusQuo, tags: {'cas-loci'}, note: 'Domus ut nōmen urbis: accūsātīvus sine praepositiōne dīcit quō (domum redit).'),
  Syntagma(id: 'cas-loci-022', text: 'servus {domō} exit', lemmaId: 'domus', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.ablativusSeparationis, functio: Functio.locusUnde, tags: {'cas-loci'}, note: 'Domus ut nōmen urbis: ablātīvus sine praepositiōne dīcit unde (domō exit).'),
  Syntagma(id: 'cas-loci-023', text: 'Aemilia {domī} manet', lemmaId: 'domus', casus: Casus.locativus, number: Numerus.singularis, constructio: Constructio.locativus, functio: Functio.locusUbi, tags: {'cas-loci'}, note: 'Domus locātīvum habet: domī dīcit ubi (domī manet).'),
  Syntagma(id: 'cas-loci-024', text: 'Iūlius {rūs} it', lemmaId: 'rus', casus: Casus.accusativus, number: Numerus.singularis, constructio: Constructio.accusativusMotus, functio: Functio.locusQuo, tags: {'cas-loci'}, note: 'Rūs ut nōmen urbis: accūsātīvus sine praepositiōne dīcit quō (rūs it).'),
  Syntagma(id: 'cas-loci-025', text: 'agricola {rūre} redit', lemmaId: 'rus', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.ablativusSeparationis, functio: Functio.locusUnde, tags: {'cas-loci'}, note: 'Rūs ut nōmen urbis: redit dīcit unde, ergō rūre ablātīvus.'),
  Syntagma(id: 'cas-loci-026', text: 'agricola {rūrī} vīvit', lemmaId: 'rus', casus: Casus.locativus, number: Numerus.singularis, constructio: Constructio.locativus, functio: Functio.locusUbi, tags: {'cas-loci'}, note: 'Rūs locātīvum habet: rūrī dīcit ubi (rūrī vīvit).'),

  // ------------------------------------------------------------- cas-temporis
  // Ablative of time when.
  Syntagma(id: 'cas-temporis-001', text: 'Iūlius {hōrā} sextā venit', lemmaId: 'hora', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.ablativusTemporis, functio: Functio.tempus, tags: {'cas-temporis'}, note: 'Tempus quandō ablātīvō sine praepositiōne: hōrā sextā, pūnctum temporis.'),
  Syntagma(id: 'cas-temporis-002', text: 'puer {nocte} dormit', lemmaId: 'nox', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.ablativusTemporis, functio: Functio.tempus, tags: {'cas-temporis'}, note: 'Tempus quandō ablātīvō: nocte dormit.'),
  Syntagma(id: 'cas-temporis-003', text: '{hieme} nāvigāre difficile est', lemmaId: 'hiems', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.ablativusTemporis, functio: Functio.tempus, tags: {'cas-temporis'}, note: 'Tempus quandō ablātīvō: hieme, quō tempore annī.'),
  Syntagma(id: 'cas-temporis-004', text: 'eō {diē} Mārcus Rōmam it', lemmaId: 'dies', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.ablativusTemporis, functio: Functio.tempus, tags: {'cas-temporis'}, note: 'Tempus quandō ablātīvō: eō diē, pūnctum temporis.'),
  Syntagma(id: 'cas-temporis-005', text: '{aestāte} agricolae labōrant', lemmaId: 'aestas', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.ablativusTemporis, functio: Functio.tempus, tags: {'cas-temporis'}, note: 'Tempus quandō ablātīvō: aestāte, quō tempore annī.'),
  Syntagma(id: 'cas-temporis-006', text: '{mēnse} Mārtiō bellum incipit', lemmaId: 'mensis', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.ablativusTemporis, functio: Functio.tempus, tags: {'cas-temporis'}, note: 'Tempus quandō ablātīvō: mēnse Mārtiō, ablātīvus nōminis mēnsis.'),
  Syntagma(id: 'cas-temporis-007', text: '{vēre} flōrēs in hortō sunt', lemmaId: 'ver', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.ablativusTemporis, functio: Functio.tempus, tags: {'cas-temporis'}, note: 'Tempus quandō ablātīvō: vēre, quō tempore annī.'),
  Syntagma(id: 'cas-temporis-008', text: '{autumnō} ūvae mātūrae sunt', lemmaId: 'autumnus', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.ablativusTemporis, functio: Functio.tempus, tags: {'cas-temporis'}, note: 'Tempus quandō ablātīvō: autumnō, quō tempore annī.'),
  Syntagma(id: 'cas-temporis-009', text: '{merīdiē} servī quiēscunt', lemmaId: 'meridies', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.ablativusTemporis, functio: Functio.tempus, tags: {'cas-temporis'}, note: 'Tempus quandō ablātīvō: merīdiē, pūnctum diēī.'),
  Syntagma(id: 'cas-temporis-010', text: 'puer {annō} septimō in lūdum it', lemmaId: 'annus', casus: Casus.ablativus, number: Numerus.singularis, constructio: Constructio.ablativusTemporis, functio: Functio.tempus, tags: {'cas-temporis'}, note: 'Tempus quandō ablātīvō: annō septimō, pūnctum temporis.'),
  // Accusative of duration.
  Syntagma(id: 'cas-temporis-011', text: 'puer trēs {hōrās} dormit', lemmaId: 'hora', casus: Casus.accusativus, number: Numerus.pluralis, constructio: Constructio.accusativusDurationis, functio: Functio.tempus, tags: {'cas-temporis'}, note: 'Tempus quam diū accūsātīvō: trēs hōrās, spatium temporis.'),
  Syntagma(id: 'cas-temporis-012', text: 'senex multōs {annōs} vīvit', lemmaId: 'annus', casus: Casus.accusativus, number: Numerus.pluralis, constructio: Constructio.accusativusDurationis, functio: Functio.tempus, tags: {'cas-temporis'}, note: 'Tempus quam diū accūsātīvō: multōs annōs, spatium temporis.'),
  Syntagma(id: 'cas-temporis-013', text: 'servus tōtam {noctem} vigilat', lemmaId: 'nox', casus: Casus.accusativus, number: Numerus.singularis, constructio: Constructio.accusativusDurationis, functio: Functio.tempus, tags: {'cas-temporis'}, note: 'Tempus quam diū accūsātīvō: tōtam noctem, spatium temporis.'),
  Syntagma(id: 'cas-temporis-014', text: 'nautae {diēs} multōs nāvigant', lemmaId: 'dies', casus: Casus.accusativus, number: Numerus.pluralis, constructio: Constructio.accusativusDurationis, functio: Functio.tempus, tags: {'cas-temporis'}, note: 'Tempus quam diū accūsātīvō: diēs multōs, accūsātīvus plūrālis.'),
  Syntagma(id: 'cas-temporis-015', text: 'agricola tōtum {diem} labōrat', lemmaId: 'dies', casus: Casus.accusativus, number: Numerus.singularis, constructio: Constructio.accusativusDurationis, functio: Functio.tempus, tags: {'cas-temporis'}, note: 'Tempus quam diū accūsātīvō: tōtum diem, spatium temporis.'),
  Syntagma(id: 'cas-temporis-016', text: 'Mēdus duōs {mēnsēs} Rōmae manet', lemmaId: 'mensis', casus: Casus.accusativus, number: Numerus.pluralis, constructio: Constructio.accusativusDurationis, functio: Functio.tempus, tags: {'cas-temporis'}, note: 'Tempus quam diū accūsātīvō: duōs mēnsēs, spatium temporis.'),
  Syntagma(id: 'cas-temporis-017', text: 'Iūlius tōtam {hiemem} in vīllā manet', lemmaId: 'hiems', casus: Casus.accusativus, number: Numerus.singularis, constructio: Constructio.accusativusDurationis, functio: Functio.tempus, tags: {'cas-temporis'}, note: 'Tempus quam diū accūsātīvō: tōtam hiemem, spatium temporis.'),
  Syntagma(id: 'cas-temporis-018', text: 'mīles tōtum {annum} in castrīs est', lemmaId: 'annus', casus: Casus.accusativus, number: Numerus.singularis, constructio: Constructio.accusativusDurationis, functio: Functio.tempus, tags: {'cas-temporis'}, note: 'Tempus quam diū accūsātīvō: tōtum annum, spatium temporis.'),
];
