/// Contextual items — section "comparatio". Authored by hand; see syntagma.dart for
/// the markers (`{target}`, `[head]`, `<candidate>`).
library;

import '../../../linguistics/model/grammar.dart';
import '../../../linguistics/model/nominal.dart';
import '../syntagma.dart';

// ignore_for_file: unused_import

const List<Syntagma> kComparatioSyntagmata = [
  // ---------------------------------------------------------------- comp-abl
  // Ablative of comparison.
  Syntagma(id: 'comp-abl-001', text: 'Quīntus {Mārcō} altior est', lemmaId: 'marcus', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.comparatio, constructio: Constructio.ablativusComparationis, tags: {'comp-abl'}, note: 'Post comparātīvum altior sine quam: Mārcō ablātīvus comparātiōnis.'),
  Syntagma(id: 'comp-abl-002', text: 'nihil est melius {sapientiā}', lemmaId: 'sapientia', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.comparatio, constructio: Constructio.ablativusComparationis, tags: {'comp-abl'}, note: 'Melius comparātīvum sine quam: sapientiā ablātīvus comparātiōnis.'),
  Syntagma(id: 'comp-abl-003', text: 'lūx {umbrā} clārior est', lemmaId: 'umbra', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.comparatio, constructio: Constructio.ablativusComparationis, tags: {'comp-abl'}, note: 'Clārior sine quam: umbrā ablātīvus comparātiōnis, quamquam ante comparātīvum stat.'),
  Syntagma(id: 'comp-abl-004', text: 'Iūlia {sorōre} minor est', lemmaId: 'soror', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.comparatio, constructio: Constructio.ablativusComparationis, tags: {'comp-abl'}, note: 'Minor comparātīvum sine quam: sorōre ablātīvus comparātiōnis tertiae dēclīnātiōnis.'),
  Syntagma(id: 'comp-abl-005', text: 'equus {asinō} vēlōcior est', lemmaId: 'asinus', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.comparatio, constructio: Constructio.ablativusComparationis, tags: {'comp-abl'}, note: 'Vēlōcior sine quam: asinō ablātīvus comparātiōnis.'),
  Syntagma(id: 'comp-abl-006', text: 'mel {vīnō} dulcius est', lemmaId: 'vinum', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.comparatio, constructio: Constructio.ablativusComparationis, tags: {'comp-abl'}, note: 'Dulcius comparātīvum neutrum sine quam: vīnō ablātīvus comparātiōnis.'),
  Syntagma(id: 'comp-abl-007', text: 'nāvis {currū} celerior est', lemmaId: 'currus', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.comparatio, constructio: Constructio.ablativusComparationis, tags: {'comp-abl'}, note: 'Celerior sine quam: currū ablātīvus comparātiōnis quārtae dēclīnātiōnis.'),
  Syntagma(id: 'comp-abl-008', text: 'nūlla rēs {fidē} cārior est', lemmaId: 'fides', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.comparatio, constructio: Constructio.ablativusComparationis, tags: {'comp-abl'}, note: 'Cārior sine quam: fidē ablātīvus comparātiōnis quīntae dēclīnātiōnis.'),
  Syntagma(id: 'comp-abl-009', text: 'mīlitēs {servīs} fortiōrēs sunt', lemmaId: 'servus', casus: Casus.ablativus, number: Numerus.pluralis, functio: Functio.comparatio, constructio: Constructio.ablativusComparationis, tags: {'comp-abl'}, note: 'Fortiōrēs sine quam: servīs ablātīvus comparātiōnis plūrālis.'),
  Syntagma(id: 'comp-abl-010', text: 'fēminae {virīs} pulchriōrēs sunt', lemmaId: 'vir', casus: Casus.ablativus, number: Numerus.pluralis, functio: Functio.comparatio, constructio: Constructio.ablativusComparationis, tags: {'comp-abl'}, note: 'Pulchriōrēs sine quam: virīs ablātīvus comparātiōnis plūrālis.'),
  Syntagma(id: 'comp-abl-011', text: 'Rōma {Athēnīs} maior est', lemmaId: 'athenae', casus: Casus.ablativus, number: Numerus.pluralis, functio: Functio.comparatio, constructio: Constructio.ablativusComparationis, tags: {'comp-abl'}, note: 'Maior sine quam: Athēnīs ablātīvus comparātiōnis (nōmen plūrāle tantum).'),
  Syntagma(id: 'comp-abl-012', text: 'leō {cane} ferōcior est', lemmaId: 'canis', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.comparatio, constructio: Constructio.ablativusComparationis, tags: {'comp-abl'}, note: 'Ferōcior sine quam: cane ablātīvus comparātiōnis.'),
  Syntagma(id: 'comp-abl-013', text: 'Mārcus {frātre} stultior est', lemmaId: 'frater', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.comparatio, constructio: Constructio.ablativusComparationis, tags: {'comp-abl'}, note: 'Stultior sine quam: frātre ablātīvus comparātiōnis.'),
  // Quam + the case of the compared word.
  Syntagma(id: 'comp-abl-014', text: 'Quīntus altior est quam {Mārcus}', lemmaId: 'marcus', casus: Casus.nominativus, number: Numerus.singularis, functio: Functio.comparatio, constructio: Constructio.quamCasus, tags: {'comp-abl'}, note: 'Post quam Mārcus eundem cāsum habet quem Quīntus subiectum: nōminātīvus.'),
  Syntagma(id: 'comp-abl-015', text: 'Iūlia Mārcum magis amat quam {Quīntum}', lemmaId: 'quintus_n', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.comparatio, constructio: Constructio.quamCasus, tags: {'comp-abl'}, note: 'Post quam Quīntum eundem cāsum habet quem Mārcum obiectum: accūsātīvus.'),
  Syntagma(id: 'comp-abl-016', text: 'Iūlius Mārcō plūs dat quam {Quīntō}', lemmaId: 'quintus_n', casus: Casus.dativus, number: Numerus.singularis, functio: Functio.comparatio, constructio: Constructio.quamCasus, tags: {'comp-abl'}, note: 'Post quam Quīntō eundem cāsum habet quem Mārcō: datīvus, nōn ablātīvus.'),
  Syntagma(id: 'comp-abl-017', text: 'nihil melius est quam {sapientia}', lemmaId: 'sapientia', casus: Casus.nominativus, number: Numerus.singularis, functio: Functio.comparatio, constructio: Constructio.quamCasus, tags: {'comp-abl'}, note: 'Cum quam sapientia cāsum subiectī nihil sūmit: nōminātīvus.'),
  Syntagma(id: 'comp-abl-018', text: 'Mārcus saepius rīdet quam {Iūlia}', lemmaId: 'iulia', casus: Casus.nominativus, number: Numerus.singularis, functio: Functio.comparatio, constructio: Constructio.quamCasus, tags: {'comp-abl'}, note: 'Post quam Iūlia eundem cāsum habet quem Mārcus subiectum: nōminātīvus.'),
  Syntagma(id: 'comp-abl-019', text: 'māter fīliam magis amat quam {fīlium}', lemmaId: 'filius', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.comparatio, constructio: Constructio.quamCasus, tags: {'comp-abl'}, note: 'Post quam fīlium eundem cāsum habet quem fīliam obiectum: accūsātīvus.'),
  Syntagma(id: 'comp-abl-020', text: 'servī plūs labōrant quam {dominī}', lemmaId: 'dominus', casus: Casus.nominativus, number: Numerus.pluralis, functio: Functio.comparatio, constructio: Constructio.quamCasus, tags: {'comp-abl'}, note: 'Post quam dominī eundem cāsum habent quem servī subiectum: nōminātīvus plūrālis.'),
  Syntagma(id: 'comp-abl-021', text: 'Iūlia rosās magis amat quam {gemmās}', lemmaId: 'gemma', casus: Casus.accusativus, number: Numerus.pluralis, functio: Functio.comparatio, constructio: Constructio.quamCasus, tags: {'comp-abl'}, note: 'Post quam gemmās eundem cāsum habet quem rosās obiectum: accūsātīvus plūrālis.'),
  Syntagma(id: 'comp-abl-022', text: 'pāstor ovēs magis cūrat quam {canem}', lemmaId: 'canis', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.comparatio, constructio: Constructio.quamCasus, tags: {'comp-abl'}, note: 'Post quam canem eundem cāsum habet quem ovēs obiectum: accūsātīvus.'),
  Syntagma(id: 'comp-abl-023', text: 'pater fīliō plūs crēdit quam {servō}', lemmaId: 'servus', casus: Casus.dativus, number: Numerus.singularis, functio: Functio.comparatio, constructio: Constructio.quamCasus, tags: {'comp-abl'}, note: 'Post quam servō eundem cāsum habet quem fīliō: datīvus, quem crēdit regit.'),
  Syntagma(id: 'comp-abl-024', text: 'saepius cum Iūliō quam cum {Mēdō} ambulat', lemmaId: 'medus', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.comparatio, constructio: Constructio.quamCasus, tags: {'comp-abl'}, note: 'Cum quam praepositiō iterātur: Mēdō ablātīvus propter cum, nōn ablātīvus comparātiōnis.'),
  Syntagma(id: 'comp-abl-025', text: 'mīlitēs fortiōrēs sunt quam {servī}', lemmaId: 'servus', casus: Casus.nominativus, number: Numerus.pluralis, functio: Functio.comparatio, constructio: Constructio.quamCasus, tags: {'comp-abl'}, note: 'Post quam servī eundem cāsum habent quem mīlitēs subiectum: nōminātīvus plūrālis.'),
  Syntagma(id: 'comp-abl-026', text: 'Rōma maior est quam {Athēnae}', lemmaId: 'athenae', casus: Casus.nominativus, number: Numerus.pluralis, functio: Functio.comparatio, constructio: Constructio.quamCasus, tags: {'comp-abl'}, note: 'Post quam Athēnae eundem cāsum habent quem Rōma subiectum: nōminātīvus.'),
];
