/// Contextual items — section "pronomina". Authored by hand; see syntagma.dart for
/// the markers (`{target}`, `[head]`, `<candidate>`).
library;

import '../../../linguistics/model/grammar.dart';
import '../../../linguistics/model/nominal.dart';
import '../syntagma.dart';

// ignore_for_file: unused_import

const List<Syntagma> kPronominaSyntagmata = [
  // ---------------------------------------------------------------- pron-me-mihi
  // Accusative objects.
  Syntagma(id: 'pron-me-mihi-001', text: 'Iūlia {mē} videt', lemmaId: 'ego', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'pron-me-mihi'}, note: 'Videt obiectum accūsātīvum habet: mē videt.'),
  Syntagma(id: 'pron-me-mihi-002', text: 'Mārcus {tē} vocat', lemmaId: 'tu', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'pron-me-mihi'}, note: 'Vocat obiectum accūsātīvum regit: quem vocat? tē.'),
  Syntagma(id: 'pron-me-mihi-003', text: 'Aemilia {nōs} exspectat', lemmaId: 'ego', casus: Casus.accusativus, number: Numerus.pluralis, functio: Functio.obiectum, tags: {'pron-me-mihi'}, note: 'Aemilia subiectum est, nōs obiectum verbī exspectat: accūsātīvus plūrālis.'),
  Syntagma(id: 'pron-me-mihi-004', text: 'Iūlius {vōs} laudat', lemmaId: 'tu', casus: Casus.accusativus, number: Numerus.pluralis, functio: Functio.obiectum, tags: {'pron-me-mihi'}, note: 'Quōs laudat Iūlius? vōs: obiectum accūsātīvum.'),
  Syntagma(id: 'pron-me-mihi-005', text: 'Quīntus {sē} in speculō videt', lemmaId: 'se', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'pron-me-mihi'}, note: 'Sē obiectum verbī videt est et ad Quīntum ipsum refertur: accūsātīvus.'),
  Syntagma(id: 'pron-me-mihi-006', text: 'servī {sē} in flūmine lavant', lemmaId: 'se', casus: Casus.accusativus, number: Numerus.pluralis, functio: Functio.obiectum, tags: {'pron-me-mihi'}, note: 'Servī sē lavant: sē obiectum accūsātīvum, plūrāle quia servī.'),
  Syntagma(id: 'pron-me-mihi-007', text: 'servus {mē} nōn audit', lemmaId: 'ego', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'pron-me-mihi'}, note: 'Audit obiectum accūsātīvum habet: mē nōn audit.'),
  Syntagma(id: 'pron-me-mihi-008', text: 'māter {tē} amat', lemmaId: 'tu', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.obiectum, tags: {'pron-me-mihi'}, note: 'Amat obiectum accūsātīvum regit: tē amat.'),
  // Ablative after a preposition.
  Syntagma(id: 'pron-me-mihi-009', text: 'Dāvus cum {mē} venit', lemmaId: 'ego', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'pron-me-mihi'}, note: 'Cum praepositiō ablātīvum regit: cum mē.'),
  Syntagma(id: 'pron-me-mihi-010', text: 'Iūlia dē {tē} loquitur', lemmaId: 'tu', casus: Casus.ablativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'pron-me-mihi'}, note: 'Dē praepositiō ablātīvum regit: dē tē loquitur.'),
  Syntagma(id: 'pron-me-mihi-011', text: 'Syra ā {nōbīs} discēdit', lemmaId: 'ego', casus: Casus.ablativus, number: Numerus.pluralis, functio: Functio.praepositio, tags: {'pron-me-mihi'}, note: 'Ā praepositiō ablātīvum regit: ā nōbīs, nōn datīvus.'),
  Syntagma(id: 'pron-me-mihi-012', text: 'Mēdus cum {vōbīs} ambulat', lemmaId: 'tu', casus: Casus.ablativus, number: Numerus.pluralis, functio: Functio.praepositio, tags: {'pron-me-mihi'}, note: 'Cum praepositiō ablātīvum regit: cum vōbīs ambulat.'),
  Syntagma(id: 'pron-me-mihi-013', text: 'Aemilia fīlium ad {sē} vocat', lemmaId: 'se', casus: Casus.accusativus, number: Numerus.singularis, functio: Functio.praepositio, tags: {'pron-me-mihi'}, note: 'Ad praepositiō accūsātīvum regit: ad sē, id est ad Aemiliam ipsam.'),
  // Dative of the recipient (giving, saying).
  Syntagma(id: 'pron-me-mihi-014', text: 'Iūlia {mihi} rosam dat', lemmaId: 'ego', casus: Casus.dativus, number: Numerus.singularis, functio: Functio.datum, tags: {'pron-me-mihi'}, note: 'Dat rem accūsātīvō, persōnam datīvō: cui dat rosam? mihi.'),
  Syntagma(id: 'pron-me-mihi-015', text: 'Mārcus {tibi} epistulam scrībit', lemmaId: 'tu', casus: Casus.dativus, number: Numerus.singularis, functio: Functio.datum, tags: {'pron-me-mihi'}, note: 'Epistulam obiectum est, tibi datīvus: cui scrībit? tibi.'),
  Syntagma(id: 'pron-me-mihi-016', text: 'magister {nōbīs} fābulam nārrat', lemmaId: 'ego', casus: Casus.dativus, number: Numerus.pluralis, functio: Functio.datum, tags: {'pron-me-mihi'}, note: 'Nārrat fābulam (accūsātīvus) nōbīs (datīvus): quibus nārrat? nōbīs.'),
  Syntagma(id: 'pron-me-mihi-017', text: 'Iūlius {vōbīs} pecūniam dat', lemmaId: 'tu', casus: Casus.dativus, number: Numerus.pluralis, functio: Functio.datum, tags: {'pron-me-mihi'}, note: 'Pecūniam obiectum est, vōbīs datīvus: quibus datur pecūnia? vōbīs.'),
  Syntagma(id: 'pron-me-mihi-018', text: 'Aemilia {mihi} respondet', lemmaId: 'ego', casus: Casus.dativus, number: Numerus.singularis, functio: Functio.datum, tags: {'pron-me-mihi'}, note: 'Respondet datīvum persōnae habet: cui respondet? mihi.'),
  Syntagma(id: 'pron-me-mihi-019', text: 'Iūlia {tibi} dōnum mittit', lemmaId: 'tu', casus: Casus.dativus, number: Numerus.singularis, functio: Functio.datum, tags: {'pron-me-mihi'}, note: 'Dōnum mittitur (accūsātīvus), tibi datīvus: cui mittit? tibi.'),
  Syntagma(id: 'pron-me-mihi-020', text: 'pater {nōbīs} librōs dat', lemmaId: 'ego', casus: Casus.dativus, number: Numerus.pluralis, functio: Functio.datum, tags: {'pron-me-mihi'}, note: 'Librōs obiectum est, nōbīs datīvus plūrālis: quibus dat? nōbīs.'),
  // Dative required by the verb.
  Syntagma(id: 'pron-me-mihi-021', text: 'hoc {mihi} placet', lemmaId: 'ego', casus: Casus.dativus, number: Numerus.singularis, functio: Functio.obiectumDativum, tags: {'pron-me-mihi'}, note: 'Placet verbum cum datīvō est: hoc mihi placet, nōn mē.'),
  Syntagma(id: 'pron-me-mihi-022', text: 'canis {tibi} pāret', lemmaId: 'tu', casus: Casus.dativus, number: Numerus.singularis, functio: Functio.obiectumDativum, tags: {'pron-me-mihi'}, note: 'Pāret datīvum regit: canis tibi pāret.'),
  Syntagma(id: 'pron-me-mihi-023', text: 'servī {nōbīs} pārent', lemmaId: 'ego', casus: Casus.dativus, number: Numerus.pluralis, functio: Functio.obiectumDativum, tags: {'pron-me-mihi'}, note: 'Pārent datīvum regit: servī nōbīs pārent, nōn nōs.'),
  Syntagma(id: 'pron-me-mihi-024', text: 'aqua frīgida {vōbīs} nocet', lemmaId: 'tu', casus: Casus.dativus, number: Numerus.pluralis, functio: Functio.obiectumDativum, tags: {'pron-me-mihi'}, note: 'Nocet datīvum regit: aqua vōbīs nocet.'),
  Syntagma(id: 'pron-me-mihi-025', text: 'Quīntus {sibi} nocet', lemmaId: 'se', casus: Casus.dativus, number: Numerus.singularis, functio: Functio.obiectumDativum, tags: {'pron-me-mihi'}, note: 'Nocet datīvum regit; sibi ad Quīntum ipsum refertur.'),
  Syntagma(id: 'pron-me-mihi-026', text: 'puerī improbī {sibi} nocent', lemmaId: 'se', casus: Casus.dativus, number: Numerus.pluralis, functio: Functio.obiectumDativum, tags: {'pron-me-mihi'}, note: 'Nocent datīvum regit; sibi plūrāle ad puerōs ipsōs refertur.'),
  // Nominative subjects.
  Syntagma(id: 'pron-me-mihi-027', text: '{nōs} in hortō ambulāmus', lemmaId: 'ego', casus: Casus.nominativus, number: Numerus.pluralis, functio: Functio.subiectum, tags: {'pron-me-mihi'}, note: 'Ambulāmus prīma persōna plūrālis est: nōs subiectum nōminātīvum.'),
  Syntagma(id: 'pron-me-mihi-028', text: '{vōs} Rōmam ītis', lemmaId: 'tu', casus: Casus.nominativus, number: Numerus.pluralis, functio: Functio.subiectum, tags: {'pron-me-mihi'}, note: 'Ītis secunda persōna plūrālis est: vōs subiectum, Rōmam accūsātīvus locī.'),
  Syntagma(id: 'pron-me-mihi-029', text: '{nōs} magistrō pārēmus', lemmaId: 'ego', casus: Casus.nominativus, number: Numerus.pluralis, functio: Functio.subiectum, tags: {'pron-me-mihi'}, note: 'Pārēmus verbum prīmae persōnae plūrālis est: nōs subiectum est, magistrō datīvus.'),
  Syntagma(id: 'pron-me-mihi-030', text: '{vōs} bene cantātis', lemmaId: 'tu', casus: Casus.nominativus, number: Numerus.pluralis, functio: Functio.subiectum, tags: {'pron-me-mihi'}, note: 'Cantātis secunda persōna plūrālis est: vōs subiectum nōminātīvum.'),

  // ---------------------------------------------------------------- pron-suus-eius
  Syntagma(id: 'pron-suus-eius-001', text: 'Iūlius fīlium {suum} vocat', lemmaId: 'suus', casus: Casus.accusativus, number: Numerus.singularis, gender: Gender.masculinum, relatio: Relatio.subiectum, tags: {'pron-suus-eius'}, note: 'Suum ad subiectum Iūlium refertur: fīlium ipsīus Iūliī.'),
  Syntagma(id: 'pron-suus-eius-002', text: 'Iūlius fīlium {eius} vocat', lemmaId: 'is', casus: Casus.genetivus, number: Numerus.singularis, gender: Gender.masculinum, relatio: Relatio.alius, tags: {'pron-suus-eius'}, note: 'Eius ad alium refertur, nōn ad Iūlium: fīlium alterīus virī vocat.'),
  Syntagma(id: 'pron-suus-eius-003', text: 'Aemilia {sē} in speculō videt', lemmaId: 'se', casus: Casus.accusativus, number: Numerus.singularis, relatio: Relatio.subiectum, tags: {'pron-suus-eius'}, note: 'Sē reflexīvum ad subiectum Aemiliam refertur: Aemilia ipsam sē videt.'),
  Syntagma(id: 'pron-suus-eius-004', text: 'Aemilia {eam} in hortō videt', lemmaId: 'is', casus: Casus.accusativus, number: Numerus.singularis, gender: Gender.femininum, relatio: Relatio.alius, tags: {'pron-suus-eius'}, note: 'Eam ad aliam fēminam refertur, nōn ad Aemiliam ipsam.'),
  Syntagma(id: 'pron-suus-eius-005', text: 'puerī librōs {suōs} legunt', lemmaId: 'suus', casus: Casus.accusativus, number: Numerus.pluralis, gender: Gender.masculinum, relatio: Relatio.subiectum, tags: {'pron-suus-eius'}, note: 'Suōs ad subiectum puerōs refertur: librōs ipsōrum puerōrum.'),
  Syntagma(id: 'pron-suus-eius-006', text: 'puerī librōs {eōrum} legunt', lemmaId: 'is', casus: Casus.genetivus, number: Numerus.pluralis, gender: Gender.masculinum, relatio: Relatio.alius, tags: {'pron-suus-eius'}, note: 'Eōrum ad aliōs refertur: librōs aliōrum, nōn suōs, legunt.'),
  Syntagma(id: 'pron-suus-eius-007', text: 'Mārcus {sibi} nocet', lemmaId: 'se', casus: Casus.dativus, number: Numerus.singularis, relatio: Relatio.subiectum, tags: {'pron-suus-eius'}, note: 'Sibi reflexīvum ad subiectum Mārcum refertur: Mārcus ipse sibi nocet.'),
  Syntagma(id: 'pron-suus-eius-008', text: 'Mārcus {eī} nocet', lemmaId: 'is', casus: Casus.dativus, number: Numerus.singularis, gender: Gender.masculinum, relatio: Relatio.alius, tags: {'pron-suus-eius'}, note: 'Eī ad alium refertur: Mārcus alterī, nōn sibi, nocet.'),
  Syntagma(id: 'pron-suus-eius-009', text: 'Iūlia mātrem {suam} amat', lemmaId: 'suus', casus: Casus.accusativus, number: Numerus.singularis, gender: Gender.femininum, relatio: Relatio.subiectum, tags: {'pron-suus-eius'}, note: 'Suam ad subiectum Iūliam refertur: mātrem ipsīus Iūliae.'),
  Syntagma(id: 'pron-suus-eius-010', text: 'Iūlia Mārcum et mātrem {eius} amat', lemmaId: 'is', casus: Casus.genetivus, number: Numerus.singularis, gender: Gender.masculinum, relatio: Relatio.alius, tags: {'pron-suus-eius'}, note: 'Eius ad Mārcum refertur, nōn ad subiectum Iūliam: mātrem Mārcī.'),
  Syntagma(id: 'pron-suus-eius-011', text: 'dominus servōs {suōs} vocat', lemmaId: 'suus', casus: Casus.accusativus, number: Numerus.pluralis, gender: Gender.masculinum, relatio: Relatio.subiectum, tags: {'pron-suus-eius'}, note: 'Suōs ad subiectum dominum refertur: servōs ipsīus dominī.'),
  Syntagma(id: 'pron-suus-eius-012', text: 'Iūlius Cornēlium et servōs {eius} videt', lemmaId: 'is', casus: Casus.genetivus, number: Numerus.singularis, gender: Gender.masculinum, relatio: Relatio.alius, tags: {'pron-suus-eius'}, note: 'Eius ad Cornēlium refertur, nōn ad subiectum Iūlium: servōs Cornēliī.'),
  Syntagma(id: 'pron-suus-eius-013', text: 'ancillae dominam {suam} timent', lemmaId: 'suus', casus: Casus.accusativus, number: Numerus.singularis, gender: Gender.femininum, relatio: Relatio.subiectum, tags: {'pron-suus-eius'}, note: 'Suam ad subiectum ancillās refertur: dominam ipsārum ancillārum.'),
  Syntagma(id: 'pron-suus-eius-014', text: 'Syra Dēliam et dominam {eius} timet', lemmaId: 'is', casus: Casus.genetivus, number: Numerus.singularis, gender: Gender.femininum, relatio: Relatio.alius, tags: {'pron-suus-eius'}, note: 'Eius ad Dēliam refertur, nōn ad subiectum Syram: dominam Dēliae.'),
  Syntagma(id: 'pron-suus-eius-015', text: 'Aemilia fīliās {suās} amat', lemmaId: 'suus', casus: Casus.accusativus, number: Numerus.pluralis, gender: Gender.femininum, relatio: Relatio.subiectum, tags: {'pron-suus-eius'}, note: 'Suās ad subiectum Aemiliam refertur: fīliās ipsīus Aemiliae.'),
  Syntagma(id: 'pron-suus-eius-016', text: 'Cornēlius Iūlium et fīliās {eius} laudat', lemmaId: 'is', casus: Casus.genetivus, number: Numerus.singularis, gender: Gender.masculinum, relatio: Relatio.alius, tags: {'pron-suus-eius'}, note: 'Eius ad Iūlium refertur, nōn ad subiectum Cornēlium: fīliās Iūliī.'),
  Syntagma(id: 'pron-suus-eius-017', text: 'Mēdus {sē} laudat', lemmaId: 'se', casus: Casus.accusativus, number: Numerus.singularis, relatio: Relatio.subiectum, tags: {'pron-suus-eius'}, note: 'Sē reflexīvum ad subiectum Mēdum refertur: Mēdus sē ipsum laudat.'),
  Syntagma(id: 'pron-suus-eius-018', text: 'Mēdus {eum} laudat', lemmaId: 'is', casus: Casus.accusativus, number: Numerus.singularis, gender: Gender.masculinum, relatio: Relatio.alius, tags: {'pron-suus-eius'}, note: 'Eum ad alium virum refertur, nōn ad Mēdum ipsum.'),
  Syntagma(id: 'pron-suus-eius-019', text: 'servī {sibi} cibum parant', lemmaId: 'se', casus: Casus.dativus, number: Numerus.pluralis, relatio: Relatio.subiectum, tags: {'pron-suus-eius'}, note: 'Sibi reflexīvum ad subiectum servōs refertur: cibum sibi ipsīs parant.'),
  Syntagma(id: 'pron-suus-eius-020', text: 'servī {eīs} cibum parant', lemmaId: 'is', casus: Casus.dativus, number: Numerus.pluralis, gender: Gender.masculinum, relatio: Relatio.alius, tags: {'pron-suus-eius'}, note: 'Eīs ad aliōs refertur, ut dominōs: servī cibum aliīs parant.'),
  Syntagma(id: 'pron-suus-eius-021', text: 'Iūlius in vīllā {suā} habitat', lemmaId: 'suus', casus: Casus.ablativus, number: Numerus.singularis, gender: Gender.femininum, relatio: Relatio.subiectum, tags: {'pron-suus-eius'}, note: 'Suā ad subiectum Iūlium refertur: in vīllā ipsīus Iūliī habitat.'),
  Syntagma(id: 'pron-suus-eius-022', text: 'Iūlius in vīllā {eius} habitat', lemmaId: 'is', casus: Casus.genetivus, number: Numerus.singularis, gender: Gender.masculinum, relatio: Relatio.alius, tags: {'pron-suus-eius'}, note: 'Eius ad alium refertur: in vīllā alterīus virī, nōn suā, habitat.'),
  Syntagma(id: 'pron-suus-eius-023', text: 'Mārcus cum amīcīs {suīs} lūdit', lemmaId: 'suus', casus: Casus.ablativus, number: Numerus.pluralis, gender: Gender.masculinum, relatio: Relatio.subiectum, tags: {'pron-suus-eius'}, note: 'Suīs ad subiectum Mārcum refertur: cum amīcīs ipsīus Mārcī.'),
  Syntagma(id: 'pron-suus-eius-024', text: 'Mārcus cum Quīntō et amīcīs {eius} lūdit', lemmaId: 'is', casus: Casus.genetivus, number: Numerus.singularis, gender: Gender.masculinum, relatio: Relatio.alius, tags: {'pron-suus-eius'}, note: 'Eius ad Quīntum refertur, nōn ad subiectum Mārcum: amīcīs Quīntī.'),
  Syntagma(id: 'pron-suus-eius-025', text: 'pater fīliae {suae} rosam dat', lemmaId: 'suus', casus: Casus.dativus, number: Numerus.singularis, gender: Gender.femininum, relatio: Relatio.subiectum, tags: {'pron-suus-eius'}, note: 'Suae ad subiectum patrem refertur: fīliae ipsīus patris.'),
  Syntagma(id: 'pron-suus-eius-026', text: 'Iūlius fīliae {eius} rosam dat', lemmaId: 'is', casus: Casus.genetivus, number: Numerus.singularis, gender: Gender.masculinum, relatio: Relatio.alius, tags: {'pron-suus-eius'}, note: 'Eius ad alium refertur: fīliae alterīus virī, nōn suae, rosam dat.'),
  Syntagma(id: 'pron-suus-eius-027', text: 'mīlitēs {sē} fortiter dēfendunt', lemmaId: 'se', casus: Casus.accusativus, number: Numerus.pluralis, relatio: Relatio.subiectum, tags: {'pron-suus-eius'}, note: 'Sē reflexīvum ad subiectum mīlitēs refertur: sē ipsōs dēfendunt.'),
  Syntagma(id: 'pron-suus-eius-028', text: 'mīlitēs {eōs} fortiter dēfendunt', lemmaId: 'is', casus: Casus.accusativus, number: Numerus.pluralis, gender: Gender.masculinum, relatio: Relatio.alius, tags: {'pron-suus-eius'}, note: 'Eōs ad aliōs refertur, ut cīvēs: mīlitēs aliōs, nōn sē, dēfendunt.'),
];
