/// Contextual items — section "relativa". Authored by hand; see syntagma.dart for
/// the markers (`{target}`, `[head]`, `<candidate>`).
library;

import '../../../linguistics/model/grammar.dart';
import '../../../linguistics/model/nominal.dart';
import '../syntagma.dart';

// ignore_for_file: unused_import

const List<Syntagma> kRelativaSyntagmata = [
  // ---------------------------------------------------------------- rel-consensus
  // Tier 0: antecedent adjacent to the relative.
  Syntagma(id: 'rel-consensus-001', text: '[puer] {quī} currit laetus est', lemmaId: 'qui', casus: Casus.nominativus, number: Numerus.singularis, gender: Gender.masculinum, head: 'puer', tier: 0, tags: {'rel-consensus'}, note: 'Quī: masculīnum singulāre ā puer, nōminātīvus quia subiectum verbī currit.'),
  Syntagma(id: 'rel-consensus-002', text: '[puer] {quem} videō Mārcus est', lemmaId: 'qui', casus: Casus.accusativus, number: Numerus.singularis, gender: Gender.masculinum, head: 'puer', tier: 0, tags: {'rel-consensus'}, note: 'Quem: masculīnum singulāre ā puer, accūsātīvus quia obiectum verbī videō.'),
  Syntagma(id: 'rel-consensus-003', text: '[puer] {cuius} librum vidēs Quīntus est', lemmaId: 'qui', casus: Casus.genetivus, number: Numerus.singularis, gender: Gender.masculinum, head: 'puer', tier: 0, tags: {'rel-consensus'}, note: 'Cuius: masculīnum singulāre ā puer, genetīvus quia possessor librī.'),
  Syntagma(id: 'rel-consensus-004', text: '[ovis] {quam} pāstor videt nigra est', lemmaId: 'qui', casus: Casus.accusativus, number: Numerus.singularis, gender: Gender.femininum, head: 'ovis', tier: 0, tags: {'rel-consensus'}, note: 'Quam: fēminīnum singulāre ab ovis, accūsātīvus quia obiectum verbī videt.'),
  Syntagma(id: 'rel-consensus-005', text: '[rēx] {cui} mīlitēs pārent bonus est', lemmaId: 'qui', casus: Casus.dativus, number: Numerus.singularis, gender: Gender.masculinum, head: 'rex', tier: 0, tags: {'rel-consensus'}, note: 'Cui: masculīnum singulāre ā rēx, datīvus quia pārent datīvum regit.'),
  Syntagma(id: 'rel-consensus-006', text: '[gladius] {quō} mīles pugnat longus est', lemmaId: 'qui', casus: Casus.ablativus, number: Numerus.singularis, gender: Gender.masculinum, head: 'gladius', tier: 0, tags: {'rel-consensus'}, note: 'Quō: masculīnum singulāre ā gladius, ablātīvus īnstrūmentī: gladiō pugnat.'),
  Syntagma(id: 'rel-consensus-007', text: '[templum] {quod} vidēs antīquum est', lemmaId: 'qui', casus: Casus.accusativus, number: Numerus.singularis, gender: Gender.neutrum, head: 'templum', tier: 0, tags: {'rel-consensus'}, note: 'Quod: neutrum singulāre ā templum, accūsātīvus quia obiectum verbī vidēs.'),
  Syntagma(id: 'rel-consensus-008', text: '[mīlitēs] {quōrum} dux Aemilius est fortēs sunt', lemmaId: 'qui', casus: Casus.genetivus, number: Numerus.pluralis, gender: Gender.masculinum, head: 'miles', tier: 0, tags: {'rel-consensus'}, note: 'Quōrum: masculīnum plūrāle ā mīlitēs, genetīvus quia possessōrēs ducis.'),
  Syntagma(id: 'rel-consensus-009', text: '[fēminae] {quibus} rosās dat laetae sunt', lemmaId: 'qui', casus: Casus.dativus, number: Numerus.pluralis, gender: Gender.femininum, head: 'femina', tier: 0, tags: {'rel-consensus'}, note: 'Quibus: fēminīnum plūrāle ā fēminae, datīvus quia eīs rosae dantur.'),
  Syntagma(id: 'rel-consensus-010', text: '[rosa] {quae} in hortō est rubra est', lemmaId: 'qui', casus: Casus.nominativus, number: Numerus.singularis, gender: Gender.femininum, head: 'rosa', tier: 0, tags: {'rel-consensus'}, note: 'Quae: fēminīnum singulāre ā rosa, nōminātīvus quia subiectum verbī est.'),
  Syntagma(id: 'rel-consensus-011', text: '[servī] {quī} labōrant fessī sunt', lemmaId: 'qui', casus: Casus.nominativus, number: Numerus.pluralis, gender: Gender.masculinum, head: 'servus', tier: 0, tags: {'rel-consensus'}, note: 'Quī: masculīnum plūrāle ā servī, nōminātīvus quia subiectum verbī labōrant.'),
  Syntagma(id: 'rel-consensus-012', text: '[puellae] {quās} vocās sorōrēs sunt', lemmaId: 'qui', casus: Casus.accusativus, number: Numerus.pluralis, gender: Gender.femininum, head: 'puella', tier: 0, tags: {'rel-consensus'}, note: 'Quās: fēminīnum plūrāle ā puellae, accūsātīvus quia obiectum verbī vocās.'),
  Syntagma(id: 'rel-consensus-013', text: '[verba] {quae} dīcis vēra sunt', lemmaId: 'qui', casus: Casus.accusativus, number: Numerus.pluralis, gender: Gender.neutrum, head: 'verbum', tier: 0, tags: {'rel-consensus'}, note: 'Quae: neutrum plūrāle ā verba, accūsātīvus quia obiectum verbī dīcis.'),
  Syntagma(id: 'rel-consensus-014', text: '[nāvis] {quā} mercātor vehitur magna est', lemmaId: 'qui', casus: Casus.ablativus, number: Numerus.singularis, gender: Gender.femininum, head: 'navis', tier: 0, tags: {'rel-consensus'}, note: 'Quā: fēminīnum singulāre ā nāvis, ablātīvus īnstrūmentī: nāve vehitur.'),
  Syntagma(id: 'rel-consensus-015', text: '[flūmen] {quod} per urbem fluit Tiberis est', lemmaId: 'qui', casus: Casus.nominativus, number: Numerus.singularis, gender: Gender.neutrum, head: 'flumen', tier: 0, tags: {'rel-consensus'}, note: 'Quod: neutrum singulāre ā flūmen, nōminātīvus quia subiectum verbī fluit.'),
  Syntagma(id: 'rel-consensus-016', text: '[manus] {quā} scrībit dextra est', lemmaId: 'qui', casus: Casus.ablativus, number: Numerus.singularis, gender: Gender.femininum, head: 'manus', tier: 0, tags: {'rel-consensus'}, note: 'Quā: fēminīnum singulāre ā manus (quārtae dēclīnātiōnis), ablātīvus īnstrūmentī.'),
  Syntagma(id: 'rel-consensus-017', text: '[rēs] {quam} quaeris difficilis est', lemmaId: 'qui', casus: Casus.accusativus, number: Numerus.singularis, gender: Gender.femininum, head: 'res', tier: 0, tags: {'rel-consensus'}, note: 'Quam: fēminīnum singulāre ā rēs (quīntae dēclīnātiōnis), accūsātīvus quia obiectum verbī quaeris.'),
  // Tier 1: antecedent separated from the relative.
  Syntagma(id: 'rel-consensus-018', text: '[puerum] in hortō {quem} vidēs Mārcus est', lemmaId: 'qui', casus: Casus.accusativus, number: Numerus.singularis, gender: Gender.masculinum, head: 'puer', tier: 1, tags: {'rel-consensus'}, note: 'Quem ā puerum genus et numerum sūmit, nōn ā hortō; accūsātīvus quia obiectum verbī vidēs.'),
  Syntagma(id: 'rel-consensus-019', text: '[puer] in hortō {quī} currit Quīntus est', lemmaId: 'qui', casus: Casus.nominativus, number: Numerus.singularis, gender: Gender.masculinum, head: 'puer', tier: 1, tags: {'rel-consensus'}, note: 'Quī ad puer refertur, nōn ad hortō; nōminātīvus quia subiectum verbī currit.'),
  Syntagma(id: 'rel-consensus-020', text: '[fēmina] in vīllā {cui} servus pāret Aemilia est', lemmaId: 'qui', casus: Casus.dativus, number: Numerus.singularis, gender: Gender.femininum, head: 'femina', tier: 1, tags: {'rel-consensus'}, note: 'Cui ā fēmina genus sūmit; datīvus quia pāret datīvum regit.'),
  Syntagma(id: 'rel-consensus-021', text: '[servōs] in agrīs {quōs} vidēs Iūlius emit', lemmaId: 'qui', casus: Casus.accusativus, number: Numerus.pluralis, gender: Gender.masculinum, head: 'servus', tier: 1, tags: {'rel-consensus'}, note: 'Quōs ad servōs refertur, nōn ad agrīs; accūsātīvus quia obiectum verbī vidēs.'),
  Syntagma(id: 'rel-consensus-022', text: '[templum] in forō {quod} vidēs Iovis est', lemmaId: 'qui', casus: Casus.accusativus, number: Numerus.singularis, gender: Gender.neutrum, head: 'templum', tier: 1, tags: {'rel-consensus'}, note: 'Quod neutrum ā templum, nōn ā forō; accūsātīvus quia obiectum verbī vidēs.'),
  Syntagma(id: 'rel-consensus-023', text: '[mīlitēs] Rōmānī {quōrum} dux fortis est vincunt', lemmaId: 'qui', casus: Casus.genetivus, number: Numerus.pluralis, gender: Gender.masculinum, head: 'miles', tier: 1, tags: {'rel-consensus'}, note: 'Quōrum ā mīlitēs numerum sūmit; genetīvus quia possessōrēs ducis.'),
  Syntagma(id: 'rel-consensus-024', text: '[epistulam] ā Mārcō {quam} accipis legō', lemmaId: 'qui', casus: Casus.accusativus, number: Numerus.singularis, gender: Gender.femininum, head: 'epistula', tier: 1, tags: {'rel-consensus'}, note: 'Quam ad epistulam refertur, nōn ad Mārcō; accūsātīvus quia obiectum verbī accipis.'),
  Syntagma(id: 'rel-consensus-025', text: '[equō] albō {quō} Iūlius vehitur gaudet', lemmaId: 'qui', casus: Casus.ablativus, number: Numerus.singularis, gender: Gender.masculinum, head: 'equus', tier: 1, tags: {'rel-consensus'}, note: 'Quō ad equō refertur; ablātīvus īnstrūmentī quia equō vehitur.'),
  Syntagma(id: 'rel-consensus-026', text: '[dux] noster fortis {cui} mīlitēs pārent vincit', lemmaId: 'qui', casus: Casus.dativus, number: Numerus.singularis, gender: Gender.masculinum, head: 'dux', tier: 1, tags: {'rel-consensus'}, note: 'Cui ā dux genus et numerum sūmit; datīvus quia pārent datīvum regit.'),
  Syntagma(id: 'rel-consensus-027', text: '[puellae] parvae {quibus} māter rosās dat rīdent', lemmaId: 'qui', casus: Casus.dativus, number: Numerus.pluralis, gender: Gender.femininum, head: 'puella', tier: 1, tags: {'rel-consensus'}, note: 'Quibus ā puellae plūrāle fēminīnum; datīvus quia eīs rosae dantur.'),
  Syntagma(id: 'rel-consensus-028', text: '[urbs] magna {quam} vidēs Rōma est', lemmaId: 'qui', casus: Casus.accusativus, number: Numerus.singularis, gender: Gender.femininum, head: 'urbs', tier: 1, tags: {'rel-consensus'}, note: 'Quam ab urbs fēminīnum sūmit; accūsātīvus quia obiectum verbī vidēs.'),
  Syntagma(id: 'rel-consensus-029', text: '[verba] magistrī {quae} audīs vēra sunt', lemmaId: 'qui', casus: Casus.accusativus, number: Numerus.pluralis, gender: Gender.neutrum, head: 'verbum', tier: 1, tags: {'rel-consensus'}, note: 'Quae ad verba refertur, nōn ad magistrī; accūsātīvus quia obiectum verbī audīs.'),
  Syntagma(id: 'rel-consensus-030', text: '[fīliī] Iūliī {quī} lūdunt laetī sunt', lemmaId: 'qui', casus: Casus.nominativus, number: Numerus.pluralis, gender: Gender.masculinum, head: 'filius', tier: 1, tags: {'rel-consensus'}, note: 'Quī ad fīliī plūrāle refertur, nōn ad Iūliī; nōminātīvus quia subiectum verbī lūdunt.'),
  Syntagma(id: 'rel-consensus-031', text: '[ancilla] dominae {quae} cantat Syra est', lemmaId: 'qui', casus: Casus.nominativus, number: Numerus.singularis, gender: Gender.femininum, head: 'ancilla', tier: 1, tags: {'rel-consensus'}, note: 'Quae ad ancilla refertur, nōn ad dominae; nōminātīvus quia subiectum verbī cantat.'),
  Syntagma(id: 'rel-consensus-032', text: '[pāstor] in campō {cuius} ovēs errant dormit', lemmaId: 'qui', casus: Casus.genetivus, number: Numerus.singularis, gender: Gender.masculinum, head: 'pastor', tier: 1, tags: {'rel-consensus'}, note: 'Cuius ad pāstor refertur; genetīvus quia possessor ovium.'),
  Syntagma(id: 'rel-consensus-033', text: '[nāvēs] in portū {quae} sunt magnae sunt', lemmaId: 'qui', casus: Casus.nominativus, number: Numerus.pluralis, gender: Gender.femininum, head: 'navis', tier: 1, tags: {'rel-consensus'}, note: 'Quae ā nāvēs fēminīnum plūrāle sūmit, nōn ā portū; nōminātīvus quia subiectum.'),
  Syntagma(id: 'rel-consensus-034', text: '[exercitus] Rōmānus {quī} venit magnus est', lemmaId: 'qui', casus: Casus.nominativus, number: Numerus.singularis, gender: Gender.masculinum, head: 'exercitus', tier: 1, tags: {'rel-consensus'}, note: 'Quī ab exercitus (quārtae dēclīnātiōnis) masculīnum singulāre; nōminātīvus quia subiectum verbī venit.'),
  Syntagma(id: 'rel-consensus-035', text: '[diēs] fēstus {quō} lūdī fīunt venit', lemmaId: 'qui', casus: Casus.ablativus, number: Numerus.singularis, gender: Gender.masculinum, head: 'dies', tier: 1, tags: {'rel-consensus'}, note: 'Quō ā diēs masculīnum sūmit; ablātīvus temporis: eō diē lūdī fīunt.'),
  Syntagma(id: 'rel-consensus-036', text: '[cornua] taurī {quae} vidēs longa sunt', lemmaId: 'qui', casus: Casus.accusativus, number: Numerus.pluralis, gender: Gender.neutrum, head: 'cornu', tier: 1, tags: {'rel-consensus'}, note: 'Quae ad cornua neutrum plūrāle refertur, nōn ad taurī; accūsātīvus quia obiectum verbī vidēs.'),
  // Tier 2: relative first, antecedent after it.
  Syntagma(id: 'rel-consensus-037', text: '{quī} prīmus venit [is] vincit', lemmaId: 'qui', casus: Casus.nominativus, number: Numerus.singularis, gender: Gender.masculinum, head: 'is', tier: 2, tags: {'rel-consensus'}, note: 'Antecēdēns is post relātīvum stat; quī nōminātīvus quia subiectum verbī venit.'),
  Syntagma(id: 'rel-consensus-038', text: '{quem} vidēs [puer] Quīntus est', lemmaId: 'qui', casus: Casus.accusativus, number: Numerus.singularis, gender: Gender.masculinum, head: 'puer', tier: 2, tags: {'rel-consensus'}, note: 'Antecēdēns puer sequitur; quem accūsātīvus quia obiectum verbī vidēs.'),
  Syntagma(id: 'rel-consensus-039', text: '{quam} amās [puellam] videō', lemmaId: 'qui', casus: Casus.accusativus, number: Numerus.singularis, gender: Gender.femininum, head: 'puella', tier: 2, tags: {'rel-consensus'}, note: 'Antecēdēns puellam sequitur; quam accūsātīvus quia obiectum verbī amās.'),
  Syntagma(id: 'rel-consensus-040', text: '{cui} mīlitēs pārent [is] dux est', lemmaId: 'qui', casus: Casus.dativus, number: Numerus.singularis, gender: Gender.masculinum, head: 'is', tier: 2, tags: {'rel-consensus'}, note: 'Antecēdēns is sequitur; cui datīvus quia pārent datīvum regit.'),
  Syntagma(id: 'rel-consensus-041', text: '{quōrum} dux fortis est [mīlitēs] vincunt', lemmaId: 'qui', casus: Casus.genetivus, number: Numerus.pluralis, gender: Gender.masculinum, head: 'miles', tier: 2, tags: {'rel-consensus'}, note: 'Antecēdēns mīlitēs sequitur; quōrum genetīvus quia possessōrēs ducis.'),
  Syntagma(id: 'rel-consensus-042', text: '{quae} in hortō sunt [rosae] rubrae sunt', lemmaId: 'qui', casus: Casus.nominativus, number: Numerus.pluralis, gender: Gender.femininum, head: 'rosa', tier: 2, tags: {'rel-consensus'}, note: 'Antecēdēns rosae sequitur; quae nōminātīvus quia subiectum verbī sunt.'),
  Syntagma(id: 'rel-consensus-043', text: '{quod} dīcis [verbum] vērum est', lemmaId: 'qui', casus: Casus.accusativus, number: Numerus.singularis, gender: Gender.neutrum, head: 'verbum', tier: 2, tags: {'rel-consensus'}, note: 'Antecēdēns verbum sequitur; quod accūsātīvus quia obiectum verbī dīcis.'),
  Syntagma(id: 'rel-consensus-044', text: '{quibus} rosās dās [fēminae] rīdent', lemmaId: 'qui', casus: Casus.dativus, number: Numerus.pluralis, gender: Gender.femininum, head: 'femina', tier: 2, tags: {'rel-consensus'}, note: 'Antecēdēns fēminae sequitur; quibus datīvus quia eīs rosae dantur.'),
  Syntagma(id: 'rel-consensus-045', text: '{quō} mīles pugnat [gladius] longus est', lemmaId: 'qui', casus: Casus.ablativus, number: Numerus.singularis, gender: Gender.masculinum, head: 'gladius', tier: 2, tags: {'rel-consensus'}, note: 'Antecēdēns gladius sequitur; quō ablātīvus īnstrūmentī.'),
  Syntagma(id: 'rel-consensus-046', text: '{quās} vocās [puellae] veniunt', lemmaId: 'qui', casus: Casus.accusativus, number: Numerus.pluralis, gender: Gender.femininum, head: 'puella', tier: 2, tags: {'rel-consensus'}, note: 'Antecēdēns puellae sequitur; quās accūsātīvus quia obiectum verbī vocās.'),
  Syntagma(id: 'rel-consensus-047', text: '{cuius} liber hic est [puer] abest', lemmaId: 'qui', casus: Casus.genetivus, number: Numerus.singularis, gender: Gender.masculinum, head: 'puer', tier: 2, tags: {'rel-consensus'}, note: 'Antecēdēns puer sequitur; cuius genetīvus quia possessor librī.'),
  Syntagma(id: 'rel-consensus-048', text: '{quōs} timent servī [dominī] sevērī sunt', lemmaId: 'qui', casus: Casus.accusativus, number: Numerus.pluralis, gender: Gender.masculinum, head: 'dominus', tier: 2, tags: {'rel-consensus'}, note: 'Antecēdēns dominī sequitur; quōs accūsātīvus quia obiectum verbī timent.'),

  // ---------------------------------------------------------------- pron-quis-qui
  // Interrogative (lemma quis).
  Syntagma(id: 'pron-quis-qui-001', text: '{Quis} clāmat?', lemmaId: 'quis', casus: Casus.nominativus, number: Numerus.singularis, gender: Gender.masculinum, tags: {'pron-quis-qui'}, note: 'Interrogātiō sine antecēdente: quis interrogātīvum, nōminātīvus subiectī verbī clāmat.'),
  Syntagma(id: 'pron-quis-qui-002', text: '{Quem} vidēs?', lemmaId: 'quis', casus: Casus.accusativus, number: Numerus.singularis, gender: Gender.masculinum, tags: {'pron-quis-qui'}, note: 'Interrogātiō sine antecēdente: quem interrogātīvum, accūsātīvus obiectī verbī vidēs.'),
  Syntagma(id: 'pron-quis-qui-003', text: '{Cuius} liber est?', lemmaId: 'quis', casus: Casus.genetivus, number: Numerus.singularis, gender: Gender.masculinum, tags: {'pron-quis-qui'}, note: 'Interrogātiō sine antecēdente: cuius interrogātīvum, genetīvus possessōris.'),
  Syntagma(id: 'pron-quis-qui-004', text: '{Cui} rosam dās?', lemmaId: 'quis', casus: Casus.dativus, number: Numerus.singularis, gender: Gender.masculinum, tags: {'pron-quis-qui'}, note: 'Interrogātiō sine antecēdente: cui interrogātīvum, datīvus eius cui datur.'),
  Syntagma(id: 'pron-quis-qui-005', text: '{Quid} facis?', lemmaId: 'quis', casus: Casus.accusativus, number: Numerus.singularis, gender: Gender.neutrum, tags: {'pron-quis-qui'}, note: 'Quid interrogātīvum neutrum, accūsātīvus quia obiectum verbī facis.'),
  Syntagma(id: 'pron-quis-qui-006', text: '{Quid} est hoc?', lemmaId: 'quis', casus: Casus.nominativus, number: Numerus.singularis, gender: Gender.neutrum, tags: {'pron-quis-qui'}, note: 'Quid interrogātīvum neutrum, nōminātīvus praedicātī cum verbō est.'),
  Syntagma(id: 'pron-quis-qui-007', text: 'Ā {quō} vocāris?', lemmaId: 'quis', casus: Casus.ablativus, number: Numerus.singularis, gender: Gender.masculinum, tags: {'pron-quis-qui'}, note: 'Interrogātiō: quō interrogātīvum post praepositiōnem ā, ablātīvus.'),
  Syntagma(id: 'pron-quis-qui-008', text: 'Cum {quō} ambulās?', lemmaId: 'quis', casus: Casus.ablativus, number: Numerus.singularis, gender: Gender.masculinum, tags: {'pron-quis-qui'}, note: 'Interrogātiō: quō interrogātīvum, ablātīvus quia cum praepositiō ablātīvum regit.'),
  Syntagma(id: 'pron-quis-qui-009', text: '{Quōs} vocat magister?', lemmaId: 'quis', casus: Casus.accusativus, number: Numerus.pluralis, gender: Gender.masculinum, tags: {'pron-quis-qui'}, note: 'Interrogātiō sine antecēdente: quōs interrogātīvum, accūsātīvus plūrālis obiectī verbī vocat.'),
  Syntagma(id: 'pron-quis-qui-010', text: '{Quis} est illa fēmina?', lemmaId: 'quis', casus: Casus.nominativus, number: Numerus.singularis, gender: Gender.femininum, tags: {'pron-quis-qui'}, note: 'Quis interrogātīvum etiam dē fēminā dīcitur: nōminātīvus praedicātī.'),
  Syntagma(id: 'pron-quis-qui-011', text: '{Quōrum} librī sunt?', lemmaId: 'quis', casus: Casus.genetivus, number: Numerus.pluralis, gender: Gender.masculinum, tags: {'pron-quis-qui'}, note: 'Interrogātiō sine antecēdente: quōrum interrogātīvum, genetīvus plūrālis possessōrum.'),
  Syntagma(id: 'pron-quis-qui-012', text: '{Quibus} pecūniam dat?', lemmaId: 'quis', casus: Casus.dativus, number: Numerus.pluralis, gender: Gender.masculinum, tags: {'pron-quis-qui'}, note: 'Interrogātiō sine antecēdente: quibus interrogātīvum, datīvus plūrālis eōrum quibus datur.'),
  Syntagma(id: 'pron-quis-qui-013', text: '{Cui} Mārcus epistulam scrībit?', lemmaId: 'quis', casus: Casus.dativus, number: Numerus.singularis, gender: Gender.masculinum, tags: {'pron-quis-qui'}, note: 'Interrogātiō sine antecēdente: cui interrogātīvum, datīvus eius cui scrībitur.'),
  // Relative (lemma qui).
  Syntagma(id: 'pron-quis-qui-014', text: '[puer] {quī} clāmat Mārcus est', lemmaId: 'qui', casus: Casus.nominativus, number: Numerus.singularis, gender: Gender.masculinum, head: 'puer', tags: {'pron-quis-qui'}, note: 'Antecēdēns puer adest: quī relātīvum, nōminātīvus subiectī verbī clāmat.'),
  Syntagma(id: 'pron-quis-qui-015', text: '[vir] {quem} videō Iūlius est', lemmaId: 'qui', casus: Casus.accusativus, number: Numerus.singularis, gender: Gender.masculinum, head: 'vir', tags: {'pron-quis-qui'}, note: 'Antecēdēns vir adest: quem relātīvum, accūsātīvus obiectī verbī videō.'),
  Syntagma(id: 'pron-quis-qui-016', text: '[fēmina] {cuius} liber hic est Aemilia est', lemmaId: 'qui', casus: Casus.genetivus, number: Numerus.singularis, gender: Gender.femininum, head: 'femina', tags: {'pron-quis-qui'}, note: 'Antecēdēns fēmina adest: cuius relātīvum, genetīvus possessōris.'),
  Syntagma(id: 'pron-quis-qui-017', text: '[puella] {cui} rosam dō Iūlia est', lemmaId: 'qui', casus: Casus.dativus, number: Numerus.singularis, gender: Gender.femininum, head: 'puella', tags: {'pron-quis-qui'}, note: 'Antecēdēns puella adest: cui relātīvum, datīvus eius cui datur.'),
  Syntagma(id: 'pron-quis-qui-018', text: '[gladius] {quō} pugnat longus est', lemmaId: 'qui', casus: Casus.ablativus, number: Numerus.singularis, gender: Gender.masculinum, head: 'gladius', tags: {'pron-quis-qui'}, note: 'Antecēdēns gladius adest: quō relātīvum, ablātīvus īnstrūmentī.'),
  Syntagma(id: 'pron-quis-qui-019', text: '[servī] {quōs} vocat magister veniunt', lemmaId: 'qui', casus: Casus.accusativus, number: Numerus.pluralis, gender: Gender.masculinum, head: 'servus', tags: {'pron-quis-qui'}, note: 'Antecēdēns servī adest: quōs relātīvum, accūsātīvus plūrālis obiectī verbī vocat.'),
  Syntagma(id: 'pron-quis-qui-020', text: '[ancilla] {quae} cantat Syra est', lemmaId: 'qui', casus: Casus.nominativus, number: Numerus.singularis, gender: Gender.femininum, head: 'ancilla', tags: {'pron-quis-qui'}, note: 'Antecēdēns ancilla adest: quae relātīvum, nōminātīvus subiectī verbī cantat.'),
  Syntagma(id: 'pron-quis-qui-021', text: '[mīlitēs] {quōrum} arma vidēs Rōmānī sunt', lemmaId: 'qui', casus: Casus.genetivus, number: Numerus.pluralis, gender: Gender.masculinum, head: 'miles', tags: {'pron-quis-qui'}, note: 'Antecēdēns mīlitēs adest: quōrum relātīvum, genetīvus plūrālis possessōrum.'),
  Syntagma(id: 'pron-quis-qui-022', text: '[servī] {quibus} pecūniam dat laetī sunt', lemmaId: 'qui', casus: Casus.dativus, number: Numerus.pluralis, gender: Gender.masculinum, head: 'servus', tags: {'pron-quis-qui'}, note: 'Antecēdēns servī adest: quibus relātīvum, datīvus plūrālis eōrum quibus datur.'),
  Syntagma(id: 'pron-quis-qui-023', text: '[dōnum] {quod} accipis pulchrum est', lemmaId: 'qui', casus: Casus.accusativus, number: Numerus.singularis, gender: Gender.neutrum, head: 'donum', tags: {'pron-quis-qui'}, note: 'Antecēdēns dōnum adest: quod relātīvum neutrum, accūsātīvus obiectī verbī accipis.'),
  Syntagma(id: 'pron-quis-qui-024', text: '[puer] {cuius} pater abest trīstis est', lemmaId: 'qui', casus: Casus.genetivus, number: Numerus.singularis, gender: Gender.masculinum, head: 'puer', tags: {'pron-quis-qui'}, note: 'Antecēdēns puer adest: cuius relātīvum, genetīvus possessōris patris.'),
  Syntagma(id: 'pron-quis-qui-025', text: '[amīcus] cum {quō} ambulō Sextus est', lemmaId: 'qui', casus: Casus.ablativus, number: Numerus.singularis, gender: Gender.masculinum, head: 'amicus', tags: {'pron-quis-qui'}, note: 'Antecēdēns amīcus adest: quō relātīvum, ablātīvus post praepositiōnem cum.'),
  Syntagma(id: 'pron-quis-qui-026', text: '[fēmina] {quam} vidēs Aemilia est', lemmaId: 'qui', casus: Casus.accusativus, number: Numerus.singularis, gender: Gender.femininum, head: 'femina', tags: {'pron-quis-qui'}, note: 'Antecēdēns fēmina adest: quam relātīvum, accūsātīvus obiectī verbī vidēs.'),
];
