/// Verified noun lexicon of Grammaticon.
///
/// Dictionary entries, stems, stem classes and irregular cells follow Allen &
/// Greenough, *New Latin Grammar* (1903; DCC edition, CC BY-SA), sections
/// cited per entry. The lexicon is a representative corpus of every
/// declension, gender pattern and well-known exception; it is not a
/// dictionary. Cells no rule produces are given in `overrides`; deliberate
/// absences carry their reason.
library;

import '../model/analysis.dart' show AbsentForm;
import '../model/grammar.dart';
import '../model/noun.dart';

const _ag = 'A&G';

NounEntry _n(
  String id,
  String lemma,
  String genitive,
  Gender g,
  Declension d,
  String stem,
  String gloss, {
  ThirdStem third = ThirdStem.consonans,
  NounNumber number = NounNumber.ambo,
  bool locative = false,
  Map<String, List<String>> overrides = const {},
  List<AbsentForm> absent = const [],
  List<String> prov = const [],
  String notes = '',
}) =>
    NounEntry(
      id: id,
      lemma: lemma,
      genitive: genitive,
      gender: g,
      declension: d,
      stem: stem,
      thirdStem: third,
      number: number,
      locative: locative,
      overrides: overrides,
      absent: absent,
      provenance: prov,
      notes: notes,
      glossFr: gloss,
    );

const _m = Gender.masculinum;
const _f = Gender.femininum;
const _nt = Gender.neutrum;

/// The noun corpus. Ids are stable and used as lemma keys in the save file.
final List<NounEntry> kNouns = List.unmodifiable([
  // ------------------------------------------------------------ prīma (A&G §40–43)
  _n('rosa', 'rosa', 'rosae', _f, Declension.prima, 'ros', 'rose', prov: ['$_ag §41']),
  _n('puella', 'puella', 'puellae', _f, Declension.prima, 'puell', 'jeune fille', prov: ['$_ag §41']),
  _n('via', 'via', 'viae', _f, Declension.prima, 'vi', 'route', prov: ['$_ag §41']),
  _n('terra', 'terra', 'terrae', _f, Declension.prima, 'terr', 'terre', prov: ['$_ag §41']),
  _n('aqua', 'aqua', 'aquae', _f, Declension.prima, 'aqu', 'eau', prov: ['$_ag §41']),
  _n('insula', 'īnsula', 'īnsulae', _f, Declension.prima, 'īnsul', 'île', prov: ['$_ag §41']),
  _n('femina', 'fēmina', 'fēminae', _f, Declension.prima, 'fēmin', 'femme', prov: ['$_ag §41']),
  _n('silva', 'silva', 'silvae', _f, Declension.prima, 'silv', 'forêt', prov: ['$_ag §41']),
  _n('porta', 'porta', 'portae', _f, Declension.prima, 'port', 'porte (de ville)', prov: ['$_ag §41']),
  _n('patria', 'patria', 'patriae', _f, Declension.prima, 'patri', 'patrie', prov: ['$_ag §41']),
  _n('vita', 'vīta', 'vītae', _f, Declension.prima, 'vīt', 'vie', prov: ['$_ag §41']),
  _n('gloria', 'glōria', 'glōriae', _f, Declension.prima, 'glōri', 'gloire', prov: ['$_ag §41']),
  _n('fortuna', 'fortūna', 'fortūnae', _f, Declension.prima, 'fortūn', 'fortune', prov: ['$_ag §41']),
  _n('sapientia', 'sapientia', 'sapientiae', _f, Declension.prima, 'sapienti', 'sagesse', prov: ['$_ag §41']),
  _n('pecunia', 'pecūnia', 'pecūniae', _f, Declension.prima, 'pecūni', 'argent', prov: ['$_ag §41']),
  _n('poeta', 'poēta', 'poētae', _m, Declension.prima, 'poēt', 'poète', prov: ['$_ag §42'], notes: 'Masculīnum prīmae dēclīnātiōnis.'),
  _n('nauta', 'nauta', 'nautae', _m, Declension.prima, 'naut', 'marin', prov: ['$_ag §42'], notes: 'Masculīnum prīmae dēclīnātiōnis.'),
  _n('agricola', 'agricola', 'agricolae', _m, Declension.prima, 'agricol', 'paysan', prov: ['$_ag §42'], notes: 'Masculīnum prīmae dēclīnātiōnis.'),
  _n('dea', 'dea', 'deae', _f, Declension.prima, 'de', 'déesse', overrides: {'dat.pl': ['deābus'], 'abl.pl': ['deābus']}, prov: ['$_ag §43e'], notes: 'Datīvus et ablātīvus plūrālis deābus, nē cum deīs cōnfundātur.'),
  _n('filia', 'fīlia', 'fīliae', _f, Declension.prima, 'fīli', 'fille', overrides: {'dat.pl': ['fīliābus', 'fīliīs'], 'abl.pl': ['fīliābus', 'fīliīs']}, prov: ['$_ag §43e'], notes: 'Fīliābus discernit ā fīliīs (fīlius).'),
  _n('roma', 'Rōma', 'Rōmae', _f, Declension.prima, 'Rōm', 'Rome', number: NounNumber.singulareTantum, locative: true, prov: ['$_ag §43c', '$_ag §427'], notes: 'Locātīvus Rōmae: "Rōmae sum".'),
  _n('athenae', 'Athēnae', 'Athēnārum', _f, Declension.prima, 'Athēn', 'Athènes', number: NounNumber.pluraleTantum, locative: true, prov: ['$_ag §101', '$_ag §427'], notes: 'Plūrāle tantum; locātīvus Athēnīs.'),
  _n('divitiae', 'dīvitiae', 'dīvitiārum', _f, Declension.prima, 'dīviti', 'richesses', number: NounNumber.pluraleTantum, prov: ['$_ag §101']),
  // ------------------------------------------------------------ secunda (A&G §45–52)
  _n('servus', 'servus', 'servī', _m, Declension.secunda, 'serv', 'esclave', prov: ['$_ag §46']),
  _n('dominus', 'dominus', 'dominī', _m, Declension.secunda, 'domin', 'maître', prov: ['$_ag §46']),
  _n('amicus', 'amīcus', 'amīcī', _m, Declension.secunda, 'amīc', 'ami', prov: ['$_ag §46']),
  _n('populus', 'populus', 'populī', _m, Declension.secunda, 'popul', 'peuple', prov: ['$_ag §46']),
  _n('hortus', 'hortus', 'hortī', _m, Declension.secunda, 'hort', 'jardin', prov: ['$_ag §46']),
  _n('equus', 'equus', 'equī', _m, Declension.secunda, 'equ', 'cheval', prov: ['$_ag §46']),
  _n('animus', 'animus', 'animī', _m, Declension.secunda, 'anim', 'esprit', prov: ['$_ag §46']),
  _n('murus', 'mūrus', 'mūrī', _m, Declension.secunda, 'mūr', 'mur', prov: ['$_ag §46']),
  _n('ventus', 'ventus', 'ventī', _m, Declension.secunda, 'vent', 'vent', prov: ['$_ag §46']),
  _n('filius', 'fīlius', 'fīliī', _m, Declension.secunda, 'fīli', 'fils', prov: ['$_ag §49b'], notes: 'Vocātīvus fīlī; genetīvus fīliī (antīquius fīlī).'),
  _n('deus', 'deus', 'deī', _m, Declension.secunda, 'de', 'dieu',
      overrides: {
        'voc.sg': ['deus'],
        'nom.pl': ['dī', 'deī', 'diī'],
        'voc.pl': ['dī', 'deī', 'diī'],
        'gen.pl': ['deōrum', 'deum'],
        'dat.pl': ['dīs', 'deīs', 'diīs'],
        'abl.pl': ['dīs', 'deīs', 'diīs'],
      },
      prov: ['$_ag §49c'],
      notes: 'Vocātīvus deus; plūrālis dī, deōrum (deum), dīs.'),
  _n('puer', 'puer', 'puerī', _m, Declension.secunda, 'puer', 'garçon', prov: ['$_ag §47'], notes: 'Nōminātīvus sine -us; e servātur (puerī).'),
  _n('ager', 'ager', 'agrī', _m, Declension.secunda, 'agr', 'champ', prov: ['$_ag §47'], notes: 'e nōminātīvī cadit: agrī.'),
  _n('magister', 'magister', 'magistrī', _m, Declension.secunda, 'magistr', 'maître d’école', prov: ['$_ag §47']),
  _n('liber', 'liber', 'librī', _m, Declension.secunda, 'libr', 'livre', prov: ['$_ag §47']),
  _n('vir', 'vir', 'virī', _m, Declension.secunda, 'vir', 'homme', prov: ['$_ag §47']),
  _n('humus', 'humus', 'humī', _f, Declension.secunda, 'hum', 'sol', number: NounNumber.singulareTantum, locative: true, prov: ['$_ag §48', '$_ag §427'], notes: 'Fēminīnum in -us; locātīvus humī.'),
  _n('corinthus', 'Corinthus', 'Corinthī', _f, Declension.secunda, 'Corinth', 'Corinthe', number: NounNumber.singulareTantum, locative: true, prov: ['$_ag §48', '$_ag §427'], notes: 'Locātīvus Corinthī.'),
  _n('bellum', 'bellum', 'bellī', _nt, Declension.secunda, 'bell', 'guerre', prov: ['$_ag §48']),
  _n('templum', 'templum', 'templī', _nt, Declension.secunda, 'templ', 'temple', prov: ['$_ag §48']),
  _n('donum', 'dōnum', 'dōnī', _nt, Declension.secunda, 'dōn', 'don', prov: ['$_ag §48']),
  _n('verbum', 'verbum', 'verbī', _nt, Declension.secunda, 'verb', 'mot', prov: ['$_ag §48']),
  _n('oppidum', 'oppidum', 'oppidī', _nt, Declension.secunda, 'oppid', 'ville fortifiée', prov: ['$_ag §48']),
  _n('regnum', 'rēgnum', 'rēgnī', _nt, Declension.secunda, 'rēgn', 'royaume', prov: ['$_ag §48']),
  _n('periculum', 'perīculum', 'perīculī', _nt, Declension.secunda, 'perīcul', 'danger', prov: ['$_ag §48']),
  _n('consilium', 'cōnsilium', 'cōnsiliī', _nt, Declension.secunda, 'cōnsili', 'conseil, décision', prov: ['$_ag §49b'], notes: 'Genetīvus cōnsiliī (antīquius cōnsilī).'),
  _n('imperium', 'imperium', 'imperiī', _nt, Declension.secunda, 'imperi', 'pouvoir', prov: ['$_ag §49b']),
  _n('castra', 'castra', 'castrōrum', _nt, Declension.secunda, 'castr', 'camp', number: NounNumber.pluraleTantum, prov: ['$_ag §101'], notes: 'Plūrāle tantum: castra, castrōrum.'),
  _n('arma', 'arma', 'armōrum', _nt, Declension.secunda, 'arm', 'armes', number: NounNumber.pluraleTantum, prov: ['$_ag §101']),
  // ------------------------------------------------------------ tertia: themata cōnsonantia (A&G §56–64)
  _n('rex', 'rēx', 'rēgis', _m, Declension.tertia, 'rēg', 'roi', prov: ['$_ag §57']),
  _n('dux', 'dux', 'ducis', _m, Declension.tertia, 'duc', 'chef', prov: ['$_ag §57']),
  _n('lex', 'lēx', 'lēgis', _f, Declension.tertia, 'lēg', 'loi', prov: ['$_ag §57']),
  _n('vox', 'vōx', 'vōcis', _f, Declension.tertia, 'vōc', 'voix', prov: ['$_ag §57']),
  _n('pax', 'pāx', 'pācis', _f, Declension.tertia, 'pāc', 'paix', prov: ['$_ag §57']),
  _n('lux', 'lūx', 'lūcis', _f, Declension.tertia, 'lūc', 'lumière', prov: ['$_ag §57']),
  _n('iudex', 'iūdex', 'iūdicis', _m, Declension.tertia, 'iūdic', 'juge', prov: ['$_ag §57']),
  _n('consul', 'cōnsul', 'cōnsulis', _m, Declension.tertia, 'cōnsul', 'consul', prov: ['$_ag §62']),
  _n('miles', 'mīles', 'mīlitis', _m, Declension.tertia, 'mīlit', 'soldat', prov: ['$_ag §62']),
  _n('eques', 'eques', 'equitis', _m, Declension.tertia, 'equit', 'cavalier', prov: ['$_ag §62']),
  _n('princeps', 'prīnceps', 'prīncipis', _m, Declension.tertia, 'prīncip', 'premier, prince', prov: ['$_ag §62']),
  _n('homo', 'homō', 'hominis', _m, Declension.tertia, 'homin', 'être humain', prov: ['$_ag §62']),
  _n('orator', 'ōrātor', 'ōrātōris', _m, Declension.tertia, 'ōrātōr', 'orateur', prov: ['$_ag §62']),
  _n('senator', 'senātor', 'senātōris', _m, Declension.tertia, 'senātōr', 'sénateur', prov: ['$_ag §62']),
  _n('honor', 'honor', 'honōris', _m, Declension.tertia, 'honōr', 'honneur', prov: ['$_ag §62']),
  _n('amor', 'amor', 'amōris', _m, Declension.tertia, 'amōr', 'amour', prov: ['$_ag §62']),
  _n('labor', 'labor', 'labōris', _m, Declension.tertia, 'labōr', 'travail, peine', prov: ['$_ag §62']),
  _n('arbor', 'arbor', 'arboris', _f, Declension.tertia, 'arbor', 'arbre', prov: ['$_ag §62'], notes: 'Fēminīnum in -or.'),
  _n('soror', 'soror', 'sorōris', _f, Declension.tertia, 'sorōr', 'sœur', prov: ['$_ag §62']),
  _n('pater', 'pater', 'patris', _m, Declension.tertia, 'patr', 'père', prov: ['$_ag §62', '$_ag §71'], notes: 'Genetīvus plūrālis patrum (nōn -ium).'),
  _n('mater', 'māter', 'mātris', _f, Declension.tertia, 'mātr', 'mère', prov: ['$_ag §62', '$_ag §71']),
  _n('frater', 'frāter', 'frātris', _m, Declension.tertia, 'frātr', 'frère', prov: ['$_ag §62', '$_ag §71']),
  _n('legio', 'lēgiō', 'lēgiōnis', _f, Declension.tertia, 'lēgiōn', 'légion', prov: ['$_ag §62']),
  _n('oratio', 'ōrātiō', 'ōrātiōnis', _f, Declension.tertia, 'ōrātiōn', 'discours', prov: ['$_ag §62']),
  _n('civitas', 'cīvitās', 'cīvitātis', _f, Declension.tertia, 'cīvitāt', 'cité', overrides: {'gen.pl': ['cīvitātum', 'cīvitātium']}, prov: ['$_ag §62', '$_ag §71'], notes: 'Genetīvus plūrālis cīvitātum aut cīvitātium.'),
  _n('virtus', 'virtūs', 'virtūtis', _f, Declension.tertia, 'virtūt', 'courage, vertu', prov: ['$_ag §62']),
  _n('aetas', 'aetās', 'aetātis', _f, Declension.tertia, 'aetāt', 'âge', overrides: {'gen.pl': ['aetātum', 'aetātium']}, prov: ['$_ag §71']),
  _n('pes', 'pēs', 'pedis', _m, Declension.tertia, 'ped', 'pied', prov: ['$_ag §62']),
  _n('lapis', 'lapis', 'lapidis', _m, Declension.tertia, 'lapid', 'pierre', prov: ['$_ag §62']),
  _n('sacerdos', 'sacerdōs', 'sacerdōtis', _m, Declension.tertia, 'sacerdōt', 'prêtre', prov: ['$_ag §62'], notes: 'Genus commūne (m. et f.).'),
  _n('canis', 'canis', 'canis', _m, Declension.tertia, 'can', 'chien', prov: ['$_ag §71'], notes: 'Thema cōnsonāns quamquam parisyllabum: canum.'),
  _n('iuvenis', 'iuvenis', 'iuvenis', _m, Declension.tertia, 'iuven', 'jeune homme', prov: ['$_ag §71'], notes: 'Genetīvus plūrālis iuvenum.'),
  _n('senex', 'senex', 'senis', _m, Declension.tertia, 'sen', 'vieillard', prov: ['$_ag §79'], notes: 'Thema sen-: senis, senem, senum.'),
  _n('bos', 'bōs', 'bovis', _m, Declension.tertia, 'bov', 'bœuf', overrides: {'gen.pl': ['boum'], 'dat.pl': ['bōbus', 'būbus'], 'abl.pl': ['bōbus', 'būbus']}, prov: ['$_ag §79'], notes: 'Genus commūne; plūrālis bovēs, boum, bōbus (būbus).'),
  _n('iuppiter', 'Iuppiter', 'Iovis', _m, Declension.tertia, 'Iov', 'Jupiter', number: NounNumber.singulareTantum, prov: ['$_ag §79'], notes: 'Nōminātīvus et vocātīvus Iuppiter, cēterī cāsūs ā themate Iov-.'),
  _n('carthago', 'Carthāgō', 'Carthāginis', _f, Declension.tertia, 'Carthāgin', 'Carthage', number: NounNumber.singulareTantum, locative: true, prov: ['$_ag §427'], notes: 'Locātīvus Carthāginī aut Carthāgine.'),
  _n('rus', 'rūs', 'rūris', _nt, Declension.tertia, 'rūr', 'campagne', number: NounNumber.singulareTantum, locative: true, prov: ['$_ag §427'], notes: 'Locātīvus rūrī (rūre). Plūrālis rūra rārus, hīc omissus.'),
  _n('corpus', 'corpus', 'corporis', _nt, Declension.tertia, 'corpor', 'corps', prov: ['$_ag §64']),
  _n('tempus', 'tempus', 'temporis', _nt, Declension.tertia, 'tempor', 'temps', prov: ['$_ag §64']),
  _n('genus', 'genus', 'generis', _nt, Declension.tertia, 'gener', 'genre, race', prov: ['$_ag §64']),
  _n('opus', 'opus', 'operis', _nt, Declension.tertia, 'oper', 'ouvrage', prov: ['$_ag §64']),
  _n('nomen', 'nōmen', 'nōminis', _nt, Declension.tertia, 'nōmin', 'nom', prov: ['$_ag §64']),
  _n('flumen', 'flūmen', 'flūminis', _nt, Declension.tertia, 'flūmin', 'fleuve', prov: ['$_ag §64']),
  _n('carmen', 'carmen', 'carminis', _nt, Declension.tertia, 'carmin', 'poème, chant', prov: ['$_ag §64']),
  _n('caput', 'caput', 'capitis', _nt, Declension.tertia, 'capit', 'tête', prov: ['$_ag §64']),
  _n('iter', 'iter', 'itineris', _nt, Declension.tertia, 'itiner', 'chemin, marche', prov: ['$_ag §79'], notes: 'Thema itiner-.'),
  _n('litus', 'lītus', 'lītoris', _nt, Declension.tertia, 'lītor', 'rivage', prov: ['$_ag §64']),
  _n('vulnus', 'vulnus', 'vulneris', _nt, Declension.tertia, 'vulner', 'blessure', prov: ['$_ag §64']),
  _n('pectus', 'pectus', 'pectoris', _nt, Declension.tertia, 'pector', 'poitrine', prov: ['$_ag §64']),
  _n('os', 'os', 'ossis', _nt, Declension.tertia, 'oss', 'os', overrides: {'gen.pl': ['ossium']}, prov: ['$_ag §71'], notes: 'Genetīvus plūrālis ossium.'),
  // ------------------------------------------------------------ tertia: themata in -i (A&G §65–71, §75–76)
  _n('civis', 'cīvis', 'cīvis', _m, Declension.tertia, 'cīv', 'citoyen', third: ThirdStem.vocalisI, prov: ['$_ag §66'], notes: 'Genus commūne; genetīvus plūrālis cīvium.'),
  _n('hostis', 'hostis', 'hostis', _m, Declension.tertia, 'host', 'ennemi', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('navis', 'nāvis', 'nāvis', _f, Declension.tertia, 'nāv', 'navire', third: ThirdStem.vocalisI, overrides: {'acc.sg': ['nāvem', 'nāvim'], 'abl.sg': ['nāve', 'nāvī']}, prov: ['$_ag §75', '$_ag §76'], notes: 'Accūsātīvus nāvem (nāvim), ablātīvus nāve (nāvī).'),
  _n('turris', 'turris', 'turris', _f, Declension.tertia, 'turr', 'tour', third: ThirdStem.vocalisI, overrides: {'acc.sg': ['turrim', 'turrem'], 'abl.sg': ['turrī', 'turre']}, prov: ['$_ag §75', '$_ag §76'], notes: 'Accūsātīvus turrim (turrem), ablātīvus turrī (turre).'),
  _n('ignis', 'ignis', 'ignis', _m, Declension.tertia, 'ign', 'feu', third: ThirdStem.vocalisI, overrides: {'abl.sg': ['ignī', 'igne']}, prov: ['$_ag §76'], notes: 'Ablātīvus ignī aut igne.'),
  _n('collis', 'collis', 'collis', _m, Declension.tertia, 'coll', 'colline', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('finis', 'fīnis', 'fīnis', _m, Declension.tertia, 'fīn', 'limite, fin', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('avis', 'avis', 'avis', _f, Declension.tertia, 'av', 'oiseau', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('nubes', 'nūbēs', 'nūbis', _f, Declension.tertia, 'nūb', 'nuage', third: ThirdStem.vocalisI, prov: ['$_ag §66'], notes: 'Parisyllabum in -ēs: nūbium.'),
  _n('caedes', 'caedēs', 'caedis', _f, Declension.tertia, 'caed', 'massacre', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('urbs', 'urbs', 'urbis', _f, Declension.tertia, 'urb', 'ville', third: ThirdStem.vocalisI, prov: ['$_ag §66'], notes: 'Monosyllabum: urbium.'),
  _n('arx', 'arx', 'arcis', _f, Declension.tertia, 'arc', 'citadelle', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('mons', 'mōns', 'montis', _m, Declension.tertia, 'mont', 'montagne', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('pons', 'pōns', 'pontis', _m, Declension.tertia, 'pont', 'pont', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('gens', 'gēns', 'gentis', _f, Declension.tertia, 'gent', 'peuple, famille', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('mens', 'mēns', 'mentis', _f, Declension.tertia, 'ment', 'esprit', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('mors', 'mors', 'mortis', _f, Declension.tertia, 'mort', 'mort', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('ars', 'ars', 'artis', _f, Declension.tertia, 'art', 'art', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('pars', 'pars', 'partis', _f, Declension.tertia, 'part', 'partie', third: ThirdStem.vocalisI, prov: ['$_ag §66'], notes: 'Accūsātīvus plūrālis partēs aut partīs.'),
  _n('dens', 'dēns', 'dentis', _m, Declension.tertia, 'dent', 'dent', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('nox', 'nox', 'noctis', _f, Declension.tertia, 'noct', 'nuit', third: ThirdStem.vocalisI, prov: ['$_ag §66'], notes: 'Genetīvus plūrālis noctium.'),
  _n('vis', 'vīs', 'vīs', _f, Declension.tertia, 'v', 'force', third: ThirdStem.vocalisIPura,
      overrides: {
        'gen.sg': ['vīs'],
        'nom.pl': ['vīrēs'],
        'voc.pl': ['vīrēs'],
        'gen.pl': ['vīrium'],
        'dat.pl': ['vīribus'],
        'abl.pl': ['vīribus'],
        'acc.pl': ['vīrēs', 'vīrīs'],
      },
      prov: ['$_ag §79'],
      notes: 'Singulāris vīs, vīs, vī, vim, vī (genetīvus et datīvus rārī); plūrālis ā themate vīr-.'),
  _n('mare', 'mare', 'maris', _nt, Declension.tertia, 'mar', 'mer', third: ThirdStem.neutrumI, prov: ['$_ag §68'], notes: 'Ablātīvus marī; plūrālis maria, marium (rārum).'),
  _n('animal', 'animal', 'animālis', _nt, Declension.tertia, 'animāl', 'animal', third: ThirdStem.neutrumI, prov: ['$_ag §68']),
  _n('exemplar', 'exemplar', 'exemplāris', _nt, Declension.tertia, 'exemplār', 'modèle', third: ThirdStem.neutrumI, prov: ['$_ag §68']),
  _n('moenia', 'moenia', 'moenium', _nt, Declension.tertia, 'moen', 'remparts', third: ThirdStem.neutrumI, number: NounNumber.pluraleTantum, prov: ['$_ag §101'], notes: 'Plūrāle tantum: moenia, moenium, moenibus.'),
  // ------------------------------------------------------------ quārta (A&G §89–94)
  _n('manus', 'manus', 'manūs', _f, Declension.quarta, 'man', 'main', prov: ['$_ag §90'], notes: 'Fēminīnum quārtae dēclīnātiōnis.'),
  _n('exercitus', 'exercitus', 'exercitūs', _m, Declension.quarta, 'exercit', 'armée', prov: ['$_ag §90']),
  _n('senatus', 'senātus', 'senātūs', _m, Declension.quarta, 'senāt', 'sénat', overrides: {'gen.sg': ['senātūs', 'senātī']}, prov: ['$_ag §92a'], notes: 'Genetīvus senātūs (etiam senātī).'),
  _n('fructus', 'frūctus', 'frūctūs', _m, Declension.quarta, 'frūct', 'fruit', prov: ['$_ag §90']),
  _n('casus', 'cāsus', 'cāsūs', _m, Declension.quarta, 'cās', 'chute, hasard, cas', prov: ['$_ag §90']),
  _n('portus', 'portus', 'portūs', _m, Declension.quarta, 'port', 'port', overrides: {'dat.pl': ['portibus', 'portubus'], 'abl.pl': ['portibus', 'portubus']}, prov: ['$_ag §92c']),
  _n('tribus', 'tribus', 'tribūs', _f, Declension.quarta, 'trib', 'tribu', overrides: {'dat.pl': ['tribubus'], 'abl.pl': ['tribubus']}, prov: ['$_ag §92c'], notes: 'Datīvus et ablātīvus plūrālis tribubus.'),
  _n('lacus', 'lacus', 'lacūs', _m, Declension.quarta, 'lac', 'lac', overrides: {'dat.pl': ['lacubus'], 'abl.pl': ['lacubus']}, prov: ['$_ag §92c']),
  _n('domus', 'domus', 'domūs', _f, Declension.quarta, 'dom', 'maison', locative: true,
      overrides: {
        'dat.sg': ['domuī', 'domō'],
        'abl.sg': ['domō', 'domū'],
        'gen.pl': ['domuum', 'domōrum'],
        'acc.pl': ['domōs', 'domūs'],
        'loc.sg': ['domī'],
      },
      prov: ['$_ag §93', '$_ag §427'],
      notes: 'Fōrmae secundae et quārtae mixtae; locātīvus domī.'),
  _n('cornu', 'cornū', 'cornūs', _nt, Declension.quarta, 'corn', 'corne, aile (d’armée)', prov: ['$_ag §89']),
  _n('genu', 'genū', 'genūs', _nt, Declension.quarta, 'gen', 'genou', prov: ['$_ag §89']),
  // ------------------------------------------------------------ quīnta (A&G §96–98)
  _n('res', 'rēs', 'reī', _f, Declension.quinta, 'r', 'chose, affaire', prov: ['$_ag §97'], notes: 'ē brevis in reī post cōnsonantem.'),
  _n('dies', 'diēs', 'diēī', _m, Declension.quinta, 'di', 'jour', prov: ['$_ag §97'], notes: 'Masculīnum (fēminīnum dē diē cōnstitūtā); ē longa in diēī post vōcālem.'),
  _n('spes', 'spēs', 'speī', _f, Declension.quinta, 'sp', 'espoir', absent: [AbsentForm('gen.pl', AbsenceStatus.nonUsitatur, note: 'plūrālis nōminātīvō et accūsātīvō tantum'), AbsentForm('dat.pl', AbsenceStatus.nonUsitatur), AbsentForm('abl.pl', AbsenceStatus.nonUsitatur)], prov: ['$_ag §98b']),
  _n('fides', 'fidēs', 'fideī', _f, Declension.quinta, 'fid', 'confiance, loyauté', number: NounNumber.singulareTantum, prov: ['$_ag §98b']),
  _n('acies', 'aciēs', 'aciēī', _f, Declension.quinta, 'aci', 'ligne de bataille', absent: [AbsentForm('gen.pl', AbsenceStatus.nonUsitatur), AbsentForm('dat.pl', AbsenceStatus.nonUsitatur), AbsentForm('abl.pl', AbsenceStatus.nonUsitatur)], prov: ['$_ag §98b']),
  _n('meridies', 'merīdiēs', 'merīdiēī', _m, Declension.quinta, 'merīdi', 'midi', number: NounNumber.singulareTantum, prov: ['$_ag §96']),
]);
