/// Verified noun lexicon of Grammaticon.
///
/// Dictionary entries, stems, stem classes and irregular cells follow Allen &
/// Greenough, *New Latin Grammar* (1903; DCC edition, CC BY-SA), sections
/// cited per entry. The lexicon is a representative corpus of every
/// declension, gender pattern and well-known exception; it is not a
/// dictionary. Cells no rule produces are given in `overrides`; deliberate
/// absences carry their reason.
library;

import '../model/analysis.dart' show AbsentForm;
import '../model/grammar.dart';
import '../model/noun.dart';

const _ag = 'A&G';

NounEntry _n(
  String id,
  String lemma,
  String genitive,
  Gender g,
  Declension d,
  String stem,
  String gloss, {
  ThirdStem third = ThirdStem.consonans,
  NounNumber number = NounNumber.ambo,
  bool locative = false,
  Map<String, List<String>> overrides = const {},
  List<AbsentForm> absent = const [],
  List<String> prov = const [],
  String notes = '',
}) =>
    NounEntry(
      id: id,
      lemma: lemma,
      genitive: genitive,
      gender: g,
      declension: d,
      stem: stem,
      thirdStem: third,
      number: number,
      locative: locative,
      overrides: overrides,
      absent: absent,
      provenance: prov,
      notes: notes,
      glossFr: gloss,
    );

const _m = Gender.masculinum;
const _f = Gender.femininum;
const _nt = Gender.neutrum;

/// The noun corpus. Ids are stable and used as lemma keys in the save file.
final List<NounEntry> kNouns = List.unmodifiable([
  // ------------------------------------------------------------ prīma (A&G §40–43)
  _n('rosa', 'rosa', 'rosae', _f, Declension.prima, 'ros', 'rose', prov: ['$_ag §41']),
  _n('puella', 'puella', 'puellae', _f, Declension.prima, 'puell', 'jeune fille', prov: ['$_ag §41']),
  _n('via', 'via', 'viae', _f, Declension.prima, 'vi', 'route', prov: ['$_ag §41']),
  _n('terra', 'terra', 'terrae', _f, Declension.prima, 'terr', 'terre', prov: ['$_ag §41']),
  _n('aqua', 'aqua', 'aquae', _f, Declension.prima, 'aqu', 'eau', prov: ['$_ag §41']),
  _n('insula', 'īnsula', 'īnsulae', _f, Declension.prima, 'īnsul', 'île', prov: ['$_ag §41']),
  _n('femina', 'fēmina', 'fēminae', _f, Declension.prima, 'fēmin', 'femme', prov: ['$_ag §41']),
  _n('silva', 'silva', 'silvae', _f, Declension.prima, 'silv', 'forêt', prov: ['$_ag §41']),
  _n('porta', 'porta', 'portae', _f, Declension.prima, 'port', 'porte (de ville)', prov: ['$_ag §41']),
  _n('patria', 'patria', 'patriae', _f, Declension.prima, 'patri', 'patrie', prov: ['$_ag §41']),
  _n('vita', 'vīta', 'vītae', _f, Declension.prima, 'vīt', 'vie', prov: ['$_ag §41']),
  _n('gloria', 'glōria', 'glōriae', _f, Declension.prima, 'glōri', 'gloire', prov: ['$_ag §41']),
  _n('fortuna', 'fortūna', 'fortūnae', _f, Declension.prima, 'fortūn', 'fortune', prov: ['$_ag §41']),
  _n('sapientia', 'sapientia', 'sapientiae', _f, Declension.prima, 'sapienti', 'sagesse', prov: ['$_ag §41']),
  _n('pecunia', 'pecūnia', 'pecūniae', _f, Declension.prima, 'pecūni', 'argent', prov: ['$_ag §41']),
  _n('poeta', 'poēta', 'poētae', _m, Declension.prima, 'poēt', 'poète', prov: ['$_ag §42'], notes: 'Masculīnum prīmae dēclīnātiōnis.'),
  _n('nauta', 'nauta', 'nautae', _m, Declension.prima, 'naut', 'marin', prov: ['$_ag §42'], notes: 'Masculīnum prīmae dēclīnātiōnis.'),
  _n('agricola', 'agricola', 'agricolae', _m, Declension.prima, 'agricol', 'paysan', prov: ['$_ag §42'], notes: 'Masculīnum prīmae dēclīnātiōnis.'),
  _n('dea', 'dea', 'deae', _f, Declension.prima, 'de', 'déesse', overrides: {'dat.pl': ['deābus'], 'abl.pl': ['deābus']}, prov: ['$_ag §43e'], notes: 'Datīvus et ablātīvus plūrālis deābus, nē cum deīs cōnfundātur.'),
  _n('filia', 'fīlia', 'fīliae', _f, Declension.prima, 'fīli', 'fille', overrides: {'dat.pl': ['fīliābus', 'fīliīs'], 'abl.pl': ['fīliābus', 'fīliīs']}, prov: ['$_ag §43e'], notes: 'Fīliābus discernit ā fīliīs (fīlius).'),
  _n('roma', 'Rōma', 'Rōmae', _f, Declension.prima, 'Rōm', 'Rome', number: NounNumber.singulareTantum, locative: true, prov: ['$_ag §43c', '$_ag §427'], notes: 'Locātīvus Rōmae: "Rōmae sum".'),
  _n('athenae', 'Athēnae', 'Athēnārum', _f, Declension.prima, 'Athēn', 'Athènes', number: NounNumber.pluraleTantum, locative: true, prov: ['$_ag §101', '$_ag §427'], notes: 'Plūrāle tantum; locātīvus Athēnīs.'),
  _n('divitiae', 'dīvitiae', 'dīvitiārum', _f, Declension.prima, 'dīviti', 'richesses', number: NounNumber.pluraleTantum, prov: ['$_ag §101']),
  // ----- LLPSI Familia Rōmāna cap. 1–19 (prīma)
  _n('ancilla', 'ancilla', 'ancillae', _f, Declension.prima, 'ancill', 'servante', prov: ['$_ag §41']),
  _n('familia', 'familia', 'familiae', _f, Declension.prima, 'famili', 'famille, maisonnée', prov: ['$_ag §41', '$_ag §43b'], notes: 'Genetīvus antīquus familiās in "pater familiās".'),
  _n('villa', 'vīlla', 'vīllae', _f, Declension.prima, 'vīll', 'maison de campagne', prov: ['$_ag §41']),
  _n('mensa', 'mēnsa', 'mēnsae', _f, Declension.prima, 'mēns', 'table', prov: ['$_ag §41']),
  _n('fenestra', 'fenestra', 'fenestrae', _f, Declension.prima, 'fenestr', 'fenêtre', prov: ['$_ag §41']),
  _n('ianua', 'iānua', 'iānuae', _f, Declension.prima, 'iānu', 'porte (de maison)', prov: ['$_ag §41']),
  _n('cena', 'cēna', 'cēnae', _f, Declension.prima, 'cēn', 'dîner', prov: ['$_ag §41']),
  _n('epistula', 'epistula', 'epistulae', _f, Declension.prima, 'epistul', 'lettre (missive)', prov: ['$_ag §41']),
  _n('tabula', 'tabula', 'tabulae', _f, Declension.prima, 'tabul', 'tablette', prov: ['$_ag §41']),
  _n('littera', 'littera', 'litterae', _f, Declension.prima, 'litter', 'lettre (de l’alphabet); pl. lettre, littérature', prov: ['$_ag §41', '$_ag §107'], notes: 'Plūrālis litterae etiam "epistula" significat.'),
  _n('syllaba', 'syllaba', 'syllabae', _f, Declension.prima, 'syllab', 'syllabe', prov: ['$_ag §41']),
  _n('pagina', 'pāgina', 'pāginae', _f, Declension.prima, 'pāgin', 'page', prov: ['$_ag §41']),
  _n('sententia', 'sententia', 'sententiae', _f, Declension.prima, 'sententi', 'phrase, opinion', prov: ['$_ag §41']),
  _n('lingua', 'lingua', 'linguae', _f, Declension.prima, 'lingu', 'langue', prov: ['$_ag §41']),
  _n('pila', 'pila', 'pilae', _f, Declension.prima, 'pil', 'balle', prov: ['$_ag §41']),
  _n('umbra', 'umbra', 'umbrae', _f, Declension.prima, 'umbr', 'ombre', prov: ['$_ag §41']),
  _n('spina', 'spīna', 'spīnae', _f, Declension.prima, 'spīn', 'épine', prov: ['$_ag §41']),
  _n('ora', 'ōra', 'ōrae', _f, Declension.prima, 'ōr', 'côte, rivage', prov: ['$_ag §41']),
  _n('hora', 'hōra', 'hōrae', _f, Declension.prima, 'hōr', 'heure', prov: ['$_ag §41']),
  _n('luna', 'lūna', 'lūnae', _f, Declension.prima, 'lūn', 'lune', prov: ['$_ag §41']),
  _n('stella', 'stēlla', 'stēllae', _f, Declension.prima, 'stēll', 'étoile', prov: ['$_ag §41']),
  _n('herba', 'herba', 'herbae', _f, Declension.prima, 'herb', 'herbe', prov: ['$_ag §41']),
  _n('uva', 'ūva', 'ūvae', _f, Declension.prima, 'ūv', 'grappe de raisin', prov: ['$_ag §41']),
  _n('hasta', 'hasta', 'hastae', _f, Declension.prima, 'hast', 'lance', prov: ['$_ag §41']),
  _n('sagitta', 'sagitta', 'sagittae', _f, Declension.prima, 'sagitt', 'flèche', prov: ['$_ag §41']),
  _n('pugna', 'pugna', 'pugnae', _f, Declension.prima, 'pugn', 'combat', prov: ['$_ag §41']),
  _n('copia', 'cōpia', 'cōpiae', _f, Declension.prima, 'cōpi', 'abondance; pl. troupes', prov: ['$_ag §41', '$_ag §107'], notes: 'Plūrālis cōpiae "mīlitēs" significat.'),
  _n('lacrima', 'lacrima', 'lacrimae', _f, Declension.prima, 'lacrim', 'larme', prov: ['$_ag §41']),
  _n('amica', 'amīca', 'amīcae', _f, Declension.prima, 'amīc', 'amie', prov: ['$_ag §41']),
  _n('domina', 'domina', 'dominae', _f, Declension.prima, 'domin', 'maîtresse de maison', prov: ['$_ag §41']),
  _n('forma', 'fōrma', 'fōrmae', _f, Declension.prima, 'fōrm', 'forme, beauté', prov: ['$_ag §41']),
  _n('columna', 'columna', 'columnae', _f, Declension.prima, 'column', 'colonne', prov: ['$_ag §41']),
  _n('statua', 'statua', 'statuae', _f, Declension.prima, 'statu', 'statue', prov: ['$_ag §41']),
  _n('casa', 'casa', 'casae', _f, Declension.prima, 'cas', 'cabane', prov: ['$_ag §41']),
  _n('bestia', 'bēstia', 'bēstiae', _f, Declension.prima, 'bēsti', 'bête', prov: ['$_ag §41']),
  _n('fabula', 'fābula', 'fābulae', _f, Declension.prima, 'fābul', 'histoire, fable', prov: ['$_ag §41']),
  _n('tunica', 'tunica', 'tunicae', _f, Declension.prima, 'tunic', 'tunique', prov: ['$_ag §41']),
  _n('gemma', 'gemma', 'gemmae', _f, Declension.prima, 'gemm', 'pierre précieuse', prov: ['$_ag §41']),
  _n('margarita', 'margarīta', 'margarītae', _f, Declension.prima, 'margarīt', 'perle', prov: ['$_ag §41']),
  _n('provincia', 'prōvincia', 'prōvinciae', _f, Declension.prima, 'prōvinci', 'province', prov: ['$_ag §41']),
  _n('italia', 'Italia', 'Italiae', _f, Declension.prima, 'Itali', 'Italie', number: NounNumber.singulareTantum, prov: ['$_ag §41'], notes: 'Nōmen regiōnis: sine locātīvō ("in Italiā").'),
  _n('graecia', 'Graecia', 'Graeciae', _f, Declension.prima, 'Graeci', 'Grèce', number: NounNumber.singulareTantum, prov: ['$_ag §41']),
  _n('germania', 'Germānia', 'Germāniae', _f, Declension.prima, 'Germāni', 'Germanie', number: NounNumber.singulareTantum, prov: ['$_ag §41']),
  _n('gallia', 'Gallia', 'Galliae', _f, Declension.prima, 'Galli', 'Gaule', number: NounNumber.singulareTantum, prov: ['$_ag §41']),
  _n('hispania', 'Hispānia', 'Hispāniae', _f, Declension.prima, 'Hispāni', 'Espagne', number: NounNumber.singulareTantum, prov: ['$_ag §41']),
  _n('britannia', 'Britannia', 'Britanniae', _f, Declension.prima, 'Britanni', 'Bretagne (Grande-)', number: NounNumber.singulareTantum, prov: ['$_ag §41']),
  _n('sicilia', 'Sicilia', 'Siciliae', _f, Declension.prima, 'Sicili', 'Sicile', number: NounNumber.singulareTantum, prov: ['$_ag §41'], notes: 'Īnsula magna: sine locātīvō ("in Siciliā").'),
  _n('sardinia', 'Sardinia', 'Sardiniae', _f, Declension.prima, 'Sardini', 'Sardaigne', number: NounNumber.singulareTantum, prov: ['$_ag §41']),
  _n('ostia', 'Ōstia', 'Ōstiae', _f, Declension.prima, 'Ōsti', 'Ostie', number: NounNumber.singulareTantum, locative: true, prov: ['$_ag §41', '$_ag §427'], notes: 'Locātīvus Ōstiae.'),
  _n('capua', 'Capua', 'Capuae', _f, Declension.prima, 'Capu', 'Capoue', number: NounNumber.singulareTantum, locative: true, prov: ['$_ag §41', '$_ag §427'], notes: 'Locātīvus Capuae.'),
  _n('aemilia', 'Aemilia', 'Aemiliae', _f, Declension.prima, 'Aemili', 'Émilie', number: NounNumber.singulareTantum, prov: ['$_ag §41']),
  _n('iulia', 'Iūlia', 'Iūliae', _f, Declension.prima, 'Iūli', 'Julie', number: NounNumber.singulareTantum, prov: ['$_ag §41']),
  _n('syra', 'Syra', 'Syrae', _f, Declension.prima, 'Syr', 'Syra', number: NounNumber.singulareTantum, prov: ['$_ag §41']),
  _n('delia', 'Dēlia', 'Dēliae', _f, Declension.prima, 'Dēli', 'Délia', number: NounNumber.singulareTantum, prov: ['$_ag §41']),
  _n('lydia', 'Lȳdia', 'Lȳdiae', _f, Declension.prima, 'Lȳdi', 'Lydie', number: NounNumber.singulareTantum, prov: ['$_ag §41']),
  _n('diana', 'Diāna', 'Diānae', _f, Declension.prima, 'Diān', 'Diane', number: NounNumber.singulareTantum, prov: ['$_ag §41']),
  _n('minerva', 'Minerva', 'Minervae', _f, Declension.prima, 'Minerv', 'Minerve', number: NounNumber.singulareTantum, prov: ['$_ag §41']),
  // ------------------------------------------------------------ secunda (A&G §45–52)
  _n('servus', 'servus', 'servī', _m, Declension.secunda, 'serv', 'esclave', prov: ['$_ag §46']),
  _n('dominus', 'dominus', 'dominī', _m, Declension.secunda, 'domin', 'maître', prov: ['$_ag §46']),
  _n('amicus', 'amīcus', 'amīcī', _m, Declension.secunda, 'amīc', 'ami', prov: ['$_ag §46']),
  _n('populus', 'populus', 'populī', _m, Declension.secunda, 'popul', 'peuple', prov: ['$_ag §46']),
  _n('hortus', 'hortus', 'hortī', _m, Declension.secunda, 'hort', 'jardin', prov: ['$_ag §46']),
  _n('equus', 'equus', 'equī', _m, Declension.secunda, 'equ', 'cheval', prov: ['$_ag §46']),
  _n('animus', 'animus', 'animī', _m, Declension.secunda, 'anim', 'esprit', prov: ['$_ag §46']),
  _n('murus', 'mūrus', 'mūrī', _m, Declension.secunda, 'mūr', 'mur', prov: ['$_ag §46']),
  _n('ventus', 'ventus', 'ventī', _m, Declension.secunda, 'vent', 'vent', prov: ['$_ag §46']),
  _n('filius', 'fīlius', 'fīliī', _m, Declension.secunda, 'fīli', 'fils', prov: ['$_ag §49b'], notes: 'Vocātīvus fīlī; genetīvus fīliī (antīquius fīlī).'),
  _n('deus', 'deus', 'deī', _m, Declension.secunda, 'de', 'dieu',
      overrides: {
        'voc.sg': ['deus'],
        'nom.pl': ['dī', 'deī', 'diī'],
        'voc.pl': ['dī', 'deī', 'diī'],
        'gen.pl': ['deōrum', 'deum'],
        'dat.pl': ['dīs', 'deīs', 'diīs'],
        'abl.pl': ['dīs', 'deīs', 'diīs'],
      },
      prov: ['$_ag §49c'],
      notes: 'Vocātīvus deus; plūrālis dī, deōrum (deum), dīs.'),
  _n('puer', 'puer', 'puerī', _m, Declension.secunda, 'puer', 'garçon', prov: ['$_ag §47'], notes: 'Nōminātīvus sine -us; e servātur (puerī).'),
  _n('ager', 'ager', 'agrī', _m, Declension.secunda, 'agr', 'champ', prov: ['$_ag §47'], notes: 'e nōminātīvī cadit: agrī.'),
  _n('magister', 'magister', 'magistrī', _m, Declension.secunda, 'magistr', 'maître d’école', prov: ['$_ag §47']),
  _n('liber', 'liber', 'librī', _m, Declension.secunda, 'libr', 'livre', prov: ['$_ag §47']),
  _n('vir', 'vir', 'virī', _m, Declension.secunda, 'vir', 'homme', prov: ['$_ag §47']),
  _n('humus', 'humus', 'humī', _f, Declension.secunda, 'hum', 'sol', number: NounNumber.singulareTantum, locative: true, prov: ['$_ag §48', '$_ag §427'], notes: 'Fēminīnum in -us; locātīvus humī.'),
  _n('corinthus', 'Corinthus', 'Corinthī', _f, Declension.secunda, 'Corinth', 'Corinthe', number: NounNumber.singulareTantum, locative: true, prov: ['$_ag §48', '$_ag §427'], notes: 'Locātīvus Corinthī.'),
  _n('bellum', 'bellum', 'bellī', _nt, Declension.secunda, 'bell', 'guerre', prov: ['$_ag §48']),
  _n('templum', 'templum', 'templī', _nt, Declension.secunda, 'templ', 'temple', prov: ['$_ag §48']),
  _n('donum', 'dōnum', 'dōnī', _nt, Declension.secunda, 'dōn', 'don', prov: ['$_ag §48']),
  _n('verbum', 'verbum', 'verbī', _nt, Declension.secunda, 'verb', 'mot', prov: ['$_ag §48']),
  _n('oppidum', 'oppidum', 'oppidī', _nt, Declension.secunda, 'oppid', 'ville fortifiée', prov: ['$_ag §48']),
  _n('regnum', 'rēgnum', 'rēgnī', _nt, Declension.secunda, 'rēgn', 'royaume', prov: ['$_ag §48']),
  _n('periculum', 'perīculum', 'perīculī', _nt, Declension.secunda, 'perīcul', 'danger', prov: ['$_ag §48']),
  _n('consilium', 'cōnsilium', 'cōnsiliī', _nt, Declension.secunda, 'cōnsili', 'conseil, décision', prov: ['$_ag §49b'], notes: 'Genetīvus cōnsiliī (antīquius cōnsilī).'),
  _n('imperium', 'imperium', 'imperiī', _nt, Declension.secunda, 'imperi', 'pouvoir', prov: ['$_ag §49b']),
  _n('castra', 'castra', 'castrōrum', _nt, Declension.secunda, 'castr', 'camp', number: NounNumber.pluraleTantum, prov: ['$_ag §101'], notes: 'Plūrāle tantum: castra, castrōrum.'),
  _n('arma', 'arma', 'armōrum', _nt, Declension.secunda, 'arm', 'armes', number: NounNumber.pluraleTantum, prov: ['$_ag §101']),
  // ----- LLPSI Familia Rōmāna cap. 1–19 (secunda)
  _n('fluvius', 'fluvius', 'fluviī', _m, Declension.secunda, 'fluvi', 'fleuve, rivière', prov: ['$_ag §46', '$_ag §49b']),
  _n('libertus', 'lībertus', 'lībertī', _m, Declension.secunda, 'lībert', 'affranchi', prov: ['$_ag §46']),
  _n('nummus', 'nummus', 'nummī', _m, Declension.secunda, 'numm', 'pièce de monnaie', overrides: {'gen.pl': ['nummōrum', 'nummum']}, prov: ['$_ag §49d'], notes: 'Genetīvus plūrālis nummum in numerīs pecūniae.'),
  _n('saccus', 'saccus', 'saccī', _m, Declension.secunda, 'sacc', 'sac', prov: ['$_ag §46']),
  _n('sacculus', 'sacculus', 'sacculī', _m, Declension.secunda, 'saccul', 'bourse', prov: ['$_ag §46']),
  _n('nasus', 'nāsus', 'nāsī', _m, Declension.secunda, 'nās', 'nez', prov: ['$_ag §46']),
  _n('oculus', 'oculus', 'oculī', _m, Declension.secunda, 'ocul', 'œil', prov: ['$_ag §46']),
  _n('digitus', 'digitus', 'digitī', _m, Declension.secunda, 'digit', 'doigt', prov: ['$_ag §46']),
  _n('capillus', 'capillus', 'capillī', _m, Declension.secunda, 'capill', 'cheveu', prov: ['$_ag §46']),
  _n('lectus', 'lectus', 'lectī', _m, Declension.secunda, 'lect', 'lit', prov: ['$_ag §46']),
  _n('cibus', 'cibus', 'cibī', _m, Declension.secunda, 'cib', 'nourriture', prov: ['$_ag §46']),
  _n('campus', 'campus', 'campī', _m, Declension.secunda, 'camp', 'plaine, champ', prov: ['$_ag §46']),
  _n('lupus', 'lupus', 'lupī', _m, Declension.secunda, 'lup', 'loup', prov: ['$_ag §46']),
  _n('asinus', 'asinus', 'asinī', _m, Declension.secunda, 'asin', 'âne', prov: ['$_ag §46']),
  _n('porcus', 'porcus', 'porcī', _m, Declension.secunda, 'porc', 'porc', prov: ['$_ag §46']),
  _n('taurus', 'taurus', 'taurī', _m, Declension.secunda, 'taur', 'taureau', prov: ['$_ag §46']),
  _n('agnus', 'agnus', 'agnī', _m, Declension.secunda, 'agn', 'agneau', prov: ['$_ag §46']),
  _n('gallus', 'gallus', 'gallī', _m, Declension.secunda, 'gall', 'coq', prov: ['$_ag §46']),
  _n('umerus', 'umerus', 'umerī', _m, Declension.secunda, 'umer', 'épaule', prov: ['$_ag §46']),
  _n('gladius', 'gladius', 'gladiī', _m, Declension.secunda, 'gladi', 'épée', prov: ['$_ag §46', '$_ag §49b']),
  _n('numerus', 'numerus', 'numerī', _m, Declension.secunda, 'numer', 'nombre', prov: ['$_ag §46']),
  _n('discipulus', 'discipulus', 'discipulī', _m, Declension.secunda, 'discipul', 'élève', prov: ['$_ag §46']),
  _n('ludus', 'lūdus', 'lūdī', _m, Declension.secunda, 'lūd', 'jeu, école', prov: ['$_ag §46']),
  _n('annus', 'annus', 'annī', _m, Declension.secunda, 'ann', 'année', prov: ['$_ag §46']),
  _n('medicus', 'medicus', 'medicī', _m, Declension.secunda, 'medic', 'médecin', prov: ['$_ag §46']),
  _n('morbus', 'morbus', 'morbī', _m, Declension.secunda, 'morb', 'maladie', prov: ['$_ag §46']),
  _n('anulus', 'ānulus', 'ānulī', _m, Declension.secunda, 'ānul', 'anneau, bague', prov: ['$_ag §46']),
  _n('calceus', 'calceus', 'calceī', _m, Declension.secunda, 'calce', 'soulier', prov: ['$_ag §46']),
  _n('autumnus', 'autumnus', 'autumnī', _m, Declension.secunda, 'autumn', 'automne', prov: ['$_ag §46']),
  _n('rhenus', 'Rhēnus', 'Rhēnī', _m, Declension.secunda, 'Rhēn', 'Rhin', number: NounNumber.singulareTantum, prov: ['$_ag §46']),
  _n('nilus', 'Nīlus', 'Nīlī', _m, Declension.secunda, 'Nīl', 'Nil', number: NounNumber.singulareTantum, prov: ['$_ag §46']),
  _n('neptunus', 'Neptūnus', 'Neptūnī', _m, Declension.secunda, 'Neptūn', 'Neptune', number: NounNumber.singulareTantum, prov: ['$_ag §46']),
  _n('mercurius', 'Mercurius', 'Mercuriī', _m, Declension.secunda, 'Mercuri', 'Mercure', number: NounNumber.singulareTantum, prov: ['$_ag §49b'], notes: 'Vocātīvus Mercurī.'),
  _n('marcus', 'Mārcus', 'Mārcī', _m, Declension.secunda, 'Mārc', 'Marcus', number: NounNumber.singulareTantum, prov: ['$_ag §46']),
  _n('quintus_n', 'Quīntus', 'Quīntī', _m, Declension.secunda, 'Quīnt', 'Quintus', number: NounNumber.singulareTantum, prov: ['$_ag §46'], notes: 'Praenōmen; cf. quīntus adiectīvum.'),
  _n('sextus_n', 'Sextus', 'Sextī', _m, Declension.secunda, 'Sext', 'Sextus', number: NounNumber.singulareTantum, prov: ['$_ag §46'], notes: 'Praenōmen; cf. sextus adiectīvum.'),
  _n('titus', 'Titus', 'Titī', _m, Declension.secunda, 'Tit', 'Titus', number: NounNumber.singulareTantum, prov: ['$_ag §46']),
  _n('iulius', 'Iūlius', 'Iūliī', _m, Declension.secunda, 'Iūli', 'Julius', number: NounNumber.singulareTantum, prov: ['$_ag §49b'], notes: 'Vocātīvus Iūlī.'),
  _n('cornelius', 'Cornēlius', 'Cornēliī', _m, Declension.secunda, 'Cornēli', 'Cornelius', number: NounNumber.singulareTantum, prov: ['$_ag §49b'], notes: 'Vocātīvus Cornēlī.'),
  _n('aemilius', 'Aemilius', 'Aemiliī', _m, Declension.secunda, 'Aemili', 'Aemilius', number: NounNumber.singulareTantum, prov: ['$_ag §49b'], notes: 'Vocātīvus Aemilī.'),
  _n('tiberius', 'Tiberius', 'Tiberiī', _m, Declension.secunda, 'Tiberi', 'Tibère', number: NounNumber.singulareTantum, prov: ['$_ag §49b'], notes: 'Vocātīvus Tiberī.'),
  _n('davus', 'Dāvus', 'Dāvī', _m, Declension.secunda, 'Dāv', 'Davus', number: NounNumber.singulareTantum, prov: ['$_ag §46']),
  _n('medus', 'Mēdus', 'Mēdī', _m, Declension.secunda, 'Mēd', 'Médus', number: NounNumber.singulareTantum, prov: ['$_ag §46']),
  _n('diodorus', 'Diodōrus', 'Diodōrī', _m, Declension.secunda, 'Diodōr', 'Diodore', number: NounNumber.singulareTantum, prov: ['$_ag §46']),
  _n('malum', 'mālum', 'mālī', _nt, Declension.secunda, 'māl', 'pomme', prov: ['$_ag §48']),
  _n('pirum', 'pirum', 'pirī', _nt, Declension.secunda, 'pir', 'poire', prov: ['$_ag §48']),
  _n('ovum', 'ōvum', 'ōvī', _nt, Declension.secunda, 'ōv', 'œuf', prov: ['$_ag §48']),
  _n('vinum', 'vīnum', 'vīnī', _nt, Declension.secunda, 'vīn', 'vin', prov: ['$_ag §48']),
  _n('poculum', 'pōculum', 'pōculī', _nt, Declension.secunda, 'pōcul', 'coupe', prov: ['$_ag §48']),
  _n('speculum', 'speculum', 'speculī', _nt, Declension.secunda, 'specul', 'miroir', prov: ['$_ag §48']),
  _n('ostium', 'ōstium', 'ōstiī', _nt, Declension.secunda, 'ōsti', 'porte, entrée', prov: ['$_ag §49b']),
  _n('cubiculum', 'cubiculum', 'cubiculī', _nt, Declension.secunda, 'cubicul', 'chambre', prov: ['$_ag §48']),
  _n('atrium', 'ātrium', 'ātriī', _nt, Declension.secunda, 'ātri', 'atrium', prov: ['$_ag §49b']),
  _n('peristylum', 'peristȳlum', 'peristȳlī', _nt, Declension.secunda, 'peristȳl', 'péristyle', prov: ['$_ag §48']),
  _n('bracchium', 'bracchium', 'bracchiī', _nt, Declension.secunda, 'bracchi', 'bras', prov: ['$_ag §49b']),
  _n('membrum', 'membrum', 'membrī', _nt, Declension.secunda, 'membr', 'membre', prov: ['$_ag §48']),
  _n('baculum', 'baculum', 'baculī', _nt, Declension.secunda, 'bacul', 'bâton', prov: ['$_ag §48']),
  _n('scutum', 'scūtum', 'scūtī', _nt, Declension.secunda, 'scūt', 'bouclier', prov: ['$_ag §48']),
  _n('pilum', 'pīlum', 'pīlī', _nt, Declension.secunda, 'pīl', 'javelot', prov: ['$_ag §48']),
  _n('vocabulum', 'vocābulum', 'vocābulī', _nt, Declension.secunda, 'vocābul', 'mot, vocable', prov: ['$_ag §48']),
  _n('exemplum', 'exemplum', 'exemplī', _nt, Declension.secunda, 'exempl', 'exemple', prov: ['$_ag §48']),
  _n('capitulum', 'capitulum', 'capitulī', _nt, Declension.secunda, 'capitul', 'chapitre', prov: ['$_ag §48']),
  _n('tergum', 'tergum', 'tergī', _nt, Declension.secunda, 'terg', 'dos', prov: ['$_ag §48']),
  _n('caelum', 'caelum', 'caelī', _nt, Declension.secunda, 'cael', 'ciel', number: NounNumber.singulareTantum, prov: ['$_ag §48', '$_ag §106b'], notes: 'Plūrālis caelī masculīnus, rārus et poēticus: hīc omissus.'),
  _n('remedium', 'remedium', 'remediī', _nt, Declension.secunda, 'remedi', 'remède', prov: ['$_ag §49b']),
  _n('ornamentum', 'ōrnāmentum', 'ōrnāmentī', _nt, Declension.secunda, 'ōrnāment', 'parure, bijou', prov: ['$_ag §48']),
  _n('collum', 'collum', 'collī', _nt, Declension.secunda, 'coll', 'cou', prov: ['$_ag §48']),
  _n('pallium', 'pallium', 'palliī', _nt, Declension.secunda, 'palli', 'manteau', prov: ['$_ag §49b']),
  _n('forum', 'forum', 'forī', _nt, Declension.secunda, 'for', 'forum, place publique', prov: ['$_ag §48']),
  _n('theatrum', 'theātrum', 'theātrī', _nt, Declension.secunda, 'theātr', 'théâtre', prov: ['$_ag §48']),
  _n('latium', 'Latium', 'Latiī', _nt, Declension.secunda, 'Lati', 'Latium', number: NounNumber.singulareTantum, prov: ['$_ag §49b'], notes: 'Nōmen regiōnis: sine locātīvō ("in Latiō").'),
  _n('brundisium', 'Brundisium', 'Brundisiī', _nt, Declension.secunda, 'Brundisi', 'Brindes', number: NounNumber.singulareTantum, locative: true, prov: ['$_ag §49b', '$_ag §427'], notes: 'Locātīvus Brundisiī.'),
  _n('tusculum', 'Tūsculum', 'Tūsculī', _nt, Declension.secunda, 'Tūscul', 'Tusculum', number: NounNumber.singulareTantum, locative: true, prov: ['$_ag §48', '$_ag §427'], notes: 'Locātīvus Tūsculī.'),
  // ------------------------------------------------------------ tertia: themata cōnsonantia (A&G §56–64)
  _n('rex', 'rēx', 'rēgis', _m, Declension.tertia, 'rēg', 'roi', prov: ['$_ag §57']),
  _n('dux', 'dux', 'ducis', _m, Declension.tertia, 'duc', 'chef', prov: ['$_ag §57']),
  _n('lex', 'lēx', 'lēgis', _f, Declension.tertia, 'lēg', 'loi', prov: ['$_ag §57']),
  _n('vox', 'vōx', 'vōcis', _f, Declension.tertia, 'vōc', 'voix', prov: ['$_ag §57']),
  _n('pax', 'pāx', 'pācis', _f, Declension.tertia, 'pāc', 'paix', prov: ['$_ag §57']),
  _n('lux', 'lūx', 'lūcis', _f, Declension.tertia, 'lūc', 'lumière', prov: ['$_ag §57']),
  _n('iudex', 'iūdex', 'iūdicis', _m, Declension.tertia, 'iūdic', 'juge', prov: ['$_ag §57']),
  _n('consul', 'cōnsul', 'cōnsulis', _m, Declension.tertia, 'cōnsul', 'consul', prov: ['$_ag §62']),
  _n('miles', 'mīles', 'mīlitis', _m, Declension.tertia, 'mīlit', 'soldat', prov: ['$_ag §62']),
  _n('eques', 'eques', 'equitis', _m, Declension.tertia, 'equit', 'cavalier', prov: ['$_ag §62']),
  _n('princeps', 'prīnceps', 'prīncipis', _m, Declension.tertia, 'prīncip', 'premier, prince', prov: ['$_ag §62']),
  _n('homo', 'homō', 'hominis', _m, Declension.tertia, 'homin', 'être humain', prov: ['$_ag §62']),
  _n('orator', 'ōrātor', 'ōrātōris', _m, Declension.tertia, 'ōrātōr', 'orateur', prov: ['$_ag §62']),
  _n('senator', 'senātor', 'senātōris', _m, Declension.tertia, 'senātōr', 'sénateur', prov: ['$_ag §62']),
  _n('honor', 'honor', 'honōris', _m, Declension.tertia, 'honōr', 'honneur', prov: ['$_ag §62']),
  _n('amor', 'amor', 'amōris', _m, Declension.tertia, 'amōr', 'amour', prov: ['$_ag §62']),
  _n('labor', 'labor', 'labōris', _m, Declension.tertia, 'labōr', 'travail, peine', prov: ['$_ag §62']),
  _n('arbor', 'arbor', 'arboris', _f, Declension.tertia, 'arbor', 'arbre', prov: ['$_ag §62'], notes: 'Fēminīnum in -or.'),
  _n('soror', 'soror', 'sorōris', _f, Declension.tertia, 'sorōr', 'sœur', prov: ['$_ag §62']),
  _n('pater', 'pater', 'patris', _m, Declension.tertia, 'patr', 'père', prov: ['$_ag §62', '$_ag §71'], notes: 'Genetīvus plūrālis patrum (nōn -ium).'),
  _n('mater', 'māter', 'mātris', _f, Declension.tertia, 'mātr', 'mère', prov: ['$_ag §62', '$_ag §71']),
  _n('frater', 'frāter', 'frātris', _m, Declension.tertia, 'frātr', 'frère', prov: ['$_ag §62', '$_ag §71']),
  _n('legio', 'lēgiō', 'lēgiōnis', _f, Declension.tertia, 'lēgiōn', 'légion', prov: ['$_ag §62']),
  _n('oratio', 'ōrātiō', 'ōrātiōnis', _f, Declension.tertia, 'ōrātiōn', 'discours', prov: ['$_ag §62']),
  _n('civitas', 'cīvitās', 'cīvitātis', _f, Declension.tertia, 'cīvitāt', 'cité', overrides: {'gen.pl': ['cīvitātum', 'cīvitātium']}, prov: ['$_ag §62', '$_ag §71'], notes: 'Genetīvus plūrālis cīvitātum aut cīvitātium.'),
  _n('virtus', 'virtūs', 'virtūtis', _f, Declension.tertia, 'virtūt', 'courage, vertu', prov: ['$_ag §62']),
  _n('aetas', 'aetās', 'aetātis', _f, Declension.tertia, 'aetāt', 'âge', overrides: {'gen.pl': ['aetātum', 'aetātium']}, prov: ['$_ag §71']),
  _n('pes', 'pēs', 'pedis', _m, Declension.tertia, 'ped', 'pied', prov: ['$_ag §62']),
  _n('lapis', 'lapis', 'lapidis', _m, Declension.tertia, 'lapid', 'pierre', prov: ['$_ag §62']),
  _n('sacerdos', 'sacerdōs', 'sacerdōtis', _m, Declension.tertia, 'sacerdōt', 'prêtre', prov: ['$_ag §62'], notes: 'Genus commūne (m. et f.).'),
  _n('canis', 'canis', 'canis', _m, Declension.tertia, 'can', 'chien', prov: ['$_ag §71'], notes: 'Thema cōnsonāns quamquam parisyllabum: canum.'),
  _n('iuvenis', 'iuvenis', 'iuvenis', _m, Declension.tertia, 'iuven', 'jeune homme', prov: ['$_ag §71'], notes: 'Genetīvus plūrālis iuvenum.'),
  _n('senex', 'senex', 'senis', _m, Declension.tertia, 'sen', 'vieillard', prov: ['$_ag §79'], notes: 'Thema sen-: senis, senem, senum.'),
  _n('bos', 'bōs', 'bovis', _m, Declension.tertia, 'bov', 'bœuf', overrides: {'gen.pl': ['boum'], 'dat.pl': ['bōbus', 'būbus'], 'abl.pl': ['bōbus', 'būbus']}, prov: ['$_ag §79'], notes: 'Genus commūne; plūrālis bovēs, boum, bōbus (būbus).'),
  _n('iuppiter', 'Iuppiter', 'Iovis', _m, Declension.tertia, 'Iov', 'Jupiter', number: NounNumber.singulareTantum, prov: ['$_ag §79'], notes: 'Nōminātīvus et vocātīvus Iuppiter, cēterī cāsūs ā themate Iov-.'),
  _n('carthago', 'Carthāgō', 'Carthāginis', _f, Declension.tertia, 'Carthāgin', 'Carthage', number: NounNumber.singulareTantum, locative: true, prov: ['$_ag §427'], notes: 'Locātīvus Carthāginī aut Carthāgine.'),
  _n('rus', 'rūs', 'rūris', _nt, Declension.tertia, 'rūr', 'campagne', number: NounNumber.singulareTantum, locative: true, prov: ['$_ag §427'], notes: 'Locātīvus rūrī (rūre). Plūrālis rūra rārus, hīc omissus.'),
  _n('corpus', 'corpus', 'corporis', _nt, Declension.tertia, 'corpor', 'corps', prov: ['$_ag §64']),
  _n('tempus', 'tempus', 'temporis', _nt, Declension.tertia, 'tempor', 'temps', prov: ['$_ag §64']),
  _n('genus', 'genus', 'generis', _nt, Declension.tertia, 'gener', 'genre, race', prov: ['$_ag §64']),
  _n('opus', 'opus', 'operis', _nt, Declension.tertia, 'oper', 'ouvrage', prov: ['$_ag §64']),
  _n('nomen', 'nōmen', 'nōminis', _nt, Declension.tertia, 'nōmin', 'nom', prov: ['$_ag §64']),
  _n('flumen', 'flūmen', 'flūminis', _nt, Declension.tertia, 'flūmin', 'fleuve', prov: ['$_ag §64']),
  _n('carmen', 'carmen', 'carminis', _nt, Declension.tertia, 'carmin', 'poème, chant', prov: ['$_ag §64']),
  _n('caput', 'caput', 'capitis', _nt, Declension.tertia, 'capit', 'tête', prov: ['$_ag §64']),
  _n('iter', 'iter', 'itineris', _nt, Declension.tertia, 'itiner', 'chemin, marche', prov: ['$_ag §79'], notes: 'Thema itiner-.'),
  _n('litus', 'lītus', 'lītoris', _nt, Declension.tertia, 'lītor', 'rivage', prov: ['$_ag §64']),
  _n('vulnus', 'vulnus', 'vulneris', _nt, Declension.tertia, 'vulner', 'blessure', prov: ['$_ag §64']),
  _n('pectus', 'pectus', 'pectoris', _nt, Declension.tertia, 'pector', 'poitrine', prov: ['$_ag §64']),
  _n('os', 'os', 'ossis', _nt, Declension.tertia, 'oss', 'os', overrides: {'gen.pl': ['ossium']}, prov: ['$_ag §71'], notes: 'Genetīvus plūrālis ossium.'),
  // ----- LLPSI Familia Rōmāna cap. 1–19 (tertia, themata cōnsonantia)
  _n('pastor', 'pāstor', 'pāstōris', _m, Declension.tertia, 'pāstōr', 'berger', prov: ['$_ag §62']),
  _n('imperator', 'imperātor', 'imperātōris', _m, Declension.tertia, 'imperātōr', 'général, empereur', prov: ['$_ag §62']),
  _n('mercator', 'mercātor', 'mercātōris', _m, Declension.tertia, 'mercātōr', 'marchand', prov: ['$_ag §62']),
  _n('victor', 'victor', 'victōris', _m, Declension.tertia, 'victōr', 'vainqueur', prov: ['$_ag §62']),
  _n('uxor', 'uxor', 'uxōris', _f, Declension.tertia, 'uxōr', 'épouse', prov: ['$_ag §62'], notes: 'Fēminīnum in -or.'),
  _n('mulier', 'mulier', 'mulieris', _f, Declension.tertia, 'mulier', 'femme', prov: ['$_ag §62']),
  _n('leo', 'leō', 'leōnis', _m, Declension.tertia, 'leōn', 'lion', prov: ['$_ag §62']),
  _n('flos', 'flōs', 'flōris', _m, Declension.tertia, 'flōr', 'fleur', prov: ['$_ag §62']),
  _n('sol', 'sōl', 'sōlis', _m, Declension.tertia, 'sōl', 'soleil', number: NounNumber.singulareTantum, prov: ['$_ag §62', '$_ag §103'], notes: 'Plūrālis sōlēs "diēs" poēticē: hīc omissus.'),
  _n('sal', 'sāl', 'salis', _m, Declension.tertia, 'sal', 'sel; pl. bons mots', prov: ['$_ag §62'], notes: 'Masculīnum (etiam neutrum in singulārī); vōcālis brevis in cāsibus oblīquīs.'),
  _n('sanguis', 'sanguis', 'sanguinis', _m, Declension.tertia, 'sanguin', 'sang', number: NounNumber.singulareTantum, prov: ['$_ag §62', '$_ag §103'], notes: 'Plūrālis rārissimus: hīc omissus.'),
  _n('hiems', 'hiems', 'hiemis', _f, Declension.tertia, 'hiem', 'hiver', prov: ['$_ag §62'], notes: 'Thema cōnsonāns: hiemum (nōn -ium).'),
  _n('aestas', 'aestās', 'aestātis', _f, Declension.tertia, 'aestāt', 'été', prov: ['$_ag §62']),
  _n('tempestas', 'tempestās', 'tempestātis', _f, Declension.tertia, 'tempestāt', 'tempête, temps (météo)', overrides: {'gen.pl': ['tempestātum', 'tempestātium']}, prov: ['$_ag §62', '$_ag §71']),
  _n('potestas', 'potestās', 'potestātis', _f, Declension.tertia, 'potestāt', 'pouvoir', prov: ['$_ag §62']),
  _n('voluntas', 'voluntās', 'voluntātis', _f, Declension.tertia, 'voluntāt', 'volonté', prov: ['$_ag §62']),
  _n('libertas', 'lībertās', 'lībertātis', _f, Declension.tertia, 'lībertāt', 'liberté', prov: ['$_ag §62']),
  _n('pietas', 'pietās', 'pietātis', _f, Declension.tertia, 'pietāt', 'piété', prov: ['$_ag §62']),
  _n('difficultas', 'difficultās', 'difficultātis', _f, Declension.tertia, 'difficultāt', 'difficulté', prov: ['$_ag §62']),
  _n('parens', 'parēns', 'parentis', _m, Declension.tertia, 'parent', 'parent (père ou mère)', overrides: {'gen.pl': ['parentum', 'parentium']}, prov: ['$_ag §62', '$_ag §121a'], notes: 'Genus commūne; genetīvus plūrālis parentum, rārius parentium.'),
  _n('venus', 'Venus', 'Veneris', _f, Declension.tertia, 'Vener', 'Vénus', number: NounNumber.singulareTantum, prov: ['$_ag §62'], notes: 'Fēminīnum in -us: Venus, Veneris.'),
  _n('ceres', 'Cerēs', 'Cereris', _f, Declension.tertia, 'Cerer', 'Cérès', number: NounNumber.singulareTantum, prov: ['$_ag §62']),
  _n('iuno', 'Iūnō', 'Iūnōnis', _f, Declension.tertia, 'Iūnōn', 'Junon', number: NounNumber.singulareTantum, prov: ['$_ag §62']),
  _n('mars', 'Mārs', 'Mārtis', _m, Declension.tertia, 'Mārt', 'Mars', number: NounNumber.singulareTantum, prov: ['$_ag §62']),
  _n('apollo', 'Apollō', 'Apollinis', _m, Declension.tertia, 'Apollin', 'Apollon', number: NounNumber.singulareTantum, prov: ['$_ag §62'], notes: 'Thema Apollin-.'),
  _n('os_oris', 'ōs', 'ōris', _nt, Declension.tertia, 'ōr', 'bouche, visage', absent: [AbsentForm('gen.pl', AbsenceStatus.nonUsitatur, note: 'genetīvus plūrālis ōrum nōn ūsitātur')], prov: ['$_ag §64', '$_ag §103'], notes: 'Ōs, ōris (bouche) ≠ os, ossis (os); plūrālis ōra, ōribus.'),
  _n('cor', 'cor', 'cordis', _nt, Declension.tertia, 'cord', 'cœur', overrides: {'gen.pl': ['cordium']}, prov: ['$_ag §64', '$_ag §71'], notes: 'Genetīvus plūrālis cordium (rārus).'),
  _n('lac', 'lac', 'lactis', _nt, Declension.tertia, 'lact', 'lait', number: NounNumber.singulareTantum, prov: ['$_ag §64', '$_ag §103']),
  _n('mel', 'mel', 'mellis', _nt, Declension.tertia, 'mell', 'miel', prov: ['$_ag §64'], notes: 'Plūrālis mella poēticus.'),
  _n('ver', 'vēr', 'vēris', _nt, Declension.tertia, 'vēr', 'printemps', number: NounNumber.singulareTantum, prov: ['$_ag §64', '$_ag §103']),
  _n('crus', 'crūs', 'crūris', _nt, Declension.tertia, 'crūr', 'jambe', prov: ['$_ag §64']),
  _n('latus_n', 'latus', 'lateris', _nt, Declension.tertia, 'later', 'côté, flanc', prov: ['$_ag §64'], notes: 'Substantīvum; cf. lātus adiectīvum.'),
  _n('munus', 'mūnus', 'mūneris', _nt, Declension.tertia, 'mūner', 'devoir, cadeau', prov: ['$_ag §64']),
  _n('onus', 'onus', 'oneris', _nt, Declension.tertia, 'oner', 'fardeau', prov: ['$_ag §64']),
  _n('sidus', 'sīdus', 'sīderis', _nt, Declension.tertia, 'sīder', 'astre, constellation', prov: ['$_ag §64']),
  _n('lumen', 'lūmen', 'lūminis', _nt, Declension.tertia, 'lūmin', 'lumière, lampe', prov: ['$_ag §64']),
  _n('agmen', 'agmen', 'agminis', _nt, Declension.tertia, 'agmin', 'armée en marche, colonne', prov: ['$_ag §64']),
  // ------------------------------------------------------------ tertia: themata in -i (A&G §65–71, §75–76)
  _n('civis', 'cīvis', 'cīvis', _m, Declension.tertia, 'cīv', 'citoyen', third: ThirdStem.vocalisI, prov: ['$_ag §66'], notes: 'Genus commūne; genetīvus plūrālis cīvium.'),
  _n('hostis', 'hostis', 'hostis', _m, Declension.tertia, 'host', 'ennemi', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('navis', 'nāvis', 'nāvis', _f, Declension.tertia, 'nāv', 'navire', third: ThirdStem.vocalisI, overrides: {'acc.sg': ['nāvem', 'nāvim'], 'abl.sg': ['nāve', 'nāvī']}, prov: ['$_ag §75', '$_ag §76'], notes: 'Accūsātīvus nāvem (nāvim), ablātīvus nāve (nāvī).'),
  _n('turris', 'turris', 'turris', _f, Declension.tertia, 'turr', 'tour', third: ThirdStem.vocalisI, overrides: {'acc.sg': ['turrim', 'turrem'], 'abl.sg': ['turrī', 'turre']}, prov: ['$_ag §75', '$_ag §76'], notes: 'Accūsātīvus turrim (turrem), ablātīvus turrī (turre).'),
  _n('ignis', 'ignis', 'ignis', _m, Declension.tertia, 'ign', 'feu', third: ThirdStem.vocalisI, overrides: {'abl.sg': ['ignī', 'igne']}, prov: ['$_ag §76'], notes: 'Ablātīvus ignī aut igne.'),
  _n('collis', 'collis', 'collis', _m, Declension.tertia, 'coll', 'colline', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('finis', 'fīnis', 'fīnis', _m, Declension.tertia, 'fīn', 'limite, fin', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('avis', 'avis', 'avis', _f, Declension.tertia, 'av', 'oiseau', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('nubes', 'nūbēs', 'nūbis', _f, Declension.tertia, 'nūb', 'nuage', third: ThirdStem.vocalisI, prov: ['$_ag §66'], notes: 'Parisyllabum in -ēs: nūbium.'),
  _n('caedes', 'caedēs', 'caedis', _f, Declension.tertia, 'caed', 'massacre', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('urbs', 'urbs', 'urbis', _f, Declension.tertia, 'urb', 'ville', third: ThirdStem.vocalisI, prov: ['$_ag §66'], notes: 'Monosyllabum: urbium.'),
  _n('arx', 'arx', 'arcis', _f, Declension.tertia, 'arc', 'citadelle', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('mons', 'mōns', 'montis', _m, Declension.tertia, 'mont', 'montagne', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('pons', 'pōns', 'pontis', _m, Declension.tertia, 'pont', 'pont', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('gens', 'gēns', 'gentis', _f, Declension.tertia, 'gent', 'peuple, famille', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('mens', 'mēns', 'mentis', _f, Declension.tertia, 'ment', 'esprit', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('mors', 'mors', 'mortis', _f, Declension.tertia, 'mort', 'mort', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('ars', 'ars', 'artis', _f, Declension.tertia, 'art', 'art', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('pars', 'pars', 'partis', _f, Declension.tertia, 'part', 'partie', third: ThirdStem.vocalisI, prov: ['$_ag §66'], notes: 'Accūsātīvus plūrālis partēs aut partīs.'),
  _n('dens', 'dēns', 'dentis', _m, Declension.tertia, 'dent', 'dent', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('nox', 'nox', 'noctis', _f, Declension.tertia, 'noct', 'nuit', third: ThirdStem.vocalisI, prov: ['$_ag §66'], notes: 'Genetīvus plūrālis noctium.'),
  _n('vis', 'vīs', 'vīs', _f, Declension.tertia, 'v', 'force', third: ThirdStem.vocalisIPura,
      overrides: {
        'gen.sg': ['vīs'],
        'nom.pl': ['vīrēs'],
        'voc.pl': ['vīrēs'],
        'gen.pl': ['vīrium'],
        'dat.pl': ['vīribus'],
        'abl.pl': ['vīribus'],
        'acc.pl': ['vīrēs', 'vīrīs'],
      },
      prov: ['$_ag §79'],
      notes: 'Singulāris vīs, vīs, vī, vim, vī (genetīvus et datīvus rārī); plūrālis ā themate vīr-.'),
  _n('mare', 'mare', 'maris', _nt, Declension.tertia, 'mar', 'mer', third: ThirdStem.neutrumI, prov: ['$_ag §68'], notes: 'Ablātīvus marī; plūrālis maria, marium (rārum).'),
  _n('animal', 'animal', 'animālis', _nt, Declension.tertia, 'animāl', 'animal', third: ThirdStem.neutrumI, prov: ['$_ag §68']),
  _n('exemplar', 'exemplar', 'exemplāris', _nt, Declension.tertia, 'exemplār', 'modèle', third: ThirdStem.neutrumI, prov: ['$_ag §68']),
  _n('moenia', 'moenia', 'moenium', _nt, Declension.tertia, 'moen', 'remparts', third: ThirdStem.neutrumI, number: NounNumber.pluraleTantum, prov: ['$_ag §101'], notes: 'Plūrāle tantum: moenia, moenium, moenibus.'),
  // ----- LLPSI Familia Rōmāna cap. 1–19 (tertia, themata in -i)
  _n('ovis', 'ovis', 'ovis', _f, Declension.tertia, 'ov', 'brebis', third: ThirdStem.vocalisI, prov: ['$_ag §66'], notes: 'Genetīvus plūrālis ovium.'),
  _n('mensis', 'mēnsis', 'mēnsis', _m, Declension.tertia, 'mēns', 'mois', third: ThirdStem.vocalisI, overrides: {'gen.pl': ['mēnsium', 'mēnsum']}, prov: ['$_ag §66', '$_ag §71'], notes: 'Genetīvus plūrālis mēnsium aut mēnsum.'),
  _n('panis', 'pānis', 'pānis', _m, Declension.tertia, 'pān', 'pain', third: ThirdStem.vocalisI, overrides: {'gen.pl': ['pānium', 'pānum']}, prov: ['$_ag §66'], notes: 'Genetīvus plūrālis pānium (Caesar) aut pānum.'),
  _n('piscis', 'piscis', 'piscis', _m, Declension.tertia, 'pisc', 'poisson', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('auris', 'auris', 'auris', _f, Declension.tertia, 'aur', 'oreille', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('vestis', 'vestis', 'vestis', _f, Declension.tertia, 'vest', 'vêtement', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('vallis', 'vallis', 'vallis', _f, Declension.tertia, 'vall', 'vallée', third: ThirdStem.vocalisI, prov: ['$_ag §66']),
  _n('frons', 'frōns', 'frontis', _f, Declension.tertia, 'front', 'front', third: ThirdStem.vocalisI, prov: ['$_ag §66'], notes: 'Monosyllabum: frontium.'),
  _n('infans', 'īnfāns', 'īnfantis', _m, Declension.tertia, 'īnfant', 'petit enfant', third: ThirdStem.vocalisI, prov: ['$_ag §66', '$_ag §121a'], notes: 'Genus commūne; genetīvus plūrālis īnfantium.'),
  _n('adulescens', 'adulēscēns', 'adulēscentis', _m, Declension.tertia, 'adulēscent', 'jeune homme', third: ThirdStem.vocalisI, overrides: {'gen.pl': ['adulēscentium', 'adulēscentum']}, prov: ['$_ag §66', '$_ag §121a'], notes: 'Genus commūne; genetīvus plūrālis adulēscentium (adulēscentum).'),
  _n('tiberis', 'Tiberis', 'Tiberis', _m, Declension.tertia, 'Tiber', 'Tibre', third: ThirdStem.vocalisIPura, number: NounNumber.singulareTantum, prov: ['$_ag §75a'], notes: 'Accūsātīvus Tiberim, ablātīvus Tiberī.'),
  // ------------------------------------------------------------ quārta (A&G §89–94)
  _n('manus', 'manus', 'manūs', _f, Declension.quarta, 'man', 'main', prov: ['$_ag §90'], notes: 'Fēminīnum quārtae dēclīnātiōnis.'),
  _n('exercitus', 'exercitus', 'exercitūs', _m, Declension.quarta, 'exercit', 'armée', prov: ['$_ag §90']),
  _n('senatus', 'senātus', 'senātūs', _m, Declension.quarta, 'senāt', 'sénat', overrides: {'gen.sg': ['senātūs', 'senātī']}, prov: ['$_ag §92a'], notes: 'Genetīvus senātūs (etiam senātī).'),
  _n('fructus', 'frūctus', 'frūctūs', _m, Declension.quarta, 'frūct', 'fruit', prov: ['$_ag §90']),
  _n('casus', 'cāsus', 'cāsūs', _m, Declension.quarta, 'cās', 'chute, hasard, cas', prov: ['$_ag §90']),
  _n('portus', 'portus', 'portūs', _m, Declension.quarta, 'port', 'port', overrides: {'dat.pl': ['portibus', 'portubus'], 'abl.pl': ['portibus', 'portubus']}, prov: ['$_ag §92c']),
  _n('tribus', 'tribus', 'tribūs', _f, Declension.quarta, 'trib', 'tribu', overrides: {'dat.pl': ['tribubus'], 'abl.pl': ['tribubus']}, prov: ['$_ag §92c'], notes: 'Datīvus et ablātīvus plūrālis tribubus.'),
  _n('lacus', 'lacus', 'lacūs', _m, Declension.quarta, 'lac', 'lac', overrides: {'dat.pl': ['lacubus'], 'abl.pl': ['lacubus']}, prov: ['$_ag §92c']),
  _n('domus', 'domus', 'domūs', _f, Declension.quarta, 'dom', 'maison', locative: true,
      overrides: {
        'dat.sg': ['domuī', 'domō'],
        'abl.sg': ['domō', 'domū'],
        'gen.pl': ['domuum', 'domōrum'],
        'acc.pl': ['domōs', 'domūs'],
        'loc.sg': ['domī'],
      },
      prov: ['$_ag §93', '$_ag §427'],
      notes: 'Fōrmae secundae et quārtae mixtae; locātīvus domī.'),
  _n('cornu', 'cornū', 'cornūs', _nt, Declension.quarta, 'corn', 'corne, aile (d’armée)', prov: ['$_ag §89']),
  _n('genu', 'genū', 'genūs', _nt, Declension.quarta, 'gen', 'genou', prov: ['$_ag §89']),
  // ----- LLPSI Familia Rōmāna cap. 1–19 (quārta)
  _n('arcus', 'arcus', 'arcūs', _m, Declension.quarta, 'arc', 'arc', overrides: {'dat.pl': ['arcubus'], 'abl.pl': ['arcubus']}, prov: ['$_ag §92c'], notes: 'Datīvus et ablātīvus plūrālis arcubus.'),
  _n('fluctus', 'flūctus', 'flūctūs', _m, Declension.quarta, 'flūct', 'vague, flot', prov: ['$_ag §90']),
  _n('versus', 'versus', 'versūs', _m, Declension.quarta, 'vers', 'vers, ligne', prov: ['$_ag §90']),
  _n('currus', 'currus', 'currūs', _m, Declension.quarta, 'curr', 'char', prov: ['$_ag §90']),
  _n('impetus', 'impetus', 'impetūs', _m, Declension.quarta, 'impet', 'élan, attaque', prov: ['$_ag §90']),
  _n('exitus', 'exitus', 'exitūs', _m, Declension.quarta, 'exit', 'sortie, issue', prov: ['$_ag §90']),
  _n('metus', 'metus', 'metūs', _m, Declension.quarta, 'met', 'crainte', prov: ['$_ag §90']),
  _n('gradus', 'gradus', 'gradūs', _m, Declension.quarta, 'grad', 'pas, degré', prov: ['$_ag §90']),
  _n('vultus', 'vultus', 'vultūs', _m, Declension.quarta, 'vult', 'visage, expression', prov: ['$_ag §90']),
  _n('spiritus', 'spīritus', 'spīritūs', _m, Declension.quarta, 'spīrit', 'souffle, esprit', prov: ['$_ag §90']),
  _n('motus', 'mōtus', 'mōtūs', _m, Declension.quarta, 'mōt', 'mouvement', prov: ['$_ag §90']),
  _n('sensus', 'sēnsus', 'sēnsūs', _m, Declension.quarta, 'sēns', 'sens, sensation', prov: ['$_ag §90']),
  _n('usus', 'ūsus', 'ūsūs', _m, Declension.quarta, 'ūs', 'usage', prov: ['$_ag §90']),
  _n('quercus', 'quercus', 'quercūs', _f, Declension.quarta, 'querc', 'chêne', prov: ['$_ag §90'], notes: 'Fēminīnum quārtae dēclīnātiōnis (nōmen arboris).'),
  _n('idus', 'Īdūs', 'Īduum', _f, Declension.quarta, 'Īd', 'ides', number: NounNumber.pluraleTantum, prov: ['$_ag §90', '$_ag §101'], notes: 'Plūrāle tantum: Īdūs, Īduum, Īdibus.'),
  // ------------------------------------------------------------ quīnta (A&G §96–98)
  _n('res', 'rēs', 'reī', _f, Declension.quinta, 'r', 'chose, affaire', prov: ['$_ag §97'], notes: 'ē brevis in reī post cōnsonantem.'),
  _n('dies', 'diēs', 'diēī', _m, Declension.quinta, 'di', 'jour', prov: ['$_ag §97'], notes: 'Masculīnum (fēminīnum dē diē cōnstitūtā); ē longa in diēī post vōcālem.'),
  _n('spes', 'spēs', 'speī', _f, Declension.quinta, 'sp', 'espoir', absent: [AbsentForm('gen.pl', AbsenceStatus.nonUsitatur, note: 'plūrālis nōminātīvō et accūsātīvō tantum'), AbsentForm('dat.pl', AbsenceStatus.nonUsitatur), AbsentForm('abl.pl', AbsenceStatus.nonUsitatur)], prov: ['$_ag §98b']),
  _n('fides', 'fidēs', 'fideī', _f, Declension.quinta, 'fid', 'confiance, loyauté', number: NounNumber.singulareTantum, prov: ['$_ag §98b']),
  _n('acies', 'aciēs', 'aciēī', _f, Declension.quinta, 'aci', 'ligne de bataille', absent: [AbsentForm('gen.pl', AbsenceStatus.nonUsitatur), AbsentForm('dat.pl', AbsenceStatus.nonUsitatur), AbsentForm('abl.pl', AbsenceStatus.nonUsitatur)], prov: ['$_ag §98b']),
  _n('meridies', 'merīdiēs', 'merīdiēī', _m, Declension.quinta, 'merīdi', 'midi', number: NounNumber.singulareTantum, prov: ['$_ag §96']),
  // ----- LLPSI Familia Rōmāna cap. 1–19 (quīnta)
  _n('facies', 'faciēs', 'faciēī', _f, Declension.quinta, 'faci', 'visage, aspect', absent: [AbsentForm('gen.pl', AbsenceStatus.nonUsitatur), AbsentForm('dat.pl', AbsenceStatus.nonUsitatur), AbsentForm('abl.pl', AbsenceStatus.nonUsitatur)], prov: ['$_ag §98a']),
  _n('species', 'speciēs', 'speciēī', _f, Declension.quinta, 'speci', 'apparence, espèce', absent: [AbsentForm('gen.pl', AbsenceStatus.nonUsitatur, note: 'speciērum, speciēbus tantum apud scrīptōrēs posteriōrēs'), AbsentForm('dat.pl', AbsenceStatus.nonUsitatur), AbsentForm('abl.pl', AbsenceStatus.nonUsitatur)], prov: ['$_ag §98a']),
]);
