/// Cardinal numerals (A&G §132–§135). Ūnus and the ordinals are adjectives
/// and live in `adjectives.dart`.
library;

import '../model/numeral.dart';

const _ag = 'A&G';

/// Plural cells of a hundred (ducentī, -ae, -a): bonus-type plural.
Map<String, List<String>> _hundreds(String stem) => {
      'nom.pl.m': ['${stem}ī'],
      'voc.pl.m': ['${stem}ī'],
      'acc.pl.m': ['${stem}ōs'],
      'gen.pl.m': ['${stem}ōrum'],
      'dat.pl.m': ['${stem}īs'],
      'abl.pl.m': ['${stem}īs'],
      'nom.pl.f': ['${stem}ae'],
      'voc.pl.f': ['${stem}ae'],
      'acc.pl.f': ['${stem}ās'],
      'gen.pl.f': ['${stem}ārum'],
      'dat.pl.f': ['${stem}īs'],
      'abl.pl.f': ['${stem}īs'],
      'nom.pl.n': ['${stem}a'],
      'voc.pl.n': ['${stem}a'],
      'acc.pl.n': ['${stem}a'],
      'gen.pl.n': ['${stem}ōrum'],
      'dat.pl.n': ['${stem}īs'],
      'abl.pl.n': ['${stem}īs'],
    };

NumeralEntry _indecl(String id, String lemma, int value, String gloss) => NumeralEntry(id: id, lemma: lemma, entry: '$lemma (indēcl.)', value: value, glossFr: gloss, hasGender: false, provenance: const ['$_ag §134']);

final List<NumeralEntry> kNumerals = List.unmodifiable([
  NumeralEntry(
    id: 'duo',
    lemma: 'duo',
    entry: 'duo, duae, duo',
    value: 2,
    glossFr: 'deux',
    cells: const {
      'nom.pl.m': ['duo'],
      'voc.pl.m': ['duo'],
      'acc.pl.m': ['duōs', 'duo'],
      'gen.pl.m': ['duōrum'],
      'dat.pl.m': ['duōbus'],
      'abl.pl.m': ['duōbus'],
      'nom.pl.f': ['duae'],
      'voc.pl.f': ['duae'],
      'acc.pl.f': ['duās'],
      'gen.pl.f': ['duārum'],
      'dat.pl.f': ['duābus'],
      'abl.pl.f': ['duābus'],
      'nom.pl.n': ['duo'],
      'voc.pl.n': ['duo'],
      'acc.pl.n': ['duo'],
      'gen.pl.n': ['duōrum'],
      'dat.pl.n': ['duōbus'],
      'abl.pl.n': ['duōbus'],
    },
    provenance: const ['$_ag §134'],
    notes: 'Reliquiae duālis: duōbus, duābus. Ambō (ambae, ambō) eōdem modō dēclīnātur.',
  ),
  NumeralEntry(
    id: 'ambo',
    lemma: 'ambō',
    entry: 'ambō, ambae, ambō',
    value: 2,
    glossFr: 'tous deux, les deux ensemble',
    cells: const {
      'nom.pl.m': ['ambō'],
      'voc.pl.m': ['ambō'],
      'acc.pl.m': ['ambōs', 'ambō'],
      'gen.pl.m': ['ambōrum'],
      'dat.pl.m': ['ambōbus'],
      'abl.pl.m': ['ambōbus'],
      'nom.pl.f': ['ambae'],
      'voc.pl.f': ['ambae'],
      'acc.pl.f': ['ambās'],
      'gen.pl.f': ['ambārum'],
      'dat.pl.f': ['ambābus'],
      'abl.pl.f': ['ambābus'],
      'nom.pl.n': ['ambō'],
      'voc.pl.n': ['ambō'],
      'acc.pl.n': ['ambō'],
      'gen.pl.n': ['ambōrum'],
      'dat.pl.n': ['ambōbus'],
      'abl.pl.n': ['ambōbus'],
    },
    provenance: const ['$_ag §134'],
  ),
  NumeralEntry(
    id: 'tres',
    lemma: 'trēs',
    entry: 'trēs, tria',
    value: 3,
    glossFr: 'trois',
    cells: const {
      'nom.pl.m': ['trēs'],
      'voc.pl.m': ['trēs'],
      'acc.pl.m': ['trēs', 'trīs'],
      'gen.pl.m': ['trium'],
      'dat.pl.m': ['tribus'],
      'abl.pl.m': ['tribus'],
      'nom.pl.f': ['trēs'],
      'voc.pl.f': ['trēs'],
      'acc.pl.f': ['trēs', 'trīs'],
      'gen.pl.f': ['trium'],
      'dat.pl.f': ['tribus'],
      'abl.pl.f': ['tribus'],
      'nom.pl.n': ['tria'],
      'voc.pl.n': ['tria'],
      'acc.pl.n': ['tria'],
      'gen.pl.n': ['trium'],
      'dat.pl.n': ['tribus'],
      'abl.pl.n': ['tribus'],
    },
    provenance: const ['$_ag §134'],
    notes: 'Ut adiectīvum tertiae classis in plūrālī (thema in -i): trium, tribus, tria.',
  ),
  _indecl('quattuor', 'quattuor', 4, 'quatre'),
  _indecl('quinque', 'quīnque', 5, 'cinq'),
  _indecl('sex', 'sex', 6, 'six'),
  _indecl('septem', 'septem', 7, 'sept'),
  _indecl('octo', 'octō', 8, 'huit'),
  _indecl('novem', 'novem', 9, 'neuf'),
  _indecl('decem', 'decem', 10, 'dix'),
  _indecl('undecim', 'ūndecim', 11, 'onze'),
  _indecl('duodecim', 'duodecim', 12, 'douze'),
  _indecl('tredecim', 'tredecim', 13, 'treize'),
  _indecl('quattuordecim', 'quattuordecim', 14, 'quatorze'),
  _indecl('quindecim', 'quīndecim', 15, 'quinze'),
  _indecl('sedecim', 'sēdecim', 16, 'seize'),
  _indecl('septendecim', 'septendecim', 17, 'dix-sept'),
  _indecl('duodeviginti', 'duodēvīgintī', 18, 'dix-huit'),
  _indecl('undeviginti', 'ūndēvīgintī', 19, 'dix-neuf'),
  _indecl('viginti', 'vīgintī', 20, 'vingt'),
  _indecl('triginta', 'trīgintā', 30, 'trente'),
  _indecl('quadraginta', 'quadrāgintā', 40, 'quarante'),
  _indecl('quinquaginta', 'quīnquāgintā', 50, 'cinquante'),
  _indecl('sexaginta', 'sexāgintā', 60, 'soixante'),
  _indecl('septuaginta', 'septuāgintā', 70, 'soixante-dix'),
  _indecl('octoginta', 'octōgintā', 80, 'quatre-vingts'),
  _indecl('nonaginta', 'nōnāgintā', 90, 'quatre-vingt-dix'),
  _indecl('centum', 'centum', 100, 'cent'),
  NumeralEntry(id: 'ducenti', lemma: 'ducentī', entry: 'ducentī, -ae, -a', value: 200, glossFr: 'deux cents', cells: _hundreds('ducent'), provenance: const ['$_ag §134'], notes: 'Centēna ut adiectīva plūrālia dēclīnantur.'),
  NumeralEntry(id: 'trecenti', lemma: 'trecentī', entry: 'trecentī, -ae, -a', value: 300, glossFr: 'trois cents', cells: _hundreds('trecent'), provenance: const ['$_ag §134']),
  NumeralEntry(id: 'quadringenti', lemma: 'quadringentī', entry: 'quadringentī, -ae, -a', value: 400, glossFr: 'quatre cents', cells: _hundreds('quadringent'), provenance: const ['$_ag §134']),
  NumeralEntry(id: 'quingenti', lemma: 'quīngentī', entry: 'quīngentī, -ae, -a', value: 500, glossFr: 'cinq cents', cells: _hundreds('quīngent'), provenance: const ['$_ag §134']),
  NumeralEntry(id: 'sescenti', lemma: 'sescentī', entry: 'sescentī, -ae, -a', value: 600, glossFr: 'six cents', cells: _hundreds('sescent'), provenance: const ['$_ag §134']),
  NumeralEntry(id: 'septingenti', lemma: 'septingentī', entry: 'septingentī, -ae, -a', value: 700, glossFr: 'sept cents', cells: _hundreds('septingent'), provenance: const ['$_ag §134']),
  NumeralEntry(id: 'octingenti', lemma: 'octingentī', entry: 'octingentī, -ae, -a', value: 800, glossFr: 'huit cents', cells: _hundreds('octingent'), provenance: const ['$_ag §134']),
  NumeralEntry(id: 'nongenti', lemma: 'nōngentī', entry: 'nōngentī, -ae, -a', value: 900, glossFr: 'neuf cents', cells: _hundreds('nōngent'), provenance: const ['$_ag §134']),
  NumeralEntry(id: 'mille', lemma: 'mīlle', entry: 'mīlle (adi. indēcl.)', value: 1000, glossFr: 'mille', hasGender: false, provenance: const ['$_ag §134d'], notes: 'Singulāre: adiectīvum indēclīnābile (mīlle mīlitēs).'),
  NumeralEntry(
    id: 'milia',
    lemma: 'mīlia',
    entry: 'mīlia, mīlium, n. pl.',
    value: 1000,
    glossFr: 'des milliers (+ génitif)',
    kind: NumeralKind.substantivum,
    hasGender: true,
    cells: const {
      'nom.pl.n': ['mīlia', 'mīllia'],
      'voc.pl.n': ['mīlia', 'mīllia'],
      'acc.pl.n': ['mīlia', 'mīllia'],
      'gen.pl.n': ['mīlium', 'mīllium'],
      'dat.pl.n': ['mīlibus', 'mīllibus'],
      'abl.pl.n': ['mīlibus', 'mīllibus'],
    },
    provenance: const ['$_ag §134d'],
    notes: 'Plūrāle: nōmen neutrum tertiae dēclīnātiōnis, genetīvum regit (tria mīlia mīlitum).',
  ),
]);
