/// Verified verb lexicon of Grammaticon.
///
/// Principal parts and classifications follow Allen & Greenough, *New Latin
/// Grammar* (1903; DCC edition, CC BY-SA), sections cited per entry. The
/// lexicon is a representative corpus covering every conjugation family; it is
/// not a dictionary. Forms not derivable by rule are given in `overrides`, and
/// deliberate absences are recorded with their reason.
library;

import '../engine/irregular_paradigms.dart';
import '../model/analysis.dart';
import '../model/grammar.dart';
import '../model/verb.dart';

const _ag = 'Allen & Greenough';

VerbEntry _reg(
  String id,
  List<String> pp,
  Conjugation c,
  String gloss, {
  bool intransitive = false,
  bool hasSupine = true,
  List<String> prov = const [],
  Map<String, List<String>> overrides = const {},
  List<AbsentForm> absent = const [],
  String notes = '',
  bool shortA = false,
}) =>
    VerbEntry(
      id: id,
      lemma: pp[0],
      principalParts: pp,
      conjugation: c,
      kind: VerbKind.regulare,
      glossFr: gloss,
      intransitive: intransitive,
      hasSupine: hasSupine,
      provenance: ['$_ag §184–189', ...prov],
      overrides: overrides,
      absent: absent,
      notes: notes,
      shortA: shortA,
    );

VerbEntry _dep(
  String id,
  List<String> pp,
  Conjugation c,
  String gloss, {
  bool hasSupine = true,
  List<String> prov = const [],
  Map<String, List<String>> overrides = const {},
  List<AbsentForm> absent = const [],
  String notes = '',
  bool intransitive = false,
}) =>
    VerbEntry(
      id: id,
      lemma: pp[0],
      principalParts: pp,
      conjugation: c,
      kind: VerbKind.deponens,
      glossFr: gloss,
      hasSupine: hasSupine,
      intransitive: intransitive,
      provenance: ['$_ag §190', ...prov],
      overrides: overrides,
      absent: absent,
      notes: notes,
    );

const _noActiveDep = [
  AbsentForm('ind.*.act', AbsenceStatus.nonExstat, note: 'verbum dēpōnēns: fōrmae āctīvae nōn exstant'),
  AbsentForm('subj.*.act', AbsenceStatus.nonExstat, note: 'verbum dēpōnēns'),
  AbsentForm('imp.*.act', AbsenceStatus.nonExstat, note: 'verbum dēpōnēns'),
  AbsentForm('inf.praes.act', AbsenceStatus.nonExstat, note: 'verbum dēpōnēns'),
  AbsentForm('inf.perf.act', AbsenceStatus.nonExstat, note: 'verbum dēpōnēns: perfectum compositum (secūtus esse)'),
];

const _sumAbsent = [
  AbsentForm('ind.*.pass', AbsenceStatus.nonExstat, note: 'sum: nūllum passīvum'),
  AbsentForm('subj.*.pass', AbsenceStatus.nonExstat, note: 'sum: nūllum passīvum'),
  AbsentForm('imp.*.pass', AbsenceStatus.nonExstat, note: 'sum: nūllum passīvum'),
  AbsentForm('inf.*.pass', AbsenceStatus.nonExstat, note: 'sum: nūllum passīvum'),
  AbsentForm('part.praes', AbsenceStatus.nonUsitatur, note: 'ēns tantum apud philosophōs sēriōrēs (A&G §170 adn.)'),
  AbsentForm('part.perf', AbsenceStatus.nonExstat, note: 'sum: nūllum supīnum'),
  AbsentForm('gdv', AbsenceStatus.nonExstat, note: 'sum: nūllum gerundīvum'),
  AbsentForm('ger', AbsenceStatus.nonExstat, note: 'sum: nūllum gerundium'),
  AbsentForm('sup', AbsenceStatus.nonExstat, note: 'sum: nūllum supīnum'),
  AbsentForm('pp', AbsenceStatus.nonExstat, note: 'sum: nūlla periphrastica passīva'),
];

const _voloAbsent = [
  AbsentForm('ind.*.pass', AbsenceStatus.nonExstat, note: 'nūllum passīvum'),
  AbsentForm('subj.*.pass', AbsenceStatus.nonExstat, note: 'nūllum passīvum'),
  AbsentForm('imp', AbsenceStatus.nonExstat, note: 'nūllus imperātīvus (A&G §199)'),
  AbsentForm('inf.*.pass', AbsenceStatus.nonExstat, note: 'nūllum passīvum'),
  AbsentForm('part.perf', AbsenceStatus.nonExstat, note: 'nūllum supīnum'),
  AbsentForm('part.fut', AbsenceStatus.nonExstat, note: 'nūllum supīnum'),
  AbsentForm('gdv', AbsenceStatus.nonExstat),
  AbsentForm('ger', AbsenceStatus.nonExstat),
  AbsentForm('sup', AbsenceStatus.nonExstat),
  AbsentForm('pa', AbsenceStatus.nonExstat),
  AbsentForm('pp', AbsenceStatus.nonExstat),
];

const _impersonalAbsent = [
  AbsentForm('part', AbsenceStatus.nonUsitatur, note: 'participia adiectīvē tantum ūsitāta; nōn generantur'),
  AbsentForm('gdv', AbsenceStatus.nonAttestatur, note: 'nōn attestātur in fontibus adhibitīs'),
  AbsentForm('ger', AbsenceStatus.nonAttestatur),
  AbsentForm('sup', AbsenceStatus.nonAttestatur),
  AbsentForm('pa', AbsenceStatus.nonAttestatur),
  AbsentForm('pp', AbsenceStatus.nonAttestatur),
  AbsentForm('inf.fut', AbsenceStatus.nonAttestatur, note: 'īnfīnītīvus futūrī rārissimus; nōn generātur'),
  AbsentForm('inf.perf.pass', AbsenceStatus.nonAttestatur),
  AbsentForm('inf.praes.pass', AbsenceStatus.nonAttestatur),
  AbsentForm('ind.*.pass', AbsenceStatus.nonExstat),
  AbsentForm('subj.*.pass', AbsenceStatus.nonExstat),
];

VerbEntry _impers(String id, List<String> pp, Conjugation c, String gloss, {Map<String, List<String>> overrides = const {}, String notes = ''}) =>
    VerbEntry(
      id: id,
      lemma: pp[0],
      principalParts: pp,
      conjugation: c,
      kind: VerbKind.impersonale,
      glossFr: gloss,
      hasSupine: false,
      provenance: const ['$_ag §207–208'],
      overrides: overrides,
      absent: _impersonalAbsent,
      notes: notes,
    );

/// The verb lexicon.
final List<VerbEntry> kVerbs = [
  // ---------------------------------------------------------------- prima
  _reg('amo', ['amō', 'amāre', 'amāvī', 'amātum'], Conjugation.prima, 'aimer', prov: ['A&G §184']),
  _reg('laudo', ['laudō', 'laudāre', 'laudāvī', 'laudātum'], Conjugation.prima, 'louer'),
  _reg('voco', ['vocō', 'vocāre', 'vocāvī', 'vocātum'], Conjugation.prima, 'appeler'),
  _reg('porto', ['portō', 'portāre', 'portāvī', 'portātum'], Conjugation.prima, 'porter'),
  _reg('pugno', ['pugnō', 'pugnāre', 'pugnāvī', 'pugnātum'], Conjugation.prima, 'combattre', intransitive: true),
  _reg('ambulo', ['ambulō', 'ambulāre', 'ambulāvī', 'ambulātum'], Conjugation.prima, 'marcher', intransitive: true),
  _reg('oro', ['ōrō', 'ōrāre', 'ōrāvī', 'ōrātum'], Conjugation.prima, 'prier'),
  _reg('sto', ['stō', 'stāre', 'stetī', 'statum'], Conjugation.prima, 'se tenir debout', intransitive: true, prov: ['A&G §211 c'], notes: 'perfectum reduplicātum stetī'),
  _reg('iuvo', ['iuvō', 'iuvāre', 'iūvī', 'iūtum'], Conjugation.prima, 'aider', notes: 'perfectum iūvī; participium futūrī iuvātūrus etiam attestātum (nōn generātur)'),
  _reg('lavo', ['lavō', 'lavāre', 'lāvī', 'lautum'], Conjugation.prima, 'laver', notes: 'supīnum lautum / lōtum / lavātum; lautum adhibētur'),
  _reg('do', ['dō', 'dare', 'dedī', 'datum'], Conjugation.prima, 'donner', shortA: true, prov: ['A&G §202'], notes: 'a brevis praeter dās, dā, dāns'),
  _reg('circumdo', ['circumdō', 'circumdare', 'circumdedī', 'circumdatum'], Conjugation.prima, 'entourer', shortA: true, prov: ['A&G §202']),
  // ---------------------------------------------------------------- secunda
  _reg('moneo', ['moneō', 'monēre', 'monuī', 'monitum'], Conjugation.secunda, 'avertir', prov: ['A&G §185']),
  _reg('habeo', ['habeō', 'habēre', 'habuī', 'habitum'], Conjugation.secunda, 'avoir'),
  _reg('video', ['videō', 'vidēre', 'vīdī', 'vīsum'], Conjugation.secunda, 'voir'),
  _reg('teneo', ['teneō', 'tenēre', 'tenuī', 'tentum'], Conjugation.secunda, 'tenir'),
  _reg('doceo', ['doceō', 'docēre', 'docuī', 'doctum'], Conjugation.secunda, 'enseigner'),
  _reg('deleo', ['dēleō', 'dēlēre', 'dēlēvī', 'dēlētum'], Conjugation.secunda, 'détruire', notes: 'perfectum in -ēvī'),
  _reg('iubeo', ['iubeō', 'iubēre', 'iussī', 'iussum'], Conjugation.secunda, 'ordonner'),
  _reg('maneo', ['maneō', 'manēre', 'mānsī', 'mānsum'], Conjugation.secunda, 'rester', intransitive: true),
  _reg('sedeo', ['sedeō', 'sedēre', 'sēdī', 'sessum'], Conjugation.secunda, 'être assis', intransitive: true),
  _reg('timeo', ['timeō', 'timēre', 'timuī', '-'], Conjugation.secunda, 'craindre', hasSupine: false, notes: 'nūllum supīnum: participium perfectī, futūrī et fōrmae compositae dēsunt'),
  _reg('moveo', ['moveō', 'movēre', 'mōvī', 'mōtum'], Conjugation.secunda, 'mouvoir'),
  // ---------------------------------------------------------------- tertia
  _reg('rego', ['regō', 'regere', 'rēxī', 'rēctum'], Conjugation.tertia, 'diriger', prov: ['A&G §186']),
  _reg('duco', ['dūcō', 'dūcere', 'dūxī', 'ductum'], Conjugation.tertia, 'conduire', overrides: {'imp.praes.act': ['dūc/dūce#arch', 'dūcite']}, prov: ['A&G §182'], notes: 'imperātīvus dūc'),
  _reg('dico', ['dīcō', 'dīcere', 'dīxī', 'dictum'], Conjugation.tertia, 'dire', overrides: {'imp.praes.act': ['dīc/dīce#arch', 'dīcite']}, prov: ['A&G §182'], notes: 'imperātīvus dīc'),
  _reg('mitto', ['mittō', 'mittere', 'mīsī', 'missum'], Conjugation.tertia, 'envoyer'),
  _reg('lego', ['legō', 'legere', 'lēgī', 'lēctum'], Conjugation.tertia, 'lire, choisir'),
  _reg('scribo', ['scrībō', 'scrībere', 'scrīpsī', 'scrīptum'], Conjugation.tertia, 'écrire'),
  _reg('vinco', ['vincō', 'vincere', 'vīcī', 'victum'], Conjugation.tertia, 'vaincre'),
  _reg('pono', ['pōnō', 'pōnere', 'posuī', 'positum'], Conjugation.tertia, 'poser'),
  _reg('ago', ['agō', 'agere', 'ēgī', 'āctum'], Conjugation.tertia, 'faire, mener'),
  _reg('peto', ['petō', 'petere', 'petīvī', 'petītum'], Conjugation.tertia, 'demander, chercher', notes: 'perfectum petīvī / petiī (contractum)'),
  _reg('credo', ['crēdō', 'crēdere', 'crēdidī', 'crēditum'], Conjugation.tertia, 'croire'),
  _reg('cado', ['cadō', 'cadere', 'cecidī', 'cāsum'], Conjugation.tertia, 'tomber', intransitive: true, notes: 'perfectum reduplicātum'),
  _reg('curro', ['currō', 'currere', 'cucurrī', 'cursum'], Conjugation.tertia, 'courir', intransitive: true),
  _reg('vivo', ['vīvō', 'vīvere', 'vīxī', 'vīctum'], Conjugation.tertia, 'vivre', intransitive: true),
  _reg('reddo', ['reddō', 'reddere', 'reddidī', 'redditum'], Conjugation.tertia, 'rendre'),
  _reg('gero', ['gerō', 'gerere', 'gessī', 'gestum'], Conjugation.tertia, 'porter, mener'),
  _reg('verto', ['vertō', 'vertere', 'vertī', 'versum'], Conjugation.tertia, 'tourner'),
  // ---------------------------------------------------------------- tertia -iō
  _reg('capio', ['capiō', 'capere', 'cēpī', 'captum'], Conjugation.tertiaIo, 'prendre', prov: ['A&G §188']),
  _reg('facio', ['faciō', 'facere', 'fēcī', 'factum'], Conjugation.tertiaIo, 'faire', overrides: facioPassiveFromFio, prov: ['A&G §204'], notes: 'passīvum praesentis systēmatis: fīō; imperātīvus fac'),
  _reg('conficio', ['cōnficiō', 'cōnficere', 'cōnfēcī', 'cōnfectum'], Conjugation.tertiaIo, 'achever', notes: 'compositum faciōnis cum passīvō regulārī (cōnficior)'),
  _reg('iacio', ['iaciō', 'iacere', 'iēcī', 'iactum'], Conjugation.tertiaIo, 'jeter'),
  _reg('rapio', ['rapiō', 'rapere', 'rapuī', 'raptum'], Conjugation.tertiaIo, 'saisir'),
  _reg('fugio', ['fugiō', 'fugere', 'fūgī', 'fugitum'], Conjugation.tertiaIo, 'fuir', notes: 'participium futūrī fugitūrus'),
  _reg('cupio', ['cupiō', 'cupere', 'cupīvī', 'cupītum'], Conjugation.tertiaIo, 'désirer'),
  // ---------------------------------------------------------------- quarta
  _reg('audio', ['audiō', 'audīre', 'audīvī', 'audītum'], Conjugation.quarta, 'entendre', prov: ['A&G §187']),
  _reg('venio', ['veniō', 'venīre', 'vēnī', 'ventum'], Conjugation.quarta, 'venir', intransitive: true),
  _reg('dormio', ['dormiō', 'dormīre', 'dormīvī', 'dormītum'], Conjugation.quarta, 'dormir', intransitive: true),
  _reg('sentio', ['sentiō', 'sentīre', 'sēnsī', 'sēnsum'], Conjugation.quarta, 'sentir'),
  _reg('scio', ['sciō', 'scīre', 'scīvī', 'scītum'], Conjugation.quarta, 'savoir',
      absent: const [AbsentForm('imp.praes.act.2.sg', AbsenceStatus.nonUsitatur, note: 'scī nōn ūsitātur; scītō adhibētur (A&G §449 a)')],
      notes: 'imperātīvus praesentis scī vītātur; futūrī scītō ūsitātus'),
  _reg('aperio', ['aperiō', 'aperīre', 'aperuī', 'apertum'], Conjugation.quarta, 'ouvrir'),
  // ---------------------------------------------------------------- dēpōnentia
  _dep('hortor', ['hortor', 'hortārī', 'hortātus sum', 'hortātum'], Conjugation.prima, 'exhorter', absent: _noActiveDep, prov: ['A&G §190']),
  _dep('vereor', ['vereor', 'verērī', 'veritus sum', 'veritum'], Conjugation.secunda, 'craindre', absent: _noActiveDep),
  _dep('sequor', ['sequor', 'sequī', 'secūtus sum', 'secūtum'], Conjugation.tertia, 'suivre', absent: _noActiveDep, prov: ['A&G §190']),
  _dep('loquor', ['loquor', 'loquī', 'locūtus sum', 'locūtum'], Conjugation.tertia, 'parler', absent: _noActiveDep),
  _dep('utor', ['ūtor', 'ūtī', 'ūsus sum', 'ūsum'], Conjugation.tertia, 'utiliser', absent: _noActiveDep),
  _dep('patior', ['patior', 'patī', 'passus sum', 'passum'], Conjugation.tertiaIo, 'souffrir, supporter', absent: _noActiveDep, prov: ['A&G §190']),
  _dep('morior', ['morior', 'morī', 'mortuus sum', 'mortuum'], Conjugation.tertiaIo, 'mourir',
      overrides: const {'part.fut.act': ['moritūr']}, absent: _noActiveDep, intransitive: true,
      notes: 'participium futūrī moritūrus (A&G §190 adn.); passīvum nūllum'),
  _dep('gradior', ['gradior', 'gradī', 'gressus sum', 'gressum'], Conjugation.tertiaIo, 'marcher', absent: _noActiveDep, intransitive: true),
  _dep('potior', ['potior', 'potīrī', 'potītus sum', 'potītum'], Conjugation.quarta, 's’emparer de',
      overrides: const {
        'ind.praes.pass.3.sg': ['potītur', 'potitur#alt'],
        'ind.praes.pass.1.pl': ['potīmur', 'potimur#alt'],
        'subj.imperf.pass.3.sg': ['potīrētur', 'poterētur#alt'],
      },
      absent: _noActiveDep, notes: 'fōrmae tertiae coniugātiōnis (potitur, poterētur) apud poētās (A&G §190 adn.)'),
  _dep('orior', ['orior', 'orīrī', 'ortus sum', 'ortum'], Conjugation.quarta, 'se lever, naître',
      overrides: const {
        'ind.praes.pass.2.sg': ['oreris', 'orīris#alt'],
        'ind.praes.pass.3.sg': ['oritur'],
        'ind.praes.pass.1.pl': ['orimur'],
        'subj.imperf.pass': ['orīrer/orerer', 'orīrēris/orerēris', 'orīrētur/orerētur', 'orīrēmur/orerēmur', 'orīrēminī/orerēminī', 'orīrentur/orerentur'],
        'part.fut.act': ['oritūr'],
      },
      absent: _noActiveDep, intransitive: true,
      notes: 'praesēns ad exemplum tertiae coniugātiōnis (oritur, orimur); participium futūrī oritūrus (A&G §190 adn.)'),
  _dep('for', ['for', 'fārī', 'fātus sum', 'fātum'], Conjugation.prima, 'parler (défectif)',
      absent: const [
        ..._noActiveDep,
        AbsentForm('ind.praes.pass.1', AbsenceStatus.nonAttestatur, note: 'for: sōlae fātur, fantur attestantur (A&G §206)'),
        AbsentForm('ind.praes.pass.2', AbsenceStatus.nonAttestatur),
        AbsentForm('ind.imperf.pass', AbsenceStatus.nonAttestatur),
        AbsentForm('ind.fut.pass.2', AbsenceStatus.nonAttestatur),
        AbsentForm('ind.fut.pass.1.pl', AbsenceStatus.nonAttestatur),
        AbsentForm('ind.fut.pass.3.pl', AbsenceStatus.nonAttestatur),
        AbsentForm('subj.praes.pass', AbsenceStatus.nonAttestatur),
        AbsentForm('subj.imperf.pass', AbsenceStatus.nonAttestatur),
        AbsentForm('imp.fut', AbsenceStatus.nonAttestatur),
        AbsentForm('imp.praes.pass.2.pl', AbsenceStatus.nonAttestatur),
        AbsentForm('sup.acc', AbsenceStatus.nonAttestatur, note: 'sōlum fātū attestātur'),
        AbsentForm('pa', AbsenceStatus.nonAttestatur),
        AbsentForm('pp', AbsenceStatus.nonAttestatur),
        AbsentForm('inf.fut', AbsenceStatus.nonAttestatur),
      ],
      prov: ['A&G §206'], notes: 'dēfectīvum: fātur, fantur, fābor, fābitur, fātus sum, fāre, fārī, fāns, fandus'),
  // ---------------------------------------------------------------- sēmidēpōnentia (A&G §192)
  VerbEntry(id: 'audeo', lemma: 'audeō', principalParts: ['audeō', 'audēre', 'ausus sum', 'ausum'], conjugation: Conjugation.secunda, kind: VerbKind.semideponens, glossFr: 'oser', provenance: ['$_ag §192'],
      overrides: const {'subj.praes.act.1.sg': ['audeam', 'ausim#arch'], 'subj.praes.act.2.sg': ['audeās', 'ausīs#arch'], 'subj.praes.act.3.sg': ['audeat', 'ausit#arch']},
      absent: const [AbsentForm('inf.perf.act', AbsenceStatus.nonExstat, note: 'perfectum compositum: ausus esse')],
      notes: 'ausim, ausīs, ausit: subiūnctīvus archaicus (A&G §183 3)'),
  VerbEntry(id: 'gaudeo', lemma: 'gaudeō', principalParts: ['gaudeō', 'gaudēre', 'gāvīsus sum', 'gāvīsum'], conjugation: Conjugation.secunda, kind: VerbKind.semideponens, glossFr: 'se réjouir', intransitive: true, provenance: ['$_ag §192'],
      absent: const [AbsentForm('inf.perf.act', AbsenceStatus.nonExstat)]),
  VerbEntry(id: 'soleo', lemma: 'soleō', principalParts: ['soleō', 'solēre', 'solitus sum', 'solitum'], conjugation: Conjugation.secunda, kind: VerbKind.semideponens, glossFr: 'avoir coutume', intransitive: true, provenance: ['$_ag §192'],
      absent: const [AbsentForm('inf.perf.act', AbsenceStatus.nonExstat), AbsentForm('imp', AbsenceStatus.nonAttestatur)]),
  VerbEntry(id: 'fido', lemma: 'fīdō', principalParts: ['fīdō', 'fīdere', 'fīsus sum', 'fīsum'], conjugation: Conjugation.tertia, kind: VerbKind.semideponens, glossFr: 'se fier', intransitive: true, provenance: ['$_ag §192'],
      absent: const [AbsentForm('inf.perf.act', AbsenceStatus.nonExstat)]),
  VerbEntry(id: 'confido', lemma: 'cōnfīdō', principalParts: ['cōnfīdō', 'cōnfīdere', 'cōnfīsus sum', 'cōnfīsum'], conjugation: Conjugation.tertia, kind: VerbKind.semideponens, glossFr: 'avoir confiance', intransitive: true, provenance: ['$_ag §192'],
      absent: const [AbsentForm('inf.perf.act', AbsenceStatus.nonExstat)]),
  VerbEntry(id: 'revertor', lemma: 'revertor', principalParts: ['revertor', 'revertī', 'revertī', 'reversum'], conjugation: Conjugation.tertia, kind: VerbKind.semideponensInversum, glossFr: 'revenir', intransitive: true, provenance: ['$_ag §191'],
      absent: const [
        AbsentForm('ind.praes.act', AbsenceStatus.nonExstat, note: 'praesēns dēpōnēns (revertor)'),
        AbsentForm('ind.imperf.act', AbsenceStatus.nonExstat),
        AbsentForm('ind.fut.act', AbsenceStatus.nonExstat),
        AbsentForm('subj.praes.act', AbsenceStatus.nonExstat),
        AbsentForm('subj.imperf.act', AbsenceStatus.nonExstat),
        AbsentForm('imp.*.act', AbsenceStatus.nonExstat),
        AbsentForm('inf.praes.act', AbsenceStatus.nonExstat),
      ],
      notes: 'praesēns dēpōnēns, perfectum āctīvum revertī (A&G §191)'),
  // ---------------------------------------------------------------- anōmala
  VerbEntry(id: 'sum', lemma: 'sum', principalParts: ['sum', 'esse', 'fuī', '-'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'sum', glossFr: 'être', hasSupine: false, intransitive: true,
      provenance: ['$_ag §170'], absent: _sumAbsent, notes: 'participium futūrī futūrus; forem, fore'),
  VerbEntry(id: 'absum', lemma: 'absum', principalParts: ['absum', 'abesse', 'āfuī', '-'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'sum', compoundOf: 'sum', prefix: 'ab', glossFr: 'être absent', hasSupine: false, intransitive: true,
      provenance: ['$_ag §170 a'], overrides: const {'part.praes.act': ['absēns/absent'], 'part.fut.act': ['āfutūr']},
      absent: [for (final a in _sumAbsent) if (!a.selectorPrefix.startsWith('part.praes')) a]),
  VerbEntry(id: 'adsum', lemma: 'adsum', principalParts: ['adsum', 'adesse', 'adfuī', '-'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'sum', compoundOf: 'sum', prefix: 'ad', glossFr: 'être présent', hasSupine: false, intransitive: true,
      provenance: ['$_ag §170 a'], overrides: const {'part.fut.act': ['adfutūr']}, absent: _sumAbsent, notes: 'etiam assum, affuī (assimilātiō)'),
  VerbEntry(id: 'prosum', lemma: 'prōsum', principalParts: ['prōsum', 'prōdesse', 'prōfuī', '-'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'sum', compoundOf: 'sum', prefix: 'prō', prefixBeforeVowel: 'prōd', glossFr: 'être utile', hasSupine: false, intransitive: true,
      provenance: ['$_ag §170 b'], overrides: const {'part.fut.act': ['prōfutūr']}, absent: _sumAbsent, notes: 'prōd- ante vōcālem: prōdes, prōdest, prōderam'),
  VerbEntry(id: 'praesum', lemma: 'praesum', principalParts: ['praesum', 'praeesse', 'praefuī', '-'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'sum', compoundOf: 'sum', prefix: 'prae', glossFr: 'être à la tête de', hasSupine: false, intransitive: true,
      provenance: ['$_ag §170 a'], overrides: const {'part.praes.act': ['praesēns/praesent'], 'part.fut.act': ['praefutūr']},
      absent: [for (final a in _sumAbsent) if (!a.selectorPrefix.startsWith('part.praes')) a]),
  VerbEntry(id: 'possum', lemma: 'possum', principalParts: ['possum', 'posse', 'potuī', '-'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'possum', glossFr: 'pouvoir', hasSupine: false, intransitive: true,
      provenance: ['$_ag §198'],
      absent: [for (final a in _sumAbsent) if (!a.selectorPrefix.startsWith('part.praes')) a, const AbsentForm('imp', AbsenceStatus.nonExstat, note: 'possum: nūllus imperātīvus'), const AbsentForm('pa', AbsenceStatus.nonExstat), const AbsentForm('inf.fut', AbsenceStatus.nonExstat)],
      notes: 'potēns participium adiectīvum'),
  VerbEntry(id: 'eo', lemma: 'eō', principalParts: ['eō', 'īre', 'iī', 'itum'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'eo', glossFr: 'aller', intransitive: true,
      provenance: ['$_ag §203'], notes: 'perfectum iī (īvī); īstī, īsse contracta; passīvum impersōnāle ītur'),
  VerbEntry(id: 'abeo', lemma: 'abeō', principalParts: ['abeō', 'abīre', 'abiī', 'abitum'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'eo', compoundOf: 'eo', prefix: 'ab', glossFr: 's’en aller', intransitive: true, provenance: ['$_ag §203']),
  VerbEntry(id: 'adeo', lemma: 'adeō', principalParts: ['adeō', 'adīre', 'adiī', 'aditum'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'eo', compoundOf: 'eo', prefix: 'ad', glossFr: 'aller vers', provenance: ['$_ag §203'], notes: 'trānsitīvum: passīvum persōnāle (adītur, aditus est)'),
  VerbEntry(id: 'redeo', lemma: 'redeō', principalParts: ['redeō', 'redīre', 'rediī', 'reditum'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'eo', compoundOf: 'eo', prefix: 'red', glossFr: 'revenir', intransitive: true, provenance: ['$_ag §203']),
  VerbEntry(id: 'exeo', lemma: 'exeō', principalParts: ['exeō', 'exīre', 'exiī', 'exitum'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'eo', compoundOf: 'eo', prefix: 'ex', glossFr: 'sortir', intransitive: true, provenance: ['$_ag §203']),
  VerbEntry(id: 'transeo', lemma: 'trānseō', principalParts: ['trānseō', 'trānsīre', 'trānsiī', 'trānsitum'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'eo', compoundOf: 'eo', prefix: 'trāns', glossFr: 'traverser', provenance: ['$_ag §203']),
  VerbEntry(id: 'pereo', lemma: 'pereō', principalParts: ['pereō', 'perīre', 'periī', 'peritum'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'eo', compoundOf: 'eo', prefix: 'per', glossFr: 'périr', intransitive: true, provenance: ['$_ag §203']),
  VerbEntry(id: 'fero', lemma: 'ferō', principalParts: ['ferō', 'ferre', 'tulī', 'lātum'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'fero', glossFr: 'porter', provenance: ['$_ag §200']),
  VerbEntry(id: 'affero', lemma: 'afferō', principalParts: ['afferō', 'afferre', 'attulī', 'allātum'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'fero', compoundOf: 'fero', prefix: 'af', glossFr: 'apporter', provenance: ['$_ag §200']),
  VerbEntry(id: 'aufero', lemma: 'auferō', principalParts: ['auferō', 'auferre', 'abstulī', 'ablātum'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'fero', compoundOf: 'fero', prefix: 'au', glossFr: 'emporter', provenance: ['$_ag §200']),
  VerbEntry(id: 'refero', lemma: 'referō', principalParts: ['referō', 'referre', 'rettulī', 'relātum'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'fero', compoundOf: 'fero', prefix: 're', glossFr: 'rapporter', provenance: ['$_ag §200']),
  VerbEntry(id: 'offero', lemma: 'offerō', principalParts: ['offerō', 'offerre', 'obtulī', 'oblātum'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'fero', compoundOf: 'fero', prefix: 'of', glossFr: 'offrir', provenance: ['$_ag §200']),
  VerbEntry(id: 'confero', lemma: 'cōnferō', principalParts: ['cōnferō', 'cōnferre', 'contulī', 'collātum'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'fero', compoundOf: 'fero', prefix: 'cōn', glossFr: 'rassembler', provenance: ['$_ag §200']),
  VerbEntry(id: 'volo', lemma: 'volō', principalParts: ['volō', 'velle', 'voluī', '-'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'volo', glossFr: 'vouloir', hasSupine: false, provenance: ['$_ag §199'], absent: _voloAbsent),
  VerbEntry(id: 'nolo', lemma: 'nōlō', principalParts: ['nōlō', 'nōlle', 'nōluī', '-'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'nolo', glossFr: 'ne pas vouloir', hasSupine: false, provenance: ['$_ag §199'],
      absent: [for (final a in _voloAbsent) if (a.selectorPrefix != 'imp') a]),
  VerbEntry(id: 'malo', lemma: 'mālō', principalParts: ['mālō', 'mālle', 'māluī', '-'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'malo', glossFr: 'préférer', hasSupine: false, provenance: ['$_ag §199'],
      absent: [..._voloAbsent, const AbsentForm('part.praes', AbsenceStatus.nonAttestatur, note: 'mālō: participium praesentis dēest (A&G §199)')]),
  VerbEntry(id: 'fio', lemma: 'fīō', principalParts: ['fīō', 'fierī', 'factus sum', 'factum'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'fio', glossFr: 'devenir, être fait', provenance: ['$_ag §204'],
      absent: const [
        AbsentForm('ind.praes.pass', AbsenceStatus.nonExstat, note: 'fīō ipsum passīvī vice fungitur'),
        AbsentForm('ind.imperf.pass', AbsenceStatus.nonExstat),
        AbsentForm('ind.fut.pass', AbsenceStatus.nonExstat),
        AbsentForm('subj.praes.pass', AbsenceStatus.nonExstat),
        AbsentForm('subj.imperf.pass', AbsenceStatus.nonExstat),
        AbsentForm('imp.*.pass', AbsenceStatus.nonExstat),
        AbsentForm('imp.fut', AbsenceStatus.nonAttestatur),
        AbsentForm('inf.praes.pass', AbsenceStatus.nonExstat),
        AbsentForm('inf.perf.act', AbsenceStatus.nonExstat, note: 'perfectum compositum: factus esse'),
        AbsentForm('part.praes', AbsenceStatus.nonExstat),
        AbsentForm('part.fut', AbsenceStatus.nonExstat, note: 'factūrus ad faciō pertinet'),
        AbsentForm('pa', AbsenceStatus.nonExstat),
        AbsentForm('sup', AbsenceStatus.nonExstat, note: 'factum ad faciō pertinet'),
        AbsentForm('ger', AbsenceStatus.nonExstat),
      ],
      notes: 'fīō passīvum praesentis systēmatis verbī faciō; perfectum factus sum'),
  VerbEntry(id: 'edo', lemma: 'edō', principalParts: ['edō', 'edere', 'ēdī', 'ēsum'], conjugation: Conjugation.anomala, kind: VerbKind.anomalum, family: 'edo', glossFr: 'manger', provenance: ['$_ag §201'], notes: 'fōrmae ēs, ēst, ēsse similēs verbō sum'),
  // ---------------------------------------------------------------- dēfectīva (A&G §205)
  VerbEntry(id: 'odi', lemma: 'ōdī', principalParts: ['ōdī', '-', 'ōdī', 'ōsum'], conjugation: Conjugation.anomala, kind: VerbKind.defectivum, glossFr: 'haïr', hasPresentSystem: false, perfectHasPresentSense: true, provenance: ['$_ag §205'],
      absent: const [
        AbsentForm('ind.praes', AbsenceStatus.nonExstat, note: 'perfectum vim praesentis habet'),
        AbsentForm('ind.imperf', AbsenceStatus.nonExstat), AbsentForm('ind.fut', AbsenceStatus.nonExstat),
        AbsentForm('subj.praes', AbsenceStatus.nonExstat), AbsentForm('subj.imperf', AbsenceStatus.nonExstat),
        AbsentForm('imp', AbsenceStatus.nonExstat), AbsentForm('inf.praes', AbsenceStatus.nonExstat),
        AbsentForm('ind.*.pass', AbsenceStatus.nonExstat), AbsentForm('subj.*.pass', AbsenceStatus.nonExstat),
        AbsentForm('inf.perf.pass', AbsenceStatus.nonExstat), AbsentForm('inf.fut.pass', AbsenceStatus.nonExstat),
        AbsentForm('part.perf', AbsenceStatus.nonUsitatur, note: 'ōsus adiectīvum (exōsus, perōsus)'),
        AbsentForm('part.praes', AbsenceStatus.nonExstat), AbsentForm('gdv', AbsenceStatus.nonExstat), AbsentForm('ger', AbsenceStatus.nonExstat), AbsentForm('sup', AbsenceStatus.nonExstat), AbsentForm('pp', AbsenceStatus.nonExstat),
      ],
      notes: 'participium futūrī ōsūrus; ōdī = ōdiō habeō'),
  VerbEntry(id: 'memini', lemma: 'meminī', principalParts: ['meminī', '-', 'meminī', '-'], conjugation: Conjugation.anomala, kind: VerbKind.defectivum, glossFr: 'se souvenir', hasPresentSystem: false, hasSupine: false, perfectHasPresentSense: true, provenance: ['$_ag §205'],
      overrides: const {'imp.fut.act': ['mementō', '-', 'mementōte', '-']},
      absent: const [
        AbsentForm('ind.praes', AbsenceStatus.nonExstat, note: 'perfectum vim praesentis habet'),
        AbsentForm('ind.imperf', AbsenceStatus.nonExstat), AbsentForm('ind.fut', AbsenceStatus.nonExstat),
        AbsentForm('subj.praes', AbsenceStatus.nonExstat), AbsentForm('subj.imperf', AbsenceStatus.nonExstat),
        AbsentForm('imp.praes', AbsenceStatus.nonExstat, note: 'imperātīvus futūrī tantum: mementō'),
        AbsentForm('inf.praes', AbsenceStatus.nonExstat),
        AbsentForm('ind.*.pass', AbsenceStatus.nonExstat), AbsentForm('subj.*.pass', AbsenceStatus.nonExstat),
        AbsentForm('part', AbsenceStatus.nonExstat), AbsentForm('gdv', AbsenceStatus.nonExstat), AbsentForm('ger', AbsenceStatus.nonExstat), AbsentForm('sup', AbsenceStatus.nonExstat), AbsentForm('pa', AbsenceStatus.nonExstat), AbsentForm('pp', AbsenceStatus.nonExstat),
      ]),
  VerbEntry(id: 'coepi', lemma: 'coepī', principalParts: ['coepī', '-', 'coepī', 'coeptum'], conjugation: Conjugation.anomala, kind: VerbKind.defectivum, glossFr: 'commencer', hasPresentSystem: false, provenance: ['$_ag §205'],
      absent: const [
        AbsentForm('ind.praes', AbsenceStatus.nonUsitatur, note: 'praesēns coepiō archaicum; incipiō adhibētur'),
        AbsentForm('ind.imperf', AbsenceStatus.nonUsitatur), AbsentForm('ind.fut', AbsenceStatus.nonUsitatur),
        AbsentForm('subj.praes', AbsenceStatus.nonUsitatur), AbsentForm('subj.imperf', AbsenceStatus.nonUsitatur),
        AbsentForm('imp', AbsenceStatus.nonExstat), AbsentForm('inf.praes', AbsenceStatus.nonUsitatur),
        AbsentForm('part.praes', AbsenceStatus.nonExstat), AbsentForm('gdv', AbsenceStatus.nonExstat), AbsentForm('ger', AbsenceStatus.nonExstat), AbsentForm('pp', AbsenceStatus.nonExstat),
      ],
      notes: 'coeptus sum passīvum (coepta est pugna); coeptūrus'),
  VerbEntry(id: 'inquam', lemma: 'inquam', principalParts: ['inquam', '-', '-', '-'], conjugation: Conjugation.anomala, kind: VerbKind.defectivum, glossFr: 'dire (incise)', hasSupine: false, hasPerfect: false, explicitOnly: true, provenance: ['$_ag §206'],
      overrides: const {
        'ind.praes.act': ['inquam', 'inquis', 'inquit', 'inquimus', '-', 'inquiunt'],
        'ind.imperf.act': ['-', '-', 'inquiēbat', '-', '-', '-'],
        'ind.fut.act': ['-', 'inquiēs', 'inquiet', '-', '-', '-'],
        'ind.perf.act': ['-', 'inquistī', 'inquit', '-', '-', '-'],
        'imp.praes.act': ['inque', '-'],
        'imp.fut.act': ['inquitō', '-', '-', '-'],
      },
      absent: const [AbsentForm('ind.praes.act.2.pl', AbsenceStatus.nonAttestatur, note: 'A&G §206 b'), AbsentForm('subj', AbsenceStatus.nonAttestatur), AbsentForm('inf', AbsenceStatus.nonAttestatur), AbsentForm('part', AbsenceStatus.nonAttestatur)]),
  VerbEntry(id: 'aio', lemma: 'āiō', principalParts: ['āiō', '-', '-', '-'], conjugation: Conjugation.anomala, kind: VerbKind.defectivum, glossFr: 'affirmer', hasSupine: false, hasPerfect: false, explicitOnly: true, provenance: ['$_ag §206'],
      overrides: const {
        'ind.praes.act': ['āiō', 'ais', 'ait', '-', '-', 'āiunt'],
        'ind.imperf.act': ['āiēbam', 'āiēbās', 'āiēbat', 'āiēbāmus', 'āiēbātis', 'āiēbant'],
        'ind.perf.act': ['-', '-', 'ait', '-', '-', '-'],
        'subj.praes.act': ['-', 'āiās', 'āiat', '-', '-', 'āiant'],
        'imp.praes.act': ['aī', '-'],
        'part.praes.act': ['āiēns/āient'],
      },
      absent: const [AbsentForm('ind.praes.act.1.pl', AbsenceStatus.nonAttestatur), AbsentForm('ind.praes.act.2.pl', AbsenceStatus.nonAttestatur), AbsentForm('ind.fut', AbsenceStatus.nonAttestatur), AbsentForm('inf', AbsenceStatus.nonAttestatur)],
      notes: 'ain’ (= aisne) colloquiāle nōn generātur'),
  VerbEntry(id: 'quaeso', lemma: 'quaesō', principalParts: ['quaesō', '-', '-', '-'], conjugation: Conjugation.anomala, kind: VerbKind.defectivum, glossFr: 'je t’en prie', hasSupine: false, hasPerfect: false, explicitOnly: true, provenance: ['$_ag §206'],
      overrides: const {'ind.praes.act': ['quaesō', '-', '-', 'quaesumus', '-', '-']},
      absent: const [AbsentForm('ind.praes.act.2', AbsenceStatus.nonAttestatur), AbsentForm('ind.praes.act.3', AbsenceStatus.nonAttestatur)]),
  VerbEntry(id: 'salve', lemma: 'salvē', principalParts: ['salvē', 'salvēre', '-', '-'], conjugation: Conjugation.anomala, kind: VerbKind.defectivum, glossFr: 'salut !', hasSupine: false, hasPerfect: false, explicitOnly: true, provenance: ['$_ag §206'],
      overrides: const {
        'imp.praes.act': ['salvē', 'salvēte'],
        'imp.fut.act': ['salvētō', '-', '-', '-'],
        'inf.praes.act': ['salvēre'],
        'ind.fut.act': ['-', 'salvēbis', '-', '-', '-', '-'],
      },
      notes: 'imperātīvus salūtātiōnis (A&G §206 g)'),
  VerbEntry(id: 'ave', lemma: 'avē', principalParts: ['avē', 'avēre', '-', '-'], conjugation: Conjugation.anomala, kind: VerbKind.defectivum, glossFr: 'salut ! adieu !', hasSupine: false, hasPerfect: false, explicitOnly: true, provenance: ['$_ag §206'],
      overrides: const {'imp.praes.act': ['avē', 'avēte'], 'imp.fut.act': ['avētō', '-', '-', '-'], 'inf.praes.act': ['avēre']},
      notes: 'etiam havē'),
  // ---------------------------------------------------------------- impersōnālia (A&G §207–208)
  _impers('licet', ['licet', 'licēre', 'licuit', '-'], Conjugation.secunda, 'il est permis', overrides: const {'ind.perf.act.3.sg': ['licuit', 'licitum est#alt']}, notes: 'licitum est etiam'),
  _impers('oportet', ['oportet', 'oportēre', 'oportuit', '-'], Conjugation.secunda, 'il faut'),
  _impers('decet', ['decet', 'decēre', 'decuit', '-'], Conjugation.secunda, 'il convient'),
  _impers('pudet', ['pudet', 'pudēre', 'puduit', '-'], Conjugation.secunda, 'on a honte', overrides: const {'ind.perf.act.3.sg': ['puduit', 'puditum est#alt']}),
  _impers('paenitet', ['paenitet', 'paenitēre', 'paenituit', '-'], Conjugation.secunda, 'on se repent'),
  _impers('taedet', ['taedet', 'taedēre', 'taeduit', '-'], Conjugation.secunda, 'on est dégoûté', overrides: const {'ind.perf.act.3.sg': ['taeduit', 'pertaesum est#alt']}),
  _impers('piget', ['piget', 'pigēre', 'piguit', '-'], Conjugation.secunda, 'on est fâché'),
  _impers('libet', ['libet', 'libēre', 'libuit', '-'], Conjugation.secunda, 'il plaît', overrides: const {'ind.perf.act.3.sg': ['libuit', 'libitum est#alt']}),
  _impers('pluit', ['pluit', 'pluere', 'pluit', '-'], Conjugation.tertia, 'il pleut', notes: 'perfectum pluit (plūvit archaicum)'),
  _impers('ningit', ['ningit', 'ningere', 'ninxit', '-'], Conjugation.tertia, 'il neige'),
  _impers('tonat', ['tonat', 'tonāre', 'tonuit', '-'], Conjugation.prima, 'il tonne'),
];
