/// L1 — Elementa nōminālia : les maillons du système nominal.
///
/// Les désinences sont des nœuds **par surface** (`n.des.ae`) et non par case :
/// c'est la surface que le joueur voit, et c'est le partage d'une surface entre
/// plusieurs cases qui fait le syncrétisme. Les cases L2 (`cellae.dart`) sont
/// composées d'un thème et d'une désinence ; deux cases qui partagent la même
/// désinence dans le même paradigme sont automatiquement en confusion
/// `syncretismus`.
library;

import 'skill.dart';

const _ag = 'A&G';

Skill _e(
  String id,
  String nomen,
  String quid, {
  List<String> not = const [],
  List<String> req = const [],
  List<Confusio> conf = const [],
  List<Dimensio> prob = const [Dimensio.casus, Dimensio.numerus, Dimensio.analysis],
  List<String> ag = const [],
  String? parens,
  bool visibilis = true,
}) => Skill(
  id,
  nomen: nomen,
  quid: quid,
  stratum: Stratum.elementum,
  notiones: not,
  requirit: req,
  confunditur: conf,
  probatur: prob,
  fontes: [for (final s in ag) '$_ag $s'],
  parens: parens,
  visibilis: visibilis,
);

Confusio _c(String cum, Modus m, [String nota = '']) => Confusio(cum, m, nota: nota);

final List<Skill> kNominalGroups = [
  _e('n', 'Nōmen', 'Le système nominal : noms.', prob: []),
  _e('n.thema', 'Themata nōminum', 'Reconnaître le type de thème d\'un nom.', parens: 'n', prob: []),
  _e('n.des', 'Dēsinentiae', 'Lire une désinence et connaître toutes ses lectures.', parens: 'n', prob: []),
  _e('n.alt', 'Alternātiōnēs thematis', 'Le nominatif qui cache le thème.', parens: 'n', prob: []),
  _e('n.genus', 'Genera nōminum', 'Prédire le genre par la déclinaison et ses exceptions.', parens: 'n', prob: []),
  _e('adj', 'Adiectīvum', 'Adjectifs, degrés, adverbes.', prob: []),
  _e('adj.classis', 'Classēs adiectīvōrum', 'Les classes d\'adjectifs et leurs paradigmes.', parens: 'adj', prob: []),
  _e('adj.gradus', 'Gradūs comparātiōnis', 'Comparatif et superlatif.', parens: 'adj', prob: []),
  _e('adj.adv', 'Adverbia', 'Formation et degrés des adverbes.', parens: 'adj', prob: []),
  _e('pron', 'Prōnōmen', 'Les pronoms : paradigmes explicites.', prob: []),
  _e('pron.des', 'Dēsinentiae prōnōminālēs', 'Les désinences propres aux pronoms.', parens: 'pron', prob: []),
  _e('num', 'Numerāle', 'Les numéraux.', prob: []),
];

final List<Skill> kNominalElementa = [
  // =====================================================================
  // Thèmes
  // =====================================================================
  _e('n.thema.d1', 'Thema in -ā (prīma)', 'Reconnaître un nom de 1re déclinaison (rosa, rosae) et son thème en -ā.',
      not: ['not.declinatio.1'], parens: 'n.thema', ag: ['§40–43'], prob: [Dimensio.declinatio, Dimensio.genus],
      conf: [_c('n.thema.d2.n', Modus.syncretismus, 'rosa (1re, f. sg.) / bella (2e, n. pl.)'), _c('n.thema.d3.n', Modus.syncretismus, 'rosa / corpora')]),
  _e('n.thema.d2.us', 'Thema in -o: nōmina in -us', 'Reconnaître un nom masculin de 2e déclinaison en -us (servus, servī).',
      not: ['not.declinatio.2', 'not.genus.m'], parens: 'n.thema', ag: ['§45–46'], prob: [Dimensio.declinatio, Dimensio.genus], req: ['n.thema.d1'],
      conf: [_c('n.thema.d4.m', Modus.similitudo, 'servus, servī / manus, manūs'), _c('n.thema.d3.n', Modus.similitudo, 'servus / corpus, tempus')]),
  _e('n.thema.d2.er', 'Nōmina in -er, -ir', 'Reconnaître puer, ager, vir : 2e déclinaison sans -us au nominatif ; voc. = nom. ; e conservé (puerī) ou perdu (agrī).',
      not: ['not.declinatio.2', 'not.genus.m'], parens: 'n.thema', ag: ['§47'], prob: [Dimensio.declinatio, Dimensio.casus], req: ['n.thema.d2.us'],
      conf: [_c('n.thema.d3.cons', Modus.analogia, 'pater, patris (3e) / puer, puerī (2e)')]),
  _e('n.thema.d2.ius', 'Nōmina in -ius, -ium', 'Reconnaître fīlius, ingenium : voc. fīlī, génitif fīlī ou fīliī.',
      not: ['not.declinatio.2'], parens: 'n.thema', ag: ['§49'], prob: [Dimensio.casus], req: ['n.thema.d2.us']),
  _e('n.thema.d2.n', 'Thema in -o: neutra in -um', 'Reconnaître un neutre de 2e déclinaison (bellum, bellī) : nom. = acc., pluriel en -a.',
      not: ['not.declinatio.2', 'not.genus.n'], parens: 'n.thema', ag: ['§48'], prob: [Dimensio.declinatio, Dimensio.genus], req: ['n.thema.d2.us'],
      conf: [_c('n.thema.d1', Modus.syncretismus, 'bella / rosa'), _c('n.thema.d2.us', Modus.similitudo, 'bellum (n.) / servum (acc. m.)')]),
  _e('n.thema.d3.cons', 'Thema cōnsonāns (tertia)', 'Reconnaître un thème consonantique de 3e déclinaison (rēx, rēgis ; cōnsul ; pater) : gén. pl. -um, abl. sg. -e.',
      not: ['not.declinatio.3'], parens: 'n.thema', ag: ['§56–64'], prob: [Dimensio.declinatio, Dimensio.genus], req: ['n.thema.d2.n'],
      conf: [_c('n.thema.d3.i', Modus.analogia, 'rēgum / cīvium : gén. pl. selon le type de thème')]),
  _e('n.thema.d3.i', 'Thema in -i (tertia)', 'Reconnaître un thème en -i (cīvis, cīvium ; urbs, urbium ; mōns, montium) : gén. pl. -ium, acc. pl. -ēs/-īs.',
      not: ['not.declinatio.3'], parens: 'n.thema', ag: ['§65–71'], prob: [Dimensio.declinatio], req: ['n.thema.d3.cons'],
      conf: [_c('n.thema.d3.cons', Modus.analogia, 'cīvium / rēgum')]),
  _e('n.thema.d3.ipura', 'Thema in -i pūrum', 'Reconnaître turris, sitis, vīs : acc. sg. -im, abl. sg. -ī.',
      not: ['not.declinatio.3'], parens: 'n.thema', ag: ['§67', '§75'], prob: [Dimensio.casus], req: ['n.thema.d3.i']),
  _e('n.thema.d3.n', 'Neutra tertiae cōnsonantia', 'Reconnaître corpus, nōmen, caput, tempus : neutres de 3e ; nom. = acc. ; pluriel -a.',
      not: ['not.declinatio.3', 'not.genus.n'], parens: 'n.thema', ag: ['§60–64'], prob: [Dimensio.declinatio, Dimensio.genus], req: ['n.thema.d3.cons'],
      conf: [_c('n.thema.d2.us', Modus.similitudo, 'corpus, tempus / servus'), _c('n.thema.d1', Modus.syncretismus, 'corpora / rosa')]),
  _e('n.thema.d3.ni', 'Neutra tertiae in -e, -al, -ar', 'Reconnaître mare, animal, exemplar : neutres à thème en -i ; abl. -ī, pl. -ia, gén. pl. -ium.',
      not: ['not.declinatio.3', 'not.genus.n'], parens: 'n.thema', ag: ['§68'], prob: [Dimensio.declinatio, Dimensio.casus], req: ['n.thema.d3.n', 'n.thema.d3.i']),
  _e('n.thema.d4.m', 'Thema in -u (quārta)', 'Reconnaître un nom de 4e déclinaison (manus, manūs ; exercitus) et le distinguer de la 2e par le génitif.',
      not: ['not.declinatio.4'], parens: 'n.thema', ag: ['§89–94'], prob: [Dimensio.declinatio, Dimensio.genus],
      conf: [_c('n.thema.d2.us', Modus.similitudo, 'manus / servus')]),
  _e('n.thema.d4.n', 'Neutra quārtae in -ū', 'Reconnaître cornū, genū : neutres de 4e, singulier presque invariable (cornū).',
      not: ['not.declinatio.4', 'not.genus.n'], parens: 'n.thema', ag: ['§89'], prob: [Dimensio.casus], req: ['n.thema.d4.m']),
  _e('n.thema.d5', 'Thema in -ē (quīnta)', 'Reconnaître rēs, diēs, spēs, fidēs : 5e déclinaison ; gén./dat. -ēī/-eī ; nom. pl. = acc. pl. -ēs.',
      not: ['not.declinatio.5'], parens: 'n.thema', ag: ['§96–98'], prob: [Dimensio.declinatio, Dimensio.genus],
      conf: [_c('n.thema.d3.cons', Modus.syncretismus, 'rēs, diēs (nom. sg. 5e) / rēgēs (nom. pl. 3e) : -ēs')]),
  _e('n.thema.proprium', 'Nōmina urbium et īnsulārum', 'Reconnaître un nom de ville ou de petite île : sans préposition, locatif au singulier (Rōmae, Corinthī, Carthāgine).',
      not: ['not.casus.loc'], parens: 'n.thema', ag: ['§427'], req: ['n.thema.d1', 'n.thema.d2.us', 'n.des.ae', 'n.des.i_long'], prob: [Dimensio.casus, Dimensio.constructio]),

  // =====================================================================
  // Alternances du thème
  // =====================================================================
  _e('n.alt.nom3', 'Nōminātīvus tertiae: thema cēlātum', 'Retrouver le thème sous un nominatif de 3e qui le déforme : rēx/rēg-, pater/patr-, corpus/corpor-, nōmen/nōmin-, iter/itiner-.',
      not: ['not.declinatio.3'], parens: 'n.alt', ag: ['§57–63'], prob: [Dimensio.lemma, Dimensio.declinatio], req: ['n.thema.d3.cons']),
  _e('n.alt.syncopa', 'Syncopa in -er', 'Savoir si le -e- du nominatif reste (puer, puerī ; miser, miserī) ou tombe (ager, agrī ; pulcher, pulchrī).',
      not: ['not.declinatio.2'], parens: 'n.alt', ag: ['§47', '§112'], prob: [Dimensio.lemma, Dimensio.formaPlena], req: ['n.thema.d2.er']),
  _e('n.alt.quantitas', 'Quantitās dēsinentiārum', 'Lire la quantité quand elle seule distingue : rosa / rosā, manus / manūs, diē / diem.',
      not: ['not.casus'], parens: 'n.alt', ag: ['§10', '§43'], req: ['n.des.a_long', 'n.des.us_long', 'n.des.is_long'], prob: [Dimensio.casus]),
  _e('n.alt.rhotacismus', 'Rhotacismus', 'Reconnaître s/r entre le nominatif et le thème : corpus, corporis ; flōs, flōris ; genus, generis.',
      not: ['not.declinatio.3'], parens: 'n.alt', ag: ['§15'], prob: [Dimensio.lemma], req: ['n.alt.nom3']),

  // =====================================================================
  // Genre
  // =====================================================================
  _e('n.genus.d1', 'Genus prīmae', 'Savoir que la 1re est féminine sauf les noms d\'hommes (poēta, nauta, agricola, Aenēās).',
      not: ['not.genus', 'not.declinatio.1'], parens: 'n.genus', ag: ['§42'], prob: [Dimensio.genus], req: ['n.thema.d1']),
  _e('n.genus.d2', 'Genus secundae', 'Savoir que -us est masculin (sauf quelques arbres et humus, alvus), -um neutre.',
      not: ['not.genus', 'not.declinatio.2'], parens: 'n.genus', ag: ['§48'], prob: [Dimensio.genus], req: ['n.thema.d2.us']),
  _e('n.genus.d3', 'Genus tertiae ex terminātiōne', 'Prédire le genre en 3e par la terminaison : -or, -ōs, -er m. ; -ās, -ēs, -is, -x, -ō f. ; -men, -us, -e, -al, -ar n. ; et ses exceptions (pater, māter, arbor f., flōs m.).',
      not: ['not.genus', 'not.declinatio.3'], parens: 'n.genus', ag: ['§84–87'], prob: [Dimensio.genus], req: ['n.thema.d3.cons']),
  _e('n.genus.d4', 'Genus quārtae', 'Savoir que la 4e est masculine sauf manus, domus, Īdūs (f.) et les neutres en -ū.',
      not: ['not.genus', 'not.declinatio.4'], parens: 'n.genus', ag: ['§90'], prob: [Dimensio.genus], req: ['n.thema.d4.m']),
  _e('n.genus.d5', 'Genus quīntae', 'Savoir que la 5e est féminine sauf diēs (m., f. au sens de « jour fixé ») et merīdiēs.',
      not: ['not.genus', 'not.declinatio.5'], parens: 'n.genus', ag: ['§97'], prob: [Dimensio.genus], req: ['n.thema.d5']),

  // =====================================================================
  // Désinences par surface
  // =====================================================================
  _e('n.des.a', 'Dēsinentia -a', 'Lire -a : nom./voc. sg. de la 1re (rosa) ; nom./voc./acc. pl. des neutres (bella, corpora).',
      not: ['not.casus.nom', 'not.numerus'], parens: 'n.des', ag: ['§41', '§48', '§60'],
      conf: [_c('n.des.a_long', Modus.syncretismus, 'rosa / rosā : la quantité seule')]),
  _e('n.des.a_long', 'Dēsinentia -ā', 'Lire -ā : abl. sg. de la 1re (rosā) ; distinguer de -a par la quantité.',
      not: ['not.casus.abl', 'not.numerus.sg'], parens: 'n.des', ag: ['§41'], req: ['n.des.a'],
      conf: [_c('n.des.a', Modus.syncretismus, 'rosā / rosa'), _c('v.des.imp.2.sg', Modus.similitudo, 'amā (impératif) / rosā')]),
  _e('n.des.ae', 'Dēsinentia -ae', 'Lire -ae : gén. sg., dat. sg., nom./voc. pl. de la 1re (rosae) ; locatif (Rōmae).',
      not: ['not.casus.gen', 'not.casus.dat', 'not.casus.nom', 'not.declinatio.1'], parens: 'n.des', ag: ['§41', '§427'],
      conf: [_c('n.des.i_long', Modus.analogia, 'rosae (gén. 1re) / servī (gén. 2e) : les deux génitifs')]),
  _e('n.des.am', 'Dēsinentia -am', 'Lire -am : acc. sg. de la 1re (rosam).',
      not: ['not.casus.acc', 'not.numerus.sg'], parens: 'n.des', ag: ['§41'],
      conf: [_c('n.des.um', Modus.analogia, 'rosam / servum'), _c('n.des.as', Modus.analogia, 'rosam / rosās')]),
  _e('n.des.arum', 'Dēsinentia -ārum', 'Lire -ārum : gén. pl. de la 1re (rosārum).',
      not: ['not.casus.gen', 'not.numerus.pl'], parens: 'n.des', ag: ['§41'],
      conf: [_c('n.des.orum', Modus.analogia, 'rosārum / servōrum'), _c('n.des.um', Modus.analogia, 'rosārum / rēgum')]),
  _e('n.des.as', 'Dēsinentia -ās', 'Lire -ās : acc. pl. de la 1re (rosās).',
      not: ['not.casus.acc', 'not.numerus.pl'], parens: 'n.des', ag: ['§41'],
      conf: [_c('n.des.os', Modus.analogia, 'rosās / servōs'), _c('n.des.am', Modus.analogia, 'rosās / rosam'), _c('v.des.act.2.sg.s', Modus.similitudo, 'rosās / amās')]),
  _e('n.des.is_long', 'Dēsinentia -īs', 'Lire -īs : dat./abl. pl. des 1re et 2e (rosīs, servīs, bellīs) ; acc. pl. des thèmes en -i (cīvīs).',
      not: ['not.casus.dat', 'not.casus.abl', 'not.numerus.pl'], parens: 'n.des', ag: ['§41', '§46', '§67'],
      conf: [_c('n.des.is', Modus.syncretismus, 'servīs / rēgis : quantité'), _c('n.des.ibus', Modus.analogia, 'rosīs / rēgibus')]),
  _e('n.des.us', 'Dēsinentia -us', 'Lire -us : nom. sg. m. de la 2e (servus) ; nom./acc. sg. des neutres de 3e (corpus, tempus) ; nom. sg. de la 4e (manus).',
      not: ['not.casus.nom', 'not.numerus.sg'], parens: 'n.des', ag: ['§46', '§60', '§89'],
      conf: [_c('n.des.us_long', Modus.syncretismus, 'manus / manūs')]),
  _e('n.des.us_long', 'Dēsinentia -ūs', 'Lire -ūs : gén. sg. et nom./voc./acc. pl. de la 4e (manūs).',
      not: ['not.casus.gen', 'not.casus.nom', 'not.casus.acc', 'not.declinatio.4'], parens: 'n.des', ag: ['§89'], req: ['n.des.us'],
      conf: [_c('n.des.us', Modus.syncretismus, 'manūs / manus')]),
  _e('n.des.e', 'Dēsinentia -e', 'Lire -e : voc. sg. de la 2e (serve) ; abl. sg. de la 3e (rēge) ; nom./acc. sg. des neutres en -e (mare).',
      not: ['not.casus.voc', 'not.casus.abl', 'not.numerus.sg'], parens: 'n.des', ag: ['§46', '§57', '§68'],
      conf: [_c('n.des.e_long', Modus.syncretismus, 'rēge / rē, diē : quantité'), _c('v.des.imp.2.sg', Modus.syncretismus, 'rege (impératif) / rēge (abl.)')]),
  _e('n.des.e_long', 'Dēsinentia -ē', 'Lire -ē : abl. sg. de la 5e (rē, diē).',
      not: ['not.casus.abl', 'not.declinatio.5'], parens: 'n.des', ag: ['§96'], req: ['n.des.e']),
  _e('n.des.um', 'Dēsinentia -um', 'Lire -um : acc. sg. m. de la 2e (servum) ; nom./voc./acc. sg. n. (bellum) ; gén. pl. de la 3e consonantique (rēgum) ; acc. sg. de la 4e (manum).',
      not: ['not.casus.acc', 'not.casus.gen', 'not.casus.nom'], parens: 'n.des', ag: ['§46', '§48', '§57', '§89'],
      conf: [_c('n.des.ium', Modus.analogia, 'rēgum / cīvium'), _c('n.des.orum', Modus.analogia, 'rēgum / servōrum'), _c('v.nom.ger.nd', Modus.similitudo, 'bellum / amandum')]),
  _e('n.des.i_long', 'Dēsinentia -ī', 'Lire -ī : gén. sg. et nom./voc. pl. de la 2e (servī) ; dat. sg. de la 3e (rēgī) ; abl. sg. des thèmes en -i purs et des neutres en -i (marī) ; locatif (Corinthī) ; voc. de -ius (fīlī).',
      not: ['not.casus.gen', 'not.casus.dat', 'not.casus.nom', 'not.casus.abl'], parens: 'n.des', ag: ['§46', '§49', '§57', '§68', '§427'],
      conf: [_c('n.des.ae', Modus.analogia, 'servī / rosae'), _c('n.des.is', Modus.analogia, 'rēgī (dat.) / rēgis (gén.)'), _c('v.des.perf.1.sg.i', Modus.similitudo, 'servī / amāvī'), _c('v.sig.inf.praes.pass.i', Modus.similitudo, 'rēgī / regī')]),
  _e('n.des.o_long', 'Dēsinentia -ō', 'Lire -ō : dat. et abl. sg. de la 2e (servō, bellō).',
      not: ['not.casus.dat', 'not.casus.abl', 'not.numerus.sg', 'not.declinatio.2'], parens: 'n.des', ag: ['§46'],
      conf: [_c('v.des.act.1.sg.o', Modus.similitudo, 'servō / amō'), _c('n.des.i_long', Modus.analogia, 'servō (dat. 2e) / rēgī (dat. 3e)')]),
  _e('n.des.orum', 'Dēsinentia -ōrum', 'Lire -ōrum : gén. pl. de la 2e (servōrum, bellōrum).',
      not: ['not.casus.gen', 'not.numerus.pl', 'not.declinatio.2'], parens: 'n.des', ag: ['§46'],
      conf: [_c('n.des.arum', Modus.analogia, 'servōrum / rosārum'), _c('n.des.um', Modus.analogia, 'servōrum / rēgum')]),
  _e('n.des.os', 'Dēsinentia -ōs', 'Lire -ōs : acc. pl. de la 2e (servōs).',
      not: ['not.casus.acc', 'not.numerus.pl', 'not.declinatio.2'], parens: 'n.des', ag: ['§46'],
      conf: [_c('n.des.as', Modus.analogia, 'servōs / rosās'), _c('n.des.us', Modus.similitudo, 'servōs / servus')]),
  _e('n.des.is', 'Dēsinentia -is', 'Lire -is : gén. sg. de la 3e (rēgis, cīvis) ; nom. sg. des noms en -is (cīvis).',
      not: ['not.casus.gen', 'not.numerus.sg', 'not.declinatio.3'], parens: 'n.des', ag: ['§57', '§65'],
      conf: [_c('n.des.is_long', Modus.syncretismus, 'rēgis / servīs'), _c('n.des.i_long', Modus.analogia, 'rēgis / rēgī'), _c('v.des.act.2.sg.s', Modus.similitudo, 'rēgis / regis')]),
  _e('n.des.em', 'Dēsinentia -em', 'Lire -em : acc. sg. de la 3e (rēgem) et de la 5e (rem, diem).',
      not: ['not.casus.acc', 'not.numerus.sg'], parens: 'n.des', ag: ['§57', '§96'],
      conf: [_c('n.des.im', Modus.analogia, 'turrim, non *turrem'), _c('n.des.um', Modus.analogia, 'rēgem / servum'), _c('n.des.e', Modus.similitudo, 'rēgem / rēge')]),
  _e('n.des.im', 'Dēsinentia -im', 'Lire -im : acc. sg. des thèmes en -i purs (turrim, sitim, vim).',
      not: ['not.casus.acc', 'not.numerus.sg', 'not.declinatio.3'], parens: 'n.des', ag: ['§67', '§75'], req: ['n.des.em']),
  _e('n.des.es_long', 'Dēsinentia -ēs', 'Lire -ēs : nom./voc./acc. pl. de la 3e (rēgēs) ; nom. sg. et nom./acc. pl. de la 5e (rēs, diēs).',
      not: ['not.casus.nom', 'not.casus.acc'], parens: 'n.des', ag: ['§57', '§96'],
      conf: [_c('n.des.is_long', Modus.analogia, 'cīvēs / cīvīs (acc. pl.)'), _c('v.des.act.2.sg.s', Modus.similitudo, 'rēgēs / regēs (futur)')]),
  _e('n.des.ium', 'Dēsinentia -ium', 'Lire -ium : gén. pl. des thèmes en -i (cīvium, urbium, marium) et des participes (amantium).',
      not: ['not.casus.gen', 'not.numerus.pl', 'not.declinatio.3'], parens: 'n.des', ag: ['§65–68'], req: ['n.des.um'],
      conf: [_c('n.des.um', Modus.analogia, 'cīvium / rēgum')]),
  _e('n.des.ibus', 'Dēsinentia -ibus', 'Lire -ibus : dat./abl. pl. des 3e et 4e (rēgibus, manibus).',
      not: ['not.casus.dat', 'not.casus.abl', 'not.numerus.pl'], parens: 'n.des', ag: ['§57', '§89'],
      conf: [_c('n.des.is_long', Modus.analogia, 'rēgibus / servīs'), _c('n.des.ebus', Modus.similitudo, 'rēgibus / rēbus')]),
  _e('n.des.ia', 'Dēsinentia -ia', 'Lire -ia : nom./voc./acc. pl. des neutres en -i (maria, animālia) et des participes/adjectifs de 3e (fortia, amantia).',
      not: ['not.casus.nom', 'not.casus.acc', 'not.numerus.pl', 'not.genus.n'], parens: 'n.des', ag: ['§68', '§117'], req: ['n.des.a'],
      conf: [_c('n.des.a', Modus.analogia, 'maria / corpora')]),
  _e('n.des.u_long', 'Dēsinentia -ū', 'Lire -ū : abl. sg. de la 4e (manū) ; tout le singulier des neutres en -ū (cornū) ; supin en -ū.',
      not: ['not.casus.abl', 'not.numerus.sg', 'not.declinatio.4'], parens: 'n.des', ag: ['§89'],
      conf: [_c('v.nom.sup.u', Modus.syncretismus, 'dictū')]),
  _e('n.des.ui', 'Dēsinentia -uī', 'Lire -uī : dat. sg. de la 4e (manuī, exercituī).',
      not: ['not.casus.dat', 'not.numerus.sg', 'not.declinatio.4'], parens: 'n.des', ag: ['§89'],
      conf: [_c('n.des.u_long', Modus.similitudo, 'manuī / manū')]),
  _e('n.des.ua', 'Dēsinentia -ua', 'Lire -ua : nom./voc./acc. pl. des neutres de 4e (cornua, genua).',
      not: ['not.casus.nom', 'not.casus.acc', 'not.numerus.pl', 'not.genus.n'], parens: 'n.des', ag: ['§89'], req: ['n.des.a']),
  _e('n.des.uum', 'Dēsinentia -uum', 'Lire -uum : gén. pl. de la 4e (manuum).',
      not: ['not.casus.gen', 'not.numerus.pl', 'not.declinatio.4'], parens: 'n.des', ag: ['§89'],
      conf: [_c('n.des.um', Modus.similitudo, 'manuum / manum')]),
  _e('n.des.ei', 'Dēsinentia -ēī, -eī', 'Lire -ēī/-eī : gén. et dat. sg. de la 5e (diēī, reī).',
      not: ['not.casus.gen', 'not.casus.dat', 'not.numerus.sg', 'not.declinatio.5'], parens: 'n.des', ag: ['§96'],
      conf: [_c('n.des.i_long', Modus.analogia, 'reī / rēgī'), _c('pron.des.i', Modus.similitudo, 'reī / eī')]),
  _e('n.des.erum', 'Dēsinentia -ērum', 'Lire -ērum : gén. pl. de la 5e (rērum, diērum).',
      not: ['not.casus.gen', 'not.numerus.pl', 'not.declinatio.5'], parens: 'n.des', ag: ['§96'],
      conf: [_c('n.des.orum', Modus.analogia, 'rērum / servōrum')]),
  _e('n.des.ebus', 'Dēsinentia -ēbus', 'Lire -ēbus : dat./abl. pl. de la 5e (rēbus, diēbus).',
      not: ['not.casus.dat', 'not.casus.abl', 'not.numerus.pl', 'not.declinatio.5'], parens: 'n.des', ag: ['§96'],
      conf: [_c('n.des.ibus', Modus.similitudo, 'rēbus / rēgibus')]),
  _e('n.des.nom3', 'Nōminātīvus tertiae sine dēsinentiā regulārī', 'Reconnaître un nominatif de 3e (rēx, cōnsul, pater, corpus, nōmen) : forme à apprendre avec le génitif.',
      not: ['not.casus.nom', 'not.numerus.sg', 'not.declinatio.3'], parens: 'n.des', ag: ['§57–63'], req: ['n.alt.nom3'],
      conf: [_c('n.des.us', Modus.similitudo, 'corpus (n. 3e) / servus (m. 2e)')]),
  _e('n.des.er', 'Nōminātīvus in -er', 'Lire -er : nom./voc. sg. de puer, ager, vir (2e) ; pater, māter (3e) ; adjectifs pulcher, ācer.',
      not: ['not.casus.nom', 'not.numerus.sg'], parens: 'n.des', ag: ['§47', '§62', '§112', '§115'],
      conf: [_c('n.des.nom3', Modus.analogia, 'puer (2e) / pater (3e)')]),
  _e('n.des.neutrum', 'Neutra: nōminātīvus = accūsātīvus', 'Savoir que, pour tout neutre, nom. = voc. = acc., et que le pluriel est en -a/-ia/-ua.',
      not: ['not.genus.n', 'not.casus.nom', 'not.casus.acc'], parens: 'n.des', ag: ['§38 b'], prob: [Dimensio.casus, Dimensio.genus],
      conf: [_c('not.casus.acc', Modus.syncretismus, 'bellum : sujet ou objet ; le contexte décide')]),

  // =====================================================================
  // Adjectifs : classes
  // =====================================================================
  _e('adj.classis.12', 'Adiectīva prīmae et secundae', 'Décliner bonus, -a, -um sur servus / rosa / bellum et lire le genre à la terminaison.',
      not: ['not.classis.12'], parens: 'adj.classis', ag: ['§110–111'], prob: [Dimensio.classis, Dimensio.genus, Dimensio.casus], req: ['n.thema.d1', 'n.thema.d2.us', 'n.thema.d2.n'],
      conf: [_c('adj.classis.3.duo', Modus.analogia, 'bonus, -a, -um / fortis, -e')]),
  _e('adj.classis.12.er', 'Adiectīva in -er (prīmae et secundae)', 'Décliner pulcher, pulchra, pulchrum et miser, misera, miserum ; noster, vester.',
      not: ['not.classis.12'], parens: 'adj.classis', ag: ['§112'], prob: [Dimensio.classis, Dimensio.formaPlena], req: ['adj.classis.12', 'n.alt.syncopa'],
      conf: [_c('adj.classis.3.tria', Modus.analogia, 'pulcher, -chra, -chrum / ācer, ācris, ācre')]),
  _e('adj.classis.3.una', 'Adiectīva tertiae ūnīus terminātiōnis', 'Décliner fēlīx, fēlīcis ; ingēns ; vetus : un seul nominatif pour les trois genres ; abl. -ī (mais vetus, dīves, pauper : -e, -um).',
      not: ['not.classis.3'], parens: 'adj.classis', ag: ['§117–121'], prob: [Dimensio.classis, Dimensio.genus, Dimensio.casus], req: ['n.thema.d3.i'],
      conf: [_c('adj.classis.3.cons', Modus.analogia, 'fēlīcī / vetere, dīvite'), _c('n.des.nom3', Modus.similitudo, 'fēlīx / rēx')]),
  _e('adj.classis.3.duo', 'Adiectīva tertiae duārum terminātiōnum', 'Décliner fortis, forte ; omnis ; brevis : -is m./f., -e n. ; abl. -ī, gén. pl. -ium, n. pl. -ia.',
      not: ['not.classis.3'], parens: 'adj.classis', ag: ['§116'], prob: [Dimensio.classis, Dimensio.genus, Dimensio.casus], req: ['n.thema.d3.i'],
      conf: [_c('adj.classis.12', Modus.analogia, 'fortis, -e / bonus, -a, -um'), _c('n.thema.d3.i', Modus.syncretismus, 'fortis (adj.) / cīvis (nom) : même paradigme')]),
  _e('adj.classis.3.tria', 'Adiectīva tertiae trium terminātiōnum', 'Décliner ācer, ācris, ācre ; celer, celeris, celere.',
      not: ['not.classis.3'], parens: 'adj.classis', ag: ['§115'], prob: [Dimensio.classis, Dimensio.genus], req: ['adj.classis.3.duo'],
      conf: [_c('adj.classis.12.er', Modus.analogia, 'ācer / pulcher')]),
  _e('adj.classis.3.cons', 'Adiectīva tertiae cōnsonantia', 'Décliner les comparatifs et vetus, dīves, pauper comme rēx : abl. -e, gén. pl. -um, n. pl. -a.',
      not: ['not.classis.3'], parens: 'adj.classis', ag: ['§120–121'], prob: [Dimensio.casus, Dimensio.classis], req: ['adj.classis.3.una', 'n.thema.d3.cons'],
      conf: [_c('adj.classis.3.una', Modus.analogia, 'fortiōre / fēlīcī')]),
  _e('adj.classis.pron', 'Adiectīva prōnōminālia', 'Décliner ūnus, sōlus, tōtus, alius, alter, uter, neuter, nūllus, ūllus : gén. -īus, dat. -ī.',
      not: ['not.classis.12'], parens: 'adj.classis', ag: ['§113'], prob: [Dimensio.casus, Dimensio.classis], req: ['adj.classis.12', 'pron.des.ius', 'pron.des.i'],
      conf: [_c('adj.classis.12', Modus.analogia, 'ūnīus, non *ūnī ; sōlī (dat.), non *sōlō')]),

  // =====================================================================
  // Adjectifs : degrés
  // =====================================================================
  _e('adj.gradus.comp.ior', 'Comparātīvus -ior, -ius', 'Former et reconnaître le comparatif : thème + -ior (m./f.), -ius (n.) : longior, longius.',
      not: ['not.gradus.comp'], parens: 'adj.gradus', ag: ['§124'], prob: [Dimensio.gradus, Dimensio.forma],
      conf: [_c('adj.gradus.sup.issimus', Modus.analogia, 'longior / longissimus'), _c('adj.adv.comp.ius', Modus.syncretismus, 'longius : comparatif neutre ou adverbe comparatif')]),
  _e('adj.gradus.comp.decl', 'Flexiō comparātīvī', 'Décliner le comparatif sur la 3e consonantique : fortiōris, fortiōrī, fortiōre, fortiōrēs, fortiōrum, fortiōra.',
      not: ['not.gradus.comp', 'not.classis.3'], parens: 'adj.gradus', ag: ['§120'], prob: [Dimensio.casus, Dimensio.numerus, Dimensio.gradus], req: ['adj.gradus.comp.ior', 'adj.classis.3.cons'],
      conf: [_c('adj.classis.3.duo', Modus.analogia, 'fortiōre, fortiōrum, fortiōra / fortī, fortium, fortia')]),
  _e('adj.gradus.sup.issimus', 'Superlātīvus -issimus', 'Former et reconnaître le superlatif régulier : longissimus, -a, -um (1re/2e classe).',
      not: ['not.gradus.sup'], parens: 'adj.gradus', ag: ['§124'], prob: [Dimensio.gradus, Dimensio.forma], req: ['adj.classis.12'],
      conf: [_c('adj.gradus.comp.ior', Modus.analogia, 'longissimus / longior')]),
  _e('adj.gradus.sup.errimus', 'Superlātīvus -errimus', 'Reconnaître le superlatif des adjectifs en -er : pulcherrimus, ācerrimus, celerrimus.',
      not: ['not.gradus.sup'], parens: 'adj.gradus', ag: ['§125'], prob: [Dimensio.gradus, Dimensio.formaPlena], req: ['adj.gradus.sup.issimus']),
  _e('adj.gradus.sup.illimus', 'Superlātīvus -illimus', 'Reconnaître facillimus, difficillimus, similis → simillimus, gracillimus, humillimus.',
      not: ['not.gradus.sup'], parens: 'adj.gradus', ag: ['§126'], prob: [Dimensio.gradus, Dimensio.formaPlena], req: ['adj.gradus.sup.issimus']),
  _e('adj.gradus.irr', 'Comparātiō irregulāris', 'Connaître bonus/melior/optimus, malus/peior/pessimus, magnus/maior/maximus, parvus/minor/minimus, multus/plūs/plūrimus.',
      not: ['not.gradus'], parens: 'adj.gradus', ag: ['§129'], prob: [Dimensio.gradus, Dimensio.lemma, Dimensio.formaPlena], req: ['adj.gradus.comp.ior', 'adj.gradus.sup.issimus'],
      conf: [_c('adj.gradus.comp.ior', Modus.analogia, '*bonior pour melior')]),
  _e('adj.gradus.irr.plus', 'Plūs, plūris', 'Savoir que plūs est un neutre substantif au singulier (plūs pecūniae) et un adjectif au pluriel (plūrēs, plūra).',
      not: ['not.gradus.comp'], parens: 'adj.gradus', ag: ['§120 b'], prob: [Dimensio.gradus, Dimensio.casus], req: ['adj.gradus.irr']),
  _e('adj.gradus.periph', 'Comparātiō perīphrastica', 'Savoir que les adjectifs en -eus, -ius, -uus se comparent avec magis / maximē (magis idōneus).',
      not: ['not.gradus'], parens: 'adj.gradus', ag: ['§128'], prob: [Dimensio.gradus, Dimensio.formaPlena], req: ['adj.gradus.comp.ior']),
  _e('adj.gradus.defect', 'Comparātiō dēfectīva', 'Connaître prior/prīmus, ulterior/ultimus, exterior/extrēmus, inferior/īnfimus : sans positif ou depuis un adverbe.',
      not: ['not.gradus'], parens: 'adj.gradus', ag: ['§130'], prob: [Dimensio.gradus, Dimensio.lemma], req: ['adj.gradus.irr']),

  // =====================================================================
  // Adverbes
  // =====================================================================
  _e('adj.adv.e', 'Adverbia in -ē', 'Former l\'adverbe des adjectifs de 1re/2e classe en -ē : longē, pulchrē, miserē.',
      not: [], parens: 'adj.adv', ag: ['§214'], prob: [Dimensio.forma, Dimensio.gradus], req: ['adj.classis.12'],
      conf: [_c('n.des.e_long', Modus.similitudo, 'longē / rē'), _c('adj.adv.iter', Modus.analogia, '*longiter')]),
  _e('adj.adv.iter', 'Adverbia in -iter, -ter', 'Former l\'adverbe des adjectifs de 3e classe en -iter (fortiter, ācriter) ou -ter après -nt- (prūdenter).',
      not: [], parens: 'adj.adv', ag: ['§214'], prob: [Dimensio.forma, Dimensio.gradus], req: ['adj.classis.3.duo'],
      conf: [_c('adj.adv.e', Modus.analogia, '*fortē pour fortiter')]),
  _e('adj.adv.o', 'Adverbia in -ō, -um', 'Reconnaître les adverbes en -ō (subitō, falsō, rārō) et les neutres adverbiaux (multum, facile, prīmum).',
      not: [], parens: 'adj.adv', ag: ['§214 c-d'], prob: [Dimensio.forma],
      conf: [_c('n.des.o_long', Modus.syncretismus, 'subitō : adverbe ou abl. sg.'), _c('n.des.um', Modus.syncretismus, 'multum : adverbe ou acc./nom. n.')]),
  _e('adj.adv.comp.ius', 'Adverbium comparātīvum -ius', 'Savoir que l\'adverbe comparatif est le neutre du comparatif : fortius, longius.',
      not: ['not.gradus.comp'], parens: 'adj.adv', ag: ['§218'], prob: [Dimensio.gradus, Dimensio.forma], req: ['adj.gradus.comp.ior'],
      conf: [_c('adj.gradus.comp.ior', Modus.syncretismus, 'fortius : adverbe ou adjectif neutre')]),
  _e('adj.adv.sup.issime', 'Adverbium superlātīvum -issimē', 'Former l\'adverbe superlatif en -issimē (fortissimē, pulcherrimē, facillimē).',
      not: ['not.gradus.sup'], parens: 'adj.adv', ag: ['§218'], prob: [Dimensio.gradus, Dimensio.forma], req: ['adj.gradus.sup.issimus', 'adj.adv.e']),
  _e('adj.adv.irr', 'Adverbia irregulāria', 'Connaître bene/melius/optimē, male/peius/pessimē, magnopere/magis/maximē, multum/plūs/plūrimum, parum/minus/minimē, diū/diūtius/diūtissimē.',
      not: ['not.gradus'], parens: 'adj.adv', ag: ['§218'], prob: [Dimensio.gradus, Dimensio.lemma, Dimensio.formaPlena], req: ['adj.gradus.irr']),

  // =====================================================================
  // Pronoms : désinences propres
  // =====================================================================
  _e('pron.des.ius', 'Genetīvus prōnōminālis -īus', 'Lire -īus (huius, eius, cuius, illīus, ipsīus, ūnīus) comme génitif singulier des trois genres.',
      not: ['not.casus.gen', 'not.numerus.sg'], parens: 'pron.des', ag: ['§146'], prob: [Dimensio.casus, Dimensio.genus],
      conf: [_c('n.des.i_long', Modus.analogia, 'illīus, non *illī au génitif'), _c('pron.des.i', Modus.similitudo, 'illīus / illī')]),
  _e('pron.des.i', 'Datīvus prōnōminālis -ī', 'Lire -ī (huic, eī, cui, illī, ipsī, ūnī) comme datif singulier des trois genres.',
      not: ['not.casus.dat', 'not.numerus.sg'], parens: 'pron.des', ag: ['§146'], prob: [Dimensio.casus, Dimensio.genus],
      conf: [_c('n.des.i_long', Modus.syncretismus, 'illī : dat. sg. ou nom. pl. m.'), _c('pron.des.ius', Modus.similitudo, 'illī / illīus')]),
  _e('pron.des.d', 'Neutrum prōnōmināle -d', 'Lire -d (id, illud, istud, quid, quod, aliud) comme nom./acc. sg. neutre.',
      not: ['not.casus.nom', 'not.casus.acc', 'not.genus.n'], parens: 'pron.des', ag: ['§146'], prob: [Dimensio.genus, Dimensio.casus],
      conf: [_c('n.des.um', Modus.analogia, 'illud, non *illum au neutre'), _c('pron.quis_qui', Modus.functio, 'quid (pronom) / quod (adjectif ou relatif)')]),
  _e('pron.des.c', 'Particula dēmōnstrātīva -c', 'Lire le -c de hic : hic, haec, hoc, hunc, hanc, huius, huic, hōc, hāc (absent de hī, hae, hōs…).',
      not: [], parens: 'pron.des', ag: ['§146 n.'], prob: [Dimensio.casus, Dimensio.genus], req: ['pron.hic']),
  _e('pron.des.dem', 'Particula -dem', 'Décliner īdem : is + -dem avec assimilation (eundem, eandem, eōrundem).',
      not: [], parens: 'pron.des', ag: ['§146'], prob: [Dimensio.casus, Dimensio.formaPlena], req: ['pron.is']),

  // =====================================================================
  // Pronoms : paradigmes
  // =====================================================================
  _e('pron.ego', 'Ego', 'Décliner ego : ego, mē, meī, mihi, mē.', not: ['not.persona.1'], parens: 'pron', ag: ['§143'], prob: [Dimensio.casus, Dimensio.persona],
      conf: [_c('pron.me_mihi', Modus.functio, 'mē / mihi'), _c('pron.tu', Modus.analogia, 'mihi / tibi')]),
  _e('pron.tu', 'Tū', 'Décliner tū : tū, tē, tuī, tibi, tē.', not: ['not.persona.2'], parens: 'pron', ag: ['§143'], prob: [Dimensio.casus, Dimensio.persona],
      conf: [_c('pron.se', Modus.similitudo, 'tibi / sibi ; tē / sē')]),
  _e('pron.nos', 'Nōs', 'Décliner nōs : nōs, nostrum (partitif) / nostrī (objectif), nōbīs.', not: ['not.persona.1', 'not.numerus.pl'], parens: 'pron', ag: ['§143', '§295 b'], prob: [Dimensio.casus, Dimensio.numerus], req: ['pron.ego'],
      conf: [_c('pron.vos', Modus.analogia, 'nōbīs / vōbīs')]),
  _e('pron.vos', 'Vōs', 'Décliner vōs : vōs, vestrum / vestrī, vōbīs.', not: ['not.persona.2', 'not.numerus.pl'], parens: 'pron', ag: ['§143'], prob: [Dimensio.casus, Dimensio.numerus], req: ['pron.tu']),
  _e('pron.se', 'Sē (reflexīvum)', 'Décliner le réfléchi : sē (sēsē), suī, sibi, sē ; même forme au singulier et au pluriel ; renvoie au sujet.', not: ['not.persona.3'], parens: 'pron', ag: ['§144', '§299'], prob: [Dimensio.casus, Dimensio.relatio],
      conf: [_c('pron.is', Modus.functio, 'sē (réfléchi) / eum (non réfléchi)'), _c('pron.tu', Modus.similitudo, 'sibi / tibi')]),
  _e('pron.me_mihi', 'Mē an mihi', 'Distinguer mē (acc./abl.) et mihi (dat.) : mē videt / mihi dat.', not: ['not.casus.acc', 'not.casus.dat'], parens: 'pron', ag: ['§143', '§362'], prob: [Dimensio.casus, Dimensio.functio], req: ['pron.ego']),
  _e('pron.poss', 'Possessīva', 'Décliner meus, tuus, suus, noster, vester comme bonus (voc. mī) et les accorder avec l\'objet possédé, non le possesseur.', not: [], parens: 'pron', ag: ['§145', '§302'], prob: [Dimensio.casus, Dimensio.genus, Dimensio.quodNomen], req: ['adj.classis.12'],
      conf: [_c('pron.suus_eius', Modus.functio, 'suus / eius')]),
  _e('pron.suus_eius', 'Suus an eius', 'Choisir suus (renvoie au sujet) ou eius (renvoie à un autre) : fīlium suum / fīlium eius.', not: [], parens: 'pron', ag: ['§299–301'], prob: [Dimensio.relatio], req: ['pron.poss', 'pron.is', 'pron.se']),
  _e('pron.is', 'Is, ea, id', 'Décliner is, ea, id : eum, eius, eī, eō ; eī/iī, eōs, eōrum, eīs/iīs.', not: [], parens: 'pron', ag: ['§146'], prob: [Dimensio.casus, Dimensio.genus, Dimensio.numerus], req: ['pron.des.ius', 'pron.des.i', 'pron.des.d'],
      conf: [_c('pron.hic', Modus.analogia, 'eum / hunc'), _c('pron.ille', Modus.analogia, 'eius / illīus'), _c('v.anom.eo.subj', Modus.syncretismus, 'eam, eā, eō : pronom ou verbe eō')]),
  _e('pron.hic', 'Hic, haec, hoc', 'Décliner hic : hunc, hanc, hoc, huius, huic, hōc, hāc ; hī, hae, hōs, hōrum, hīs.', not: [], parens: 'pron', ag: ['§146'], prob: [Dimensio.casus, Dimensio.genus, Dimensio.numerus], req: ['pron.des.ius', 'pron.des.i'],
      conf: [_c('pron.ille', Modus.functio, 'hic (proche) / ille (éloigné)'), _c('pron.is', Modus.analogia, 'hunc / eum')]),
  _e('pron.ille', 'Ille, illa, illud', 'Décliner ille : illum, illīus, illī, illō ; illī, illae, illa, illōrum, illīs.', not: [], parens: 'pron', ag: ['§146'], prob: [Dimensio.casus, Dimensio.genus, Dimensio.numerus], req: ['pron.des.ius', 'pron.des.i', 'pron.des.d'],
      conf: [_c('pron.iste', Modus.analogia, 'illud / istud'), _c('pron.hic', Modus.functio, 'ille / hic')]),
  _e('pron.iste', 'Iste, ista, istud', 'Décliner iste comme ille ; valeur de 2e personne, souvent dépréciative.', not: [], parens: 'pron', ag: ['§146', '§297 c'], prob: [Dimensio.casus, Dimensio.genus], req: ['pron.ille']),
  _e('pron.ipse', 'Ipse, ipsa, ipsum', 'Décliner ipse : ipsum (n. -um, non -ud), ipsīus, ipsī, ipsō ; sens « lui-même », non réfléchi.', not: [], parens: 'pron', ag: ['§146', '§298'], prob: [Dimensio.casus, Dimensio.genus, Dimensio.relatio], req: ['pron.des.ius', 'pron.des.i'],
      conf: [_c('pron.des.d', Modus.analogia, 'ipsum, non *ipsud'), _c('pron.se', Modus.functio, 'ipse (intensif) / sē (réfléchi)'), _c('pron.idem', Modus.sensus, 'ipse « lui-même » / īdem « le même »')]),
  _e('pron.idem', 'Īdem, eadem, idem', 'Décliner īdem : eundem, eandem, eiusdem, eīdem, eōdem ; eōrundem, eīsdem.', not: [], parens: 'pron', ag: ['§146'], prob: [Dimensio.casus, Dimensio.genus, Dimensio.formaPlena], req: ['pron.is', 'pron.des.dem'],
      conf: [_c('pron.ipse', Modus.sensus, 'īdem / ipse')]),
  _e('pron.qui', 'Quī, quae, quod (relātīvum)', 'Décliner le relatif : quem, cuius, cui, quō ; quae, quam, quā ; quod ; quī, quae, quōs, quās, quōrum, quibus.', not: [], parens: 'pron', ag: ['§147'], prob: [Dimensio.casus, Dimensio.genus, Dimensio.numerus, Dimensio.genusNumerus], req: ['pron.des.ius', 'pron.des.i', 'pron.des.d'],
      conf: [_c('pron.quis', Modus.syncretismus, 'quem, cuius, cui : relatif ou interrogatif'), _c('pron.quis_qui', Modus.functio, 'quī / quis')]),
  _e('pron.quis', 'Quis, quid (interrogātīvum)', 'Décliner l\'interrogatif : quis, quid ; quem, cuius, cui, quō ; pluriel = relatif.', not: [], parens: 'pron', ag: ['§148'], prob: [Dimensio.casus, Dimensio.genus], req: ['pron.qui'],
      conf: [_c('pron.qui', Modus.syncretismus, 'quem : qui ? ou que'), _c('pron.indef.si_ne', Modus.functio, 'sī quis = sī aliquis')]),
  _e('pron.quis_qui', 'Quis an quī', 'Distinguer quis (pronom interrogatif : quis vēnit ?) et quī (adjectif interrogatif ou relatif : quī vir ? vir quī vēnit) ; quid (pronom) / quod (adjectif).', not: [], parens: 'pron', ag: ['§148', '§333'], prob: [Dimensio.functio, Dimensio.lemma], req: ['pron.qui', 'pron.quis']),
  _e('pron.indef', 'Indēfīnīta', 'Décliner et distinguer aliquis, quīdam, quisque, quisquam, quīvīs, quīlibet, nēmō, nihil, nūllus, ūllus.', not: [], parens: 'pron', ag: ['§149–151', '§310–315'], prob: [Dimensio.lemma, Dimensio.casus, Dimensio.sensus], req: ['pron.quis'],
      conf: [_c('pron.quis', Modus.similitudo, 'aliquis / quis'), _c('pron.indef.quisque', Modus.sensus, 'quisquam / quisque')]),
  _e('pron.indef.si_ne', 'Quis post sī, nisi, nē, num', 'Savoir que quis, quī après sī, nisi, nē, num vaut aliquis : sī quis venit.', not: [], parens: 'pron', ag: ['§310 a'], prob: [Dimensio.sensus, Dimensio.lemma], req: ['pron.indef']),
  _e('pron.indef.quisque', 'Quisque, quisquam, quīdam', 'Distinguer quisque (chacun), quisquam (quelqu\'un, en contexte négatif), quīdam (un certain), aliquis (quelqu\'un).', not: [], parens: 'pron', ag: ['§311–313'], prob: [Dimensio.sensus, Dimensio.lemma], req: ['pron.indef']),
  _e('pron.indef.nemo', 'Nēmō, nihil, nūllus', 'Décliner nēmō (nēminem, nūllīus, nēminī, nūllō) et nihil ; distinguer nēmō (personne) et nūllus (aucun).', not: [], parens: 'pron', ag: ['§314'], prob: [Dimensio.casus, Dimensio.lemma], req: ['pron.indef', 'adj.classis.pron']),
  _e('pron.rel.indef', 'Relātīva indēfīnīta', 'Reconnaître quīcumque, quisquis (quiconque) : relatif + -cumque ou redoublé.', not: [], parens: 'pron', ag: ['§151'], prob: [Dimensio.lemma, Dimensio.casus], req: ['pron.qui']),
  _e('pron.corr', 'Correlātīva', 'Apparier tantus/quantus, tālis/quālis, tot/quot, tam/quam, ibi/ubi, eō/quō, is/quī.', not: [], parens: 'pron', ag: ['§152'], prob: [Dimensio.correlativum, Dimensio.lemma], req: ['pron.qui', 'pron.is']),

  // =====================================================================
  // Numéraux
  // =====================================================================
  _e('num.unus', 'Ūnus, -a, -um', 'Décliner ūnus comme adjectif pronominal (ūnīus, ūnī) ; pluriel avec les pluralia tantum (ūnae litterae).', not: [], parens: 'num', ag: ['§134'], prob: [Dimensio.casus, Dimensio.genus, Dimensio.valor], req: ['adj.classis.pron']),
  _e('num.duo', 'Duo, duae, duo', 'Décliner duo : duōrum/duārum, duōbus/duābus, duōs/duo ; ambō de même.', not: ['not.numerus.pl'], parens: 'num', ag: ['§134'], prob: [Dimensio.casus, Dimensio.genus, Dimensio.valor],
      conf: [_c('num.tres', Modus.analogia, 'duōbus / tribus')]),
  _e('num.tres', 'Trēs, tria', 'Décliner trēs, tria : trium, tribus ; 3e classe.', not: ['not.numerus.pl'], parens: 'num', ag: ['§134'], prob: [Dimensio.casus, Dimensio.genus, Dimensio.valor], req: ['adj.classis.3.duo'],
      conf: [_c('num.duo', Modus.analogia, 'tribus / duōbus')]),
  _e('num.card.indecl', 'Cardinālia indēclīnābilia', 'Savoir que quattuor … centum sont invariables et lire leur valeur.', not: [], parens: 'num', ag: ['§134'], prob: [Dimensio.valor, Dimensio.lemma],
      conf: [_c('num.ord', Modus.sensus, 'quattuor / quārtus'), _c('num.distr', Modus.sensus, 'quattuor / quaternī'), _c('num.adv', Modus.sensus, 'quattuor / quater')]),
  _e('num.card.centeni', 'Cardinālia ducentī … nōngentī', 'Décliner ducentī, -ae, -a … nōngentī comme un pluriel de 1re/2e classe.', not: ['not.numerus.pl'], parens: 'num', ag: ['§134'], prob: [Dimensio.casus, Dimensio.valor], req: ['num.card.indecl', 'adj.classis.12']),
  _e('num.mille', 'Mīlle et mīlia', 'Distinguer mīlle (adjectif invariable : mīlle mīlitēs) et mīlia (nom neutre pluriel + génitif : tria mīlia mīlitum).', not: [], parens: 'num', ag: ['§134 d'], prob: [Dimensio.casus, Dimensio.constructio, Dimensio.valor], req: ['num.card.indecl'],
      conf: [_c('num.card.indecl', Modus.analogia, '*tria mīlia mīlitēs')]),
  _e('num.ord', 'Ōrdinālia', 'Décliner prīmus, secundus (alter), tertius … comme bonus et lire leur valeur (quel rang).', not: [], parens: 'num', ag: ['§134'], prob: [Dimensio.valor, Dimensio.casus], req: ['adj.classis.12'],
      conf: [_c('num.card.indecl', Modus.sensus, 'tertius / trēs'), _c('num.distr', Modus.similitudo, 'tertius / ternī')]),
  _e('num.distr', 'Distribūtīva', 'Reconnaître singulī, bīnī, ternī, quaternī… (chacun combien) : pluriel seulement, gén. -um.', not: ['not.numerus.pl'], parens: 'num', ag: ['§136–137'], prob: [Dimensio.valor, Dimensio.sensus], req: ['num.card.indecl'],
      conf: [_c('num.card.indecl', Modus.sensus, 'bīnī / duo'), _c('num.ord', Modus.similitudo, 'ternī / tertius')]),
  _e('num.adv', 'Adverbia numerālia', 'Reconnaître semel, bis, ter, quater, quīnquiēns… (combien de fois).', not: [], parens: 'num', ag: ['§138'], prob: [Dimensio.valor, Dimensio.sensus], req: ['num.card.indecl'],
      conf: [_c('num.card.indecl', Modus.sensus, 'bis / duo'), _c('num.distr', Modus.sensus, 'bis / bīnī')]),
];
