/// L1 — Elementa verbālia : les maillons du système verbal.
///
/// Un maillon = ce qu'un distracteur peut casser seul dans une forme verbale :
/// le radical (et sa classe), le marqueur de temps-mode, la désinence, une
/// alternance, une particularité de lexème (déponent, défectif). Les cases L2
/// (`cellae.dart`) sont composées de ces maillons ; le diagnostic d'un
/// distracteur est la différence de maillons entre deux cases.
///
/// Sources : Allen & Greenough, *New Latin Grammar* (1903), §§ cités.
library;

import 'skill.dart';

const _ag = 'A&G';

Skill _e(
  String id,
  String nomen,
  String quid, {
  List<String> not = const [],
  List<String> req = const [],
  List<Confusio> conf = const [],
  List<Dimensio> prob = const [Dimensio.tempus, Dimensio.tempusModus, Dimensio.analysis, Dimensio.formaPlena],
  List<String> ag = const [],
  String? parens,
  bool visibilis = true,
}) => Skill(
  id,
  nomen: nomen,
  quid: quid,
  stratum: Stratum.elementum,
  notiones: not,
  requirit: req,
  confunditur: conf,
  probatur: prob,
  fontes: [for (final s in ag) '$_ag $s'],
  parens: parens,
  visibilis: visibilis,
);

Confusio _c(String cum, Modus m, [String nota = '']) => Confusio(cum, m, nota: nota);

/// Groupes d'affichage (Tabula) du système verbal.
final List<Skill> kVerbalGroups = [
  _e('v', 'Verbum', 'Le système verbal.', prob: []),
  _e('v.thema', 'Themata', 'Isoler le radical et reconnaître sa classe.', parens: 'v', prob: []),
  _e('v.voc', 'Vōcālēs thematicae', 'La voyelle qui distingue les conjugaisons.', parens: 'v', prob: []),
  _e('v.sig', 'Signa temporum et modōrum', 'Les marqueurs de temps et de mode.', parens: 'v', prob: []),
  _e('v.des', 'Dēsinentiae persōnālēs', 'Les terminaisons de personne et de nombre.', parens: 'v', prob: []),
  _e('v.comp', 'Fōrmae compositae', 'Participe + auxiliaire.', parens: 'v', prob: []),
  _e('v.nom', 'Fōrmae nōminālēs', 'Infinitifs, participes, gérondif, adjectif verbal, supin.', parens: 'v', prob: []),
  _e('v.alt', 'Alternātiōnēs', 'Quantités, contractions, variantes.', parens: 'v', prob: []),
  _e('v.kind', 'Genera verbōrum', 'Déponents, semi-déponents, défectifs, impersonnels.', parens: 'v', prob: []),
  _e('v.anom', 'Verba anōmala', 'sum, possum, eō, ferō, volō, nōlō, mālō, fīō, dō, edō et composés.', parens: 'v', prob: []),
];

final List<Skill> kVerbalElementa = [
  // =====================================================================
  // Thèmes (radicaux)
  // =====================================================================
  _e('v.thema.praes.c1', 'Thema praesentis in -ā-', 'Isoler le radical du présent d\'un verbe de 1re conjugaison (amā-) et y reconnaître la classe.',
      not: ['not.coniugatio.1', 'not.tempus.systema.praes'], parens: 'v.thema', ag: ['§171', '§179'],
      prob: [Dimensio.coniugatio, Dimensio.lemma],
      conf: [_c('v.thema.praes.c2', Modus.analogia, 'amāre/monēre : voyelle longue dans les deux cas'), _c('v.sig.subj.praes.a', Modus.syncretismus, 'moneat, regat : le -ā- du subjonctif ressemble au radical de la 1re')]),
  _e('v.thema.praes.c2', 'Thema praesentis in -ē-', 'Isoler le radical du présent d\'un verbe de 2e conjugaison (monē-) : l\'-ē- appartient au radical.',
      not: ['not.coniugatio.2', 'not.tempus.systema.praes'], parens: 'v.thema', ag: ['§171', '§179'],
      prob: [Dimensio.coniugatio, Dimensio.lemma],
      conf: [_c('v.thema.praes.c3', Modus.analogia, 'monēre/regere : la quantité de l\'e décide'), _c('v.sig.fut.a_e', Modus.analogia, 'monēs (présent 2e) / regēs (futur 3e)'), _c('v.sig.subj.praes.e', Modus.analogia, 'monēs (présent 2e) / amēs (subjonctif 1re)')]),
  _e('v.thema.praes.c3', 'Thema praesentis cōnsonāns', 'Isoler le radical consonantique (reg-) : la voyelle -i-/-u- qui suit n\'est pas du radical.',
      not: ['not.coniugatio.3', 'not.tempus.systema.praes'], parens: 'v.thema', ag: ['§171', '§179'],
      prob: [Dimensio.coniugatio, Dimensio.lemma],
      conf: [_c('v.thema.praes.c3io', Modus.analogia, 'regō/capiō : même infinitif en -ere, 1re sg différente'), _c('v.thema.praes.c4', Modus.analogia, 'regis/audīs : quantité du i')]),
  _e('v.thema.praes.c3io', 'Thema praesentis in -i- brevī', 'Reconnaître un verbe mixte (capiō, capere) : -iō, -iunt comme la 4e, infinitif en -ere comme la 3e.',
      not: ['not.coniugatio.3io', 'not.tempus.systema.praes'], parens: 'v.thema', ag: ['§176'],
      prob: [Dimensio.coniugatio, Dimensio.lemma],
      conf: [_c('v.thema.praes.c4', Modus.analogia, 'capiō/audiō : la 2e sg et l\'infinitif tranchent (capis, capere / audīs, audīre)')]),
  _e('v.thema.praes.c4', 'Thema praesentis in -ī-', 'Isoler le radical du présent en -ī- (audī-).',
      not: ['not.coniugatio.4', 'not.tempus.systema.praes'], parens: 'v.thema', ag: ['§171', '§179'],
      prob: [Dimensio.coniugatio, Dimensio.lemma]),
  _e('v.thema.perf', 'Thema perfectī', 'Isoler le radical du parfait (amāv-, monu-, rēx-, cecid-, vēn-) et le rattacher à son lexème.',
      not: ['not.tempus.systema.perf'], parens: 'v.thema', ag: ['§177'],
      prob: [Dimensio.lemma, Dimensio.tempus], req: ['v.thema.praes.c1']),
  _e('v.thema.perf.v', 'Perfectum in -v-', 'Parfait en -v- (amāvī, audīvī) : reconnaître -v- comme marque de parfait, pas comme radical.',
      not: ['not.tempus.systema.perf'], parens: 'v.thema', ag: ['§177 a'], req: ['v.thema.perf'], prob: [Dimensio.tempus, Dimensio.lemma],
      conf: [_c('v.thema.perf.u', Modus.similitudo, 'amāvī/monuī')]),
  _e('v.thema.perf.u', 'Perfectum in -u-', 'Parfait en -u- (monuī, habuī) : la voyelle du radical du présent disparaît.',
      not: ['not.tempus.systema.perf'], parens: 'v.thema', ag: ['§177 a'], req: ['v.thema.perf'], prob: [Dimensio.tempus, Dimensio.lemma]),
  _e('v.thema.perf.s', 'Perfectum in -s-', 'Parfait sigmatique (rēxī, scrīpsī, dīxī) : retrouver le lexème sous la consonne modifiée.',
      not: ['not.tempus.systema.perf'], parens: 'v.thema', ag: ['§177 b'], req: ['v.thema.perf'], prob: [Dimensio.lemma, Dimensio.tempus],
      conf: [_c('v.thema.sup.s', Modus.similitudo, 'rēxī / rēctum, mīsī / missum')]),
  _e('v.thema.perf.redup', 'Perfectum reduplicātum', 'Parfait à redoublement (cecidī, dedī, stetī, pepulī).',
      not: ['not.tempus.systema.perf'], parens: 'v.thema', ag: ['§177 c'], req: ['v.thema.perf'], prob: [Dimensio.lemma, Dimensio.tempus]),
  _e('v.thema.perf.long', 'Perfectum vōcālī prōductā', 'Parfait par allongement (vēnī, lēgī, ēgī, fēcī) : seule la quantité distingue du présent (venit / vēnit).',
      not: ['not.tempus.systema.perf'], parens: 'v.thema', ag: ['§177 d'], req: ['v.thema.perf'], prob: [Dimensio.tempus],
      conf: [_c('v.alt.quantitas', Modus.syncretismus, 'venit (présent) / vēnit (parfait)')]),
  _e('v.thema.perf.nud', 'Perfectum sine signō', 'Parfait sans marque (vertī, bibī, dēfendī) : forme identique au présent hors contexte.',
      not: ['not.tempus.systema.perf'], parens: 'v.thema', ag: ['§177 e'], req: ['v.thema.perf'], prob: [Dimensio.tempus]),
  _e('v.thema.sup.t', 'Thema supīnī in -t-', 'Radical du supin et du participe parfait en -t- (amāt-, audīt-, lēct-).',
      not: ['not.forma.part', 'not.forma.sup'], parens: 'v.thema', ag: ['§178'], prob: [Dimensio.lemma, Dimensio.forma]),
  _e('v.thema.sup.s', 'Thema supīnī in -s-', 'Radical du supin en -s- (mīss-, cās-, vīs-) : la dentale du radical s\'est assimilée.',
      not: ['not.forma.part', 'not.forma.sup'], parens: 'v.thema', ag: ['§178', '§15'], prob: [Dimensio.lemma, Dimensio.forma], req: ['v.thema.sup.t']),

  // =====================================================================
  // Voyelles thématiques
  // =====================================================================
  _e('v.voc.a', 'Vōcālis -ā- (prīma)', 'Reconnaître -ā- comme voyelle de la 1re conjugaison (amās, amāmus).',
      not: ['not.coniugatio.1'], parens: 'v.voc', ag: ['§179'], prob: [Dimensio.coniugatio],
      conf: [_c('v.sig.subj.praes.a', Modus.syncretismus, 'amās (ind. 1re) / moneās, regās (subj. 2e-4e)')]),
  _e('v.voc.e', 'Vōcālis -ē- (secunda)', 'Reconnaître -ē- comme voyelle de la 2e conjugaison (monēs, monēmus).',
      not: ['not.coniugatio.2'], parens: 'v.voc', ag: ['§179'], prob: [Dimensio.coniugatio],
      conf: [_c('v.sig.fut.a_e', Modus.syncretismus, 'monēs (ind. 2e) / regēs (fut. 3e)'), _c('v.sig.subj.praes.e', Modus.syncretismus, 'monēs / amēs')]),
  _e('v.voc.i_u', 'Vōcālēs -i-/-u- (tertia)', 'Reconnaître -i-/-u- brefs de liaison de la 3e conjugaison (regis, regit, regunt).',
      not: ['not.coniugatio.3'], parens: 'v.voc', ag: ['§179'], prob: [Dimensio.coniugatio],
      conf: [_c('v.voc.i_long', Modus.syncretismus, 'regis / audīs : quantité')]),
  _e('v.voc.i_long', 'Vōcālis -ī- (quārta)', 'Reconnaître -ī- long de la 4e conjugaison (audīs, audīmus).',
      not: ['not.coniugatio.4'], parens: 'v.voc', ag: ['§179'], prob: [Dimensio.coniugatio]),
  _e('v.voc.io', 'Terminātiōnēs -iō, -iunt', 'Reconnaître -iō / -iunt (3e mixte et 4e) et distinguer capiō de audiō par la 2e sg (capis / audīs).',
      not: ['not.coniugatio.3io', 'not.coniugatio.4'], parens: 'v.voc', ag: ['§176', '§179'], prob: [Dimensio.coniugatio, Dimensio.lemma]),

  // =====================================================================
  // Marqueurs de temps et de mode — système du présent
  // =====================================================================
  _e('v.sig.praes', 'Praesēns: sine signō', 'Le présent de l\'indicatif = radical + voyelle thématique + désinence, sans marqueur.',
      not: ['not.tempus.praes', 'not.modus.ind'], parens: 'v.sig', ag: ['§179'],
      conf: [_c('v.sig.imperf.ba', Modus.similitudo, 'amat / amābat'), _c('v.sig.fut.a_e', Modus.similitudo, 'regit / reget'), _c('v.sig.subj.praes.a', Modus.similitudo, 'monet / moneat'), _c('v.sig.subj.praes.e', Modus.similitudo, 'amat / amet'), _c('v.thema.perf.long', Modus.syncretismus, 'venit / vēnit')]),
  _e('v.sig.imperf.ba', 'Signum imperfectī -bā-', 'Reconnaître -bā- (-ba-) comme marque de l\'imparfait de l\'indicatif, toutes conjugaisons, actif et passif.',
      not: ['not.tempus.imperf', 'not.modus.ind'], parens: 'v.sig', ag: ['§179', '§184'], req: ['v.sig.praes'],
      conf: [_c('v.sig.fut.b', Modus.similitudo, '-bā- / -bi-, -bō, -bu- : amābat / amābit'), _c('v.sig.subj.imperf.re', Modus.analogia, 'amābat / amāret : les deux sont « imparfaits »'), _c('v.sig.plusq.era', Modus.analogia, 'amābat / amāverat'), _c('v.anom.sum.imperf', Modus.similitudo, 'amābat / erat')]),
  _e('v.sig.imperf.ie', 'Imperfectum in -iē-', 'Reconnaître -iē-bat des 3e mixte et 4e (capiēbat, audiēbat) : le -iē- n\'est pas celui de la 2e (monēbat).',
      not: ['not.tempus.imperf', 'not.coniugatio.4', 'not.coniugatio.3io'], parens: 'v.sig', ag: ['§179', '§184'], req: ['v.sig.imperf.ba'],
      prob: [Dimensio.coniugatio, Dimensio.lemma],
      conf: [_c('v.thema.praes.c2', Modus.analogia, 'audiēbat / monēbat : classe différente, même -ēba-')]),
  _e('v.sig.fut.b', 'Signum futūrī -b-', 'Reconnaître -bō, -bi-, -bu- comme marque du futur des 1re et 2e conjugaisons (amābō, monēbis, amābunt).',
      not: ['not.tempus.fut', 'not.modus.ind', 'not.coniugatio.1', 'not.coniugatio.2'], parens: 'v.sig', ag: ['§179', '§184'], req: ['v.sig.praes'],
      conf: [_c('v.sig.imperf.ba', Modus.similitudo, 'amābit / amābat'), _c('v.sig.futex.eri', Modus.analogia, 'amābit / amāverit : deux futurs'), _c('v.sig.fut.a_e', Modus.analogia, 'transfert : *regēbit pour reget, *amam pour amābō')]),
  _e('v.sig.fut.a_e', 'Signum futūrī -a-/-ē-', 'Reconnaître le futur des 3e et 4e conjugaisons : -am à la 1re sg, -ē- ailleurs (regam, regēs, audiet).',
      not: ['not.tempus.fut', 'not.modus.ind', 'not.coniugatio.3', 'not.coniugatio.4'], parens: 'v.sig', ag: ['§179', '§184'], req: ['v.sig.praes'],
      conf: [_c('v.sig.subj.praes.a', Modus.syncretismus, 'regam : futur 1re sg et subjonctif présent 1re sg ; regēs (fut.) / regās (subj.)'), _c('v.thema.praes.c2', Modus.analogia, 'reget (futur 3e) / monet (présent 2e)'), _c('v.sig.fut.b', Modus.analogia, 'transfert de -b- : *regēbit'), _c('v.sig.subj.imperf.re', Modus.similitudo, 'regēs / regerēs')]),
  _e('v.sig.subj.praes.e', 'Signum subiūnctīvī praesentis -ē- (prīma)', 'Reconnaître -e-/-ē- comme marque du subjonctif présent de la 1re conjugaison (amem, amēs, amet).',
      not: ['not.tempus.praes', 'not.modus.subj', 'not.coniugatio.1'], parens: 'v.sig', ag: ['§179', '§185'], req: ['v.sig.praes'],
      prob: [Dimensio.modus, Dimensio.tempusModus, Dimensio.analysis],
      conf: [_c('v.thema.praes.c2', Modus.syncretismus, 'amēs (subj. 1re) / monēs (ind. 2e)'), _c('v.sig.fut.a_e', Modus.syncretismus, 'amet (subj. 1re) / reget (fut. 3e)')]),
  _e('v.sig.subj.praes.a', 'Signum subiūnctīvī praesentis -ā-', 'Reconnaître -a-/-ā- comme marque du subjonctif présent des 2e, 3e et 4e conjugaisons (moneam, regās, audiat).',
      not: ['not.tempus.praes', 'not.modus.subj', 'not.coniugatio.2', 'not.coniugatio.3', 'not.coniugatio.4'], parens: 'v.sig', ag: ['§179', '§185'], req: ['v.sig.praes'],
      prob: [Dimensio.modus, Dimensio.tempusModus, Dimensio.analysis],
      conf: [_c('v.voc.a', Modus.syncretismus, 'regat (subj. 3e) / amat (ind. 1re)'), _c('v.sig.fut.a_e', Modus.syncretismus, 'regam : subjonctif ou futur')]),
  _e('v.sig.subj.imperf.re', 'Signum subiūnctīvī imperfectī -rē-', 'Reconnaître le subjonctif imparfait : infinitif présent + désinence (amārem, regerēs, esset).',
      not: ['not.tempus.imperf', 'not.modus.subj'], parens: 'v.sig', ag: ['§179', '§185'], req: ['v.sig.inf.praes.act.re'],
      prob: [Dimensio.modus, Dimensio.tempusModus, Dimensio.analysis],
      conf: [_c('v.sig.imperf.ba', Modus.analogia, 'amāret / amābat'), _c('v.sig.inf.praes.act.re', Modus.similitudo, 'amāre / amārem'), _c('v.sig.subj.plusq.isse', Modus.analogia, 'amāret / amāvisset'), _c('v.sig.fut.a_e', Modus.similitudo, 'regerēs / regēs')]),

  // =====================================================================
  // Marqueurs — système du parfait
  // =====================================================================
  _e('v.sig.perf', 'Perfectum indicātīvī: thema perfectī + dēsinentiae', 'Reconnaître le parfait de l\'indicatif à son radical propre et à ses désinences spéciales (-ī, -istī, -it…).',
      not: ['not.tempus.perf', 'not.modus.ind', 'not.tempus.systema.perf'], parens: 'v.sig', ag: ['§179', '§184'], req: ['v.thema.perf'],
      conf: [_c('v.sig.praes', Modus.syncretismus, 'venit / vēnit, vertit (présent ou parfait)'), _c('v.sig.plusq.era', Modus.analogia, 'amāvit / amāverat'), _c('v.comp.perf.pass', Modus.analogia, 'amāvit / amātus est : deux parfaits')]),
  _e('v.sig.plusq.era', 'Signum plūsquamperfectī -erā-', 'Reconnaître -erā- après le radical du parfait comme marque du plus-que-parfait de l\'indicatif (amāveram, amāverat).',
      not: ['not.tempus.plusq', 'not.modus.ind', 'not.tempus.systema.perf'], parens: 'v.sig', ag: ['§179', '§184'], req: ['v.sig.perf'],
      conf: [_c('v.sig.futex.eri', Modus.similitudo, 'amāverat / amāverit'), _c('v.anom.sum.imperf', Modus.similitudo, 'amāverat = amāv- + erat'), _c('v.sig.imperf.ba', Modus.analogia, 'amāverat / amābat'), _c('v.sig.subj.plusq.isse', Modus.analogia, 'amāverat / amāvisset')]),
  _e('v.sig.futex.eri', 'Signum futūrī exāctī -eri-', 'Reconnaître -erō, -eri- comme marque du futur antérieur (amāverō, amāverit).',
      not: ['not.tempus.futex', 'not.modus.ind', 'not.tempus.systema.perf'], parens: 'v.sig', ag: ['§179', '§184'], req: ['v.sig.perf'],
      conf: [_c('v.sig.subj.perf.eri', Modus.syncretismus, 'amāverit : futur antérieur ou subjonctif parfait ; amāveris / amāverīs par la quantité'), _c('v.sig.plusq.era', Modus.similitudo, 'amāverit / amāverat'), _c('v.sig.fut.b', Modus.analogia, 'amāverit / amābit'), _c('v.anom.sum.fut', Modus.similitudo, 'amāverō = amāv- + erō')]),
  _e('v.sig.subj.perf.eri', 'Signum subiūnctīvī perfectī -erī-', 'Reconnaître -erim, -erī- comme marque du subjonctif parfait (amāverim, amāverīs).',
      not: ['not.tempus.perf', 'not.modus.subj', 'not.tempus.systema.perf'], parens: 'v.sig', ag: ['§179', '§185'], req: ['v.sig.perf'],
      prob: [Dimensio.modus, Dimensio.tempusModus, Dimensio.analysis],
      conf: [_c('v.sig.futex.eri', Modus.syncretismus, 'amāverit / amāverit'), _c('v.sig.subj.plusq.isse', Modus.analogia, 'amāverit / amāvisset')]),
  _e('v.sig.subj.plusq.isse', 'Signum subiūnctīvī plūsquamperfectī -issē-', 'Reconnaître -issem, -issē- comme marque du subjonctif plus-que-parfait (amāvissem).',
      not: ['not.tempus.plusq', 'not.modus.subj', 'not.tempus.systema.perf'], parens: 'v.sig', ag: ['§179', '§185'], req: ['v.sig.perf', 'v.sig.inf.perf.act.isse'],
      prob: [Dimensio.modus, Dimensio.tempusModus, Dimensio.analysis],
      conf: [_c('v.sig.inf.perf.act.isse', Modus.similitudo, 'amāvisse / amāvissem'), _c('v.sig.subj.imperf.re', Modus.analogia, 'amāvisset / amāret'), _c('v.sig.plusq.era', Modus.analogia, 'amāvisset / amāverat')]),

  // =====================================================================
  // Impératif, infinitifs
  // =====================================================================
  _e('v.sig.imp.praes', 'Imperātīvus praesēns', 'Reconnaître l\'impératif présent : radical nu à la 2e sg (amā, monē, rege, audī), -te au pluriel.',
      not: ['not.modus.imp', 'not.tempus.praes'], parens: 'v.sig', ag: ['§179', '§182'],
      prob: [Dimensio.modus, Dimensio.tempusModus, Dimensio.numerus],
      conf: [_c('v.sig.praes', Modus.similitudo, 'amā / amat'), _c('v.sig.inf.praes.act.re', Modus.similitudo, 'amāte / amāre'), _c('v.sig.imp.fut.to', Modus.analogia, 'amā / amātō')]),
  _e('v.sig.imp.fut.to', 'Imperātīvus futūrus -tō', 'Reconnaître -tō, -tōte, -ntō (amātō, amātōte, amantō) comme impératif futur.',
      not: ['not.modus.imp', 'not.tempus.fut'], parens: 'v.sig', ag: ['§179', '§182', '§449'], req: ['v.sig.imp.praes'],
      prob: [Dimensio.modus, Dimensio.tempusModus, Dimensio.persona],
      conf: [_c('v.sig.imp.praes', Modus.analogia, 'amātō / amā'), _c('v.thema.sup.t', Modus.similitudo, 'amātō / amātum')]),
  _e('v.sig.inf.praes.act.re', 'Īnfīnītīvus praesēns āctīvus -re', 'Reconnaître -re comme infinitif présent actif (amāre, regere).',
      not: ['not.modus.inf', 'not.tempus.praes', 'not.vox.act', 'not.forma.inf'], parens: 'v.sig', ag: ['§179', '§183'],
      prob: [Dimensio.modus, Dimensio.forma, Dimensio.vox],
      conf: [_c('v.des.imp.pass.2.sg.re', Modus.syncretismus, 'amāre : infinitif ou impératif passif 2e sg'), _c('v.alt.re', Modus.syncretismus, 'amābāre : 2e sg passive en -re'), _c('v.sig.inf.praes.pass.ri', Modus.similitudo, 'amāre / amārī'), _c('v.sig.subj.imperf.re', Modus.similitudo, 'amāre / amārem')]),
  _e('v.sig.inf.praes.pass.ri', 'Īnfīnītīvus praesēns passīvus -rī', 'Reconnaître -rī (1re, 2e, 4e) comme infinitif présent passif (amārī, monērī, audīrī).',
      not: ['not.modus.inf', 'not.vox.pass', 'not.forma.inf'], parens: 'v.sig', ag: ['§179', '§183'], req: ['v.sig.inf.praes.act.re'],
      prob: [Dimensio.vox, Dimensio.forma],
      conf: [_c('v.sig.inf.praes.act.re', Modus.similitudo, 'amārī / amāre'), _c('v.sig.inf.praes.pass.i', Modus.analogia, 'transfert : *regerī pour regī')]),
  _e('v.sig.inf.praes.pass.i', 'Īnfīnītīvus praesēns passīvus -ī (tertia)', 'Reconnaître -ī seul (regī, capī) comme infinitif présent passif de la 3e conjugaison.',
      not: ['not.modus.inf', 'not.vox.pass', 'not.forma.inf', 'not.coniugatio.3'], parens: 'v.sig', ag: ['§179', '§183'], req: ['v.sig.inf.praes.pass.ri'],
      prob: [Dimensio.vox, Dimensio.forma],
      conf: [_c('v.des.perf.1.sg.i', Modus.similitudo, 'regī (inf. pass.) / rēxī (parfait) ; capī / cēpī'), _c('v.sig.imp.praes', Modus.similitudo, 'audī (impératif 4e) / regī')]),
  _e('v.sig.inf.perf.act.isse', 'Īnfīnītīvus perfectus āctīvus -isse', 'Reconnaître -isse après le radical du parfait comme infinitif parfait actif (amāvisse).',
      not: ['not.modus.inf', 'not.tempus.perf', 'not.vox.act', 'not.forma.inf'], parens: 'v.sig', ag: ['§179', '§183'], req: ['v.thema.perf'],
      prob: [Dimensio.tempus, Dimensio.forma],
      conf: [_c('v.sig.subj.plusq.isse', Modus.similitudo, 'amāvisse / amāvisset'), _c('v.sig.inf.praes.act.re', Modus.analogia, 'amāvisse / amāre : temps de l\'infinitif'), _c('v.anom.edo.inf', Modus.syncretismus, 'ēsse (manger) / esse ; mais aussi -isse')]),

  // =====================================================================
  // Formes nominales du verbe
  // =====================================================================
  _e('v.nom.part.praes.nt', 'Participium praesēns -ns, -nt-', 'Reconnaître -ns/-nt- comme participe présent actif (amāns, amantis), déclinaison de 3e classe.',
      not: ['not.forma.part', 'not.tempus.praes', 'not.vox.act'], parens: 'v.nom', ag: ['§190', '§494'],
      prob: [Dimensio.forma, Dimensio.casus, Dimensio.tempus],
      conf: [_c('v.des.act.3.pl.nt', Modus.similitudo, 'amant / amāns'), _c('v.nom.gdv.ndus', Modus.similitudo, 'amantem / amandum')]),
  _e('v.nom.part.perf.tus', 'Participium perfectum -tus/-sus', 'Reconnaître -tus, -sus (amātus, mīssus) comme participe parfait passif, déclinaison 1re/2e classe.',
      not: ['not.forma.part', 'not.tempus.perf', 'not.vox.pass'], parens: 'v.nom', ag: ['§190', '§494'], req: ['v.thema.sup.t'],
      prob: [Dimensio.forma, Dimensio.casus, Dimensio.tempus, Dimensio.vox],
      conf: [_c('v.nom.part.fut.urus', Modus.similitudo, 'amātus / amātūrus'), _c('v.nom.sup.um', Modus.syncretismus, 'amātum : supin ou participe acc. sg. / nom. n.'), _c('v.kind.dep', Modus.analogia, 'secūtus : passif de forme, actif de sens')]),
  _e('v.nom.part.fut.urus', 'Participium futūrum -ūrus', 'Reconnaître -ūrus (amātūrus) comme participe futur actif.',
      not: ['not.forma.part', 'not.tempus.fut', 'not.vox.act'], parens: 'v.nom', ag: ['§190', '§498'], req: ['v.nom.part.perf.tus'],
      prob: [Dimensio.forma, Dimensio.tempus, Dimensio.vox],
      conf: [_c('v.nom.part.perf.tus', Modus.similitudo, 'amātūrus / amātus'), _c('v.nom.gdv.ndus', Modus.functio, 'amātūrus (actif, « qui va aimer ») / amandus (passif, « à aimer »)')]),
  _e('v.nom.gdv.ndus', 'Gerundīvum -ndus', 'Reconnaître -ndus, -a, -um (amandus) comme adjectif verbal passif d\'obligation.',
      not: ['not.forma.gdv', 'not.vox.pass'], parens: 'v.nom', ag: ['§190', '§500'],
      prob: [Dimensio.forma, Dimensio.casus, Dimensio.genus],
      conf: [_c('v.nom.ger.nd', Modus.syncretismus, 'amandum : gérondif ou gerundīvum neutre ; amandī : gér. gén. ou gdv. gén. m./n., nom. pl. m.'), _c('v.nom.part.fut.urus', Modus.functio, 'amandus / amātūrus'), _c('v.nom.part.praes.nt', Modus.similitudo, 'amandum / amantem')]),
  _e('v.nom.ger.nd', 'Gerundium -ndī, -ndō, -ndum', 'Reconnaître le gérondif : nom verbal neutre singulier aux cas obliques (amandī, amandō, ad amandum).',
      not: ['not.forma.ger'], parens: 'v.nom', ag: ['§190', '§501–507'], req: ['v.nom.gdv.ndus'],
      prob: [Dimensio.forma, Dimensio.casus],
      conf: [_c('v.nom.gdv.ndus', Modus.syncretismus, 'amandum / amandum')]),
  _e('v.nom.sup.um', 'Supīnum in -um', 'Reconnaître le supin en -um (amātum īre) : but après un verbe de mouvement.',
      not: ['not.forma.sup'], parens: 'v.nom', ag: ['§190', '§509'], req: ['v.thema.sup.t'],
      prob: [Dimensio.forma],
      conf: [_c('v.nom.part.perf.tus', Modus.syncretismus, 'amātum : supin ou participe'), _c('v.nom.sup.u', Modus.similitudo, 'amātum / amātū')]),
  _e('v.nom.sup.u', 'Supīnum in -ū', 'Reconnaître le supin en -ū (mīrābile dictū) : ablatif de relation après un adjectif.',
      not: ['not.forma.sup'], parens: 'v.nom', ag: ['§190', '§510'], req: ['v.nom.sup.um'],
      prob: [Dimensio.forma],
      conf: [_c('v.nom.sup.um', Modus.similitudo, 'dictū / dictum')]),

  // =====================================================================
  // Formes composées
  // =====================================================================
  _e('v.comp.perf.pass', 'Perfectum passīvum compositum', 'Reconnaître participe parfait + sum comme parfait passif (amātus est) et non comme un présent.',
      not: ['not.tempus.perf', 'not.vox.pass', 'not.modus.ind'], parens: 'v.comp', ag: ['§184', '§186'], req: ['v.nom.part.perf.tus', 'v.anom.sum.praes'],
      prob: [Dimensio.tempus, Dimensio.vox, Dimensio.tempusModus],
      conf: [_c('v.sig.praes', Modus.analogia, 'amātus est lu comme un présent à cause de est'), _c('v.comp.peri.pass', Modus.similitudo, 'amātus est / amandus est'), _c('v.comp.peri.act', Modus.similitudo, 'amātus est / amātūrus est'), _c('v.sig.perf', Modus.analogia, 'amātus est / amāvit')]),
  _e('v.comp.aux.tempus', 'Tempus auxiliāris', 'Lire le temps du composé sur l\'auxiliaire : est = parfait, erat = plus-que-parfait, erit = futur antérieur ; sit / esset au subjonctif.',
      not: ['not.tempus.perf', 'not.tempus.plusq', 'not.tempus.futex'], parens: 'v.comp', ag: ['§184', '§186'], req: ['v.comp.perf.pass', 'v.anom.sum.imperf', 'v.anom.sum.fut'],
      prob: [Dimensio.tempus, Dimensio.tempusModus],
      conf: [_c('v.anom.sum.imperf', Modus.functio, 'erat : imparfait de sum, mais plus-que-parfait dans amātus erat'), _c('v.anom.sum.fut', Modus.functio, 'erit : futur de sum, futur antérieur dans amātus erit'), _c('v.alt.fui', Modus.similitudo, 'amātus fuit / amātus est')]),
  _e('v.comp.aux.perf', 'Auxiliāre praesēns: perfectum', 'Lire est / sunt (sit / sint) après un participe parfait comme un parfait passif, non comme un présent (amātus est = il a été aimé).',
      not: ['not.tempus.perf', 'not.vox.pass'], parens: 'v.comp', ag: ['§184', '§186'], req: ['v.comp.perf.pass'], prob: [Dimensio.tempus, Dimensio.tempusModus],
      conf: [_c('v.comp.aux.plusq', Modus.similitudo, 'amātus est / amātus erat'), _c('v.sig.praes', Modus.analogia, 'est lu comme un présent')]),
  _e('v.comp.aux.plusq', 'Auxiliāre imperfectum: plūsquamperfectum', 'Lire erat / erant (esset / essent) après un participe parfait comme un plus-que-parfait passif (amātus erat = il avait été aimé).',
      not: ['not.tempus.plusq', 'not.vox.pass'], parens: 'v.comp', ag: ['§184', '§186'], req: ['v.comp.aux.perf', 'v.anom.sum.imperf'], prob: [Dimensio.tempus, Dimensio.tempusModus],
      conf: [_c('v.comp.aux.perf', Modus.similitudo, 'amātus erat / amātus est'), _c('v.comp.aux.futex', Modus.similitudo, 'amātus erat / amātus erit'), _c('v.sig.imperf.ba', Modus.analogia, 'amātus erat lu comme un imparfait')]),
  _e('v.comp.aux.futex', 'Auxiliāre futūrum: futūrum exāctum', 'Lire erit / erunt après un participe parfait comme un futur antérieur passif (amātus erit = il aura été aimé).',
      not: ['not.tempus.futex', 'not.vox.pass'], parens: 'v.comp', ag: ['§184', '§186'], req: ['v.comp.aux.perf', 'v.anom.sum.fut'], prob: [Dimensio.tempus, Dimensio.tempusModus],
      conf: [_c('v.comp.aux.plusq', Modus.similitudo, 'amātus erit / amātus erat'), _c('v.sig.fut.b', Modus.analogia, 'amātus erit lu comme un futur simple')]),
  _e('v.comp.part.concordia', 'Cōnsēnsus participiī in compositīs', 'Accorder le participe du composé avec le sujet (puella amāta est, puerī amātī sunt).',
      not: ['not.genus', 'not.numerus'], parens: 'v.comp', ag: ['§186', '§286'], req: ['v.comp.perf.pass'],
      prob: [Dimensio.genus, Dimensio.numerus, Dimensio.personaNumerus]),
  _e('v.comp.peri.act', 'Coniugātiō periphrastica āctīva', 'Reconnaître participe futur + sum (amātūrus sum) : « je suis sur le point d\'aimer ».',
      not: ['not.tempus.fut', 'not.vox.act'], parens: 'v.comp', ag: ['§193–195'], req: ['v.nom.part.fut.urus', 'v.comp.perf.pass'],
      prob: [Dimensio.tempus, Dimensio.vox, Dimensio.forma],
      conf: [_c('v.comp.perf.pass', Modus.similitudo, 'amātūrus est / amātus est'), _c('v.comp.peri.pass', Modus.similitudo, 'amātūrus est / amandus est'), _c('v.sig.fut.b', Modus.functio, 'amātūrus est / amābit')]),
  _e('v.comp.peri.pass', 'Coniugātiō periphrastica passīva', 'Reconnaître gerundīvum + sum (amandus est) : obligation, agent au datif.',
      not: ['not.vox.pass'], parens: 'v.comp', ag: ['§194', '§196', '§374'], req: ['v.nom.gdv.ndus', 'v.comp.perf.pass'],
      prob: [Dimensio.vox, Dimensio.forma, Dimensio.tempus],
      conf: [_c('v.comp.perf.pass', Modus.similitudo, 'amandus est / amātus est'), _c('v.comp.peri.act', Modus.similitudo, 'amandus est / amātūrus est')]),
  _e('v.comp.inf.perf.pass', 'Īnfīnītīvus perfectus passīvus', 'Reconnaître participe parfait + esse (amātum esse) comme infinitif parfait passif ; le participe s\'accorde.',
      not: ['not.modus.inf', 'not.tempus.perf', 'not.vox.pass', 'not.forma.inf'], parens: 'v.comp', ag: ['§183', '§184'], req: ['v.nom.part.perf.tus', 'v.sig.inf.praes.act.re'],
      prob: [Dimensio.tempus, Dimensio.vox, Dimensio.forma],
      conf: [_c('v.comp.inf.fut.act', Modus.similitudo, 'amātum esse / amātūrum esse'), _c('v.sig.inf.perf.act.isse', Modus.functio, 'amātum esse / amāvisse : même temps, voix opposée')]),
  _e('v.comp.inf.fut.act', 'Īnfīnītīvus futūrus āctīvus', 'Reconnaître participe futur + esse (amātūrum esse) comme infinitif futur actif.',
      not: ['not.modus.inf', 'not.tempus.fut', 'not.vox.act', 'not.forma.inf'], parens: 'v.comp', ag: ['§183', '§184'], req: ['v.nom.part.fut.urus', 'v.sig.inf.praes.act.re'],
      prob: [Dimensio.tempus, Dimensio.vox, Dimensio.forma],
      conf: [_c('v.comp.inf.perf.pass', Modus.similitudo, 'amātūrum esse / amātum esse'), _c('v.comp.inf.fut.pass.iri', Modus.functio, 'amātūrum esse / amātum īrī')]),
  _e('v.comp.inf.fut.pass.iri', 'Īnfīnītīvus futūrus passīvus -um īrī', 'Reconnaître supin + īrī (amātum īrī) comme infinitif futur passif, invariable.',
      not: ['not.modus.inf', 'not.tempus.fut', 'not.vox.pass', 'not.forma.inf'], parens: 'v.comp', ag: ['§183', '§203 a'], req: ['v.nom.sup.um', 'v.anom.eo.inf'],
      prob: [Dimensio.tempus, Dimensio.vox, Dimensio.forma],
      conf: [_c('v.comp.inf.perf.pass', Modus.similitudo, 'amātum īrī / amātum esse')]),

  // =====================================================================
  // Désinences personnelles actives
  // =====================================================================
  _e('v.des.act.1.sg.o', 'Dēsinentia -ō (1 sg)', 'Reconnaître -ō comme 1re personne du singulier (présent, futur en -bō).',
      not: ['not.persona.1', 'not.numerus.sg', 'not.vox.act'], parens: 'v.des', ag: ['§163'], prob: [Dimensio.persona, Dimensio.personaNumerus],
      conf: [_c('v.des.act.1.sg.m', Modus.analogia, 'amō / amābam, regam'), _c('v.des.pass.1.sg.r', Modus.similitudo, 'amō / amor')]),
  _e('v.des.act.1.sg.m', 'Dēsinentia -m (1 sg)', 'Reconnaître -m comme 1re personne du singulier hors présent (amābam, amem, regam, amāverim).',
      not: ['not.persona.1', 'not.numerus.sg', 'not.vox.act'], parens: 'v.des', ag: ['§163'], prob: [Dimensio.persona, Dimensio.personaNumerus],
      conf: [_c('v.des.act.1.sg.o', Modus.analogia, 'amābam / amō')]),
  _e('v.des.act.2.sg.s', 'Dēsinentia -s (2 sg)', 'Reconnaître -s comme 2e personne du singulier (amās, regis, amāverās).',
      not: ['not.persona.2', 'not.numerus.sg', 'not.vox.act'], parens: 'v.des', ag: ['§163'], prob: [Dimensio.persona, Dimensio.personaNumerus],
      conf: [_c('v.des.act.2.pl.tis', Modus.analogia, 'amās / amātis'), _c('v.des.pass.2.sg.ris', Modus.similitudo, 'amās / amāris'), _c('v.des.perf.2.sg.isti', Modus.analogia, 'amās / amāvistī')]),
  _e('v.des.act.3.sg.t', 'Dēsinentia -t (3 sg)', 'Reconnaître -t comme 3e personne du singulier (amat, regit, amāverit).',
      not: ['not.persona.3', 'not.numerus.sg', 'not.vox.act'], parens: 'v.des', ag: ['§163'], prob: [Dimensio.persona, Dimensio.personaNumerus],
      conf: [_c('v.des.act.3.pl.nt', Modus.analogia, 'amat / amant'), _c('v.des.pass.3.sg.tur', Modus.similitudo, 'amat / amātur')]),
  _e('v.des.act.1.pl.mus', 'Dēsinentia -mus (1 pl)', 'Reconnaître -mus comme 1re personne du pluriel (amāmus, regimus).',
      not: ['not.persona.1', 'not.numerus.pl', 'not.vox.act'], parens: 'v.des', ag: ['§163'], prob: [Dimensio.persona, Dimensio.personaNumerus, Dimensio.numerus],
      conf: [_c('v.des.act.1.sg.o', Modus.analogia, 'amāmus / amō'), _c('v.des.pass.1.pl.mur', Modus.similitudo, 'amāmus / amāmur')]),
  _e('v.des.act.2.pl.tis', 'Dēsinentia -tis (2 pl)', 'Reconnaître -tis comme 2e personne du pluriel (amātis, regitis).',
      not: ['not.persona.2', 'not.numerus.pl', 'not.vox.act'], parens: 'v.des', ag: ['§163'], prob: [Dimensio.persona, Dimensio.personaNumerus, Dimensio.numerus],
      conf: [_c('v.des.act.2.sg.s', Modus.analogia, 'amātis / amās'), _c('v.des.perf.2.pl.istis', Modus.similitudo, 'amātis / amāvistis'), _c('v.des.pass.2.pl.mini', Modus.analogia, 'amātis / amāminī')]),
  _e('v.des.act.3.pl.nt', 'Dēsinentia -nt (3 pl)', 'Reconnaître -nt comme 3e personne du pluriel (amant, regunt, amāverint).',
      not: ['not.persona.3', 'not.numerus.pl', 'not.vox.act'], parens: 'v.des', ag: ['§163'], prob: [Dimensio.persona, Dimensio.personaNumerus, Dimensio.numerus],
      conf: [_c('v.des.act.3.sg.t', Modus.analogia, 'amant / amat'), _c('v.nom.part.praes.nt', Modus.similitudo, 'amant / amāns'), _c('v.des.pass.3.pl.ntur', Modus.similitudo, 'amant / amantur')]),

  // =====================================================================
  // Désinences personnelles passives
  // =====================================================================
  _e('v.des.pass.1.sg.r', 'Dēsinentia -r, -or (1 sg pass.)', 'Reconnaître -or/-r comme 1re personne du singulier passive (amor, amābar, amer).',
      not: ['not.persona.1', 'not.numerus.sg', 'not.vox.pass'], parens: 'v.des', ag: ['§163'], prob: [Dimensio.persona, Dimensio.vox, Dimensio.personaNumerus],
      conf: [_c('v.des.act.1.sg.o', Modus.similitudo, 'amor / amō'), _c('v.des.pass.2.sg.ris', Modus.analogia, 'amor / amāris')]),
  _e('v.des.pass.2.sg.ris', 'Dēsinentia -ris (2 sg pass.)', 'Reconnaître -ris comme 2e personne du singulier passive (amāris, amābāris).',
      not: ['not.persona.2', 'not.numerus.sg', 'not.vox.pass'], parens: 'v.des', ag: ['§163'], prob: [Dimensio.persona, Dimensio.vox, Dimensio.personaNumerus],
      conf: [_c('v.des.act.2.sg.s', Modus.similitudo, 'amāris / amās'), _c('v.sig.futex.eri', Modus.similitudo, 'amāris / amāveris : -ris / -eris'), _c('v.alt.re', Modus.syncretismus, 'amābāris / amābāre'), _c('v.sig.subj.imperf.re', Modus.similitudo, 'amāris / amārēs')]),
  _e('v.des.pass.3.sg.tur', 'Dēsinentia -tur (3 sg pass.)', 'Reconnaître -tur comme 3e personne du singulier passive (amātur, regitur).',
      not: ['not.persona.3', 'not.numerus.sg', 'not.vox.pass'], parens: 'v.des', ag: ['§163'], prob: [Dimensio.persona, Dimensio.vox, Dimensio.personaNumerus],
      conf: [_c('v.des.act.3.sg.t', Modus.similitudo, 'amātur / amat'), _c('v.des.pass.3.pl.ntur', Modus.analogia, 'amātur / amantur')]),
  _e('v.des.pass.1.pl.mur', 'Dēsinentia -mur (1 pl pass.)', 'Reconnaître -mur comme 1re personne du pluriel passive (amāmur).',
      not: ['not.persona.1', 'not.numerus.pl', 'not.vox.pass'], parens: 'v.des', ag: ['§163'], prob: [Dimensio.persona, Dimensio.vox, Dimensio.personaNumerus],
      conf: [_c('v.des.act.1.pl.mus', Modus.similitudo, 'amāmur / amāmus')]),
  _e('v.des.pass.2.pl.mini', 'Dēsinentia -minī (2 pl pass.)', 'Reconnaître -minī comme 2e personne du pluriel passive (amāminī) ; identique à l\'impératif passif pluriel.',
      not: ['not.persona.2', 'not.numerus.pl', 'not.vox.pass'], parens: 'v.des', ag: ['§163'], prob: [Dimensio.persona, Dimensio.vox, Dimensio.personaNumerus],
      conf: [_c('v.des.act.2.pl.tis', Modus.analogia, 'amāminī / amātis'), _c('v.des.imp.pass.2.pl.mini', Modus.syncretismus, 'amāminī : indicatif ou impératif')]),
  _e('v.des.pass.3.pl.ntur', 'Dēsinentia -ntur (3 pl pass.)', 'Reconnaître -ntur comme 3e personne du pluriel passive (amantur, reguntur).',
      not: ['not.persona.3', 'not.numerus.pl', 'not.vox.pass'], parens: 'v.des', ag: ['§163'], prob: [Dimensio.persona, Dimensio.vox, Dimensio.personaNumerus],
      conf: [_c('v.des.act.3.pl.nt', Modus.similitudo, 'amantur / amant'), _c('v.des.pass.3.sg.tur', Modus.analogia, 'amantur / amātur')]),

  // =====================================================================
  // Désinences du parfait
  // =====================================================================
  _e('v.des.perf.1.sg.i', 'Dēsinentia perfectī -ī (1 sg)', 'Reconnaître -ī comme 1re personne du singulier du parfait (amāvī, rēxī).',
      not: ['not.persona.1', 'not.numerus.sg', 'not.tempus.perf'], parens: 'v.des', ag: ['§163 b'], prob: [Dimensio.persona, Dimensio.tempus, Dimensio.personaNumerus],
      conf: [_c('v.sig.inf.praes.pass.i', Modus.similitudo, 'rēxī / regī'), _c('v.des.act.1.sg.o', Modus.analogia, 'amāvī / amō')]),
  _e('v.des.perf.2.sg.isti', 'Dēsinentia perfectī -istī (2 sg)', 'Reconnaître -istī comme 2e personne du singulier du parfait (amāvistī).',
      not: ['not.persona.2', 'not.numerus.sg', 'not.tempus.perf'], parens: 'v.des', ag: ['§163 b'], prob: [Dimensio.persona, Dimensio.personaNumerus],
      conf: [_c('v.des.perf.2.pl.istis', Modus.similitudo, 'amāvistī / amāvistis'), _c('v.des.act.2.sg.s', Modus.analogia, 'amāvistī / amās')]),
  _e('v.des.perf.3.sg.it', 'Dēsinentia perfectī -it (3 sg)', 'Reconnaître -it comme 3e personne du singulier du parfait (amāvit, vēnit) : même désinence qu\'au présent de la 3e/4e (regit, venit).',
      not: ['not.persona.3', 'not.numerus.sg', 'not.tempus.perf'], parens: 'v.des', ag: ['§163 b'], prob: [Dimensio.persona, Dimensio.tempus],
      conf: [_c('v.des.act.3.sg.t', Modus.syncretismus, 'vēnit / venit : la désinence ne distingue pas, le radical oui')]),
  _e('v.des.perf.1.pl.imus', 'Dēsinentia perfectī -imus (1 pl)', 'Reconnaître -imus comme 1re personne du pluriel du parfait (amāvimus) ; identique au présent de la 3e (regimus).',
      not: ['not.persona.1', 'not.numerus.pl', 'not.tempus.perf'], parens: 'v.des', ag: ['§163 b'], prob: [Dimensio.persona, Dimensio.tempus],
      conf: [_c('v.des.act.1.pl.mus', Modus.syncretismus, 'amāvimus / regimus')]),
  _e('v.des.perf.2.pl.istis', 'Dēsinentia perfectī -istis (2 pl)', 'Reconnaître -istis comme 2e personne du pluriel du parfait (amāvistis).',
      not: ['not.persona.2', 'not.numerus.pl', 'not.tempus.perf'], parens: 'v.des', ag: ['§163 b'], prob: [Dimensio.persona, Dimensio.personaNumerus],
      conf: [_c('v.des.perf.2.sg.isti', Modus.similitudo, 'amāvistis / amāvistī'), _c('v.des.act.2.pl.tis', Modus.similitudo, 'amāvistis / amātis')]),
  _e('v.des.perf.3.pl.erunt', 'Dēsinentia perfectī -ērunt, -ēre (3 pl)', 'Reconnaître -ērunt (et -ēre) comme 3e personne du pluriel du parfait (amāvērunt, amāvēre).',
      not: ['not.persona.3', 'not.numerus.pl', 'not.tempus.perf'], parens: 'v.des', ag: ['§163 b'], prob: [Dimensio.persona, Dimensio.tempus, Dimensio.personaNumerus],
      conf: [_c('v.anom.sum.fut', Modus.similitudo, 'amāvērunt / erunt'), _c('v.sig.inf.praes.act.re', Modus.similitudo, 'amāvēre (3 pl) / amāre'), _c('v.sig.futex.eri', Modus.similitudo, 'amāvērunt / amāverint')]),

  // =====================================================================
  // Désinences de l'impératif
  // =====================================================================
  _e('v.des.imp.2.sg', 'Imperātīvus 2 sg: thema nūdum', 'Reconnaître la 2e sg de l\'impératif présent actif : le radical sans désinence (amā, monē, rege, audī ; dīc, dūc, fac, fer).',
      not: ['not.modus.imp', 'not.persona.2', 'not.numerus.sg'], parens: 'v.des', ag: ['§182', '§182 b'], req: ['v.sig.imp.praes'], prob: [Dimensio.modus, Dimensio.numerus],
      conf: [_c('v.des.imp.2.pl.te', Modus.analogia, 'amā / amāte')]),
  _e('v.des.imp.2.pl.te', 'Imperātīvus 2 pl: -te', 'Reconnaître -te comme 2e pluriel de l\'impératif présent actif (amāte, regite).',
      not: ['not.modus.imp', 'not.persona.2', 'not.numerus.pl'], parens: 'v.des', ag: ['§182'], req: ['v.sig.imp.praes'], prob: [Dimensio.modus, Dimensio.numerus],
      conf: [_c('v.des.imp.2.sg', Modus.analogia, 'amāte / amā'), _c('v.des.act.2.pl.tis', Modus.similitudo, 'amāte / amātis')]),
  _e('v.des.imp.pass.2.sg.re', 'Imperātīvus passīvus 2 sg: -re', 'Reconnaître -re comme impératif passif 2e sg (amāre, sequere) : identique à l\'infinitif actif.',
      not: ['not.modus.imp', 'not.vox.pass', 'not.persona.2', 'not.numerus.sg'], parens: 'v.des', ag: ['§182'], req: ['v.sig.imp.praes'], prob: [Dimensio.modus, Dimensio.vox],
      conf: [_c('v.sig.inf.praes.act.re', Modus.syncretismus, 'sequere / amāre'), _c('v.alt.re', Modus.syncretismus, 'amāre : impératif ou 2 sg passive en -re')]),
  _e('v.des.imp.pass.2.pl.mini', 'Imperātīvus passīvus 2 pl: -minī', 'Reconnaître -minī comme impératif passif 2e pl (amāminī, sequiminī) : identique à l\'indicatif.',
      not: ['not.modus.imp', 'not.vox.pass', 'not.persona.2', 'not.numerus.pl'], parens: 'v.des', ag: ['§182'], req: ['v.sig.imp.praes'], prob: [Dimensio.modus, Dimensio.vox],
      conf: [_c('v.des.pass.2.pl.mini', Modus.syncretismus, 'sequiminī : indicatif ou impératif')]),

  _e('v.des.imp.fut.2.sg.to', 'Imperātīvus futūrus 2 sg: -tō', 'Reconnaître -tō comme 2e sg de l\'impératif futur (amātō : tu devras aimer).',
      not: ['not.modus.imp', 'not.tempus.fut', 'not.persona.2', 'not.numerus.sg'], parens: 'v.des', ag: ['§182', '§449'], req: ['v.sig.imp.fut.to'], prob: [Dimensio.persona, Dimensio.numerus],
      conf: [_c('v.des.imp.fut.3.sg.to', Modus.syncretismus, 'amātō : 2e ou 3e sg')]),
  _e('v.des.imp.fut.3.sg.to', 'Imperātīvus futūrus 3 sg: -tō', 'Reconnaître -tō comme 3e sg de l\'impératif futur (amātō : qu\'il aime).',
      not: ['not.modus.imp', 'not.tempus.fut', 'not.persona.3', 'not.numerus.sg'], parens: 'v.des', ag: ['§182', '§449'], req: ['v.sig.imp.fut.to'], prob: [Dimensio.persona, Dimensio.numerus]),
  _e('v.des.imp.fut.2.pl.tote', 'Imperātīvus futūrus 2 pl: -tōte', 'Reconnaître -tōte comme 2e pl de l\'impératif futur (amātōte).',
      not: ['not.modus.imp', 'not.tempus.fut', 'not.persona.2', 'not.numerus.pl'], parens: 'v.des', ag: ['§182', '§449'], req: ['v.sig.imp.fut.to'], prob: [Dimensio.persona, Dimensio.numerus],
      conf: [_c('v.des.imp.2.pl.te', Modus.similitudo, 'amātōte / amāte')]),
  _e('v.des.imp.fut.3.pl.nto', 'Imperātīvus futūrus 3 pl: -ntō', 'Reconnaître -ntō comme 3e pl de l\'impératif futur (amantō).',
      not: ['not.modus.imp', 'not.tempus.fut', 'not.persona.3', 'not.numerus.pl'], parens: 'v.des', ag: ['§182', '§449'], req: ['v.sig.imp.fut.to'], prob: [Dimensio.persona, Dimensio.numerus],
      conf: [_c('v.des.act.3.pl.nt', Modus.similitudo, 'amantō / amant')]),
  _e('v.des.imp.fut.pass.2.sg.tor', 'Imperātīvus futūrus passīvus 2/3 sg: -tor', 'Reconnaître -tor comme impératif futur passif (amātor).',
      not: ['not.modus.imp', 'not.tempus.fut', 'not.vox.pass', 'not.numerus.sg'], parens: 'v.des', ag: ['§182', '§449'], req: ['v.sig.imp.fut.to'], prob: [Dimensio.vox, Dimensio.numerus],
      conf: [_c('v.des.imp.fut.2.sg.to', Modus.similitudo, 'amātor / amātō'), _c('lect.vocabula.suffixa', Modus.similitudo, 'amātor : impératif ou nom d\'agent en -tor')]),
  _e('v.des.imp.fut.pass.3.pl.ntor', 'Imperātīvus futūrus passīvus 3 pl: -ntor', 'Reconnaître -ntor comme 3e pl de l\'impératif futur passif (amantor).',
      not: ['not.modus.imp', 'not.tempus.fut', 'not.vox.pass', 'not.numerus.pl'], parens: 'v.des', ag: ['§182', '§449'], req: ['v.sig.imp.fut.to'], prob: [Dimensio.vox, Dimensio.numerus]),

  // =====================================================================
  // Alternances et variantes
  // =====================================================================
  _e('v.alt.quantitas', 'Quantitās vōcālium distinctīva', 'Lire la quantité quand elle seule distingue deux formes : venit / vēnit, amāveris / amāverīs, legit / lēgit.',
      not: ['not.tempus'], parens: 'v.alt', ag: ['§10', '§177 d'], prob: [Dimensio.tempus, Dimensio.tempusModus]),
  _e('v.alt.re', 'Fōrma passīva altera in -re', 'Reconnaître -re comme variante de -ris à la 2e sg passive (amābāre = amābāris).',
      not: ['not.persona.2', 'not.vox.pass'], parens: 'v.alt', ag: ['§163 b n.'], req: ['v.des.pass.2.sg.ris'], prob: [Dimensio.persona, Dimensio.vox],
      conf: [_c('v.sig.inf.praes.act.re', Modus.syncretismus, 'amāre : infinitif ou 2 sg passive'), _c('v.des.imp.pass.2.sg.re', Modus.syncretismus, 'amāre')]),
  _e('v.alt.syncopa', 'Fōrmae contractae perfectī', 'Reconnaître les parfaits contractés : amāsse (= amāvisse), amārunt (= amāvērunt), audiit (= audīvit).',
      not: ['not.tempus.perf'], parens: 'v.alt', ag: ['§181'], req: ['v.thema.perf.v'], prob: [Dimensio.tempus, Dimensio.formaPlena],
      conf: [_c('v.sig.inf.praes.act.re', Modus.similitudo, 'amāsse / amāre'), _c('v.des.act.3.pl.nt', Modus.similitudo, 'amārunt / amant')]),
  _e('v.alt.ere', 'Perfectum in -ēre', 'Reconnaître -ēre comme variante de -ērunt (amāvēre = amāvērunt).',
      not: ['not.tempus.perf', 'not.persona.3', 'not.numerus.pl'], parens: 'v.alt', ag: ['§163 b n.'], req: ['v.des.perf.3.pl.erunt'], prob: [Dimensio.persona, Dimensio.tempus],
      conf: [_c('v.sig.inf.praes.act.re', Modus.similitudo, 'amāvēre / amāre'), _c('v.thema.praes.c2', Modus.similitudo, 'dīxēre / monēre')]),
  _e('v.alt.fui', 'Auxiliāre fuī in compositīs', 'Reconnaître amātus fuit, fuerat comme variantes du parfait et du plus-que-parfait passifs.',
      not: ['not.tempus.perf', 'not.vox.pass'], parens: 'v.alt', ag: ['§184 n.'], req: ['v.comp.aux.tempus'], prob: [Dimensio.tempus]),
  _e('v.alt.forem', 'Forem, fore', 'Reconnaître forem (= essem) et fore (= futūrum esse).',
      not: ['not.modus.subj', 'not.modus.inf'], parens: 'v.alt', ag: ['§170 a'], req: ['v.anom.sum.subj'], prob: [Dimensio.tempusModus]),
  _e('v.alt.undus', 'Gerundīvum in -undus', 'Reconnaître -undus (dīcundus, faciundus) comme variante de -endus.',
      not: ['not.forma.gdv'], parens: 'v.alt', ag: ['§ 190 n.'], req: ['v.nom.gdv.ndus'], prob: [Dimensio.forma]),

  // =====================================================================
  // Genres de verbes
  // =====================================================================
  _e('v.kind.dep', 'Verba dēpōnentia', 'Reconnaître un déponent : forme passive, sens actif (sequitur = il suit) ; ne pas le traduire au passif.',
      not: ['not.vox.dep'], parens: 'v.kind', ag: ['§190'], req: ['v.des.pass.3.sg.tur'], prob: [Dimensio.vox, Dimensio.voxSensus, Dimensio.lemma],
      conf: [_c('not.vox.pass', Modus.analogia, 'sequitur lu « il est suivi »')]),
  _e('v.kind.dep.part', 'Participia dēpōnentium', 'Savoir que le déponent a un participe présent actif (sequēns), un participe parfait à sens actif (secūtus) et un gerundīvum à sens passif (sequendus).',
      not: ['not.vox.dep', 'not.forma.part'], parens: 'v.kind', ag: ['§190 a-b'], req: ['v.kind.dep', 'v.nom.part.perf.tus'], prob: [Dimensio.voxSensus, Dimensio.forma],
      conf: [_c('v.nom.part.perf.tus', Modus.analogia, 'secūtus « ayant suivi », non « suivi »')]),
  _e('v.kind.semidep', 'Verba sēmidēpōnentia', 'Reconnaître audeō, gaudeō, soleō, fīdō : actifs au système du présent, déponents au parfait (ausus sum).',
      not: ['not.vox.dep'], parens: 'v.kind', ag: ['§192'], req: ['v.kind.dep'], prob: [Dimensio.vox, Dimensio.voxSensus, Dimensio.tempus],
      conf: [_c('v.comp.perf.pass', Modus.analogia, 'ausus est lu au passif')]),
  _e('v.kind.semidep.inv', 'Sēmidēpōnentia inversa', 'Reconnaître revertor, revertī : déponent au présent, actif au parfait.',
      not: ['not.vox.dep'], parens: 'v.kind', ag: ['§192 n.'], req: ['v.kind.semidep'], prob: [Dimensio.voxSensus]),
  _e('v.kind.def', 'Verba dēfectīva: perfectum praesentis sēnsū', 'Reconnaître ōdī, meminī, nōvī : forme de parfait, sens présent ; plus-que-parfait = imparfait.',
      not: ['not.tempus.perf'], parens: 'v.kind', ag: ['§205'], req: ['v.sig.perf'], prob: [Dimensio.tempusSensus, Dimensio.tempus],
      conf: [_c('not.tempus.perf', Modus.analogia, 'ōdī lu « j\'ai haï »')]),
  _e('v.kind.def.coepi', 'Coepī, incipiō', 'Savoir que coepī n\'a que le système du parfait et se complète par incipiō.',
      not: ['not.tempus.perf'], parens: 'v.kind', ag: ['§205 a'], req: ['v.kind.def'], prob: [Dimensio.tempus, Dimensio.lemma]),
  _e('v.kind.def.inquam', 'Inquam, āiō', 'Reconnaître les formes de inquam, inquit et de āiō, ait (verbes de parole défectifs).',
      not: [], parens: 'v.kind', ag: ['§206'], req: ['v.kind.def'], prob: [Dimensio.lemma, Dimensio.persona]),
  _e('v.kind.impers', 'Verba impersōnālia', 'Reconnaître licet, oportet, decet, libet, pluit : 3e sg seule, sujet en infinitif ou proposition.',
      not: ['not.persona.3'], parens: 'v.kind', ag: ['§207–208'], prob: [Dimensio.persona, Dimensio.lemma]),
  _e('v.kind.impers.pass', 'Passīvum impersōnāle', 'Reconnaître le passif impersonnel des intransitifs (pugnātur, ītur, ventum est) : « on combat », « on va ».',
      not: ['not.vox.pass', 'not.persona.3'], parens: 'v.kind', ag: ['§208 d'], req: ['v.des.pass.3.sg.tur'], prob: [Dimensio.vox, Dimensio.voxSensus],
      conf: [_c('v.des.pass.3.sg.tur', Modus.functio, 'pugnātur n\'a pas de sujet « il »')]),
  _e('v.kind.comp', 'Verba composita', 'Retrouver le verbe simple sous le préverbe (ab-eō, au-ferō, re-deō, prō-sum) et y appliquer la conjugaison du simple.',
      not: [], parens: 'v.kind', ag: ['§267'], prob: [Dimensio.lemma, Dimensio.coniugatio]),

  // =====================================================================
  // Verbes anomaux
  // =====================================================================
  _e('v.anom.sum.praes', 'Sum: praesēns indicātīvī', 'Reconnaître sum, es, est, sumus, estis, sunt.',
      not: ['not.coniugatio.anom', 'not.tempus.praes'], parens: 'v.anom', ag: ['§170'], prob: [Dimensio.persona, Dimensio.personaNumerus, Dimensio.tempus],
      conf: [_c('v.anom.edo.praes', Modus.syncretismus, 'es, est / ēs, ēst'), _c('v.anom.possum.praes', Modus.similitudo, 'est / potest')]),
  _e('v.anom.sum.imperf', 'Sum: eram', 'Reconnaître eram, erās, erat… comme imparfait de sum.',
      not: ['not.coniugatio.anom', 'not.tempus.imperf'], parens: 'v.anom', ag: ['§170'], req: ['v.anom.sum.praes'], prob: [Dimensio.tempus, Dimensio.persona],
      conf: [_c('v.anom.sum.fut', Modus.similitudo, 'erat / erit'), _c('v.sig.plusq.era', Modus.similitudo, 'erat / amāverat')]),
  _e('v.anom.sum.fut', 'Sum: erō', 'Reconnaître erō, eris, erit… comme futur de sum.',
      not: ['not.coniugatio.anom', 'not.tempus.fut'], parens: 'v.anom', ag: ['§170'], req: ['v.anom.sum.praes'], prob: [Dimensio.tempus, Dimensio.persona],
      conf: [_c('v.anom.sum.imperf', Modus.similitudo, 'erit / erat'), _c('v.sig.futex.eri', Modus.similitudo, 'erit / amāverit')]),
  _e('v.anom.sum.subj', 'Sum: sim, essem', 'Reconnaître sim, sīs, sit et essem, essēs, esset comme subjonctifs de sum.',
      not: ['not.coniugatio.anom', 'not.modus.subj'], parens: 'v.anom', ag: ['§170'], req: ['v.anom.sum.praes'], prob: [Dimensio.tempusModus, Dimensio.modus],
      conf: [_c('v.anom.sum.inf', Modus.similitudo, 'esset / esse'), _c('v.alt.forem', Modus.syncretismus, 'essem / forem')]),
  _e('v.anom.sum.perf', 'Sum: fuī', 'Reconnaître fuī, fueram, fuerō, fuerim, fuissem : le parfait de sum sur le radical fu-.',
      not: ['not.coniugatio.anom', 'not.tempus.systema.perf'], parens: 'v.anom', ag: ['§170'], req: ['v.anom.sum.praes', 'v.sig.perf'], prob: [Dimensio.tempus, Dimensio.tempusModus]),
  _e('v.anom.sum.inf', 'Sum: esse, fuisse, futūrum esse', 'Reconnaître esse, fuisse, futūrum esse (fore) comme infinitifs de sum.',
      not: ['not.coniugatio.anom', 'not.modus.inf'], parens: 'v.anom', ag: ['§170'], req: ['v.anom.sum.praes'], prob: [Dimensio.tempus, Dimensio.forma],
      conf: [_c('v.anom.edo.inf', Modus.syncretismus, 'esse / ēsse')]),
  _e('v.anom.sum.imp', 'Sum: es, este, estō', 'Reconnaître es, este (impératif présent), estō, estōte, suntō (futur).',
      not: ['not.coniugatio.anom', 'not.modus.imp'], parens: 'v.anom', ag: ['§170'], req: ['v.anom.sum.praes'], prob: [Dimensio.modus],
      conf: [_c('v.anom.sum.praes', Modus.syncretismus, 'es : indicatif 2 sg ou impératif')]),
  _e('v.anom.possum', 'Possum: pot-/pos-', 'Reconnaître possum, potes, potest, possumus, potestis, possunt : pot- devant voyelle, pos- devant s ; posse, potuī.',
      not: ['not.coniugatio.anom'], parens: 'v.anom', ag: ['§198'], req: ['v.anom.sum.praes'], prob: [Dimensio.persona, Dimensio.tempus, Dimensio.lemma],
      conf: [_c('v.anom.sum.praes', Modus.similitudo, 'potest / est')]),
  _e('v.anom.possum.praes', 'Possum: praesēns', 'Reconnaître les formes du présent de possum (possum, potes, potest…).',
      not: ['not.coniugatio.anom', 'not.tempus.praes'], parens: 'v.anom', ag: ['§198'], req: ['v.anom.possum'], prob: [Dimensio.persona, Dimensio.personaNumerus], visibilis: false),
  _e('v.anom.eo.praes', 'Eō: eō, īs, it, eunt', 'Reconnaître eō, īs, it, īmus, ītis, eunt : radical ī-/e-.',
      not: ['not.coniugatio.anom', 'not.tempus.praes'], parens: 'v.anom', ag: ['§203'], prob: [Dimensio.persona, Dimensio.lemma, Dimensio.tempus],
      conf: [_c('v.voc.i_long', Modus.analogia, 'īs, it comme audīs, audit'), _c('v.des.act.3.pl.nt', Modus.analogia, 'eunt : -unt sur radical e-')]),
  _e('v.anom.eo.imperf', 'Eō: ībam', 'Reconnaître ībam, ībās, ībat… comme imparfait de eō (-bā- sur le radical ī-).',
      not: ['not.coniugatio.anom', 'not.tempus.imperf'], parens: 'v.anom', ag: ['§203'], req: ['v.anom.eo.praes', 'v.sig.imperf.ba'], prob: [Dimensio.tempus],
      conf: [_c('v.anom.eo.fut', Modus.similitudo, 'ībat / ībit')]),
  _e('v.anom.eo.fut', 'Eō: ībō', 'Reconnaître ībō, ībis, ībit… comme futur de eō : -b- comme les 1re et 2e conjugaisons, non *iam.',
      not: ['not.coniugatio.anom', 'not.tempus.fut'], parens: 'v.anom', ag: ['§203'], req: ['v.anom.eo.praes', 'v.sig.fut.b'], prob: [Dimensio.tempus],
      conf: [_c('v.sig.fut.a_e', Modus.analogia, 'ībō, non *iam'), _c('v.anom.eo.imperf', Modus.similitudo, 'ībit / ībat')]),
  _e('v.anom.eo.subj', 'Eō: eam, īrem', 'Reconnaître eam, eās, eat (subjonctif présent) et īrem (imparfait).',
      not: ['not.coniugatio.anom', 'not.modus.subj'], parens: 'v.anom', ag: ['§203'], req: ['v.anom.eo.praes'], prob: [Dimensio.modus, Dimensio.tempusModus],
      conf: [_c('pron.is', Modus.syncretismus, 'eam : subjonctif de eō ou accusatif de is, ea, id ; eā, eī, eō de même')]),
  _e('v.anom.eo.perf', 'Eō: iī, īvī', 'Reconnaître iī (īvī), iistī, iit, iimus, iistis, iērunt ; īsse.',
      not: ['not.coniugatio.anom', 'not.tempus.systema.perf'], parens: 'v.anom', ag: ['§203'], req: ['v.anom.eo.praes', 'v.sig.perf'], prob: [Dimensio.tempus, Dimensio.persona]),
  _e('v.anom.eo.inf', 'Eō: īre, ītum, eundum', 'Reconnaître īre, ītum īrī, iēns/euntis, eundum (gérondif en eu-).',
      not: ['not.coniugatio.anom', 'not.modus.inf', 'not.forma'], parens: 'v.anom', ag: ['§203'], req: ['v.anom.eo.praes'], prob: [Dimensio.forma, Dimensio.tempus]),
  _e('v.anom.eo.comp', 'Composita verbī eō', 'Reconnaître les composés de eō : abeō, adeō, exeō, redeō, trānseō, pereō ; parfait en -iī.',
      not: ['not.coniugatio.anom'], parens: 'v.anom', ag: ['§203 a'], req: ['v.anom.eo.praes', 'v.kind.comp'], prob: [Dimensio.lemma]),
  _e('v.anom.fero.praes', 'Ferō: fers, fert, fertur', 'Reconnaître les formes athématiques de ferō : fers, fert, fertis ; fertur, ferris ; fer, ferte ; ferre, ferrī.',
      not: ['not.coniugatio.anom', 'not.tempus.praes'], parens: 'v.anom', ag: ['§200'], prob: [Dimensio.persona, Dimensio.lemma, Dimensio.vox],
      conf: [_c('v.voc.i_u', Modus.analogia, 'fers, non *feris ; fert, non *ferit'), _c('v.sig.inf.praes.act.re', Modus.analogia, 'ferre, non *ferere')]),
  _e('v.anom.fero.perf', 'Ferō: tulī, lātum', 'Reconnaître tulī, tulistī… et lātus comme parfait et participe de ferō (radicaux différents).',
      not: ['not.coniugatio.anom', 'not.tempus.systema.perf'], parens: 'v.anom', ag: ['§200'], req: ['v.anom.fero.praes'], prob: [Dimensio.lemma, Dimensio.tempus]),
  _e('v.anom.fero.comp', 'Composita verbī ferō', 'Reconnaître auferō (abstulī, ablātum), afferō (attulī, allātum), referō, offerō, differō : assimilation du préverbe.',
      not: ['not.coniugatio.anom'], parens: 'v.anom', ag: ['§200 a'], req: ['v.anom.fero.praes', 'v.kind.comp'], prob: [Dimensio.lemma]),
  _e('v.anom.volo.praes', 'Volō: vīs, vult, volunt', 'Reconnaître volō, vīs, vult, volumus, vultis, volunt ; velle, velim, vellem, voluī.',
      not: ['not.coniugatio.anom', 'not.tempus.praes'], parens: 'v.anom', ag: ['§199'], prob: [Dimensio.persona, Dimensio.lemma, Dimensio.tempusModus],
      conf: [_c('v.anom.nolo', Modus.similitudo, 'vult / nōn vult'), _c('v.anom.malo', Modus.similitudo, 'vult / māvult')]),
  _e('v.anom.nolo', 'Nōlō', 'Reconnaître nōlō, nōn vīs, nōn vult, nōlumus, nōn vultis, nōlunt ; nōlle ; nōlī, nōlīte + infinitif (défense).',
      not: ['not.coniugatio.anom'], parens: 'v.anom', ag: ['§199'], req: ['v.anom.volo.praes'], prob: [Dimensio.persona, Dimensio.lemma, Dimensio.modus],
      conf: [_c('v.anom.volo.praes', Modus.similitudo, 'nōn vult / vult')]),
  _e('v.anom.malo', 'Mālō', 'Reconnaître mālō, māvīs, māvult, mālumus, māvultis, mālunt ; mālle ; māluī.',
      not: ['not.coniugatio.anom'], parens: 'v.anom', ag: ['§199'], req: ['v.anom.volo.praes'], prob: [Dimensio.persona, Dimensio.lemma],
      conf: [_c('v.anom.volo.praes', Modus.similitudo, 'māvult / vult')]),
  _e('v.anom.fio', 'Fīō: passīvum verbī faciō', 'Reconnaître fīō, fīs, fit, fīunt ; fīēbam, fīam ; fierī ; factus sum : le passif de faciō a la forme active fīō au système du présent.',
      not: ['not.coniugatio.anom', 'not.vox.pass'], parens: 'v.anom', ag: ['§204'], prob: [Dimensio.vox, Dimensio.voxSensus, Dimensio.lemma, Dimensio.tempus],
      conf: [_c('v.voc.i_long', Modus.analogia, 'fīs, fit comme la 4e'), _c('not.vox.act', Modus.analogia, 'fit lu comme un actif')]),
  _e('v.anom.do', 'Dō: dās, damus, dăre', 'Reconnaître dō : -a- bref (dăs, dămus, dăre, dăbam) ; dedī, dătum ; composés circumdō (1re) et crēdō, reddō (3e).',
      not: ['not.coniugatio.anom', 'not.coniugatio.1'], parens: 'v.anom', ag: ['§202'], prob: [Dimensio.coniugatio, Dimensio.lemma, Dimensio.tempus],
      conf: [_c('v.voc.a', Modus.analogia, 'dăs / amās : quantité'), _c('v.thema.perf.redup', Modus.similitudo, 'dedī')]),
  _e('v.anom.edo.praes', 'Edō: ēs, ēst, ēsse', 'Reconnaître les formes de edō homographes de sum sauf la quantité : ēs, ēst, ēstis, ēsse, ēssem.',
      not: ['not.coniugatio.anom', 'not.tempus.praes'], parens: 'v.anom', ag: ['§201'], prob: [Dimensio.lemma, Dimensio.persona],
      conf: [_c('v.anom.sum.praes', Modus.syncretismus, 'ēst / est')]),
  _e('v.anom.edo.inf', 'Edō: ēsse', 'Reconnaître ēsse (manger) face à esse (être).',
      not: ['not.coniugatio.anom', 'not.modus.inf'], parens: 'v.anom', ag: ['§201'], req: ['v.anom.edo.praes'], prob: [Dimensio.lemma],
      conf: [_c('v.anom.sum.inf', Modus.syncretismus, 'ēsse / esse')]),
];
